# SPDX-License-Identifier: GPL-2.0-only
HL_GAUDI_FILES := gaudi/gaudi.o gaudi/gaudi_security.o \
	gaudi/gaudi_coresight.o

HL_GAUDI_FILES += gaudi/gaudi_nic.o gaudi/gaudi_nic_debugfs.o \
	gaudi/gaudi_bringup.o gaudi/gaudi_simulator.o gaudi/gaudi_nic_phy.o \
	gaudi/gaudi_security_emulation.o
