# SPDX-License-Identifier: GPL-2.0-only

# Goes upstream
HL_GAUDI2_FILES := gaudi2/gaudi2.o gaudi2/gaudi2_security.o \
		gaudi2/gaudi2_coresight.o

# Doesn't go upstream
HL_GAUDI2_FILES += gaudi2/gaudi2_simulator.o gaudi2/gaudi2_nic.o \
		gaudi2/gaudi2_bringup.o gaudi2/gaudi2_nic_debugfs.o \
		gaudi2/gaudi2_nic_eq.o gaudi2/gaudi2_fpga.o \
		gaudi2/gaudi2_hbm_bringup.o gaudi2/gaudi2_nic_phy.o \
		gaudi2/gaudi2_nic_bringup.o
