/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

#ifndef GAUDI3_MASKS_H_
#define GAUDI3_MASKS_H_

#include "../include/gaudi3/asic_reg/gaudi3_regs.h"

#define PLL_DIV_CFG_FBDIV_MASK		GENMASK(11, 0)
#define PLL_DIV_CFG_POSTDIV1_MASK	GENMASK(18, 16)
#define PLL_DIV_CFG_POSTDIV2_MASK	GENMASK(22, 20)
#define PLL_DIV_CFG_REFDIV_MASK		GENMASK(29, 24)
#define PLL_CTRL_DIV_SEL_REF_CLK		0
#define PLL_CTRL_DIV_SEL_PLL_CLK		1
#define PLL_CTRL_DIV_SEL_DIVIDED_REF_CLK	2
#define PLL_CTRL_DIV_SEL_DIVIDED_PLL_CLK	3

#define TPC_INTR_MASK_0_HBW_DCACHE_L0CD_MISMATCH_SHIFT		14
#define TPC_INTR_MASK_0_HBW_INVALID_LOCK_ACCESS_SHIFT		13
#define TPC_INTR_MASK_0_HBW_ST_UNLOCK_ALREADY_UNLOCKED_SHIFT	12
#define TPC_INTR_MASK_0_HBW_LBW_TPC_MSTR_BRESP_ERR_SHIFT	11
#define TPC_INTR_MASK_0_HBW_LBW_TPC_MSTR_RRESP_ERR_SHIFT	10
#define TPC_INTR_MASK_0_HBW_TPC_MSTR_BRESP_ERR_SHIFT		9
#define TPC_INTR_MASK_0_HBW_TPC_MSTR_RRESP_ERR_SHIFT		8
#define TPC_INTR_MASK_0_HBW_TPC_SPU_AGU_IRF44_SAT_IND_SHIFT	7
#define TPC_INTR_MASK_0_HBW_TSB_ERR_IND_NUM_SHIFT		6
#define TPC_INTR_MASK_0_HBW_TSB_ERR_IND_RR_DBG_SHIFT		5
#define TPC_INTR_MASK_0_HBW_TSB_SLV_ERR_IND_SHIFT		4
#define TPC_INTR_MASK_0_HBW_TPC_DCACHE_RR_DBG_ERR_SHIFT		3
#define TPC_INTR_MASK_0_HBW_WQ_MEM_RR_DBG_ERR_SHIFT		2
#define TPC_INTR_MASK_0_HBW_WQ_MEM_NUM_ERR_SHIFT		1
#define TPC_INTR_MASK_0_HBW_TPC_QM_SW_ERR_SHIFT			0

#define TPC_INTR_MASK_0_MASK \
		((0x0 << TPC_INTR_MASK_0_HBW_DCACHE_L0CD_MISMATCH_SHIFT) | \
		(0x0 << TPC_INTR_MASK_0_HBW_INVALID_LOCK_ACCESS_SHIFT) | \
		(0x0 << TPC_INTR_MASK_0_HBW_ST_UNLOCK_ALREADY_UNLOCKED_SHIFT) | \
		(0x0 << TPC_INTR_MASK_0_HBW_LBW_TPC_MSTR_BRESP_ERR_SHIFT) | \
		(0x0 << TPC_INTR_MASK_0_HBW_LBW_TPC_MSTR_RRESP_ERR_SHIFT) | \
		(0x0 << TPC_INTR_MASK_0_HBW_TPC_MSTR_BRESP_ERR_SHIFT) | \
		(0x0 << TPC_INTR_MASK_0_HBW_TPC_MSTR_RRESP_ERR_SHIFT) | \
		(0x0 << TPC_INTR_MASK_0_HBW_TPC_SPU_AGU_IRF44_SAT_IND_SHIFT) | \
		(0x1 << TPC_INTR_MASK_0_HBW_TSB_ERR_IND_NUM_SHIFT) | \
		(0x0 << TPC_INTR_MASK_0_HBW_TSB_ERR_IND_RR_DBG_SHIFT) | \
		(0x0 << TPC_INTR_MASK_0_HBW_TSB_SLV_ERR_IND_SHIFT) | \
		(0x0 << TPC_INTR_MASK_0_HBW_TPC_DCACHE_RR_DBG_ERR_SHIFT) | \
		(0x0 << TPC_INTR_MASK_0_HBW_WQ_MEM_RR_DBG_ERR_SHIFT) | \
		(0x0 << TPC_INTR_MASK_0_HBW_WQ_MEM_NUM_ERR_SHIFT) | \
		(0x1 << TPC_INTR_MASK_0_HBW_TPC_QM_SW_ERR_SHIFT))

#define TPC_TH_INTR_MASK_0_HBW_ST_L_PROT_VIO_SHIFT			26
#define TPC_TH_INTR_MASK_0_HBW_LD_L_PROT_VIO_SHIFT			25
#define TPC_TH_INTR_MASK_0_HBW_TPC_ADDRESS_EXCEED_VLM			24
#define TPC_TH_INTR_MASK_0_HBW_TPC_DCACHE_L1_DECREMENT_RST_EVENT_SHIFT	23
#define TPC_TH_INTR_MASK_0_HBW_TPC_DCACHE_L2_DECREMENT_RST_EVENT_SHIFT	22
#define TPC_TH_INTR_MASK_0_HBW_TPC_PC_WRAP_AROUND_SHIFT			21
#define TPC_TH_INTR_MASK_0_HBW_TPC_SQZ_OOB_PULSE_SHIFT			20
#define TPC_TH_INTR_MASK_0_HBW_TPC_SQZ_CNT_OVRFLOW_IND_PULSE_SHIFT	19
#define TPC_TH_INTR_MASK_0_HBW_TPC_VPU_FP_DST_DENORM_SHIFT		18
#define TPC_TH_INTR_MASK_0_HBW_TPC_VPU_FMA_FP_DST_INF_SHIFT		17
#define TPC_TH_INTR_MASK_0_HBW_TPC_VPU_FMA_FP_DST_NAN_SHIFT		16
#define TPC_TH_INTR_MASK_0_HBW_TPC_VPU_CONVERT_FP_DST_INF_SHIFT		15
#define TPC_TH_INTR_MASK_0_HBW_TPC_VPU_CONVERT_FP_DST_NAN_SHIFT		14
#define TPC_TH_INTR_MASK_0_HBW_TPC_VPU_ABS_OVERFLOW_SHIFT		13
#define TPC_TH_INTR_MASK_0_HBW_TPC_VPU_ADDSUB_OVERFLOW_SHIFT		12
#define TPC_TH_INTR_MASK_0_HBW_TPC_VPU_MAC_OVERFLOW_SHIFT		11
#define TPC_TH_INTR_MASK_0_HBW_TPC_SPU_FP_DST_DENORM_SHIFT		10
#define TPC_TH_INTR_MASK_0_HBW_TPC_SPU_CONVERT_FP_DST_INF_SHIFT		9
#define TPC_TH_INTR_MASK_0_HBW_TPC_SPU_CONVERT_FP_DST_NAN_SHIFT		8
#define TPC_TH_INTR_MASK_0_HBW_TPC_SPU_FMA_FP_DST_INF_SHIFT		7
#define TPC_TH_INTR_MASK_0_HBW_TPC_SPU_FMA_FP_DST_NAN_SHIFT		6
#define TPC_TH_INTR_MASK_0_HBW_TPC_SPU_ABS_OVERFLOW_SHIFT		5
#define TPC_TH_INTR_MASK_0_HBW_TPC_SPU_ADDSUB_OVERFLOW_SHIFT		4
#define TPC_TH_INTR_MASK_0_HBW_TPC_SPU_MAC_OVERFLOW_SHIFT		3
#define TPC_TH_INTR_MASK_0_HBW_TPC_DIV_BY_0_SHIFT			2
#define TPC_TH_INTR_MASK_0_HBW_TPC_ADDRESS_EXCEED_SLM_SHIFT		1
#define TPC_TH_INTR_MASK_0_HBW_TPC_ILLEGAL_INSTRUCTION_SHIFT		0

#define TPC_TH_INTR_MASK_0_MASK \
		((0x0 << TPC_TH_INTR_MASK_0_HBW_ST_L_PROT_VIO_SHIFT) | \
		(0x0 << TPC_TH_INTR_MASK_0_HBW_LD_L_PROT_VIO_SHIFT) | \
		(0x0 << TPC_TH_INTR_MASK_0_HBW_TPC_ADDRESS_EXCEED_VLM) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_DCACHE_L1_DECREMENT_RST_EVENT_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_DCACHE_L2_DECREMENT_RST_EVENT_SHIFT) | \
		(0x0 << TPC_TH_INTR_MASK_0_HBW_TPC_PC_WRAP_AROUND_SHIFT) | \
		(0x0 << TPC_TH_INTR_MASK_0_HBW_TPC_SQZ_OOB_PULSE_SHIFT) | \
		(0x0 << TPC_TH_INTR_MASK_0_HBW_TPC_SQZ_CNT_OVRFLOW_IND_PULSE_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_VPU_FP_DST_DENORM_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_VPU_FMA_FP_DST_INF_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_VPU_FMA_FP_DST_NAN_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_VPU_CONVERT_FP_DST_INF_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_VPU_CONVERT_FP_DST_NAN_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_VPU_ABS_OVERFLOW_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_VPU_ADDSUB_OVERFLOW_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_VPU_MAC_OVERFLOW_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_SPU_FP_DST_DENORM_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_SPU_CONVERT_FP_DST_INF_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_SPU_CONVERT_FP_DST_NAN_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_SPU_FMA_FP_DST_INF_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_SPU_FMA_FP_DST_NAN_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_SPU_ABS_OVERFLOW_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_SPU_ADDSUB_OVERFLOW_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_SPU_MAC_OVERFLOW_SHIFT) | \
		(0x1 << TPC_TH_INTR_MASK_0_HBW_TPC_DIV_BY_0_SHIFT) | \
		(0x0 << TPC_TH_INTR_MASK_0_HBW_TPC_ADDRESS_EXCEED_SLM_SHIFT) | \
		(0x0 << TPC_TH_INTR_MASK_0_HBW_TPC_ILLEGAL_INSTRUCTION_SHIFT))

#define MME_ACC_INTR_MASK_WBC_ERR_RESP_MASK			BIT(0)
#define MME_ACC_INTR_MASK_WBC_BUSER_SLV_ERR_MASK		BIT(1)
#define MME_ACC_INTR_MASK_WBC_BUSER_NUMERICAL_INF_ERR_MASK	BIT(2)
#define MME_ACC_INTR_MASK_WBC_BUSER_NUMERICAL_NINF_ERR_MASK	BIT(3)
#define MME_ACC_INTR_MASK_WBC_BUSER_NUMERICAL_NAN_ERR_MASK	BIT(4)
#define MME_ACC_INTR_MASK_WBC_BUSER_RR_DBG_ERR_MASK		BIT(5)
#define MME_ACC_INTR_MASK_AP_STS_SRC_DNRM_INTR_P_MASK		BIT(6)
#define MME_ACC_INTR_MASK_AP_STS_SRC_INF_INTR_P_MASK		BIT(7)
#define MME_ACC_INTR_MASK_AP_STS_SRC_NINF_INTR_P_MASK		BIT(8)
#define MME_ACC_INTR_MASK_AP_STS_SRC_NAN_INTR_P_MASK		BIT(9)
#define MME_ACC_INTR_MASK_AP_STS_RES_INF_INTR_P_MASK		BIT(10)
#define MME_ACC_INTR_MASK_AP_STS_RES_NINF_INTR_P_MASK		BIT(11)

#define ROT_MSS_HALT_WBC_MASK	BIT(0)
#define ROT_MSS_HALT_RSB_MASK	BIT(1)
#define ROT_MSS_HALT_MRSB_MASK	BIT(2)

#define PDMA_CH_B_ERR_ENABLE_MASK \
		((0x0 << PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_HBW_RD_RSP_ERR_S) | \
		(0x1 << PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_HBW_RD_RSP_ERR_S) | \
		(0x0 << PDMA_CH_B_ERR_ENABLE_EN_MSG_ENGINE_TIMEOUT_S) | \
		(0x1 << PDMA_CH_B_ERR_ENABLE_EN_STALL_ENGINE_TIMEOUT_S) | \
		(0x0 << PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_LBW_RD_RSP_ERR_S) | \
		(0x1 << PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_LBW_RD_RSP_ERR_S) | \
		(0x0 << PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_HBW_WR_RSP_ERR_S) | \
		(0x1 << PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_HBW_WR_RSP_ERR_S) | \
		(0x0 << PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_LBW_WR_RSP_ERR_S) | \
		(0x1 << PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_LBW_WR_RSP_ERR_S) | \
		(0x0 << PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_MSG_WR_ERR_S) | \
		(0x1 << PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_MSG_WR_ERR_S) | \
		(0x0 << PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_NAN_DETECT_S) | \
		(0x1 << PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_NAN_DETECT_S) | \
		(0x0 << PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_INF_DETECT_S) | \
		(0x1 << PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_INF_DETECT_S) | \
		(0x0 << PDMA_CH_B_ERR_ENABLE_EN_MSG_LBW_CH_NUM_EXCEED_S) | \
		(0x1 << PDMA_CH_B_ERR_ENABLE_EN_STL_LBW_CH_NUM_EXCEED_S) | \
		(0x0 << PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_SRC_RANGE_ERR_S) | \
		(0x1 << PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_SRC_RANGE_ERR_S) | \
		(0x0 << PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_DST_RANGE_ERR_S) | \
		(0x1 << PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_DST_RANGE_ERR_S) | \
		(0x0 << PDMA_CH_B_ERR_ENABLE_EN_MSG_DESC_OVF_ERR_S) | \
		(0x1 << PDMA_CH_B_ERR_ENABLE_EN_STL_DESC_OVF_ERR_S))

#define PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_MASK \
		((0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_CQ_RD_ERR_EN_S) | \
		(0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_CP_MSG_WR_ERR_EN_S) | \
		(0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_DESC_PTR_RLS_MSG_ERR_EN_S) | \
		(0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_CP_WREG_ERR_EN_S) | \
		(0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_CP_STOP_OP_EN_S) | \
		(0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_CP_UNDEF_CMD_ERR_EN_S) | \
		(0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_CQ_PTR_OVFL_EN_S) | \
		(0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_FENCE_UDF_ERR_EN_0_S) | \
		(0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_FENCE_UDF_ERR_EN_1_S) | \
		(0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_FENCE_UDF_ERR_EN_2_S) | \
		(0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_FENCE_UDF_ERR_EN_3_S) | \
		(0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_FENCE_OVF_ERR_EN_0_S) | \
		(0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_FENCE_OVF_ERR_EN_1_S) | \
		(0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_FENCE_OVF_ERR_EN_2_S) | \
		(0x1 << PDMA_CH_B_PQM_CH_ERR_STOP_ENABLE_FENCE_OVF_ERR_EN_3_S))

#define QMAN_ARC_AUX_RST_VEC_ADDR_REGION_M	0xF0000000

#define VDEC_BRDG_CTRL_CAUSE_INTR_SEI_M	(VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_VCD_HBW_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_L2C_HBW_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_NRM_HBW_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_ABNRM_HBW_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_VCD_LBW_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_L2C_LBW_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_NRM_LBW_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_ABNRM_LBW_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_APB_VCD_LBW_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_APB_L2C_LBW_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_APB_NRM_LBW_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_APB_ABNRM_LBW_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_DEC_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_DEC_APB_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_TRC_APB_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_LBW_MSTR_IF_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_AXI_SPLIT_BRESP_ERR_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_HBW_AXI_WR_VIOL_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_HBW_AXI_RD_VIOL_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_LBW_AXI_WR_VIOL_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_LBW_AXI_RD_VIOL_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_VCD_RR_DBG_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_L2C_RR_DBG_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_NRM_RR_DBG_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_ABNRM_RR_DBG_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_DEC_WR_RR_DBG_SEI_M | \
					VDEC_BRDG_CTRL_CAUSE_INTR_DEC_RD_RR_DBG_SEI_M)

#define TPC_SPI_INTR_MASK		0xFF
#define TPC_SMT_TH_SPI_INTR_MASK	0x1FFFFFF

#define TPC_SEI_INTR_MASK		0x7F00
#define TPC_SMT_TH_SEI_INTR_MASK	0x6000000

#endif /* GAUDI3_MASKS_H_ */
