# SPDX-License-Identifier: GPL-2.0-only
HL_GAUDI3_FILES := gaudi3/gaudi3.o gaudi3/gaudi3_coresight.o

# The following files should not be upstreamed, but untangling them
# is a separate task.
HL_GAUDI3_FILES += gaudi3/gaudi3_security.o gaudi3/gaudi3_axuser.o \
		gaudi3/gaudi3_cn.o
