/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2023 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_CACHE_ERR_MASKS_H_
#define ASIC_REG_CACHE_ERR_MASKS_H_

/*
 *****************************************
 *   CACHE_ERR
 *   (Prototype: CACHE_ERR_CAPTURE)
 *****************************************
 */

/* CACHE_ERR_NUM_ERR_FAR_HOST_A */
#define CACHE_ERR_NUM_ERR_FAR_HOST_A_NUM_ERR_S 0
#define CACHE_ERR_NUM_ERR_FAR_HOST_A_NUM_ERR_M 0x3
#define CACHE_ERR_NUM_ERR_FAR_HOST_A_USER_MSB_S 8
#define CACHE_ERR_NUM_ERR_FAR_HOST_A_USER_MSB_M 0xFF00
#define CACHE_ERR_NUM_ERR_FAR_HOST_A_ADDR_MSB_S 16
#define CACHE_ERR_NUM_ERR_FAR_HOST_A_ADDR_MSB_M 0xFF0000

/* CACHE_ERR_NUM_ERR_FAR_HOST_B */
#define CACHE_ERR_NUM_ERR_FAR_HOST_B_USER_LSB_S 0
#define CACHE_ERR_NUM_ERR_FAR_HOST_B_USER_LSB_M 0xFFFFFFFF

/* CACHE_ERR_NUM_ERR_FAR_HOST_C */
#define CACHE_ERR_NUM_ERR_FAR_HOST_C_ADDR_LSB_S 0
#define CACHE_ERR_NUM_ERR_FAR_HOST_C_ADDR_LSB_M 0xFFFFFFFF

/* CACHE_ERR_NUM_ERR_FAR_HOST_CLEAR */
#define CACHE_ERR_NUM_ERR_FAR_HOST_CLEAR_CLEAR_S 0
#define CACHE_ERR_NUM_ERR_FAR_HOST_CLEAR_CLEAR_M 0x1

/* CACHE_ERR_NUM_ERR_CLOSE_HOST_A */
#define CACHE_ERR_NUM_ERR_CLOSE_HOST_A_NUM_ERR_S 0
#define CACHE_ERR_NUM_ERR_CLOSE_HOST_A_NUM_ERR_M 0x3
#define CACHE_ERR_NUM_ERR_CLOSE_HOST_A_USER_MSB_S 8
#define CACHE_ERR_NUM_ERR_CLOSE_HOST_A_USER_MSB_M 0xFF00
#define CACHE_ERR_NUM_ERR_CLOSE_HOST_A_ADDR_MSB_S 16
#define CACHE_ERR_NUM_ERR_CLOSE_HOST_A_ADDR_MSB_M 0xFF0000

/* CACHE_ERR_NUM_ERR_CLOSE_HOST_B */
#define CACHE_ERR_NUM_ERR_CLOSE_HOST_B_USER_LSB_S 0
#define CACHE_ERR_NUM_ERR_CLOSE_HOST_B_USER_LSB_M 0xFFFFFFFF

/* CACHE_ERR_NUM_ERR_CLOSE_HOST_C */
#define CACHE_ERR_NUM_ERR_CLOSE_HOST_C_ADDR_LSB_S 0
#define CACHE_ERR_NUM_ERR_CLOSE_HOST_C_ADDR_LSB_M 0xFFFFFFFF

/* CACHE_ERR_NUM_ERR_CLOSE_HOST_CLEAR */
#define CACHE_ERR_NUM_ERR_CLOSE_HOST_CLEAR_CLEAR_S 0
#define CACHE_ERR_NUM_ERR_CLOSE_HOST_CLEAR_CLEAR_M 0x1

/* CACHE_ERR_NUM_ERR_AAB_A */
#define CACHE_ERR_NUM_ERR_AAB_A_NUM_ERR_S 0
#define CACHE_ERR_NUM_ERR_AAB_A_NUM_ERR_M 0x3

/* CACHE_ERR_NUM_ERR_AAB_CLEAR */
#define CACHE_ERR_NUM_ERR_AAB_CLEAR_CLEAR_S 0
#define CACHE_ERR_NUM_ERR_AAB_CLEAR_CLEAR_M 0x1

/* CACHE_ERR_SLV_ERR_ADDR_LSB */
#define CACHE_ERR_SLV_ERR_ADDR_LSB_VALUE_S 0
#define CACHE_ERR_SLV_ERR_ADDR_LSB_VALUE_M 0xFFFFFFFF

/* CACHE_ERR_SLV_ERR_ADDR_MSB */
#define CACHE_ERR_SLV_ERR_ADDR_MSB_VALUE_S 0
#define CACHE_ERR_SLV_ERR_ADDR_MSB_VALUE_M 0xFF

/* CACHE_ERR_POISON_INFO_A */
#define CACHE_ERR_POISON_INFO_A_LOCAL_AR_S 0
#define CACHE_ERR_POISON_INFO_A_LOCAL_AR_M 0x1
#define CACHE_ERR_POISON_INFO_A_LOCAL_AWW_S 1
#define CACHE_ERR_POISON_INFO_A_LOCAL_AWW_M 0x2
#define CACHE_ERR_POISON_INFO_A_LOCAL_WR_M_S 2
#define CACHE_ERR_POISON_INFO_A_LOCAL_WR_M_M 0x4
#define CACHE_ERR_POISON_INFO_A_REMOTE_AR_S 3
#define CACHE_ERR_POISON_INFO_A_REMOTE_AR_M 0x8
#define CACHE_ERR_POISON_INFO_A_REMOTE_AWW_S 4
#define CACHE_ERR_POISON_INFO_A_REMOTE_AWW_M 0x10
#define CACHE_ERR_POISON_INFO_A_ID_MSB_S 8
#define CACHE_ERR_POISON_INFO_A_ID_MSB_M 0xF00
#define CACHE_ERR_POISON_INFO_A_ADDR_MSB_S 16
#define CACHE_ERR_POISON_INFO_A_ADDR_MSB_M 0xFF0000

/* CACHE_ERR_POISON_INFO_B */
#define CACHE_ERR_POISON_INFO_B_ID_LSB_S 0
#define CACHE_ERR_POISON_INFO_B_ID_LSB_M 0xFFFFFFFF

/* CACHE_ERR_POISON_INFO_C */
#define CACHE_ERR_POISON_INFO_C_ADDR_LSB_S 0
#define CACHE_ERR_POISON_INFO_C_ADDR_LSB_M 0xFFFFFFFF

/* CACHE_ERR_POISON_INFO_CLEAR */
#define CACHE_ERR_POISON_INFO_CLEAR_CLEAR_S 0
#define CACHE_ERR_POISON_INFO_CLEAR_CLEAR_M 0x1

/* CACHE_ERR_DN_CONV_INFO_A */
#define CACHE_ERR_DN_CONV_INFO_A_ID_LSB_S 0
#define CACHE_ERR_DN_CONV_INFO_A_ID_LSB_M 0xFFFFFFFF

/* CACHE_ERR_DN_CONV_INFO_B */
#define CACHE_ERR_DN_CONV_INFO_B_ID_MSB_S 0
#define CACHE_ERR_DN_CONV_INFO_B_ID_MSB_M 0xF

/* CACHE_ERR_DN_CONV_INFO_CLEAR */
#define CACHE_ERR_DN_CONV_INFO_CLEAR_CLEAR_S 0
#define CACHE_ERR_DN_CONV_INFO_CLEAR_CLEAR_M 0x1

#endif /* ASIC_REG_CACHE_ERR_MASKS_H_ */
