/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_CBC_MASKS_H_
#define ASIC_REG_CBC_MASKS_H_

/*
 *****************************************
 *   CBC
 *   (Prototype: CBC)
 *****************************************
 */

/* CBC_CBC_EN */
#define CBC_CBC_EN_VAL_S 0
#define CBC_CBC_EN_VAL_M 0x1

/* CBC_CBC_CTRL */
#define CBC_CBC_CTRL_INV_BP_EN_S 0
#define CBC_CBC_CTRL_INV_BP_EN_M 0x1

/* CBC_CBC_MODE */
#define CBC_CBC_MODE_RANGE_MODE_S 0
#define CBC_CBC_MODE_RANGE_MODE_M 0x1
#define CBC_CBC_MODE_ARCACHE_MODE_S 4
#define CBC_CBC_MODE_ARCACHE_MODE_M 0x10

/* CBC_CBC_RANGE_ASID_CHK_EN */
#define CBC_CBC_RANGE_ASID_CHK_EN_VAL_S 0
#define CBC_CBC_RANGE_ASID_CHK_EN_VAL_M 0x1

/* CBC_CBC_RANGE_ASID_BASE */
#define CBC_CBC_RANGE_ASID_BASE_VAL_S 0
#define CBC_CBC_RANGE_ASID_BASE_VAL_M 0x3FF

/* CBC_CBC_RANGE_ASID_MASK */
#define CBC_CBC_RANGE_ASID_MASK_VAL_S 0
#define CBC_CBC_RANGE_ASID_MASK_VAL_M 0x3FF

/* CBC_CBC_ARB_WEIGHT */
#define CBC_CBC_ARB_WEIGHT_RRB_WEIGHT_S 0
#define CBC_CBC_ARB_WEIGHT_RRB_WEIGHT_M 0xFF
#define CBC_CBC_ARB_WEIGHT_TAG_WEIGHT_S 8
#define CBC_CBC_ARB_WEIGHT_TAG_WEIGHT_M 0xFF00

/* CBC_CBC_PLRU_MODE */
#define CBC_CBC_PLRU_MODE_VAL_S 0
#define CBC_CBC_PLRU_MODE_VAL_M 0x1

/* CBC_SET_SCRAM_EN */
#define CBC_SET_SCRAM_EN_VAL_S 0
#define CBC_SET_SCRAM_EN_VAL_M 0x1

/* CBC_SET_SCRAM_POLY */
#define CBC_SET_SCRAM_POLY_VAL_S 0
#define CBC_SET_SCRAM_POLY_VAL_M 0x3F

/* CBC_LBW_ID */
#define CBC_LBW_ID_VAL_S 3
#define CBC_LBW_ID_VAL_M 0x7FF8

/* CBC_LBW_USER */
#define CBC_LBW_USER_VAL_S 0
#define CBC_LBW_USER_VAL_M 0xF

/* CBC_LBW_PROT0 */
#define CBC_LBW_PROT0_VAL_S 0
#define CBC_LBW_PROT0_VAL_M 0x1

/* CBC_LBW_PROT1 */
#define CBC_LBW_PROT1_VAL_S 0
#define CBC_LBW_PROT1_VAL_M 0x1

/* CBC_LBW_PROT2 */
#define CBC_LBW_PROT2_VAL_S 0
#define CBC_LBW_PROT2_VAL_M 0x1

/* CBC_LBW_RSP_ERR_HAPPENED_CLR */
#define CBC_LBW_RSP_ERR_HAPPENED_CLR_VAL_S 0
#define CBC_LBW_RSP_ERR_HAPPENED_CLR_VAL_M 0x1

/* CBC_LBW_RSP_ERR_HAPPENED_ST */
#define CBC_LBW_RSP_ERR_HAPPENED_ST_VAL_S 0
#define CBC_LBW_RSP_ERR_HAPPENED_ST_VAL_M 0x1

/* CBC_LBW_RSP_ERR_MISC */
#define CBC_LBW_RSP_ERR_MISC_BID_S 0
#define CBC_LBW_RSP_ERR_MISC_BID_M 0xFFFF
#define CBC_LBW_RSP_ERR_MISC_BUSER_S 16
#define CBC_LBW_RSP_ERR_MISC_BUSER_M 0xFF0000
#define CBC_LBW_RSP_ERR_MISC_BRESP_S 24
#define CBC_LBW_RSP_ERR_MISC_BRESP_M 0x3000000

/* CBC_CBC_DBG_RRB */
#define CBC_CBC_DBG_RRB_RRB_USED_S 0
#define CBC_CBC_DBG_RRB_RRB_USED_M 0xFFF

/* CBC_CBC_DBG_CSH_VLD */
#define CBC_CBC_DBG_CSH_VLD_RANGE_0_VLD_S 0
#define CBC_CBC_DBG_CSH_VLD_RANGE_0_VLD_M 0x1
#define CBC_CBC_DBG_CSH_VLD_RANGE_1_VLD_S 4
#define CBC_CBC_DBG_CSH_VLD_RANGE_1_VLD_M 0x10
#define CBC_CBC_DBG_CSH_VLD_RANGE_2_VLD_S 8
#define CBC_CBC_DBG_CSH_VLD_RANGE_2_VLD_M 0x100
#define CBC_CBC_DBG_CSH_VLD_RANGE_3_VLD_S 12
#define CBC_CBC_DBG_CSH_VLD_RANGE_3_VLD_M 0x1000

/* CBC_CBC_DBG_CNT_EN */
#define CBC_CBC_DBG_CNT_EN_VAL_S 0
#define CBC_CBC_DBG_CNT_EN_VAL_M 0x1

/* CBC_CBC_DBG_TOT */
#define CBC_CBC_DBG_TOT_OTF_S 0
#define CBC_CBC_DBG_TOT_OTF_M 0xFFFF

/* CBC_CBC_DBG_RANGE */
#define CBC_CBC_DBG_RANGE_OTF_S 0
#define CBC_CBC_DBG_RANGE_OTF_M 0xFFFF

/* CBC_CBC_WRAP_DBG_TOT */
#define CBC_CBC_WRAP_DBG_TOT_OTF_S 0
#define CBC_CBC_WRAP_DBG_TOT_OTF_M 0xFFFF

/* CBC_CBC_WRAP_DBG_RANGE */
#define CBC_CBC_WRAP_DBG_RANGE_OTF_S 0
#define CBC_CBC_WRAP_DBG_RANGE_OTF_M 0xFFFF

/* CBC_CBC_INV_CHK_BIT */
#define CBC_CBC_INV_CHK_BIT_BLK_ALL_S 0
#define CBC_CBC_INV_CHK_BIT_BLK_ALL_M 0x1
#define CBC_CBC_INV_CHK_BIT_DLY_PIPE_FREE_S 4
#define CBC_CBC_INV_CHK_BIT_DLY_PIPE_FREE_M 0x10

#endif /* ASIC_REG_CBC_MASKS_H_ */
