/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_CS_DBG_TPC_EML_BMON0_MASKS_H_
#define ASIC_REG_CS_DBG_TPC_EML_BMON0_MASKS_H_

/*
 *****************************************
 *   CS_DBG_TPC_EML_BMON0
 *   (Prototype: BMON)
 *****************************************
 */

/* CS_DBG_TPC_EML_BMON0_CR */
#define CS_DBG_TPC_EML_BMON0_CR_ENABLE_S 0
#define CS_DBG_TPC_EML_BMON0_CR_ENABLE_M 0x1
#define CS_DBG_TPC_EML_BMON0_CR_TRC_BW_EN_S 1
#define CS_DBG_TPC_EML_BMON0_CR_TRC_BW_EN_M 0x2
#define CS_DBG_TPC_EML_BMON0_CR_TRC_ADDR_EN_S 2
#define CS_DBG_TPC_EML_BMON0_CR_TRC_ADDR_EN_M 0x4
#define CS_DBG_TPC_EML_BMON0_CR_TRC_TRAFFIC_EN_S 3
#define CS_DBG_TPC_EML_BMON0_CR_TRC_TRAFFIC_EN_M 0x8
#define CS_DBG_TPC_EML_BMON0_CR_TRC_LATENCY_EN_S 4
#define CS_DBG_TPC_EML_BMON0_CR_TRC_LATENCY_EN_M 0x10
#define CS_DBG_TPC_EML_BMON0_CR_TRC_OS_EN_S 5
#define CS_DBG_TPC_EML_BMON0_CR_TRC_OS_EN_M 0x20
#define CS_DBG_TPC_EML_BMON0_CR_TRC_COMPRESS_EN_S 6
#define CS_DBG_TPC_EML_BMON0_CR_TRC_COMPRESS_EN_M 0x40
#define CS_DBG_TPC_EML_BMON0_CR_TRC_COMP_BW_EN_S 7
#define CS_DBG_TPC_EML_BMON0_CR_TRC_COMP_BW_EN_M 0x80
#define CS_DBG_TPC_EML_BMON0_CR_AXADDR_LK_EN_S 12
#define CS_DBG_TPC_EML_BMON0_CR_AXADDR_LK_EN_M 0xF000
#define CS_DBG_TPC_EML_BMON0_CR_INTR_EN_S 16
#define CS_DBG_TPC_EML_BMON0_CR_INTR_EN_M 0xF0000
#define CS_DBG_TPC_EML_BMON0_CR_TRIGOUT_EN_S 20
#define CS_DBG_TPC_EML_BMON0_CR_TRIGOUT_EN_M 0xF00000
#define CS_DBG_TPC_EML_BMON0_CR_STAS_EN_S 24
#define CS_DBG_TPC_EML_BMON0_CR_STAS_EN_M 0xF000000
#define CS_DBG_TPC_EML_BMON0_CR_AXATTR_LK_EN_S 28
#define CS_DBG_TPC_EML_BMON0_CR_AXATTR_LK_EN_M 0xF0000000

/* CS_DBG_TPC_EML_BMON0_R_RESET */
#define CS_DBG_TPC_EML_BMON0_R_RESET_F_RESET_S 0
#define CS_DBG_TPC_EML_BMON0_R_RESET_F_RESET_M 0x1

/* CS_DBG_TPC_EML_BMON0_INT_CLR */
#define CS_DBG_TPC_EML_BMON0_INT_CLR_CLR_S 0
#define CS_DBG_TPC_EML_BMON0_INT_CLR_CLR_M 0x1

/* CS_DBG_TPC_EML_BMON0_TRIG_TH */
#define CS_DBG_TPC_EML_BMON0_TRIG_TH_TH_S 0
#define CS_DBG_TPC_EML_BMON0_TRIG_TH_TH_M 0xFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRL_S0 */
#define CS_DBG_TPC_EML_BMON0_ADDRL_S0_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRL_S0_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRH_S0 */
#define CS_DBG_TPC_EML_BMON0_ADDRH_S0_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRH_S0_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRL_E0 */
#define CS_DBG_TPC_EML_BMON0_ADDRL_E0_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRL_E0_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRH_E0 */
#define CS_DBG_TPC_EML_BMON0_ADDRH_E0_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRH_E0_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRL_S1 */
#define CS_DBG_TPC_EML_BMON0_ADDRL_S1_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRL_S1_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRH_S1 */
#define CS_DBG_TPC_EML_BMON0_ADDRH_S1_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRH_S1_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRL_E1 */
#define CS_DBG_TPC_EML_BMON0_ADDRL_E1_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRL_E1_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRH_E1 */
#define CS_DBG_TPC_EML_BMON0_ADDRH_E1_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRH_E1_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRL_S2 */
#define CS_DBG_TPC_EML_BMON0_ADDRL_S2_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRL_S2_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRH_S2 */
#define CS_DBG_TPC_EML_BMON0_ADDRH_S2_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRH_S2_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRL_E2 */
#define CS_DBG_TPC_EML_BMON0_ADDRL_E2_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRL_E2_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRH_E2 */
#define CS_DBG_TPC_EML_BMON0_ADDRH_E2_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRH_E2_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRL_S3 */
#define CS_DBG_TPC_EML_BMON0_ADDRL_S3_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRL_S3_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRH_S3 */
#define CS_DBG_TPC_EML_BMON0_ADDRH_S3_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRH_S3_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRL_E3 */
#define CS_DBG_TPC_EML_BMON0_ADDRL_E3_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRL_E3_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRH_E3 */
#define CS_DBG_TPC_EML_BMON0_ADDRH_E3_ADDR_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRH_E3_ADDR_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_REDUCTION */
#define CS_DBG_TPC_EML_BMON0_REDUCTION_ENABLE_S 0
#define CS_DBG_TPC_EML_BMON0_REDUCTION_ENABLE_M 0x1
#define CS_DBG_TPC_EML_BMON0_REDUCTION_INDEX_S 8
#define CS_DBG_TPC_EML_BMON0_REDUCTION_INDEX_M 0xFF00

/* CS_DBG_TPC_EML_BMON0_IDL */
#define CS_DBG_TPC_EML_BMON0_IDL_VAL_S 0
#define CS_DBG_TPC_EML_BMON0_IDL_VAL_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_IDH */
#define CS_DBG_TPC_EML_BMON0_IDH_EN_S 0
#define CS_DBG_TPC_EML_BMON0_IDH_EN_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_IDENL */
#define CS_DBG_TPC_EML_BMON0_IDENL_VAL_S 0
#define CS_DBG_TPC_EML_BMON0_IDENL_VAL_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_IDENH */
#define CS_DBG_TPC_EML_BMON0_IDENH_EN_S 0
#define CS_DBG_TPC_EML_BMON0_IDENH_EN_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_LATENCY_SMP */
#define CS_DBG_TPC_EML_BMON0_LATENCY_SMP_EN_S 0
#define CS_DBG_TPC_EML_BMON0_LATENCY_SMP_EN_M 0x1
#define CS_DBG_TPC_EML_BMON0_LATENCY_SMP_SAMPLE_FREQ_S 8
#define CS_DBG_TPC_EML_BMON0_LATENCY_SMP_SAMPLE_FREQ_M 0xFF00

/* CS_DBG_TPC_EML_BMON0_ATTR */
#define CS_DBG_TPC_EML_BMON0_ATTR_AXCACHE_S 0
#define CS_DBG_TPC_EML_BMON0_ATTR_AXCACHE_M 0xF
#define CS_DBG_TPC_EML_BMON0_ATTR_AXPROT_S 8
#define CS_DBG_TPC_EML_BMON0_ATTR_AXPROT_M 0x700
#define CS_DBG_TPC_EML_BMON0_ATTR_AXLOCK_S 12
#define CS_DBG_TPC_EML_BMON0_ATTR_AXLOCK_M 0x1000

/* CS_DBG_TPC_EML_BMON0_ATTREN */
#define CS_DBG_TPC_EML_BMON0_ATTREN_AXCACHE_EN_S 0
#define CS_DBG_TPC_EML_BMON0_ATTREN_AXCACHE_EN_M 0xF
#define CS_DBG_TPC_EML_BMON0_ATTREN_AXPROT_EN_S 8
#define CS_DBG_TPC_EML_BMON0_ATTREN_AXPROT_EN_M 0x700
#define CS_DBG_TPC_EML_BMON0_ATTREN_AXLOCK_EN_S 12
#define CS_DBG_TPC_EML_BMON0_ATTREN_AXLOCK_EN_M 0x1000

/* CS_DBG_TPC_EML_BMON0_USREN0 */
#define CS_DBG_TPC_EML_BMON0_USREN0_EN_S 0
#define CS_DBG_TPC_EML_BMON0_USREN0_EN_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_USR0 */
#define CS_DBG_TPC_EML_BMON0_USR0_VAL_S 0
#define CS_DBG_TPC_EML_BMON0_USR0_VAL_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_USREN1 */
#define CS_DBG_TPC_EML_BMON0_USREN1_EN_S 0
#define CS_DBG_TPC_EML_BMON0_USREN1_EN_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_USR1 */
#define CS_DBG_TPC_EML_BMON0_USR1_VAL_S 0
#define CS_DBG_TPC_EML_BMON0_USR1_VAL_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_USREN2 */
#define CS_DBG_TPC_EML_BMON0_USREN2_EN_S 0
#define CS_DBG_TPC_EML_BMON0_USREN2_EN_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_USR2 */
#define CS_DBG_TPC_EML_BMON0_USR2_VAL_S 0
#define CS_DBG_TPC_EML_BMON0_USR2_VAL_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_CAPTURE */
#define CS_DBG_TPC_EML_BMON0_CAPTURE_CAPTURE_S 0
#define CS_DBG_TPC_EML_BMON0_CAPTURE_CAPTURE_M 0x1

/* CS_DBG_TPC_EML_BMON0_RELEASE */
#define CS_DBG_TPC_EML_BMON0_RELEASE_RELEASE_S 0
#define CS_DBG_TPC_EML_BMON0_RELEASE_RELEASE_M 0x1

/* CS_DBG_TPC_EML_BMON0_WIN_CAPTURE */
#define CS_DBG_TPC_EML_BMON0_WIN_CAPTURE_PERIOD_S 0
#define CS_DBG_TPC_EML_BMON0_WIN_CAPTURE_PERIOD_M 0xFFFF

/* CS_DBG_TPC_EML_BMON0_BW_WIN */
#define CS_DBG_TPC_EML_BMON0_BW_WIN_BW_WIN_S 0
#define CS_DBG_TPC_EML_BMON0_BW_WIN_BW_WIN_M 0xFFFF

/* CS_DBG_TPC_EML_BMON0_MATCH_CNT_SOD */
#define CS_DBG_TPC_EML_BMON0_MATCH_CNT_SOD_CNT_S 0
#define CS_DBG_TPC_EML_BMON0_MATCH_CNT_SOD_CNT_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_MATCH_CNT_WIN */
#define CS_DBG_TPC_EML_BMON0_MATCH_CNT_WIN_CNT_S 0
#define CS_DBG_TPC_EML_BMON0_MATCH_CNT_WIN_CNT_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_CYCCNT_L */
#define CS_DBG_TPC_EML_BMON0_CYCCNT_L_CYCLEL_S 0
#define CS_DBG_TPC_EML_BMON0_CYCCNT_L_CYCLEL_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_CYCCNT_H */
#define CS_DBG_TPC_EML_BMON0_CYCCNT_H_CYCLEH_S 0
#define CS_DBG_TPC_EML_BMON0_CYCCNT_H_CYCLEH_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_MAXLAT_SOD */
#define CS_DBG_TPC_EML_BMON0_MAXLAT_SOD_MAX_S 0
#define CS_DBG_TPC_EML_BMON0_MAXLAT_SOD_MAX_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_MINLAT_SOD */
#define CS_DBG_TPC_EML_BMON0_MINLAT_SOD_MIN_S 0
#define CS_DBG_TPC_EML_BMON0_MINLAT_SOD_MIN_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_MAXBW_SOD */
#define CS_DBG_TPC_EML_BMON0_MAXBW_SOD_BW_S 0
#define CS_DBG_TPC_EML_BMON0_MAXBW_SOD_BW_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_MINBW_SOD */
#define CS_DBG_TPC_EML_BMON0_MINBW_SOD_BW_S 0
#define CS_DBG_TPC_EML_BMON0_MINBW_SOD_BW_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_MAXOS_SOD */
#define CS_DBG_TPC_EML_BMON0_MAXOS_SOD_MAX_S 0
#define CS_DBG_TPC_EML_BMON0_MAXOS_SOD_MAX_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_MINOS_SOD */
#define CS_DBG_TPC_EML_BMON0_MINOS_SOD_MIN_S 0
#define CS_DBG_TPC_EML_BMON0_MINOS_SOD_MIN_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRL_SNAPSHOT */
#define CS_DBG_TPC_EML_BMON0_ADDRL_SNAPSHOT_ADDRL_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRL_SNAPSHOT_ADDRL_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_ADDRH_SNAPSHOT */
#define CS_DBG_TPC_EML_BMON0_ADDRH_SNAPSHOT_ADDRH_S 0
#define CS_DBG_TPC_EML_BMON0_ADDRH_SNAPSHOT_ADDRH_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_IDL_SNAPSHOT */
#define CS_DBG_TPC_EML_BMON0_IDL_SNAPSHOT_ID_S 0
#define CS_DBG_TPC_EML_BMON0_IDL_SNAPSHOT_ID_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_IDH_SNAPSHOT */

/* CS_DBG_TPC_EML_BMON0_ATTR_SNAPSHOT */
#define CS_DBG_TPC_EML_BMON0_ATTR_SNAPSHOT_AXCACHE_S 0
#define CS_DBG_TPC_EML_BMON0_ATTR_SNAPSHOT_AXCACHE_M 0xF
#define CS_DBG_TPC_EML_BMON0_ATTR_SNAPSHOT_AXPROT_S 4
#define CS_DBG_TPC_EML_BMON0_ATTR_SNAPSHOT_AXPROT_M 0x70
#define CS_DBG_TPC_EML_BMON0_ATTR_SNAPSHOT_AXLOCK_S 8
#define CS_DBG_TPC_EML_BMON0_ATTR_SNAPSHOT_AXLOCK_M 0x100

/* CS_DBG_TPC_EML_BMON0_STM_TRC */
#define CS_DBG_TPC_EML_BMON0_STM_TRC_TIMESTAMP_EN_S 0
#define CS_DBG_TPC_EML_BMON0_STM_TRC_TIMESTAMP_EN_M 0x1
#define CS_DBG_TPC_EML_BMON0_STM_TRC_MARKED_S 1
#define CS_DBG_TPC_EML_BMON0_STM_TRC_MARKED_M 0x2
#define CS_DBG_TPC_EML_BMON0_STM_TRC_GUARANTEED_S 2
#define CS_DBG_TPC_EML_BMON0_STM_TRC_GUARANTEED_M 0x4
#define CS_DBG_TPC_EML_BMON0_STM_TRC_CFG_MASTER_ID_S 8
#define CS_DBG_TPC_EML_BMON0_STM_TRC_CFG_MASTER_ID_M 0x3F00

/* CS_DBG_TPC_EML_BMON0_STM_TRC_DROP */
#define CS_DBG_TPC_EML_BMON0_STM_TRC_DROP_DROP_S 0
#define CS_DBG_TPC_EML_BMON0_STM_TRC_DROP_DROP_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_DEVARCH */
#define CS_DBG_TPC_EML_BMON0_DEVARCH_VAL_S 0
#define CS_DBG_TPC_EML_BMON0_DEVARCH_VAL_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_PMDEVID2 */
#define CS_DBG_TPC_EML_BMON0_PMDEVID2_VAL_S 0
#define CS_DBG_TPC_EML_BMON0_PMDEVID2_VAL_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_PMDEVID1 */
#define CS_DBG_TPC_EML_BMON0_PMDEVID1_VAL_S 0
#define CS_DBG_TPC_EML_BMON0_PMDEVID1_VAL_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_PMDEVID */
#define CS_DBG_TPC_EML_BMON0_PMDEVID_VAL_S 0
#define CS_DBG_TPC_EML_BMON0_PMDEVID_VAL_M 0xFFFFFFFF

/* CS_DBG_TPC_EML_BMON0_DEVTYPE */
#define CS_DBG_TPC_EML_BMON0_DEVTYPE_MAJOR_S 0
#define CS_DBG_TPC_EML_BMON0_DEVTYPE_MAJOR_M 0xF
#define CS_DBG_TPC_EML_BMON0_DEVTYPE_SUB_S 4
#define CS_DBG_TPC_EML_BMON0_DEVTYPE_SUB_M 0xF0

/* CS_DBG_TPC_EML_BMON0_PIDR4 */
#define CS_DBG_TPC_EML_BMON0_PIDR4_DES_2_S 0
#define CS_DBG_TPC_EML_BMON0_PIDR4_DES_2_M 0xF
#define CS_DBG_TPC_EML_BMON0_PIDR4_SIZE_FLD_S 4
#define CS_DBG_TPC_EML_BMON0_PIDR4_SIZE_FLD_M 0xF0

/* CS_DBG_TPC_EML_BMON0_PIDR5 */
#define CS_DBG_TPC_EML_BMON0_PIDR5_RSV_S 0
#define CS_DBG_TPC_EML_BMON0_PIDR5_RSV_M 0xFF

/* CS_DBG_TPC_EML_BMON0_PIDR6 */
#define CS_DBG_TPC_EML_BMON0_PIDR6_RSV_S 0
#define CS_DBG_TPC_EML_BMON0_PIDR6_RSV_M 0xFF

/* CS_DBG_TPC_EML_BMON0_PIDR7 */
#define CS_DBG_TPC_EML_BMON0_PIDR7_RSV_S 0
#define CS_DBG_TPC_EML_BMON0_PIDR7_RSV_M 0xFF

/* CS_DBG_TPC_EML_BMON0_PIDR0 */
#define CS_DBG_TPC_EML_BMON0_PIDR0_PARTNUMBER_S 0
#define CS_DBG_TPC_EML_BMON0_PIDR0_PARTNUMBER_M 0xFF

/* CS_DBG_TPC_EML_BMON0_PIDR1 */
#define CS_DBG_TPC_EML_BMON0_PIDR1_PART_1_S 0
#define CS_DBG_TPC_EML_BMON0_PIDR1_PART_1_M 0xF
#define CS_DBG_TPC_EML_BMON0_PIDR1_DES_S 4
#define CS_DBG_TPC_EML_BMON0_PIDR1_DES_M 0xF0

/* CS_DBG_TPC_EML_BMON0_PIDR2 */
#define CS_DBG_TPC_EML_BMON0_PIDR2_DES1_S 0
#define CS_DBG_TPC_EML_BMON0_PIDR2_DES1_M 0x7
#define CS_DBG_TPC_EML_BMON0_PIDR2_JEDEC_S 3
#define CS_DBG_TPC_EML_BMON0_PIDR2_JEDEC_M 0x8
#define CS_DBG_TPC_EML_BMON0_PIDR2_REVISION_S 4
#define CS_DBG_TPC_EML_BMON0_PIDR2_REVISION_M 0xF0

/* CS_DBG_TPC_EML_BMON0_PIDR3 */
#define CS_DBG_TPC_EML_BMON0_PIDR3_CMOD_S 0
#define CS_DBG_TPC_EML_BMON0_PIDR3_CMOD_M 0xF
#define CS_DBG_TPC_EML_BMON0_PIDR3_REVAND_S 4
#define CS_DBG_TPC_EML_BMON0_PIDR3_REVAND_M 0xF0

/* CS_DBG_TPC_EML_BMON0_CIDR0 */
#define CS_DBG_TPC_EML_BMON0_CIDR0_PREAMPLE_S 0
#define CS_DBG_TPC_EML_BMON0_CIDR0_PREAMPLE_M 0xFF

/* CS_DBG_TPC_EML_BMON0_CIDR1 */
#define CS_DBG_TPC_EML_BMON0_CIDR1_PRAMPL1_S 0
#define CS_DBG_TPC_EML_BMON0_CIDR1_PRAMPL1_M 0xF
#define CS_DBG_TPC_EML_BMON0_CIDR1_CLASS_FLD_S 4
#define CS_DBG_TPC_EML_BMON0_CIDR1_CLASS_FLD_M 0xF0

/* CS_DBG_TPC_EML_BMON0_CIDR2 */
#define CS_DBG_TPC_EML_BMON0_CIDR2_PRAMPL2_S 0
#define CS_DBG_TPC_EML_BMON0_CIDR2_PRAMPL2_M 0xFF

/* CS_DBG_TPC_EML_BMON0_CIDR3 */
#define CS_DBG_TPC_EML_BMON0_CIDR3_PRAMPL3_S 0
#define CS_DBG_TPC_EML_BMON0_CIDR3_PRAMPL3_M 0xFF

#endif /* ASIC_REG_CS_DBG_TPC_EML_BMON0_MASKS_H_ */
