/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_CS_DBG_TPC_EML_BMON0_REGS_H_
#define ASIC_REG_CS_DBG_TPC_EML_BMON0_REGS_H_

/*
 *****************************************
 *   CS_DBG_TPC_EML_BMON0
 *   (Prototype: BMON)
 *****************************************
 */

#define mmCS_DBG_TPC_EML_BMON0_CR 0x0

#define mmCS_DBG_TPC_EML_BMON0_R_RESET 0x4

#define mmCS_DBG_TPC_EML_BMON0_INT_CLR 0x8

#define mmCS_DBG_TPC_EML_BMON0_TRIG_TH 0xC

#define mmCS_DBG_TPC_EML_BMON0_ADDRL_S0 0x20

#define mmCS_DBG_TPC_EML_BMON0_ADDRH_S0 0x24

#define mmCS_DBG_TPC_EML_BMON0_ADDRL_E0 0x28

#define mmCS_DBG_TPC_EML_BMON0_ADDRH_E0 0x2C

#define mmCS_DBG_TPC_EML_BMON0_ADDRL_S1 0x30

#define mmCS_DBG_TPC_EML_BMON0_ADDRH_S1 0x34

#define mmCS_DBG_TPC_EML_BMON0_ADDRL_E1 0x38

#define mmCS_DBG_TPC_EML_BMON0_ADDRH_E1 0x3C

#define mmCS_DBG_TPC_EML_BMON0_ADDRL_S2 0x40

#define mmCS_DBG_TPC_EML_BMON0_ADDRH_S2 0x44

#define mmCS_DBG_TPC_EML_BMON0_ADDRL_E2 0x48

#define mmCS_DBG_TPC_EML_BMON0_ADDRH_E2 0x4C

#define mmCS_DBG_TPC_EML_BMON0_ADDRL_S3 0x50

#define mmCS_DBG_TPC_EML_BMON0_ADDRH_S3 0x54

#define mmCS_DBG_TPC_EML_BMON0_ADDRL_E3 0x58

#define mmCS_DBG_TPC_EML_BMON0_ADDRH_E3 0x5C

#define mmCS_DBG_TPC_EML_BMON0_REDUCTION 0x60

#define mmCS_DBG_TPC_EML_BMON0_IDL 0x70

#define mmCS_DBG_TPC_EML_BMON0_IDH 0x74

#define mmCS_DBG_TPC_EML_BMON0_IDENL 0x78

#define mmCS_DBG_TPC_EML_BMON0_IDENH 0x7C

#define mmCS_DBG_TPC_EML_BMON0_LATENCY_SMP 0x90

#define mmCS_DBG_TPC_EML_BMON0_ATTR 0x94

#define mmCS_DBG_TPC_EML_BMON0_ATTREN 0x98

#define mmCS_DBG_TPC_EML_BMON0_USREN0 0x9C

#define mmCS_DBG_TPC_EML_BMON0_USR0 0x100

#define mmCS_DBG_TPC_EML_BMON0_USREN1 0x104

#define mmCS_DBG_TPC_EML_BMON0_USR1 0x110

#define mmCS_DBG_TPC_EML_BMON0_USREN2 0x114

#define mmCS_DBG_TPC_EML_BMON0_USR2 0x118

#define mmCS_DBG_TPC_EML_BMON0_CAPTURE 0x200

#define mmCS_DBG_TPC_EML_BMON0_RELEASE 0x204

#define mmCS_DBG_TPC_EML_BMON0_WIN_CAPTURE 0x208

#define mmCS_DBG_TPC_EML_BMON0_BW_WIN 0x20C

#define mmCS_DBG_TPC_EML_BMON0_MATCH_CNT_SOD 0x220

#define mmCS_DBG_TPC_EML_BMON0_MATCH_CNT_WIN 0x224

#define mmCS_DBG_TPC_EML_BMON0_CYCCNT_L 0x228

#define mmCS_DBG_TPC_EML_BMON0_CYCCNT_H 0x22C

#define mmCS_DBG_TPC_EML_BMON0_MAXLAT_SOD 0x304

#define mmCS_DBG_TPC_EML_BMON0_MINLAT_SOD 0x308

#define mmCS_DBG_TPC_EML_BMON0_MAXBW_SOD 0x310

#define mmCS_DBG_TPC_EML_BMON0_MINBW_SOD 0x314

#define mmCS_DBG_TPC_EML_BMON0_MAXOS_SOD 0x320

#define mmCS_DBG_TPC_EML_BMON0_MINOS_SOD 0x324

#define mmCS_DBG_TPC_EML_BMON0_ADDRL_SNAPSHOT 0x400

#define mmCS_DBG_TPC_EML_BMON0_ADDRH_SNAPSHOT 0x404

#define mmCS_DBG_TPC_EML_BMON0_IDL_SNAPSHOT 0x408

#define mmCS_DBG_TPC_EML_BMON0_IDH_SNAPSHOT 0x40C

#define mmCS_DBG_TPC_EML_BMON0_ATTR_SNAPSHOT 0x410

#define mmCS_DBG_TPC_EML_BMON0_STM_TRC 0x420

#define mmCS_DBG_TPC_EML_BMON0_STM_TRC_DROP 0x424

#define mmCS_DBG_TPC_EML_BMON0_DEVARCH 0xFBC

#define mmCS_DBG_TPC_EML_BMON0_PMDEVID2 0xFC0

#define mmCS_DBG_TPC_EML_BMON0_PMDEVID1 0xFC4

#define mmCS_DBG_TPC_EML_BMON0_PMDEVID 0xFC8

#define mmCS_DBG_TPC_EML_BMON0_DEVTYPE 0xFCC

#define mmCS_DBG_TPC_EML_BMON0_PIDR4 0xFD0

#define mmCS_DBG_TPC_EML_BMON0_PIDR5 0xFD4

#define mmCS_DBG_TPC_EML_BMON0_PIDR6 0xFD8

#define mmCS_DBG_TPC_EML_BMON0_PIDR7 0xFDC

#define mmCS_DBG_TPC_EML_BMON0_PIDR0 0xFE0

#define mmCS_DBG_TPC_EML_BMON0_PIDR1 0xFE4

#define mmCS_DBG_TPC_EML_BMON0_PIDR2 0xFE8

#define mmCS_DBG_TPC_EML_BMON0_PIDR3 0xFEC

#define mmCS_DBG_TPC_EML_BMON0_CIDR0 0xFF0

#define mmCS_DBG_TPC_EML_BMON0_CIDR1 0xFF4

#define mmCS_DBG_TPC_EML_BMON0_CIDR2 0xFF8

#define mmCS_DBG_TPC_EML_BMON0_CIDR3 0xFFC

#endif /* ASIC_REG_CS_DBG_TPC_EML_BMON0_REGS_H_ */
