/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_D0_NCH_ETR_MASKS_H_
#define ASIC_REG_D0_NCH_ETR_MASKS_H_

/*
 *****************************************
 *   D0_NCH_ETR
 *   (Prototype: ETR)
 *****************************************
 */

/* D0_NCH_ETR_RSZ */
#define D0_NCH_ETR_RSZ_ETR_S 0
#define D0_NCH_ETR_RSZ_ETR_M 0x7FFFFFFF

/* D0_NCH_ETR_STS */
#define D0_NCH_ETR_STS_FULL_S 0
#define D0_NCH_ETR_STS_FULL_M 0x1
#define D0_NCH_ETR_STS_TRIGGERED_S 1
#define D0_NCH_ETR_STS_TRIGGERED_M 0x2
#define D0_NCH_ETR_STS_TMCREADY_S 2
#define D0_NCH_ETR_STS_TMCREADY_M 0x4
#define D0_NCH_ETR_STS_FTEMPTY_S 3
#define D0_NCH_ETR_STS_FTEMPTY_M 0x8
#define D0_NCH_ETR_STS_EMPTY_S 4
#define D0_NCH_ETR_STS_EMPTY_M 0x10
#define D0_NCH_ETR_STS_MEMERR_S 5
#define D0_NCH_ETR_STS_MEMERR_M 0x20

/* D0_NCH_ETR_RRD */
#define D0_NCH_ETR_RRD_VAL_S 0
#define D0_NCH_ETR_RRD_VAL_M 0xFFFFFFFF

/* D0_NCH_ETR_RRP */
#define D0_NCH_ETR_RRP_VAL_S 0
#define D0_NCH_ETR_RRP_VAL_M 0xFFFFFFFF

/* D0_NCH_ETR_RWP */
#define D0_NCH_ETR_RWP_VAL_S 0
#define D0_NCH_ETR_RWP_VAL_M 0xFFFFFFFF

/* D0_NCH_ETR_TRG */
#define D0_NCH_ETR_TRG_VAL_S 0
#define D0_NCH_ETR_TRG_VAL_M 0xFFFFFFFF

/* D0_NCH_ETR_CTL */
#define D0_NCH_ETR_CTL_TRACECAPTEN_S 0
#define D0_NCH_ETR_CTL_TRACECAPTEN_M 0x1

/* D0_NCH_ETR_RWD */
#define D0_NCH_ETR_RWD_VAL_S 0
#define D0_NCH_ETR_RWD_VAL_M 0xFFFFFFFF

/* D0_NCH_ETR_MODE */
#define D0_NCH_ETR_MODE_VAL_S 0
#define D0_NCH_ETR_MODE_VAL_M 0x3

/* D0_NCH_ETR_LBUFLEVEL */
#define D0_NCH_ETR_LBUFLEVEL_VAL_S 0
#define D0_NCH_ETR_LBUFLEVEL_VAL_M 0x7FFFFFFF

/* D0_NCH_ETR_CBUFLEVEL */
#define D0_NCH_ETR_CBUFLEVEL_VAL_S 0
#define D0_NCH_ETR_CBUFLEVEL_VAL_M 0x7FFFFFFF

/* D0_NCH_ETR_BUFWM */
#define D0_NCH_ETR_BUFWM_VAL_S 0
#define D0_NCH_ETR_BUFWM_VAL_M 0x3FFFFFFF

/* D0_NCH_ETR_RRPHI */
#define D0_NCH_ETR_RRPHI_VAL_S 0
#define D0_NCH_ETR_RRPHI_VAL_M 0xFF

/* D0_NCH_ETR_RWPHI */
#define D0_NCH_ETR_RWPHI_VAL_S 0
#define D0_NCH_ETR_RWPHI_VAL_M 0xFF

/* D0_NCH_ETR_AXICTL */
#define D0_NCH_ETR_AXICTL_PROTCTRLBIT0_S 0
#define D0_NCH_ETR_AXICTL_PROTCTRLBIT0_M 0x1
#define D0_NCH_ETR_AXICTL_PROTCTRLBIT1_S 1
#define D0_NCH_ETR_AXICTL_PROTCTRLBIT1_M 0x2
#define D0_NCH_ETR_AXICTL_CACHECTRLBIT0_S 2
#define D0_NCH_ETR_AXICTL_CACHECTRLBIT0_M 0x4
#define D0_NCH_ETR_AXICTL_CACHECTRLBIT1_S 3
#define D0_NCH_ETR_AXICTL_CACHECTRLBIT1_M 0x8
#define D0_NCH_ETR_AXICTL_CACHECTRLBIT2_S 4
#define D0_NCH_ETR_AXICTL_CACHECTRLBIT2_M 0x10
#define D0_NCH_ETR_AXICTL_CACHECTRLBIT3_S 5
#define D0_NCH_ETR_AXICTL_CACHECTRLBIT3_M 0x20
#define D0_NCH_ETR_AXICTL_SCATTERGATHERMODE_S 7
#define D0_NCH_ETR_AXICTL_SCATTERGATHERMODE_M 0x80
#define D0_NCH_ETR_AXICTL_WRBURSTLEN_S 8
#define D0_NCH_ETR_AXICTL_WRBURSTLEN_M 0xF00

/* D0_NCH_ETR_DBALO */
#define D0_NCH_ETR_DBALO_BUFADDRLO_S 0
#define D0_NCH_ETR_DBALO_BUFADDRLO_M 0xFFFFFFFF

/* D0_NCH_ETR_DBAHI */
#define D0_NCH_ETR_DBAHI_BUFADDRHI_S 0
#define D0_NCH_ETR_DBAHI_BUFADDRHI_M 0xFF

/* D0_NCH_ETR_FFSR */
#define D0_NCH_ETR_FFSR_FLINPROG_S 0
#define D0_NCH_ETR_FFSR_FLINPROG_M 0x1
#define D0_NCH_ETR_FFSR_FTSTOPPED_S 1
#define D0_NCH_ETR_FFSR_FTSTOPPED_M 0x2

/* D0_NCH_ETR_FFCR */
#define D0_NCH_ETR_FFCR_ENFT_S 0
#define D0_NCH_ETR_FFCR_ENFT_M 0x1
#define D0_NCH_ETR_FFCR_ENTI_S 1
#define D0_NCH_ETR_FFCR_ENTI_M 0x2
#define D0_NCH_ETR_FFCR_FONFLIN_S 4
#define D0_NCH_ETR_FFCR_FONFLIN_M 0x10
#define D0_NCH_ETR_FFCR_FONTRIGEVT_S 5
#define D0_NCH_ETR_FFCR_FONTRIGEVT_M 0x20
#define D0_NCH_ETR_FFCR_FLUSHMAN_S 6
#define D0_NCH_ETR_FFCR_FLUSHMAN_M 0x40
#define D0_NCH_ETR_FFCR_TRIGONTRIGIN_S 8
#define D0_NCH_ETR_FFCR_TRIGONTRIGIN_M 0x100
#define D0_NCH_ETR_FFCR_TRIGONTRIGEVT_S 9
#define D0_NCH_ETR_FFCR_TRIGONTRIGEVT_M 0x200
#define D0_NCH_ETR_FFCR_TRIGONFL_S 10
#define D0_NCH_ETR_FFCR_TRIGONFL_M 0x400
#define D0_NCH_ETR_FFCR_STOPONFL_S 12
#define D0_NCH_ETR_FFCR_STOPONFL_M 0x1000
#define D0_NCH_ETR_FFCR_STOPONTRIGEVT_S 13
#define D0_NCH_ETR_FFCR_STOPONTRIGEVT_M 0x2000

/* D0_NCH_ETR_PSCR */
#define D0_NCH_ETR_PSCR_PSCOUNT_S 0
#define D0_NCH_ETR_PSCR_PSCOUNT_M 0x1F

/* D0_NCH_ETR_ITMISCOP0 */
#define D0_NCH_ETR_ITMISCOP0_ACQCOMP_S 0
#define D0_NCH_ETR_ITMISCOP0_ACQCOMP_M 0x1
#define D0_NCH_ETR_ITMISCOP0_FULL_S 1
#define D0_NCH_ETR_ITMISCOP0_FULL_M 0x2

/* D0_NCH_ETR_ITTRFLIN */
#define D0_NCH_ETR_ITTRFLIN_TRIGIN_S 0
#define D0_NCH_ETR_ITTRFLIN_TRIGIN_M 0x1
#define D0_NCH_ETR_ITTRFLIN_FLUSHIN_S 1
#define D0_NCH_ETR_ITTRFLIN_FLUSHIN_M 0x2

/* D0_NCH_ETR_ITATBDATA0 */
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT0_S 0
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT0_M 0x1
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT7_S 1
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT7_M 0x2
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT15_S 2
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT15_M 0x4
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT23_S 3
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT23_M 0x8
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT31_S 4
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT31_M 0x10
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT39_S 5
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT39_M 0x20
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT47_S 6
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT47_M 0x40
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT55_S 7
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT55_M 0x80
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT63_S 8
#define D0_NCH_ETR_ITATBDATA0_ATDATASBIT63_M 0x100

/* D0_NCH_ETR_ITATBCTR2 */
#define D0_NCH_ETR_ITATBCTR2_ATREADYS_S 0
#define D0_NCH_ETR_ITATBCTR2_ATREADYS_M 0x1
#define D0_NCH_ETR_ITATBCTR2_AFVALIDS_S 1
#define D0_NCH_ETR_ITATBCTR2_AFVALIDS_M 0x2
#define D0_NCH_ETR_ITATBCTR2_SYNCREQS_S 2
#define D0_NCH_ETR_ITATBCTR2_SYNCREQS_M 0x4

/* D0_NCH_ETR_ITATBCTR1 */
#define D0_NCH_ETR_ITATBCTR1_ATIDS_S 0
#define D0_NCH_ETR_ITATBCTR1_ATIDS_M 0x7F

/* D0_NCH_ETR_ITATBCTR0 */
#define D0_NCH_ETR_ITATBCTR0_ATVALIDS_S 0
#define D0_NCH_ETR_ITATBCTR0_ATVALIDS_M 0x1
#define D0_NCH_ETR_ITATBCTR0_AFREADYS_S 1
#define D0_NCH_ETR_ITATBCTR0_AFREADYS_M 0x2
#define D0_NCH_ETR_ITATBCTR0_ATBYTESS_S 8
#define D0_NCH_ETR_ITATBCTR0_ATBYTESS_M 0x700

/* D0_NCH_ETR_ITCTRL */
#define D0_NCH_ETR_ITCTRL_INTEGRATION_MODE_S 0
#define D0_NCH_ETR_ITCTRL_INTEGRATION_MODE_M 0x1

/* D0_NCH_ETR_CLAIMSET */
#define D0_NCH_ETR_CLAIMSET_VAL_S 0
#define D0_NCH_ETR_CLAIMSET_VAL_M 0xF

/* D0_NCH_ETR_CLAIMCLR */
#define D0_NCH_ETR_CLAIMCLR_VAL_S 0
#define D0_NCH_ETR_CLAIMCLR_VAL_M 0xF

/* D0_NCH_ETR_LAR */
#define D0_NCH_ETR_LAR_ACCESS_W_S 0
#define D0_NCH_ETR_LAR_ACCESS_W_M 0xFFFFFFFF

/* D0_NCH_ETR_LSR */
#define D0_NCH_ETR_LSR_LOCKEXIST_S 0
#define D0_NCH_ETR_LSR_LOCKEXIST_M 0x1
#define D0_NCH_ETR_LSR_LOCKGRANT_S 1
#define D0_NCH_ETR_LSR_LOCKGRANT_M 0x2
#define D0_NCH_ETR_LSR_LOCKTYPE_S 2
#define D0_NCH_ETR_LSR_LOCKTYPE_M 0x4

/* D0_NCH_ETR_AUTHSTATUS */
#define D0_NCH_ETR_AUTHSTATUS_NSID_S 0
#define D0_NCH_ETR_AUTHSTATUS_NSID_M 0x3
#define D0_NCH_ETR_AUTHSTATUS_NSNID_S 2
#define D0_NCH_ETR_AUTHSTATUS_NSNID_M 0xC
#define D0_NCH_ETR_AUTHSTATUS_SID_S 4
#define D0_NCH_ETR_AUTHSTATUS_SID_M 0x30
#define D0_NCH_ETR_AUTHSTATUS_SNID_S 6
#define D0_NCH_ETR_AUTHSTATUS_SNID_M 0xC0

/* D0_NCH_ETR_DEVID */
#define D0_NCH_ETR_DEVID_ATBINPORTCOUNT_S 0
#define D0_NCH_ETR_DEVID_ATBINPORTCOUNT_M 0x1F
#define D0_NCH_ETR_DEVID_CLKSCHEME_S 5
#define D0_NCH_ETR_DEVID_CLKSCHEME_M 0x20
#define D0_NCH_ETR_DEVID_CONFIGTYPE_S 6
#define D0_NCH_ETR_DEVID_CONFIGTYPE_M 0xC0
#define D0_NCH_ETR_DEVID_MEMWIDTH_S 8
#define D0_NCH_ETR_DEVID_MEMWIDTH_M 0x700
#define D0_NCH_ETR_DEVID_WBUF_DEPTH_S 11
#define D0_NCH_ETR_DEVID_WBUF_DEPTH_M 0x3800

/* D0_NCH_ETR_DEVTYPE */
#define D0_NCH_ETR_DEVTYPE_MAJOR_TYPE_S 0
#define D0_NCH_ETR_DEVTYPE_MAJOR_TYPE_M 0xF
#define D0_NCH_ETR_DEVTYPE_SUB_TYPE_S 4
#define D0_NCH_ETR_DEVTYPE_SUB_TYPE_M 0xF0

/* D0_NCH_ETR_PERIPHID4 */
#define D0_NCH_ETR_PERIPHID4_JEP106_CONT_S 0
#define D0_NCH_ETR_PERIPHID4_JEP106_CONT_M 0xF
#define D0_NCH_ETR_PERIPHID4_FOURKB_COUNT_S 4
#define D0_NCH_ETR_PERIPHID4_FOURKB_COUNT_M 0xF0

/* D0_NCH_ETR_PERIPHID5 */
#define D0_NCH_ETR_PERIPHID5_VAL_S 0
#define D0_NCH_ETR_PERIPHID5_VAL_M 0xFFFFFFFF

/* D0_NCH_ETR_PERIPHID6 */
#define D0_NCH_ETR_PERIPHID6_VAL_S 0
#define D0_NCH_ETR_PERIPHID6_VAL_M 0xFFFFFFFF

/* D0_NCH_ETR_PERIPHID7 */
#define D0_NCH_ETR_PERIPHID7_VAL_S 0
#define D0_NCH_ETR_PERIPHID7_VAL_M 0xFFFFFFFF

/* D0_NCH_ETR_PERIPHID0 */
#define D0_NCH_ETR_PERIPHID0_PART_NUMBER_BITS7TO0_S 0
#define D0_NCH_ETR_PERIPHID0_PART_NUMBER_BITS7TO0_M 0xFF

/* D0_NCH_ETR_PERIPHID1 */
#define D0_NCH_ETR_PERIPHID1_PART_NUMBER_BITS11TO8_S 0
#define D0_NCH_ETR_PERIPHID1_PART_NUMBER_BITS11TO8_M 0xF
#define D0_NCH_ETR_PERIPHID1_JEP106_BITS3TO0_S 4
#define D0_NCH_ETR_PERIPHID1_JEP106_BITS3TO0_M 0xF0

/* D0_NCH_ETR_PERIPHID2 */
#define D0_NCH_ETR_PERIPHID2_JEP106_BITS6TO4_S 0
#define D0_NCH_ETR_PERIPHID2_JEP106_BITS6TO4_M 0x7
#define D0_NCH_ETR_PERIPHID2_JEDEC_S 3
#define D0_NCH_ETR_PERIPHID2_JEDEC_M 0x8
#define D0_NCH_ETR_PERIPHID2_REVISION_S 4
#define D0_NCH_ETR_PERIPHID2_REVISION_M 0xF0

/* D0_NCH_ETR_PERIPHID3 */
#define D0_NCH_ETR_PERIPHID3_CUSTOMER_MODIFIED_S 0
#define D0_NCH_ETR_PERIPHID3_CUSTOMER_MODIFIED_M 0xF
#define D0_NCH_ETR_PERIPHID3_REVAND_S 4
#define D0_NCH_ETR_PERIPHID3_REVAND_M 0xF0

/* D0_NCH_ETR_COMPID0 */
#define D0_NCH_ETR_COMPID0_PREAMBLE_S 0
#define D0_NCH_ETR_COMPID0_PREAMBLE_M 0xFF

/* D0_NCH_ETR_COMPID1 */
#define D0_NCH_ETR_COMPID1_PREAMBLE_S 0
#define D0_NCH_ETR_COMPID1_PREAMBLE_M 0xF
#define D0_NCH_ETR_COMPID1_F_CLASS_S 4
#define D0_NCH_ETR_COMPID1_F_CLASS_M 0xF0

/* D0_NCH_ETR_COMPID2 */
#define D0_NCH_ETR_COMPID2_PREAMBLE_S 0
#define D0_NCH_ETR_COMPID2_PREAMBLE_M 0xFF

/* D0_NCH_ETR_COMPID3 */
#define D0_NCH_ETR_COMPID3_PREAMBLE_S 0
#define D0_NCH_ETR_COMPID3_PREAMBLE_M 0xFF

#endif /* ASIC_REG_D0_NCH_ETR_MASKS_H_ */
