/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_D0_NIC0_RXB_CORE_SPECIAL_MASKS_H_
#define ASIC_REG_D0_NIC0_RXB_CORE_SPECIAL_MASKS_H_

/*
 *****************************************
 *   D0_NIC0_RXB_CORE_SPECIAL
 *   (Prototype: SPECIAL_REGS)
 *****************************************
 */

/* D0_NIC0_RXB_CORE_SPECIAL_GLBL_PRIV */
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_PRIV_VAL_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_PRIV_VAL_M 0xFFFFFFFF

/* D0_NIC0_RXB_CORE_SPECIAL_MEM_GW_DATA */
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_GW_DATA_VAL_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_GW_DATA_VAL_M 0xFFFFFFFF

/* D0_NIC0_RXB_CORE_SPECIAL_MEM_GW_REQ */
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_GW_REQ_ADDR_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_GW_REQ_ADDR_M 0x3FFFFF
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_GW_REQ_MID_S 22
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_GW_REQ_MID_M 0x3FC00000
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_GW_REQ_WNR_S 30
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_GW_REQ_WNR_M 0x40000000
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_GW_REQ_VLD_S 31
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_GW_REQ_VLD_M 0x80000000

/* D0_NIC0_RXB_CORE_SPECIAL_MEM_NUMOF */
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_NUMOF_VAL_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_NUMOF_VAL_M 0xFF

/* D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_SEL */
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_SEL_VAL_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_SEL_VAL_M 0xFF

/* D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL */
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL_SERR_INJ_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL_SERR_INJ_M 0x1
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL_DERR_INJ_S 1
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL_DERR_INJ_M 0x2
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL_SERR_CLR_S 2
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL_SERR_CLR_M 0x4
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL_DERR_CLR_S 3
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL_DERR_CLR_M 0x8
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL_CNT_TH_S 4
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL_CNT_TH_M 0xFF0
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL_CNT_SERR_CLR_S 12
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL_CNT_SERR_CLR_M 0x1000
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL_CNT_DERR_CLR_S 13
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_CTL_CNT_DERR_CLR_M 0x2000

/* D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_MASK */
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_MASK_SERR_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_MASK_SERR_M 0x1
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_MASK_DERR_S 1
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_MASK_DERR_M 0x2

/* D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_GLBL_ERR_MASK */
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_GLBL_ERR_MASK_SERR_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_GLBL_ERR_MASK_SERR_M 0x1
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_GLBL_ERR_MASK_DERR_S 1
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_GLBL_ERR_MASK_DERR_M 0x2

/* D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_STS */
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_STS_SYND_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_STS_SYND_M 0xFFFF
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_STS_SERR_S 16
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_STS_SERR_M 0x10000
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_STS_DERR_S 17
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_STS_DERR_M 0x20000

/* D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_ADDR */
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_ADDR_VAL_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_ADDR_VAL_M 0xFFFF

/* D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_CNT */
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_CNT_CNT_SERR_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_CNT_CNT_SERR_M 0xFF
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_CNT_SERR_TH_HIT_S 8
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_CNT_SERR_TH_HIT_M 0x100
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_CNT_CNT_DERR_S 9
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_CNT_CNT_DERR_M 0x1FE00
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_CNT_DERR_TH_HIT_S 17
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_ECC_ERR_CNT_DERR_TH_HIT_M 0x20000

/* D0_NIC0_RXB_CORE_SPECIAL_MEM_RM */
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_RM_VAL_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_MEM_RM_VAL_M 0x3FFFFFFF

/* D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK */
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_APB_PRIV_RD_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_APB_PRIV_RD_M 0x1
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_APB_SEC_RD_S 1
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_APB_SEC_RD_M 0x2
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_APB_UNMAPPED_RD_S 2
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_APB_UNMAPPED_RD_M 0x4
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_APB_PRIV_WR_S 3
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_APB_PRIV_WR_M 0x8
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_APB_SEC_WR_S 4
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_APB_SEC_WR_M 0x10
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_APB_UNMAPPED_WR_S 5
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_APB_UNMAPPED_WR_M 0x20
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_EXT_SEC_WR_S 16
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_EXT_SEC_WR_M 0x10000
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_EXT_UNMAPPED_WR_S 17
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_EXT_UNMAPPED_WR_M 0x20000
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_RD_TO_WO_S 24
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_RD_TO_WO_M 0x1000000
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_WR_TO_RO_S 25
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_MASK_WR_TO_RO_M 0x2000000

/* D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_ADDR */
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_ADDR_VAL_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_ADDR_VAL_M 0xFFFFFFFF

/* D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE */
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_PRIV_RD_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_PRIV_RD_M 0x1
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_SEC_RD_S 1
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_SEC_RD_M 0x2
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_UNMAPPED_RD_S 2
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_UNMAPPED_RD_M 0x4
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_PRIV_WR_S 3
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_PRIV_WR_M 0x8
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_SEC_WR_S 4
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_SEC_WR_M 0x10
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_UNMAPPED_WR_S 5
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_UNMAPPED_WR_M 0x20
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_EXT_SEC_WR_S 16
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_EXT_SEC_WR_M 0x10000
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_EXT_UNMAPPED_WR_S 17
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_EXT_UNMAPPED_WR_M 0x20000
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_RD_TO_WO_S 24
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_RD_TO_WO_M 0x1000000
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_WR_TO_RO_S 25
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_ERR_CAUSE_WR_TO_RO_M 0x2000000

/* D0_NIC0_RXB_CORE_SPECIAL_GLBL_SPARE */
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_SPARE_R_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_SPARE_R_M 0xFFFFFFFF

/* D0_NIC0_RXB_CORE_SPECIAL_GLBL_SEC */
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_SEC_VAL_S 0
#define D0_NIC0_RXB_CORE_SPECIAL_GLBL_SEC_VAL_M 0xFFFFFFFF

#endif /* ASIC_REG_D0_NIC0_RXB_CORE_SPECIAL_MASKS_H_ */
