/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_MASKS_H_
#define ASIC_REG_D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_MASKS_H_

/*
 *****************************************
 *   D0_NIC0_QPC_AXUSER_LBW_DB_FIFO
 *   (Prototype: AXUSER_LBW)
 *****************************************
 */

/* D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_LOCK_IND */
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_LOCK_IND_RD_S 0
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_LOCK_IND_RD_M 0x1
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_LOCK_IND_WR_S 4
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_LOCK_IND_WR_M 0x10

/* D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_RESERVED */
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_RESERVED_RD_3_1_S 0
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_RESERVED_RD_3_1_M 0x7
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_RESERVED_WR_3_1_S 4
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_RESERVED_WR_3_1_M 0x70

/* D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_LOCK_IND_OVRD */
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_LOCK_IND_OVRD_RD_S 0
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_LOCK_IND_OVRD_RD_M 0x1
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_LOCK_IND_OVRD_WR_S 4
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_LOCK_IND_OVRD_WR_M 0x10

/* D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_RESERVED_OVRD */
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_RESERVED_OVRD_RD_3_1_S 0
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_RESERVED_OVRD_RD_3_1_M 0x7
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_RESERVED_OVRD_WR_3_1_S 4
#define D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_LB_RESERVED_OVRD_WR_3_1_M 0x70

#endif /* ASIC_REG_D0_NIC0_QPC_AXUSER_LBW_DB_FIFO_MASKS_H_ */
