/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_D0_NIC0_MAC_GLOB_STAT_TX0_MASKS_H_
#define ASIC_REG_D0_NIC0_MAC_GLOB_STAT_TX0_MASKS_H_

/*
 *****************************************
 *   D0_NIC0_MAC_GLOB_STAT_TX0
 *   (Prototype: MAC_MAC0_TX_CNT)
 *****************************************
 */

/* D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSOCTETS_4 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSOCTETS_4_ETHERSTATSOCTETS_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSOCTETS_4_ETHERSTATSOCTETS_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_OCTETSTRANSMITTEDOK */
#define D0_NIC0_MAC_GLOB_STAT_TX0_OCTETSTRANSMITTEDOK_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_OCTETSTRANSMITTEDOK_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_APAUSEMACCTRLFRAMESTRANSMITTED */
#define D0_NIC0_MAC_GLOB_STAT_TX0_APAUSEMACCTRLFRAMESTRANSMITTED_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_APAUSEMACCTRLFRAMESTRANSMITTED_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_AFRAMESTRANSMITTEDOK */
#define D0_NIC0_MAC_GLOB_STAT_TX0_AFRAMESTRANSMITTEDOK_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_AFRAMESTRANSMITTEDOK_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_VLANTRANSMITTEDOK */
#define D0_NIC0_MAC_GLOB_STAT_TX0_VLANTRANSMITTEDOK_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_VLANTRANSMITTEDOK_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_IFOUTERRORS */
#define D0_NIC0_MAC_GLOB_STAT_TX0_IFOUTERRORS_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_IFOUTERRORS_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_IFOUTUCASTPKTS */
#define D0_NIC0_MAC_GLOB_STAT_TX0_IFOUTUCASTPKTS_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_IFOUTUCASTPKTS_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_IFOUTMULTICASTPKTS */
#define D0_NIC0_MAC_GLOB_STAT_TX0_IFOUTMULTICASTPKTS_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_IFOUTMULTICASTPKTS_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_IFOUTBROADCASTPKTS */
#define D0_NIC0_MAC_GLOB_STAT_TX0_IFOUTBROADCASTPKTS_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_IFOUTBROADCASTPKTS_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS64OCTETS_4 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS64OCTETS_4_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS64OCTETS_4_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS65TO127OCTETS_4 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS65TO127OCTETS_4_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS65TO127OCTETS_4_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS128TO255OCTETS_4 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS128TO255OCTETS_4_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS128TO255OCTETS_4_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS256TO511OCTETS_4 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS256TO511OCTETS_4_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS256TO511OCTETS_4_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS512TO1023OCTETS_4 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS512TO1023OCTETS_4_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS512TO1023OCTETS_4_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS1024TO1518OCTETS_4 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS1024TO1518OCTETS_4_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS1024TO1518OCTETS_4_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS1519TOMAXOCTETS_4 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS1519TOMAXOCTETS_4_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS1519TOMAXOCTETS_4_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED0 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED0_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED0_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED1 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED1_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED1_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED2 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED2_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED2_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED3 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED3_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED3_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED4 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED4_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED4_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED5 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED5_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED5_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED6 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED6_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED6_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED7 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED7_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED7_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_AMACCONTROLFRAMESTRANSMITTED */
#define D0_NIC0_MAC_GLOB_STAT_TX0_AMACCONTROLFRAMESTRANSMITTED_VAL_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_AMACCONTROLFRAMESTRANSMITTED_VAL_M 0xFFFFFFFF

/* D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS_4 */
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS_4_ETHERSTATSPKTS_S 0
#define D0_NIC0_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS_4_ETHERSTATSPKTS_M 0xFFFFFFFF

#endif /* ASIC_REG_D0_NIC0_MAC_GLOB_STAT_TX0_MASKS_H_ */
