/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_D0_NIC0_PHY_MASKS_H_
#define ASIC_REG_D0_NIC0_PHY_MASKS_H_

/*
 *****************************************
 *   D0_NIC0_PHY
 *   (Prototype: PRT_PHY)
 *****************************************
 */

/* D0_NIC0_PHY_PHY_CFG_ACCESS */
#define D0_NIC0_PHY_PHY_CFG_ACCESS_DATA_S 0
#define D0_NIC0_PHY_PHY_CFG_ACCESS_DATA_M 0xFFFFFFFF

/* D0_NIC0_PHY_PHY_CFG_ADDR */
#define D0_NIC0_PHY_PHY_CFG_ADDR_ADDR_S 0
#define D0_NIC0_PHY_PHY_CFG_ADDR_ADDR_M 0x7FFFFF

/* D0_NIC0_PHY_PHY_CFG_SEC */
#define D0_NIC0_PHY_PHY_CFG_SEC_PRIVILEGED_ACCESS_S 0
#define D0_NIC0_PHY_PHY_CFG_SEC_PRIVILEGED_ACCESS_M 0x1
#define D0_NIC0_PHY_PHY_CFG_SEC_NONSECURE_ACCESS_S 1
#define D0_NIC0_PHY_PHY_CFG_SEC_NONSECURE_ACCESS_M 0x2
#define D0_NIC0_PHY_PHY_CFG_SEC_INST_DATA_B_ACCESS_S 2
#define D0_NIC0_PHY_PHY_CFG_SEC_INST_DATA_B_ACCESS_M 0x4

/* D0_NIC0_PHY_PRT_AXI2APB_CFG */
#define D0_NIC0_PHY_PRT_AXI2APB_CFG_MASK_ERROR_RSP_S 0
#define D0_NIC0_PHY_PRT_AXI2APB_CFG_MASK_ERROR_RSP_M 0x1
#define D0_NIC0_PHY_PRT_AXI2APB_CFG_BLOCK_PARTIAL_STRB_S 1
#define D0_NIC0_PHY_PRT_AXI2APB_CFG_BLOCK_PARTIAL_STRB_M 0x2
#define D0_NIC0_PHY_PRT_AXI2APB_CFG_SPL_ERROR_RSP_S 2
#define D0_NIC0_PHY_PRT_AXI2APB_CFG_SPL_ERROR_RSP_M 0x4

/* D0_NIC0_PHY_PHY_RST_CFG */
#define D0_NIC0_PHY_PHY_RST_CFG_PHY_CFG_SW_0_RST_N_S 0
#define D0_NIC0_PHY_PHY_RST_CFG_PHY_CFG_SW_0_RST_N_M 0x1
#define D0_NIC0_PHY_PHY_RST_CFG_PHY_CFG_SW_1_RST_N_S 1
#define D0_NIC0_PHY_PHY_RST_CFG_PHY_CFG_SW_1_RST_N_M 0x2
#define D0_NIC0_PHY_PHY_RST_CFG_PHY_CFG_SW_2_RST_N_S 2
#define D0_NIC0_PHY_PHY_RST_CFG_PHY_CFG_SW_2_RST_N_M 0x4
#define D0_NIC0_PHY_PHY_RST_CFG_PHY_CFG_SW_3_RST_N_S 3
#define D0_NIC0_PHY_PHY_RST_CFG_PHY_CFG_SW_3_RST_N_M 0x8
#define D0_NIC0_PHY_PHY_RST_CFG_PHY_CFG_SW_POR_RST_N_S 4
#define D0_NIC0_PHY_PHY_RST_CFG_PHY_CFG_SW_POR_RST_N_M 0x10
#define D0_NIC0_PHY_PHY_RST_CFG_PHY_CFG_SW_APB_RST_N_S 5
#define D0_NIC0_PHY_PHY_RST_CFG_PHY_CFG_SW_APB_RST_N_M 0x20

/* D0_NIC0_PHY_PHY_REFCLK_MUX */
#define D0_NIC0_PHY_PHY_REFCLK_MUX_ICTL_REF_LS_ENA_A_S 0
#define D0_NIC0_PHY_PHY_REFCLK_MUX_ICTL_REF_LS_ENA_A_M 0x1
#define D0_NIC0_PHY_PHY_REFCLK_MUX_ICTL_REF_CML_LS_R2L_1_SEL_S 1
#define D0_NIC0_PHY_PHY_REFCLK_MUX_ICTL_REF_CML_LS_R2L_1_SEL_M 0x6
#define D0_NIC0_PHY_PHY_REFCLK_MUX_ICTL_REF_CML_LS_R2L_0_SEL_S 3
#define D0_NIC0_PHY_PHY_REFCLK_MUX_ICTL_REF_CML_LS_R2L_0_SEL_M 0x18
#define D0_NIC0_PHY_PHY_REFCLK_MUX_ICTL_REF_CML_LS_L2R_1_SEL_S 5
#define D0_NIC0_PHY_PHY_REFCLK_MUX_ICTL_REF_CML_LS_L2R_1_SEL_M 0x60
#define D0_NIC0_PHY_PHY_REFCLK_MUX_ICTL_REF_CML_LS_L2R_0_SEL_S 7
#define D0_NIC0_PHY_PHY_REFCLK_MUX_ICTL_REF_CML_LS_L2R_0_SEL_M 0x180
#define D0_NIC0_PHY_PHY_REFCLK_MUX_ICTL_REF_LS_MUX_SEL_S 9
#define D0_NIC0_PHY_PHY_REFCLK_MUX_ICTL_REF_LS_MUX_SEL_M 0xE00

/* D0_NIC0_PHY_PHY_SD_CFG */
#define D0_NIC0_PHY_PHY_SD_CFG_RX_DATA_VLD_OVRD_S 0
#define D0_NIC0_PHY_PHY_SD_CFG_RX_DATA_VLD_OVRD_M 0xF
#define D0_NIC0_PHY_PHY_SD_CFG_TX_DATA_VLD_OVRD_S 4
#define D0_NIC0_PHY_PHY_SD_CFG_TX_DATA_VLD_OVRD_M 0xF0

/* D0_NIC0_PHY_PHY_EQ_EN */
#define D0_NIC0_PHY_PHY_EQ_EN_ANLT_LINK_GOOD_S 0
#define D0_NIC0_PHY_PHY_EQ_EN_ANLT_LINK_GOOD_M 0xF
#define D0_NIC0_PHY_PHY_EQ_EN_ANLT_DONE_S 4
#define D0_NIC0_PHY_PHY_EQ_EN_ANLT_DONE_M 0xF0

/* D0_NIC0_PHY_PHY_ANLT */
#define D0_NIC0_PHY_PHY_ANLT_LANE0_GROUP_S 0
#define D0_NIC0_PHY_PHY_ANLT_LANE0_GROUP_M 0x1
#define D0_NIC0_PHY_PHY_ANLT_LANE0_MASTER_S 1
#define D0_NIC0_PHY_PHY_ANLT_LANE0_MASTER_M 0x2
#define D0_NIC0_PHY_PHY_ANLT_LANE1_GROUP_S 2
#define D0_NIC0_PHY_PHY_ANLT_LANE1_GROUP_M 0x4
#define D0_NIC0_PHY_PHY_ANLT_LANE1_MASTER_S 3
#define D0_NIC0_PHY_PHY_ANLT_LANE1_MASTER_M 0x8
#define D0_NIC0_PHY_PHY_ANLT_LANE2_GROUP_S 4
#define D0_NIC0_PHY_PHY_ANLT_LANE2_GROUP_M 0x10
#define D0_NIC0_PHY_PHY_ANLT_LANE2_MASTER_S 5
#define D0_NIC0_PHY_PHY_ANLT_LANE2_MASTER_M 0x20
#define D0_NIC0_PHY_PHY_ANLT_LANE3_GROUP_S 6
#define D0_NIC0_PHY_PHY_ANLT_LANE3_GROUP_M 0x40
#define D0_NIC0_PHY_PHY_ANLT_LANE3_MASTER_S 7
#define D0_NIC0_PHY_PHY_ANLT_LANE3_MASTER_M 0x80

/* D0_NIC0_PHY_PHY_SIG_DETECT */
#define D0_NIC0_PHY_PHY_SIG_DETECT_LANE0_S 0
#define D0_NIC0_PHY_PHY_SIG_DETECT_LANE0_M 0x1
#define D0_NIC0_PHY_PHY_SIG_DETECT_LANE1_S 1
#define D0_NIC0_PHY_PHY_SIG_DETECT_LANE1_M 0x2
#define D0_NIC0_PHY_PHY_SIG_DETECT_LANE2_S 2
#define D0_NIC0_PHY_PHY_SIG_DETECT_LANE2_M 0x4
#define D0_NIC0_PHY_PHY_SIG_DETECT_LANE3_S 3
#define D0_NIC0_PHY_PHY_SIG_DETECT_LANE3_M 0x8

#endif /* ASIC_REG_D0_NIC0_PHY_MASKS_H_ */
