/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_D0_NIC0_QPC_AXUSER_HBW_RXWQE_REGS_H_
#define ASIC_REG_D0_NIC0_QPC_AXUSER_HBW_RXWQE_REGS_H_

/*
 *****************************************
 *   D0_NIC0_QPC_AXUSER_HBW_RXWQE
 *   (Prototype: AXUSER_HBW)
 *****************************************
 */

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_MMU_BYPASS 0xD023180

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_ASID 0xD023184

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_QOS 0xD023188

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_MCID 0xD02318C

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_CLASS_TYPE 0xD023190

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_REDUCTION 0xD023194

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_ATOMIC 0xD023198

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_DOWN_CONV 0xD02319C

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_MMU_PF_EN 0xD0231A0

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_STRONG_ORDER 0xD0231A4

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_RESERVED 0xD0231A8

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_MMU_BYPASS_OVRD 0xD0231B0

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_ASID_OVRD 0xD0231B4

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_QOS_OVRD 0xD0231B8

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_MCID_OVRD 0xD0231BC

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_CLASS_TYPE_OVRD 0xD0231C0

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_REDUCTION_OVRD 0xD0231C4

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_ATOMIC_OVRD 0xD0231C8

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_DOWN_CONV_OVRD 0xD0231CC

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_MMU_PF_EN_OVRD 0xD0231D0

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_STRONG_ORDER_OVRD 0xD0231D4

#define mmD0_NIC0_QPC_AXUSER_HBW_RXWQE_HB_RESERVED_OVRD 0xD0231D8

#endif /* ASIC_REG_D0_NIC0_QPC_AXUSER_HBW_RXWQE_REGS_H_ */
