/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_D0_PSOC_CS_TRACE_MASKS_H_
#define ASIC_REG_D0_PSOC_CS_TRACE_MASKS_H_

/*
 *****************************************
 *   D0_PSOC_CS_TRACE
 *   (Prototype: CS_TRACE)
 *****************************************
 */

/* D0_PSOC_CS_TRACE_TOP_ROM_TABLE */
#define D0_PSOC_CS_TRACE_TOP_ROM_TABLE_ROM_VALID_S 0
#define D0_PSOC_CS_TRACE_TOP_ROM_TABLE_ROM_VALID_M 0xFFFFFFFF

/* D0_PSOC_CS_TRACE_D0_SHARED_ROM_TABLE */
#define D0_PSOC_CS_TRACE_D0_SHARED_ROM_TABLE_ROM_VALID_S 0
#define D0_PSOC_CS_TRACE_D0_SHARED_ROM_TABLE_ROM_VALID_M 0xFFFFFFFF

/* D0_PSOC_CS_TRACE_D1_SHARED_ROM_TABLE */
#define D0_PSOC_CS_TRACE_D1_SHARED_ROM_TABLE_ROM_VALID_S 0
#define D0_PSOC_CS_TRACE_D1_SHARED_ROM_TABLE_ROM_VALID_M 0xFFFFFFFF

/* D0_PSOC_CS_TRACE_D0_NIC_ROM_TABLE */
#define D0_PSOC_CS_TRACE_D0_NIC_ROM_TABLE_ROM_VALID_S 0
#define D0_PSOC_CS_TRACE_D0_NIC_ROM_TABLE_ROM_VALID_M 0xFFFFFFFF

/* D0_PSOC_CS_TRACE_D1_NIC_ROM_TABLE */
#define D0_PSOC_CS_TRACE_D1_NIC_ROM_TABLE_ROM_VALID_S 0
#define D0_PSOC_CS_TRACE_D1_NIC_ROM_TABLE_ROM_VALID_M 0xFFFFFFFF

/* D0_PSOC_CS_TRACE_HD5_ROM_TABLE */
#define D0_PSOC_CS_TRACE_HD5_ROM_TABLE_ROM_VALID_S 0
#define D0_PSOC_CS_TRACE_HD5_ROM_TABLE_ROM_VALID_M 0xFFFFFFFF

/* D0_PSOC_CS_TRACE_HD1_ROM_TABLE */
#define D0_PSOC_CS_TRACE_HD1_ROM_TABLE_ROM_VALID_S 0
#define D0_PSOC_CS_TRACE_HD1_ROM_TABLE_ROM_VALID_M 0xFFFFFFFF

/* D0_PSOC_CS_TRACE_HD3_ROM_TABLE */
#define D0_PSOC_CS_TRACE_HD3_ROM_TABLE_ROM_VALID_S 0
#define D0_PSOC_CS_TRACE_HD3_ROM_TABLE_ROM_VALID_M 0xFFFFFFFF

/* D0_PSOC_CS_TRACE_HD6_ROM_TABLE */
#define D0_PSOC_CS_TRACE_HD6_ROM_TABLE_ROM_VALID_S 0
#define D0_PSOC_CS_TRACE_HD6_ROM_TABLE_ROM_VALID_M 0xFFFFFFFF

/* D0_PSOC_CS_TRACE_HD2_ROM_TABLE */
#define D0_PSOC_CS_TRACE_HD2_ROM_TABLE_ROM_VALID_S 0
#define D0_PSOC_CS_TRACE_HD2_ROM_TABLE_ROM_VALID_M 0xFFFFFFFF

/* D0_PSOC_CS_TRACE_HD7_ROM_TABLE */
#define D0_PSOC_CS_TRACE_HD7_ROM_TABLE_ROM_VALID_S 0
#define D0_PSOC_CS_TRACE_HD7_ROM_TABLE_ROM_VALID_M 0xFFFFFFFF

/* D0_PSOC_CS_TRACE_HD4_ROM_TABLE */
#define D0_PSOC_CS_TRACE_HD4_ROM_TABLE_ROM_VALID_S 0
#define D0_PSOC_CS_TRACE_HD4_ROM_TABLE_ROM_VALID_M 0xFFFFFFFF

/* D0_PSOC_CS_TRACE_HD0_ROM_TABLE */
#define D0_PSOC_CS_TRACE_HD0_ROM_TABLE_ROM_VALID_S 0
#define D0_PSOC_CS_TRACE_HD0_ROM_TABLE_ROM_VALID_M 0xFFFFFFFF

/* D0_PSOC_CS_TRACE_SECURITY_CTRL */
#define D0_PSOC_CS_TRACE_SECURITY_CTRL_LOCK_DAP_AP_TO_DBG_S 0
#define D0_PSOC_CS_TRACE_SECURITY_CTRL_LOCK_DAP_AP_TO_DBG_M 0x1
#define D0_PSOC_CS_TRACE_SECURITY_CTRL_LOCK_DAP_PSLVERR_S 1
#define D0_PSOC_CS_TRACE_SECURITY_CTRL_LOCK_DAP_PSLVERR_M 0x2

/* D0_PSOC_CS_TRACE_ETR_FLUSH */
#define D0_PSOC_CS_TRACE_ETR_FLUSH_MASK_S 0
#define D0_PSOC_CS_TRACE_ETR_FLUSH_MASK_M 0x1

/* D0_PSOC_CS_TRACE_ETR_ARB_APB */
#define D0_PSOC_CS_TRACE_ETR_ARB_APB_TO_S 0
#define D0_PSOC_CS_TRACE_ETR_ARB_APB_TO_M 0xFFFF

/* D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CFG */
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CFG_FORCE_RSP_OK_S 0
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CFG_FORCE_RSP_OK_M 0x1
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CFG_FORCE_WR_BUF_S 1
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CFG_FORCE_WR_BUF_M 0x2

/* D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CACHE */
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CACHE_OVR_AXI_RD_S 0
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CACHE_OVR_AXI_RD_M 0xF
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CACHE_OVR_EN_AXI_RD_S 4
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CACHE_OVR_EN_AXI_RD_M 0xF0
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CACHE_OVR_AXI_WR_S 8
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CACHE_OVR_AXI_WR_M 0xF00
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CACHE_OVR_EN_AXI_WR_S 12
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CACHE_OVR_EN_AXI_WR_M 0xF000

/* D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_PROT */
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_PROT_OVR_AXI_RD_S 0
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_PROT_OVR_AXI_RD_M 0x7
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_PROT_OVR_EN_AXI_RD_S 4
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_PROT_OVR_EN_AXI_RD_M 0x70
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_PROT_OVR_AXI_WR_S 8
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_PROT_OVR_AXI_WR_M 0x700
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_PROT_OVR_EN_AXI_WR_S 12
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_PROT_OVR_EN_AXI_WR_M 0x7000

/* D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CFG_OS */
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CFG_OS_NUM_RD_OS_S 0
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CFG_OS_NUM_RD_OS_M 0xFFFF
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CFG_OS_NUM_WR_OS_S 16
#define D0_PSOC_CS_TRACE_ETR_AXI_SPLIT_CFG_OS_NUM_WR_OS_M 0xFFFF0000

/* D0_PSOC_CS_TRACE_TRACE_ADDR */
#define D0_PSOC_CS_TRACE_TRACE_ADDR_MSB_S 0
#define D0_PSOC_CS_TRACE_TRACE_ADDR_MSB_M 0xFFFFFFFF

#endif /* ASIC_REG_D0_PSOC_CS_TRACE_MASKS_H_ */
