/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DTLB_SPECIAL_REGS_H_
#define ASIC_REG_DTLB_SPECIAL_REGS_H_

/*
 *****************************************
 *   DTLB_SPECIAL
 *   (Prototype: SPECIAL_REGS)
 *****************************************
 */

#define mmDTLB_SPECIAL_GLBL_PRIV_0 0x0

#define mmDTLB_SPECIAL_GLBL_PRIV_1 0x4

#define mmDTLB_SPECIAL_GLBL_PRIV_2 0x8

#define mmDTLB_SPECIAL_GLBL_PRIV_3 0xC

#define mmDTLB_SPECIAL_GLBL_PRIV_4 0x10

#define mmDTLB_SPECIAL_GLBL_PRIV_5 0x14

#define mmDTLB_SPECIAL_GLBL_PRIV_6 0x18

#define mmDTLB_SPECIAL_GLBL_PRIV_7 0x1C

#define mmDTLB_SPECIAL_GLBL_PRIV_8 0x20

#define mmDTLB_SPECIAL_GLBL_PRIV_9 0x24

#define mmDTLB_SPECIAL_GLBL_PRIV_10 0x28

#define mmDTLB_SPECIAL_GLBL_PRIV_11 0x2C

#define mmDTLB_SPECIAL_GLBL_PRIV_12 0x30

#define mmDTLB_SPECIAL_GLBL_PRIV_13 0x34

#define mmDTLB_SPECIAL_GLBL_PRIV_14 0x38

#define mmDTLB_SPECIAL_GLBL_PRIV_15 0x3C

#define mmDTLB_SPECIAL_GLBL_PRIV_16 0x40

#define mmDTLB_SPECIAL_GLBL_PRIV_17 0x44

#define mmDTLB_SPECIAL_GLBL_PRIV_18 0x48

#define mmDTLB_SPECIAL_GLBL_PRIV_19 0x4C

#define mmDTLB_SPECIAL_GLBL_PRIV_20 0x50

#define mmDTLB_SPECIAL_GLBL_PRIV_21 0x54

#define mmDTLB_SPECIAL_GLBL_PRIV_22 0x58

#define mmDTLB_SPECIAL_GLBL_PRIV_23 0x5C

#define mmDTLB_SPECIAL_GLBL_PRIV_24 0x60

#define mmDTLB_SPECIAL_GLBL_PRIV_25 0x64

#define mmDTLB_SPECIAL_GLBL_PRIV_26 0x68

#define mmDTLB_SPECIAL_GLBL_PRIV_27 0x6C

#define mmDTLB_SPECIAL_GLBL_PRIV_28 0x70

#define mmDTLB_SPECIAL_GLBL_PRIV_29 0x74

#define mmDTLB_SPECIAL_GLBL_PRIV_30 0x78

#define mmDTLB_SPECIAL_GLBL_PRIV_31 0x7C

#define mmDTLB_SPECIAL_MEM_GW_DATA 0x80

#define mmDTLB_SPECIAL_MEM_GW_REQ 0x84

#define mmDTLB_SPECIAL_MEM_NUMOF 0x8C

#define mmDTLB_SPECIAL_MEM_ECC_SEL 0x90

#define mmDTLB_SPECIAL_MEM_ECC_CTL 0x94

#define mmDTLB_SPECIAL_MEM_ECC_ERR_MASK 0x98

#define mmDTLB_SPECIAL_MEM_ECC_GLBL_ERR_MASK 0x9C

#define mmDTLB_SPECIAL_MEM_ECC_ERR_STS 0xA0

#define mmDTLB_SPECIAL_MEM_ECC_ERR_ADDR 0xA4

#define mmDTLB_SPECIAL_MEM_ECC_ERR_CNT 0xA8

#define mmDTLB_SPECIAL_MEM_RM 0xAC

#define mmDTLB_SPECIAL_GLBL_ERR_MASK 0xC0

#define mmDTLB_SPECIAL_GLBL_ERR_ADDR 0xC4

#define mmDTLB_SPECIAL_GLBL_ERR_CAUSE 0xC8

#define mmDTLB_SPECIAL_GLBL_SPARE_0 0xE0

#define mmDTLB_SPECIAL_GLBL_SPARE_1 0xE4

#define mmDTLB_SPECIAL_GLBL_SPARE_2 0xE8

#define mmDTLB_SPECIAL_GLBL_SPARE_3 0xEC

#define mmDTLB_SPECIAL_GLBL_SEC_0 0x100

#define mmDTLB_SPECIAL_GLBL_SEC_1 0x104

#define mmDTLB_SPECIAL_GLBL_SEC_2 0x108

#define mmDTLB_SPECIAL_GLBL_SEC_3 0x10C

#define mmDTLB_SPECIAL_GLBL_SEC_4 0x110

#define mmDTLB_SPECIAL_GLBL_SEC_5 0x114

#define mmDTLB_SPECIAL_GLBL_SEC_6 0x118

#define mmDTLB_SPECIAL_GLBL_SEC_7 0x11C

#define mmDTLB_SPECIAL_GLBL_SEC_8 0x120

#define mmDTLB_SPECIAL_GLBL_SEC_9 0x124

#define mmDTLB_SPECIAL_GLBL_SEC_10 0x128

#define mmDTLB_SPECIAL_GLBL_SEC_11 0x12C

#define mmDTLB_SPECIAL_GLBL_SEC_12 0x130

#define mmDTLB_SPECIAL_GLBL_SEC_13 0x134

#define mmDTLB_SPECIAL_GLBL_SEC_14 0x138

#define mmDTLB_SPECIAL_GLBL_SEC_15 0x13C

#define mmDTLB_SPECIAL_GLBL_SEC_16 0x140

#define mmDTLB_SPECIAL_GLBL_SEC_17 0x144

#define mmDTLB_SPECIAL_GLBL_SEC_18 0x148

#define mmDTLB_SPECIAL_GLBL_SEC_19 0x14C

#define mmDTLB_SPECIAL_GLBL_SEC_20 0x150

#define mmDTLB_SPECIAL_GLBL_SEC_21 0x154

#define mmDTLB_SPECIAL_GLBL_SEC_22 0x158

#define mmDTLB_SPECIAL_GLBL_SEC_23 0x15C

#define mmDTLB_SPECIAL_GLBL_SEC_24 0x160

#define mmDTLB_SPECIAL_GLBL_SEC_25 0x164

#define mmDTLB_SPECIAL_GLBL_SEC_26 0x168

#define mmDTLB_SPECIAL_GLBL_SEC_27 0x16C

#define mmDTLB_SPECIAL_GLBL_SEC_28 0x170

#define mmDTLB_SPECIAL_GLBL_SEC_29 0x174

#define mmDTLB_SPECIAL_GLBL_SEC_30 0x178

#define mmDTLB_SPECIAL_GLBL_SEC_31 0x17C

#endif /* ASIC_REG_DTLB_SPECIAL_REGS_H_ */
