/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_GLOBAL_CONF_MASKS_H_
#define ASIC_REG_GLOBAL_CONF_MASKS_H_

/*
 *****************************************
 *   GLOBAL_CONF
 *   (Prototype: GLOBAL_CONF)
 *****************************************
 */

/* GLOBAL_CONF_NON_RST_FLOPS */
#define GLOBAL_CONF_NON_RST_FLOPS_VAL_S 0
#define GLOBAL_CONF_NON_RST_FLOPS_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_BOOT_GPIO_SET_DURATION */
#define GLOBAL_CONF_BOOT_GPIO_SET_DURATION_READY_S 0
#define GLOBAL_CONF_BOOT_GPIO_SET_DURATION_READY_M 0xFFFF
#define GLOBAL_CONF_BOOT_GPIO_SET_DURATION_RECOVERY_S 16
#define GLOBAL_CONF_BOOT_GPIO_SET_DURATION_RECOVERY_M 0xFFFF0000

/* GLOBAL_CONF_BMAN_READY_GPIO_WD_CTRL */
#define GLOBAL_CONF_BMAN_READY_GPIO_WD_CTRL_DURATION_S 0
#define GLOBAL_CONF_BMAN_READY_GPIO_WD_CTRL_DURATION_M 0xFFFFFF
#define GLOBAL_CONF_BMAN_READY_GPIO_WD_CTRL_SET_S 24
#define GLOBAL_CONF_BMAN_READY_GPIO_WD_CTRL_SET_M 0x1000000
#define GLOBAL_CONF_BMAN_READY_GPIO_WD_CTRL_DEC_S 25
#define GLOBAL_CONF_BMAN_READY_GPIO_WD_CTRL_DEC_M 0x2000000
#define GLOBAL_CONF_BMAN_READY_GPIO_WD_CTRL_DIS_S 26
#define GLOBAL_CONF_BMAN_READY_GPIO_WD_CTRL_DIS_M 0x4000000

/* GLOBAL_CONF_BMAN_READY_GPIO_WD_STS */
#define GLOBAL_CONF_BMAN_READY_GPIO_WD_STS_VAL_S 0
#define GLOBAL_CONF_BMAN_READY_GPIO_WD_STS_VAL_M 0xFFFFFF
#define GLOBAL_CONF_BMAN_READY_GPIO_WD_STS_ACTIVE_S 24
#define GLOBAL_CONF_BMAN_READY_GPIO_WD_STS_ACTIVE_M 0x1000000

/* GLOBAL_CONF_BMAN_READY_GPIO_STS */
#define GLOBAL_CONF_BMAN_READY_GPIO_STS_DIE_READY_IN_S 0
#define GLOBAL_CONF_BMAN_READY_GPIO_STS_DIE_READY_IN_M 0x1
#define GLOBAL_CONF_BMAN_READY_GPIO_STS_DIE_READY_IN_EXPR_S 1
#define GLOBAL_CONF_BMAN_READY_GPIO_STS_DIE_READY_IN_EXPR_M 0x2
#define GLOBAL_CONF_BMAN_READY_GPIO_STS_RSRVD_S 2
#define GLOBAL_CONF_BMAN_READY_GPIO_STS_RSRVD_M 0xFFFFFFFC

/* GLOBAL_CONF_BOOT_SEQ_RE_START */
#define GLOBAL_CONF_BOOT_SEQ_RE_START_IND_S 0
#define GLOBAL_CONF_BOOT_SEQ_RE_START_IND_M 0x1
#define GLOBAL_CONF_BOOT_SEQ_RE_START_MNL_RST_IND_S 4
#define GLOBAL_CONF_BOOT_SEQ_RE_START_MNL_RST_IND_M 0x10
#define GLOBAL_CONF_BOOT_SEQ_RE_START_WD_RST_IND_S 5
#define GLOBAL_CONF_BOOT_SEQ_RE_START_WD_RST_IND_M 0x20
#define GLOBAL_CONF_BOOT_SEQ_RE_START_SW_RST_IND_S 6
#define GLOBAL_CONF_BOOT_SEQ_RE_START_SW_RST_IND_M 0x40
#define GLOBAL_CONF_BOOT_SEQ_RE_START_SOFT_RST_IND_S 7
#define GLOBAL_CONF_BOOT_SEQ_RE_START_SOFT_RST_IND_M 0x80
#define GLOBAL_CONF_BOOT_SEQ_RE_START_PRST_RST_IND_S 8
#define GLOBAL_CONF_BOOT_SEQ_RE_START_PRST_RST_IND_M 0x100
#define GLOBAL_CONF_BOOT_SEQ_RE_START_FLR_RST_IND_S 9
#define GLOBAL_CONF_BOOT_SEQ_RE_START_FLR_RST_IND_M 0x200
#define GLOBAL_CONF_BOOT_SEQ_RE_START_FW_RST_IND_S 10
#define GLOBAL_CONF_BOOT_SEQ_RE_START_FW_RST_IND_M 0x400
#define GLOBAL_CONF_BOOT_SEQ_RE_START_ECC_DERR_RST_IND_S 11
#define GLOBAL_CONF_BOOT_SEQ_RE_START_ECC_DERR_RST_IND_M 0x800

/* GLOBAL_CONF_BTM_FSM */
#define GLOBAL_CONF_BTM_FSM_STATE_S 0
#define GLOBAL_CONF_BTM_FSM_STATE_M 0x1F

/* GLOBAL_CONF_SW_BTM_FSM */
#define GLOBAL_CONF_SW_BTM_FSM_CTRL_S 0
#define GLOBAL_CONF_SW_BTM_FSM_CTRL_M 0x1F

/* GLOBAL_CONF_SW_BOOT_SEQ_FSM */
#define GLOBAL_CONF_SW_BOOT_SEQ_FSM_CTRL_S 0
#define GLOBAL_CONF_SW_BOOT_SEQ_FSM_CTRL_M 0x1F

/* GLOBAL_CONF_BOOT_SEQ_TIMEOUT */
#define GLOBAL_CONF_BOOT_SEQ_TIMEOUT_VAL_S 0
#define GLOBAL_CONF_BOOT_SEQ_TIMEOUT_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_BMAN_FLR_GPIO_STS */
#define GLOBAL_CONF_BMAN_FLR_GPIO_STS_VAL_S 0
#define GLOBAL_CONF_BMAN_FLR_GPIO_STS_VAL_M 0xFFFF
#define GLOBAL_CONF_BMAN_FLR_GPIO_STS_ACTIVE_S 16
#define GLOBAL_CONF_BMAN_FLR_GPIO_STS_ACTIVE_M 0x10000

/* GLOBAL_CONF_BMAN_FLR_GPIO_CTRL */
#define GLOBAL_CONF_BMAN_FLR_GPIO_CTRL_DURATION_S 0
#define GLOBAL_CONF_BMAN_FLR_GPIO_CTRL_DURATION_M 0xFFFF
#define GLOBAL_CONF_BMAN_FLR_GPIO_CTRL_SET_S 16
#define GLOBAL_CONF_BMAN_FLR_GPIO_CTRL_SET_M 0x10000
#define GLOBAL_CONF_BMAN_FLR_GPIO_CTRL_INC_S 17
#define GLOBAL_CONF_BMAN_FLR_GPIO_CTRL_INC_M 0x20000
#define GLOBAL_CONF_BMAN_FLR_GPIO_CTRL_DEC_S 18
#define GLOBAL_CONF_BMAN_FLR_GPIO_CTRL_DEC_M 0x40000
#define GLOBAL_CONF_BMAN_FLR_GPIO_CTRL_DIS_S 19
#define GLOBAL_CONF_BMAN_FLR_GPIO_CTRL_DIS_M 0x80000

/* GLOBAL_CONF_SPI_MEM_EN */
#define GLOBAL_CONF_SPI_MEM_EN_IND_SPI_S 0
#define GLOBAL_CONF_SPI_MEM_EN_IND_SPI_M 0x1
#define GLOBAL_CONF_SPI_MEM_EN_IND_QSPI_S 1
#define GLOBAL_CONF_SPI_MEM_EN_IND_QSPI_M 0x2

/* GLOBAL_CONF_PRSTN */
#define GLOBAL_CONF_PRSTN_VAL_S 0
#define GLOBAL_CONF_PRSTN_VAL_M 0x1

/* GLOBAL_CONF_BMAN_READY_CTRL */
#define GLOBAL_CONF_BMAN_READY_CTRL_READY_OUT_LATCH_S 0
#define GLOBAL_CONF_BMAN_READY_CTRL_READY_OUT_LATCH_M 0x1

/* GLOBAL_CONF_PHY_STABLE */
#define GLOBAL_CONF_PHY_STABLE_PRSTN_S 0
#define GLOBAL_CONF_PHY_STABLE_PRSTN_M 0x1

/* GLOBAL_CONF_SPI_IMG_STS */
#define GLOBAL_CONF_SPI_IMG_STS_SPI_PRI_S 0
#define GLOBAL_CONF_SPI_IMG_STS_SPI_PRI_M 0x3
#define GLOBAL_CONF_SPI_IMG_STS_SPI_SEC_S 2
#define GLOBAL_CONF_SPI_IMG_STS_SPI_SEC_M 0xC
#define GLOBAL_CONF_SPI_IMG_STS_PRSTN_PRI_S 4
#define GLOBAL_CONF_SPI_IMG_STS_PRSTN_PRI_M 0x30
#define GLOBAL_CONF_SPI_IMG_STS_PRSTN_SEC_S 6
#define GLOBAL_CONF_SPI_IMG_STS_PRSTN_SEC_M 0xC0
#define GLOBAL_CONF_SPI_IMG_STS_PRSTN_DEASSERT_PRI_S 8
#define GLOBAL_CONF_SPI_IMG_STS_PRSTN_DEASSERT_PRI_M 0x300
#define GLOBAL_CONF_SPI_IMG_STS_PRSTN_DEASSERT_SEC_S 10
#define GLOBAL_CONF_SPI_IMG_STS_PRSTN_DEASSERT_SEC_M 0xC00
#define GLOBAL_CONF_SPI_IMG_STS_PRE_SPI_PRI_S 12
#define GLOBAL_CONF_SPI_IMG_STS_PRE_SPI_PRI_M 0x3000
#define GLOBAL_CONF_SPI_IMG_STS_PRE_PRSTN_PRI_S 14
#define GLOBAL_CONF_SPI_IMG_STS_PRE_PRSTN_PRI_M 0xC000
#define GLOBAL_CONF_SPI_IMG_STS_PRE_SPI_SEC_S 16
#define GLOBAL_CONF_SPI_IMG_STS_PRE_SPI_SEC_M 0x30000
#define GLOBAL_CONF_SPI_IMG_STS_PRE_PRSTN_SEC_S 18
#define GLOBAL_CONF_SPI_IMG_STS_PRE_PRSTN_SEC_M 0xC0000
#define GLOBAL_CONF_SPI_IMG_STS_PCIE_FW_PRI_S 20
#define GLOBAL_CONF_SPI_IMG_STS_PCIE_FW_PRI_M 0x300000
#define GLOBAL_CONF_SPI_IMG_STS_PCIE_FW_SEC_S 22
#define GLOBAL_CONF_SPI_IMG_STS_PCIE_FW_SEC_M 0xC00000

/* GLOBAL_CONF_BOOT_SEQ_FSM */
#define GLOBAL_CONF_BOOT_SEQ_FSM_IDLE_S 0
#define GLOBAL_CONF_BOOT_SEQ_FSM_IDLE_M 0x1
#define GLOBAL_CONF_BOOT_SEQ_FSM_BOOT_INIT_S 1
#define GLOBAL_CONF_BOOT_SEQ_FSM_BOOT_INIT_M 0x2
#define GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PRI_S 2
#define GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PRI_M 0x4
#define GLOBAL_CONF_BOOT_SEQ_FSM_SPI_SEC_S 3
#define GLOBAL_CONF_BOOT_SEQ_FSM_SPI_SEC_M 0x8
#define GLOBAL_CONF_BOOT_SEQ_FSM_PRSTN_PRI_S 4
#define GLOBAL_CONF_BOOT_SEQ_FSM_PRSTN_PRI_M 0x10
#define GLOBAL_CONF_BOOT_SEQ_FSM_PRSTN_SEC_S 5
#define GLOBAL_CONF_BOOT_SEQ_FSM_PRSTN_SEC_M 0x20
#define GLOBAL_CONF_BOOT_SEQ_FSM_BTL_ROM_S 6
#define GLOBAL_CONF_BOOT_SEQ_FSM_BTL_ROM_M 0x40
#define GLOBAL_CONF_BOOT_SEQ_FSM_PCLK_READY_S 7
#define GLOBAL_CONF_BOOT_SEQ_FSM_PCLK_READY_M 0x80
#define GLOBAL_CONF_BOOT_SEQ_FSM_LTSSM_EN_S 8
#define GLOBAL_CONF_BOOT_SEQ_FSM_LTSSM_EN_M 0x100
#define GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PRE_S 9
#define GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PRE_M 0x200
#define GLOBAL_CONF_BOOT_SEQ_FSM_PRSTN_PRE_S 10
#define GLOBAL_CONF_BOOT_SEQ_FSM_PRSTN_PRE_M 0x400
#define GLOBAL_CONF_BOOT_SEQ_FSM_PRSTN_WAIT_S 11
#define GLOBAL_CONF_BOOT_SEQ_FSM_PRSTN_WAIT_M 0x800
#define GLOBAL_CONF_BOOT_SEQ_FSM_PCIE_FW_PRI_S 12
#define GLOBAL_CONF_BOOT_SEQ_FSM_PCIE_FW_PRI_M 0x1000
#define GLOBAL_CONF_BOOT_SEQ_FSM_PCIE_FW_SEC_S 13
#define GLOBAL_CONF_BOOT_SEQ_FSM_PCIE_FW_SEC_M 0x2000
#define GLOBAL_CONF_BOOT_SEQ_FSM_PRSTN_DEASSERT_PRI_S 14
#define GLOBAL_CONF_BOOT_SEQ_FSM_PRSTN_DEASSERT_PRI_M 0x4000
#define GLOBAL_CONF_BOOT_SEQ_FSM_PRSTN_DEASSERT_SEC_S 15
#define GLOBAL_CONF_BOOT_SEQ_FSM_PRSTN_DEASSERT_SEC_M 0x8000
#define GLOBAL_CONF_BOOT_SEQ_FSM_BSEQ_FSM_S 16
#define GLOBAL_CONF_BOOT_SEQ_FSM_BSEQ_FSM_M 0x1F0000

/* GLOBAL_CONF_BOOT_SEQ_EXT_LD */
#define GLOBAL_CONF_BOOT_SEQ_EXT_LD_DONE_S 0
#define GLOBAL_CONF_BOOT_SEQ_EXT_LD_DONE_M 0x1

/* GLOBAL_CONF_QSPI_SPI_BOOTSEQ_RST */
#define GLOBAL_CONF_QSPI_SPI_BOOTSEQ_RST_VAL_S 0
#define GLOBAL_CONF_QSPI_SPI_BOOTSEQ_RST_VAL_M 0x1

/* GLOBAL_CONF_COLD_RST_FLOPS */
#define GLOBAL_CONF_COLD_RST_FLOPS_VAL_S 0
#define GLOBAL_CONF_COLD_RST_FLOPS_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_BTM_RR_DELAY */
#define GLOBAL_CONF_BTM_RR_DELAY_VAL_S 0
#define GLOBAL_CONF_BTM_RR_DELAY_VAL_M 0xFFFF

/* GLOBAL_CONF_BTM_RR_RESTART */
#define GLOBAL_CONF_BTM_RR_RESTART_EN_S 0
#define GLOBAL_CONF_BTM_RR_RESTART_EN_M 0x1
#define GLOBAL_CONF_BTM_RR_RESTART_MNL_RST_EN_S 4
#define GLOBAL_CONF_BTM_RR_RESTART_MNL_RST_EN_M 0x10
#define GLOBAL_CONF_BTM_RR_RESTART_WD_RST_EN_S 5
#define GLOBAL_CONF_BTM_RR_RESTART_WD_RST_EN_M 0x20
#define GLOBAL_CONF_BTM_RR_RESTART_SW_RST_EN_S 6
#define GLOBAL_CONF_BTM_RR_RESTART_SW_RST_EN_M 0x40
#define GLOBAL_CONF_BTM_RR_RESTART_SOFT_RST_EN_S 7
#define GLOBAL_CONF_BTM_RR_RESTART_SOFT_RST_EN_M 0x80
#define GLOBAL_CONF_BTM_RR_RESTART_PRST_RST_EN_S 8
#define GLOBAL_CONF_BTM_RR_RESTART_PRST_RST_EN_M 0x100
#define GLOBAL_CONF_BTM_RR_RESTART_FLR_RST_EN_S 9
#define GLOBAL_CONF_BTM_RR_RESTART_FLR_RST_EN_M 0x200
#define GLOBAL_CONF_BTM_RR_RESTART_FW_RST_EN_S 10
#define GLOBAL_CONF_BTM_RR_RESTART_FW_RST_EN_M 0x400
#define GLOBAL_CONF_BTM_RR_RESTART_ECC_DERR_RST_EN_S 11
#define GLOBAL_CONF_BTM_RR_RESTART_ECC_DERR_RST_EN_M 0x800

/* GLOBAL_CONF_BTM_RST_IN_PRG_DELAY */
#define GLOBAL_CONF_BTM_RST_IN_PRG_DELAY_VAL_S 0
#define GLOBAL_CONF_BTM_RST_IN_PRG_DELAY_VAL_M 0xFFFF

/* GLOBAL_CONF_BTM_RST_IN_PRG_RESTART */
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_EN_S 0
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_EN_M 0x1
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_MNL_RST_EN_S 4
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_MNL_RST_EN_M 0x10
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_WD_RST_EN_S 5
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_WD_RST_EN_M 0x20
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_SW_RST_EN_S 6
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_SW_RST_EN_M 0x40
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_SOFT_RST_EN_S 7
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_SOFT_RST_EN_M 0x80
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_PRST_RST_EN_S 8
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_PRST_RST_EN_M 0x100
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_FLR_RST_EN_S 9
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_FLR_RST_EN_M 0x200
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_FW_RST_EN_S 10
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_FW_RST_EN_M 0x400
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_ECC_DERR_RST_EN_S 11
#define GLOBAL_CONF_BTM_RST_IN_PRG_RESTART_ECC_DERR_RST_EN_M 0x800

/* GLOBAL_CONF_PRSTN_OVR */
#define GLOBAL_CONF_PRSTN_OVR_EN_S 0
#define GLOBAL_CONF_PRSTN_OVR_EN_M 0x1
#define GLOBAL_CONF_PRSTN_OVR_VAL_S 4
#define GLOBAL_CONF_PRSTN_OVR_VAL_M 0x10

/* GLOBAL_CONF_PCIE_PHY_RST_N */
#define GLOBAL_CONF_PCIE_PHY_RST_N_IND_S 0
#define GLOBAL_CONF_PCIE_PHY_RST_N_IND_M 0x1
#define GLOBAL_CONF_PCIE_PHY_RST_N_CLK_DIS_S 16
#define GLOBAL_CONF_PCIE_PHY_RST_N_CLK_DIS_M 0x10000

/* GLOBAL_CONF_BTL_ROM_DELAY */
#define GLOBAL_CONF_BTL_ROM_DELAY_VAL_S 0
#define GLOBAL_CONF_BTL_ROM_DELAY_VAL_M 0xFFFF

/* GLOBAL_CONF_BTL_ROM_STS */
#define GLOBAL_CONF_BTL_ROM_STS_INIT_S 0
#define GLOBAL_CONF_BTL_ROM_STS_INIT_M 0x1
#define GLOBAL_CONF_BTL_ROM_STS_DONE_S 1
#define GLOBAL_CONF_BTL_ROM_STS_DONE_M 0x2
#define GLOBAL_CONF_BTL_ROM_STS_I2C_INIT_DONE_S 2
#define GLOBAL_CONF_BTL_ROM_STS_I2C_INIT_DONE_M 0x4
#define GLOBAL_CONF_BTL_ROM_STS_PCIE_INIT_DONE_S 3
#define GLOBAL_CONF_BTL_ROM_STS_PCIE_INIT_DONE_M 0x8
#define GLOBAL_CONF_BTL_ROM_STS_GLINK_INIT_DONE_S 4
#define GLOBAL_CONF_BTL_ROM_STS_GLINK_INIT_DONE_M 0x10
#define GLOBAL_CONF_BTL_ROM_STS_LTSSM_EN_S 5
#define GLOBAL_CONF_BTL_ROM_STS_LTSSM_EN_M 0x20

/* GLOBAL_CONF_BTL_ROM_CTRL */
#define GLOBAL_CONF_BTL_ROM_CTRL_EN_S 0
#define GLOBAL_CONF_BTL_ROM_CTRL_EN_M 0x1

/* GLOBAL_CONF_BTL_ADDR_EXT */
#define GLOBAL_CONF_BTL_ADDR_EXT_VAL_S 0
#define GLOBAL_CONF_BTL_ADDR_EXT_VAL_M 0xFFFFF

/* GLOBAL_CONF_BOOT_SEQ_TO */
#define GLOBAL_CONF_BOOT_SEQ_TO_MASK_S 0
#define GLOBAL_CONF_BOOT_SEQ_TO_MASK_M 0x1

/* GLOBAL_CONF_RESET_DELAYS */
#define GLOBAL_CONF_RESET_DELAYS_PRE_RESET_S 0
#define GLOBAL_CONF_RESET_DELAYS_PRE_RESET_M 0xFFFF
#define GLOBAL_CONF_RESET_DELAYS_GRAD_RESET_S 16
#define GLOBAL_CONF_RESET_DELAYS_GRAD_RESET_M 0xFFFF0000

/* GLOBAL_CONF_BSEQ_PSLVERR_FIFO_STATUS */
#define GLOBAL_CONF_BSEQ_PSLVERR_FIFO_STATUS_FILL_LVL_S 0
#define GLOBAL_CONF_BSEQ_PSLVERR_FIFO_STATUS_FILL_LVL_M 0xF
#define GLOBAL_CONF_BSEQ_PSLVERR_FIFO_STATUS_EMPTY_S 5
#define GLOBAL_CONF_BSEQ_PSLVERR_FIFO_STATUS_EMPTY_M 0x20
#define GLOBAL_CONF_BSEQ_PSLVERR_FIFO_STATUS_FULL_S 6
#define GLOBAL_CONF_BSEQ_PSLVERR_FIFO_STATUS_FULL_M 0x40

/* GLOBAL_CONF_BSEQ_PSLVERR_FIFO_HEAD */
#define GLOBAL_CONF_BSEQ_PSLVERR_FIFO_HEAD_APB_SRC_S 0
#define GLOBAL_CONF_BSEQ_PSLVERR_FIFO_HEAD_APB_SRC_M 0x3
#define GLOBAL_CONF_BSEQ_PSLVERR_FIFO_HEAD_ADDR_S 2
#define GLOBAL_CONF_BSEQ_PSLVERR_FIFO_HEAD_ADDR_M 0xFFFFFFFC

/* GLOBAL_CONF_BSEQ_PSLVERR_FIFO_CMD */
#define GLOBAL_CONF_BSEQ_PSLVERR_FIFO_CMD_POP_S 0
#define GLOBAL_CONF_BSEQ_PSLVERR_FIFO_CMD_POP_M 0x1
#define GLOBAL_CONF_BSEQ_PSLVERR_FIFO_CMD_FLUSH_S 1
#define GLOBAL_CONF_BSEQ_PSLVERR_FIFO_CMD_FLUSH_M 0x2

/* GLOBAL_CONF_BAUDR */
#define GLOBAL_CONF_BAUDR_VAL_S 0
#define GLOBAL_CONF_BAUDR_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_IC_TERM */
#define GLOBAL_CONF_IC_TERM_WRITE_BRESP_S 0
#define GLOBAL_CONF_IC_TERM_WRITE_BRESP_M 0x3
#define GLOBAL_CONF_IC_TERM_READ_RRESP_S 2
#define GLOBAL_CONF_IC_TERM_READ_RRESP_M 0xC

/* GLOBAL_CONF_IC_LBW_PSOC_UM_CTRL */
#define GLOBAL_CONF_IC_LBW_PSOC_UM_CTRL_PSLVERR_S 0
#define GLOBAL_CONF_IC_LBW_PSOC_UM_CTRL_PSLVERR_M 0x1

/* GLOBAL_CONF_IC_LBW_PSOC_UM_STS0 */
#define GLOBAL_CONF_IC_LBW_PSOC_UM_STS0_ADDR_S 0
#define GLOBAL_CONF_IC_LBW_PSOC_UM_STS0_ADDR_M 0xFFFFFFFF

/* GLOBAL_CONF_IC_LBW_PSOC_UM_STS1 */
#define GLOBAL_CONF_IC_LBW_PSOC_UM_STS1_USER_S 0
#define GLOBAL_CONF_IC_LBW_PSOC_UM_STS1_USER_M 0xFFFF

/* GLOBAL_CONF_IC_LBW_PSOC_UM_STS */
#define GLOBAL_CONF_IC_LBW_PSOC_UM_STS_FULL_S 0
#define GLOBAL_CONF_IC_LBW_PSOC_UM_STS_FULL_M 0x1
#define GLOBAL_CONF_IC_LBW_PSOC_UM_STS_EMPTY_S 1
#define GLOBAL_CONF_IC_LBW_PSOC_UM_STS_EMPTY_M 0x2

/* GLOBAL_CONF_IC_HBW_MAIN_ERR_ADDR_LSB */
#define GLOBAL_CONF_IC_HBW_MAIN_ERR_ADDR_LSB_VAL_S 0
#define GLOBAL_CONF_IC_HBW_MAIN_ERR_ADDR_LSB_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_IC_HBW_MAIN_ERR_ADDR_MSB */
#define GLOBAL_CONF_IC_HBW_MAIN_ERR_ADDR_MSB_VAL_S 0
#define GLOBAL_CONF_IC_HBW_MAIN_ERR_ADDR_MSB_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_IC_HBW_MAIN_ERR_INFO */
#define GLOBAL_CONF_IC_HBW_MAIN_ERR_INFO_DOUBLE_HIT_S 0
#define GLOBAL_CONF_IC_HBW_MAIN_ERR_INFO_DOUBLE_HIT_M 0x1
#define GLOBAL_CONF_IC_HBW_MAIN_ERR_INFO_WINDOW_MISS_S 1
#define GLOBAL_CONF_IC_HBW_MAIN_ERR_INFO_WINDOW_MISS_M 0x2
#define GLOBAL_CONF_IC_HBW_MAIN_ERR_INFO_WR_ERROR_S 2
#define GLOBAL_CONF_IC_HBW_MAIN_ERR_INFO_WR_ERROR_M 0x4
#define GLOBAL_CONF_IC_HBW_MAIN_ERR_INFO_RD_ERROR_S 3
#define GLOBAL_CONF_IC_HBW_MAIN_ERR_INFO_RD_ERROR_M 0x8

/* GLOBAL_CONF_IC_LBW_ERR_ADDR_LSB */
#define GLOBAL_CONF_IC_LBW_ERR_ADDR_LSB_VAL_S 0
#define GLOBAL_CONF_IC_LBW_ERR_ADDR_LSB_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_IC_LBW_ERR_INFO */
#define GLOBAL_CONF_IC_LBW_ERR_INFO_DOUBLE_HIT_S 0
#define GLOBAL_CONF_IC_LBW_ERR_INFO_DOUBLE_HIT_M 0x1
#define GLOBAL_CONF_IC_LBW_ERR_INFO_WINDOW_MISS_S 1
#define GLOBAL_CONF_IC_LBW_ERR_INFO_WINDOW_MISS_M 0x2
#define GLOBAL_CONF_IC_LBW_ERR_INFO_WR_ERROR_S 2
#define GLOBAL_CONF_IC_LBW_ERR_INFO_WR_ERROR_M 0x4
#define GLOBAL_CONF_IC_LBW_ERR_INFO_RD_ERROR_S 3
#define GLOBAL_CONF_IC_LBW_ERR_INFO_RD_ERROR_M 0x8

/* GLOBAL_CONF_IC_HBW_32_ERR_INFO */
#define GLOBAL_CONF_IC_HBW_32_ERR_INFO_DOUBLE_HIT_S 0
#define GLOBAL_CONF_IC_HBW_32_ERR_INFO_DOUBLE_HIT_M 0x1
#define GLOBAL_CONF_IC_HBW_32_ERR_INFO_WINDOW_MISS_S 1
#define GLOBAL_CONF_IC_HBW_32_ERR_INFO_WINDOW_MISS_M 0x2
#define GLOBAL_CONF_IC_HBW_32_ERR_INFO_WR_ERROR_S 2
#define GLOBAL_CONF_IC_HBW_32_ERR_INFO_WR_ERROR_M 0x4
#define GLOBAL_CONF_IC_HBW_32_ERR_INFO_RD_ERROR_S 3
#define GLOBAL_CONF_IC_HBW_32_ERR_INFO_RD_ERROR_M 0x8

/* GLOBAL_CONF_IC_HBW_64_ERR_INFO */
#define GLOBAL_CONF_IC_HBW_64_ERR_INFO_DOUBLE_HIT_S 0
#define GLOBAL_CONF_IC_HBW_64_ERR_INFO_DOUBLE_HIT_M 0x1
#define GLOBAL_CONF_IC_HBW_64_ERR_INFO_WINDOW_MISS_S 1
#define GLOBAL_CONF_IC_HBW_64_ERR_INFO_WINDOW_MISS_M 0x2
#define GLOBAL_CONF_IC_HBW_64_ERR_INFO_WR_ERROR_S 2
#define GLOBAL_CONF_IC_HBW_64_ERR_INFO_WR_ERROR_M 0x4
#define GLOBAL_CONF_IC_HBW_64_ERR_INFO_RD_ERROR_S 3
#define GLOBAL_CONF_IC_HBW_64_ERR_INFO_RD_ERROR_M 0x8

/* GLOBAL_CONF_DFT_EFUSE_STATUS */
#define GLOBAL_CONF_DFT_EFUSE_STATUS_FUNC_S 0
#define GLOBAL_CONF_DFT_EFUSE_STATUS_FUNC_M 0x1
#define GLOBAL_CONF_DFT_EFUSE_STATUS_MEM_REPAIR_S 1
#define GLOBAL_CONF_DFT_EFUSE_STATUS_MEM_REPAIR_M 0x2

/* GLOBAL_CONF_OTHER_DIE_RESET */
#define GLOBAL_CONF_OTHER_DIE_RESET_IND_S 0
#define GLOBAL_CONF_OTHER_DIE_RESET_IND_M 0x1

/* GLOBAL_CONF_BOOT_SEQ_ARB_TO */
#define GLOBAL_CONF_BOOT_SEQ_ARB_TO_VAL_S 0
#define GLOBAL_CONF_BOOT_SEQ_ARB_TO_VAL_M 0xFFFF

/* GLOBAL_CONF_BOOT_ARB_TO */
#define GLOBAL_CONF_BOOT_ARB_TO_VAL_S 0
#define GLOBAL_CONF_BOOT_ARB_TO_VAL_M 0xFFFF

/* GLOBAL_CONF_DPHY_FSM_CTRL */
#define GLOBAL_CONF_DPHY_FSM_CTRL_START_S 0
#define GLOBAL_CONF_DPHY_FSM_CTRL_START_M 0x1

/* GLOBAL_CONF_DPHY_FSM_STS */
#define GLOBAL_CONF_DPHY_FSM_STS_DONE_S 0
#define GLOBAL_CONF_DPHY_FSM_STS_DONE_M 0x1
#define GLOBAL_CONF_DPHY_FSM_STS_RESERVED_S 1
#define GLOBAL_CONF_DPHY_FSM_STS_RESERVED_M 0x2
#define GLOBAL_CONF_DPHY_FSM_STS_BUSY_S 4
#define GLOBAL_CONF_DPHY_FSM_STS_BUSY_M 0x10
#define GLOBAL_CONF_DPHY_FSM_STS_AC_CMD_INDEX_S 8
#define GLOBAL_CONF_DPHY_FSM_STS_AC_CMD_INDEX_M 0xFF00
#define GLOBAL_CONF_DPHY_FSM_STS_AC_LOCK_CMD_S 16
#define GLOBAL_CONF_DPHY_FSM_STS_AC_LOCK_CMD_M 0x10000
#define GLOBAL_CONF_DPHY_FSM_STS_AC_CMD_ERROR_EVENT_S 17
#define GLOBAL_CONF_DPHY_FSM_STS_AC_CMD_ERROR_EVENT_M 0x20000
#define GLOBAL_CONF_DPHY_FSM_STS_AC_APB_ERROR_EVENT_S 18
#define GLOBAL_CONF_DPHY_FSM_STS_AC_APB_ERROR_EVENT_M 0x40000

/* GLOBAL_CONF_SCRATCHPAD */
#define GLOBAL_CONF_SCRATCHPAD_REG_S 0
#define GLOBAL_CONF_SCRATCHPAD_REG_M 0xFFFFFFFF

/* GLOBAL_CONF_SEMAPHORE */
#define GLOBAL_CONF_SEMAPHORE_REG_S 0
#define GLOBAL_CONF_SEMAPHORE_REG_M 0xFFFFFFFF

/* GLOBAL_CONF_CPU_BOOT_STATUS */
#define GLOBAL_CONF_CPU_BOOT_STATUS_CNTR_S 0
#define GLOBAL_CONF_CPU_BOOT_STATUS_CNTR_M 0xFFFFFFFF

/* GLOBAL_CONF_KMD_MSG_TO_CPU */
#define GLOBAL_CONF_KMD_MSG_TO_CPU_VAL_S 0
#define GLOBAL_CONF_KMD_MSG_TO_CPU_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_I2C_MSTR1_DBG */
#define GLOBAL_CONF_I2C_MSTR1_DBG_S_GEN_S 0
#define GLOBAL_CONF_I2C_MSTR1_DBG_S_GEN_M 0x1
#define GLOBAL_CONF_I2C_MSTR1_DBG_P_GEN_S 1
#define GLOBAL_CONF_I2C_MSTR1_DBG_P_GEN_M 0x2
#define GLOBAL_CONF_I2C_MSTR1_DBG_DATA_S 2
#define GLOBAL_CONF_I2C_MSTR1_DBG_DATA_M 0x4
#define GLOBAL_CONF_I2C_MSTR1_DBG_ADDR_S 3
#define GLOBAL_CONF_I2C_MSTR1_DBG_ADDR_M 0x8
#define GLOBAL_CONF_I2C_MSTR1_DBG_RD_S 4
#define GLOBAL_CONF_I2C_MSTR1_DBG_RD_M 0x10
#define GLOBAL_CONF_I2C_MSTR1_DBG_WR_S 5
#define GLOBAL_CONF_I2C_MSTR1_DBG_WR_M 0x20
#define GLOBAL_CONF_I2C_MSTR1_DBG_HS_S 6
#define GLOBAL_CONF_I2C_MSTR1_DBG_HS_M 0x40
#define GLOBAL_CONF_I2C_MSTR1_DBG_MASTER_ACT_S 7
#define GLOBAL_CONF_I2C_MSTR1_DBG_MASTER_ACT_M 0x80
#define GLOBAL_CONF_I2C_MSTR1_DBG_SLAVE_ACT_S 8
#define GLOBAL_CONF_I2C_MSTR1_DBG_SLAVE_ACT_M 0x100
#define GLOBAL_CONF_I2C_MSTR1_DBG_ADDR_10BIT_S 9
#define GLOBAL_CONF_I2C_MSTR1_DBG_ADDR_10BIT_M 0x200
#define GLOBAL_CONF_I2C_MSTR1_DBG_MST_CSTATE_S 10
#define GLOBAL_CONF_I2C_MSTR1_DBG_MST_CSTATE_M 0x7C00
#define GLOBAL_CONF_I2C_MSTR1_DBG_SLV_CSTATE_S 15
#define GLOBAL_CONF_I2C_MSTR1_DBG_SLV_CSTATE_M 0x78000
#define GLOBAL_CONF_I2C_MSTR1_DBG_IC_EN_S 19
#define GLOBAL_CONF_I2C_MSTR1_DBG_IC_EN_M 0x80000

/* GLOBAL_CONF_I2C_SLV */
#define GLOBAL_CONF_I2C_SLV_CPU_CTRL_S 0
#define GLOBAL_CONF_I2C_SLV_CPU_CTRL_M 0x1

/* GLOBAL_CONF_I2C_SLV_ARB_TO */
#define GLOBAL_CONF_I2C_SLV_ARB_TO_VAL_S 0
#define GLOBAL_CONF_I2C_SLV_ARB_TO_VAL_M 0xFFFF

/* GLOBAL_CONF_I2C_M0_ARB_TO */
#define GLOBAL_CONF_I2C_M0_ARB_TO_VAL_S 0
#define GLOBAL_CONF_I2C_M0_ARB_TO_VAL_M 0xFFFF

/* GLOBAL_CONF_I2C_M1_ARB_TO */
#define GLOBAL_CONF_I2C_M1_ARB_TO_VAL_S 0
#define GLOBAL_CONF_I2C_M1_ARB_TO_VAL_M 0xFFFF

/* GLOBAL_CONF_SMB_ALERT_CTRL */
#define GLOBAL_CONF_SMB_ALERT_CTRL_I2C_M0_ALERT_MASK_S 0
#define GLOBAL_CONF_SMB_ALERT_CTRL_I2C_M0_ALERT_MASK_M 0xFF
#define GLOBAL_CONF_SMB_ALERT_CTRL_I2C_M1_ALERT_MASK_S 8
#define GLOBAL_CONF_SMB_ALERT_CTRL_I2C_M1_ALERT_MASK_M 0xFF00
#define GLOBAL_CONF_SMB_ALERT_CTRL_I2C_SLV_ALERT_MASK_S 16
#define GLOBAL_CONF_SMB_ALERT_CTRL_I2C_SLV_ALERT_MASK_M 0xFF0000

/* GLOBAL_CONF_SMB_ALERT_INTR_CAUSE */
#define GLOBAL_CONF_SMB_ALERT_INTR_CAUSE_VAL_S 0
#define GLOBAL_CONF_SMB_ALERT_INTR_CAUSE_VAL_M 0xFF

/* GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CLEAR */
#define GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CLEAR_IND_S 0
#define GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CLEAR_IND_M 0x1

/* GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CTRL */
#define GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CTRL_IND_S 0
#define GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CTRL_IND_M 0x1
#define GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CTRL_MASK_S 4
#define GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CTRL_MASK_M 0x10

/* GLOBAL_CONF_BTL_STS */
#define GLOBAL_CONF_BTL_STS_DONE_S 0
#define GLOBAL_CONF_BTL_STS_DONE_M 0x1
#define GLOBAL_CONF_BTL_STS_FAIL_S 4
#define GLOBAL_CONF_BTL_STS_FAIL_M 0x10
#define GLOBAL_CONF_BTL_STS_FAIL_CODE_S 8
#define GLOBAL_CONF_BTL_STS_FAIL_CODE_M 0xF00

/* GLOBAL_CONF_DBG_SLV_TERM_CTRL */
#define GLOBAL_CONF_DBG_SLV_TERM_CTRL_PSLVERR_S 0
#define GLOBAL_CONF_DBG_SLV_TERM_CTRL_PSLVERR_M 0x1

/* GLOBAL_CONF_DBG_APB_CTRL */
#define GLOBAL_CONF_DBG_APB_CTRL_SEL_S 0
#define GLOBAL_CONF_DBG_APB_CTRL_SEL_M 0x1
#define GLOBAL_CONF_DBG_APB_CTRL_VAL_S 1
#define GLOBAL_CONF_DBG_APB_CTRL_VAL_M 0x2

/* GLOBAL_CONF_DAP_APB_CTRL */
#define GLOBAL_CONF_DAP_APB_CTRL_PSLVERR_MASK_S 0
#define GLOBAL_CONF_DAP_APB_CTRL_PSLVERR_MASK_M 0x1

/* GLOBAL_CONF_ROM_TBL_ARB_TO */
#define GLOBAL_CONF_ROM_TBL_ARB_TO_VAL_S 0
#define GLOBAL_CONF_ROM_TBL_ARB_TO_VAL_M 0xFFFF

/* GLOBAL_CONF_QSPI_SEMAPHORE_CTRL */
#define GLOBAL_CONF_QSPI_SEMAPHORE_CTRL_EN_S 0
#define GLOBAL_CONF_QSPI_SEMAPHORE_CTRL_EN_M 0x1
#define GLOBAL_CONF_QSPI_SEMAPHORE_CTRL_UNGRANT_SW_TERM_EN_S 1
#define GLOBAL_CONF_QSPI_SEMAPHORE_CTRL_UNGRANT_SW_TERM_EN_M 0x2

/* GLOBAL_CONF_QSPI_SEMAPHORE_SW_CTRL */
#define GLOBAL_CONF_QSPI_SEMAPHORE_SW_CTRL_REQ_S 0
#define GLOBAL_CONF_QSPI_SEMAPHORE_SW_CTRL_REQ_M 0x1

/* GLOBAL_CONF_QSPI_SEMAPHORE_STS */
#define GLOBAL_CONF_QSPI_SEMAPHORE_STS_GRANT_S 0
#define GLOBAL_CONF_QSPI_SEMAPHORE_STS_GRANT_M 0x7

/* GLOBAL_CONF_QSPI_SEMAPHORE_WD */
#define GLOBAL_CONF_QSPI_SEMAPHORE_WD_TIMER_VAL_S 0
#define GLOBAL_CONF_QSPI_SEMAPHORE_WD_TIMER_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_CTRL */
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_CTRL_PRIO_WR_S 0
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_CTRL_PRIO_WR_M 0x3
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_CTRL_PRIO_RD_S 2
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_CTRL_PRIO_RD_M 0xC
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_CTRL_PRIO_EN_S 4
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_CTRL_PRIO_EN_M 0x10
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_CTRL_PSLVERR_S 5
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_CTRL_PSLVERR_M 0x20

/* GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_INFO_STS */
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_INFO_STS_EMPTY_S 0
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_INFO_STS_EMPTY_M 0x1
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_INFO_STS_FULL_S 1
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_INFO_STS_FULL_M 0x2

/* GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_INFO0 */
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_INFO0_ADDR_S 0
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_INFO0_ADDR_M 0xFFFFFFFF

/* GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_INFO1 */
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_INFO1_USER_S 0
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_INFO1_USER_M 0x3FFFFFFF
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_INFO1_PROT_S 30
#define GLOBAL_CONF_QSPI_MEM_ACCESS_PROT_INFO1_PROT_M 0xC0000000

/* GLOBAL_CONF_QSPI_ARB_TO */
#define GLOBAL_CONF_QSPI_ARB_TO_VAL_S 0
#define GLOBAL_CONF_QSPI_ARB_TO_VAL_M 0xFFFF

/* GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL */
#define GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WEN_S 0
#define GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WEN_M 0x1
#define GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_BYTE_SWAP_S 4
#define GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_BYTE_SWAP_M 0x10
#define GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WRITE_CMD_S 8
#define GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WRITE_CMD_M 0xFF00
#define GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WREN_CMD_S 16
#define GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WREN_CMD_M 0xFF0000
#define GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WRDI_CMD_S 24
#define GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WRDI_CMD_M 0xFF000000

/* GLOBAL_CONF_SPI_ARB_TO */
#define GLOBAL_CONF_SPI_ARB_TO_VAL_S 0
#define GLOBAL_CONF_SPI_ARB_TO_VAL_M 0xFFFF

/* GLOBAL_CONF_SPI_WR_WO_CTRL */
#define GLOBAL_CONF_SPI_WR_WO_CTRL_EN_S 0
#define GLOBAL_CONF_SPI_WR_WO_CTRL_EN_M 0x1
#define GLOBAL_CONF_SPI_WR_WO_CTRL_RESP_ERR_S 1
#define GLOBAL_CONF_SPI_WR_WO_CTRL_RESP_ERR_M 0x2
#define GLOBAL_CONF_SPI_WR_WO_CTRL_SE_RANGE_SEL_S 4
#define GLOBAL_CONF_SPI_WR_WO_CTRL_SE_RANGE_SEL_M 0xFF0

/* GLOBAL_CONF_SPI_WR_WO_TIMER_RST_VAL_L */
#define GLOBAL_CONF_SPI_WR_WO_TIMER_RST_VAL_L_VAL_S 0
#define GLOBAL_CONF_SPI_WR_WO_TIMER_RST_VAL_L_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_SPI_WR_WO_TIMER_RST_VAL_H */
#define GLOBAL_CONF_SPI_WR_WO_TIMER_RST_VAL_H_VAL_S 0
#define GLOBAL_CONF_SPI_WR_WO_TIMER_RST_VAL_H_VAL_M 0xFF

/* GLOBAL_CONF_SPI_WR_WO_TIMER_VAL_L */
#define GLOBAL_CONF_SPI_WR_WO_TIMER_VAL_L_VAL_S 0
#define GLOBAL_CONF_SPI_WR_WO_TIMER_VAL_L_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_SPI_WR_WO_TIMER_VAL_H */
#define GLOBAL_CONF_SPI_WR_WO_TIMER_VAL_H_VAL_S 0
#define GLOBAL_CONF_SPI_WR_WO_TIMER_VAL_H_VAL_M 0xFF

/* GLOBAL_CONF_QSPI_WR_WO_TIMER_VAL_L */
#define GLOBAL_CONF_QSPI_WR_WO_TIMER_VAL_L_VAL_S 0
#define GLOBAL_CONF_QSPI_WR_WO_TIMER_VAL_L_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_QSPI_WR_WO_TIMER_VAL_H */
#define GLOBAL_CONF_QSPI_WR_WO_TIMER_VAL_H_VAL_S 0
#define GLOBAL_CONF_QSPI_WR_WO_TIMER_VAL_H_VAL_M 0xFF

/* GLOBAL_CONF_SPI_WR_WO_SE_STATUS */
#define GLOBAL_CONF_SPI_WR_WO_SE_STATUS_VAL_S 0
#define GLOBAL_CONF_SPI_WR_WO_SE_STATUS_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_QSPI_WR_WO_SE_STATUS */
#define GLOBAL_CONF_QSPI_WR_WO_SE_STATUS_VAL_S 0
#define GLOBAL_CONF_QSPI_WR_WO_SE_STATUS_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_SPI_WR_WO_ERR_ADDR */
#define GLOBAL_CONF_SPI_WR_WO_ERR_ADDR_VAL_S 0
#define GLOBAL_CONF_SPI_WR_WO_ERR_ADDR_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_QSPI_WR_WO_ERR_ADDR */
#define GLOBAL_CONF_QSPI_WR_WO_ERR_ADDR_VAL_S 0
#define GLOBAL_CONF_QSPI_WR_WO_ERR_ADDR_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_SPI_WRITE_LIMIT */
#define GLOBAL_CONF_SPI_WRITE_LIMIT_VAL_S 0
#define GLOBAL_CONF_SPI_WRITE_LIMIT_VAL_M 0xF

/* GLOBAL_CONF_SPI_SE_RDSR */
#define GLOBAL_CONF_SPI_SE_RDSR_NEED_SE_S 0
#define GLOBAL_CONF_SPI_SE_RDSR_NEED_SE_M 0x1
#define GLOBAL_CONF_SPI_SE_RDSR_SE_SIZE_S 4
#define GLOBAL_CONF_SPI_SE_RDSR_SE_SIZE_M 0xF0
#define GLOBAL_CONF_SPI_SE_RDSR_SE_CMD_S 8
#define GLOBAL_CONF_SPI_SE_RDSR_SE_CMD_M 0xFF00
#define GLOBAL_CONF_SPI_SE_RDSR_RDSR_CMD_S 16
#define GLOBAL_CONF_SPI_SE_RDSR_RDSR_CMD_M 0xFF0000

/* GLOBAL_CONF_TARGETID */
#define GLOBAL_CONF_TARGETID_TDESIGNER_S 1
#define GLOBAL_CONF_TARGETID_TDESIGNER_M 0xFFE
#define GLOBAL_CONF_TARGETID_TPARTNO_S 16
#define GLOBAL_CONF_TARGETID_TPARTNO_M 0xFFF0000
#define GLOBAL_CONF_TARGETID_TREVISION_S 28
#define GLOBAL_CONF_TARGETID_TREVISION_M 0xF0000000

/* GLOBAL_CONF_ETR_AXI_SPLIT */
#define GLOBAL_CONF_ETR_AXI_SPLIT_SEI_INTR_ID_S 0
#define GLOBAL_CONF_ETR_AXI_SPLIT_SEI_INTR_ID_M 0x7FFF

/* GLOBAL_CONF_DIE_READY_IN */
#define GLOBAL_CONF_DIE_READY_IN_IND_S 0
#define GLOBAL_CONF_DIE_READY_IN_IND_M 0x1
#define GLOBAL_CONF_DIE_READY_IN_STICKY_S 1
#define GLOBAL_CONF_DIE_READY_IN_STICKY_M 0x2

/* GLOBAL_CONF_DIE_READY_OUT */
#define GLOBAL_CONF_DIE_READY_OUT_IND_S 0
#define GLOBAL_CONF_DIE_READY_OUT_IND_M 0x1
#define GLOBAL_CONF_DIE_READY_OUT_STICKY_S 1
#define GLOBAL_CONF_DIE_READY_OUT_STICKY_M 0x2

/* GLOBAL_CONF_DIE_RECOVERY_IN */
#define GLOBAL_CONF_DIE_RECOVERY_IN_IND_S 0
#define GLOBAL_CONF_DIE_RECOVERY_IN_IND_M 0x1
#define GLOBAL_CONF_DIE_RECOVERY_IN_STICKY_S 1
#define GLOBAL_CONF_DIE_RECOVERY_IN_STICKY_M 0x2

/* GLOBAL_CONF_DIE_RECOVERY_OUT */
#define GLOBAL_CONF_DIE_RECOVERY_OUT_IND_S 0
#define GLOBAL_CONF_DIE_RECOVERY_OUT_IND_M 0x1
#define GLOBAL_CONF_DIE_RECOVERY_OUT_STICKY_S 1
#define GLOBAL_CONF_DIE_RECOVERY_OUT_STICKY_M 0x2

/* GLOBAL_CONF_LEGACY_BOOT_STRAPS */
#define GLOBAL_CONF_LEGACY_BOOT_STRAPS_PCIE_EN_S 0
#define GLOBAL_CONF_LEGACY_BOOT_STRAPS_PCIE_EN_M 0x1

/* GLOBAL_CONF_MEM_REPAIR_DIV */
#define GLOBAL_CONF_MEM_REPAIR_DIV_EN_S 0
#define GLOBAL_CONF_MEM_REPAIR_DIV_EN_M 0x1
#define GLOBAL_CONF_MEM_REPAIR_DIV_VAL_OVRD_EN_S 1
#define GLOBAL_CONF_MEM_REPAIR_DIV_VAL_OVRD_EN_M 0x2
#define GLOBAL_CONF_MEM_REPAIR_DIV_VAL_S 8
#define GLOBAL_CONF_MEM_REPAIR_DIV_VAL_M 0xFF00

/* GLOBAL_CONF_MEM_REPAIR_STS */
#define GLOBAL_CONF_MEM_REPAIR_STS_DONE_S 0
#define GLOBAL_CONF_MEM_REPAIR_STS_DONE_M 0xF
#define GLOBAL_CONF_MEM_REPAIR_STS_PASS_S 4
#define GLOBAL_CONF_MEM_REPAIR_STS_PASS_M 0xF0
#define GLOBAL_CONF_MEM_REPAIR_STS_FAIL_COMB_S 8
#define GLOBAL_CONF_MEM_REPAIR_STS_FAIL_COMB_M 0x100

/* GLOBAL_CONF_MEM_REPAIR_WD_CTRL */
#define GLOBAL_CONF_MEM_REPAIR_WD_CTRL_MASK_WD_TIMER_S 0
#define GLOBAL_CONF_MEM_REPAIR_WD_CTRL_MASK_WD_TIMER_M 0x1

/* GLOBAL_CONF_MEM_REPAIR_WD_STS */
#define GLOBAL_CONF_MEM_REPAIR_WD_STS_WD_TIMER_EXPIRED_S 0
#define GLOBAL_CONF_MEM_REPAIR_WD_STS_WD_TIMER_EXPIRED_M 0x1

/* GLOBAL_CONF_MEM_REPAIR_WD_CNTR */
#define GLOBAL_CONF_MEM_REPAIR_WD_CNTR_VAL_S 0
#define GLOBAL_CONF_MEM_REPAIR_WD_CNTR_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_BSAC_CTRL */
#define GLOBAL_CONF_BSAC_CTRL_ENABLE_S 0
#define GLOBAL_CONF_BSAC_CTRL_ENABLE_M 0x1
#define GLOBAL_CONF_BSAC_CTRL_HOLD_S 1
#define GLOBAL_CONF_BSAC_CTRL_HOLD_M 0x2
#define GLOBAL_CONF_BSAC_CTRL_DONE_S 4
#define GLOBAL_CONF_BSAC_CTRL_DONE_M 0x10
#define GLOBAL_CONF_BSAC_CTRL_STARTED_S 5
#define GLOBAL_CONF_BSAC_CTRL_STARTED_M 0x20
#define GLOBAL_CONF_BSAC_CTRL_APBERROR_S 6
#define GLOBAL_CONF_BSAC_CTRL_APBERROR_M 0x40
#define GLOBAL_CONF_BSAC_CTRL_FRF_S 8
#define GLOBAL_CONF_BSAC_CTRL_FRF_M 0x300
#define GLOBAL_CONF_BSAC_CTRL_TMOD_S 10
#define GLOBAL_CONF_BSAC_CTRL_TMOD_M 0xC00
#define GLOBAL_CONF_BSAC_CTRL_SPI_FRF_S 12
#define GLOBAL_CONF_BSAC_CTRL_SPI_FRF_M 0x3000

/* GLOBAL_CONF_BSAC_ADDR */
#define GLOBAL_CONF_BSAC_ADDR_VAL_S 0
#define GLOBAL_CONF_BSAC_ADDR_VAL_M 0xFFFFFFF

/* GLOBAL_CONF_BSAC_DATA */
#define GLOBAL_CONF_BSAC_DATA_VAL_S 0
#define GLOBAL_CONF_BSAC_DATA_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_BSAC_POLLING_CTRL */
#define GLOBAL_CONF_BSAC_POLLING_CTRL_ADDR_S 0
#define GLOBAL_CONF_BSAC_POLLING_CTRL_ADDR_M 0xFFFFFFF
#define GLOBAL_CONF_BSAC_POLLING_CTRL_ENABLE_S 28
#define GLOBAL_CONF_BSAC_POLLING_CTRL_ENABLE_M 0x10000000
#define GLOBAL_CONF_BSAC_POLLING_CTRL_DONE_S 29
#define GLOBAL_CONF_BSAC_POLLING_CTRL_DONE_M 0x20000000

/* GLOBAL_CONF_BSAC_POLLING_DATA */
#define GLOBAL_CONF_BSAC_POLLING_DATA_VAL_S 0
#define GLOBAL_CONF_BSAC_POLLING_DATA_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_BSAC_POLLING_MASK */
#define GLOBAL_CONF_BSAC_POLLING_MASK_VAL_S 0
#define GLOBAL_CONF_BSAC_POLLING_MASK_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_BTL_ROM_QSPI_BASE */
#define GLOBAL_CONF_BTL_ROM_QSPI_BASE_CFG_ADDR_S 0
#define GLOBAL_CONF_BTL_ROM_QSPI_BASE_CFG_ADDR_M 0xFFFFFFFF

/* GLOBAL_CONF_BTL_ROM_I2C_BASE */
#define GLOBAL_CONF_BTL_ROM_I2C_BASE_CFG_ADDR_S 0
#define GLOBAL_CONF_BTL_ROM_I2C_BASE_CFG_ADDR_M 0xFFFFFFFF

/* GLOBAL_CONF_BTL_ROM_DUMMY_WRITES_BASE */
#define GLOBAL_CONF_BTL_ROM_DUMMY_WRITES_BASE_CFG_ADDR_S 0
#define GLOBAL_CONF_BTL_ROM_DUMMY_WRITES_BASE_CFG_ADDR_M 0xFFFFFFFF

/* GLOBAL_CONF_BTL_IMG */
#define GLOBAL_CONF_BTL_IMG_SPI_IMAGE_FLIP_S 0
#define GLOBAL_CONF_BTL_IMG_SPI_IMAGE_FLIP_M 0x1
#define GLOBAL_CONF_BTL_IMG_PRST_IMAGE_FLIP_S 1
#define GLOBAL_CONF_BTL_IMG_PRST_IMAGE_FLIP_M 0x2
#define GLOBAL_CONF_BTL_IMG_PCIE_IMAGE_FLIP_S 2
#define GLOBAL_CONF_BTL_IMG_PCIE_IMAGE_FLIP_M 0x4
#define GLOBAL_CONF_BTL_IMG_PCIE_FW_IMAGE_FLIP_S 3
#define GLOBAL_CONF_BTL_IMG_PCIE_FW_IMAGE_FLIP_M 0x8
#define GLOBAL_CONF_BTL_IMG_SW_RST_RUN_PCIE_IMAGE_S 4
#define GLOBAL_CONF_BTL_IMG_SW_RST_RUN_PCIE_IMAGE_M 0x10
#define GLOBAL_CONF_BTL_IMG_SOFT_RST_RUN_PCIE_IMAGE_S 5
#define GLOBAL_CONF_BTL_IMG_SOFT_RST_RUN_PCIE_IMAGE_M 0x20
#define GLOBAL_CONF_BTL_IMG_WD_RST_RUN_PCIE_IMAGE_S 6
#define GLOBAL_CONF_BTL_IMG_WD_RST_RUN_PCIE_IMAGE_M 0x40
#define GLOBAL_CONF_BTL_IMG_MNL_RST_RUN_PCIE_IMAGE_S 7
#define GLOBAL_CONF_BTL_IMG_MNL_RST_RUN_PCIE_IMAGE_M 0x80
#define GLOBAL_CONF_BTL_IMG_PRST_RUN_PCIE_IMAGE_S 8
#define GLOBAL_CONF_BTL_IMG_PRST_RUN_PCIE_IMAGE_M 0x100
#define GLOBAL_CONF_BTL_IMG_FLR_RST_RUN_PCIE_IMAGE_S 9
#define GLOBAL_CONF_BTL_IMG_FLR_RST_RUN_PCIE_IMAGE_M 0x200
#define GLOBAL_CONF_BTL_IMG_FW_RST_RUN_PCIE_IMAGE_S 10
#define GLOBAL_CONF_BTL_IMG_FW_RST_RUN_PCIE_IMAGE_M 0x400
#define GLOBAL_CONF_BTL_IMG_ECC_DERR_RUN_PCIE_IMAGE_S 11
#define GLOBAL_CONF_BTL_IMG_ECC_DERR_RUN_PCIE_IMAGE_M 0x800

/* GLOBAL_CONF_PRSTN_MASK */
#define GLOBAL_CONF_PRSTN_MASK_IND_S 0
#define GLOBAL_CONF_PRSTN_MASK_IND_M 0x1

/* GLOBAL_CONF_WD_MASK */
#define GLOBAL_CONF_WD_MASK_IND_S 0
#define GLOBAL_CONF_WD_MASK_IND_M 0x1

/* GLOBAL_CONF_RST_SRC */
#define GLOBAL_CONF_RST_SRC_COLD_RST_IND_S 0
#define GLOBAL_CONF_RST_SRC_COLD_RST_IND_M 0x1
#define GLOBAL_CONF_RST_SRC_MNL_RST_IND_S 1
#define GLOBAL_CONF_RST_SRC_MNL_RST_IND_M 0x2
#define GLOBAL_CONF_RST_SRC_PRSTN_RST_IND_S 2
#define GLOBAL_CONF_RST_SRC_PRSTN_RST_IND_M 0x4
#define GLOBAL_CONF_RST_SRC_SOFT_RST_IND_S 3
#define GLOBAL_CONF_RST_SRC_SOFT_RST_IND_M 0x8
#define GLOBAL_CONF_RST_SRC_WD_RST_IND_S 4
#define GLOBAL_CONF_RST_SRC_WD_RST_IND_M 0x10
#define GLOBAL_CONF_RST_SRC_FW_RST_IND_S 5
#define GLOBAL_CONF_RST_SRC_FW_RST_IND_M 0x20
#define GLOBAL_CONF_RST_SRC_SW_RST_IND_S 6
#define GLOBAL_CONF_RST_SRC_SW_RST_IND_M 0x40
#define GLOBAL_CONF_RST_SRC_FLR_RST_IND_S 7
#define GLOBAL_CONF_RST_SRC_FLR_RST_IND_M 0x80
#define GLOBAL_CONF_RST_SRC_ECC_DERR_RST_IND_S 8
#define GLOBAL_CONF_RST_SRC_ECC_DERR_RST_IND_M 0x100

/* GLOBAL_CONF_RST_FROM_PCIE_CTRL */
#define GLOBAL_CONF_RST_FROM_PCIE_CTRL_SOFT_RST_MASK_S 0
#define GLOBAL_CONF_RST_FROM_PCIE_CTRL_SOFT_RST_MASK_M 0x1
#define GLOBAL_CONF_RST_FROM_PCIE_CTRL_SW_RST_MASK_S 4
#define GLOBAL_CONF_RST_FROM_PCIE_CTRL_SW_RST_MASK_M 0x10

/* GLOBAL_CONF_PAD_1V2_CFG */
#define GLOBAL_CONF_PAD_1V2_CFG_VAL_S 0
#define GLOBAL_CONF_PAD_1V2_CFG_VAL_M 0x7F

/* GLOBAL_CONF_I3C_CFG */
#define GLOBAL_CONF_I3C_CFG_ACT_MODE_S 0
#define GLOBAL_CONF_I3C_CFG_ACT_MODE_M 0x3
#define GLOBAL_CONF_I3C_CFG_PENDING_INT_S 2
#define GLOBAL_CONF_I3C_CFG_PENDING_INT_M 0x3C
#define GLOBAL_CONF_I3C_CFG_MODE_I2C_S 6
#define GLOBAL_CONF_I3C_CFG_MODE_I2C_M 0x40
#define GLOBAL_CONF_I3C_CFG_STATIC_ADDR_EN_S 7
#define GLOBAL_CONF_I3C_CFG_STATIC_ADDR_EN_M 0x80
#define GLOBAL_CONF_I3C_CFG_STATIC_ADDR_S 8
#define GLOBAL_CONF_I3C_CFG_STATIC_ADDR_M 0x7F00
#define GLOBAL_CONF_I3C_CFG_SLV_MAX_RD_SPEED_S 15
#define GLOBAL_CONF_I3C_CFG_SLV_MAX_RD_SPEED_M 0x38000
#define GLOBAL_CONF_I3C_CFG_SLV_MAX_WR_SPEED_S 18
#define GLOBAL_CONF_I3C_CFG_SLV_MAX_WR_SPEED_M 0x1C0000
#define GLOBAL_CONF_I3C_CFG_SLV_CLK_DATA_TURN_TIME_S 21
#define GLOBAL_CONF_I3C_CFG_SLV_CLK_DATA_TURN_TIME_M 0xE00000
#define GLOBAL_CONF_I3C_CFG_SLV_DCR_S 24
#define GLOBAL_CONF_I3C_CFG_SLV_DCR_M 0xFF000000

/* GLOBAL_CONF_I3C_CFG_PID_LSB */
#define GLOBAL_CONF_I3C_CFG_PID_LSB_VAL_S 0
#define GLOBAL_CONF_I3C_CFG_PID_LSB_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_I3C_CFG_PID_MSB */
#define GLOBAL_CONF_I3C_CFG_PID_MSB_VAL_S 0
#define GLOBAL_CONF_I3C_CFG_PID_MSB_VAL_M 0xFFFF

/* GLOBAL_CONF_I3C_STATUS */
#define GLOBAL_CONF_I3C_STATUS_I2C_GLITCH_FILTER_EN_S 0
#define GLOBAL_CONF_I3C_STATUS_I2C_GLITCH_FILTER_EN_M 0x1
#define GLOBAL_CONF_I3C_STATUS_WAKEUP_S 1
#define GLOBAL_CONF_I3C_STATUS_WAKEUP_M 0x2
#define GLOBAL_CONF_I3C_STATUS_IBI_PAYLOAD_SIZE_S 16
#define GLOBAL_CONF_I3C_STATUS_IBI_PAYLOAD_SIZE_M 0xFF0000

/* GLOBAL_CONF_I3C_CFG_DEBUG_LSB */
#define GLOBAL_CONF_I3C_CFG_DEBUG_LSB_VAL_S 0
#define GLOBAL_CONF_I3C_CFG_DEBUG_LSB_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_I3C_CFG_DEBUG_MSB */
#define GLOBAL_CONF_I3C_CFG_DEBUG_MSB_VAL_S 0
#define GLOBAL_CONF_I3C_CFG_DEBUG_MSB_VAL_M 0xFFFFFF

/* GLOBAL_CONF_ASIF_MSTR_REQ_STATUS */
#define GLOBAL_CONF_ASIF_MSTR_REQ_STATUS_FAILED_S 0
#define GLOBAL_CONF_ASIF_MSTR_REQ_STATUS_FAILED_M 0x1

/* GLOBAL_CONF_ASIF_MSTR_REQ_PUSH */
#define GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_LSB_ADDR_S 0
#define GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_LSB_ADDR_M 0xFFF
#define GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_PPROT_S 12
#define GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_PPROT_M 0x7000
#define GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_PWRITE_S 16
#define GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_PWRITE_M 0x10000
#define GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_FENCE_S 17
#define GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_FENCE_M 0x20000
#define GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_DROP_S 18
#define GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_DROP_M 0x40000
#define GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_DST_ID_S 20
#define GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_DST_ID_M 0x3F00000

/* GLOBAL_CONF_ASIF_MSTR_REQ_WR */
#define GLOBAL_CONF_ASIF_MSTR_REQ_WR_PWDATA_S 0
#define GLOBAL_CONF_ASIF_MSTR_REQ_WR_PWDATA_M 0xFFFFFFFF

/* GLOBAL_CONF_ASIF_MSTR_RES_STATUS */
#define GLOBAL_CONF_ASIF_MSTR_RES_STATUS_RES_READY_S 0
#define GLOBAL_CONF_ASIF_MSTR_RES_STATUS_RES_READY_M 0x1
#define GLOBAL_CONF_ASIF_MSTR_RES_STATUS_PSLVERR_S 4
#define GLOBAL_CONF_ASIF_MSTR_RES_STATUS_PSLVERR_M 0x10

/* GLOBAL_CONF_ASIF_MSTR_RES_POP */
#define GLOBAL_CONF_ASIF_MSTR_RES_POP_PRDATA_S 0
#define GLOBAL_CONF_ASIF_MSTR_RES_POP_PRDATA_M 0xFFFFFFFF

/* GLOBAL_CONF_ASIF_MSTR_ERROR */
#define GLOBAL_CONF_ASIF_MSTR_ERROR_REQ_BUFF_FULL_S 0
#define GLOBAL_CONF_ASIF_MSTR_ERROR_REQ_BUFF_FULL_M 0x1
#define GLOBAL_CONF_ASIF_MSTR_ERROR_RES_BUFF_FULL_S 1
#define GLOBAL_CONF_ASIF_MSTR_ERROR_RES_BUFF_FULL_M 0x2
#define GLOBAL_CONF_ASIF_MSTR_ERROR_REQ_ILLEGAL_S 2
#define GLOBAL_CONF_ASIF_MSTR_ERROR_REQ_ILLEGAL_M 0x4
#define GLOBAL_CONF_ASIF_MSTR_ERROR_RES_DATA_OVRN_S 3
#define GLOBAL_CONF_ASIF_MSTR_ERROR_RES_DATA_OVRN_M 0x8
#define GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_S 4
#define GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_M 0x10
#define GLOBAL_CONF_ASIF_MSTR_ERROR_RES_QUAL_OVRN_S 5
#define GLOBAL_CONF_ASIF_MSTR_ERROR_RES_QUAL_OVRN_M 0x20
#define GLOBAL_CONF_ASIF_MSTR_ERROR_POP_RES_WHILE_EMPTY_S 6
#define GLOBAL_CONF_ASIF_MSTR_ERROR_POP_RES_WHILE_EMPTY_M 0x40
#define GLOBAL_CONF_ASIF_MSTR_ERROR_PUSH_REQ_WHILE_FULL_S 7
#define GLOBAL_CONF_ASIF_MSTR_ERROR_PUSH_REQ_WHILE_FULL_M 0x80
#define GLOBAL_CONF_ASIF_MSTR_ERROR_RX_TIMEOUT_S 8
#define GLOBAL_CONF_ASIF_MSTR_ERROR_RX_TIMEOUT_M 0x100
#define GLOBAL_CONF_ASIF_MSTR_ERROR_TX_TIMEOUT_S 9
#define GLOBAL_CONF_ASIF_MSTR_ERROR_TX_TIMEOUT_M 0x200
#define GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_ADDR_S 12
#define GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_ADDR_M 0xFFF000
#define GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_DST_ID_S 24
#define GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_DST_ID_M 0x3F000000
#define GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_DROP_S 31
#define GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_DROP_M 0x80000000

/* GLOBAL_CONF_ASIF_MSTR_INTR_MASK */
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_REQ_BUFF_FULL_S 0
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_REQ_BUFF_FULL_M 0x1
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_BUFF_FULL_S 1
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_BUFF_FULL_M 0x2
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_REQ_ILLEGAL_S 2
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_REQ_ILLEGAL_M 0x4
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_DATA_OVRN_S 3
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_DATA_OVRN_M 0x8
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_PSLVERR_S 4
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_PSLVERR_M 0x10
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_QUAL_OVRN_S 5
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_QUAL_OVRN_M 0x20
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_POP_RES_WHILE_EMPTY_S 6
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_POP_RES_WHILE_EMPTY_M 0x40
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_PUSH_REQ_WHILE_FULL_S 7
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_PUSH_REQ_WHILE_FULL_M 0x80
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RX_TIMEOUT_S 8
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RX_TIMEOUT_M 0x100
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_TX_TIMEOUT_S 9
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_TX_TIMEOUT_M 0x200
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_VALID_S 16
#define GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_VALID_M 0x10000

/* GLOBAL_CONF_ASIF_MSTR_STATUS */
#define GLOBAL_CONF_ASIF_MSTR_STATUS_REQ_LL_USED_S 0
#define GLOBAL_CONF_ASIF_MSTR_STATUS_REQ_LL_USED_M 0x3F
#define GLOBAL_CONF_ASIF_MSTR_STATUS_RES_LL_USED_S 8
#define GLOBAL_CONF_ASIF_MSTR_STATUS_RES_LL_USED_M 0x1F00
#define GLOBAL_CONF_ASIF_MSTR_STATUS_OTF_FIFO_USED_S 16
#define GLOBAL_CONF_ASIF_MSTR_STATUS_OTF_FIFO_USED_M 0x3F0000

/* GLOBAL_CONF_ASIF_CORE_CFG */
#define GLOBAL_CONF_ASIF_CORE_CFG_RISE_DELAY_S 0
#define GLOBAL_CONF_ASIF_CORE_CFG_RISE_DELAY_M 0x1F
#define GLOBAL_CONF_ASIF_CORE_CFG_FALL_DELAY_S 8
#define GLOBAL_CONF_ASIF_CORE_CFG_FALL_DELAY_M 0x1F00
#define GLOBAL_CONF_ASIF_CORE_CFG_DETECT_DELAY_S 16
#define GLOBAL_CONF_ASIF_CORE_CFG_DETECT_DELAY_M 0xF0000
#define GLOBAL_CONF_ASIF_CORE_CFG_FLUSH_DESIGN_S 31
#define GLOBAL_CONF_ASIF_CORE_CFG_FLUSH_DESIGN_M 0x80000000

/* GLOBAL_CONF_ASIF_CORE_DBG_CNT */
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_DATA_OVRN_CNT_S 0
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_DATA_OVRN_CNT_M 0xF
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_QUAL_OVRN_CNT_S 4
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_QUAL_OVRN_CNT_M 0xF0
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_DETECT_CYCLES_CNT_S 8
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_DETECT_CYCLES_CNT_M 0xF00
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_CNT_S 12
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_CNT_M 0xF000
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_TX_CNT_S 16
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_TX_CNT_M 0xF0000
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_FSM_S 20
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_FSM_M 0xF00000
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_TX_FSM_S 24
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_TX_FSM_M 0xF000000

/* GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR */
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_GLB_CLEAR_S 0
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_GLB_CLEAR_M 0x1
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_RX_DATA_OVRN_CLR_S 1
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_RX_DATA_OVRN_CLR_M 0x2
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_RX_QUAL_OVRN_CLR_S 2
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_RX_QUAL_OVRN_CLR_M 0x4
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_RX_CLR_S 3
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_RX_CLR_M 0x8
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_TX_CLR_S 4
#define GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_TX_CLR_M 0x10

/* GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG */
#define GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_RX_TIMEOUT_EN_S 0
#define GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_RX_TIMEOUT_EN_M 0x1
#define GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_TX_TIMEOUT_EN_S 1
#define GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_TX_TIMEOUT_EN_M 0x2
#define GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_RX_TIMEOUT_RES_S 2
#define GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_RX_TIMEOUT_RES_M 0x4
#define GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_TX_TIMEOUT_RES_S 3
#define GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_TX_TIMEOUT_RES_M 0x8
#define GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_RX_TIMEOUT_VALUE_S 8
#define GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_RX_TIMEOUT_VALUE_M 0x3FF00
#define GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_TX_TIMEOUT_VALUE_S 20
#define GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_TX_TIMEOUT_VALUE_M 0x3FF00000

/* GLOBAL_CONF_ASIF_FUNC_INTR_CAUSE */
#define GLOBAL_CONF_ASIF_FUNC_INTR_CAUSE_IND_S 0
#define GLOBAL_CONF_ASIF_FUNC_INTR_CAUSE_IND_M 0x1

/* GLOBAL_CONF_ASIF_FUNC_INTR_CLEAR */
#define GLOBAL_CONF_ASIF_FUNC_INTR_CLEAR_IND_S 0
#define GLOBAL_CONF_ASIF_FUNC_INTR_CLEAR_IND_M 0x1

/* GLOBAL_CONF_ASIF_FUNC_INTR_MASK */
#define GLOBAL_CONF_ASIF_FUNC_INTR_MASK_VAL_S 0
#define GLOBAL_CONF_ASIF_FUNC_INTR_MASK_VAL_M 0x1

/* GLOBAL_CONF_ASIF_ERR_INTR_CAUSE */
#define GLOBAL_CONF_ASIF_ERR_INTR_CAUSE_IND_S 0
#define GLOBAL_CONF_ASIF_ERR_INTR_CAUSE_IND_M 0x1

/* GLOBAL_CONF_ASIF_ERR_INTR_CLEAR */
#define GLOBAL_CONF_ASIF_ERR_INTR_CLEAR_IND_S 0
#define GLOBAL_CONF_ASIF_ERR_INTR_CLEAR_IND_M 0x1

/* GLOBAL_CONF_ASIF_ERR_INTR_MASK */
#define GLOBAL_CONF_ASIF_ERR_INTR_MASK_VAL_S 0
#define GLOBAL_CONF_ASIF_ERR_INTR_MASK_VAL_M 0x1

/* GLOBAL_CONF_PAD_DEFAULT */
#define GLOBAL_CONF_PAD_DEFAULT_VAL_S 0
#define GLOBAL_CONF_PAD_DEFAULT_VAL_M 0xF

/* GLOBAL_CONF_PAD_SEL */
#define GLOBAL_CONF_PAD_SEL_VAL_S 0
#define GLOBAL_CONF_PAD_SEL_VAL_M 0x3

/* GLOBAL_CONF_ACCESS_PROT_UNIT */
#define GLOBAL_CONF_ACCESS_PROT_UNIT_SEL_S 0
#define GLOBAL_CONF_ACCESS_PROT_UNIT_SEL_M 0x1F

/* GLOBAL_CONF_ACCESS_PROT_CTRL */
#define GLOBAL_CONF_ACCESS_PROT_CTRL_PRIO_WR_S 0
#define GLOBAL_CONF_ACCESS_PROT_CTRL_PRIO_WR_M 0x3
#define GLOBAL_CONF_ACCESS_PROT_CTRL_PRIO_RD_S 2
#define GLOBAL_CONF_ACCESS_PROT_CTRL_PRIO_RD_M 0xC
#define GLOBAL_CONF_ACCESS_PROT_CTRL_PRIO_EN_S 4
#define GLOBAL_CONF_ACCESS_PROT_CTRL_PRIO_EN_M 0x10
#define GLOBAL_CONF_ACCESS_PROT_CTRL_PSLVERR_S 5
#define GLOBAL_CONF_ACCESS_PROT_CTRL_PSLVERR_M 0x20

/* GLOBAL_CONF_ACCESS_PROT_INFO_STS */
#define GLOBAL_CONF_ACCESS_PROT_INFO_STS_EMPTY_S 0
#define GLOBAL_CONF_ACCESS_PROT_INFO_STS_EMPTY_M 0x1
#define GLOBAL_CONF_ACCESS_PROT_INFO_STS_FULL_S 1
#define GLOBAL_CONF_ACCESS_PROT_INFO_STS_FULL_M 0x2

/* GLOBAL_CONF_ACCESS_PROT_INFO0 */
#define GLOBAL_CONF_ACCESS_PROT_INFO0_ADDR_S 0
#define GLOBAL_CONF_ACCESS_PROT_INFO0_ADDR_M 0xFFFFFFFF

/* GLOBAL_CONF_ACCESS_PROT_INFO1 */
#define GLOBAL_CONF_ACCESS_PROT_INFO1_USER_S 0
#define GLOBAL_CONF_ACCESS_PROT_INFO1_USER_M 0x3FFFFFFF
#define GLOBAL_CONF_ACCESS_PROT_INFO1_PROT_S 30
#define GLOBAL_CONF_ACCESS_PROT_INFO1_PROT_M 0xC0000000

/* GLOBAL_CONF_FORCE_PAD_INACTIVE */
#define GLOBAL_CONF_FORCE_PAD_INACTIVE_VAL_S 0
#define GLOBAL_CONF_FORCE_PAD_INACTIVE_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_ADC_CLK_FREQ */
#define GLOBAL_CONF_ADC_CLK_FREQ_VAL_S 0
#define GLOBAL_CONF_ADC_CLK_FREQ_VAL_M 0xFF

/* GLOBAL_CONF_ADC_DELAY_FROM_START */
#define GLOBAL_CONF_ADC_DELAY_FROM_START_VAL_S 0
#define GLOBAL_CONF_ADC_DELAY_FROM_START_VAL_M 0xFF

/* GLOBAL_CONF_ADC_SAMPLES */
#define GLOBAL_CONF_ADC_SAMPLES_DATA_SAMPLES_S 0
#define GLOBAL_CONF_ADC_SAMPLES_DATA_SAMPLES_M 0x1F
#define GLOBAL_CONF_ADC_SAMPLES_CLK_SAMPLES_S 8
#define GLOBAL_CONF_ADC_SAMPLES_CLK_SAMPLES_M 0x1F00

/* GLOBAL_CONF_ADC_TPH_CS */
#define GLOBAL_CONF_ADC_TPH_CS_VAL_S 0
#define GLOBAL_CONF_ADC_TPH_CS_VAL_M 0xFF

/* GLOBAL_CONF_ADC_LSB_NMSB */
#define GLOBAL_CONF_ADC_LSB_NMSB_VAL_S 0
#define GLOBAL_CONF_ADC_LSB_NMSB_VAL_M 0x1

/* GLOBAL_CONF_ADC_ONE_NCONTIUES */
#define GLOBAL_CONF_ADC_ONE_NCONTIUES_VAL_S 0
#define GLOBAL_CONF_ADC_ONE_NCONTIUES_VAL_M 0x1

/* GLOBAL_CONF_ADC_BLOCK_ENABLE */
#define GLOBAL_CONF_ADC_BLOCK_ENABLE_VAL_S 0
#define GLOBAL_CONF_ADC_BLOCK_ENABLE_VAL_M 0x1
#define GLOBAL_CONF_ADC_BLOCK_ENABLE_CH_SEL_S 4
#define GLOBAL_CONF_ADC_BLOCK_ENABLE_CH_SEL_M 0x30

/* GLOBAL_CONF_ADC_TDV_CSDO */
#define GLOBAL_CONF_ADC_TDV_CSDO_VAL_S 0
#define GLOBAL_CONF_ADC_TDV_CSDO_VAL_M 0xFFF

/* GLOBAL_CONF_ADC_TSU_CSCK */
#define GLOBAL_CONF_ADC_TSU_CSCK_VAL_S 0
#define GLOBAL_CONF_ADC_TSU_CSCK_VAL_M 0xFF

/* GLOBAL_CONF_ADC_CH_SEL */
#define GLOBAL_CONF_ADC_CH_SEL_SEL_DELAY_S 0
#define GLOBAL_CONF_ADC_CH_SEL_SEL_DELAY_M 0xFF
#define GLOBAL_CONF_ADC_CH_SEL_SEL_MAX_S 8
#define GLOBAL_CONF_ADC_CH_SEL_SEL_MAX_M 0x300

/* GLOBAL_CONF_ADC_WRITE_ADDR */
#define GLOBAL_CONF_ADC_WRITE_ADDR_VAL_S 0
#define GLOBAL_CONF_ADC_WRITE_ADDR_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_ADC_CFG_DATA */
#define GLOBAL_CONF_ADC_CFG_DATA_VAL_S 0
#define GLOBAL_CONF_ADC_CFG_DATA_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_ADC_AUX_STM_CTRL */
#define GLOBAL_CONF_ADC_AUX_STM_CTRL_AUX_WR_EN_S 0
#define GLOBAL_CONF_ADC_AUX_STM_CTRL_AUX_WR_EN_M 0x1
#define GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_WR_EN_S 1
#define GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_WR_EN_M 0x2
#define GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_GRNT_S 12
#define GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_GRNT_M 0x1000
#define GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_IS_DATA_S 13
#define GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_IS_DATA_M 0x2000
#define GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_IS_TS_S 14
#define GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_IS_TS_M 0x4000
#define GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_IS_MARKED_S 15
#define GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_IS_MARKED_M 0x8000
#define GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_CAUSE_TRIG_S 16
#define GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_CAUSE_TRIG_M 0x10000

/* GLOBAL_CONF_ADC_STM_ID */
#define GLOBAL_CONF_ADC_STM_ID_STM_MSTR_ID_S 0
#define GLOBAL_CONF_ADC_STM_ID_STM_MSTR_ID_M 0x3F

/* GLOBAL_CONF_ADC_STM_CH_OFFSET */
#define GLOBAL_CONF_ADC_STM_CH_OFFSET_VAL_S 0
#define GLOBAL_CONF_ADC_STM_CH_OFFSET_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_ADC_GLOBAL_CTRL */
#define GLOBAL_CONF_ADC_GLOBAL_CTRL_MODE_S 0
#define GLOBAL_CONF_ADC_GLOBAL_CTRL_MODE_M 0x3

/* GLOBAL_CONF_ADC_GENERIC_CTRL */
#define GLOBAL_CONF_ADC_GENERIC_CTRL_SCLK_PRE_CS_S 0
#define GLOBAL_CONF_ADC_GENERIC_CTRL_SCLK_PRE_CS_M 0x1
#define GLOBAL_CONF_ADC_GENERIC_CTRL_SCLK_CONT_MODE_S 1
#define GLOBAL_CONF_ADC_GENERIC_CTRL_SCLK_CONT_MODE_M 0x2

/* GLOBAL_CONF_SMI_ACCESS_EN */
#define GLOBAL_CONF_SMI_ACCESS_EN_VAL_S 0
#define GLOBAL_CONF_SMI_ACCESS_EN_VAL_M 0x1

/* GLOBAL_CONF_SCRATCHPAD_INIT_CTRL */
#define GLOBAL_CONF_SCRATCHPAD_INIT_CTRL_START_S 0
#define GLOBAL_CONF_SCRATCHPAD_INIT_CTRL_START_M 0x1
#define GLOBAL_CONF_SCRATCHPAD_INIT_CTRL_DONE_S 4
#define GLOBAL_CONF_SCRATCHPAD_INIT_CTRL_DONE_M 0x10

/* GLOBAL_CONF_SCRATCHPAD_INIT_STS */
#define GLOBAL_CONF_SCRATCHPAD_INIT_STS_INIT_DONE_S 0
#define GLOBAL_CONF_SCRATCHPAD_INIT_STS_INIT_DONE_M 0x1
#define GLOBAL_CONF_SCRATCHPAD_INIT_STS_INIT_BUSY_S 1
#define GLOBAL_CONF_SCRATCHPAD_INIT_STS_INIT_BUSY_M 0x2

/* GLOBAL_CONF_MEM_CPY_CTRL */
#define GLOBAL_CONF_MEM_CPY_CTRL_EN_S 0
#define GLOBAL_CONF_MEM_CPY_CTRL_EN_M 0x1

/* GLOBAL_CONF_MEM_CPY_STATUS */
#define GLOBAL_CONF_MEM_CPY_STATUS_DONE_S 0
#define GLOBAL_CONF_MEM_CPY_STATUS_DONE_M 0x1

/* GLOBAL_CONF_MEM_CPY_START_ADDR_H */
#define GLOBAL_CONF_MEM_CPY_START_ADDR_H_VAL_S 0
#define GLOBAL_CONF_MEM_CPY_START_ADDR_H_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_MEM_CPY_START_ADDR_L */
#define GLOBAL_CONF_MEM_CPY_START_ADDR_L_VAL_S 0
#define GLOBAL_CONF_MEM_CPY_START_ADDR_L_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_MEM_CPY_DEST_ADDR_H */
#define GLOBAL_CONF_MEM_CPY_DEST_ADDR_H_VAL_S 0
#define GLOBAL_CONF_MEM_CPY_DEST_ADDR_H_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_MEM_CPY_DEST_ADDR_L */
#define GLOBAL_CONF_MEM_CPY_DEST_ADDR_L_VAL_S 0
#define GLOBAL_CONF_MEM_CPY_DEST_ADDR_L_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_MEM_CPY_CTRL2 */
#define GLOBAL_CONF_MEM_CPY_CTRL2_MEM_SIZE_S 0
#define GLOBAL_CONF_MEM_CPY_CTRL2_MEM_SIZE_M 0xFFFF
#define GLOBAL_CONF_MEM_CPY_CTRL2_WR_OS_S 16
#define GLOBAL_CONF_MEM_CPY_CTRL2_WR_OS_M 0x3F0000
#define GLOBAL_CONF_MEM_CPY_CTRL2_RD_OS_S 24
#define GLOBAL_CONF_MEM_CPY_CTRL2_RD_OS_M 0x3F000000
#define GLOBAL_CONF_MEM_CPY_CTRL2_USE_CONST_S 31
#define GLOBAL_CONF_MEM_CPY_CTRL2_USE_CONST_M 0x80000000

/* GLOBAL_CONF_MEM_CPY_CONST */
#define GLOBAL_CONF_MEM_CPY_CONST_VAL_S 0
#define GLOBAL_CONF_MEM_CPY_CONST_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_MEM_CPY_CURR_ADDR_H */
#define GLOBAL_CONF_MEM_CPY_CURR_ADDR_H_VAL_S 0
#define GLOBAL_CONF_MEM_CPY_CURR_ADDR_H_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_MEM_CPY_CURR_ADDR_L */
#define GLOBAL_CONF_MEM_CPY_CURR_ADDR_L_VAL_S 0
#define GLOBAL_CONF_MEM_CPY_CURR_ADDR_L_VAL_M 0xFFFFFFFF

/* GLOBAL_CONF_PLL_DUMP_CRTL */
#define GLOBAL_CONF_PLL_DUMP_CRTL_PLL_SEL_S 0
#define GLOBAL_CONF_PLL_DUMP_CRTL_PLL_SEL_M 0x3F
#define GLOBAL_CONF_PLL_DUMP_CRTL_BIT_SEL_S 8
#define GLOBAL_CONF_PLL_DUMP_CRTL_BIT_SEL_M 0xF00

/* GLOBAL_CONF_BTL_STOP_SPI_CLK */
#define GLOBAL_CONF_BTL_STOP_SPI_CLK_VAL_S 0
#define GLOBAL_CONF_BTL_STOP_SPI_CLK_VAL_M 0x1

/* GLOBAL_CONF_DFT_APB_CONTROL */
#define GLOBAL_CONF_DFT_APB_CONTROL_SPIF_MODE_S 0
#define GLOBAL_CONF_DFT_APB_CONTROL_SPIF_MODE_M 0x1
#define GLOBAL_CONF_DFT_APB_CONTROL_RESERVED_OUT_S 1
#define GLOBAL_CONF_DFT_APB_CONTROL_RESERVED_OUT_M 0xFFFE
#define GLOBAL_CONF_DFT_APB_CONTROL_RESERVED_IN_S 16
#define GLOBAL_CONF_DFT_APB_CONTROL_RESERVED_IN_M 0xFFFF0000

#endif /* ASIC_REG_GLOBAL_CONF_MASKS_H_ */
