/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_HBM_PHY_CHANNELS_CH0_AW_REGS_H_
#define ASIC_REG_HBM_PHY_CHANNELS_CH0_AW_REGS_H_

/*
 *****************************************
 *   HBM_PHY_CHANNELS_CH0_AW
 *   (Prototype: HBM_PHY_P0_CHANX_AWORD)
 *****************************************
 */

#define mmHBM_PHY_CHANNELS_CH0_AW_AWREMAP 0x0

#define mmHBM_PHY_CHANNELS_CH0_AW_IOCTRL 0x4

#define mmHBM_PHY_CHANNELS_CH0_AW_REMAPCTRL 0x8

#define mmHBM_PHY_CHANNELS_CH0_AW_AWLANEDISLN15LN0 0xC

#define mmHBM_PHY_CHANNELS_CH0_AW_AWLANEDISLN23LN16 0x10

#define mmHBM_PHY_CHANNELS_CH0_AW_AWERRSTATUS 0x14

#define mmHBM_PHY_CHANNELS_CH0_AW_RSVDAWORD 0x18

#define mmHBM_PHY_CHANNELS_CH0_AW_PHYCTLUPDGOODCTR 0x1C

#define mmHBM_PHY_CHANNELS_CH0_AW_PHYCTLUPDFAILCTR 0x20

#define mmHBM_PHY_CHANNELS_CH0_AW_CTLPHYUPDGOODCTR 0x24

#define mmHBM_PHY_CHANNELS_CH0_AW_CHANENABLE 0x28

#define mmHBM_PHY_CHANNELS_CH0_AW_CMDRDPTRINITVAL_P0 0x2C

#define mmHBM_PHY_CHANNELS_CH0_AW_ACRDLAT 0x30

#define mmHBM_PHY_CHANNELS_CH0_AW_RESETFIFO 0x34

#define mmHBM_PHY_CHANNELS_CH0_AW_RXPWRDN 0x38

#define mmHBM_PHY_CHANNELS_CH0_AW_LOOPBACKCTRL 0x3C

#define mmHBM_PHY_CHANNELS_CH0_AW_DFIPHYUPD 0x40

#define mmHBM_PHY_CHANNELS_CH0_AW_PHYPERFCTREN 0x44

#define mmHBM_PHY_CHANNELS_CH0_AW_CALCTRL 0x48

#define mmHBM_PHY_CHANNELS_CH0_AW_DWORDTXCALDATOVR 0x4C

#define mmHBM_PHY_CHANNELS_CH0_AW_DWORDTXCALSTROBEOVR 0x50

#define mmHBM_PHY_CHANNELS_CH0_AW_AWTXCALDATOVR 0x54

#define mmHBM_PHY_CHANNELS_CH0_AW_AWTXCALSTROBEOVR 0x58

#define mmHBM_PHY_CHANNELS_CH0_AW_LCDLCALPHASE 0x5C

#define mmHBM_PHY_CHANNELS_CH0_AW_LCDLCALCTRL 0x60

#define mmHBM_PHY_CHANNELS_CH0_AW_LCDLTRAINPARAM 0x64

#define mmHBM_PHY_CHANNELS_CH0_AW_LCDLGAINCTL_P0 0x68

#define mmHBM_PHY_CHANNELS_CH0_AW_LCDLLOCKPARAM_P0 0x6C

#define mmHBM_PHY_CHANNELS_CH0_AW_AWLCDLSEL 0x74

#define mmHBM_PHY_CHANNELS_CH0_AW_DLYTESTSEQ 0x78

#define mmHBM_PHY_CHANNELS_CH0_AW_DLYTESTCNTDFICLKIV 0x7C

#define mmHBM_PHY_CHANNELS_CH0_AW_TXACMINDLY 0x80

#define mmHBM_PHY_CHANNELS_CH0_AW_TXACMAXDLY 0x84

#define mmHBM_PHY_CHANNELS_CH0_AW_TXACDLY_P0 0x88

#define mmHBM_PHY_CHANNELS_CH0_AW_TXCKDLY_P0 0x8C

#define mmHBM_PHY_CHANNELS_CH0_AW_AWLCDLCTRL 0x94

#define mmHBM_PHY_CHANNELS_CH0_AW_TXACLCDL1UI 0x98

#define mmHBM_PHY_CHANNELS_CH0_AW_TXCKLCDL1UI 0x9C

#define mmHBM_PHY_CHANNELS_CH0_AW_AWLCDLCALPHDETOUT 0xA0

#define mmHBM_PHY_CHANNELS_CH0_AW_AWDLYTESTCNTRINGOSC 0xA4

#define mmHBM_PHY_CHANNELS_CH0_AW_DLYTESTCNTDFICLK 0xA8

#define mmHBM_PHY_CHANNELS_CH0_AW_DRAMPARAM0_P0 0xAC

#define mmHBM_PHY_CHANNELS_CH0_AW_DRAMPARAM1_P0 0xB0

#define mmHBM_PHY_CHANNELS_CH0_AW_DATACTRL 0xB4

#define mmHBM_PHY_CHANNELS_CH0_AW_AWDATACTRL 0xB8

#define mmHBM_PHY_CHANNELS_CH0_AW_AWDATA0 0xBC

#define mmHBM_PHY_CHANNELS_CH0_AW_AWDATA1 0xC0

#define mmHBM_PHY_CHANNELS_CH0_AW_AWDATASTATUS0 0xC4

#define mmHBM_PHY_CHANNELS_CH0_AW_AWDATASTATUS1 0xC8

#define mmHBM_PHY_CHANNELS_CH0_AW_AWDATABITERR0 0xCC

#define mmHBM_PHY_CHANNELS_CH0_AW_AWDATABITERR1 0xD0

#define mmHBM_PHY_CHANNELS_CH0_AW_RDQSCTRL 0xD4

#define mmHBM_PHY_CHANNELS_CH0_AW_AWDATA2 0xD8

#endif /* ASIC_REG_HBM_PHY_CHANNELS_CH0_AW_REGS_H_ */
