/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_MC_CMN_MASKS_H_
#define ASIC_REG_MC_CMN_MASKS_H_

/*
 *****************************************
 *   MC_CMN
 *   (Prototype: MC_CMN)
 *****************************************
 */

/* MC_CMN_COMPRS */
#define MC_CMN_COMPRS_MOD_S 0
#define MC_CMN_COMPRS_MOD_M 0xFFFF
#define MC_CMN_COMPRS_EN_S 16
#define MC_CMN_COMPRS_EN_M 0x10000

/* MC_CMN_HCON_AXIS_WR_MAX_CRED */
#define MC_CMN_HCON_AXIS_WR_MAX_CRED_VAL_S 0
#define MC_CMN_HCON_AXIS_WR_MAX_CRED_VAL_M 0xFF

/* MC_CMN_HCON_AXIS_RD_MAX_INFLIGHT */
#define MC_CMN_HCON_AXIS_RD_MAX_INFLIGHT_VAL_S 0
#define MC_CMN_HCON_AXIS_RD_MAX_INFLIGHT_VAL_M 0xFF

/* MC_CMN_HCON_AXIS_WR_CRED_STS */
#define MC_CMN_HCON_AXIS_WR_CRED_STS_VAL_S 0
#define MC_CMN_HCON_AXIS_WR_CRED_STS_VAL_M 0xFF

/* MC_CMN_HCON_AXIS_RD_INFLIGHT_STS */
#define MC_CMN_HCON_AXIS_RD_INFLIGHT_STS_VAL_S 0
#define MC_CMN_HCON_AXIS_RD_INFLIGHT_STS_VAL_M 0xFF

/* MC_CMN_HCON_RD_RSP_CB_STS */
#define MC_CMN_HCON_RD_RSP_CB_STS_LVL_S 0
#define MC_CMN_HCON_RD_RSP_CB_STS_LVL_M 0xFF
#define MC_CMN_HCON_RD_RSP_CB_STS_PIPE_EMPTY_S 8
#define MC_CMN_HCON_RD_RSP_CB_STS_PIPE_EMPTY_M 0x100

/* MC_CMN_DBG_CNTR_EN */
#define MC_CMN_DBG_CNTR_EN_VAL_S 0
#define MC_CMN_DBG_CNTR_EN_VAL_M 0x1

/* MC_CMN_DBG_CNTR_CC */
#define MC_CMN_DBG_CNTR_CC_VAL_S 0
#define MC_CMN_DBG_CNTR_CC_VAL_M 0xFFFFFFFF

/* MC_CMN_DBG_CNTR_VAL */
#define MC_CMN_DBG_CNTR_VAL_VAL_S 0
#define MC_CMN_DBG_CNTR_VAL_VAL_M 0xFFFFFFFF

/* MC_CMN_DBG_TRACE_PL_EVE_MSK */
#define MC_CMN_DBG_TRACE_PL_EVE_MSK_VAL_S 0
#define MC_CMN_DBG_TRACE_PL_EVE_MSK_VAL_M 0xFFFFFFFF

/* MC_CMN_DBG_TRACE_CFG */
#define MC_CMN_DBG_TRACE_CFG_PC_SEL_S 0
#define MC_CMN_DBG_TRACE_CFG_PC_SEL_M 0x7
#define MC_CMN_DBG_TRACE_CFG_HWEVENTS_STRETCH_CC_SEL_S 3
#define MC_CMN_DBG_TRACE_CFG_HWEVENTS_STRETCH_CC_SEL_M 0x38

/* MC_CMN_DBG_TRACE_PL_DATA_MSK */
#define MC_CMN_DBG_TRACE_PL_DATA_MSK_VAL_S 0
#define MC_CMN_DBG_TRACE_PL_DATA_MSK_VAL_M 0xFFFFFFFF

#endif /* ASIC_REG_MC_CMN_MASKS_H_ */
