/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_MME_CTRL_LO_ARCH_DMA_N_TEN_REGS_H_
#define ASIC_REG_MME_CTRL_LO_ARCH_DMA_N_TEN_REGS_H_

/*
 *****************************************
 *   MME_CTRL_LO_ARCH_DMA_N_TEN
 *   (Prototype: MME_NON_TENSOR_DESCRIPTOR)
 *****************************************
 */

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_CONV_KERNEL_SIZE_MINUS_1 0x0

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_CONV_LO 0x4

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_CONV_HI 0x8

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_OUTER_LOOP 0xC

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_NUM_ITERATIONS_MINUS_1 0x10

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SB_REPEAT 0x14

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SO_CTRL 0x18

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SO_ADDR0 0x1C

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SO_VAL0 0x20

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SO_ADDR1 0x24

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SO_VAL1 0x28

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SLAVE_SO_0_ADDR 0x2C

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SLAVE_SO_1_ADDR 0x30

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_NUMERIC 0x34

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_AXI_AWUSER_DATA 0x38

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_AXI_USER_DATA_A 0x3C

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_AXI_USER_DATA_B 0x40

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_AXI_USER_DATA_COUT 0x44

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_AXI_CACHE_DATA 0x48

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_PERF_EVT_IN 0x4C

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_PERF_EVT_OUT 0x50

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_PERF_EVT_EU 0x54

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_RATE_LIMITER 0x58

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_POWER 0x5C

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SPARE0_MASTER 0x60

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SPARE1_MASTER 0x64

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SPARE2_MASTER 0x68

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SPARE3_MASTER 0x6C

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SPARE0_SLAVE 0x70

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SPARE1_SLAVE 0x74

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SPARE2_SLAVE 0x78

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_SPARE3_SLAVE 0x7C

#define mmMME_CTRL_LO_ARCH_DMA_N_TEN_WKL_ID 0x80

#endif /* ASIC_REG_MME_CTRL_LO_ARCH_DMA_N_TEN_REGS_H_ */
