/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC_TMR_REGS_H_
#define ASIC_REG_NIC_TMR_REGS_H_

/*
 *****************************************
 *   NIC_TMR
 *   (Prototype: NIC_TMR)
 *****************************************
 */

#define mmNIC_TMR_TMR_PUSH_MASK 0x0

#define mmNIC_TMR_TMR_POP_MASK 0x4

#define mmNIC_TMR_TMR_PUSH_RELEASE_INVALIDATE 0x8

#define mmNIC_TMR_TMR_POP_RELEASE_INVALIDATE 0xC

#define mmNIC_TMR_TMR_LIST_MEM_READ_MASK 0x10

#define mmNIC_TMR_TMR_FIFO_MEM_READ_MASK 0x14

#define mmNIC_TMR_TMR_LIST_MEM_WRITE_MASK 0x18

#define mmNIC_TMR_TMR_FIFO_MEM_WRITE_MASK 0x1C

#define mmNIC_TMR_TMR_BASE_ADDRESS_63_32 0x20

#define mmNIC_TMR_TMR_BASE_ADDRESS_31_7 0x24

#define mmNIC_TMR_TMR_LIST_AXI_PROT 0x2C

#define mmNIC_TMR_TMR_STATE_AXI_PROT 0x34

#define mmNIC_TMR_TMR_SCHEDQ_UPDATE_EN 0x3C

#define mmNIC_TMR_TMR_SCHEDQ_UPDATE_FIFO 0x40

#define mmNIC_TMR_TMR_SCHEDQ_UPDATE_DESC_0 0x44

#define mmNIC_TMR_TMR_SCHEDQ_UPDATE_DESC_1 0x48

#define mmNIC_TMR_TMR_SCHEDQ_UPDATE_DESC_2 0x4C

#define mmNIC_TMR_TMR_SCHEDQ_UPDATE_DESC_3 0x50

#define mmNIC_TMR_TMR_SCHEDQ_UPDATE_DESC_4 0x54

#define mmNIC_TMR_TMR_SCHEDQ_UPDATE_DESC_5 0x58

#define mmNIC_TMR_TMR_SCHEDQ_UPDATE_DESC_6 0x5C

#define mmNIC_TMR_TMR_FORCE_HIT_EN 0x60

#define mmNIC_TMR_TMR_INVALIDATE_LIST 0x64

#define mmNIC_TMR_TMR_INVALIDATE_LIST_STAT 0x68

#define mmNIC_TMR_TMR_INVALIDATE_FREE 0x6C

#define mmNIC_TMR_TMR_INVALIDATE_FREE_STAT 0x70

#define mmNIC_TMR_TMR_PUSH_PREFETCH_EN 0x74

#define mmNIC_TMR_TMR_PUSH_RELEASE_EN 0x78

#define mmNIC_TMR_TMR_PUSH_LOCK_EN 0x7C

#define mmNIC_TMR_TMR_PUSH_PREFETCH_NEXT_EN 0x80

#define mmNIC_TMR_TMR_POP_PREFETCH_EN 0x84

#define mmNIC_TMR_TMR_POP_RELEASE_EN 0x88

#define mmNIC_TMR_TMR_POP_LOCK_EN 0x8C

#define mmNIC_TMR_TMR_POP_PREFETCH_NEXT_EN 0x90

#define mmNIC_TMR_TMR_LIST_MASK 0x94

#define mmNIC_TMR_TMR_RELEASE_INCALIDATE 0x98

#define mmNIC_TMR_TMR_BASE_ADDRESS_FREE_LIST_63_32 0x9C

#define mmNIC_TMR_TMR_BASE_ADDRESS_FREE_LIST_31_0 0xA0

#define mmNIC_TMR_TMR_FREE_LIST_EN 0xA4

#define mmNIC_TMR_TMR_PUSH_FORCE_HIT_EN 0xA8

#define mmNIC_TMR_TMR_PRODUCER_UPDATE_EN 0xAC

#define mmNIC_TMR_TMR_PRODUCER_UPDATE 0xB0

#define mmNIC_TMR_TMR_CAHE_INVALIDATE 0xB4

#define mmNIC_TMR_TMR_CAHE_INVALIDATE_STAT 0xB8

#define mmNIC_TMR_TMR_CACHE_CLEAR_LINK_LIST 0xBC

#define mmNIC_TMR_TMR_CACHE_CFG 0xC0

#define mmNIC_TMR_TMR_CACHE_BASE_ADDR_63_32 0xC4

#define mmNIC_TMR_TMR_CACHE_BASE_ADDR_31_7 0xC8

#define mmNIC_TMR_TMR_TIMER_EN 0xCC

#define mmNIC_TMR_TMR_TICK_WRAP 0xD0

#define mmNIC_TMR_TMR_SCAN_TIMER_COMP_47_32 0xD4

#define mmNIC_TMR_TMR_SCAN_TIMER_COMP_31_0 0xD8

#define mmNIC_TMR_TMR_SCHEDQS_0 0xDC

#define mmNIC_TMR_TMR_SCHEDQS_1 0xE0

#define mmNIC_TMR_TMR_SCHEDQS_2 0xE4

#define mmNIC_TMR_TMR_SCHEDQS_3 0xE8

#define mmNIC_TMR_TMR_CACHES_CFG 0xEC

#define mmNIC_TMR_TMR_DBG_COUNT_SELECT_0 0xF0

#define mmNIC_TMR_TMR_DBG_COUNT_SELECT_1 0xF4

#define mmNIC_TMR_TMR_DBG_COUNT_SELECT_2 0xF8

#define mmNIC_TMR_TMR_DBG_COUNT_SELECT_3 0xFC

#define mmNIC_TMR_TMR_DBG_COUNT_SELECT_4 0x100

#define mmNIC_TMR_TMR_DBG_COUNT_SELECT_5 0x104

#define mmNIC_TMR_TMR_DBG_COUNT_SELECT_6 0x108

#define mmNIC_TMR_TMR_DBG_COUNT_SELECT_7 0x10C

#define mmNIC_TMR_TMR_DBG_COUNT_SELECT_8 0x110

#define mmNIC_TMR_TMR_DBG_COUNT_SELECT_9 0x114

#define mmNIC_TMR_TMR_DBG_COUNT_SELECT_10 0x118

#define mmNIC_TMR_TMR_DBG_COUNT_SELECT_11 0x11C

#define mmNIC_TMR_TMR_POP_CACHE_CREDIT 0x138

#define mmNIC_TMR_TMR_PIPE_CREDIT 0x13C

#define mmNIC_TMR_TMR_DBG_TRIG 0x140

#define mmNIC_TMR_INTERRUPT_CAUSE 0x144

#define mmNIC_TMR_INTERRUPT_MASK 0x148

#define mmNIC_TMR_INTERRUPT_CLR 0x14C

#define mmNIC_TMR_TMR_SLICE_CREDIT 0x150

#define mmNIC_TMR_TMR_AXI_CACHE 0x154

#define mmNIC_TMR_FREE_LIST_PUSH_MASK_EN 0x158

#define mmNIC_TMR_FREE_AEMPTY_THRESHOLD 0x15C

#define mmNIC_TMR_MEM_WRITE_INIT 0x170

#define mmNIC_TMR_IMMEDIATE_SQ 0x180

#define mmNIC_TMR_APB_ADDR_MASK 0x200

#define mmNIC_TMR_APB_SPLIT_ADDR0 0x204

#endif /* ASIC_REG_NIC_TMR_REGS_H_ */
