/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC_MAC_GLOB_STAT_RX2_REGS_H_
#define ASIC_REG_NIC_MAC_GLOB_STAT_RX2_REGS_H_

/*
 *****************************************
 *   NIC_MAC_GLOB_STAT_RX2
 *   (Prototype: MAC_MAC2_RX_CNT)
 *****************************************
 */

#define mmNIC_MAC_GLOB_STAT_RX2_ETHERSTATSOCTETS_2 0x0

#define mmNIC_MAC_GLOB_STAT_RX2_OCTETSRECEIVEDOK_2 0x4

#define mmNIC_MAC_GLOB_STAT_RX2_AALIGNMENTERRORS_2 0x8

#define mmNIC_MAC_GLOB_STAT_RX2_APAUSEMACCTRLFRAMESRECEIVED_2 0xC

#define mmNIC_MAC_GLOB_STAT_RX2_AFRAMETOOLONGERRORS_2 0x10

#define mmNIC_MAC_GLOB_STAT_RX2_AINRANGELENGTHERRORS_2 0x14

#define mmNIC_MAC_GLOB_STAT_RX2_AFRAMESRECEIVEDOK_2 0x18

#define mmNIC_MAC_GLOB_STAT_RX2_AFRAMECHECKSEQUENCEERRORS_2 0x1C

#define mmNIC_MAC_GLOB_STAT_RX2_VLANRECEIVEDOK_2 0x20

#define mmNIC_MAC_GLOB_STAT_RX2_IFINERRORS_2 0x24

#define mmNIC_MAC_GLOB_STAT_RX2_IFINUCASTPKTS_2 0x28

#define mmNIC_MAC_GLOB_STAT_RX2_IFINMULTICASTPKTS_2 0x2C

#define mmNIC_MAC_GLOB_STAT_RX2_IFINBROADCASTPKTS_2 0x30

#define mmNIC_MAC_GLOB_STAT_RX2_ETHERSTATSDROPEVENTS_2 0x34

#define mmNIC_MAC_GLOB_STAT_RX2_ETHERSTATSPKTS_2 0x38

#define mmNIC_MAC_GLOB_STAT_RX2_ETHERSTATSUNDERSIZEPKTS_2 0x3C

#define mmNIC_MAC_GLOB_STAT_RX2_ETHERSTATSPKTS64OCTETS_2 0x40

#define mmNIC_MAC_GLOB_STAT_RX2_ETHERSTATSPKTS65TO127OCTETS_2 0x44

#define mmNIC_MAC_GLOB_STAT_RX2_ETHERSTATSPKTS128TO255OCTETS_2 0x48

#define mmNIC_MAC_GLOB_STAT_RX2_ETHERSTATSPKTS256TO511OCTETS_2 0x4C

#define mmNIC_MAC_GLOB_STAT_RX2_ETHERSTATSPKTS512TO1023OCTETS_2 0x50

#define mmNIC_MAC_GLOB_STAT_RX2_ETHERSTATSPKTS1024TO1518OCTETS_2 0x54

#define mmNIC_MAC_GLOB_STAT_RX2_ETHERSTATSPKTS1519TOMAXOCTETS_2 0x58

#define mmNIC_MAC_GLOB_STAT_RX2_ETHERSTATSOVERSIZEPKTS_2 0x5C

#define mmNIC_MAC_GLOB_STAT_RX2_ETHERSTATSJABBERS_2 0x60

#define mmNIC_MAC_GLOB_STAT_RX2_ETHERSTATSFRAGMENTS_2 0x64

#define mmNIC_MAC_GLOB_STAT_RX2_ACBFCPAUSEFRAMESRECEIVED0_2 0x68

#define mmNIC_MAC_GLOB_STAT_RX2_ACBFCPAUSEFRAMESRECEIVED1_2 0x6C

#define mmNIC_MAC_GLOB_STAT_RX2_ACBFCPAUSEFRAMESRECEIVED2_2 0x70

#define mmNIC_MAC_GLOB_STAT_RX2_ACBFCPAUSEFRAMESRECEIVED3_2 0x74

#define mmNIC_MAC_GLOB_STAT_RX2_ACBFCPAUSEFRAMESRECEIVED4_2 0x78

#define mmNIC_MAC_GLOB_STAT_RX2_ACBFCPAUSEFRAMESRECEIVED5_2 0x7C

#define mmNIC_MAC_GLOB_STAT_RX2_ACBFCPAUSEFRAMESRECEIVED6_2 0x80

#define mmNIC_MAC_GLOB_STAT_RX2_ACBFCPAUSEFRAMESRECEIVED7_2 0x84

#define mmNIC_MAC_GLOB_STAT_RX2_AMACCONTROLFRAMESRECEIVED_2 0x88

#endif /* ASIC_REG_NIC_MAC_GLOB_STAT_RX2_REGS_H_ */
