/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC_RXE_MASKS_H_
#define ASIC_REG_NIC_RXE_MASKS_H_

/*
 *****************************************
 *   NIC_RXE
 *   (Prototype: NIC_RXE)
 *****************************************
 */

/* NIC_RXE_CONTROL */
#define NIC_RXE_CONTROL_SCATTER_BARRIER_S 0
#define NIC_RXE_CONTROL_SCATTER_BARRIER_M 0x1
#define NIC_RXE_CONTROL_IGNORE_RNR_NAK_S 1
#define NIC_RXE_CONTROL_IGNORE_RNR_NAK_M 0x2
#define NIC_RXE_CONTROL_SOB_CQ_MUTEX_S 2
#define NIC_RXE_CONTROL_SOB_CQ_MUTEX_M 0x4
#define NIC_RXE_CONTROL_SPARE0_S 3
#define NIC_RXE_CONTROL_SPARE0_M 0xFFF8
#define NIC_RXE_CONTROL_SPARE1_S 16
#define NIC_RXE_CONTROL_SPARE1_M 0xFFFF0000

/* NIC_RXE_RAW_QPN_P0 */
#define NIC_RXE_RAW_QPN_P0_RAW_QPN_P0_S 0
#define NIC_RXE_RAW_QPN_P0_RAW_QPN_P0_M 0xFFFFFF

/* NIC_RXE_RAW_QPN_P1 */
#define NIC_RXE_RAW_QPN_P1_RAW_QPN_P1_S 0
#define NIC_RXE_RAW_QPN_P1_RAW_QPN_P1_M 0xFFFFFF

/* NIC_RXE_RAW_QPN_P2 */
#define NIC_RXE_RAW_QPN_P2_RAW_QPN_P2_S 0
#define NIC_RXE_RAW_QPN_P2_RAW_QPN_P2_M 0xFFFFFF

/* NIC_RXE_RAW_QPN_P3 */
#define NIC_RXE_RAW_QPN_P3_RAW_QPN_P3_S 0
#define NIC_RXE_RAW_QPN_P3_RAW_QPN_P3_M 0xFFFFFF

/* NIC_RXE_PKT_CHECKS_EN */
#define NIC_RXE_PKT_CHECKS_EN_PKT_BAD_FORMAT_S 0
#define NIC_RXE_PKT_CHECKS_EN_PKT_BAD_FORMAT_M 0x1
#define NIC_RXE_PKT_CHECKS_EN_PKT_PRS_FSM_INV_S 1
#define NIC_RXE_PKT_CHECKS_EN_PKT_PRS_FSM_INV_M 0x2
#define NIC_RXE_PKT_CHECKS_EN_PKT_HDRS_SIZE_INV_S 2
#define NIC_RXE_PKT_CHECKS_EN_PKT_HDRS_SIZE_INV_M 0x4
#define NIC_RXE_PKT_CHECKS_EN_PKT_IPV4_LEN_INV_S 3
#define NIC_RXE_PKT_CHECKS_EN_PKT_IPV4_LEN_INV_M 0x8
#define NIC_RXE_PKT_CHECKS_EN_PKT_IPV6_LEN_INV_S 4
#define NIC_RXE_PKT_CHECKS_EN_PKT_IPV6_LEN_INV_M 0x10
#define NIC_RXE_PKT_CHECKS_EN_PKT_TUNNEL_INV_S 5
#define NIC_RXE_PKT_CHECKS_EN_PKT_TUNNEL_INV_M 0x20
#define NIC_RXE_PKT_CHECKS_EN_PKT_PRS_HINT_INV_S 6
#define NIC_RXE_PKT_CHECKS_EN_PKT_PRS_HINT_INV_M 0x40
#define NIC_RXE_PKT_CHECKS_EN_PKT_BTH_OPCODE_INV_S 7
#define NIC_RXE_PKT_CHECKS_EN_PKT_BTH_OPCODE_INV_M 0x80
#define NIC_RXE_PKT_CHECKS_EN_PKT_SYNDROME_INV_S 8
#define NIC_RXE_PKT_CHECKS_EN_PKT_SYNDROME_INV_M 0x100
#define NIC_RXE_PKT_CHECKS_EN_PKT_RC_MAX_SIZE_INV_S 9
#define NIC_RXE_PKT_CHECKS_EN_PKT_RC_MAX_SIZE_INV_M 0x200
#define NIC_RXE_PKT_CHECKS_EN_PKT_RC_MIN_SIZE_INV_S 10
#define NIC_RXE_PKT_CHECKS_EN_PKT_RC_MIN_SIZE_INV_M 0x400
#define NIC_RXE_PKT_CHECKS_EN_PKT_RAW_INV_S 11
#define NIC_RXE_PKT_CHECKS_EN_PKT_RAW_INV_M 0x800
#define NIC_RXE_PKT_CHECKS_EN_PKT_RAW_INV_LEN_S 12
#define NIC_RXE_PKT_CHECKS_EN_PKT_RAW_INV_LEN_M 0x1000
#define NIC_RXE_PKT_CHECKS_EN_PKT_RAW_MIN_SIZE_INV_S 13
#define NIC_RXE_PKT_CHECKS_EN_PKT_RAW_MIN_SIZE_INV_M 0x2000
#define NIC_RXE_PKT_CHECKS_EN_PKT_RAW_MAX_SIZE_INV_S 14
#define NIC_RXE_PKT_CHECKS_EN_PKT_RAW_MAX_SIZE_INV_M 0x4000

/* NIC_RXE_PKT_CHECKS_ACTION */
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_BAD_FORMAT_S 0
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_BAD_FORMAT_M 0x1
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_PRS_FSM_INV_S 1
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_PRS_FSM_INV_M 0x2
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_HDRS_SIZE_INV_S 2
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_HDRS_SIZE_INV_M 0x4
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_IPV4_LEN_INV_S 3
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_IPV4_LEN_INV_M 0x8
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_IPV6_LEN_INV_S 4
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_IPV6_LEN_INV_M 0x10
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_TUNNEL_INV_S 5
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_TUNNEL_INV_M 0x20
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_PRS_HINT_INV_S 6
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_PRS_HINT_INV_M 0x40
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_BTH_OPCODE_INV_S 7
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_BTH_OPCODE_INV_M 0x80
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_SYNDROME_INV_S 8
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_SYNDROME_INV_M 0x100
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_RC_MAX_SIZE_INV_S 9
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_RC_MAX_SIZE_INV_M 0x200
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_RC_MIN_SIZE_INV_S 10
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_RC_MIN_SIZE_INV_M 0x400
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_RAW_INV_S 11
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_RAW_INV_M 0x800
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_RAW_INV_LEN_S 12
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_RAW_INV_LEN_M 0x1000
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_RAW_MIN_SIZE_INV_S 13
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_RAW_MIN_SIZE_INV_M 0x2000
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_RAW_MAX_SIZE_INV_S 14
#define NIC_RXE_PKT_CHECKS_ACTION_PKT_RAW_MAX_SIZE_INV_M 0x4000

/* NIC_RXE_QPC_CHECKS_EN */
#define NIC_RXE_QPC_CHECKS_EN_QPC_QP_INV_S 0
#define NIC_RXE_QPC_CHECKS_EN_QPC_QP_INV_M 0x1
#define NIC_RXE_QPC_CHECKS_EN_QPC_TS_MISMATCH_S 1
#define NIC_RXE_QPC_CHECKS_EN_QPC_TS_MISMATCH_M 0x2
#define NIC_RXE_QPC_CHECKS_EN_QPC_REQ_CS_INV_S 2
#define NIC_RXE_QPC_CHECKS_EN_QPC_REQ_CS_INV_M 0x4
#define NIC_RXE_QPC_CHECKS_EN_QPC_RES_CS_INV_S 3
#define NIC_RXE_QPC_CHECKS_EN_QPC_RES_CS_INV_M 0x8
#define NIC_RXE_QPC_CHECKS_EN_QPC_RES_RESYNC_INV_S 4
#define NIC_RXE_QPC_CHECKS_EN_QPC_RES_RESYNC_INV_M 0x10
#define NIC_RXE_QPC_CHECKS_EN_QPC_REQ_PSN_INV_S 5
#define NIC_RXE_QPC_CHECKS_EN_QPC_REQ_PSN_INV_M 0x20
#define NIC_RXE_QPC_CHECKS_EN_QPC_REQ_PSN_UNSENT_S 6
#define NIC_RXE_QPC_CHECKS_EN_QPC_REQ_PSN_UNSENT_M 0x40
#define NIC_RXE_QPC_CHECKS_EN_QPC_REQ_SAL_NTS_INV_S 7
#define NIC_RXE_QPC_CHECKS_EN_QPC_REQ_SAL_NTS_INV_M 0x80
#define NIC_RXE_QPC_CHECKS_EN_QPC_RES_RKEY_INV_S 8
#define NIC_RXE_QPC_CHECKS_EN_QPC_RES_RKEY_INV_M 0x100
#define NIC_RXE_QPC_CHECKS_EN_QPC_RES_SAL_PSN_INV_S 9
#define NIC_RXE_QPC_CHECKS_EN_QPC_RES_SAL_PSN_INV_M 0x200

/* NIC_RXE_QPC_CHECKS_ACTION */
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_QP_INV_S 0
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_QP_INV_M 0x1
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_TS_MISMATCH_S 1
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_TS_MISMATCH_M 0x2
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_REQ_CS_INV_S 2
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_REQ_CS_INV_M 0x4
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_RES_CS_INV_S 3
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_RES_CS_INV_M 0x8
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_RES_RESYNC_INV_S 4
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_RES_RESYNC_INV_M 0x10
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_REQ_PSN_INV_S 5
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_REQ_PSN_INV_M 0x20
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_REQ_PSN_UNSENT_S 6
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_REQ_PSN_UNSENT_M 0x40
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_REQ_SAL_NTS_INV_S 7
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_REQ_SAL_NTS_INV_M 0x80
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_RES_RKEY_INV_S 8
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_RES_RKEY_INV_M 0x100
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_RES_SAL_PSN_INV_S 9
#define NIC_RXE_QPC_CHECKS_ACTION_QPC_RES_SAL_PSN_INV_M 0x200

/* NIC_RXE_WQE_CHECKS_EN */
#define NIC_RXE_WQE_CHECKS_EN_WQE_IDX_MISMATCH_S 0
#define NIC_RXE_WQE_CHECKS_EN_WQE_IDX_MISMATCH_M 0x1
#define NIC_RXE_WQE_CHECKS_EN_WQE_WR_OPCODE_INV_S 1
#define NIC_RXE_WQE_CHECKS_EN_WQE_WR_OPCODE_INV_M 0x2
#define NIC_RXE_WQE_CHECKS_EN_WQE_RDV_OPCODE_INV_S 2
#define NIC_RXE_WQE_CHECKS_EN_WQE_RDV_OPCODE_INV_M 0x4
#define NIC_RXE_WQE_CHECKS_EN_WQE_RD_OPCODE_INV_S 3
#define NIC_RXE_WQE_CHECKS_EN_WQE_RD_OPCODE_INV_M 0x8
#define NIC_RXE_WQE_CHECKS_EN_WQE_WR_ZERO_S 4
#define NIC_RXE_WQE_CHECKS_EN_WQE_WR_ZERO_M 0x10
#define NIC_RXE_WQE_CHECKS_EN_WQE_MULTI_ZERO_S 5
#define NIC_RXE_WQE_CHECKS_EN_WQE_MULTI_ZERO_M 0x20
#define NIC_RXE_WQE_CHECKS_EN_WQE_WR_SEND_BIG_S 6
#define NIC_RXE_WQE_CHECKS_EN_WQE_WR_SEND_BIG_M 0x40
#define NIC_RXE_WQE_CHECKS_EN_WQE_MULTI_BIG_S 7
#define NIC_RXE_WQE_CHECKS_EN_WQE_MULTI_BIG_M 0x80

/* NIC_RXE_WQE_CHECKS_ACTION */
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_IDX_MISMATCH_S 0
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_IDX_MISMATCH_M 0x1
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_WR_OPCODE_INV_S 1
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_WR_OPCODE_INV_M 0x2
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_RDV_OPCODE_INV_S 2
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_RDV_OPCODE_INV_M 0x4
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_RD_OPCODE_INV_S 3
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_RD_OPCODE_INV_M 0x8
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_WR_ZERO_S 4
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_WR_ZERO_M 0x10
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_MULTI_ZERO_S 5
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_MULTI_ZERO_M 0x20
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_WR_SEND_BIG_S 6
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_WR_SEND_BIG_M 0x40
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_MULTI_BIG_S 7
#define NIC_RXE_WQE_CHECKS_ACTION_WQE_MULTI_BIG_M 0x80

/* NIC_RXE_PKT_SIZE_CHECK_RC */
#define NIC_RXE_PKT_SIZE_CHECK_RC_MIN_S 0
#define NIC_RXE_PKT_SIZE_CHECK_RC_MIN_M 0xFFFF
#define NIC_RXE_PKT_SIZE_CHECK_RC_MAX_S 16
#define NIC_RXE_PKT_SIZE_CHECK_RC_MAX_M 0xFFFF0000

/* NIC_RXE_PKT_SIZE_CHECK_RAW */
#define NIC_RXE_PKT_SIZE_CHECK_RAW_MIN_S 0
#define NIC_RXE_PKT_SIZE_CHECK_RAW_MIN_M 0xFFFF

/* NIC_RXE_WQE_ARCACHE */
#define NIC_RXE_WQE_ARCACHE_VAL_S 0
#define NIC_RXE_WQE_ARCACHE_VAL_M 0xF

/* NIC_RXE_WQE_ARUSER_ATTR */
#define NIC_RXE_WQE_ARUSER_ATTR_0_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_0_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_1_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_1_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_2_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_2_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_3_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_3_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_4_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_4_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_5_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_5_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_6_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_6_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_7_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_7_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_8_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_8_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_9_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_9_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_10_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_10_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_11_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_11_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_12_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_12_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_13_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_13_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_14_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_14_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_15_ASID_S 0
#define NIC_RXE_WQE_ARUSER_ATTR_15_ASID_M 0x3FF
#define NIC_RXE_WQE_ARUSER_ATTR_MMU_BP_S 10
#define NIC_RXE_WQE_ARUSER_ATTR_MMU_BP_M 0x400

/* NIC_RXE_ARPROT_HBW_UNSEC */
#define NIC_RXE_ARPROT_HBW_UNSEC_VAL_S 0
#define NIC_RXE_ARPROT_HBW_UNSEC_VAL_M 0x7

/* NIC_RXE_ARPROT_HBW_SEC */
#define NIC_RXE_ARPROT_HBW_SEC_VAL_S 0
#define NIC_RXE_ARPROT_HBW_SEC_VAL_M 0x7

/* NIC_RXE_ARPROT_HBW_PRIV */
#define NIC_RXE_ARPROT_HBW_PRIV_VAL_S 0
#define NIC_RXE_ARPROT_HBW_PRIV_VAL_M 0x7

/* NIC_RXE_AWPROT_LBW_UNSEC */
#define NIC_RXE_AWPROT_LBW_UNSEC_VAL_S 0
#define NIC_RXE_AWPROT_LBW_UNSEC_VAL_M 0x7

/* NIC_RXE_AWPROT_LBW_SEC */
#define NIC_RXE_AWPROT_LBW_SEC_VAL_S 0
#define NIC_RXE_AWPROT_LBW_SEC_VAL_M 0x7

/* NIC_RXE_AWPROT_LBW_PRIV */
#define NIC_RXE_AWPROT_LBW_PRIV_VAL_S 0
#define NIC_RXE_AWPROT_LBW_PRIV_VAL_M 0x7

/* NIC_RXE_AFA_LBW_ADDR_0 */
#define NIC_RXE_AFA_LBW_ADDR_0_VAL_S 0
#define NIC_RXE_AFA_LBW_ADDR_0_VAL_M 0x1FFFFFFF

/* NIC_RXE_AFA_LBW_ADDR_1 */
#define NIC_RXE_AFA_LBW_ADDR_1_VAL_S 0
#define NIC_RXE_AFA_LBW_ADDR_1_VAL_M 0x1FFFFFFF

/* NIC_RXE_AFA_MASK_SIZE */
#define NIC_RXE_AFA_MASK_SIZE_VAL_S 0
#define NIC_RXE_AFA_MASK_SIZE_VAL_M 0x3F

/* NIC_RXE_AFA_ARUSER_ATTR */
#define NIC_RXE_AFA_ARUSER_ATTR_0_ASID_S 0
#define NIC_RXE_AFA_ARUSER_ATTR_0_ASID_M 0x3FF
#define NIC_RXE_AFA_ARUSER_ATTR_1_ASID_S 0
#define NIC_RXE_AFA_ARUSER_ATTR_1_ASID_M 0x3FF
#define NIC_RXE_AFA_ARUSER_ATTR_2_ASID_S 0
#define NIC_RXE_AFA_ARUSER_ATTR_2_ASID_M 0x3FF
#define NIC_RXE_AFA_ARUSER_ATTR_3_ASID_S 0
#define NIC_RXE_AFA_ARUSER_ATTR_3_ASID_M 0x3FF
#define NIC_RXE_AFA_ARUSER_ATTR_MMU_BP_S 10
#define NIC_RXE_AFA_ARUSER_ATTR_MMU_BP_M 0x400

/* NIC_RXE_AFA_CACHE_ATTR */
#define NIC_RXE_AFA_CACHE_ATTR_MCID_15_7_S 0
#define NIC_RXE_AFA_CACHE_ATTR_MCID_15_7_M 0x1FF
#define NIC_RXE_AFA_CACHE_ATTR_ARCACHE_BIT0_S 9
#define NIC_RXE_AFA_CACHE_ATTR_ARCACHE_BIT0_M 0x200
#define NIC_RXE_AFA_CACHE_ATTR_ARCACHE_BIT1_S 10
#define NIC_RXE_AFA_CACHE_ATTR_ARCACHE_BIT1_M 0x400
#define NIC_RXE_AFA_CACHE_ATTR_ARCACHE_BIT3_S 11
#define NIC_RXE_AFA_CACHE_ATTR_ARCACHE_BIT3_M 0x800

/* NIC_RXE_CG */
#define NIC_RXE_CG_DISABLE_S 0
#define NIC_RXE_CG_DISABLE_M 0x1
#define NIC_RXE_CG_GATED_CLK_ACTIVE_S 1
#define NIC_RXE_CG_GATED_CLK_ACTIVE_M 0x2

/* NIC_RXE_CG_TIMER */
#define NIC_RXE_CG_TIMER_VAL_S 0
#define NIC_RXE_CG_TIMER_VAL_M 0xFFFFFFFF

/* NIC_RXE_WQE_WQ_WR_OP_DISABLE */
#define NIC_RXE_WQE_WQ_WR_OP_DISABLE_VAL_S 0
#define NIC_RXE_WQE_WQ_WR_OP_DISABLE_VAL_M 0xFFFFFFFF

/* NIC_RXE_WQE_WQ_RDV_OP_DISABLE */
#define NIC_RXE_WQE_WQ_RDV_OP_DISABLE_VAL_S 0
#define NIC_RXE_WQE_WQ_RDV_OP_DISABLE_VAL_M 0xFFFFFFFF

/* NIC_RXE_WQE_WQ_RD_OP_DISABLE */
#define NIC_RXE_WQE_WQ_RD_OP_DISABLE_VAL_S 0
#define NIC_RXE_WQE_WQ_RD_OP_DISABLE_VAL_M 0xFFFFFFFF

/* NIC_RXE_WQE_MAX_WRITE_SEND_SIZE */
#define NIC_RXE_WQE_MAX_WRITE_SEND_SIZE_VAL_S 0
#define NIC_RXE_WQE_MAX_WRITE_SEND_SIZE_VAL_M 0xFFFFFFFF

/* NIC_RXE_WQE_MAX_MULTI_STRIDE_SIZE */
#define NIC_RXE_WQE_MAX_MULTI_STRIDE_SIZE_VAL_S 0
#define NIC_RXE_WQE_MAX_MULTI_STRIDE_SIZE_VAL_M 0xFFFFFFFF

/* NIC_RXE_CACHE_CFG */
#define NIC_RXE_CACHE_CFG_STOP_S 0
#define NIC_RXE_CACHE_CFG_STOP_M 0x1
#define NIC_RXE_CACHE_CFG_FORCE_BYPASS_S 1
#define NIC_RXE_CACHE_CFG_FORCE_BYPASS_M 0x2
#define NIC_RXE_CACHE_CFG_INVALIDATION_S 2
#define NIC_RXE_CACHE_CFG_INVALIDATION_M 0x4
#define NIC_RXE_CACHE_CFG_RELEASE_INVALIDATE_S 3
#define NIC_RXE_CACHE_CFG_RELEASE_INVALIDATE_M 0x8
#define NIC_RXE_CACHE_CFG_INVALIDATE_WRITEBACK_S 4
#define NIC_RXE_CACHE_CFG_INVALIDATE_WRITEBACK_M 0x10
#define NIC_RXE_CACHE_CFG_LOCK_SLICE_DIS_S 5
#define NIC_RXE_CACHE_CFG_LOCK_SLICE_DIS_M 0x20
#define NIC_RXE_CACHE_CFG_PARTIAL_LINE_INV_EN_S 6
#define NIC_RXE_CACHE_CFG_PARTIAL_LINE_INV_EN_M 0x40

/* NIC_RXE_CACHE_INFO */
#define NIC_RXE_CACHE_INFO_INVALIDATION_DONE_S 0
#define NIC_RXE_CACHE_INFO_INVALIDATION_DONE_M 0x1
#define NIC_RXE_CACHE_INFO_IDLE_S 1
#define NIC_RXE_CACHE_INFO_IDLE_M 0x2

/* NIC_RXE_CACHE_ADDR_LO */
#define NIC_RXE_CACHE_ADDR_LO_VAL_S 8
#define NIC_RXE_CACHE_ADDR_LO_VAL_M 0xFFFFFF00

/* NIC_RXE_CACHE_ADDR_HI */
#define NIC_RXE_CACHE_ADDR_HI_VAL_S 0
#define NIC_RXE_CACHE_ADDR_HI_VAL_M 0xFFFFFFFF

/* NIC_RXE_CQ_CFG */
#define NIC_RXE_CQ_CFG_ENABLE_S 0
#define NIC_RXE_CQ_CFG_ENABLE_M 0x1
#define NIC_RXE_CQ_CFG_OVERRUN_EN_S 1
#define NIC_RXE_CQ_CFG_OVERRUN_EN_M 0x2
#define NIC_RXE_CQ_CFG_WINDOW_WRAPAROUND_EN_S 2
#define NIC_RXE_CQ_CFG_WINDOW_WRAPAROUND_EN_M 0x4
#define NIC_RXE_CQ_CFG_WRITE_PI_EN_S 3
#define NIC_RXE_CQ_CFG_WRITE_PI_EN_M 0x8
#define NIC_RXE_CQ_CFG_CMPL_EVENT_PER_CQE_S 4
#define NIC_RXE_CQ_CFG_CMPL_EVENT_PER_CQE_M 0x10
#define NIC_RXE_CQ_CFG_CMPL_EVENT_FIRST_CQE_S 5
#define NIC_RXE_CQ_CFG_CMPL_EVENT_FIRST_CQE_M 0x20
#define NIC_RXE_CQ_CFG_CMPL_EVENT_CI_UPDATED_S 6
#define NIC_RXE_CQ_CFG_CMPL_EVENT_CI_UPDATED_M 0x40
#define NIC_RXE_CQ_CFG_EQ_ID_S 8
#define NIC_RXE_CQ_CFG_EQ_ID_M 0x300

/* NIC_RXE_CQ_WRITE_INDEX */
#define NIC_RXE_CQ_WRITE_INDEX_R_S 0
#define NIC_RXE_CQ_WRITE_INDEX_R_M 0xFFFFFFFF

/* NIC_RXE_CQ_PRODUCER_INDEX */
#define NIC_RXE_CQ_PRODUCER_INDEX_R_S 0
#define NIC_RXE_CQ_PRODUCER_INDEX_R_M 0xFFFFFFFF

/* NIC_RXE_CQ_CONSUMER_INDEX */
#define NIC_RXE_CQ_CONSUMER_INDEX_R_S 0
#define NIC_RXE_CQ_CONSUMER_INDEX_R_M 0xFFFFFFFF

/* NIC_RXE_CQ_BASE_ADDR_LO */
#define NIC_RXE_CQ_BASE_ADDR_LO_R_S 0
#define NIC_RXE_CQ_BASE_ADDR_LO_R_M 0xFFFFFFFF

/* NIC_RXE_CQ_BASE_ADDR_HI */
#define NIC_RXE_CQ_BASE_ADDR_HI_R_S 0
#define NIC_RXE_CQ_BASE_ADDR_HI_R_M 0xFFFFFFFF

/* NIC_RXE_CQ_PI_ADDR_LO */
#define NIC_RXE_CQ_PI_ADDR_LO_R_S 0
#define NIC_RXE_CQ_PI_ADDR_LO_R_M 0xFFFFFFFF

/* NIC_RXE_CQ_PI_ADDR_HI */
#define NIC_RXE_CQ_PI_ADDR_HI_R_S 0
#define NIC_RXE_CQ_PI_ADDR_HI_R_M 0xFFFFFFFF

/* NIC_RXE_CQ_LOG_SIZE */
#define NIC_RXE_CQ_LOG_SIZE_R_S 0
#define NIC_RXE_CQ_LOG_SIZE_R_M 0xFFFFFFFF

/* NIC_RXE_CQ_AXI_USER */
#define NIC_RXE_CQ_AXI_USER_0_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_0_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_1_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_1_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_2_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_2_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_3_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_3_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_4_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_4_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_5_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_5_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_6_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_6_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_7_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_7_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_8_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_8_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_9_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_9_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_10_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_10_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_11_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_11_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_12_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_12_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_13_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_13_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_14_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_14_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_15_ASID_S 0
#define NIC_RXE_CQ_AXI_USER_15_ASID_M 0x3FF
#define NIC_RXE_CQ_AXI_USER_MMU_BP_S 10
#define NIC_RXE_CQ_AXI_USER_MMU_BP_M 0x400

/* NIC_RXE_CQ_AXI_PROT0 */
#define NIC_RXE_CQ_AXI_PROT0_VAL_S 0
#define NIC_RXE_CQ_AXI_PROT0_VAL_M 0x1

/* NIC_RXE_CQ_AXI_PROT1 */
#define NIC_RXE_CQ_AXI_PROT1_VAL_S 0
#define NIC_RXE_CQ_AXI_PROT1_VAL_M 0x1

/* NIC_RXE_CQ_AXI_PROT2 */
#define NIC_RXE_CQ_AXI_PROT2_VAL_S 0
#define NIC_RXE_CQ_AXI_PROT2_VAL_M 0x1

/* NIC_RXE_CQ_AWCACHE */
#define NIC_RXE_CQ_AWCACHE_VAL_S 0
#define NIC_RXE_CQ_AWCACHE_VAL_M 0xF

/* NIC_RXE_CQ_ARM_TIMEOUT_EN */
#define NIC_RXE_CQ_ARM_TIMEOUT_EN_EN_S 0
#define NIC_RXE_CQ_ARM_TIMEOUT_EN_EN_M 0xFFFF

/* NIC_RXE_CQ_ARM_TIMEOUT */
#define NIC_RXE_CQ_ARM_TIMEOUT_VAL_S 0
#define NIC_RXE_CQ_ARM_TIMEOUT_VAL_M 0xFFFFFFFF

/* NIC_RXE_CQ_UMR_BASE_ADDR */
#define NIC_RXE_CQ_UMR_BASE_ADDR_R_S 0
#define NIC_RXE_CQ_UMR_BASE_ADDR_R_M 0x7FFFF

/* NIC_RXE_QPC_LIMIT_CFG */
#define NIC_RXE_QPC_LIMIT_CFG_CRDT_REQ_THRESHOLD_S 0
#define NIC_RXE_QPC_LIMIT_CFG_CRDT_REQ_THRESHOLD_M 0xFF
#define NIC_RXE_QPC_LIMIT_CFG_CRDT_RES_THRESHOLD_S 8
#define NIC_RXE_QPC_LIMIT_CFG_CRDT_RES_THRESHOLD_M 0xFF00
#define NIC_RXE_QPC_LIMIT_CFG_CRDT_REQ_EN_S 16
#define NIC_RXE_QPC_LIMIT_CFG_CRDT_REQ_EN_M 0x10000
#define NIC_RXE_QPC_LIMIT_CFG_CRDT_RES_EN_S 17
#define NIC_RXE_QPC_LIMIT_CFG_CRDT_RES_EN_M 0x20000

/* NIC_RXE_SOB_SM_BASE_ADDR */
#define NIC_RXE_SOB_SM_BASE_ADDR_VAL_S 0
#define NIC_RXE_SOB_SM_BASE_ADDR_VAL_M 0x1FFFFFFF

/* NIC_RXE_SOB_SUB_SM_OFFSET */
#define NIC_RXE_SOB_SUB_SM_OFFSET_VAL_S 0
#define NIC_RXE_SOB_SUB_SM_OFFSET_VAL_M 0x1FFFFFFF

/* NIC_RXE_SOB_MESSAGE */
#define NIC_RXE_SOB_MESSAGE_REQ_S 0
#define NIC_RXE_SOB_MESSAGE_REQ_M 0x3F
#define NIC_RXE_SOB_MESSAGE_RES_S 8
#define NIC_RXE_SOB_MESSAGE_RES_M 0x3F00

/* NIC_RXE_LBW_BASE_LO */
#define NIC_RXE_LBW_BASE_LO_LBW_BASE_ADDR_LO_S 0
#define NIC_RXE_LBW_BASE_LO_LBW_BASE_ADDR_LO_M 0xFFFFFFFF

/* NIC_RXE_LBW_BASE_HI */
#define NIC_RXE_LBW_BASE_HI_LBW_BASE_ADDR_HI_S 0
#define NIC_RXE_LBW_BASE_HI_LBW_BASE_ADDR_HI_M 0xFFFFFFFF

/* NIC_RXE_LBW_LOG_SIZE */
#define NIC_RXE_LBW_LOG_SIZE_LBW_LOG_SIZE_S 0
#define NIC_RXE_LBW_LOG_SIZE_LBW_LOG_SIZE_M 0x3F

/* NIC_RXE_RAW_BASE_LO_P0 */
#define NIC_RXE_RAW_BASE_LO_P0_RAW_BASE_ADDR_LO_P0_S 0
#define NIC_RXE_RAW_BASE_LO_P0_RAW_BASE_ADDR_LO_P0_M 0xFFFFFFFF

/* NIC_RXE_RAW_BASE_HI_P0 */
#define NIC_RXE_RAW_BASE_HI_P0_RAW_BASE_ADDR_HI_P0_S 0
#define NIC_RXE_RAW_BASE_HI_P0_RAW_BASE_ADDR_HI_P0_M 0xFFFFFFFF

/* NIC_RXE_RAW_MISC_P0 */
#define NIC_RXE_RAW_MISC_P0_LOG_RAW_ENTRY_SIZE_P0_S 0
#define NIC_RXE_RAW_MISC_P0_LOG_RAW_ENTRY_SIZE_P0_M 0xF
#define NIC_RXE_RAW_MISC_P0_RAW_REDUC_OP_P0_S 5
#define NIC_RXE_RAW_MISC_P0_RAW_REDUC_OP_P0_M 0x7FE0
#define NIC_RXE_RAW_MISC_P0_LOG_BUFFER_SIZE_MASK_P0_S 15
#define NIC_RXE_RAW_MISC_P0_LOG_BUFFER_SIZE_MASK_P0_M 0xF8000

/* NIC_RXE_RAW_BASE_LO_P1 */
#define NIC_RXE_RAW_BASE_LO_P1_RAW_BASE_ADDR_LO_P1_S 0
#define NIC_RXE_RAW_BASE_LO_P1_RAW_BASE_ADDR_LO_P1_M 0xFFFFFFFF

/* NIC_RXE_RAW_BASE_HI_P1 */
#define NIC_RXE_RAW_BASE_HI_P1_RAW_BASE_ADDR_HI_P1_S 0
#define NIC_RXE_RAW_BASE_HI_P1_RAW_BASE_ADDR_HI_P1_M 0xFFFFFFFF

/* NIC_RXE_RAW_MISC_P1 */
#define NIC_RXE_RAW_MISC_P1_LOG_RAW_ENTRY_SIZE_P1_S 0
#define NIC_RXE_RAW_MISC_P1_LOG_RAW_ENTRY_SIZE_P1_M 0xF
#define NIC_RXE_RAW_MISC_P1_RAW_REDUC_OP_P1_S 5
#define NIC_RXE_RAW_MISC_P1_RAW_REDUC_OP_P1_M 0x7FE0
#define NIC_RXE_RAW_MISC_P1_LOG_BUFFER_SIZE_MASK_P1_S 15
#define NIC_RXE_RAW_MISC_P1_LOG_BUFFER_SIZE_MASK_P1_M 0xF8000

/* NIC_RXE_RAW_BASE_LO_P2 */
#define NIC_RXE_RAW_BASE_LO_P2_RAW_BASE_ADDR_LO_P2_S 0
#define NIC_RXE_RAW_BASE_LO_P2_RAW_BASE_ADDR_LO_P2_M 0xFFFFFFFF

/* NIC_RXE_RAW_BASE_HI_P2 */
#define NIC_RXE_RAW_BASE_HI_P2_RAW_BASE_ADDR_HI_P2_S 0
#define NIC_RXE_RAW_BASE_HI_P2_RAW_BASE_ADDR_HI_P2_M 0xFFFFFFFF

/* NIC_RXE_RAW_MISC_P2 */
#define NIC_RXE_RAW_MISC_P2_LOG_RAW_ENTRY_SIZE_P2_S 0
#define NIC_RXE_RAW_MISC_P2_LOG_RAW_ENTRY_SIZE_P2_M 0xF
#define NIC_RXE_RAW_MISC_P2_RAW_REDUC_OP_P2_S 5
#define NIC_RXE_RAW_MISC_P2_RAW_REDUC_OP_P2_M 0x7FE0
#define NIC_RXE_RAW_MISC_P2_LOG_BUFFER_SIZE_MASK_P2_S 15
#define NIC_RXE_RAW_MISC_P2_LOG_BUFFER_SIZE_MASK_P2_M 0xF8000

/* NIC_RXE_RAW_BASE_LO_P3 */
#define NIC_RXE_RAW_BASE_LO_P3_RAW_BASE_ADDR_LO_P3_S 0
#define NIC_RXE_RAW_BASE_LO_P3_RAW_BASE_ADDR_LO_P3_M 0xFFFFFFFF

/* NIC_RXE_RAW_BASE_HI_P3 */
#define NIC_RXE_RAW_BASE_HI_P3_RAW_BASE_ADDR_HI_P3_S 0
#define NIC_RXE_RAW_BASE_HI_P3_RAW_BASE_ADDR_HI_P3_M 0xFFFFFFFF

/* NIC_RXE_RAW_MISC_P3 */
#define NIC_RXE_RAW_MISC_P3_LOG_RAW_ENTRY_SIZE_P3_S 0
#define NIC_RXE_RAW_MISC_P3_LOG_RAW_ENTRY_SIZE_P3_M 0xF
#define NIC_RXE_RAW_MISC_P3_RAW_REDUC_OP_P3_S 5
#define NIC_RXE_RAW_MISC_P3_RAW_REDUC_OP_P3_M 0x7FE0
#define NIC_RXE_RAW_MISC_P3_LOG_BUFFER_SIZE_MASK_P3_S 15
#define NIC_RXE_RAW_MISC_P3_LOG_BUFFER_SIZE_MASK_P3_M 0xF8000

/* NIC_RXE_WIN_WQ_BASE_LO */
#define NIC_RXE_WIN_WQ_BASE_LO_WQ_BASE_ADDR_LO_S 0
#define NIC_RXE_WIN_WQ_BASE_LO_WQ_BASE_ADDR_LO_M 0xFFFFFFFF

/* NIC_RXE_WIN_WQ_BASE_HI */
#define NIC_RXE_WIN_WQ_BASE_HI_WQ_BASE_ADDR_HI_S 0
#define NIC_RXE_WIN_WQ_BASE_HI_WQ_BASE_ADDR_HI_M 0xFFFFFFFF

/* NIC_RXE_WIN_WQ_MISC */
#define NIC_RXE_WIN_WQ_MISC_LOG_MAX_WQ_SIZE_S 0
#define NIC_RXE_WIN_WQ_MISC_LOG_MAX_WQ_SIZE_M 0x1F

/* NIC_RXE_RDV_TX_WQ_BASE_ADDR_LO */
#define NIC_RXE_RDV_TX_WQ_BASE_ADDR_LO_VAL_S 0
#define NIC_RXE_RDV_TX_WQ_BASE_ADDR_LO_VAL_M 0xFFFFFFFF

/* NIC_RXE_RDV_TX_WQ_BASE_ADDR_HI */
#define NIC_RXE_RDV_TX_WQ_BASE_ADDR_HI_VAL_S 0
#define NIC_RXE_RDV_TX_WQ_BASE_ADDR_HI_VAL_M 0xFFFFFFFF

/* NIC_RXE_RDV_TX_WQ_LOG_MAX_SIZE */
#define NIC_RXE_RDV_TX_WQ_LOG_MAX_SIZE_VAL_S 0
#define NIC_RXE_RDV_TX_WQ_LOG_MAX_SIZE_VAL_M 0x1F

/* NIC_RXE_SEI_INTR_CAUSE */
#define NIC_RXE_SEI_INTR_CAUSE_HBW_RRESP_ERR_WQE_S 0
#define NIC_RXE_SEI_INTR_CAUSE_HBW_RRESP_ERR_WQE_M 0x1
#define NIC_RXE_SEI_INTR_CAUSE_HBW_RRESP_ERR_FNA_S 1
#define NIC_RXE_SEI_INTR_CAUSE_HBW_RRESP_ERR_FNA_M 0x2
#define NIC_RXE_SEI_INTR_CAUSE_LBW_BRESP_ERR_S 2
#define NIC_RXE_SEI_INTR_CAUSE_LBW_BRESP_ERR_M 0x4
#define NIC_RXE_SEI_INTR_CAUSE_HBW_BRESP_ERR_S 3
#define NIC_RXE_SEI_INTR_CAUSE_HBW_BRESP_ERR_M 0x8

/* NIC_RXE_SEI_INTR_MASK */
#define NIC_RXE_SEI_INTR_MASK_HBW_RRESP_ERR_WQE_S 0
#define NIC_RXE_SEI_INTR_MASK_HBW_RRESP_ERR_WQE_M 0x1
#define NIC_RXE_SEI_INTR_MASK_HBW_RRESP_ERR_FNA_S 1
#define NIC_RXE_SEI_INTR_MASK_HBW_RRESP_ERR_FNA_M 0x2
#define NIC_RXE_SEI_INTR_MASK_LBW_BRESP_ERR_S 2
#define NIC_RXE_SEI_INTR_MASK_LBW_BRESP_ERR_M 0x4
#define NIC_RXE_SEI_INTR_MASK_HBW_BRESP_ERR_S 3
#define NIC_RXE_SEI_INTR_MASK_HBW_BRESP_ERR_M 0x8

/* NIC_RXE_SEI_INTR_CLEAR */
#define NIC_RXE_SEI_INTR_CLEAR_HBW_RRESP_ERR_WQE_S 0
#define NIC_RXE_SEI_INTR_CLEAR_HBW_RRESP_ERR_WQE_M 0x1
#define NIC_RXE_SEI_INTR_CLEAR_HBW_RRESP_ERR_FNA_S 1
#define NIC_RXE_SEI_INTR_CLEAR_HBW_RRESP_ERR_FNA_M 0x2
#define NIC_RXE_SEI_INTR_CLEAR_LBW_BRESP_ERR_S 2
#define NIC_RXE_SEI_INTR_CLEAR_LBW_BRESP_ERR_M 0x4
#define NIC_RXE_SEI_INTR_CLEAR_HBW_BRESP_ERR_S 3
#define NIC_RXE_SEI_INTR_CLEAR_HBW_BRESP_ERR_M 0x8

/* NIC_RXE_SPI_INTR_CAUSE */
#define NIC_RXE_SPI_INTR_CAUSE_VAL_S 0
#define NIC_RXE_SPI_INTR_CAUSE_VAL_M 0xFFFFFFFF

/* NIC_RXE_SPI_INTR_MASK */
#define NIC_RXE_SPI_INTR_MASK_VAL_S 0
#define NIC_RXE_SPI_INTR_MASK_VAL_M 0xFFFFFFFF

/* NIC_RXE_SPI_INTR_CLEAR */
#define NIC_RXE_SPI_INTR_CLEAR_VAL_S 0
#define NIC_RXE_SPI_INTR_CLEAR_VAL_M 0xFFFFFFFF

/* NIC_RXE_DBG_SPMU_SELECT */
#define NIC_RXE_DBG_SPMU_SELECT_VAL_S 0
#define NIC_RXE_DBG_SPMU_SELECT_VAL_M 0x3

/* NIC_RXE_DBG_INV_OP_0 */
#define NIC_RXE_DBG_INV_OP_0_DBG_INV_OP_PSN_S 0
#define NIC_RXE_DBG_INV_OP_0_DBG_INV_OP_PSN_M 0xFFFFFF
#define NIC_RXE_DBG_INV_OP_0_DBG_INV_OP_LATCHED_S 31
#define NIC_RXE_DBG_INV_OP_0_DBG_INV_OP_LATCHED_M 0x80000000

/* NIC_RXE_DBG_INV_OP_1 */
#define NIC_RXE_DBG_INV_OP_1_DBG_INV_OP_QPN_S 0
#define NIC_RXE_DBG_INV_OP_1_DBG_INV_OP_QPN_M 0xFFFFFF
#define NIC_RXE_DBG_INV_OP_1_DBG_INV_OP_OPCODE_S 24
#define NIC_RXE_DBG_INV_OP_1_DBG_INV_OP_OPCODE_M 0xFF000000

/* NIC_RXE_DBG_EN */
#define NIC_RXE_DBG_EN_VAL_S 0
#define NIC_RXE_DBG_EN_VAL_M 0x1

/* NIC_RXE_DBG_CQ_ARM_ON */
#define NIC_RXE_DBG_CQ_ARM_ON_STATE_S 0
#define NIC_RXE_DBG_CQ_ARM_ON_STATE_M 0xFFFF

/* NIC_RXE_DBG_SLICE_MAIN */
#define NIC_RXE_DBG_SLICE_MAIN_PQ_OCCUPANCY_S 0
#define NIC_RXE_DBG_SLICE_MAIN_PQ_OCCUPANCY_M 0x7F
#define NIC_RXE_DBG_SLICE_MAIN_MAIN_OCCUPANCY_S 8
#define NIC_RXE_DBG_SLICE_MAIN_MAIN_OCCUPANCY_M 0x7F00

/* NIC_RXE_DBG_SLICE_SCT */
#define NIC_RXE_DBG_SLICE_SCT_SQ_OCCUPANCY_S 0
#define NIC_RXE_DBG_SLICE_SCT_SQ_OCCUPANCY_M 0x3F

/* NIC_RXE_DBG_SLICE_WQE */
#define NIC_RXE_DBG_SLICE_WQE_WP_OCCUPANCY_S 0
#define NIC_RXE_DBG_SLICE_WQE_WP_OCCUPANCY_M 0x1F

/* NIC_RXE_DBG_AXI_FNA_ERR */
#define NIC_RXE_DBG_AXI_FNA_ERR_HBW_RRESP_ERR_FNA_LATCHED_S 0
#define NIC_RXE_DBG_AXI_FNA_ERR_HBW_RRESP_ERR_FNA_LATCHED_M 0xFFFFFFFF

/* NIC_RXE_DBG_AXI_WQE_ERR */
#define NIC_RXE_DBG_AXI_WQE_ERR_HBW_RRESP_ERR_WQE_LATCHED_S 0
#define NIC_RXE_DBG_AXI_WQE_ERR_HBW_RRESP_ERR_WQE_LATCHED_M 0x1

/* NIC_RXE_DBG_AXI_CQE_ERR */
#define NIC_RXE_DBG_AXI_CQE_ERR_DBG_HBW_BRESP_ERR_LATCHED_S 0
#define NIC_RXE_DBG_AXI_CQE_ERR_DBG_HBW_BRESP_ERR_LATCHED_M 0xFFFF

/* NIC_RXE_DBG_AXI_LBW_WQE_ERR */
#define NIC_RXE_DBG_AXI_LBW_WQE_ERR_DBG_LBW_BRESP_ERR_LATCHED_S 0
#define NIC_RXE_DBG_AXI_LBW_WQE_ERR_DBG_LBW_BRESP_ERR_LATCHED_M 0xFFFF

/* NIC_RXE_DBG_AXI_LBW_SCT_ERR */
#define NIC_RXE_DBG_AXI_LBW_SCT_ERR_DBG_LBW_BRESP_ERR_LATCHED_S 0
#define NIC_RXE_DBG_AXI_LBW_SCT_ERR_DBG_LBW_BRESP_ERR_LATCHED_M 0xFFFFFFFF

/* NIC_RXE_DBG_QPC_CRDT */
#define NIC_RXE_DBG_QPC_CRDT_CRDT_RESET_S 0
#define NIC_RXE_DBG_QPC_CRDT_CRDT_RESET_M 0x1
#define NIC_RXE_DBG_QPC_CRDT_CRDT_LEVEL_REQ_S 1
#define NIC_RXE_DBG_QPC_CRDT_CRDT_LEVEL_REQ_M 0xFE
#define NIC_RXE_DBG_QPC_CRDT_CRDT_LEVEL_RES_S 8
#define NIC_RXE_DBG_QPC_CRDT_CRDT_LEVEL_RES_M 0x7F00

/* NIC_RXE_DBG_RD_MEM_CRDT */
#define NIC_RXE_DBG_RD_MEM_CRDT_CRDT_RESET_S 0
#define NIC_RXE_DBG_RD_MEM_CRDT_CRDT_RESET_M 0x1
#define NIC_RXE_DBG_RD_MEM_CRDT_CRDT_LEVEL_WQE_S 1
#define NIC_RXE_DBG_RD_MEM_CRDT_CRDT_LEVEL_WQE_M 0xE
#define NIC_RXE_DBG_RD_MEM_CRDT_CRDT_LEVEL_SCT_S 4
#define NIC_RXE_DBG_RD_MEM_CRDT_CRDT_LEVEL_SCT_M 0x70
#define NIC_RXE_DBG_RD_MEM_CRDT_CRDT_LEVEL_CYC_IDX_S 7
#define NIC_RXE_DBG_RD_MEM_CRDT_CRDT_LEVEL_CYC_IDX_M 0x380

#endif /* ASIC_REG_NIC_RXE_MASKS_H_ */
