/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC_MAC_GLOB_STAT_TX0_REGS_H_
#define ASIC_REG_NIC_MAC_GLOB_STAT_TX0_REGS_H_

/*
 *****************************************
 *   NIC_MAC_GLOB_STAT_TX0
 *   (Prototype: MAC_MAC0_TX_CNT)
 *****************************************
 */

#define mmNIC_MAC_GLOB_STAT_TX0_ETHERSTATSOCTETS_4 0x0

#define mmNIC_MAC_GLOB_STAT_TX0_OCTETSTRANSMITTEDOK 0x4

#define mmNIC_MAC_GLOB_STAT_TX0_APAUSEMACCTRLFRAMESTRANSMITTED 0x8

#define mmNIC_MAC_GLOB_STAT_TX0_AFRAMESTRANSMITTEDOK 0xC

#define mmNIC_MAC_GLOB_STAT_TX0_VLANTRANSMITTEDOK 0x10

#define mmNIC_MAC_GLOB_STAT_TX0_IFOUTERRORS 0x14

#define mmNIC_MAC_GLOB_STAT_TX0_IFOUTUCASTPKTS 0x18

#define mmNIC_MAC_GLOB_STAT_TX0_IFOUTMULTICASTPKTS 0x1C

#define mmNIC_MAC_GLOB_STAT_TX0_IFOUTBROADCASTPKTS 0x20

#define mmNIC_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS64OCTETS_4 0x24

#define mmNIC_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS65TO127OCTETS_4 0x28

#define mmNIC_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS128TO255OCTETS_4 0x2C

#define mmNIC_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS256TO511OCTETS_4 0x30

#define mmNIC_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS512TO1023OCTETS_4 0x34

#define mmNIC_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS1024TO1518OCTETS_4 0x38

#define mmNIC_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS1519TOMAXOCTETS_4 0x3C

#define mmNIC_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED0 0x40

#define mmNIC_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED1 0x44

#define mmNIC_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED2 0x48

#define mmNIC_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED3 0x4C

#define mmNIC_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED4 0x50

#define mmNIC_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED5 0x54

#define mmNIC_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED6 0x58

#define mmNIC_MAC_GLOB_STAT_TX0_ACBFCPAUSEFRAMESTRANSMITTED7 0x5C

#define mmNIC_MAC_GLOB_STAT_TX0_AMACCONTROLFRAMESTRANSMITTED 0x60

#define mmNIC_MAC_GLOB_STAT_TX0_ETHERSTATSPKTS_4 0x64

#endif /* ASIC_REG_NIC_MAC_GLOB_STAT_TX0_REGS_H_ */
