/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC_MAC_GLOB_STAT_RSFEC_STATS_REGS_H_
#define ASIC_REG_NIC_MAC_GLOB_STAT_RSFEC_STATS_REGS_H_

/*
 *****************************************
 *   NIC_MAC_GLOB_STAT_RSFEC_STATS
 *   (Prototype: NIC_MAC_RSF_STAT)
 *****************************************
 */

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_DATA_HI 0x0

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_STATN_STATUS 0x4

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_STATN_CONFIG 0x8

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_STATN_CONTROL 0xC

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_STATN_CLEARVALUE_LO 0x10

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_STATN_CLEARVALUE_HI 0x14

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_DATA_HI_2 0x1C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CW 0x20

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CORRECT_CW 0x24

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CORRECTED_CW 0x28

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_UNCORRECTED_CW 0x2C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_1_SYMB_ERR 0x30

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_2_SYMB_ERR 0x34

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_3_SYMB_ERR 0x38

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_4_SYMB_ERR 0x3C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_5_SYMB_ERR 0x40

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_6_SYMB_ERR 0x44

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_7_SYMB_ERR 0x48

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_8_SYMB_ERR 0x4C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_9_SYMB_ERR 0x50

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_10_SYMB_ERR 0x54

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_11_SYMB_ERR 0x58

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_12_SYMB_ERR 0x5C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_13_SYMB_ERR 0x60

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_14_SYMB_ERR 0x64

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_15_SYMB_ERR 0x68

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_SYM_ERR_TOTAL 0x6C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CW_1 0x70

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CORRECT_CW_1 0x74

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CORRECTED_CW_1 0x78

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_UNCORRECTED_CW_1 0x7C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_1_SYMB_ERR_1 0x80

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_2_SYMB_ERR_1 0x84

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_3_SYMB_ERR_1 0x88

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_4_SYMB_ERR_1 0x8C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_5_SYMB_ERR_1 0x90

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_6_SYMB_ERR_1 0x94

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_7_SYMB_ERR_1 0x98

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_8_SYMB_ERR_1 0x9C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_9_SYMB_ERR_1 0xA0

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_10_SYMB_ERR_1 0xA4

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_11_SYMB_ERR_1 0xA8

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_12_SYMB_ERR_1 0xAC

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_13_SYMB_ERR_1 0xB0

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_14_SYMB_ERR_1 0xB4

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_15_SYMB_ERR_1 0xB8

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_SYM_ERR_TOTAL_1 0xBC

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CW_2 0xC0

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CORRECT_CW_2 0xC4

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CORRECTED_CW_2 0xC8

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_UNCORRECTED_CW_2 0xCC

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_1_SYMB_ERR_2 0xD0

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_2_SYMB_ERR_2 0xD4

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_3_SYMB_ERR_2 0xD8

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_4_SYMB_ERR_2 0xDC

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_5_SYMB_ERR_2 0xE0

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_6_SYMB_ERR_2 0xE4

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_7_SYMB_ERR_2 0xE8

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_8_SYMB_ERR_2 0xEC

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_9_SYMB_ERR_2 0xF0

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_10_SYMB_ERR_2 0xF4

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_11_SYMB_ERR_2 0xF8

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_12_SYMB_ERR_2 0xFC

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_13_SYMB_ERR_2 0x100

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_14_SYMB_ERR_2 0x104

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_15_SYMB_ERR_2 0x108

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_SYM_ERR_TOTAL_2 0x10C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CW_3 0x110

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CORRECT_CW_3 0x114

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CORRECTED_CW_3 0x118

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_UNCORRECTED_CW_3 0x11C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_1_SYMB_ERR_3 0x120

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_2_SYMB_ERR_3 0x124

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_3_SYMB_ERR_3 0x128

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_4_SYMB_ERR_3 0x12C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_5_SYMB_ERR_3 0x130

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_6_SYMB_ERR_3 0x134

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_7_SYMB_ERR_3 0x138

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_8_SYMB_ERR_3 0x13C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_9_SYMB_ERR_3 0x140

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_10_SYMB_ERR_3 0x144

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_11_SYMB_ERR_3 0x148

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_12_SYMB_ERR_3 0x14C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_13_SYMB_ERR_3 0x150

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_14_SYMB_ERR_3 0x154

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_15_SYMB_ERR_3 0x158

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_SYM_ERR_TOTAL_3 0x15C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CW_4 0x160

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CORRECT_CW_4 0x164

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_CORRECTED_CW_4 0x168

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_TOTAL_UNCORRECTED_CW_4 0x16C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_1_SYMB_ERR_4 0x170

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_2_SYMB_ERR_4 0x174

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_3_SYMB_ERR_4 0x178

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_4_SYMB_ERR_4 0x17C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_5_SYMB_ERR_4 0x180

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_6_SYMB_ERR_4 0x184

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_7_SYMB_ERR_4 0x188

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_8_SYMB_ERR_4 0x18C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_9_SYMB_ERR_4 0x190

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_10_SYMB_ERR_4 0x194

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_11_SYMB_ERR_4 0x198

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_12_SYMB_ERR_4 0x19C

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_13_SYMB_ERR_4 0x1A0

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_14_SYMB_ERR_4 0x1A4

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_CW_CORRECTED_15_SYMB_ERR_4 0x1A8

#define mmNIC_MAC_GLOB_STAT_RSFEC_STATS_SYM_ERR_TOTAL_4 0x1AC

#endif /* ASIC_REG_NIC_MAC_GLOB_STAT_RSFEC_STATS_REGS_H_ */
