/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC_TXE_MASKS_H_
#define ASIC_REG_NIC_TXE_MASKS_H_

/*
 *****************************************
 *   NIC_TXE
 *   (Prototype: NIC_TXE)
 *****************************************
 */

/* NIC_TXE_WQE_FETCH_REQ_MASK_REG0 */
#define NIC_TXE_WQE_FETCH_REQ_MASK_REG0_R_S 0
#define NIC_TXE_WQE_FETCH_REQ_MASK_REG0_R_M 0xFFFFFFFF

/* NIC_TXE_WQE_FETCH_REQ_MASK_REG1 */
#define NIC_TXE_WQE_FETCH_REQ_MASK_REG1_R_S 0
#define NIC_TXE_WQE_FETCH_REQ_MASK_REG1_R_M 0xFFFFFFFF

/* NIC_TXE_WQE_FETCH_OCCUP_INFO */
#define NIC_TXE_WQE_FETCH_OCCUP_INFO_TOT_LINES_S 0
#define NIC_TXE_WQE_FETCH_OCCUP_INFO_TOT_LINES_M 0x7F
#define NIC_TXE_WQE_FETCH_OCCUP_INFO_ACT_SLICES_S 7
#define NIC_TXE_WQE_FETCH_OCCUP_INFO_ACT_SLICES_M 0x1F80

/* NIC_TXE_ALLOC_CREDIT */
#define NIC_TXE_ALLOC_CREDIT_TOTAL_S 0
#define NIC_TXE_ALLOC_CREDIT_TOTAL_M 0xFF
#define NIC_TXE_ALLOC_CREDIT_PAYLOAD_S 8
#define NIC_TXE_ALLOC_CREDIT_PAYLOAD_M 0xFF00

/* NIC_TXE_ALLOC_CREDIT_FORCE_FULL */
#define NIC_TXE_ALLOC_CREDIT_FORCE_FULL_TOTAL_S 0
#define NIC_TXE_ALLOC_CREDIT_FORCE_FULL_TOTAL_M 0x1
#define NIC_TXE_ALLOC_CREDIT_FORCE_FULL_PAYLOAD_S 1
#define NIC_TXE_ALLOC_CREDIT_FORCE_FULL_PAYLOAD_M 0x2

/* NIC_TXE_READ_CREDIT */
#define NIC_TXE_READ_CREDIT_R_S 0
#define NIC_TXE_READ_CREDIT_R_M 0x7FF

/* NIC_TXE_READ_CREDIT_FORCE_FULL */
#define NIC_TXE_READ_CREDIT_FORCE_FULL_R_S 0
#define NIC_TXE_READ_CREDIT_FORCE_FULL_R_M 0x1

/* NIC_TXE_BURST_ENABLE */
#define NIC_TXE_BURST_ENABLE_R_S 0
#define NIC_TXE_BURST_ENABLE_R_M 0x1

/* NIC_TXE_MEM_INIT */
#define NIC_TXE_MEM_INIT_R_S 0
#define NIC_TXE_MEM_INIT_R_M 0xFFFFFFFF

/* NIC_TXE_WR_INIT_BUSY */
#define NIC_TXE_WR_INIT_BUSY_R_S 0
#define NIC_TXE_WR_INIT_BUSY_R_M 0x1F

/* NIC_TXE_READ_RES_WT_INIT_BUSY */
#define NIC_TXE_READ_RES_WT_INIT_BUSY_R_S 0
#define NIC_TXE_READ_RES_WT_INIT_BUSY_R_M 0x1

/* NIC_TXE_BTH_TVER */
#define NIC_TXE_BTH_TVER_GAUDI1_S 0
#define NIC_TXE_BTH_TVER_GAUDI1_M 0xF
#define NIC_TXE_BTH_TVER_GAUDI2_S 4
#define NIC_TXE_BTH_TVER_GAUDI2_M 0xF0
#define NIC_TXE_BTH_TVER_GAUDI3_S 8
#define NIC_TXE_BTH_TVER_GAUDI3_M 0xF00
#define NIC_TXE_BTH_TVER_PLAIN_S 12
#define NIC_TXE_BTH_TVER_PLAIN_M 0xF000

/* NIC_TXE_IPV4_IDENTIFICATION */
#define NIC_TXE_IPV4_IDENTIFICATION_R_S 0
#define NIC_TXE_IPV4_IDENTIFICATION_R_M 0xFFFF

/* NIC_TXE_IPV4_FLAGS */
#define NIC_TXE_IPV4_FLAGS_R_S 0
#define NIC_TXE_IPV4_FLAGS_R_M 0x7

/* NIC_TXE_PAD */
#define NIC_TXE_PAD_ENABLE_S 0
#define NIC_TXE_PAD_ENABLE_M 0x1
#define NIC_TXE_PAD_RAW_QP_ENABLE_S 1
#define NIC_TXE_PAD_RAW_QP_ENABLE_M 0x2

/* NIC_TXE_ADD_PAD_TO_IPV4_LEN */
#define NIC_TXE_ADD_PAD_TO_IPV4_LEN_R_S 0
#define NIC_TXE_ADD_PAD_TO_IPV4_LEN_R_M 0x1

/* NIC_TXE_ADD_PAD_TO_UDP_LEN */
#define NIC_TXE_ADD_PAD_TO_UDP_LEN_R_S 0
#define NIC_TXE_ADD_PAD_TO_UDP_LEN_R_M 0x1

/* NIC_TXE_ICRC_EN */
#define NIC_TXE_ICRC_EN_R_S 0
#define NIC_TXE_ICRC_EN_R_M 0x1

/* NIC_TXE_UDP_MASK_S_PORT */
#define NIC_TXE_UDP_MASK_S_PORT_R_S 0
#define NIC_TXE_UDP_MASK_S_PORT_R_M 0xFFFF

/* NIC_TXE_PORT_MAC_CFG_47_32 */
#define NIC_TXE_PORT_MAC_CFG_47_32_R_S 0
#define NIC_TXE_PORT_MAC_CFG_47_32_R_M 0xFFFF

/* NIC_TXE_PORT_MAC_CFG_31_0 */
#define NIC_TXE_PORT_MAC_CFG_31_0_R_S 0
#define NIC_TXE_PORT_MAC_CFG_31_0_R_M 0xFFFFFFFF

/* NIC_TXE_PRIO_TO_DSCP */
#define NIC_TXE_PRIO_TO_DSCP_PRIO0_S 0
#define NIC_TXE_PRIO_TO_DSCP_PRIO0_M 0x3F
#define NIC_TXE_PRIO_TO_DSCP_PRIO1_S 8
#define NIC_TXE_PRIO_TO_DSCP_PRIO1_M 0x3F00
#define NIC_TXE_PRIO_TO_DSCP_PRIO2_S 16
#define NIC_TXE_PRIO_TO_DSCP_PRIO2_M 0x3F0000
#define NIC_TXE_PRIO_TO_DSCP_PRIO3_S 24
#define NIC_TXE_PRIO_TO_DSCP_PRIO3_M 0x3F000000

/* NIC_TXE_PRIO_TO_PCP */
#define NIC_TXE_PRIO_TO_PCP_PR0_PRIO0_S 0
#define NIC_TXE_PRIO_TO_PCP_PR0_PRIO0_M 0x7
#define NIC_TXE_PRIO_TO_PCP_PR0_PRIO1_S 3
#define NIC_TXE_PRIO_TO_PCP_PR0_PRIO1_M 0x38
#define NIC_TXE_PRIO_TO_PCP_PR0_PRIO2_S 6
#define NIC_TXE_PRIO_TO_PCP_PR0_PRIO2_M 0x1C0
#define NIC_TXE_PRIO_TO_PCP_PR0_PRIO3_S 9
#define NIC_TXE_PRIO_TO_PCP_PR0_PRIO3_M 0xE00
#define NIC_TXE_PRIO_TO_PCP_PR1_PRIO0_S 12
#define NIC_TXE_PRIO_TO_PCP_PR1_PRIO0_M 0x7000
#define NIC_TXE_PRIO_TO_PCP_PR1_PRIO1_S 15
#define NIC_TXE_PRIO_TO_PCP_PR1_PRIO1_M 0x38000
#define NIC_TXE_PRIO_TO_PCP_PR1_PRIO2_S 18
#define NIC_TXE_PRIO_TO_PCP_PR1_PRIO2_M 0x1C0000
#define NIC_TXE_PRIO_TO_PCP_PR1_PRIO3_S 21
#define NIC_TXE_PRIO_TO_PCP_PR1_PRIO3_M 0xE00000

/* NIC_TXE_UDP_CHECKSUM */
#define NIC_TXE_UDP_CHECKSUM_R_S 0
#define NIC_TXE_UDP_CHECKSUM_R_M 0xFFFF

/* NIC_TXE_UDP_DEST_PORT */
#define NIC_TXE_UDP_DEST_PORT_R_S 0
#define NIC_TXE_UDP_DEST_PORT_R_M 0xFFFF

/* NIC_TXE_MAC_ETHER_TYPE */
#define NIC_TXE_MAC_ETHER_TYPE_R_S 0
#define NIC_TXE_MAC_ETHER_TYPE_R_M 0xFFFF

/* NIC_TXE_MAC_ETHER_TYPE_VLAN */
#define NIC_TXE_MAC_ETHER_TYPE_VLAN_R_S 0
#define NIC_TXE_MAC_ETHER_TYPE_VLAN_R_M 0xFFFF

/* NIC_TXE_CREDIT_FORCE_FULL */
#define NIC_TXE_CREDIT_FORCE_FULL_PORT_PRIO_S 0
#define NIC_TXE_CREDIT_FORCE_FULL_PORT_PRIO_M 0xFFFF

/* NIC_TXE_PORT_PRIO_PLD_CREDIT */
#define NIC_TXE_PORT_PRIO_PLD_CREDIT_PRIO0_S 0
#define NIC_TXE_PORT_PRIO_PLD_CREDIT_PRIO0_M 0xFF
#define NIC_TXE_PORT_PRIO_PLD_CREDIT_PRIO1_S 8
#define NIC_TXE_PORT_PRIO_PLD_CREDIT_PRIO1_M 0xFF00
#define NIC_TXE_PORT_PRIO_PLD_CREDIT_PRIO2_S 16
#define NIC_TXE_PORT_PRIO_PLD_CREDIT_PRIO2_M 0xFF0000
#define NIC_TXE_PORT_PRIO_PLD_CREDIT_PRIO3_S 24
#define NIC_TXE_PORT_PRIO_PLD_CREDIT_PRIO3_M 0xFF000000

/* NIC_TXE_PORT_PRIO_HDR_CREDIT */
#define NIC_TXE_PORT_PRIO_HDR_CREDIT_PRIO0_S 0
#define NIC_TXE_PORT_PRIO_HDR_CREDIT_PRIO0_M 0xFF
#define NIC_TXE_PORT_PRIO_HDR_CREDIT_PRIO1_S 8
#define NIC_TXE_PORT_PRIO_HDR_CREDIT_PRIO1_M 0xFF00
#define NIC_TXE_PORT_PRIO_HDR_CREDIT_PRIO2_S 16
#define NIC_TXE_PORT_PRIO_HDR_CREDIT_PRIO2_M 0xFF0000
#define NIC_TXE_PORT_PRIO_HDR_CREDIT_PRIO3_S 24
#define NIC_TXE_PORT_PRIO_HDR_CREDIT_PRIO3_M 0xFF000000

/* NIC_TXE_PRIOQ_ALMOST_FULL */
#define NIC_TXE_PRIOQ_ALMOST_FULL_THR_PLD_S 0
#define NIC_TXE_PRIOQ_ALMOST_FULL_THR_PLD_M 0xFF
#define NIC_TXE_PRIOQ_ALMOST_FULL_THR_HDR_S 8
#define NIC_TXE_PRIOQ_ALMOST_FULL_THR_HDR_M 0xFF00
#define NIC_TXE_PRIOQ_ALMOST_FULL_EN_S 16
#define NIC_TXE_PRIOQ_ALMOST_FULL_EN_M 0x10000

/* NIC_TXE_NACK_SYNDROME */
#define NIC_TXE_NACK_SYNDROME_SYNDROME_0_S 0
#define NIC_TXE_NACK_SYNDROME_SYNDROME_0_M 0xFF
#define NIC_TXE_NACK_SYNDROME_SYNDROME_1_S 8
#define NIC_TXE_NACK_SYNDROME_SYNDROME_1_M 0xFF00
#define NIC_TXE_NACK_SYNDROME_SYNDROME_2_S 16
#define NIC_TXE_NACK_SYNDROME_SYNDROME_2_M 0xFF0000
#define NIC_TXE_NACK_SYNDROME_SYNDROME_3_S 24
#define NIC_TXE_NACK_SYNDROME_SYNDROME_3_M 0xFF000000

/* NIC_TXE_ECN_COUNT_EN */
#define NIC_TXE_ECN_COUNT_EN_R_S 0
#define NIC_TXE_ECN_COUNT_EN_R_M 0x1

/* NIC_TXE_INTERRUPT_CAUSE */
#define NIC_TXE_INTERRUPT_CAUSE_R_S 0
#define NIC_TXE_INTERRUPT_CAUSE_R_M 0xF

/* NIC_TXE_INTERRUPT_MASK */
#define NIC_TXE_INTERRUPT_MASK_R_S 0
#define NIC_TXE_INTERRUPT_MASK_R_M 0xF

/* NIC_TXE_INTERRUPT_CLR */
#define NIC_TXE_INTERRUPT_CLR_R_S 0
#define NIC_TXE_INTERRUPT_CLR_R_M 0x1

/* NIC_TXE_VLAN_TAG_QPN_OFFSET */
#define NIC_TXE_VLAN_TAG_QPN_OFFSET_R_S 0
#define NIC_TXE_VLAN_TAG_QPN_OFFSET_R_M 0x1F

/* NIC_TXE_VALN_TAG_CFG */
#define NIC_TXE_VALN_TAG_CFG_TPD_S 0
#define NIC_TXE_VALN_TAG_CFG_TPD_M 0xFFFF
#define NIC_TXE_VALN_TAG_CFG_VLAN_ID_S 16
#define NIC_TXE_VALN_TAG_CFG_VLAN_ID_M 0xFFF0000
#define NIC_TXE_VALN_TAG_CFG_DEI_S 28
#define NIC_TXE_VALN_TAG_CFG_DEI_M 0x10000000
#define NIC_TXE_VALN_TAG_CFG_ENABLE_S 31
#define NIC_TXE_VALN_TAG_CFG_ENABLE_M 0x80000000

/* NIC_TXE_DBG_TRIG */
#define NIC_TXE_DBG_TRIG_R_S 0
#define NIC_TXE_DBG_TRIG_R_M 0xF

/* NIC_TXE_SWAP_MEMORY_ENDIANNESS */
#define NIC_TXE_SWAP_MEMORY_ENDIANNESS_RAW_S 0
#define NIC_TXE_SWAP_MEMORY_ENDIANNESS_RAW_M 0x1
#define NIC_TXE_SWAP_MEMORY_ENDIANNESS_RDMA_S 1
#define NIC_TXE_SWAP_MEMORY_ENDIANNESS_RDMA_M 0x2

/* NIC_TXE_WQE_FETCH_SLICE_REG0 */
#define NIC_TXE_WQE_FETCH_SLICE_REG0_R_S 0
#define NIC_TXE_WQE_FETCH_SLICE_REG0_R_M 0xFFFFFFFF

/* NIC_TXE_WQE_FETCH_SLICE_REG1 */
#define NIC_TXE_WQE_FETCH_SLICE_REG1_R_S 0
#define NIC_TXE_WQE_FETCH_SLICE_REG1_R_M 0xFFFFFFFF

/* NIC_TXE_WQE_EXE_SLICE_REG0 */
#define NIC_TXE_WQE_EXE_SLICE_REG0_R_S 0
#define NIC_TXE_WQE_EXE_SLICE_REG0_R_M 0xFFFFFFFF

/* NIC_TXE_WQE_EXE_SLICE_REG1 */
#define NIC_TXE_WQE_EXE_SLICE_REG1_R_S 0
#define NIC_TXE_WQE_EXE_SLICE_REG1_R_M 0xFFFFFFFF

/* NIC_TXE_DBG_COUNT_SELECT0 */
#define NIC_TXE_DBG_COUNT_SELECT0_R_S 0
#define NIC_TXE_DBG_COUNT_SELECT0_R_M 0x3F

/* NIC_TXE_DBG_COUNT_SELECT1 */
#define NIC_TXE_DBG_COUNT_SELECT1_R_S 0
#define NIC_TXE_DBG_COUNT_SELECT1_R_M 0x3F

/* NIC_TXE_DBG_COUNT_SELECT2 */
#define NIC_TXE_DBG_COUNT_SELECT2_R_S 0
#define NIC_TXE_DBG_COUNT_SELECT2_R_M 0x3F

/* NIC_TXE_DBG_COUNT_SELECT3 */
#define NIC_TXE_DBG_COUNT_SELECT3_R_S 0
#define NIC_TXE_DBG_COUNT_SELECT3_R_M 0x3F

/* NIC_TXE_DBG_COUNT_SELECT4 */
#define NIC_TXE_DBG_COUNT_SELECT4_R_S 0
#define NIC_TXE_DBG_COUNT_SELECT4_R_M 0x3F

/* NIC_TXE_DBG_COUNT_SELECT5 */
#define NIC_TXE_DBG_COUNT_SELECT5_R_S 0
#define NIC_TXE_DBG_COUNT_SELECT5_R_M 0x3F

/* NIC_TXE_DBG_COUNT_SELECT6 */
#define NIC_TXE_DBG_COUNT_SELECT6_R_S 0
#define NIC_TXE_DBG_COUNT_SELECT6_R_M 0x3F

/* NIC_TXE_DBG_COUNT_SELECT7 */
#define NIC_TXE_DBG_COUNT_SELECT7_R_S 0
#define NIC_TXE_DBG_COUNT_SELECT7_R_M 0x3F

/* NIC_TXE_DBG_COUNT_SELECT8 */
#define NIC_TXE_DBG_COUNT_SELECT8_R_S 0
#define NIC_TXE_DBG_COUNT_SELECT8_R_M 0x3F

/* NIC_TXE_DBG_COUNT_SELECT9 */
#define NIC_TXE_DBG_COUNT_SELECT9_R_S 0
#define NIC_TXE_DBG_COUNT_SELECT9_R_M 0x3F

/* NIC_TXE_DBG_COUNT_SELECT10 */
#define NIC_TXE_DBG_COUNT_SELECT10_R_S 0
#define NIC_TXE_DBG_COUNT_SELECT10_R_M 0x3F

/* NIC_TXE_DBG_COUNT_SELECT11 */
#define NIC_TXE_DBG_COUNT_SELECT11_R_S 0
#define NIC_TXE_DBG_COUNT_SELECT11_R_M 0x3F

/* NIC_TXE_BTH_MKEY */
#define NIC_TXE_BTH_MKEY_R_S 0
#define NIC_TXE_BTH_MKEY_R_M 0xFFFF

/* NIC_TXE_WQE_BUFF_FLUSH_SLICE_REG0 */
#define NIC_TXE_WQE_BUFF_FLUSH_SLICE_REG0_R_S 0
#define NIC_TXE_WQE_BUFF_FLUSH_SLICE_REG0_R_M 0xFFFFFFFF

/* NIC_TXE_WQE_BUFF_FLUSH_SLICE_REG1 */
#define NIC_TXE_WQE_BUFF_FLUSH_SLICE_REG1_R_S 0
#define NIC_TXE_WQE_BUFF_FLUSH_SLICE_REG1_R_M 0xFFFFFFFF

/* NIC_TXE_CHICKEN_BITS */
#define NIC_TXE_CHICKEN_BITS_BUS_S 0
#define NIC_TXE_CHICKEN_BITS_BUS_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_EN */
#define NIC_TXE_WQE_CHECK_EN_WRITE_VALID_OPCODE_EN_S 0
#define NIC_TXE_WQE_CHECK_EN_WRITE_VALID_OPCODE_EN_M 0x1
#define NIC_TXE_WQE_CHECK_EN_RDV_VALID_OPCODE_EN_S 1
#define NIC_TXE_WQE_CHECK_EN_RDV_VALID_OPCODE_EN_M 0x2
#define NIC_TXE_WQE_CHECK_EN_READ_VALID_OPCODE_EN_S 2
#define NIC_TXE_WQE_CHECK_EN_READ_VALID_OPCODE_EN_M 0x4
#define NIC_TXE_WQE_CHECK_EN_INLINE_VALID_OPCODE_EN_S 3
#define NIC_TXE_WQE_CHECK_EN_INLINE_VALID_OPCODE_EN_M 0x8
#define NIC_TXE_WQE_CHECK_EN_WRITE_SIZE_ZERO_EN_S 4
#define NIC_TXE_WQE_CHECK_EN_WRITE_SIZE_ZERO_EN_M 0x10
#define NIC_TXE_WQE_CHECK_EN_STRIDE_SIZE_ZERO_EN_S 5
#define NIC_TXE_WQE_CHECK_EN_STRIDE_SIZE_ZERO_EN_M 0x20
#define NIC_TXE_WQE_CHECK_EN_SEND_SIZE_ZERO_EN_S 6
#define NIC_TXE_WQE_CHECK_EN_SEND_SIZE_ZERO_EN_M 0x40
#define NIC_TXE_WQE_CHECK_EN_RDV_WR_RD_SIZE_ZERO_EN_S 7
#define NIC_TXE_WQE_CHECK_EN_RDV_WR_RD_SIZE_ZERO_EN_M 0x80
#define NIC_TXE_WQE_CHECK_EN_WRITE_SEND_SIZE_2BIG_EN_S 8
#define NIC_TXE_WQE_CHECK_EN_WRITE_SEND_SIZE_2BIG_EN_M 0x100
#define NIC_TXE_WQE_CHECK_EN_STRIDE_SIZE_2BIG_EN_S 9
#define NIC_TXE_WQE_CHECK_EN_STRIDE_SIZE_2BIG_EN_M 0x200
#define NIC_TXE_WQE_CHECK_EN_RDV_REMOTE_LOG_SIZE_EN_S 10
#define NIC_TXE_WQE_CHECK_EN_RDV_REMOTE_LOG_SIZE_EN_M 0x400
#define NIC_TXE_WQE_CHECK_EN_RDV_WR_SIZE_BAD_EN_S 11
#define NIC_TXE_WQE_CHECK_EN_RDV_WR_SIZE_BAD_EN_M 0x800
#define NIC_TXE_WQE_CHECK_EN_RDV_RD_SIZE_BAD_EN_S 12
#define NIC_TXE_WQE_CHECK_EN_RDV_RD_SIZE_BAD_EN_M 0x1000
#define NIC_TXE_WQE_CHECK_EN_INLINE_SIZE_BAD_EN_S 13
#define NIC_TXE_WQE_CHECK_EN_INLINE_SIZE_BAD_EN_M 0x2000
#define NIC_TXE_WQE_CHECK_EN_STRIDE_BAD_GRAN_EN_S 14
#define NIC_TXE_WQE_CHECK_EN_STRIDE_BAD_GRAN_EN_M 0x4000
#define NIC_TXE_WQE_CHECK_EN_RAW_COMP_CONVERT_EN_S 15
#define NIC_TXE_WQE_CHECK_EN_RAW_COMP_CONVERT_EN_M 0x8000
#define NIC_TXE_WQE_CHECK_EN_STRIDE_WQE_SIZE_SMALL_EN_S 16
#define NIC_TXE_WQE_CHECK_EN_STRIDE_WQE_SIZE_SMALL_EN_M 0x10000
#define NIC_TXE_WQE_CHECK_EN_UPSCALE_ALIGN_EN_S 17
#define NIC_TXE_WQE_CHECK_EN_UPSCALE_ALIGN_EN_M 0x20000
#define NIC_TXE_WQE_CHECK_EN_UPSCALE_VALID_OPCODE_EN_S 18
#define NIC_TXE_WQE_CHECK_EN_UPSCALE_VALID_OPCODE_EN_M 0x40000
#define NIC_TXE_WQE_CHECK_EN_RAW_UNSUPPORTED_SIZE_EN_S 19
#define NIC_TXE_WQE_CHECK_EN_RAW_UNSUPPORTED_SIZE_EN_M 0x80000
#define NIC_TXE_WQE_CHECK_EN_SACK_NOP_EN_S 20
#define NIC_TXE_WQE_CHECK_EN_SACK_NOP_EN_M 0x100000
#define NIC_TXE_WQE_CHECK_EN_RAW_BAD_OPCODE_EN_S 21
#define NIC_TXE_WQE_CHECK_EN_RAW_BAD_OPCODE_EN_M 0x200000
#define NIC_TXE_WQE_CHECK_EN_PLAIN_VALID_OPCODE_EN_S 22
#define NIC_TXE_WQE_CHECK_EN_PLAIN_VALID_OPCODE_EN_M 0x400000
#define NIC_TXE_WQE_CHECK_EN_PLAIN_CONVERT_EN_S 23
#define NIC_TXE_WQE_CHECK_EN_PLAIN_CONVERT_EN_M 0x800000
#define NIC_TXE_WQE_CHECK_EN_CONVERT_BAD_ALIGN_EN_S 24
#define NIC_TXE_WQE_CHECK_EN_CONVERT_BAD_ALIGN_EN_M 0x1000000
#define NIC_TXE_WQE_CHECK_EN_RSVD_S 25
#define NIC_TXE_WQE_CHECK_EN_RSVD_M 0xFE000000

/* NIC_TXE_WQE_CHECK_EN2 */
#define NIC_TXE_WQE_CHECK_EN2_RSVD_S 0
#define NIC_TXE_WQE_CHECK_EN2_RSVD_M 0x7FFFF
#define NIC_TXE_WQE_CHECK_EN2_WQE_SENT_OVERFLOW_EN_S 19
#define NIC_TXE_WQE_CHECK_EN2_WQE_SENT_OVERFLOW_EN_M 0x80000
#define NIC_TXE_WQE_CHECK_EN2_MIN_LOCAL_WQ_LOG_SIZE_ERR_S 20
#define NIC_TXE_WQE_CHECK_EN2_MIN_LOCAL_WQ_LOG_SIZE_ERR_M 0x100000
#define NIC_TXE_WQE_CHECK_EN2_MAX_LOCAL_WQ_LOG_SIZE_ERR_S 21
#define NIC_TXE_WQE_CHECK_EN2_MAX_LOCAL_WQ_LOG_SIZE_ERR_M 0x200000
#define NIC_TXE_WQE_CHECK_EN2_RAW_ABOVE_MIN_RAW_UNSUPPO_S 22
#define NIC_TXE_WQE_CHECK_EN2_RAW_ABOVE_MIN_RAW_UNSUPPO_M 0x400000
#define NIC_TXE_WQE_CHECK_EN2_RAW_BELOW_MAX_RAW_UNSUPPO_S 23
#define NIC_TXE_WQE_CHECK_EN2_RAW_BELOW_MAX_RAW_UNSUPPO_M 0x800000
#define NIC_TXE_WQE_CHECK_EN2_RDV_READ_AND_INLINE_ERR_S 24
#define NIC_TXE_WQE_CHECK_EN2_RDV_READ_AND_INLINE_ERR_M 0x1000000
#define NIC_TXE_WQE_CHECK_EN2_ATOMIC_FNA_BAD_SIZE_EN_S 25
#define NIC_TXE_WQE_CHECK_EN2_ATOMIC_FNA_BAD_SIZE_EN_M 0x2000000
#define NIC_TXE_WQE_CHECK_EN2_ATOMIC_FNA_BAD_ADDR_EN_S 26
#define NIC_TXE_WQE_CHECK_EN2_ATOMIC_FNA_BAD_ADDR_EN_M 0x4000000
#define NIC_TXE_WQE_CHECK_EN2_OPCODE_ABOVE_15_ERR_S 27
#define NIC_TXE_WQE_CHECK_EN2_OPCODE_ABOVE_15_ERR_M 0x8000000
#define NIC_TXE_WQE_CHECK_EN2_WQE_SE_NOT_RAW_S 28
#define NIC_TXE_WQE_CHECK_EN2_WQE_SE_NOT_RAW_M 0x10000000
#define NIC_TXE_WQE_CHECK_EN2_WQE_BAD_SIZE_ERR_S 29
#define NIC_TXE_WQE_CHECK_EN2_WQE_BAD_SIZE_ERR_M 0x20000000
#define NIC_TXE_WQE_CHECK_EN2_TUNNEL_ZERO_SIZE_ERR_S 30
#define NIC_TXE_WQE_CHECK_EN2_TUNNEL_ZERO_SIZE_ERR_M 0x40000000
#define NIC_TXE_WQE_CHECK_EN2_TUNNEL_MAX_SIZE_ERR_S 31
#define NIC_TXE_WQE_CHECK_EN2_TUNNEL_MAX_SIZE_ERR_M 0x80000000

/* NIC_TXE_WQE_CHECK_QPC_OPC_WR_WQ_TYPE_ERR */
#define NIC_TXE_WQE_CHECK_QPC_OPC_WR_WQ_TYPE_ERR_EN_S 0
#define NIC_TXE_WQE_CHECK_QPC_OPC_WR_WQ_TYPE_ERR_EN_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_QPC_OPC_RD_WQ_TYPE_ERR */
#define NIC_TXE_WQE_CHECK_QPC_OPC_RD_WQ_TYPE_ERR_EN_S 0
#define NIC_TXE_WQE_CHECK_QPC_OPC_RD_WQ_TYPE_ERR_EN_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_WQE_OPCODE_ERR */
#define NIC_TXE_WQE_CHECK_WQE_OPCODE_ERR_EN_S 0
#define NIC_TXE_WQE_CHECK_WQE_OPCODE_ERR_EN_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_WQE_SIZE_ERR */
#define NIC_TXE_WQE_CHECK_WQE_SIZE_ERR_EN_S 0
#define NIC_TXE_WQE_CHECK_WQE_SIZE_ERR_EN_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_INLINE_ERR */
#define NIC_TXE_WQE_CHECK_INLINE_ERR_EN_S 0
#define NIC_TXE_WQE_CHECK_INLINE_ERR_EN_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_UPSCALE_ERR */
#define NIC_TXE_WQE_CHECK_UPSCALE_ERR_EN_S 0
#define NIC_TXE_WQE_CHECK_UPSCALE_ERR_EN_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_PLAIN_RDMA_ERR */
#define NIC_TXE_WQE_CHECK_PLAIN_RDMA_ERR_EN_S 0
#define NIC_TXE_WQE_CHECK_PLAIN_RDMA_ERR_EN_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_CONST1 */
#define NIC_TXE_WQE_CHECK_CONST1_WRITE_SEND_MAX_SIZE_S 0
#define NIC_TXE_WQE_CHECK_CONST1_WRITE_SEND_MAX_SIZE_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_CONST2 */
#define NIC_TXE_WQE_CHECK_CONST2_STRIDE_MAX_WQE_SIZE_S 0
#define NIC_TXE_WQE_CHECK_CONST2_STRIDE_MAX_WQE_SIZE_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_CONST3 */
#define NIC_TXE_WQE_CHECK_CONST3_RDV_GRAN1_WQE_SIZE_S 0
#define NIC_TXE_WQE_CHECK_CONST3_RDV_GRAN1_WQE_SIZE_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_CONST4 */
#define NIC_TXE_WQE_CHECK_CONST4_RDV_GRAN0_WQE_SIZE_S 0
#define NIC_TXE_WQE_CHECK_CONST4_RDV_GRAN0_WQE_SIZE_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_CONST5 */
#define NIC_TXE_WQE_CHECK_CONST5_INL_GRAN1_WQE_SIZE_S 0
#define NIC_TXE_WQE_CHECK_CONST5_INL_GRAN1_WQE_SIZE_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_CONST6 */
#define NIC_TXE_WQE_CHECK_CONST6_INL_GRAN0_WQE_SIZE_S 0
#define NIC_TXE_WQE_CHECK_CONST6_INL_GRAN0_WQE_SIZE_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_CONST7 */
#define NIC_TXE_WQE_CHECK_CONST7_ERR_WQE_SIZE_S 0
#define NIC_TXE_WQE_CHECK_CONST7_ERR_WQE_SIZE_M 0xFFFFFFFF

/* NIC_TXE_TXWQC_STATUS */
#define NIC_TXE_TXWQC_STATUS_INVALIDATE_DONE_S 0
#define NIC_TXE_TXWQC_STATUS_INVALIDATE_DONE_M 0x1
#define NIC_TXE_TXWQC_STATUS_CACHE_WR_IDLE_S 1
#define NIC_TXE_TXWQC_STATUS_CACHE_WR_IDLE_M 0x2
#define NIC_TXE_TXWQC_STATUS_CACHE_RD_IDLE_S 2
#define NIC_TXE_TXWQC_STATUS_CACHE_RD_IDLE_M 0x4
#define NIC_TXE_TXWQC_STATUS_CACHE_USED_ENTRY_S 8
#define NIC_TXE_TXWQC_STATUS_CACHE_USED_ENTRY_M 0xFF00
#define NIC_TXE_TXWQC_STATUS_CACHE_STATS_S 16
#define NIC_TXE_TXWQC_STATUS_CACHE_STATS_M 0x3F0000

/* NIC_TXE_TXWQC_INVALIDATE */
#define NIC_TXE_TXWQC_INVALIDATE_INVALIDATE_SC_S 0
#define NIC_TXE_TXWQC_INVALIDATE_INVALIDATE_SC_M 0x1

/* NIC_TXE_STATS_CFG0 */
#define NIC_TXE_STATS_CFG0_MEAS_WIN_SIZE_S 0
#define NIC_TXE_STATS_CFG0_MEAS_WIN_SIZE_M 0xFFFFFFFF

/* NIC_TXE_STATS_CFG1 */
#define NIC_TXE_STATS_CFG1_TOT_TYPE_S 0
#define NIC_TXE_STATS_CFG1_TOT_TYPE_M 0x3
#define NIC_TXE_STATS_CFG1_WIN_TYPE_S 4
#define NIC_TXE_STATS_CFG1_WIN_TYPE_M 0x30
#define NIC_TXE_STATS_CFG1_ENABLE_S 8
#define NIC_TXE_STATS_CFG1_ENABLE_M 0x100
#define NIC_TXE_STATS_CFG1_WIN_SAMP_LATENCY_S 9
#define NIC_TXE_STATS_CFG1_WIN_SAMP_LATENCY_M 0x200
#define NIC_TXE_STATS_CFG1_IGNORE_MIN_ZERO_S 10
#define NIC_TXE_STATS_CFG1_IGNORE_MIN_ZERO_M 0x400
#define NIC_TXE_STATS_CFG1_LATENCY_ENABLE_S 11
#define NIC_TXE_STATS_CFG1_LATENCY_ENABLE_M 0x800
#define NIC_TXE_STATS_CFG1_CLEAR_SC_S 31
#define NIC_TXE_STATS_CFG1_CLEAR_SC_M 0x80000000

/* NIC_TXE_STATS_CFG2 */
#define NIC_TXE_STATS_CFG2_LATENCY_MAX_VAL_S 0
#define NIC_TXE_STATS_CFG2_LATENCY_MAX_VAL_M 0xFFFF
#define NIC_TXE_STATS_CFG2_LATENCY_WRAP_EN_S 16
#define NIC_TXE_STATS_CFG2_LATENCY_WRAP_EN_M 0x10000

/* NIC_TXE_STATS_TOT_BYTES_LSB */
#define NIC_TXE_STATS_TOT_BYTES_LSB_R_S 0
#define NIC_TXE_STATS_TOT_BYTES_LSB_R_M 0xFFFFFFFF

/* NIC_TXE_STATS_TOT_BYTES_MSB */
#define NIC_TXE_STATS_TOT_BYTES_MSB_R_S 0
#define NIC_TXE_STATS_TOT_BYTES_MSB_R_M 0xFFFFFFFF

/* NIC_TXE_STATS_TOT_PKTS_LSB */
#define NIC_TXE_STATS_TOT_PKTS_LSB_R_S 0
#define NIC_TXE_STATS_TOT_PKTS_LSB_R_M 0xFFFFFFFF

/* NIC_TXE_STATS_TOT_PKTS_MSB */
#define NIC_TXE_STATS_TOT_PKTS_MSB_R_S 0
#define NIC_TXE_STATS_TOT_PKTS_MSB_R_M 0xFFFFFFFF

/* NIC_TXE_STATS_MEAS_WIN_BYTES_LSB */
#define NIC_TXE_STATS_MEAS_WIN_BYTES_LSB_R_S 0
#define NIC_TXE_STATS_MEAS_WIN_BYTES_LSB_R_M 0xFFFFFFFF

/* NIC_TXE_STATS_MEAS_WIN_BYTES_MSB */
#define NIC_TXE_STATS_MEAS_WIN_BYTES_MSB_R_S 0
#define NIC_TXE_STATS_MEAS_WIN_BYTES_MSB_R_M 0xFFFFFFFF

/* NIC_TXE_STATS_MEAS_WIN_PKTS */
#define NIC_TXE_STATS_MEAS_WIN_PKTS_R_S 0
#define NIC_TXE_STATS_MEAS_WIN_PKTS_R_M 0xFFFFFFFF

/* NIC_TXE_STATS_MEAS_LATENCY */
#define NIC_TXE_STATS_MEAS_LATENCY_ERROR_CNTR_S 0
#define NIC_TXE_STATS_MEAS_LATENCY_ERROR_CNTR_M 0xFFFF

/* NIC_TXE_HW_EVENT_CFG */
#define NIC_TXE_HW_EVENT_CFG_EVENT_ID_S 0
#define NIC_TXE_HW_EVENT_CFG_EVENT_ID_M 0xFFFF
#define NIC_TXE_HW_EVENT_CFG_DBG_SELECT0_S 16
#define NIC_TXE_HW_EVENT_CFG_DBG_SELECT0_M 0xF0000
#define NIC_TXE_HW_EVENT_CFG_DBG_SELECT1_S 20
#define NIC_TXE_HW_EVENT_CFG_DBG_SELECT1_M 0xF00000
#define NIC_TXE_HW_EVENT_CFG_DBG_SELECT2_S 24
#define NIC_TXE_HW_EVENT_CFG_DBG_SELECT2_M 0xF000000

/* NIC_TXE_BTH_RSVD */
#define NIC_TXE_BTH_RSVD_REQ_RSVD2_S 0
#define NIC_TXE_BTH_RSVD_REQ_RSVD2_M 0x3
#define NIC_TXE_BTH_RSVD_REQ_RSVD6_S 2
#define NIC_TXE_BTH_RSVD_REQ_RSVD6_M 0xFC
#define NIC_TXE_BTH_RSVD_RES_RSVD2_S 8
#define NIC_TXE_BTH_RSVD_RES_RSVD2_M 0x300
#define NIC_TXE_BTH_RSVD_RES_RSVD6_S 10
#define NIC_TXE_BTH_RSVD_RES_RSVD6_M 0xFC00
#define NIC_TXE_BTH_RSVD_RES_RSVD7_S 16
#define NIC_TXE_BTH_RSVD_RES_RSVD7_M 0x7F0000
#define NIC_TXE_BTH_RSVD_RES_SOB_EN_S 23
#define NIC_TXE_BTH_RSVD_RES_SOB_EN_M 0x800000
#define NIC_TXE_BTH_RSVD_RES_CI_VALID_S 25
#define NIC_TXE_BTH_RSVD_RES_CI_VALID_M 0x2000000

/* NIC_TXE_MULTI_PKT_WQE */
#define NIC_TXE_MULTI_PKT_WQE_ACKREQ_ON_LAST_PKT_S 0
#define NIC_TXE_MULTI_PKT_WQE_ACKREQ_ON_LAST_PKT_M 0x1
#define NIC_TXE_MULTI_PKT_WQE_ACKREQ_ON_RETRANS_EN_S 1
#define NIC_TXE_MULTI_PKT_WQE_ACKREQ_ON_RETRANS_EN_M 0x2
#define NIC_TXE_MULTI_PKT_WQE_RDV_QUARTER_GUARD_S 16
#define NIC_TXE_MULTI_PKT_WQE_RDV_QUARTER_GUARD_M 0xF0000

/* NIC_TXE_ENCAP_CFG */
#define NIC_TXE_ENCAP_CFG_IPV4_PROTOCOL_UDP_DEST_S 0
#define NIC_TXE_ENCAP_CFG_IPV4_PROTOCOL_UDP_DEST_M 0xFFFF
#define NIC_TXE_ENCAP_CFG_ENCAP_SIZE_S 24
#define NIC_TXE_ENCAP_CFG_ENCAP_SIZE_M 0xF000000
#define NIC_TXE_ENCAP_CFG_HDR_FORMAT_S 28
#define NIC_TXE_ENCAP_CFG_HDR_FORMAT_M 0x10000000

/* NIC_TXE_ENCAP_DATA_31_0 */
#define NIC_TXE_ENCAP_DATA_31_0_R_S 0
#define NIC_TXE_ENCAP_DATA_31_0_R_M 0xFFFFFFFF

/* NIC_TXE_ENCAP_DATA_63_32 */
#define NIC_TXE_ENCAP_DATA_63_32_R_S 0
#define NIC_TXE_ENCAP_DATA_63_32_R_M 0xFFFFFFFF

/* NIC_TXE_ENCAP_DATA_95_64 */
#define NIC_TXE_ENCAP_DATA_95_64_R_S 0
#define NIC_TXE_ENCAP_DATA_95_64_R_M 0xFFFFFFFF

/* NIC_TXE_ENCAP_DATA_127_96 */
#define NIC_TXE_ENCAP_DATA_127_96_R_S 0
#define NIC_TXE_ENCAP_DATA_127_96_R_M 0xFFFFFFFF

/* NIC_TXE_ENCAP_DATA_159_128 */
#define NIC_TXE_ENCAP_DATA_159_128_R_S 0
#define NIC_TXE_ENCAP_DATA_159_128_R_M 0xFFFFFFFF

/* NIC_TXE_ENCAP_DATA_191_160 */
#define NIC_TXE_ENCAP_DATA_191_160_R_S 0
#define NIC_TXE_ENCAP_DATA_191_160_R_M 0xFFFFFFFF

/* NIC_TXE_ENCAP_DATA_223_192 */
#define NIC_TXE_ENCAP_DATA_223_192_R_S 0
#define NIC_TXE_ENCAP_DATA_223_192_R_M 0xFFFFFFFF

/* NIC_TXE_ENCAP_DATA_255_224 */
#define NIC_TXE_ENCAP_DATA_255_224_R_S 0
#define NIC_TXE_ENCAP_DATA_255_224_R_M 0xFFFFFFFF

/* NIC_TXE_ENCAP_CFG2 */
#define NIC_TXE_ENCAP_CFG2_CHECKSUM_S 0
#define NIC_TXE_ENCAP_CFG2_CHECKSUM_M 0xFFFF
#define NIC_TXE_ENCAP_CFG2_MASK_S_PORT_S 16
#define NIC_TXE_ENCAP_CFG2_MASK_S_PORT_M 0xFFFF0000

/* NIC_TXE_MTD_DUAL_STRIDE3 */
#define NIC_TXE_MTD_DUAL_STRIDE3_R_S 0
#define NIC_TXE_MTD_DUAL_STRIDE3_R_M 0xFFFFFFFF

/* NIC_TXE_MTD_DUAL_STRIDE4 */
#define NIC_TXE_MTD_DUAL_STRIDE4_R_S 0
#define NIC_TXE_MTD_DUAL_STRIDE4_R_M 0xFFFFFFFF

/* NIC_TXE_MTD_DUAL_NUM_OF_STRIDES */
#define NIC_TXE_MTD_DUAL_NUM_OF_STRIDES_R3_S 0
#define NIC_TXE_MTD_DUAL_NUM_OF_STRIDES_R3_M 0xFFFF
#define NIC_TXE_MTD_DUAL_NUM_OF_STRIDES_R4_S 16
#define NIC_TXE_MTD_DUAL_NUM_OF_STRIDES_R4_M 0xFFFF0000

/* NIC_TXE_CLK_GATE_CFG */
#define NIC_TXE_CLK_GATE_CFG_CLOSE_DELAY_S 0
#define NIC_TXE_CLK_GATE_CFG_CLOSE_DELAY_M 0x3FFFFFFF
#define NIC_TXE_CLK_GATE_CFG_FORCE_OPEN_S 31
#define NIC_TXE_CLK_GATE_CFG_FORCE_OPEN_M 0x80000000

/* NIC_TXE_WQE_CHECK_NOTIFY_EN */
#define NIC_TXE_WQE_CHECK_NOTIFY_EN_BUS_S 0
#define NIC_TXE_WQE_CHECK_NOTIFY_EN_BUS_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_NOTIFY_EN2 */
#define NIC_TXE_WQE_CHECK_NOTIFY_EN2_BUS_S 0
#define NIC_TXE_WQE_CHECK_NOTIFY_EN2_BUS_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_CFG4 */
#define NIC_TXE_WQE_CHECK_CFG4_MIN_RAW_UNSUPPORTED_SIZE_S 0
#define NIC_TXE_WQE_CHECK_CFG4_MIN_RAW_UNSUPPORTED_SIZE_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_CFG5 */
#define NIC_TXE_WQE_CHECK_CFG5_MAX_RAW_UNSUPPORTED_SIZE_S 0
#define NIC_TXE_WQE_CHECK_CFG5_MAX_RAW_UNSUPPORTED_SIZE_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_CFG6 */
#define NIC_TXE_WQE_CHECK_CFG6_QPC_OPC_RDV_WQE_TYPE_ERR_S 0
#define NIC_TXE_WQE_CHECK_CFG6_QPC_OPC_RDV_WQE_TYPE_ERR_M 0xFFFFFFFF

/* NIC_TXE_WQE_CHECK_CFG7 */
#define NIC_TXE_WQE_CHECK_CFG7_MIN_REMOTE_LOG_SIZE_S 0
#define NIC_TXE_WQE_CHECK_CFG7_MIN_REMOTE_LOG_SIZE_M 0x1F
#define NIC_TXE_WQE_CHECK_CFG7_MIN_LOCAL_WQ_LOG_SIZE_S 8
#define NIC_TXE_WQE_CHECK_CFG7_MIN_LOCAL_WQ_LOG_SIZE_M 0x1F00
#define NIC_TXE_WQE_CHECK_CFG7_MAX_LOCAL_WQ_LOG_SIZE_S 16
#define NIC_TXE_WQE_CHECK_CFG7_MAX_LOCAL_WQ_LOG_SIZE_M 0x1F0000

/* NIC_TXE_DATA_READ_RL_CFG */
#define NIC_TXE_DATA_READ_RL_CFG_EN_S 0
#define NIC_TXE_DATA_READ_RL_CFG_EN_M 0x1
#define NIC_TXE_DATA_READ_RL_CFG_SATURATION_S 8
#define NIC_TXE_DATA_READ_RL_CFG_SATURATION_M 0xFF00
#define NIC_TXE_DATA_READ_RL_CFG_RST_TOKEN_S 16
#define NIC_TXE_DATA_READ_RL_CFG_RST_TOKEN_M 0xFF0000
#define NIC_TXE_DATA_READ_RL_CFG_TIMEOUT_S 24
#define NIC_TXE_DATA_READ_RL_CFG_TIMEOUT_M 0xFF000000

/* NIC_TXE_CTRL_READ_RL_CFG */
#define NIC_TXE_CTRL_READ_RL_CFG_EN_S 0
#define NIC_TXE_CTRL_READ_RL_CFG_EN_M 0x1
#define NIC_TXE_CTRL_READ_RL_CFG_SATURATION_S 8
#define NIC_TXE_CTRL_READ_RL_CFG_SATURATION_M 0xFF00
#define NIC_TXE_CTRL_READ_RL_CFG_RST_TOKEN_S 16
#define NIC_TXE_CTRL_READ_RL_CFG_RST_TOKEN_M 0xFF0000
#define NIC_TXE_CTRL_READ_RL_CFG_TIMEOUT_S 24
#define NIC_TXE_CTRL_READ_RL_CFG_TIMEOUT_M 0xFF000000

/* NIC_TXE_SOURCE_IP_PORT0 */
#define NIC_TXE_SOURCE_IP_PORT0_SOURCE_IP_S 0
#define NIC_TXE_SOURCE_IP_PORT0_SOURCE_IP_M 0xFFFFFFFF

/* NIC_TXE_SOURCE_IP_PORT1 */
#define NIC_TXE_SOURCE_IP_PORT1_SOURCE_IP_S 0
#define NIC_TXE_SOURCE_IP_PORT1_SOURCE_IP_M 0xFFFFFFFF

/* NIC_TXE_SOURCE_IP_PORT2 */
#define NIC_TXE_SOURCE_IP_PORT2_SOURCE_IP_S 0
#define NIC_TXE_SOURCE_IP_PORT2_SOURCE_IP_M 0xFFFFFFFF

/* NIC_TXE_SOURCE_IP_PORT3 */
#define NIC_TXE_SOURCE_IP_PORT3_SOURCE_IP_S 0
#define NIC_TXE_SOURCE_IP_PORT3_SOURCE_IP_M 0xFFFFFFFF

/* NIC_TXE_IPV4_TIME_TO_LIVE */
#define NIC_TXE_IPV4_TIME_TO_LIVE_R_S 0
#define NIC_TXE_IPV4_TIME_TO_LIVE_R_M 0xFF

/* NIC_TXE_ECN */
#define NIC_TXE_ECN_PORT0_S 0
#define NIC_TXE_ECN_PORT0_M 0x3
#define NIC_TXE_ECN_PORT1_S 4
#define NIC_TXE_ECN_PORT1_M 0x30
#define NIC_TXE_ECN_PORT2_S 8
#define NIC_TXE_ECN_PORT2_M 0x300
#define NIC_TXE_ECN_PORT3_S 12
#define NIC_TXE_ECN_PORT3_M 0x3000

/* NIC_TXE_TUNNEL */
#define NIC_TXE_TUNNEL_TUNNEL_WORD_POS_S 0
#define NIC_TXE_TUNNEL_TUNNEL_WORD_POS_M 0x3F

/* NIC_TXE_QPC_IF_LIMITER */
#define NIC_TXE_QPC_IF_LIMITER_CNTR_EN_S 0
#define NIC_TXE_QPC_IF_LIMITER_CNTR_EN_M 0x3
#define NIC_TXE_QPC_IF_LIMITER_CNTR0_THR_S 8
#define NIC_TXE_QPC_IF_LIMITER_CNTR0_THR_M 0xFF00
#define NIC_TXE_QPC_IF_LIMITER_CNTR1_THR_S 16
#define NIC_TXE_QPC_IF_LIMITER_CNTR1_THR_M 0xFF0000

/* NIC_TXE_OCCUP_SLICE_CNTR */
#define NIC_TXE_OCCUP_SLICE_CNTR_IGNORE_BURST_THRESHOLD_S 0
#define NIC_TXE_OCCUP_SLICE_CNTR_IGNORE_BURST_THRESHOLD_M 0xFF
#define NIC_TXE_OCCUP_SLICE_CNTR_COUNT_RESPONDERS_S 16
#define NIC_TXE_OCCUP_SLICE_CNTR_COUNT_RESPONDERS_M 0x10000
#define NIC_TXE_OCCUP_SLICE_CNTR_IGNORE_BURST_PER_PRIOQ_S 17
#define NIC_TXE_OCCUP_SLICE_CNTR_IGNORE_BURST_PER_PRIOQ_M 0x20000
#define NIC_TXE_OCCUP_SLICE_CNTR_DBG_OCCUP_SLICE_CNTR_S 24
#define NIC_TXE_OCCUP_SLICE_CNTR_DBG_OCCUP_SLICE_CNTR_M 0xFF000000

/* NIC_TXE_TXWQC */
#define NIC_TXE_TXWQC_EN_S 0
#define NIC_TXE_TXWQC_EN_M 0x1
#define NIC_TXE_TXWQC_PRIO_BASED_EVICTION_EN_S 1
#define NIC_TXE_TXWQC_PRIO_BASED_EVICTION_EN_M 0x2

/* NIC_TXE_PORT_PRIO_PLD_EVICT_ON_TH */
#define NIC_TXE_PORT_PRIO_PLD_EVICT_ON_TH_PRIO0_S 0
#define NIC_TXE_PORT_PRIO_PLD_EVICT_ON_TH_PRIO0_M 0xFF
#define NIC_TXE_PORT_PRIO_PLD_EVICT_ON_TH_PRIO1_S 8
#define NIC_TXE_PORT_PRIO_PLD_EVICT_ON_TH_PRIO1_M 0xFF00
#define NIC_TXE_PORT_PRIO_PLD_EVICT_ON_TH_PRIO2_S 16
#define NIC_TXE_PORT_PRIO_PLD_EVICT_ON_TH_PRIO2_M 0xFF0000
#define NIC_TXE_PORT_PRIO_PLD_EVICT_ON_TH_PRIO3_S 24
#define NIC_TXE_PORT_PRIO_PLD_EVICT_ON_TH_PRIO3_M 0xFF000000

/* NIC_TXE_PORT_PRIO_PLD_EVICT_OFF_TH */
#define NIC_TXE_PORT_PRIO_PLD_EVICT_OFF_TH_PRIO0_S 0
#define NIC_TXE_PORT_PRIO_PLD_EVICT_OFF_TH_PRIO0_M 0xFF
#define NIC_TXE_PORT_PRIO_PLD_EVICT_OFF_TH_PRIO1_S 8
#define NIC_TXE_PORT_PRIO_PLD_EVICT_OFF_TH_PRIO1_M 0xFF00
#define NIC_TXE_PORT_PRIO_PLD_EVICT_OFF_TH_PRIO2_S 16
#define NIC_TXE_PORT_PRIO_PLD_EVICT_OFF_TH_PRIO2_M 0xFF0000
#define NIC_TXE_PORT_PRIO_PLD_EVICT_OFF_TH_PRIO3_S 24
#define NIC_TXE_PORT_PRIO_PLD_EVICT_OFF_TH_PRIO3_M 0xFF000000

/* NIC_TXE_PORT_PRIO_HDR_EVICT_ON_TH */
#define NIC_TXE_PORT_PRIO_HDR_EVICT_ON_TH_PRIO0_S 0
#define NIC_TXE_PORT_PRIO_HDR_EVICT_ON_TH_PRIO0_M 0xFF
#define NIC_TXE_PORT_PRIO_HDR_EVICT_ON_TH_PRIO1_S 8
#define NIC_TXE_PORT_PRIO_HDR_EVICT_ON_TH_PRIO1_M 0xFF00
#define NIC_TXE_PORT_PRIO_HDR_EVICT_ON_TH_PRIO2_S 16
#define NIC_TXE_PORT_PRIO_HDR_EVICT_ON_TH_PRIO2_M 0xFF0000
#define NIC_TXE_PORT_PRIO_HDR_EVICT_ON_TH_PRIO3_S 24
#define NIC_TXE_PORT_PRIO_HDR_EVICT_ON_TH_PRIO3_M 0xFF000000

/* NIC_TXE_PORT_PRIO_HDR_EVICT_OFF_TH */
#define NIC_TXE_PORT_PRIO_HDR_EVICT_OFF_TH_PRIO0_S 0
#define NIC_TXE_PORT_PRIO_HDR_EVICT_OFF_TH_PRIO0_M 0xFF
#define NIC_TXE_PORT_PRIO_HDR_EVICT_OFF_TH_PRIO1_S 8
#define NIC_TXE_PORT_PRIO_HDR_EVICT_OFF_TH_PRIO1_M 0xFF00
#define NIC_TXE_PORT_PRIO_HDR_EVICT_OFF_TH_PRIO2_S 16
#define NIC_TXE_PORT_PRIO_HDR_EVICT_OFF_TH_PRIO2_M 0xFF0000
#define NIC_TXE_PORT_PRIO_HDR_EVICT_OFF_TH_PRIO3_S 24
#define NIC_TXE_PORT_PRIO_HDR_EVICT_OFF_TH_PRIO3_M 0xFF000000

/* NIC_TXE_PORT_PRIO_FORCE_EVICT */
#define NIC_TXE_PORT_PRIO_FORCE_EVICT_EN_S 0
#define NIC_TXE_PORT_PRIO_FORCE_EVICT_EN_M 0xFFFF

/* NIC_TXE_EVICT_IGNORE_THRESHOLD */
#define NIC_TXE_EVICT_IGNORE_THRESHOLD_VAL_S 0
#define NIC_TXE_EVICT_IGNORE_THRESHOLD_VAL_M 0x3F

/* NIC_TXE_RDV_RD_WQE_SOB_ATTR */
#define NIC_TXE_RDV_RD_WQE_SOB_ATTR_LSO_S 0
#define NIC_TXE_RDV_RD_WQE_SOB_ATTR_LSO_M 0x1
#define NIC_TXE_RDV_RD_WQE_SOB_ATTR_SOB_CTRL_S 1
#define NIC_TXE_RDV_RD_WQE_SOB_ATTR_SOB_CTRL_M 0x2

/* NIC_TXE_LONGTAIL_SOB_CFG */
#define NIC_TXE_LONGTAIL_SOB_CFG_CT_MASK_S 0
#define NIC_TXE_LONGTAIL_SOB_CFG_CT_MASK_M 0x3
#define NIC_TXE_LONGTAIL_SOB_CFG_SOB_ID_S 2
#define NIC_TXE_LONGTAIL_SOB_CFG_SOB_ID_M 0x7FFC

/* NIC_TXE_DBG_TXWQC_HIT_STAT */
#define NIC_TXE_DBG_TXWQC_HIT_STAT_VAL_S 0
#define NIC_TXE_DBG_TXWQC_HIT_STAT_VAL_M 0xFFFFFFFF

/* NIC_TXE_DBG_TXWQC_MISS_STAT */
#define NIC_TXE_DBG_TXWQC_MISS_STAT_VAL_S 0
#define NIC_TXE_DBG_TXWQC_MISS_STAT_VAL_M 0xFFFFFFFF

/* NIC_TXE_LOG_MAX_WQ_SIZE */
#define NIC_TXE_LOG_MAX_WQ_SIZE_R_S 0
#define NIC_TXE_LOG_MAX_WQ_SIZE_R_M 0x1F

/* NIC_TXE_SQ_BASE_ADDRESS_63_32 */
#define NIC_TXE_SQ_BASE_ADDRESS_63_32_R_S 0
#define NIC_TXE_SQ_BASE_ADDRESS_63_32_R_M 0xFFFFFFFF

/* NIC_TXE_SQ_BASE_ADDRESS_31_0 */
#define NIC_TXE_SQ_BASE_ADDRESS_31_0_R_S 0
#define NIC_TXE_SQ_BASE_ADDRESS_31_0_R_M 0xFFFFFFFF

/* NIC_TXE_WQE_FETCH_AXI_USER */
#define NIC_TXE_WQE_FETCH_AXI_USER_0_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_0_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_1_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_1_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_2_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_2_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_3_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_3_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_4_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_4_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_5_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_5_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_6_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_6_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_7_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_7_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_8_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_8_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_9_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_9_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_10_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_10_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_11_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_11_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_12_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_12_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_13_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_13_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_14_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_14_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_15_ASID_S 0
#define NIC_TXE_WQE_FETCH_AXI_USER_15_ASID_M 0x3FF
#define NIC_TXE_WQE_FETCH_AXI_USER_MMU_BYPASS_S 10
#define NIC_TXE_WQE_FETCH_AXI_USER_MMU_BYPASS_M 0x400

/* NIC_TXE_WQE_FETCH_AXI_PROT_UNSEC */
#define NIC_TXE_WQE_FETCH_AXI_PROT_UNSEC_VAL_S 0
#define NIC_TXE_WQE_FETCH_AXI_PROT_UNSEC_VAL_M 0x7

/* NIC_TXE_WQE_FETCH_AXI_PROT_SEC */
#define NIC_TXE_WQE_FETCH_AXI_PROT_SEC_VAL_S 0
#define NIC_TXE_WQE_FETCH_AXI_PROT_SEC_VAL_M 0x7

/* NIC_TXE_WQE_FETCH_AXI_PROT_PRIV */
#define NIC_TXE_WQE_FETCH_AXI_PROT_PRIV_VAL_S 0
#define NIC_TXE_WQE_FETCH_AXI_PROT_PRIV_VAL_M 0x7

/* NIC_TXE_WQE_FETCH_AXI_CACHE */
#define NIC_TXE_WQE_FETCH_AXI_CACHE_VAL_S 0
#define NIC_TXE_WQE_FETCH_AXI_CACHE_VAL_M 0xF

/* NIC_TXE_WQE_FETCH_CFG */
#define NIC_TXE_WQE_FETCH_CFG_COMMON_CRED_NUM_S 0
#define NIC_TXE_WQE_FETCH_CFG_COMMON_CRED_NUM_M 0x7F
#define NIC_TXE_WQE_FETCH_CFG_MAX_LIMIT_S 8
#define NIC_TXE_WQE_FETCH_CFG_MAX_LIMIT_M 0x7F00
#define NIC_TXE_WQE_FETCH_CFG_GUAR_THR_S 16
#define NIC_TXE_WQE_FETCH_CFG_GUAR_THR_M 0x30000

/* NIC_TXE_DATA_FETCH_AXI_PROT_UNSEC */
#define NIC_TXE_DATA_FETCH_AXI_PROT_UNSEC_VAL_S 0
#define NIC_TXE_DATA_FETCH_AXI_PROT_UNSEC_VAL_M 0x7

/* NIC_TXE_DATA_FETCH_AXI_PROT_SEC */
#define NIC_TXE_DATA_FETCH_AXI_PROT_SEC_VAL_S 0
#define NIC_TXE_DATA_FETCH_AXI_PROT_SEC_VAL_M 0x7

/* NIC_TXE_DATA_FETCH_AXI_PROT_PRIV */
#define NIC_TXE_DATA_FETCH_AXI_PROT_PRIV_VAL_S 0
#define NIC_TXE_DATA_FETCH_AXI_PROT_PRIV_VAL_M 0x7

/* NIC_TXE_DATA_FETCH_AXI_CACHE */
#define NIC_TXE_DATA_FETCH_AXI_CACHE_BIT0_S 0
#define NIC_TXE_DATA_FETCH_AXI_CACHE_BIT0_M 0x1
#define NIC_TXE_DATA_FETCH_AXI_CACHE_BIT1_S 1
#define NIC_TXE_DATA_FETCH_AXI_CACHE_BIT1_M 0x2
#define NIC_TXE_DATA_FETCH_AXI_CACHE_BIT3_S 2
#define NIC_TXE_DATA_FETCH_AXI_CACHE_BIT3_M 0x4

#endif /* ASIC_REG_NIC_TXE_MASKS_H_ */
