/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC_TXS_REGS_H_
#define ASIC_REG_NIC_TXS_REGS_H_

/*
 *****************************************
 *   NIC_TXS
 *   (Prototype: NIC_TXS)
 *****************************************
 */

#define mmNIC_TXS_TMR_SCAN_EN 0x0

#define mmNIC_TXS_TICK_WRAP 0x4

#define mmNIC_TXS_SCAN_TIME_COMPARE_0 0x8

#define mmNIC_TXS_SCAN_TIME_COMPARE_1 0xC

#define mmNIC_TXS_SLICE_CREDIT 0x10

#define mmNIC_TXS_SLICE_FORCE_FULL 0x14

#define mmNIC_TXS_FIRST_SCHEDQ_ID 0x18

#define mmNIC_TXS_LAST_SCHEDQ_ID 0x1C

#define mmNIC_TXS_PUSH_MASK 0x20

#define mmNIC_TXS_POP_MASK 0x24

#define mmNIC_TXS_PUSH_RELEASE_INVALIDATE 0x28

#define mmNIC_TXS_POP_RELEASE_INVALIDATE 0x2C

#define mmNIC_TXS_LIST_MEM_READ_MASK 0x30

#define mmNIC_TXS_FIFO_MEM_READ_MASK 0x34

#define mmNIC_TXS_LIST_MEM_WRITE_MASK 0x38

#define mmNIC_TXS_FIFO_MEM_WRITE_MASK 0x3C

#define mmNIC_TXS_BASE_ADDRESS_63_32 0x40

#define mmNIC_TXS_BASE_ADDRESS_31_7 0x44

#define mmNIC_TXS_AXI_PROT 0x4C

#define mmNIC_TXS_RATE_LIMIT 0x50

#define mmNIC_TXS_CACHE_CFG 0x54

#define mmNIC_TXS_SCHEDQ_MEM_INIT 0x58

#define mmNIC_TXS_SCHEDQ_UPDATE_EN 0x5C

#define mmNIC_TXS_SCHEDQ_UPDATE_FIFO 0x60

#define mmNIC_TXS_SCHEDQ_UPDATE_DESC_0 0x64

#define mmNIC_TXS_SCHEDQ_UPDATE_DESC_1 0x68

#define mmNIC_TXS_SCHEDQ_UPDATE_DESC_2 0x6C

#define mmNIC_TXS_SCHEDQ_UPDATE_DESC_3 0x70

#define mmNIC_TXS_SCHEDQ_UPDATE_DESC_4 0x74

#define mmNIC_TXS_SCHEDQ_UPDATE_DESC_5 0x78

#define mmNIC_TXS_SCHEDQ_UPDATE_DESC_6 0x7C

#define mmNIC_TXS_FORCE_HIT_EN 0x80

#define mmNIC_TXS_INVALIDATE_LIST 0x84

#define mmNIC_TXS_INVALIDATE_LIST_STATUS 0x88

#define mmNIC_TXS_INVALIDATE_FREE_LIST 0x8C

#define mmNIC_TXS_INVALIDATE_FREE_LIST_STAT 0x90

#define mmNIC_TXS_PUSH_PREFETCH_EN 0x94

#define mmNIC_TXS_PUSH_RELEASE_EN 0x98

#define mmNIC_TXS_PUSH_LOCK_EN 0x9C

#define mmNIC_TXS_PUSH_PREFETCH_NEXT_EN 0xA0

#define mmNIC_TXS_POP_PREFETCH_EN 0xA4

#define mmNIC_TXS_POP_RELEASE_EN 0xA8

#define mmNIC_TXS_POP_LOCK_EN 0xAC

#define mmNIC_TXS_POP_PREFETCH_NEXT_EN 0xB0

#define mmNIC_TXS_LIST_MASK 0xB4

#define mmNIC_TXS_RELEASE_INCALIDATE 0xB8

#define mmNIC_TXS_BASE_ADDRESS_FREE_LIST_63_32 0xBC

#define mmNIC_TXS_BASE_ADDRESS_FREE_LIST_31_0 0xC0

#define mmNIC_TXS_FREE_LIST_EN 0xC4

#define mmNIC_TXS_PUSH_FORCE_HIT_EN 0xC8

#define mmNIC_TXS_PRODUCER_UPDATE_EN 0xCC

#define mmNIC_TXS_PRODUCER_UPDATE 0xD0

#define mmNIC_TXS_PRIOQ_CREDIT_FORCE 0xD4

#define mmNIC_TXS_PRIOQ_CREDIT_0 0xD8

#define mmNIC_TXS_PRIOQ_CREDIT_1 0xDC

#define mmNIC_TXS_PRIOQ_CREDIT_2 0xE0

#define mmNIC_TXS_PRIOQ_CREDIT_3 0xE4

#define mmNIC_TXS_DBG_COUNT_SELECT0 0xF8

#define mmNIC_TXS_DBG_COUNT_SELECT1 0xFC

#define mmNIC_TXS_DBG_COUNT_SELECT2 0x100

#define mmNIC_TXS_DBG_COUNT_SELECT3 0x104

#define mmNIC_TXS_DBG_COUNT_SELECT4 0x108

#define mmNIC_TXS_DBG_COUNT_SELECT5 0x10C

#define mmNIC_TXS_DBG_COUNT_SELECT6 0x110

#define mmNIC_TXS_DBG_COUNT_SELECT7 0x114

#define mmNIC_TXS_DBG_COUNT_SELECT8 0x118

#define mmNIC_TXS_DBG_COUNT_SELECT9 0x11C

#define mmNIC_TXS_DBG_COUNT_SELECT10 0x120

#define mmNIC_TXS_DBG_COUNT_SELECT11 0x124

#define mmNIC_TXS_IGNORE_BURST_EN 0x140

#define mmNIC_TXS_PRIOQ_IGNORE_BURST_THRESH_0 0x144

#define mmNIC_TXS_PRIOQ_IGNORE_BURST_THRESH_1 0x148

#define mmNIC_TXS_PRIOQ_IGNORE_BURST_THRESH_2 0x14C

#define mmNIC_TXS_PRIOQ_IGNORE_BURST_THRESH_3 0x150

#define mmNIC_TXS_PORT_IGNORE_BURST_THRESH 0x154

#define mmNIC_TXS_RANDOM_PSUH_CFG 0x164

#define mmNIC_TXS_DBG_HW_EVENT_TRIGER 0x168

#define mmNIC_TXS_INTERRUPT_CAUSE 0x16C

#define mmNIC_TXS_INTERRUPT_MASK 0x170

#define mmNIC_TXS_INTERRUPT_CLR 0x174

#define mmNIC_TXS_LOAD_SLICE_HIT_EN 0x178

#define mmNIC_TXS_SLICE_ACTIVE_64_32 0x17C

#define mmNIC_TXS_SLICE_ACTIVE_31_0 0x180

#define mmNIC_TXS_AXI_CACHE 0x184

#define mmNIC_TXS_SLICE_GW_ADDR 0x188

#define mmNIC_TXS_SLICE_GW_DATA 0x18C

#define mmNIC_TXS_SCANNER_CREDIT_EN 0x190

#define mmNIC_TXS_FREE_LIST_PUSH_MASK_EN 0x194

#define mmNIC_TXS_FREE_AEMPTY_THRESHOLD 0x198

#define mmNIC_TXS_AXI2APB 0x210

#define mmNIC_TXS_STATS_CFG 0x220

#define mmNIC_TXS_STATS_TOT_PUSH_REQ 0x230

#define mmNIC_TXS_STATS_TOT_PUSH_RES 0x234

#define mmNIC_TXS_STATS_TOT_SCHED_QP_REQ 0x238

#define mmNIC_TXS_STATS_TOT_SCHED_QP_RES 0x23C

#define mmNIC_TXS_STATS_TOT_RETURN_SLICE 0x240

#define mmNIC_TXS_STATS_WIN_PUSH_REQ 0x250

#define mmNIC_TXS_STATS_WIN_PUSH_RES 0x254

#define mmNIC_TXS_STATS_WIN_SCHED_QP_REQ 0x258

#define mmNIC_TXS_STATS_WIN_SCHED_QP_RES 0x25C

#define mmNIC_TXS_STATS_WIN_RETURN_SLICE 0x260

#define mmNIC_TXS_TX_APB_ADDR_MASK 0x2B0

#define mmNIC_TXS_TX_APB_SPLIT_ADDR0 0x2B4

#define mmNIC_TXS_TX_APB_SPLIT_ADDR1 0x2B8

#define mmNIC_TXS_TX_APB_SPLIT_ADDR2 0x2BC

#define mmNIC_TXS_TX_APB_SPLIT_ADDR3 0x2C0

#define mmNIC_TXS_TX_APB_SPLIT_ADDR4 0x2C4

#define mmNIC_TXS_HW_EVENT_CFG 0x2E0

#define mmNIC_TXS_CHICKEN_BITS 0x2E8

#define mmNIC_TXS_CLK_GATE_CFG 0x2F0

#define mmNIC_TXS_EVICTED_QPS 0x300

#define mmNIC_TXS_PRIO_ARB 0x308

#endif /* ASIC_REG_NIC_TXS_REGS_H_ */
