/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC_MAC_CH_MAC_CH0_REGS_H_
#define ASIC_REG_NIC_MAC_CH_MAC_CH0_REGS_H_

/*
 *****************************************
 *   NIC_MAC_CH_MAC_CH0
 *   (Prototype: NIC_MAC400)
 *****************************************
 */

#define mmNIC_MAC_CH_MAC_CH0_REVISION 0x0

#define mmNIC_MAC_CH_MAC_CH0_SCRATCH 0x4

#define mmNIC_MAC_CH_MAC_CH0_COMMAND_CONFIG 0x8

#define mmNIC_MAC_CH_MAC_CH0_MAC_ADDR_0 0xC

#define mmNIC_MAC_CH_MAC_CH0_MAC_ADDR_1 0x10

#define mmNIC_MAC_CH_MAC_CH0_FRM_LENGTH 0x14

#define mmNIC_MAC_CH_MAC_CH0_RX_FIFO_SECTIONS 0x1C

#define mmNIC_MAC_CH_MAC_CH0_TX_FIFO_SECTIONS 0x20

#define mmNIC_MAC_CH_MAC_CH0_HASHTABLE_LOAD 0x2C

#define mmNIC_MAC_CH_MAC_CH0_MDIO_CFG_STATUS 0x30

#define mmNIC_MAC_CH_MAC_CH0_MDIO_COMMAND 0x34

#define mmNIC_MAC_CH_MAC_CH0_MDIO_DATA 0x38

#define mmNIC_MAC_CH_MAC_CH0_MDIO_REGADDR 0x3C

#define mmNIC_MAC_CH_MAC_CH0_STATUS 0x40

#define mmNIC_MAC_CH_MAC_CH0_TX_IPG_LENGTH 0x44

#define mmNIC_MAC_CH_MAC_CH0_CRC_INV_MASK 0x4C

#define mmNIC_MAC_CH_MAC_CH0_CL01_PAUSE_QUANTA 0x54

#define mmNIC_MAC_CH_MAC_CH0_CL23_PAUSE_QUANTA 0x58

#define mmNIC_MAC_CH_MAC_CH0_CL45_PAUSE_QUANTA 0x5C

#define mmNIC_MAC_CH_MAC_CH0_CL67_PAUSE_QUANTA 0x60

#define mmNIC_MAC_CH_MAC_CH0_CL01_QUANTA_THRESH 0x64

#define mmNIC_MAC_CH_MAC_CH0_CL23_QUANTA_THRESH 0x68

#define mmNIC_MAC_CH_MAC_CH0_CL45_QUANTA_THRESH 0x6C

#define mmNIC_MAC_CH_MAC_CH0_CL67_QUANTA_THRESH 0x70

#define mmNIC_MAC_CH_MAC_CH0_RX_PAUSE_STATUS 0x74

#define mmNIC_MAC_CH_MAC_CH0_TS_TIMESTAMP 0x7C

#define mmNIC_MAC_CH_MAC_CH0_XIF_MODE 0x80

#define mmNIC_MAC_CH_MAC_CH0_AFRAMESTRANSMITTEDOK 0x100

#define mmNIC_MAC_CH_MAC_CH0_AFRAMESTRANSMITTEDOK_H 0x104

#define mmNIC_MAC_CH_MAC_CH0_AFRAMESRECEIVEDOK 0x108

#define mmNIC_MAC_CH_MAC_CH0_AFRAMESRECEIVEDOK_H 0x10C

#define mmNIC_MAC_CH_MAC_CH0_AFRAMECHECKSEQUENCEERRORS 0x110

#define mmNIC_MAC_CH_MAC_CH0_AFRAMECHECKSEQUENCEERRORS_H 0x114

#define mmNIC_MAC_CH_MAC_CH0_AALIGNMENTERRORS 0x118

#define mmNIC_MAC_CH_MAC_CH0_AALIGNMENTERRORS_H 0x11C

#define mmNIC_MAC_CH_MAC_CH0_APAUSEMACCTRLFRAMESTRANSMITTED 0x120

#define mmNIC_MAC_CH_MAC_CH0_APAUSEMACCTRLFRAMESTRANSMITTED_H 0x124

#define mmNIC_MAC_CH_MAC_CH0_APAUSEMACCTRLFRAMESRECEIVED 0x128

#define mmNIC_MAC_CH_MAC_CH0_APAUSEMACCTRLFRAMESRECEIVED_H 0x12C

#define mmNIC_MAC_CH_MAC_CH0_AFRAMETOOLONGERRORS 0x130

#define mmNIC_MAC_CH_MAC_CH0_AFRAMETOOLONGERRORS_H 0x134

#define mmNIC_MAC_CH_MAC_CH0_AINRANGELENGTHERRORS 0x138

#define mmNIC_MAC_CH_MAC_CH0_AINRANGELENGTHERRORS_H 0x13C

#define mmNIC_MAC_CH_MAC_CH0_VLANTRANSMITTEDOK 0x140

#define mmNIC_MAC_CH_MAC_CH0_VLANTRANSMITTEDOK_H 0x144

#define mmNIC_MAC_CH_MAC_CH0_VLANRECEIVEDOK 0x148

#define mmNIC_MAC_CH_MAC_CH0_VLANRECEIVEDOK_H 0x14C

#define mmNIC_MAC_CH_MAC_CH0_IFOUTOCTETS 0x150

#define mmNIC_MAC_CH_MAC_CH0_IFOUTOCTETS_H 0x154

#define mmNIC_MAC_CH_MAC_CH0_IFINOCTETS 0x158

#define mmNIC_MAC_CH_MAC_CH0_IFINOCTETS_H 0x15C

#define mmNIC_MAC_CH_MAC_CH0_IFINUCASTPKTS 0x160

#define mmNIC_MAC_CH_MAC_CH0_IFINUCASTPKTS_H 0x164

#define mmNIC_MAC_CH_MAC_CH0_IFINMULTICASTPKTS 0x168

#define mmNIC_MAC_CH_MAC_CH0_IFINMULTICASTPKTS_H 0x16C

#define mmNIC_MAC_CH_MAC_CH0_IFINBROADCASTPKTS 0x170

#define mmNIC_MAC_CH_MAC_CH0_IFINBROADCASTPKTS_H 0x174

#define mmNIC_MAC_CH_MAC_CH0_IFOUTERRORS 0x178

#define mmNIC_MAC_CH_MAC_CH0_IFOUTERRORS_H 0x17C

#define mmNIC_MAC_CH_MAC_CH0_IFOUTUCASTPKTS 0x188

#define mmNIC_MAC_CH_MAC_CH0_IFOUTUCASTPKTS_H 0x18C

#define mmNIC_MAC_CH_MAC_CH0_IFOUTMULTICASTPKTS 0x190

#define mmNIC_MAC_CH_MAC_CH0_IFOUTMULTICASTPKTS_H 0x194

#define mmNIC_MAC_CH_MAC_CH0_IFOUTBROADCASTPKTS 0x198

#define mmNIC_MAC_CH_MAC_CH0_IFOUTBROADCASTPKTS_H 0x19C

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSDROPEVENTS 0x1A0

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSDROPEVENTS_H 0x1A4

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSOCTETS 0x1A8

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSOCTETS_H 0x1AC

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS 0x1B0

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS_H 0x1B4

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSUNDERSIZEPKTS 0x1B8

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSUNDERSIZEPKTS_H 0x1BC

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS64OCTETS 0x1C0

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS64OCTETS_H 0x1C4

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS65TO127OCTETS 0x1C8

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS65TO127OCTETS_H 0x1CC

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS128TO255OCTETS 0x1D0

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS128TO255OCTETS_H 0x1D4

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS256TO511OCTETS 0x1D8

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS256TO511OCTETS_H 0x1DC

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS512TO1023OCTETS 0x1E0

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS512TO1023OCTETS_H 0x1E4

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS1024TO1518OCTETS 0x1E8

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS1024TO1518OCTETS_H 0x1EC

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS1519TOMAXOCTETS 0x1F0

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSPKTS1519TOMAXOCTETS_H 0x1F4

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSOVERSIZEPKTS 0x1F8

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSOVERSIZEPKTS_H 0x1FC

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSJABBERS 0x200

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSJABBERS_H 0x204

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSFRAGMENTS 0x208

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSFRAGMENTS_H 0x20C

#define mmNIC_MAC_CH_MAC_CH0_IFINERRORS 0x210

#define mmNIC_MAC_CH_MAC_CH0_IFINERRORS_H 0x214

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_0 0x218

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_0_H 0x21C

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_1 0x220

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_1_H 0x224

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_2 0x228

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_2_H 0x22C

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_3 0x230

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_3_H 0x234

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_4 0x238

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_4_H 0x23C

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_5 0x240

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_5_H 0x244

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_6 0x248

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_6_H 0x24C

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_7 0x250

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESTRANSMITTED_7_H 0x254

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_0 0x258

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_0_H 0x25C

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_1 0x260

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_1_H 0x264

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_2 0x268

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_2_H 0x26C

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_3 0x270

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_3_H 0x274

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_4 0x278

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_4_H 0x27C

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_5 0x280

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_5_H 0x284

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_6 0x288

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_6_H 0x28C

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_7 0x290

#define mmNIC_MAC_CH_MAC_CH0_ACBFCPAUSEFRAMESRECEIVED_7_H 0x294

#define mmNIC_MAC_CH_MAC_CH0_AMACCONTROLFRAMESTRANSMITTED 0x298

#define mmNIC_MAC_CH_MAC_CH0_AMACCONTROLFRAMESTRANSMITTED_H 0x29C

#define mmNIC_MAC_CH_MAC_CH0_AMACCONTROLFRAMESRECEIVED 0x2A0

#define mmNIC_MAC_CH_MAC_CH0_AMACCONTROLFRAMESRECEIVED_H 0x2A4

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXOCTETS 0x2A8

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXOCTETS_H 0x2AC

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS 0x2B0

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS_H 0x2B4

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS64 0x2B8

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS64_H 0x2BC

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS65 0x2C0

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS65_H 0x2C4

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS128 0x2C8

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS128_H 0x2CC

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS256 0x2D0

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS256_H 0x2D4

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS512 0x2D8

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS512_H 0x2DC

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS1024 0x2E0

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS1024_H 0x2E4

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS1519 0x2E8

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXPKTS1519_H 0x2EC

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXOVERSIZEPKTS 0x2F0

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXOVERSIZEPKTS_H 0x2F4

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXJABBERS 0x2F8

#define mmNIC_MAC_CH_MAC_CH0_ETHERSTATSTXJABBERS_H 0x2FC

#endif /* ASIC_REG_NIC_MAC_CH_MAC_CH0_REGS_H_ */
