/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC_TXS_MASKS_H_
#define ASIC_REG_NIC_TXS_MASKS_H_

/*
 *****************************************
 *   NIC_TXS
 *   (Prototype: NIC_TXS)
 *****************************************
 */

/* NIC_TXS_TMR_SCAN_EN */
#define NIC_TXS_TMR_SCAN_EN_R_S 0
#define NIC_TXS_TMR_SCAN_EN_R_M 0x1

/* NIC_TXS_TICK_WRAP */
#define NIC_TXS_TICK_WRAP_R_S 0
#define NIC_TXS_TICK_WRAP_R_M 0xFFFF

/* NIC_TXS_SCAN_TIME_COMPARE_0 */
#define NIC_TXS_SCAN_TIME_COMPARE_0_R_S 0
#define NIC_TXS_SCAN_TIME_COMPARE_0_R_M 0xFFFFFFFF

/* NIC_TXS_SCAN_TIME_COMPARE_1 */
#define NIC_TXS_SCAN_TIME_COMPARE_1_R_S 0
#define NIC_TXS_SCAN_TIME_COMPARE_1_R_M 0xFFFF

/* NIC_TXS_SLICE_CREDIT */
#define NIC_TXS_SLICE_CREDIT_R_S 0
#define NIC_TXS_SLICE_CREDIT_R_M 0x3F

/* NIC_TXS_SLICE_FORCE_FULL */
#define NIC_TXS_SLICE_FORCE_FULL_R_S 0
#define NIC_TXS_SLICE_FORCE_FULL_R_M 0x1

/* NIC_TXS_FIRST_SCHEDQ_ID */
#define NIC_TXS_FIRST_SCHEDQ_ID_R0_S 0
#define NIC_TXS_FIRST_SCHEDQ_ID_R0_M 0x3F
#define NIC_TXS_FIRST_SCHEDQ_ID_R1_S 8
#define NIC_TXS_FIRST_SCHEDQ_ID_R1_M 0x3F00
#define NIC_TXS_FIRST_SCHEDQ_ID_R2_S 16
#define NIC_TXS_FIRST_SCHEDQ_ID_R2_M 0x3F0000
#define NIC_TXS_FIRST_SCHEDQ_ID_R3_S 24
#define NIC_TXS_FIRST_SCHEDQ_ID_R3_M 0x3F000000

/* NIC_TXS_LAST_SCHEDQ_ID */
#define NIC_TXS_LAST_SCHEDQ_ID_R0_S 0
#define NIC_TXS_LAST_SCHEDQ_ID_R0_M 0x3F
#define NIC_TXS_LAST_SCHEDQ_ID_R1_S 8
#define NIC_TXS_LAST_SCHEDQ_ID_R1_M 0x3F00
#define NIC_TXS_LAST_SCHEDQ_ID_R2_S 16
#define NIC_TXS_LAST_SCHEDQ_ID_R2_M 0x3F0000
#define NIC_TXS_LAST_SCHEDQ_ID_R3_S 24
#define NIC_TXS_LAST_SCHEDQ_ID_R3_M 0x3F000000

/* NIC_TXS_PUSH_MASK */
#define NIC_TXS_PUSH_MASK_R_S 0
#define NIC_TXS_PUSH_MASK_R_M 0x1

/* NIC_TXS_POP_MASK */
#define NIC_TXS_POP_MASK_R_S 0
#define NIC_TXS_POP_MASK_R_M 0x1

/* NIC_TXS_PUSH_RELEASE_INVALIDATE */
#define NIC_TXS_PUSH_RELEASE_INVALIDATE_R_S 0
#define NIC_TXS_PUSH_RELEASE_INVALIDATE_R_M 0x1

/* NIC_TXS_POP_RELEASE_INVALIDATE */
#define NIC_TXS_POP_RELEASE_INVALIDATE_R_S 0
#define NIC_TXS_POP_RELEASE_INVALIDATE_R_M 0x1

/* NIC_TXS_LIST_MEM_READ_MASK */
#define NIC_TXS_LIST_MEM_READ_MASK_R_S 0
#define NIC_TXS_LIST_MEM_READ_MASK_R_M 0x1

/* NIC_TXS_FIFO_MEM_READ_MASK */
#define NIC_TXS_FIFO_MEM_READ_MASK_R_S 0
#define NIC_TXS_FIFO_MEM_READ_MASK_R_M 0x1

/* NIC_TXS_LIST_MEM_WRITE_MASK */
#define NIC_TXS_LIST_MEM_WRITE_MASK_R_S 0
#define NIC_TXS_LIST_MEM_WRITE_MASK_R_M 0x1

/* NIC_TXS_FIFO_MEM_WRITE_MASK */
#define NIC_TXS_FIFO_MEM_WRITE_MASK_R_S 0
#define NIC_TXS_FIFO_MEM_WRITE_MASK_R_M 0x1

/* NIC_TXS_BASE_ADDRESS_63_32 */
#define NIC_TXS_BASE_ADDRESS_63_32_R_S 0
#define NIC_TXS_BASE_ADDRESS_63_32_R_M 0xFFFFFFFF

/* NIC_TXS_BASE_ADDRESS_31_7 */
#define NIC_TXS_BASE_ADDRESS_31_7_R_S 0
#define NIC_TXS_BASE_ADDRESS_31_7_R_M 0x1FFFFFF

/* NIC_TXS_AXI_PROT */
#define NIC_TXS_AXI_PROT_R_S 0
#define NIC_TXS_AXI_PROT_R_M 0x7

/* NIC_TXS_RATE_LIMIT */
#define NIC_TXS_RATE_LIMIT_ALWAYS_EN_S 0
#define NIC_TXS_RATE_LIMIT_ALWAYS_EN_M 0x1
#define NIC_TXS_RATE_LIMIT_IMMEDIATE_SET_S 1
#define NIC_TXS_RATE_LIMIT_IMMEDIATE_SET_M 0x2

/* NIC_TXS_CACHE_CFG */
#define NIC_TXS_CACHE_CFG_LIST_PLRU_EVICTION_S 0
#define NIC_TXS_CACHE_CFG_LIST_PLRU_EVICTION_M 0x1
#define NIC_TXS_CACHE_CFG_LIST_CACHE_STOP_S 1
#define NIC_TXS_CACHE_CFG_LIST_CACHE_STOP_M 0x2
#define NIC_TXS_CACHE_CFG_LIST_INV_WRITEBACK_S 2
#define NIC_TXS_CACHE_CFG_LIST_INV_WRITEBACK_M 0x4
#define NIC_TXS_CACHE_CFG_FREE_LIST_PLRU_EVICTION_S 3
#define NIC_TXS_CACHE_CFG_FREE_LIST_PLRU_EVICTION_M 0x8
#define NIC_TXS_CACHE_CFG_FREE_LIST_CACHE_STOP_S 4
#define NIC_TXS_CACHE_CFG_FREE_LIST_CACHE_STOP_M 0x10
#define NIC_TXS_CACHE_CFG_FREE_LIST_INV_WRITEBACK_S 5
#define NIC_TXS_CACHE_CFG_FREE_LIST_INV_WRITEBACK_M 0x20

/* NIC_TXS_SCHEDQ_MEM_INIT */
#define NIC_TXS_SCHEDQ_MEM_INIT_SCHED_MEM_INIT_SC_S 0
#define NIC_TXS_SCHEDQ_MEM_INIT_SCHED_MEM_INIT_SC_M 0x7
#define NIC_TXS_SCHEDQ_MEM_INIT_TMR_MEM_INIT_SC_S 4
#define NIC_TXS_SCHEDQ_MEM_INIT_TMR_MEM_INIT_SC_M 0xF0
#define NIC_TXS_SCHEDQ_MEM_INIT_SCHED_MEM_INIT_BUSY_S 8
#define NIC_TXS_SCHEDQ_MEM_INIT_SCHED_MEM_INIT_BUSY_M 0x700
#define NIC_TXS_SCHEDQ_MEM_INIT_TMR_MEM_INIT_BUSY_S 12
#define NIC_TXS_SCHEDQ_MEM_INIT_TMR_MEM_INIT_BUSY_M 0xF000

/* NIC_TXS_SCHEDQ_UPDATE_EN */
#define NIC_TXS_SCHEDQ_UPDATE_EN_R_S 0
#define NIC_TXS_SCHEDQ_UPDATE_EN_R_M 0x1

/* NIC_TXS_SCHEDQ_UPDATE_FIFO */
#define NIC_TXS_SCHEDQ_UPDATE_FIFO_R_S 0
#define NIC_TXS_SCHEDQ_UPDATE_FIFO_R_M 0xFF

/* NIC_TXS_SCHEDQ_UPDATE_DESC_0 */
#define NIC_TXS_SCHEDQ_UPDATE_DESC_0_R_S 0
#define NIC_TXS_SCHEDQ_UPDATE_DESC_0_R_M 0xFFFFFFFF

/* NIC_TXS_SCHEDQ_UPDATE_DESC_1 */
#define NIC_TXS_SCHEDQ_UPDATE_DESC_1_R_S 0
#define NIC_TXS_SCHEDQ_UPDATE_DESC_1_R_M 0xFFFFFFFF

/* NIC_TXS_SCHEDQ_UPDATE_DESC_2 */
#define NIC_TXS_SCHEDQ_UPDATE_DESC_2_R_S 0
#define NIC_TXS_SCHEDQ_UPDATE_DESC_2_R_M 0xFFFFFFFF

/* NIC_TXS_SCHEDQ_UPDATE_DESC_3 */
#define NIC_TXS_SCHEDQ_UPDATE_DESC_3_R_S 0
#define NIC_TXS_SCHEDQ_UPDATE_DESC_3_R_M 0xFFFFFFFF

/* NIC_TXS_SCHEDQ_UPDATE_DESC_4 */
#define NIC_TXS_SCHEDQ_UPDATE_DESC_4_R_S 0
#define NIC_TXS_SCHEDQ_UPDATE_DESC_4_R_M 0xFFFFFFFF

/* NIC_TXS_SCHEDQ_UPDATE_DESC_5 */
#define NIC_TXS_SCHEDQ_UPDATE_DESC_5_R_S 0
#define NIC_TXS_SCHEDQ_UPDATE_DESC_5_R_M 0xFFFFFFFF

/* NIC_TXS_SCHEDQ_UPDATE_DESC_6 */
#define NIC_TXS_SCHEDQ_UPDATE_DESC_6_R_S 0
#define NIC_TXS_SCHEDQ_UPDATE_DESC_6_R_M 0x3FFFFFF

/* NIC_TXS_FORCE_HIT_EN */
#define NIC_TXS_FORCE_HIT_EN_R_S 0
#define NIC_TXS_FORCE_HIT_EN_R_M 0x1

/* NIC_TXS_INVALIDATE_LIST */

/* NIC_TXS_INVALIDATE_LIST_STATUS */
#define NIC_TXS_INVALIDATE_LIST_STATUS_INVALIDATE_DONE_S 0
#define NIC_TXS_INVALIDATE_LIST_STATUS_INVALIDATE_DONE_M 0x1
#define NIC_TXS_INVALIDATE_LIST_STATUS_CACHE_IDLE_S 1
#define NIC_TXS_INVALIDATE_LIST_STATUS_CACHE_IDLE_M 0x2

/* NIC_TXS_INVALIDATE_FREE_LIST */

/* NIC_TXS_INVALIDATE_FREE_LIST_STAT */
#define NIC_TXS_INVALIDATE_FREE_LIST_STAT_INVALIDATE_DONE_S 0
#define NIC_TXS_INVALIDATE_FREE_LIST_STAT_INVALIDATE_DONE_M 0x1
#define NIC_TXS_INVALIDATE_FREE_LIST_STAT_CACHE_IDLE_S 1
#define NIC_TXS_INVALIDATE_FREE_LIST_STAT_CACHE_IDLE_M 0x2

/* NIC_TXS_PUSH_PREFETCH_EN */
#define NIC_TXS_PUSH_PREFETCH_EN_R_S 0
#define NIC_TXS_PUSH_PREFETCH_EN_R_M 0x1

/* NIC_TXS_PUSH_RELEASE_EN */
#define NIC_TXS_PUSH_RELEASE_EN_R_S 0
#define NIC_TXS_PUSH_RELEASE_EN_R_M 0x1

/* NIC_TXS_PUSH_LOCK_EN */
#define NIC_TXS_PUSH_LOCK_EN_R_S 0
#define NIC_TXS_PUSH_LOCK_EN_R_M 0x1

/* NIC_TXS_PUSH_PREFETCH_NEXT_EN */
#define NIC_TXS_PUSH_PREFETCH_NEXT_EN_R_S 0
#define NIC_TXS_PUSH_PREFETCH_NEXT_EN_R_M 0x1

/* NIC_TXS_POP_PREFETCH_EN */
#define NIC_TXS_POP_PREFETCH_EN_R_S 0
#define NIC_TXS_POP_PREFETCH_EN_R_M 0x1

/* NIC_TXS_POP_RELEASE_EN */
#define NIC_TXS_POP_RELEASE_EN_R_S 0
#define NIC_TXS_POP_RELEASE_EN_R_M 0x1

/* NIC_TXS_POP_LOCK_EN */
#define NIC_TXS_POP_LOCK_EN_R_S 0
#define NIC_TXS_POP_LOCK_EN_R_M 0x1

/* NIC_TXS_POP_PREFETCH_NEXT_EN */
#define NIC_TXS_POP_PREFETCH_NEXT_EN_R_S 0
#define NIC_TXS_POP_PREFETCH_NEXT_EN_R_M 0x1

/* NIC_TXS_LIST_MASK */
#define NIC_TXS_LIST_MASK_R_S 0
#define NIC_TXS_LIST_MASK_R_M 0x7FFFFFF

/* NIC_TXS_RELEASE_INCALIDATE */
#define NIC_TXS_RELEASE_INCALIDATE_R_S 0
#define NIC_TXS_RELEASE_INCALIDATE_R_M 0x1

/* NIC_TXS_BASE_ADDRESS_FREE_LIST_63_32 */
#define NIC_TXS_BASE_ADDRESS_FREE_LIST_63_32_R_S 0
#define NIC_TXS_BASE_ADDRESS_FREE_LIST_63_32_R_M 0xFFFFFFFF

/* NIC_TXS_BASE_ADDRESS_FREE_LIST_31_0 */
#define NIC_TXS_BASE_ADDRESS_FREE_LIST_31_0_R_S 0
#define NIC_TXS_BASE_ADDRESS_FREE_LIST_31_0_R_M 0xFFFFFFFF

/* NIC_TXS_FREE_LIST_EN */
#define NIC_TXS_FREE_LIST_EN_R_S 0
#define NIC_TXS_FREE_LIST_EN_R_M 0x1

/* NIC_TXS_PUSH_FORCE_HIT_EN */
#define NIC_TXS_PUSH_FORCE_HIT_EN_R_S 0
#define NIC_TXS_PUSH_FORCE_HIT_EN_R_M 0x1

/* NIC_TXS_PRODUCER_UPDATE_EN */
#define NIC_TXS_PRODUCER_UPDATE_EN_R_S 0
#define NIC_TXS_PRODUCER_UPDATE_EN_R_M 0x1

/* NIC_TXS_PRODUCER_UPDATE */
#define NIC_TXS_PRODUCER_UPDATE_R_S 0
#define NIC_TXS_PRODUCER_UPDATE_R_M 0xFFFFFFFF

/* NIC_TXS_PRIOQ_CREDIT_FORCE */
#define NIC_TXS_PRIOQ_CREDIT_FORCE_FORCE_FULL_S 0
#define NIC_TXS_PRIOQ_CREDIT_FORCE_FORCE_FULL_M 0xFFFF

/* NIC_TXS_PRIOQ_CREDIT */
#define NIC_TXS_PRIOQ_CREDIT_PR0_S 0
#define NIC_TXS_PRIOQ_CREDIT_PR0_M 0x3F
#define NIC_TXS_PRIOQ_CREDIT_PR1_S 8
#define NIC_TXS_PRIOQ_CREDIT_PR1_M 0x3F00
#define NIC_TXS_PRIOQ_CREDIT_PR2_S 16
#define NIC_TXS_PRIOQ_CREDIT_PR2_M 0x3F0000
#define NIC_TXS_PRIOQ_CREDIT_PR3_S 24
#define NIC_TXS_PRIOQ_CREDIT_PR3_M 0x3F000000

/* NIC_TXS_DBG_COUNT_SELECT0 */
#define NIC_TXS_DBG_COUNT_SELECT0_R_S 0
#define NIC_TXS_DBG_COUNT_SELECT0_R_M 0x3F

/* NIC_TXS_DBG_COUNT_SELECT1 */
#define NIC_TXS_DBG_COUNT_SELECT1_R_S 0
#define NIC_TXS_DBG_COUNT_SELECT1_R_M 0x3F

/* NIC_TXS_DBG_COUNT_SELECT2 */
#define NIC_TXS_DBG_COUNT_SELECT2_R_S 0
#define NIC_TXS_DBG_COUNT_SELECT2_R_M 0x3F

/* NIC_TXS_DBG_COUNT_SELECT3 */
#define NIC_TXS_DBG_COUNT_SELECT3_R_S 0
#define NIC_TXS_DBG_COUNT_SELECT3_R_M 0x3F

/* NIC_TXS_DBG_COUNT_SELECT4 */
#define NIC_TXS_DBG_COUNT_SELECT4_R_S 0
#define NIC_TXS_DBG_COUNT_SELECT4_R_M 0x3F

/* NIC_TXS_DBG_COUNT_SELECT5 */
#define NIC_TXS_DBG_COUNT_SELECT5_R_S 0
#define NIC_TXS_DBG_COUNT_SELECT5_R_M 0x3F

/* NIC_TXS_DBG_COUNT_SELECT6 */
#define NIC_TXS_DBG_COUNT_SELECT6_R_S 0
#define NIC_TXS_DBG_COUNT_SELECT6_R_M 0x3F

/* NIC_TXS_DBG_COUNT_SELECT7 */
#define NIC_TXS_DBG_COUNT_SELECT7_R_S 0
#define NIC_TXS_DBG_COUNT_SELECT7_R_M 0x3F

/* NIC_TXS_DBG_COUNT_SELECT8 */
#define NIC_TXS_DBG_COUNT_SELECT8_R_S 0
#define NIC_TXS_DBG_COUNT_SELECT8_R_M 0x3F

/* NIC_TXS_DBG_COUNT_SELECT9 */
#define NIC_TXS_DBG_COUNT_SELECT9_R_S 0
#define NIC_TXS_DBG_COUNT_SELECT9_R_M 0x3F

/* NIC_TXS_DBG_COUNT_SELECT10 */
#define NIC_TXS_DBG_COUNT_SELECT10_R_S 0
#define NIC_TXS_DBG_COUNT_SELECT10_R_M 0x3F

/* NIC_TXS_DBG_COUNT_SELECT11 */
#define NIC_TXS_DBG_COUNT_SELECT11_R_S 0
#define NIC_TXS_DBG_COUNT_SELECT11_R_M 0x3F

/* NIC_TXS_IGNORE_BURST_EN */
#define NIC_TXS_IGNORE_BURST_EN_R_S 0
#define NIC_TXS_IGNORE_BURST_EN_R_M 0xFFFF

/* NIC_TXS_PRIOQ_IGNORE_BURST_THRESH */
#define NIC_TXS_PRIOQ_IGNORE_BURST_THRESH_PRIO0_S 0
#define NIC_TXS_PRIOQ_IGNORE_BURST_THRESH_PRIO0_M 0xFF
#define NIC_TXS_PRIOQ_IGNORE_BURST_THRESH_PRIO1_S 8
#define NIC_TXS_PRIOQ_IGNORE_BURST_THRESH_PRIO1_M 0xFF00
#define NIC_TXS_PRIOQ_IGNORE_BURST_THRESH_PRIO2_S 16
#define NIC_TXS_PRIOQ_IGNORE_BURST_THRESH_PRIO2_M 0xFF0000
#define NIC_TXS_PRIOQ_IGNORE_BURST_THRESH_PRIO3_S 24
#define NIC_TXS_PRIOQ_IGNORE_BURST_THRESH_PRIO3_M 0xFF000000

/* NIC_TXS_PORT_IGNORE_BURST_THRESH */
#define NIC_TXS_PORT_IGNORE_BURST_THRESH_PORT0_S 0
#define NIC_TXS_PORT_IGNORE_BURST_THRESH_PORT0_M 0xFF
#define NIC_TXS_PORT_IGNORE_BURST_THRESH_PORT1_S 8
#define NIC_TXS_PORT_IGNORE_BURST_THRESH_PORT1_M 0xFF00
#define NIC_TXS_PORT_IGNORE_BURST_THRESH_PORT2_S 16
#define NIC_TXS_PORT_IGNORE_BURST_THRESH_PORT2_M 0xFF0000
#define NIC_TXS_PORT_IGNORE_BURST_THRESH_PORT3_S 24
#define NIC_TXS_PORT_IGNORE_BURST_THRESH_PORT3_M 0xFF000000

/* NIC_TXS_RANDOM_PSUH_CFG */
#define NIC_TXS_RANDOM_PSUH_CFG_BYPASS_S 0
#define NIC_TXS_RANDOM_PSUH_CFG_BYPASS_M 0x1
#define NIC_TXS_RANDOM_PSUH_CFG_RATE_LIMIT_EN_S 1
#define NIC_TXS_RANDOM_PSUH_CFG_RATE_LIMIT_EN_M 0x2
#define NIC_TXS_RANDOM_PSUH_CFG_SATURATION_S 2
#define NIC_TXS_RANDOM_PSUH_CFG_SATURATION_M 0x3C
#define NIC_TXS_RANDOM_PSUH_CFG_RST_TOKEN_S 6
#define NIC_TXS_RANDOM_PSUH_CFG_RST_TOKEN_M 0x7FFC0
#define NIC_TXS_RANDOM_PSUH_CFG_TIMEOUT_S 19
#define NIC_TXS_RANDOM_PSUH_CFG_TIMEOUT_M 0xFFF80000

/* NIC_TXS_DBG_HW_EVENT_TRIGER */
#define NIC_TXS_DBG_HW_EVENT_TRIGER_R_S 0
#define NIC_TXS_DBG_HW_EVENT_TRIGER_R_M 0xFF

/* NIC_TXS_INTERRUPT_CAUSE */
#define NIC_TXS_INTERRUPT_CAUSE_R_S 0
#define NIC_TXS_INTERRUPT_CAUSE_R_M 0xF

/* NIC_TXS_INTERRUPT_MASK */
#define NIC_TXS_INTERRUPT_MASK_R_S 0
#define NIC_TXS_INTERRUPT_MASK_R_M 0xF

/* NIC_TXS_INTERRUPT_CLR */

/* NIC_TXS_LOAD_SLICE_HIT_EN */
#define NIC_TXS_LOAD_SLICE_HIT_EN_R_S 0
#define NIC_TXS_LOAD_SLICE_HIT_EN_R_M 0x1

/* NIC_TXS_SLICE_ACTIVE_64_32 */
#define NIC_TXS_SLICE_ACTIVE_64_32_R_S 0
#define NIC_TXS_SLICE_ACTIVE_64_32_R_M 0xFFFFFFFF

/* NIC_TXS_SLICE_ACTIVE_31_0 */
#define NIC_TXS_SLICE_ACTIVE_31_0_R_S 0
#define NIC_TXS_SLICE_ACTIVE_31_0_R_M 0xFFFFFFFF

/* NIC_TXS_AXI_CACHE */
#define NIC_TXS_AXI_CACHE_AR_CACHE_S 0
#define NIC_TXS_AXI_CACHE_AR_CACHE_M 0xF
#define NIC_TXS_AXI_CACHE_AW_CACHE_S 4
#define NIC_TXS_AXI_CACHE_AW_CACHE_M 0xF0

/* NIC_TXS_SLICE_GW_ADDR */
#define NIC_TXS_SLICE_GW_ADDR_R_S 0
#define NIC_TXS_SLICE_GW_ADDR_R_M 0x3F

/* NIC_TXS_SLICE_GW_DATA */
#define NIC_TXS_SLICE_GW_DATA_R_S 0
#define NIC_TXS_SLICE_GW_DATA_R_M 0x1FFFFFF

/* NIC_TXS_SCANNER_CREDIT_EN */
#define NIC_TXS_SCANNER_CREDIT_EN_R_S 0
#define NIC_TXS_SCANNER_CREDIT_EN_R_M 0x3

/* NIC_TXS_FREE_LIST_PUSH_MASK_EN */
#define NIC_TXS_FREE_LIST_PUSH_MASK_EN_R_S 0
#define NIC_TXS_FREE_LIST_PUSH_MASK_EN_R_M 0x1

/* NIC_TXS_FREE_AEMPTY_THRESHOLD */
#define NIC_TXS_FREE_AEMPTY_THRESHOLD_R_S 0
#define NIC_TXS_FREE_AEMPTY_THRESHOLD_R_M 0xFFFFFFFF

/* NIC_TXS_AXI2APB */
#define NIC_TXS_AXI2APB_MSK_ERROR_RSP_S 0
#define NIC_TXS_AXI2APB_MSK_ERROR_RSP_M 0x1
#define NIC_TXS_AXI2APB_BLOCK_PARTIAL_STRB_S 1
#define NIC_TXS_AXI2APB_BLOCK_PARTIAL_STRB_M 0x2
#define NIC_TXS_AXI2APB_SPL_ERROR_RSP_S 2
#define NIC_TXS_AXI2APB_SPL_ERROR_RSP_M 0x4

/* NIC_TXS_STATS_CFG */
#define NIC_TXS_STATS_CFG_MEAS_WIN_SIZE_S 0
#define NIC_TXS_STATS_CFG_MEAS_WIN_SIZE_M 0x7FFFFFFF
#define NIC_TXS_STATS_CFG_CLEAR_SC_S 31
#define NIC_TXS_STATS_CFG_CLEAR_SC_M 0x80000000

/* NIC_TXS_STATS_TOT_PUSH_REQ */
#define NIC_TXS_STATS_TOT_PUSH_REQ_R_S 0
#define NIC_TXS_STATS_TOT_PUSH_REQ_R_M 0xFFFFFFFF

/* NIC_TXS_STATS_TOT_PUSH_RES */
#define NIC_TXS_STATS_TOT_PUSH_RES_R_S 0
#define NIC_TXS_STATS_TOT_PUSH_RES_R_M 0xFFFFFFFF

/* NIC_TXS_STATS_TOT_SCHED_QP_REQ */
#define NIC_TXS_STATS_TOT_SCHED_QP_REQ_R_S 0
#define NIC_TXS_STATS_TOT_SCHED_QP_REQ_R_M 0xFFFFFFFF

/* NIC_TXS_STATS_TOT_SCHED_QP_RES */
#define NIC_TXS_STATS_TOT_SCHED_QP_RES_R_S 0
#define NIC_TXS_STATS_TOT_SCHED_QP_RES_R_M 0xFFFFFFFF

/* NIC_TXS_STATS_TOT_RETURN_SLICE */
#define NIC_TXS_STATS_TOT_RETURN_SLICE_R_S 0
#define NIC_TXS_STATS_TOT_RETURN_SLICE_R_M 0xFFFFFFFF

/* NIC_TXS_STATS_WIN_PUSH_REQ */
#define NIC_TXS_STATS_WIN_PUSH_REQ_R_S 0
#define NIC_TXS_STATS_WIN_PUSH_REQ_R_M 0xFFFFFFFF

/* NIC_TXS_STATS_WIN_PUSH_RES */
#define NIC_TXS_STATS_WIN_PUSH_RES_R_S 0
#define NIC_TXS_STATS_WIN_PUSH_RES_R_M 0xFFFFFFFF

/* NIC_TXS_STATS_WIN_SCHED_QP_REQ */
#define NIC_TXS_STATS_WIN_SCHED_QP_REQ_R_S 0
#define NIC_TXS_STATS_WIN_SCHED_QP_REQ_R_M 0xFFFFFFFF

/* NIC_TXS_STATS_WIN_SCHED_QP_RES */
#define NIC_TXS_STATS_WIN_SCHED_QP_RES_R_S 0
#define NIC_TXS_STATS_WIN_SCHED_QP_RES_R_M 0xFFFFFFFF

/* NIC_TXS_STATS_WIN_RETURN_SLICE */
#define NIC_TXS_STATS_WIN_RETURN_SLICE_R_S 0
#define NIC_TXS_STATS_WIN_RETURN_SLICE_R_M 0xFFFFFFFF

/* NIC_TXS_TX_APB_ADDR_MASK */
#define NIC_TXS_TX_APB_ADDR_MASK_R_S 0
#define NIC_TXS_TX_APB_ADDR_MASK_R_M 0xFFFFFFFF

/* NIC_TXS_TX_APB_SPLIT_ADDR0 */
#define NIC_TXS_TX_APB_SPLIT_ADDR0_R_S 0
#define NIC_TXS_TX_APB_SPLIT_ADDR0_R_M 0xFFFFFFFF

/* NIC_TXS_TX_APB_SPLIT_ADDR1 */
#define NIC_TXS_TX_APB_SPLIT_ADDR1_R_S 0
#define NIC_TXS_TX_APB_SPLIT_ADDR1_R_M 0xFFFFFFFF

/* NIC_TXS_TX_APB_SPLIT_ADDR2 */
#define NIC_TXS_TX_APB_SPLIT_ADDR2_R_S 0
#define NIC_TXS_TX_APB_SPLIT_ADDR2_R_M 0xFFFFFFFF

/* NIC_TXS_TX_APB_SPLIT_ADDR3 */
#define NIC_TXS_TX_APB_SPLIT_ADDR3_R_S 0
#define NIC_TXS_TX_APB_SPLIT_ADDR3_R_M 0xFFFFFFFF

/* NIC_TXS_TX_APB_SPLIT_ADDR4 */
#define NIC_TXS_TX_APB_SPLIT_ADDR4_R_S 0
#define NIC_TXS_TX_APB_SPLIT_ADDR4_R_M 0xFFFFFFFF

/* NIC_TXS_HW_EVENT_CFG */
#define NIC_TXS_HW_EVENT_CFG_EVENT_ID_S 0
#define NIC_TXS_HW_EVENT_CFG_EVENT_ID_M 0xFFFF
#define NIC_TXS_HW_EVENT_CFG_DBG_SELECT0_S 16
#define NIC_TXS_HW_EVENT_CFG_DBG_SELECT0_M 0xF0000
#define NIC_TXS_HW_EVENT_CFG_DBG_SELECT1_S 20
#define NIC_TXS_HW_EVENT_CFG_DBG_SELECT1_M 0xF00000
#define NIC_TXS_HW_EVENT_CFG_DBG_SELECT2_S 24
#define NIC_TXS_HW_EVENT_CFG_DBG_SELECT2_M 0xF000000

/* NIC_TXS_CHICKEN_BITS */
#define NIC_TXS_CHICKEN_BITS_R_S 0
#define NIC_TXS_CHICKEN_BITS_R_M 0xFFFFFFFF

/* NIC_TXS_CLK_GATE_CFG */
#define NIC_TXS_CLK_GATE_CFG_CLOSE_DELAY_S 0
#define NIC_TXS_CLK_GATE_CFG_CLOSE_DELAY_M 0xFFFF
#define NIC_TXS_CLK_GATE_CFG_CGM_DIS_S 30
#define NIC_TXS_CLK_GATE_CFG_CGM_DIS_M 0x40000000
#define NIC_TXS_CLK_GATE_CFG_FORCE_OPEN_S 31
#define NIC_TXS_CLK_GATE_CFG_FORCE_OPEN_M 0x80000000

/* NIC_TXS_EVICTED_QPS */
#define NIC_TXS_EVICTED_QPS_IMMEDIATE_SQ_BASE_ADDR_S 0
#define NIC_TXS_EVICTED_QPS_IMMEDIATE_SQ_BASE_ADDR_M 0xF
#define NIC_TXS_EVICTED_QPS_EVICTED_LB_SCHEDQ_S 8
#define NIC_TXS_EVICTED_QPS_EVICTED_LB_SCHEDQ_M 0xFF00
#define NIC_TXS_EVICTED_QPS_EVICTED_IS_IMMEDIATE_S 31
#define NIC_TXS_EVICTED_QPS_EVICTED_IS_IMMEDIATE_M 0x80000000

/* NIC_TXS_PRIO_ARB */
#define NIC_TXS_PRIO_ARB_ABS_EN_S 0
#define NIC_TXS_PRIO_ARB_ABS_EN_M 0x1
#define NIC_TXS_PRIO_ARB_ABS_REVERSED_S 1
#define NIC_TXS_PRIO_ARB_ABS_REVERSED_M 0x2

#endif /* ASIC_REG_NIC_TXS_MASKS_H_ */
