/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC_MAC_GLOB_STAT_TX3_REGS_H_
#define ASIC_REG_NIC_MAC_GLOB_STAT_TX3_REGS_H_

/*
 *****************************************
 *   NIC_MAC_GLOB_STAT_TX3
 *   (Prototype: MAC_MAC3_TX_CNT)
 *****************************************
 */

#define mmNIC_MAC_GLOB_STAT_TX3_ETHERSTATSOCTETS_7 0x0

#define mmNIC_MAC_GLOB_STAT_TX3_OCTETSTRANSMITTEDOK_3 0x4

#define mmNIC_MAC_GLOB_STAT_TX3_APAUSEMACCTRLFRAMESTRANSMITTED_3 0x8

#define mmNIC_MAC_GLOB_STAT_TX3_AFRAMESTRANSMITTEDOK_3 0xC

#define mmNIC_MAC_GLOB_STAT_TX3_VLANTRANSMITTEDOK_3 0x10

#define mmNIC_MAC_GLOB_STAT_TX3_IFOUTERRORS_3 0x14

#define mmNIC_MAC_GLOB_STAT_TX3_IFOUTUCASTPKTS_3 0x18

#define mmNIC_MAC_GLOB_STAT_TX3_IFOUTMULTICASTPKTS_3 0x1C

#define mmNIC_MAC_GLOB_STAT_TX3_IFOUTBROADCASTPKTS_3 0x20

#define mmNIC_MAC_GLOB_STAT_TX3_ETHERSTATSPKTS64OCTETS_7 0x24

#define mmNIC_MAC_GLOB_STAT_TX3_ETHERSTATSPKTS65TO127OCTETS_7 0x28

#define mmNIC_MAC_GLOB_STAT_TX3_ETHERSTATSPKTS128TO255OCTETS_7 0x2C

#define mmNIC_MAC_GLOB_STAT_TX3_ETHERSTATSPKTS256TO511OCTETS_7 0x30

#define mmNIC_MAC_GLOB_STAT_TX3_ETHERSTATSPKTS512TO1023OCTETS_7 0x34

#define mmNIC_MAC_GLOB_STAT_TX3_ETHERSTATSPKTS1024TO1518OCTETS_7 0x38

#define mmNIC_MAC_GLOB_STAT_TX3_ETHERSTATSPKTS1519TOMAXOCTETS_7 0x3C

#define mmNIC_MAC_GLOB_STAT_TX3_ACBFCPAUSEFRAMESTRANSMITTED0_3 0x40

#define mmNIC_MAC_GLOB_STAT_TX3_ACBFCPAUSEFRAMESTRANSMITTED1_3 0x44

#define mmNIC_MAC_GLOB_STAT_TX3_ACBFCPAUSEFRAMESTRANSMITTED2_3 0x48

#define mmNIC_MAC_GLOB_STAT_TX3_ACBFCPAUSEFRAMESTRANSMITTED3_3 0x4C

#define mmNIC_MAC_GLOB_STAT_TX3_ACBFCPAUSEFRAMESTRANSMITTED4_3 0x50

#define mmNIC_MAC_GLOB_STAT_TX3_ACBFCPAUSEFRAMESTRANSMITTED5_3 0x54

#define mmNIC_MAC_GLOB_STAT_TX3_ACBFCPAUSEFRAMESTRANSMITTED6_3 0x58

#define mmNIC_MAC_GLOB_STAT_TX3_ACBFCPAUSEFRAMESTRANSMITTED7_3 0x5C

#define mmNIC_MAC_GLOB_STAT_TX3_AMACCONTROLFRAMESTRANSMITTED_3 0x60

#define mmNIC_MAC_GLOB_STAT_TX3_ETHERSTATSPKTS_7 0x64

#endif /* ASIC_REG_NIC_MAC_GLOB_STAT_TX3_REGS_H_ */
