/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PCIE_WRAP_DBI_ACCESS_MASKS_H_
#define ASIC_REG_PCIE_WRAP_DBI_ACCESS_MASKS_H_

/*
 *****************************************
 *   PCIE_WRAP_DBI_ACCESS
 *   (Prototype: PCIE_DBI_ACCESS)
 *****************************************
 */

/* PCIE_WRAP_DBI_ACCESS_MSIX_GLBL_CNT */
#define PCIE_WRAP_DBI_ACCESS_MSIX_GLBL_CNT_V_S 0
#define PCIE_WRAP_DBI_ACCESS_MSIX_GLBL_CNT_V_M 0xFFFFFFFF

/* PCIE_WRAP_DBI_ACCESS_MSIX_DOORBELL_OFF_ADDR */
#define PCIE_WRAP_DBI_ACCESS_MSIX_DOORBELL_OFF_ADDR_ADDR_S 0
#define PCIE_WRAP_DBI_ACCESS_MSIX_DOORBELL_OFF_ADDR_ADDR_M 0xFFFFFFFF

/* PCIE_WRAP_DBI_ACCESS_MSIX_MASK_CTRL */
#define PCIE_WRAP_DBI_ACCESS_MSIX_MASK_CTRL_EN_S 0
#define PCIE_WRAP_DBI_ACCESS_MSIX_MASK_CTRL_EN_M 0x1
#define PCIE_WRAP_DBI_ACCESS_MSIX_MASK_CTRL_RESP_S 1
#define PCIE_WRAP_DBI_ACCESS_MSIX_MASK_CTRL_RESP_M 0x2

/* PCIE_WRAP_DBI_ACCESS_MSIX_GW */
#define PCIE_WRAP_DBI_ACCESS_MSIX_GW_EN_S 0
#define PCIE_WRAP_DBI_ACCESS_MSIX_GW_EN_M 0x1
#define PCIE_WRAP_DBI_ACCESS_MSIX_GW_INTR_MASK_S 1
#define PCIE_WRAP_DBI_ACCESS_MSIX_GW_INTR_MASK_M 0x2
#define PCIE_WRAP_DBI_ACCESS_MSIX_GW_ERR_RESP_S 2
#define PCIE_WRAP_DBI_ACCESS_MSIX_GW_ERR_RESP_M 0x4

/* PCIE_WRAP_DBI_ACCESS_MSIX_GW_VEC */
#define PCIE_WRAP_DBI_ACCESS_MSIX_GW_VEC_VAL_S 0
#define PCIE_WRAP_DBI_ACCESS_MSIX_GW_VEC_VAL_M 0xFFFFFFFF

/* PCIE_WRAP_DBI_ACCESS_MSIX_GW_INTR */
#define PCIE_WRAP_DBI_ACCESS_MSIX_GW_INTR_INTR_S 0
#define PCIE_WRAP_DBI_ACCESS_MSIX_GW_INTR_INTR_M 0x1

/* PCIE_WRAP_DBI_ACCESS_MSIX_GW_TABLE */
#define PCIE_WRAP_DBI_ACCESS_MSIX_GW_TABLE_VAL_S 0
#define PCIE_WRAP_DBI_ACCESS_MSIX_GW_TABLE_VAL_M 0xFFFFFFFF

/* PCIE_WRAP_DBI_ACCESS_MSIX_PROT */
#define PCIE_WRAP_DBI_ACCESS_MSIX_PROT_VAL_S 0
#define PCIE_WRAP_DBI_ACCESS_MSIX_PROT_VAL_M 0x7

/* PCIE_WRAP_DBI_ACCESS_DBI_GW_M0_ADDR_OVERIDE_DATA */
#define PCIE_WRAP_DBI_ACCESS_DBI_GW_M0_ADDR_OVERIDE_DATA_DATA_S 0
#define PCIE_WRAP_DBI_ACCESS_DBI_GW_M0_ADDR_OVERIDE_DATA_DATA_M 0xFFFFFFFF

/* PCIE_WRAP_DBI_ACCESS_CS2_ADDR_M0_OVERIDE_ADDR */
#define PCIE_WRAP_DBI_ACCESS_CS2_ADDR_M0_OVERIDE_ADDR_VAL_S 0
#define PCIE_WRAP_DBI_ACCESS_CS2_ADDR_M0_OVERIDE_ADDR_VAL_M 0xFFFFFFFF

/* PCIE_WRAP_DBI_ACCESS_DBI_GW_BYPASS */
#define PCIE_WRAP_DBI_ACCESS_DBI_GW_BYPASS_VAL_S 0
#define PCIE_WRAP_DBI_ACCESS_DBI_GW_BYPASS_VAL_M 0x1

/* PCIE_WRAP_DBI_ACCESS_DBI_GW_M1_ADDR_OVERIDE_DATA */
#define PCIE_WRAP_DBI_ACCESS_DBI_GW_M1_ADDR_OVERIDE_DATA_VAL_S 0
#define PCIE_WRAP_DBI_ACCESS_DBI_GW_M1_ADDR_OVERIDE_DATA_VAL_M 0xFFFFFFFF

/* PCIE_WRAP_DBI_ACCESS_CS2_ADDR_M1_OVERIDE_ADDR */
#define PCIE_WRAP_DBI_ACCESS_CS2_ADDR_M1_OVERIDE_ADDR_VAL_S 0
#define PCIE_WRAP_DBI_ACCESS_CS2_ADDR_M1_OVERIDE_ADDR_VAL_M 0xFFFFFFFF

/* PCIE_WRAP_DBI_ACCESS_MSIX_PSLV_ERR_VAL */
#define PCIE_WRAP_DBI_ACCESS_MSIX_PSLV_ERR_VAL_VAL_S 0
#define PCIE_WRAP_DBI_ACCESS_MSIX_PSLV_ERR_VAL_VAL_M 0x1

/* PCIE_WRAP_DBI_ACCESS_CS2_APB_PPROT_VAL */
#define PCIE_WRAP_DBI_ACCESS_CS2_APB_PPROT_VAL_VAL_S 0
#define PCIE_WRAP_DBI_ACCESS_CS2_APB_PPROT_VAL_VAL_M 0x7

/* PCIE_WRAP_DBI_ACCESS_ACCESS_PROT_MASK */
#define PCIE_WRAP_DBI_ACCESS_ACCESS_PROT_MASK_M0_S 0
#define PCIE_WRAP_DBI_ACCESS_ACCESS_PROT_MASK_M0_M 0x1
#define PCIE_WRAP_DBI_ACCESS_ACCESS_PROT_MASK_M1_S 1
#define PCIE_WRAP_DBI_ACCESS_ACCESS_PROT_MASK_M1_M 0x2

/* PCIE_WRAP_DBI_ACCESS_APB_DBI_GW_ARB_TIMEOUT */
#define PCIE_WRAP_DBI_ACCESS_APB_DBI_GW_ARB_TIMEOUT_NON_BYPASS_S 0
#define PCIE_WRAP_DBI_ACCESS_APB_DBI_GW_ARB_TIMEOUT_NON_BYPASS_M 0xFFFF
#define PCIE_WRAP_DBI_ACCESS_APB_DBI_GW_ARB_TIMEOUT_BYPASS_S 16
#define PCIE_WRAP_DBI_ACCESS_APB_DBI_GW_ARB_TIMEOUT_BYPASS_M 0xFFFF0000

/* PCIE_WRAP_DBI_ACCESS_APB_COAL_ARB_TIMEOUT */
#define PCIE_WRAP_DBI_ACCESS_APB_COAL_ARB_TIMEOUT_MSIX_COAL_S 0
#define PCIE_WRAP_DBI_ACCESS_APB_COAL_ARB_TIMEOUT_MSIX_COAL_M 0xFFFF

#endif /* ASIC_REG_PCIE_WRAP_DBI_ACCESS_MASKS_H_ */
