/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PSOC_RESET_CONF_MASKS_H_
#define ASIC_REG_PSOC_RESET_CONF_MASKS_H_

/*
 *****************************************
 *   PSOC_RESET_CONF
 *   (Prototype: PSOC_RESET_CONF)
 *****************************************
 */

/* PSOC_RESET_CONF_PSOC_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_PSOC_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PSOC_PRSTN_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PSOC_SOFT_RST_CFG */
#define PSOC_RESET_CONF_PSOC_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PSOC_SOFT_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PSOC_FW_RST_CFG */
#define PSOC_RESET_CONF_PSOC_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PSOC_FW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PSOC_WD_RST_CFG */
#define PSOC_RESET_CONF_PSOC_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PSOC_WD_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PSOC_MNL_RST_CFG */
#define PSOC_RESET_CONF_PSOC_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PSOC_MNL_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PSOC_FLR_RST_CFG */
#define PSOC_RESET_CONF_PSOC_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PSOC_FLR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PSOC_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_PSOC_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PSOC_ECC_DERR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PSOC_SW_RST_CFG */
#define PSOC_RESET_CONF_PSOC_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PSOC_SW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_CPU_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_CPU_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CPU_PRSTN_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_CPU_SOFT_RST_CFG */
#define PSOC_RESET_CONF_CPU_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CPU_SOFT_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_CPU_FW_RST_CFG */
#define PSOC_RESET_CONF_CPU_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CPU_FW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_CPU_WD_RST_CFG */
#define PSOC_RESET_CONF_CPU_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CPU_WD_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_CPU_MNL_RST_CFG */
#define PSOC_RESET_CONF_CPU_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CPU_MNL_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_CPU_FLR_RST_CFG */
#define PSOC_RESET_CONF_CPU_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CPU_FLR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_CPU_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_CPU_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CPU_ECC_DERR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_CPU_SW_RST_CFG */
#define PSOC_RESET_CONF_CPU_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CPU_SW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_ARC_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_ARC_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ARC_PRSTN_RST_CFG_EN_M 0x7

/* PSOC_RESET_CONF_ARC_SOFT_RST_CFG */
#define PSOC_RESET_CONF_ARC_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ARC_SOFT_RST_CFG_EN_M 0x7

/* PSOC_RESET_CONF_ARC_FW_RST_CFG */
#define PSOC_RESET_CONF_ARC_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ARC_FW_RST_CFG_EN_M 0x7

/* PSOC_RESET_CONF_ARC_WD_RST_CFG */
#define PSOC_RESET_CONF_ARC_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ARC_WD_RST_CFG_EN_M 0x7

/* PSOC_RESET_CONF_ARC_MNL_RST_CFG */
#define PSOC_RESET_CONF_ARC_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ARC_MNL_RST_CFG_EN_M 0x7

/* PSOC_RESET_CONF_ARC_FLR_RST_CFG */
#define PSOC_RESET_CONF_ARC_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ARC_FLR_RST_CFG_EN_M 0x7

/* PSOC_RESET_CONF_ARC_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_ARC_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ARC_ECC_DERR_RST_CFG_EN_M 0x7

/* PSOC_RESET_CONF_ARC_SW_RST_CFG */
#define PSOC_RESET_CONF_ARC_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ARC_SW_RST_CFG_EN_M 0x7

/* PSOC_RESET_CONF_RRTR_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_RRTR_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_RRTR_PRSTN_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_RRTR_SOFT_RST_CFG */
#define PSOC_RESET_CONF_RRTR_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_RRTR_SOFT_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_RRTR_FW_RST_CFG */
#define PSOC_RESET_CONF_RRTR_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_RRTR_FW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_RRTR_WD_RST_CFG */
#define PSOC_RESET_CONF_RRTR_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_RRTR_WD_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_RRTR_MNL_RST_CFG */
#define PSOC_RESET_CONF_RRTR_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_RRTR_MNL_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_RRTR_FLR_RST_CFG */
#define PSOC_RESET_CONF_RRTR_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_RRTR_FLR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_RRTR_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_RRTR_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_RRTR_ECC_DERR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_RRTR_SW_RST_CFG */
#define PSOC_RESET_CONF_RRTR_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_RRTR_SW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_NRTR_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_NRTR_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NRTR_PRSTN_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NRTR_SOFT_RST_CFG */
#define PSOC_RESET_CONF_NRTR_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NRTR_SOFT_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NRTR_FW_RST_CFG */
#define PSOC_RESET_CONF_NRTR_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NRTR_FW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NRTR_WD_RST_CFG */
#define PSOC_RESET_CONF_NRTR_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NRTR_WD_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NRTR_MNL_RST_CFG */
#define PSOC_RESET_CONF_NRTR_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NRTR_MNL_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NRTR_FLR_RST_CFG */
#define PSOC_RESET_CONF_NRTR_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NRTR_FLR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NRTR_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_NRTR_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NRTR_ECC_DERR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NRTR_SW_RST_CFG */
#define PSOC_RESET_CONF_NRTR_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NRTR_SW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_GRTR_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_GRTR_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_GRTR_PRSTN_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_GRTR_SOFT_RST_CFG */
#define PSOC_RESET_CONF_GRTR_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_GRTR_SOFT_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_GRTR_FW_RST_CFG */
#define PSOC_RESET_CONF_GRTR_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_GRTR_FW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_GRTR_WD_RST_CFG */
#define PSOC_RESET_CONF_GRTR_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_GRTR_WD_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_GRTR_MNL_RST_CFG */
#define PSOC_RESET_CONF_GRTR_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_GRTR_MNL_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_GRTR_FLR_RST_CFG */
#define PSOC_RESET_CONF_GRTR_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_GRTR_FLR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_GRTR_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_GRTR_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_GRTR_ECC_DERR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_GRTR_SW_RST_CFG */
#define PSOC_RESET_CONF_GRTR_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_GRTR_SW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_DRTR_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_DRTR_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DRTR_PRSTN_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_DRTR_SOFT_RST_CFG */
#define PSOC_RESET_CONF_DRTR_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DRTR_SOFT_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_DRTR_FW_RST_CFG */
#define PSOC_RESET_CONF_DRTR_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DRTR_FW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_DRTR_WD_RST_CFG */
#define PSOC_RESET_CONF_DRTR_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DRTR_WD_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_DRTR_MNL_RST_CFG */
#define PSOC_RESET_CONF_DRTR_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DRTR_MNL_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_DRTR_FLR_RST_CFG */
#define PSOC_RESET_CONF_DRTR_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DRTR_FLR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_DRTR_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_DRTR_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DRTR_ECC_DERR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_DRTR_SW_RST_CFG */
#define PSOC_RESET_CONF_DRTR_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DRTR_SW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_CS_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_CS_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CS_PRSTN_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_CS_SOFT_RST_CFG */
#define PSOC_RESET_CONF_CS_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CS_SOFT_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_CS_FW_RST_CFG */
#define PSOC_RESET_CONF_CS_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CS_FW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_CS_WD_RST_CFG */
#define PSOC_RESET_CONF_CS_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CS_WD_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_CS_MNL_RST_CFG */
#define PSOC_RESET_CONF_CS_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CS_MNL_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_CS_FLR_RST_CFG */
#define PSOC_RESET_CONF_CS_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CS_FLR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_CS_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_CS_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CS_ECC_DERR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_CS_SW_RST_CFG */
#define PSOC_RESET_CONF_CS_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_CS_SW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_PCIE_CTRL_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_PCIE_CTRL_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_CTRL_PRSTN_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_CTRL_SOFT_RST_CFG */
#define PSOC_RESET_CONF_PCIE_CTRL_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_CTRL_SOFT_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_CTRL_FW_RST_CFG */
#define PSOC_RESET_CONF_PCIE_CTRL_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_CTRL_FW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_CTRL_WD_RST_CFG */
#define PSOC_RESET_CONF_PCIE_CTRL_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_CTRL_WD_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_CTRL_MNL_RST_CFG */
#define PSOC_RESET_CONF_PCIE_CTRL_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_CTRL_MNL_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_CTRL_FLR_RST_CFG */
#define PSOC_RESET_CONF_PCIE_CTRL_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_CTRL_FLR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_CTRL_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_PCIE_CTRL_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_CTRL_ECC_DERR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_CTRL_SW_RST_CFG */
#define PSOC_RESET_CONF_PCIE_CTRL_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_CTRL_SW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_PHY_CFG_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_PCIE_PHY_CFG_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_PHY_CFG_PRSTN_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_PHY_CFG_SOFT_RST_CFG */
#define PSOC_RESET_CONF_PCIE_PHY_CFG_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_PHY_CFG_SOFT_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_PHY_CFG_FW_RST_CFG */
#define PSOC_RESET_CONF_PCIE_PHY_CFG_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_PHY_CFG_FW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_PHY_CFG_WD_RST_CFG */
#define PSOC_RESET_CONF_PCIE_PHY_CFG_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_PHY_CFG_WD_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_PHY_CFG_MNL_RST_CFG */
#define PSOC_RESET_CONF_PCIE_PHY_CFG_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_PHY_CFG_MNL_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_PHY_CFG_FLR_RST_CFG */
#define PSOC_RESET_CONF_PCIE_PHY_CFG_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_PHY_CFG_FLR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_PHY_CFG_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_PCIE_PHY_CFG_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_PHY_CFG_ECC_DERR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_PHY_CFG_SW_RST_CFG */
#define PSOC_RESET_CONF_PCIE_PHY_CFG_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_PHY_CFG_SW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_IF_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_PCIE_IF_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_IF_PRSTN_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_IF_SOFT_RST_CFG */
#define PSOC_RESET_CONF_PCIE_IF_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_IF_SOFT_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_IF_FW_RST_CFG */
#define PSOC_RESET_CONF_PCIE_IF_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_IF_FW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_IF_WD_RST_CFG */
#define PSOC_RESET_CONF_PCIE_IF_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_IF_WD_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_IF_MNL_RST_CFG */
#define PSOC_RESET_CONF_PCIE_IF_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_IF_MNL_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_IF_FLR_RST_CFG */
#define PSOC_RESET_CONF_PCIE_IF_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_IF_FLR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_IF_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_PCIE_IF_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_IF_ECC_DERR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_IF_SW_RST_CFG */
#define PSOC_RESET_CONF_PCIE_IF_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PCIE_IF_SW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_TPC_DIV_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_TPC_DIV_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_DIV_PRSTN_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_TPC_DIV_SOFT_RST_CFG */
#define PSOC_RESET_CONF_TPC_DIV_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_DIV_SOFT_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_TPC_DIV_FW_RST_CFG */
#define PSOC_RESET_CONF_TPC_DIV_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_DIV_FW_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_TPC_DIV_WD_RST_CFG */
#define PSOC_RESET_CONF_TPC_DIV_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_DIV_WD_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_TPC_DIV_MNL_RST_CFG */
#define PSOC_RESET_CONF_TPC_DIV_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_DIV_MNL_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_TPC_DIV_FLR_RST_CFG */
#define PSOC_RESET_CONF_TPC_DIV_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_DIV_FLR_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_TPC_DIV_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_TPC_DIV_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_DIV_ECC_DERR_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_TPC_DIV_SW_RST_CFG */
#define PSOC_RESET_CONF_TPC_DIV_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_DIV_SW_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_HBM_DIV_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_HBM_DIV_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_DIV_PRSTN_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_HBM_DIV_SOFT_RST_CFG */
#define PSOC_RESET_CONF_HBM_DIV_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_DIV_SOFT_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_HBM_DIV_FW_RST_CFG */
#define PSOC_RESET_CONF_HBM_DIV_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_DIV_FW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_HBM_DIV_WD_RST_CFG */
#define PSOC_RESET_CONF_HBM_DIV_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_DIV_WD_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_HBM_DIV_MNL_RST_CFG */
#define PSOC_RESET_CONF_HBM_DIV_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_DIV_MNL_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_HBM_DIV_FLR_RST_CFG */
#define PSOC_RESET_CONF_HBM_DIV_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_DIV_FLR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_HBM_DIV_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_HBM_DIV_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_DIV_ECC_DERR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_HBM_DIV_SW_RST_CFG */
#define PSOC_RESET_CONF_HBM_DIV_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_DIV_SW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_PMMU_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_PMMU_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PMMU_PRSTN_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PMMU_SOFT_RST_CFG */
#define PSOC_RESET_CONF_PMMU_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PMMU_SOFT_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PMMU_FW_RST_CFG */
#define PSOC_RESET_CONF_PMMU_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PMMU_FW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PMMU_WD_RST_CFG */
#define PSOC_RESET_CONF_PMMU_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PMMU_WD_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PMMU_MNL_RST_CFG */
#define PSOC_RESET_CONF_PMMU_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PMMU_MNL_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PMMU_FLR_RST_CFG */
#define PSOC_RESET_CONF_PMMU_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PMMU_FLR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PMMU_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_PMMU_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PMMU_ECC_DERR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PMMU_SW_RST_CFG */
#define PSOC_RESET_CONF_PMMU_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PMMU_SW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PM_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_PM_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PM_PRSTN_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_PM_SOFT_RST_CFG */
#define PSOC_RESET_CONF_PM_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PM_SOFT_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_PM_FW_RST_CFG */
#define PSOC_RESET_CONF_PM_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PM_FW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_PM_WD_RST_CFG */
#define PSOC_RESET_CONF_PM_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PM_WD_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_PM_MNL_RST_CFG */
#define PSOC_RESET_CONF_PM_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PM_MNL_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_PM_FLR_RST_CFG */
#define PSOC_RESET_CONF_PM_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PM_FLR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_PM_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_PM_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PM_ECC_DERR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_PM_SW_RST_CFG */
#define PSOC_RESET_CONF_PM_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PM_SW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_PRSTN_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_SOFT_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_SOFT_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_FW_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_FW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_WD_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_WD_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_MNL_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_MNL_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_FLR_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_FLR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_ECC_DERR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_SW_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_SW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_IF_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_IF_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_IF_PRSTN_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_IF_SOFT_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_IF_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_IF_SOFT_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_IF_FW_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_IF_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_IF_FW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_IF_WD_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_IF_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_IF_WD_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_IF_MNL_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_IF_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_IF_MNL_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_IF_FLR_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_IF_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_IF_FLR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_IF_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_IF_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_IF_ECC_DERR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_IF_SW_RST_CFG */
#define PSOC_RESET_CONF_TSTDVS_IF_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_IF_SW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_DPHY_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_DPHY_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DPHY_PRSTN_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_DPHY_SOFT_RST_CFG */
#define PSOC_RESET_CONF_DPHY_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DPHY_SOFT_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_DPHY_FW_RST_CFG */
#define PSOC_RESET_CONF_DPHY_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DPHY_FW_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_DPHY_WD_RST_CFG */
#define PSOC_RESET_CONF_DPHY_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DPHY_WD_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_DPHY_MNL_RST_CFG */
#define PSOC_RESET_CONF_DPHY_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DPHY_MNL_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_DPHY_FLR_RST_CFG */
#define PSOC_RESET_CONF_DPHY_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DPHY_FLR_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_DPHY_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_DPHY_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DPHY_ECC_DERR_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_DPHY_SW_RST_CFG */
#define PSOC_RESET_CONF_DPHY_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_DPHY_SW_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_D2D_MAC_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_D2D_MAC_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_MAC_PRSTN_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_D2D_MAC_SOFT_RST_CFG */
#define PSOC_RESET_CONF_D2D_MAC_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_MAC_SOFT_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_D2D_MAC_FW_RST_CFG */
#define PSOC_RESET_CONF_D2D_MAC_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_MAC_FW_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_D2D_MAC_WD_RST_CFG */
#define PSOC_RESET_CONF_D2D_MAC_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_MAC_WD_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_D2D_MAC_MNL_RST_CFG */
#define PSOC_RESET_CONF_D2D_MAC_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_MAC_MNL_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_D2D_MAC_FLR_RST_CFG */
#define PSOC_RESET_CONF_D2D_MAC_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_MAC_FLR_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_D2D_MAC_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_D2D_MAC_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_MAC_ECC_DERR_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_D2D_MAC_SW_RST_CFG */
#define PSOC_RESET_CONF_D2D_MAC_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_MAC_SW_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_PLL_PSOC_ARC_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_PLL_PSOC_ARC_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_PSOC_ARC_PRSTN_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PLL_PSOC_ARC_SOFT_RST_CFG */
#define PSOC_RESET_CONF_PLL_PSOC_ARC_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_PSOC_ARC_SOFT_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PLL_PSOC_ARC_FW_RST_CFG */
#define PSOC_RESET_CONF_PLL_PSOC_ARC_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_PSOC_ARC_FW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PLL_PSOC_ARC_WD_RST_CFG */
#define PSOC_RESET_CONF_PLL_PSOC_ARC_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_PSOC_ARC_WD_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PLL_PSOC_ARC_MNL_RST_CFG */
#define PSOC_RESET_CONF_PLL_PSOC_ARC_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_PSOC_ARC_MNL_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PLL_PSOC_ARC_FLR_RST_CFG */
#define PSOC_RESET_CONF_PLL_PSOC_ARC_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_PSOC_ARC_FLR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PLL_PSOC_ARC_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_PLL_PSOC_ARC_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_PSOC_ARC_ECC_DERR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PLL_PSOC_ARC_SW_RST_CFG */
#define PSOC_RESET_CONF_PLL_PSOC_ARC_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_PSOC_ARC_SW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PLL_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_PLL_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_PRSTN_RST_CFG_EN_M 0xFFFFFF

/* PSOC_RESET_CONF_PLL_SOFT_RST_CFG */
#define PSOC_RESET_CONF_PLL_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_SOFT_RST_CFG_EN_M 0xFFFFFF

/* PSOC_RESET_CONF_PLL_FW_RST_CFG */
#define PSOC_RESET_CONF_PLL_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_FW_RST_CFG_EN_M 0xFFFFFF

/* PSOC_RESET_CONF_PLL_WD_RST_CFG */
#define PSOC_RESET_CONF_PLL_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_WD_RST_CFG_EN_M 0xFFFFFF

/* PSOC_RESET_CONF_PLL_MNL_RST_CFG */
#define PSOC_RESET_CONF_PLL_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_MNL_RST_CFG_EN_M 0xFFFFFF

/* PSOC_RESET_CONF_PLL_FLR_RST_CFG */
#define PSOC_RESET_CONF_PLL_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_FLR_RST_CFG_EN_M 0xFFFFFF

/* PSOC_RESET_CONF_PLL_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_PLL_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_ECC_DERR_RST_CFG_EN_M 0xFFFFFF

/* PSOC_RESET_CONF_PLL_SW_RST_CFG */
#define PSOC_RESET_CONF_PLL_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PLL_SW_RST_CFG_EN_M 0xFFFFFF

/* PSOC_RESET_CONF_MME_EUS_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_MME_EUS_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MME_EUS_PRSTN_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MME_EUS_SOFT_RST_CFG */
#define PSOC_RESET_CONF_MME_EUS_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MME_EUS_SOFT_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MME_EUS_FW_RST_CFG */
#define PSOC_RESET_CONF_MME_EUS_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MME_EUS_FW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MME_EUS_WD_RST_CFG */
#define PSOC_RESET_CONF_MME_EUS_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MME_EUS_WD_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MME_EUS_MNL_RST_CFG */
#define PSOC_RESET_CONF_MME_EUS_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MME_EUS_MNL_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MME_EUS_FLR_RST_CFG */
#define PSOC_RESET_CONF_MME_EUS_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MME_EUS_FLR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MME_EUS_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_MME_EUS_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MME_EUS_ECC_DERR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MME_EUS_SW_RST_CFG */
#define PSOC_RESET_CONF_MME_EUS_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MME_EUS_SW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MSS_CLS_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_MSS_CLS_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MSS_CLS_PRSTN_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MSS_CLS_SOFT_RST_CFG */
#define PSOC_RESET_CONF_MSS_CLS_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MSS_CLS_SOFT_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MSS_CLS_FW_RST_CFG */
#define PSOC_RESET_CONF_MSS_CLS_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MSS_CLS_FW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MSS_CLS_WD_RST_CFG */
#define PSOC_RESET_CONF_MSS_CLS_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MSS_CLS_WD_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MSS_CLS_MNL_RST_CFG */
#define PSOC_RESET_CONF_MSS_CLS_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MSS_CLS_MNL_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MSS_CLS_FLR_RST_CFG */
#define PSOC_RESET_CONF_MSS_CLS_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MSS_CLS_FLR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MSS_CLS_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_MSS_CLS_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MSS_CLS_ECC_DERR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_MSS_CLS_SW_RST_CFG */
#define PSOC_RESET_CONF_MSS_CLS_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_MSS_CLS_SW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_TPC_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_TPC_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_PRSTN_RST_CFG_EN_M 0xFFFFFFFF

/* PSOC_RESET_CONF_TPC_SOFT_RST_CFG */
#define PSOC_RESET_CONF_TPC_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_SOFT_RST_CFG_EN_M 0xFFFFFFFF

/* PSOC_RESET_CONF_TPC_FW_RST_CFG */
#define PSOC_RESET_CONF_TPC_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_FW_RST_CFG_EN_M 0xFFFFFFFF

/* PSOC_RESET_CONF_TPC_WD_RST_CFG */
#define PSOC_RESET_CONF_TPC_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_WD_RST_CFG_EN_M 0xFFFFFFFF

/* PSOC_RESET_CONF_TPC_MNL_RST_CFG */
#define PSOC_RESET_CONF_TPC_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_MNL_RST_CFG_EN_M 0xFFFFFFFF

/* PSOC_RESET_CONF_TPC_FLR_RST_CFG */
#define PSOC_RESET_CONF_TPC_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_FLR_RST_CFG_EN_M 0xFFFFFFFF

/* PSOC_RESET_CONF_TPC_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_TPC_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_ECC_DERR_RST_CFG_EN_M 0xFFFFFFFF

/* PSOC_RESET_CONF_TPC_SW_RST_CFG */
#define PSOC_RESET_CONF_TPC_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_SW_RST_CFG_EN_M 0xFFFFFFFF

/* PSOC_RESET_CONF_TPC_ECLS_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_TPC_ECLS_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_ECLS_PRSTN_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_TPC_ECLS_SOFT_RST_CFG */
#define PSOC_RESET_CONF_TPC_ECLS_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_ECLS_SOFT_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_TPC_ECLS_FW_RST_CFG */
#define PSOC_RESET_CONF_TPC_ECLS_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_ECLS_FW_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_TPC_ECLS_WD_RST_CFG */
#define PSOC_RESET_CONF_TPC_ECLS_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_ECLS_WD_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_TPC_ECLS_MNL_RST_CFG */
#define PSOC_RESET_CONF_TPC_ECLS_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_ECLS_MNL_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_TPC_ECLS_FLR_RST_CFG */
#define PSOC_RESET_CONF_TPC_ECLS_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_ECLS_FLR_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_TPC_ECLS_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_TPC_ECLS_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_ECLS_ECC_DERR_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_TPC_ECLS_SW_RST_CFG */
#define PSOC_RESET_CONF_TPC_ECLS_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_TPC_ECLS_SW_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_STLB_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_STLB_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_STLB_PRSTN_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_STLB_SOFT_RST_CFG */
#define PSOC_RESET_CONF_STLB_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_STLB_SOFT_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_STLB_FW_RST_CFG */
#define PSOC_RESET_CONF_STLB_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_STLB_FW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_STLB_WD_RST_CFG */
#define PSOC_RESET_CONF_STLB_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_STLB_WD_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_STLB_MNL_RST_CFG */
#define PSOC_RESET_CONF_STLB_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_STLB_MNL_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_STLB_FLR_RST_CFG */
#define PSOC_RESET_CONF_STLB_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_STLB_FLR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_STLB_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_STLB_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_STLB_ECC_DERR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_STLB_SW_RST_CFG */
#define PSOC_RESET_CONF_STLB_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_STLB_SW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_EDMA_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_EDMA_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_EDMA_PRSTN_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_EDMA_SOFT_RST_CFG */
#define PSOC_RESET_CONF_EDMA_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_EDMA_SOFT_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_EDMA_FW_RST_CFG */
#define PSOC_RESET_CONF_EDMA_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_EDMA_FW_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_EDMA_WD_RST_CFG */
#define PSOC_RESET_CONF_EDMA_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_EDMA_WD_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_EDMA_MNL_RST_CFG */
#define PSOC_RESET_CONF_EDMA_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_EDMA_MNL_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_EDMA_FLR_RST_CFG */
#define PSOC_RESET_CONF_EDMA_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_EDMA_FLR_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_EDMA_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_EDMA_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_EDMA_ECC_DERR_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_EDMA_SW_RST_CFG */
#define PSOC_RESET_CONF_EDMA_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_EDMA_SW_RST_CFG_EN_M 0x3

/* PSOC_RESET_CONF_PDMA_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_PDMA_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PDMA_PRSTN_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PDMA_SOFT_RST_CFG */
#define PSOC_RESET_CONF_PDMA_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PDMA_SOFT_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PDMA_FW_RST_CFG */
#define PSOC_RESET_CONF_PDMA_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PDMA_FW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PDMA_WD_RST_CFG */
#define PSOC_RESET_CONF_PDMA_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PDMA_WD_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PDMA_MNL_RST_CFG */
#define PSOC_RESET_CONF_PDMA_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PDMA_MNL_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PDMA_FLR_RST_CFG */
#define PSOC_RESET_CONF_PDMA_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PDMA_FLR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PDMA_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_PDMA_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PDMA_ECC_DERR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_PDMA_SW_RST_CFG */
#define PSOC_RESET_CONF_PDMA_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_PDMA_SW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_SCHED_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_SCHED_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SCHED_PRSTN_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SCHED_SOFT_RST_CFG */
#define PSOC_RESET_CONF_SCHED_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SCHED_SOFT_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SCHED_FW_RST_CFG */
#define PSOC_RESET_CONF_SCHED_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SCHED_FW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SCHED_WD_RST_CFG */
#define PSOC_RESET_CONF_SCHED_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SCHED_WD_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SCHED_MNL_RST_CFG */
#define PSOC_RESET_CONF_SCHED_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SCHED_MNL_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SCHED_FLR_RST_CFG */
#define PSOC_RESET_CONF_SCHED_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SCHED_FLR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SCHED_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_SCHED_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SCHED_ECC_DERR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SCHED_SW_RST_CFG */
#define PSOC_RESET_CONF_SCHED_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SCHED_SW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_ROTATOR_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_ROTATOR_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ROTATOR_PRSTN_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_ROTATOR_SOFT_RST_CFG */
#define PSOC_RESET_CONF_ROTATOR_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ROTATOR_SOFT_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_ROTATOR_FW_RST_CFG */
#define PSOC_RESET_CONF_ROTATOR_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ROTATOR_FW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_ROTATOR_WD_RST_CFG */
#define PSOC_RESET_CONF_ROTATOR_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ROTATOR_WD_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_ROTATOR_MNL_RST_CFG */
#define PSOC_RESET_CONF_ROTATOR_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ROTATOR_MNL_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_ROTATOR_FLR_RST_CFG */
#define PSOC_RESET_CONF_ROTATOR_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ROTATOR_FLR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_ROTATOR_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_ROTATOR_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ROTATOR_ECC_DERR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_ROTATOR_SW_RST_CFG */
#define PSOC_RESET_CONF_ROTATOR_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_ROTATOR_SW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SM_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_SM_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SM_PRSTN_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SM_SOFT_RST_CFG */
#define PSOC_RESET_CONF_SM_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SM_SOFT_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SM_FW_RST_CFG */
#define PSOC_RESET_CONF_SM_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SM_FW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SM_WD_RST_CFG */
#define PSOC_RESET_CONF_SM_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SM_WD_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SM_MNL_RST_CFG */
#define PSOC_RESET_CONF_SM_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SM_MNL_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SM_FLR_RST_CFG */
#define PSOC_RESET_CONF_SM_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SM_FLR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SM_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_SM_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SM_ECC_DERR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_SM_SW_RST_CFG */
#define PSOC_RESET_CONF_SM_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_SM_SW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_VIDEO_DEC_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_VIDEO_DEC_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_PRSTN_RST_CFG_EN_M 0xFF

/* PSOC_RESET_CONF_VIDEO_DEC_SOFT_RST_CFG */
#define PSOC_RESET_CONF_VIDEO_DEC_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_SOFT_RST_CFG_EN_M 0xFF

/* PSOC_RESET_CONF_VIDEO_DEC_FW_RST_CFG */
#define PSOC_RESET_CONF_VIDEO_DEC_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_FW_RST_CFG_EN_M 0xFF

/* PSOC_RESET_CONF_VIDEO_DEC_WD_RST_CFG */
#define PSOC_RESET_CONF_VIDEO_DEC_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_WD_RST_CFG_EN_M 0xFF

/* PSOC_RESET_CONF_VIDEO_DEC_MNL_RST_CFG */
#define PSOC_RESET_CONF_VIDEO_DEC_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_MNL_RST_CFG_EN_M 0xFF

/* PSOC_RESET_CONF_VIDEO_DEC_FLR_RST_CFG */
#define PSOC_RESET_CONF_VIDEO_DEC_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_FLR_RST_CFG_EN_M 0xFF

/* PSOC_RESET_CONF_VIDEO_DEC_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_VIDEO_DEC_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_ECC_DERR_RST_CFG_EN_M 0xFF

/* PSOC_RESET_CONF_VIDEO_DEC_SW_RST_CFG */
#define PSOC_RESET_CONF_VIDEO_DEC_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_SW_RST_CFG_EN_M 0xFF

/* PSOC_RESET_CONF_HBM_MC_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_HBM_MC_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_MC_PRSTN_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_HBM_MC_SOFT_RST_CFG */
#define PSOC_RESET_CONF_HBM_MC_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_MC_SOFT_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_HBM_MC_FW_RST_CFG */
#define PSOC_RESET_CONF_HBM_MC_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_MC_FW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_HBM_MC_WD_RST_CFG */
#define PSOC_RESET_CONF_HBM_MC_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_MC_WD_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_HBM_MC_MNL_RST_CFG */
#define PSOC_RESET_CONF_HBM_MC_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_MC_MNL_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_HBM_MC_FLR_RST_CFG */
#define PSOC_RESET_CONF_HBM_MC_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_MC_FLR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_HBM_MC_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_HBM_MC_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_MC_ECC_DERR_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_HBM_MC_SW_RST_CFG */
#define PSOC_RESET_CONF_HBM_MC_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_HBM_MC_SW_RST_CFG_EN_M 0xF

/* PSOC_RESET_CONF_NIC_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_NIC_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_PRSTN_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_SOFT_RST_CFG */
#define PSOC_RESET_CONF_NIC_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_SOFT_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_FW_RST_CFG */
#define PSOC_RESET_CONF_NIC_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_FW_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_WD_RST_CFG */
#define PSOC_RESET_CONF_NIC_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_WD_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_MNL_RST_CFG */
#define PSOC_RESET_CONF_NIC_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_MNL_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_FLR_RST_CFG */
#define PSOC_RESET_CONF_NIC_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_FLR_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_NIC_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_ECC_DERR_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_SW_RST_CFG */
#define PSOC_RESET_CONF_NIC_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_SW_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_QMAN_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_NIC_QMAN_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_QMAN_PRSTN_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_QMAN_SOFT_RST_CFG */
#define PSOC_RESET_CONF_NIC_QMAN_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_QMAN_SOFT_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_QMAN_FW_RST_CFG */
#define PSOC_RESET_CONF_NIC_QMAN_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_QMAN_FW_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_QMAN_WD_RST_CFG */
#define PSOC_RESET_CONF_NIC_QMAN_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_QMAN_WD_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_QMAN_MNL_RST_CFG */
#define PSOC_RESET_CONF_NIC_QMAN_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_QMAN_MNL_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_QMAN_FLR_RST_CFG */
#define PSOC_RESET_CONF_NIC_QMAN_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_QMAN_FLR_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_QMAN_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_NIC_QMAN_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_QMAN_ECC_DERR_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_QMAN_SW_RST_CFG */
#define PSOC_RESET_CONF_NIC_QMAN_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_QMAN_SW_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_PRT_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_NIC_PRT_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_PRT_PRSTN_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_PRT_SOFT_RST_CFG */
#define PSOC_RESET_CONF_NIC_PRT_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_PRT_SOFT_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_PRT_FW_RST_CFG */
#define PSOC_RESET_CONF_NIC_PRT_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_PRT_FW_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_PRT_WD_RST_CFG */
#define PSOC_RESET_CONF_NIC_PRT_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_PRT_WD_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_PRT_MNL_RST_CFG */
#define PSOC_RESET_CONF_NIC_PRT_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_PRT_MNL_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_PRT_FLR_RST_CFG */
#define PSOC_RESET_CONF_NIC_PRT_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_PRT_FLR_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_PRT_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_NIC_PRT_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_PRT_ECC_DERR_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_PRT_SW_RST_CFG */
#define PSOC_RESET_CONF_NIC_PRT_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NIC_PRT_SW_RST_CFG_EN_M 0x3F

/* PSOC_RESET_CONF_NCH_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_NCH_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_PRSTN_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_SOFT_RST_CFG */
#define PSOC_RESET_CONF_NCH_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_SOFT_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_FW_RST_CFG */
#define PSOC_RESET_CONF_NCH_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_FW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_WD_RST_CFG */
#define PSOC_RESET_CONF_NCH_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_WD_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_MNL_RST_CFG */
#define PSOC_RESET_CONF_NCH_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_MNL_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_FLR_RST_CFG */
#define PSOC_RESET_CONF_NCH_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_FLR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_NCH_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_ECC_DERR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_SW_RST_CFG */
#define PSOC_RESET_CONF_NCH_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_SW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_D2D_FT_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_D2D_FT_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_FT_PRSTN_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_D2D_FT_SOFT_RST_CFG */
#define PSOC_RESET_CONF_D2D_FT_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_FT_SOFT_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_D2D_FT_FW_RST_CFG */
#define PSOC_RESET_CONF_D2D_FT_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_FT_FW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_D2D_FT_WD_RST_CFG */
#define PSOC_RESET_CONF_D2D_FT_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_FT_WD_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_D2D_FT_MNL_RST_CFG */
#define PSOC_RESET_CONF_D2D_FT_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_FT_MNL_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_D2D_FT_FLR_RST_CFG */
#define PSOC_RESET_CONF_D2D_FT_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_FT_FLR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_D2D_FT_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_D2D_FT_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_FT_ECC_DERR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_D2D_FT_SW_RST_CFG */
#define PSOC_RESET_CONF_D2D_FT_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_D2D_FT_SW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_FT_PRSTN_RST_CFG */
#define PSOC_RESET_CONF_NCH_FT_PRSTN_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_FT_PRSTN_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_FT_SOFT_RST_CFG */
#define PSOC_RESET_CONF_NCH_FT_SOFT_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_FT_SOFT_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_FT_FW_RST_CFG */
#define PSOC_RESET_CONF_NCH_FT_FW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_FT_FW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_FT_WD_RST_CFG */
#define PSOC_RESET_CONF_NCH_FT_WD_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_FT_WD_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_FT_MNL_RST_CFG */
#define PSOC_RESET_CONF_NCH_FT_MNL_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_FT_MNL_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_FT_FLR_RST_CFG */
#define PSOC_RESET_CONF_NCH_FT_FLR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_FT_FLR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_FT_ECC_DERR_RST_CFG */
#define PSOC_RESET_CONF_NCH_FT_ECC_DERR_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_FT_ECC_DERR_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_NCH_FT_SW_RST_CFG */
#define PSOC_RESET_CONF_NCH_FT_SW_RST_CFG_EN_S 0
#define PSOC_RESET_CONF_NCH_FT_SW_RST_CFG_EN_M 0x1

/* PSOC_RESET_CONF_SOFT_RST */
#define PSOC_RESET_CONF_SOFT_RST_IND_S 0
#define PSOC_RESET_CONF_SOFT_RST_IND_M 0x1

/* PSOC_RESET_CONF_SW_ALL_RST */
#define PSOC_RESET_CONF_SW_ALL_RST_IND_S 0
#define PSOC_RESET_CONF_SW_ALL_RST_IND_M 0x1

/* PSOC_RESET_CONF_UNIT_RST_N */
#define PSOC_RESET_CONF_UNIT_RST_N_IND_S 0
#define PSOC_RESET_CONF_UNIT_RST_N_IND_M 0x1

/* PSOC_RESET_CONF_PSOC_UNIT_RST */
#define PSOC_RESET_CONF_PSOC_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_PSOC_UNIT_RST_EN_M 0x1

/* PSOC_RESET_CONF_CPU_UNIT_RST */
#define PSOC_RESET_CONF_CPU_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_CPU_UNIT_RST_EN_M 0x1

/* PSOC_RESET_CONF_ARC_UNIT_RST */
#define PSOC_RESET_CONF_ARC_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_ARC_UNIT_RST_EN_M 0x7

/* PSOC_RESET_CONF_RRTR_UNIT_RST */
#define PSOC_RESET_CONF_RRTR_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_RRTR_UNIT_RST_EN_M 0xF

/* PSOC_RESET_CONF_NRTR_UNIT_RST */
#define PSOC_RESET_CONF_NRTR_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_NRTR_UNIT_RST_EN_M 0x1

/* PSOC_RESET_CONF_GRTR_UNIT_RST */
#define PSOC_RESET_CONF_GRTR_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_GRTR_UNIT_RST_EN_M 0x1

/* PSOC_RESET_CONF_DRTR_UNIT_RST */
#define PSOC_RESET_CONF_DRTR_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_DRTR_UNIT_RST_EN_M 0x1

/* PSOC_RESET_CONF_CS_UNIT_RST */
#define PSOC_RESET_CONF_CS_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_CS_UNIT_RST_EN_M 0xF

/* PSOC_RESET_CONF_PCIE_CTRL_UNIT_RST */
#define PSOC_RESET_CONF_PCIE_CTRL_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_PCIE_CTRL_UNIT_RST_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_PHY_CFG_UNIT_RST */
#define PSOC_RESET_CONF_PCIE_PHY_CFG_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_PCIE_PHY_CFG_UNIT_RST_EN_M 0x1

/* PSOC_RESET_CONF_PCIE_IF_UNIT_RST */
#define PSOC_RESET_CONF_PCIE_IF_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_PCIE_IF_UNIT_RST_EN_M 0x1

/* PSOC_RESET_CONF_TPC_DIV_UNIT_RST */
#define PSOC_RESET_CONF_TPC_DIV_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_TPC_DIV_UNIT_RST_EN_M 0x3F

/* PSOC_RESET_CONF_HBM_DIV_UNIT_RST */
#define PSOC_RESET_CONF_HBM_DIV_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_HBM_DIV_UNIT_RST_EN_M 0xF

/* PSOC_RESET_CONF_PMMU_UNIT_RST */
#define PSOC_RESET_CONF_PMMU_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_PMMU_UNIT_RST_EN_M 0x1

/* PSOC_RESET_CONF_PM_UNIT_RST */
#define PSOC_RESET_CONF_PM_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_PM_UNIT_RST_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_UNIT_RST */
#define PSOC_RESET_CONF_TSTDVS_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_UNIT_RST_EN_M 0xF

/* PSOC_RESET_CONF_TSTDVS_IF_UNIT_RST */
#define PSOC_RESET_CONF_TSTDVS_IF_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_TSTDVS_IF_UNIT_RST_EN_M 0xF

/* PSOC_RESET_CONF_DPHY_UNIT_RST */
#define PSOC_RESET_CONF_DPHY_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_DPHY_UNIT_RST_EN_M 0x3F

/* PSOC_RESET_CONF_D2D_MAC_UNIT_RST */
#define PSOC_RESET_CONF_D2D_MAC_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_D2D_MAC_UNIT_RST_EN_M 0x3

/* PSOC_RESET_CONF_PLL_PSOC_ARC_UNIT_RST */
#define PSOC_RESET_CONF_PLL_PSOC_ARC_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_PLL_PSOC_ARC_UNIT_RST_EN_M 0x1

/* PSOC_RESET_CONF_PLL_UNIT_RST */
#define PSOC_RESET_CONF_PLL_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_PLL_UNIT_RST_EN_M 0xFFFFFF

/* PSOC_RESET_CONF_MME_EUS_UNIT_RST */
#define PSOC_RESET_CONF_MME_EUS_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_MME_EUS_UNIT_RST_EN_M 0xF

/* PSOC_RESET_CONF_MSS_CLS_UNIT_RST */
#define PSOC_RESET_CONF_MSS_CLS_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_MSS_CLS_UNIT_RST_EN_M 0xF

/* PSOC_RESET_CONF_TPC_UNIT_RST */
#define PSOC_RESET_CONF_TPC_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_TPC_UNIT_RST_EN_M 0xFFFFFFFF

/* PSOC_RESET_CONF_TPC_ECLS_UNIT_RST */
#define PSOC_RESET_CONF_TPC_ECLS_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_TPC_ECLS_UNIT_RST_EN_M 0x3

/* PSOC_RESET_CONF_STLB_UNIT_RST */
#define PSOC_RESET_CONF_STLB_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_STLB_UNIT_RST_EN_M 0xF

/* PSOC_RESET_CONF_EDMA_UNIT_RST */
#define PSOC_RESET_CONF_EDMA_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_EDMA_UNIT_RST_EN_M 0x3

/* PSOC_RESET_CONF_PDMA_UNIT_RST */
#define PSOC_RESET_CONF_PDMA_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_PDMA_UNIT_RST_EN_M 0x1

/* PSOC_RESET_CONF_SCHED_UNIT_RST */
#define PSOC_RESET_CONF_SCHED_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_SCHED_UNIT_RST_EN_M 0xF

/* PSOC_RESET_CONF_ROTATOR_UNIT_RST */
#define PSOC_RESET_CONF_ROTATOR_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_ROTATOR_UNIT_RST_EN_M 0xF

/* PSOC_RESET_CONF_SM_UNIT_RST */
#define PSOC_RESET_CONF_SM_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_SM_UNIT_RST_EN_M 0xF

/* PSOC_RESET_CONF_VIDEO_DEC_UNIT_RST */
#define PSOC_RESET_CONF_VIDEO_DEC_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_UNIT_RST_EN_M 0xFF

/* PSOC_RESET_CONF_HBM_MC_UNIT_RST */
#define PSOC_RESET_CONF_HBM_MC_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_HBM_MC_UNIT_RST_EN_M 0xF

/* PSOC_RESET_CONF_NIC_UNIT_RST */
#define PSOC_RESET_CONF_NIC_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_NIC_UNIT_RST_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_QMAN_UNIT_RST */
#define PSOC_RESET_CONF_NIC_QMAN_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_NIC_QMAN_UNIT_RST_EN_M 0x3F

/* PSOC_RESET_CONF_NIC_PRT_UNIT_RST */
#define PSOC_RESET_CONF_NIC_PRT_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_NIC_PRT_UNIT_RST_EN_M 0x3F

/* PSOC_RESET_CONF_NCH_UNIT_RST */
#define PSOC_RESET_CONF_NCH_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_NCH_UNIT_RST_EN_M 0x1

/* PSOC_RESET_CONF_D2D_FT_UNIT_RST */
#define PSOC_RESET_CONF_D2D_FT_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_D2D_FT_UNIT_RST_EN_M 0x1

/* PSOC_RESET_CONF_NCH_FT_UNIT_RST */
#define PSOC_RESET_CONF_NCH_FT_UNIT_RST_EN_S 0
#define PSOC_RESET_CONF_NCH_FT_UNIT_RST_EN_M 0x1

/* PSOC_RESET_CONF_PSOC_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PSOC_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PSOC_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PSOC_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PSOC_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_CPU_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_CPU_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_CPU_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_CPU_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_CPU_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_ARC_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_ARC_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_ARC_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_ARC_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_ARC_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_ARC_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_ARC_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_ARC_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_ARC_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_ARC_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_ARC_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_ARC_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_ARC_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_ARC_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_ARC_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_RRTR_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_RRTR_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_RRTR_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_RRTR_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_RRTR_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_RRTR_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_RRTR_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_RRTR_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_RRTR_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_RRTR_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_RRTR_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_RRTR_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_RRTR_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_RRTR_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_RRTR_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_RRTR_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_RRTR_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_RRTR_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_RRTR_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_RRTR_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NRTR_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NRTR_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NRTR_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NRTR_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NRTR_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_GRTR_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_GRTR_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_GRTR_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_GRTR_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_GRTR_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_DRTR_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_DRTR_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_DRTR_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_DRTR_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_DRTR_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_CS_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_CS_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_CS_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_CS_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_CS_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_CS_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_CS_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_CS_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_CS_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_CS_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_CS_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_CS_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_CS_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_CS_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_CS_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_CS_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_CS_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_CS_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_CS_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_CS_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PCIE_CTRL_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PCIE_CTRL_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PCIE_CTRL_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PCIE_CTRL_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PCIE_CTRL_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PCIE_PHY_CFG_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PCIE_PHY_CFG_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PCIE_PHY_CFG_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PCIE_PHY_CFG_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PCIE_PHY_CFG_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PCIE_IF_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PCIE_IF_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PCIE_IF_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PCIE_IF_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PCIE_IF_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_DIV_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_DIV_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_DIV_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_DIV_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_DIV_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_DIV_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_DIV_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_DIV_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_DIV_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_DIV_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_DIV_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_DIV_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_DIV_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_DIV_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_DIV_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_DIV_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_DIV_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_DIV_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_DIV_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_DIV_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_DIV_4_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_DIV_4_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_DIV_4_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_DIV_4_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_DIV_4_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_DIV_5_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_DIV_5_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_DIV_5_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_DIV_5_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_DIV_5_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_HBM_DIV_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_HBM_DIV_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_HBM_DIV_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_HBM_DIV_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_HBM_DIV_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_HBM_DIV_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_HBM_DIV_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_HBM_DIV_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_HBM_DIV_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_HBM_DIV_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_HBM_DIV_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_HBM_DIV_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_HBM_DIV_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_HBM_DIV_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_HBM_DIV_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_HBM_DIV_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_HBM_DIV_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_HBM_DIV_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_HBM_DIV_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_HBM_DIV_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PMMU_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PMMU_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PMMU_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PMMU_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PMMU_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PM_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PM_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PM_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PM_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PM_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PM_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PM_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PM_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PM_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PM_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PM_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PM_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PM_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PM_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PM_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PM_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PM_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PM_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PM_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PM_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TSTDVS_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TSTDVS_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TSTDVS_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TSTDVS_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TSTDVS_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TSTDVS_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TSTDVS_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TSTDVS_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TSTDVS_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TSTDVS_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TSTDVS_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TSTDVS_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TSTDVS_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TSTDVS_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TSTDVS_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TSTDVS_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TSTDVS_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TSTDVS_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TSTDVS_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TSTDVS_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TSTDVS_IF_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TSTDVS_IF_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TSTDVS_IF_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TSTDVS_IF_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TSTDVS_IF_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TSTDVS_IF_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TSTDVS_IF_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TSTDVS_IF_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TSTDVS_IF_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TSTDVS_IF_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TSTDVS_IF_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TSTDVS_IF_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TSTDVS_IF_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TSTDVS_IF_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TSTDVS_IF_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TSTDVS_IF_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TSTDVS_IF_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TSTDVS_IF_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TSTDVS_IF_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TSTDVS_IF_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_DPHY_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_DPHY_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_DPHY_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_DPHY_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_DPHY_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_DPHY_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_DPHY_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_DPHY_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_DPHY_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_DPHY_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_DPHY_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_DPHY_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_DPHY_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_DPHY_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_DPHY_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_DPHY_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_DPHY_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_DPHY_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_DPHY_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_DPHY_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_DPHY_4_CLK_RST_CTRL */
#define PSOC_RESET_CONF_DPHY_4_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_DPHY_4_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_DPHY_4_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_DPHY_4_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_DPHY_5_CLK_RST_CTRL */
#define PSOC_RESET_CONF_DPHY_5_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_DPHY_5_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_DPHY_5_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_DPHY_5_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_D2D_MAC_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_D2D_MAC_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_D2D_MAC_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_D2D_MAC_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_D2D_MAC_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_D2D_MAC_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_D2D_MAC_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_D2D_MAC_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_D2D_MAC_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_D2D_MAC_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_PSOC_ARC_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_PSOC_ARC_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_PSOC_ARC_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_PSOC_ARC_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_PSOC_ARC_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_4_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_4_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_4_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_4_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_4_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_5_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_5_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_5_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_5_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_5_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_6_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_6_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_6_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_6_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_6_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_7_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_7_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_7_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_7_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_7_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_8_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_8_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_8_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_8_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_8_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_9_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_9_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_9_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_9_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_9_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_10_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_10_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_10_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_10_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_10_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_11_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_11_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_11_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_11_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_11_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_12_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_12_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_12_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_12_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_12_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_13_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_13_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_13_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_13_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_13_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_14_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_14_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_14_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_14_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_14_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_15_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_15_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_15_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_15_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_15_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_16_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_16_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_16_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_16_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_16_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_17_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_17_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_17_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_17_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_17_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_18_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_18_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_18_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_18_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_18_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_19_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_19_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_19_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_19_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_19_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_20_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_20_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_20_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_20_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_20_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_21_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_21_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_21_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_21_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_21_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_22_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_22_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_22_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_22_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_22_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PLL_23_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PLL_23_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PLL_23_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PLL_23_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PLL_23_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_MME_EUS_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_MME_EUS_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_MME_EUS_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_MME_EUS_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_MME_EUS_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_MME_EUS_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_MME_EUS_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_MME_EUS_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_MME_EUS_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_MME_EUS_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_MME_EUS_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_MME_EUS_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_MME_EUS_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_MME_EUS_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_MME_EUS_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_MME_EUS_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_MME_EUS_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_MME_EUS_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_MME_EUS_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_MME_EUS_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_MSS_CLS_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_MSS_CLS_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_MSS_CLS_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_MSS_CLS_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_MSS_CLS_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_MSS_CLS_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_MSS_CLS_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_MSS_CLS_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_MSS_CLS_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_MSS_CLS_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_MSS_CLS_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_MSS_CLS_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_MSS_CLS_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_MSS_CLS_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_MSS_CLS_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_MSS_CLS_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_MSS_CLS_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_MSS_CLS_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_MSS_CLS_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_MSS_CLS_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_4_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_4_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_4_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_4_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_4_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_5_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_5_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_5_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_5_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_5_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_6_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_6_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_6_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_6_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_6_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_7_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_7_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_7_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_7_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_7_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_8_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_8_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_8_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_8_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_8_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_9_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_9_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_9_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_9_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_9_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_10_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_10_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_10_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_10_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_10_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_11_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_11_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_11_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_11_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_11_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_12_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_12_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_12_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_12_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_12_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_13_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_13_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_13_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_13_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_13_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_14_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_14_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_14_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_14_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_14_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_15_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_15_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_15_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_15_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_15_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_16_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_16_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_16_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_16_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_16_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_17_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_17_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_17_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_17_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_17_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_18_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_18_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_18_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_18_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_18_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_19_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_19_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_19_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_19_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_19_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_20_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_20_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_20_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_20_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_20_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_21_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_21_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_21_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_21_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_21_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_22_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_22_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_22_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_22_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_22_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_23_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_23_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_23_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_23_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_23_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_24_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_24_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_24_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_24_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_24_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_25_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_25_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_25_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_25_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_25_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_26_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_26_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_26_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_26_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_26_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_27_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_27_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_27_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_27_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_27_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_28_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_28_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_28_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_28_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_28_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_29_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_29_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_29_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_29_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_29_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_30_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_30_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_30_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_30_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_30_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_31_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_31_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_31_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_31_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_31_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_ECLS_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_ECLS_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_ECLS_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_ECLS_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_ECLS_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_TPC_ECLS_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_TPC_ECLS_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_TPC_ECLS_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_TPC_ECLS_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_TPC_ECLS_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_STLB_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_STLB_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_STLB_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_STLB_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_STLB_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_STLB_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_STLB_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_STLB_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_STLB_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_STLB_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_STLB_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_STLB_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_STLB_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_STLB_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_STLB_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_STLB_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_STLB_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_STLB_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_STLB_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_STLB_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_EDMA_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_EDMA_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_EDMA_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_EDMA_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_EDMA_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_EDMA_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_EDMA_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_EDMA_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_EDMA_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_EDMA_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_PDMA_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_PDMA_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_PDMA_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_PDMA_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_PDMA_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_SCHED_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_SCHED_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_SCHED_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_SCHED_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_SCHED_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_SCHED_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_SCHED_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_SCHED_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_SCHED_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_SCHED_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_SCHED_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_SCHED_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_SCHED_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_SCHED_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_SCHED_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_SCHED_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_SCHED_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_SCHED_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_SCHED_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_SCHED_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_ROTATOR_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_ROTATOR_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_ROTATOR_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_ROTATOR_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_ROTATOR_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_ROTATOR_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_ROTATOR_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_ROTATOR_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_ROTATOR_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_ROTATOR_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_ROTATOR_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_ROTATOR_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_ROTATOR_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_ROTATOR_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_ROTATOR_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_ROTATOR_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_ROTATOR_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_ROTATOR_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_ROTATOR_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_ROTATOR_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_SM_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_SM_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_SM_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_SM_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_SM_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_SM_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_SM_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_SM_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_SM_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_SM_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_SM_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_SM_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_SM_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_SM_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_SM_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_SM_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_SM_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_SM_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_SM_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_SM_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_VIDEO_DEC_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_VIDEO_DEC_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_VIDEO_DEC_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_VIDEO_DEC_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_VIDEO_DEC_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_VIDEO_DEC_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_VIDEO_DEC_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_VIDEO_DEC_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_VIDEO_DEC_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_VIDEO_DEC_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_VIDEO_DEC_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_VIDEO_DEC_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_VIDEO_DEC_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_VIDEO_DEC_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_VIDEO_DEC_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_VIDEO_DEC_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_VIDEO_DEC_4_CLK_RST_CTRL */
#define PSOC_RESET_CONF_VIDEO_DEC_4_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_4_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_VIDEO_DEC_4_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_VIDEO_DEC_4_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_VIDEO_DEC_5_CLK_RST_CTRL */
#define PSOC_RESET_CONF_VIDEO_DEC_5_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_5_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_VIDEO_DEC_5_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_VIDEO_DEC_5_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_VIDEO_DEC_6_CLK_RST_CTRL */
#define PSOC_RESET_CONF_VIDEO_DEC_6_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_6_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_VIDEO_DEC_6_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_VIDEO_DEC_6_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_VIDEO_DEC_7_CLK_RST_CTRL */
#define PSOC_RESET_CONF_VIDEO_DEC_7_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_VIDEO_DEC_7_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_VIDEO_DEC_7_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_VIDEO_DEC_7_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_HBM_MC_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_HBM_MC_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_HBM_MC_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_HBM_MC_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_HBM_MC_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_HBM_MC_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_HBM_MC_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_HBM_MC_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_HBM_MC_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_HBM_MC_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_HBM_MC_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_HBM_MC_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_HBM_MC_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_HBM_MC_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_HBM_MC_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_HBM_MC_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_HBM_MC_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_HBM_MC_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_HBM_MC_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_HBM_MC_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_4_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_4_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_4_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_4_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_4_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_5_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_5_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_5_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_5_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_5_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_QMAN_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_QMAN_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_QMAN_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_QMAN_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_QMAN_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_QMAN_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_QMAN_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_QMAN_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_QMAN_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_QMAN_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_QMAN_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_QMAN_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_QMAN_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_QMAN_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_QMAN_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_QMAN_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_QMAN_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_QMAN_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_QMAN_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_QMAN_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_QMAN_4_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_QMAN_4_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_QMAN_4_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_QMAN_4_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_QMAN_4_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_QMAN_5_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_QMAN_5_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_QMAN_5_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_QMAN_5_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_QMAN_5_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_PRT_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_PRT_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_PRT_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_PRT_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_PRT_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_PRT_1_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_PRT_1_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_PRT_1_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_PRT_1_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_PRT_1_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_PRT_2_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_PRT_2_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_PRT_2_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_PRT_2_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_PRT_2_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_PRT_3_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_PRT_3_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_PRT_3_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_PRT_3_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_PRT_3_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_PRT_4_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_PRT_4_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_PRT_4_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_PRT_4_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_PRT_4_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NIC_PRT_5_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NIC_PRT_5_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NIC_PRT_5_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NIC_PRT_5_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NIC_PRT_5_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NCH_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NCH_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NCH_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NCH_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NCH_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_D2D_FT_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_D2D_FT_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_D2D_FT_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_D2D_FT_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_D2D_FT_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

/* PSOC_RESET_CONF_NCH_FT_0_CLK_RST_CTRL */
#define PSOC_RESET_CONF_NCH_FT_0_CLK_RST_CTRL_RST_SEL_S 0
#define PSOC_RESET_CONF_NCH_FT_0_CLK_RST_CTRL_RST_SEL_M 0xFF
#define PSOC_RESET_CONF_NCH_FT_0_CLK_RST_CTRL_CLK_DIS_S 16
#define PSOC_RESET_CONF_NCH_FT_0_CLK_RST_CTRL_CLK_DIS_M 0x10000

#endif /* ASIC_REG_PSOC_RESET_CONF_MASKS_H_ */
