/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_RTR_CTRL_CH_RAZWI_HBW_REGS_H_
#define ASIC_REG_RTR_CTRL_CH_RAZWI_HBW_REGS_H_

/*
 *****************************************
 *   RTR_CTRL_CH_RAZWI_HBW
 *   (Prototype: RTR_CTRL_RAZWI)
 *****************************************
 */

#define mmRTR_CTRL_CH_RAZWI_HBW_RR_RAZWI_AW_HAPPENED_CLR 0x0

#define mmRTR_CTRL_CH_RAZWI_HBW_RR_RAZWI_AW_HAPPENED_ST 0x4

#define mmRTR_CTRL_CH_RAZWI_HBW_RR_RAZWI_AW_ADDR_HI 0x8

#define mmRTR_CTRL_CH_RAZWI_HBW_RR_RAZWI_AW_ADDR_LO 0xC

#define mmRTR_CTRL_CH_RAZWI_HBW_RR_RAZWI_AW_ID 0x10

#define mmRTR_CTRL_CH_RAZWI_HBW_RR_RAZWI_AR_HAPPENED_CLR 0x20

#define mmRTR_CTRL_CH_RAZWI_HBW_RR_RAZWI_AR_HAPPENED_ST 0x24

#define mmRTR_CTRL_CH_RAZWI_HBW_RR_RAZWI_AR_ADDR_HI 0x28

#define mmRTR_CTRL_CH_RAZWI_HBW_RR_RAZWI_AR_ADDR_LO 0x2C

#define mmRTR_CTRL_CH_RAZWI_HBW_RR_RAZWI_AR_ID 0x30

#define mmRTR_CTRL_CH_RAZWI_HBW_ADEC_RAZWI_AW_CLR 0x40

#define mmRTR_CTRL_CH_RAZWI_HBW_ADEC_RAZWI_AW_SET 0x44

#define mmRTR_CTRL_CH_RAZWI_HBW_ADEC_RAZWI_AW_ADDR_HI 0x48

#define mmRTR_CTRL_CH_RAZWI_HBW_ADEC_RAZWI_AW_ADDR_LO 0x4C

#define mmRTR_CTRL_CH_RAZWI_HBW_ADEC_RAZWI_AW_ID 0x50

#define mmRTR_CTRL_CH_RAZWI_HBW_ADEC_RAZWI_AR_CLR 0x60

#define mmRTR_CTRL_CH_RAZWI_HBW_ADEC_RAZWI_AR_SET 0x64

#define mmRTR_CTRL_CH_RAZWI_HBW_ADEC_RAZWI_AR_ADDR_HI 0x68

#define mmRTR_CTRL_CH_RAZWI_HBW_ADEC_RAZWI_AR_ADDR_LO 0x6C

#define mmRTR_CTRL_CH_RAZWI_HBW_ADEC_RAZWI_AR_ID 0x70

#define mmRTR_CTRL_CH_RAZWI_HBW_RAZWI_RESP_SIG 0x80

#endif /* ASIC_REG_RTR_CTRL_CH_RAZWI_HBW_REGS_H_ */
