/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_RTR_CTRL_HBW_SCRAM_REGS_H_
#define ASIC_REG_RTR_CTRL_HBW_SCRAM_REGS_H_

/*
 *****************************************
 *   RTR_CTRL_HBW_SCRAM
 *   (Prototype: RTR_CTRL_SCRAM)
 *****************************************
 */

#define mmRTR_CTRL_HBW_SCRAM_NUM_HBM 0x0

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_EXTMEM_EN 0x10

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_POLY_H3_0 0x14

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_POLY_H3_1 0x18

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_POLY_H3_2 0x1C

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_POLY_H3_3 0x20

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_POLY_H3_4 0x24

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_POLY_H3_5 0x28

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_POLY_H3_6 0x2C

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_POLY_H3_7 0x30

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_POLY_H3_8 0x34

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_POLY_H3_9 0x38

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_POLY_H3_10 0x3C

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_POLY_H3_11 0x40

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P2_EXTMEM_EN 0x50

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P2_POLY_H3_0 0x54

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P2_POLY_H3_1 0x58

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P2_POLY_H3_2 0x5C

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P2_POLY_H3_3 0x60

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P2_POLY_H3_4 0x64

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P2_POLY_H3_5 0x68

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P2_POLY_H3_6 0x6C

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P2_POLY_H3_7 0x70

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P2_POLY_H3_8 0x74

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P2_POLY_H3_9 0x78

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P2_POLY_H3_10 0x7C

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P2_POLY_H3_11 0x80

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P3_EXTMEM_EN 0x90

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P3_POLY_H3_0 0x94

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P3_POLY_H3_1 0x98

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P3_POLY_H3_2 0x9C

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P3_POLY_H3_3 0xA0

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P3_POLY_H3_4 0xA4

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P3_POLY_H3_5 0xA8

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P3_POLY_H3_6 0xAC

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P3_POLY_H3_7 0xB0

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P3_POLY_H3_8 0xB4

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P3_POLY_H3_9 0xB8

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P3_POLY_H3_10 0xBC

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P3_POLY_H3_11 0xC0

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_HA_MAP_0 0xD0

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_HA_MAP_1 0xD4

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_R2C_MAP 0xD8

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_R2C_NLIN 0xE0

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_BANK_NLIN 0xE4

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P1_CS_NLIN 0xE8

#define mmRTR_CTRL_HBW_SCRAM_SCRAM_P3_D2D_NLIN 0xEC

#define mmRTR_CTRL_HBW_SCRAM_OVRD_SRAM_AXCACHE 0xF0

#define mmRTR_CTRL_HBW_SCRAM_SRAM_MODE 0xF4

#define mmRTR_CTRL_HBW_SCRAM_OVRD_HBM_AXCACHE 0xF8

#endif /* ASIC_REG_RTR_CTRL_HBW_SCRAM_REGS_H_ */
