/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_VDEC_BRDG_CTRL_MASKS_H_
#define ASIC_REG_VDEC_BRDG_CTRL_MASKS_H_

/*
 *****************************************
 *   VDEC_BRDG_CTRL
 *   (Prototype: VDEC_BRDG_CTRL)
 *****************************************
 */

/* VDEC_BRDG_CTRL_CGM_DISABLE */
#define VDEC_BRDG_CTRL_CGM_DISABLE_VAL_S 0
#define VDEC_BRDG_CTRL_CGM_DISABLE_VAL_M 0x1

/* VDEC_BRDG_CTRL_IDLE_MASK */
#define VDEC_BRDG_CTRL_IDLE_MASK_VAL_S 0
#define VDEC_BRDG_CTRL_IDLE_MASK_VAL_M 0x7

/* VDEC_BRDG_CTRL_APB_CGM_CNT */
#define VDEC_BRDG_CTRL_APB_CGM_CNT_VAL_S 0
#define VDEC_BRDG_CTRL_APB_CGM_CNT_VAL_M 0xFFFF

/* VDEC_BRDG_CTRL_APB_ARB_WDOG_CNT */
#define VDEC_BRDG_CTRL_APB_ARB_WDOG_CNT_VAL_S 0
#define VDEC_BRDG_CTRL_APB_ARB_WDOG_CNT_VAL_M 0xFFFF

/* VDEC_BRDG_CTRL_GRACEFUL */
#define VDEC_BRDG_CTRL_GRACEFUL_STOP_S 0
#define VDEC_BRDG_CTRL_GRACEFUL_STOP_M 0x1
#define VDEC_BRDG_CTRL_GRACEFUL_PEND_S 4
#define VDEC_BRDG_CTRL_GRACEFUL_PEND_M 0x10

/* VDEC_BRDG_CTRL_IDLE_CGM_CNT */
#define VDEC_BRDG_CTRL_IDLE_CGM_CNT_VAL_S 0
#define VDEC_BRDG_CTRL_IDLE_CGM_CNT_VAL_M 0xFFFF

/* VDEC_BRDG_CTRL_CAUSE_INTR */
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_VCD_HBW_SEI_S 0
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_VCD_HBW_SEI_M 0x1
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_L2C_HBW_SEI_S 1
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_L2C_HBW_SEI_M 0x2
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_NRM_HBW_SEI_S 2
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_NRM_HBW_SEI_M 0x4
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_ABNRM_HBW_SEI_S 3
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_ABNRM_HBW_SEI_M 0x8
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_VCD_LBW_SEI_S 4
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_VCD_LBW_SEI_M 0x10
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_L2C_LBW_SEI_S 5
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_L2C_LBW_SEI_M 0x20
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_NRM_LBW_SEI_S 6
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_NRM_LBW_SEI_M 0x40
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_ABNRM_LBW_SEI_S 7
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_ABNRM_LBW_SEI_M 0x80
#define VDEC_BRDG_CTRL_CAUSE_INTR_APB_VCD_LBW_SEI_S 8
#define VDEC_BRDG_CTRL_CAUSE_INTR_APB_VCD_LBW_SEI_M 0x100
#define VDEC_BRDG_CTRL_CAUSE_INTR_APB_L2C_LBW_SEI_S 9
#define VDEC_BRDG_CTRL_CAUSE_INTR_APB_L2C_LBW_SEI_M 0x200
#define VDEC_BRDG_CTRL_CAUSE_INTR_APB_NRM_LBW_SEI_S 10
#define VDEC_BRDG_CTRL_CAUSE_INTR_APB_NRM_LBW_SEI_M 0x400
#define VDEC_BRDG_CTRL_CAUSE_INTR_APB_ABNRM_LBW_SEI_S 11
#define VDEC_BRDG_CTRL_CAUSE_INTR_APB_ABNRM_LBW_SEI_M 0x800
#define VDEC_BRDG_CTRL_CAUSE_INTR_DEC_SEI_S 12
#define VDEC_BRDG_CTRL_CAUSE_INTR_DEC_SEI_M 0x1000
#define VDEC_BRDG_CTRL_CAUSE_INTR_DEC_APB_SEI_S 13
#define VDEC_BRDG_CTRL_CAUSE_INTR_DEC_APB_SEI_M 0x2000
#define VDEC_BRDG_CTRL_CAUSE_INTR_TRC_APB_SEI_S 14
#define VDEC_BRDG_CTRL_CAUSE_INTR_TRC_APB_SEI_M 0x4000
#define VDEC_BRDG_CTRL_CAUSE_INTR_LBW_MSTR_IF_SEI_S 15
#define VDEC_BRDG_CTRL_CAUSE_INTR_LBW_MSTR_IF_SEI_M 0x8000
#define VDEC_BRDG_CTRL_CAUSE_INTR_AXI_SPLIT_BRESP_ERR_SEI_S 16
#define VDEC_BRDG_CTRL_CAUSE_INTR_AXI_SPLIT_BRESP_ERR_SEI_M 0x10000
#define VDEC_BRDG_CTRL_CAUSE_INTR_HBW_AXI_WR_VIOL_SEI_S 17
#define VDEC_BRDG_CTRL_CAUSE_INTR_HBW_AXI_WR_VIOL_SEI_M 0x20000
#define VDEC_BRDG_CTRL_CAUSE_INTR_HBW_AXI_RD_VIOL_SEI_S 18
#define VDEC_BRDG_CTRL_CAUSE_INTR_HBW_AXI_RD_VIOL_SEI_M 0x40000
#define VDEC_BRDG_CTRL_CAUSE_INTR_LBW_AXI_WR_VIOL_SEI_S 19
#define VDEC_BRDG_CTRL_CAUSE_INTR_LBW_AXI_WR_VIOL_SEI_M 0x80000
#define VDEC_BRDG_CTRL_CAUSE_INTR_LBW_AXI_RD_VIOL_SEI_S 20
#define VDEC_BRDG_CTRL_CAUSE_INTR_LBW_AXI_RD_VIOL_SEI_M 0x100000
#define VDEC_BRDG_CTRL_CAUSE_INTR_VCD_SPI_S 21
#define VDEC_BRDG_CTRL_CAUSE_INTR_VCD_SPI_M 0x200000
#define VDEC_BRDG_CTRL_CAUSE_INTR_L2C_SPI_S 22
#define VDEC_BRDG_CTRL_CAUSE_INTR_L2C_SPI_M 0x400000
#define VDEC_BRDG_CTRL_CAUSE_INTR_NRM_SPI_S 23
#define VDEC_BRDG_CTRL_CAUSE_INTR_NRM_SPI_M 0x800000
#define VDEC_BRDG_CTRL_CAUSE_INTR_ABNRM_SPI_S 24
#define VDEC_BRDG_CTRL_CAUSE_INTR_ABNRM_SPI_M 0x1000000
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_VCD_RR_DBG_SEI_S 25
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_VCD_RR_DBG_SEI_M 0x2000000
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_L2C_RR_DBG_SEI_S 26
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_L2C_RR_DBG_SEI_M 0x4000000
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_NRM_RR_DBG_SEI_S 27
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_NRM_RR_DBG_SEI_M 0x8000000
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_ABNRM_RR_DBG_SEI_S 28
#define VDEC_BRDG_CTRL_CAUSE_INTR_MSIX_ABNRM_RR_DBG_SEI_M 0x10000000
#define VDEC_BRDG_CTRL_CAUSE_INTR_DEC_WR_RR_DBG_SEI_S 29
#define VDEC_BRDG_CTRL_CAUSE_INTR_DEC_WR_RR_DBG_SEI_M 0x20000000
#define VDEC_BRDG_CTRL_CAUSE_INTR_DEC_RD_RR_DBG_SEI_S 30
#define VDEC_BRDG_CTRL_CAUSE_INTR_DEC_RD_RR_DBG_SEI_M 0x40000000

/* VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE */
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWLEN_GT_31_S 0
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWLEN_GT_31_M 0x1
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWLOCK_VIOL_S 1
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWLOCK_VIOL_M 0x2
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWBURST_VIOL_S 2
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWBURST_VIOL_M 0x4
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWADDR_SIZE_ALIGN_VIOL_S 3
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWADDR_SIZE_ALIGN_VIOL_M 0x8
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWSIZE_VIOL_S 4
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWSIZE_VIOL_M 0x10
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARLEN_GT_31_S 5
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARLEN_GT_31_M 0x20
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARLOCK_VIOL_S 6
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARLOCK_VIOL_M 0x40
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARBURST_VIOL_S 7
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARBURST_VIOL_M 0x80
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARADDR_SIZE_ALIGN_VIOL_S 8
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARADDR_SIZE_ALIGN_VIOL_M 0x100
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARSIZE_VIOL_S 9
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARSIZE_VIOL_M 0x200

/* VDEC_BRDG_CTRL_LBW_AXI_VIOL_CAUSE */
#define VDEC_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_READ_ACCESS_VIOL_S 0
#define VDEC_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_READ_ACCESS_VIOL_M 0x1
#define VDEC_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWLOCK_VIOL_S 1
#define VDEC_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWLOCK_VIOL_M 0x2
#define VDEC_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWADDR_ALIGN_VIOL_S 2
#define VDEC_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWADDR_ALIGN_VIOL_M 0x4
#define VDEC_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWSIZE_VIOL_S 3
#define VDEC_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWSIZE_VIOL_M 0x8
#define VDEC_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWLEN_VIOL_S 4
#define VDEC_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWLEN_VIOL_M 0x10
#define VDEC_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_WSTRB_VIOL_S 5
#define VDEC_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_WSTRB_VIOL_M 0x20

/* VDEC_BRDG_CTRL_AXI_VIOL_CLR_STICKY_TERM */
#define VDEC_BRDG_CTRL_AXI_VIOL_CLR_STICKY_TERM_HBW_AW_VIOL_CLR_S 0
#define VDEC_BRDG_CTRL_AXI_VIOL_CLR_STICKY_TERM_HBW_AW_VIOL_CLR_M 0x1
#define VDEC_BRDG_CTRL_AXI_VIOL_CLR_STICKY_TERM_HBW_AR_VIOL_CLR_S 1
#define VDEC_BRDG_CTRL_AXI_VIOL_CLR_STICKY_TERM_HBW_AR_VIOL_CLR_M 0x2
#define VDEC_BRDG_CTRL_AXI_VIOL_CLR_STICKY_TERM_LBW_AW_VIOL_CLR_S 2
#define VDEC_BRDG_CTRL_AXI_VIOL_CLR_STICKY_TERM_LBW_AW_VIOL_CLR_M 0x4

/* VDEC_BRDG_CTRL_CAUSE_INTR_MASK */
#define VDEC_BRDG_CTRL_CAUSE_INTR_MASK_VAL_S 0
#define VDEC_BRDG_CTRL_CAUSE_INTR_MASK_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_HBW_AXI_VIOL_MASK */
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_MASK_MASK_S 0
#define VDEC_BRDG_CTRL_HBW_AXI_VIOL_MASK_MASK_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_LBW_AXI_VIOL_MASK */
#define VDEC_BRDG_CTRL_LBW_AXI_VIOL_MASK_MASK_S 0
#define VDEC_BRDG_CTRL_LBW_AXI_VIOL_MASK_MASK_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_VCD_GIC_INTR_MASK */
#define VDEC_BRDG_CTRL_VCD_GIC_INTR_MASK_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_GIC_INTR_MASK_VAL_M 0x1

/* VDEC_BRDG_CTRL_L2C_GIC_INTR_MASK */
#define VDEC_BRDG_CTRL_L2C_GIC_INTR_MASK_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_GIC_INTR_MASK_VAL_M 0x1

/* VDEC_BRDG_CTRL_NRM_GIC_INTR_MASK */
#define VDEC_BRDG_CTRL_NRM_GIC_INTR_MASK_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_GIC_INTR_MASK_VAL_M 0x1

/* VDEC_BRDG_CTRL_ABNRM_GIC_INTR_MASK */
#define VDEC_BRDG_CTRL_ABNRM_GIC_INTR_MASK_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_GIC_INTR_MASK_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_HBW_AWPROT_0 */
#define VDEC_BRDG_CTRL_DEC_HBW_AWPROT_0_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_HBW_AWPROT_0_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_HBW_AWPROT_1 */
#define VDEC_BRDG_CTRL_DEC_HBW_AWPROT_1_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_HBW_AWPROT_1_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_HBW_AWPROT_2 */
#define VDEC_BRDG_CTRL_DEC_HBW_AWPROT_2_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_HBW_AWPROT_2_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_HBW_ARPROT_0 */
#define VDEC_BRDG_CTRL_DEC_HBW_ARPROT_0_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_HBW_ARPROT_0_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_HBW_ARPROT_1 */
#define VDEC_BRDG_CTRL_DEC_HBW_ARPROT_1_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_HBW_ARPROT_1_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_HBW_ARPROT_2 */
#define VDEC_BRDG_CTRL_DEC_HBW_ARPROT_2_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_HBW_ARPROT_2_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_LBW_AWPROT_0 */
#define VDEC_BRDG_CTRL_DEC_LBW_AWPROT_0_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_LBW_AWPROT_0_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_LBW_AWPROT_1 */
#define VDEC_BRDG_CTRL_DEC_LBW_AWPROT_1_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_LBW_AWPROT_1_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_LBW_AWPROT_2 */
#define VDEC_BRDG_CTRL_DEC_LBW_AWPROT_2_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_LBW_AWPROT_2_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_LBW_ARPROT_0 */
#define VDEC_BRDG_CTRL_DEC_LBW_ARPROT_0_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_LBW_ARPROT_0_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_LBW_ARPROT_1 */
#define VDEC_BRDG_CTRL_DEC_LBW_ARPROT_1_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_LBW_ARPROT_1_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_LBW_ARPROT_2 */
#define VDEC_BRDG_CTRL_DEC_LBW_ARPROT_2_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_LBW_ARPROT_2_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_LBW_SLV_AWPROT_0 */
#define VDEC_BRDG_CTRL_DEC_LBW_SLV_AWPROT_0_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_LBW_SLV_AWPROT_0_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_LBW_SLV_AWPROT_1 */
#define VDEC_BRDG_CTRL_DEC_LBW_SLV_AWPROT_1_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_LBW_SLV_AWPROT_1_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_LBW_SLV_AWPROT_2 */
#define VDEC_BRDG_CTRL_DEC_LBW_SLV_AWPROT_2_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_LBW_SLV_AWPROT_2_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_LBW_SLV_ARPROT_0 */
#define VDEC_BRDG_CTRL_DEC_LBW_SLV_ARPROT_0_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_LBW_SLV_ARPROT_0_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_LBW_SLV_ARPROT_1 */
#define VDEC_BRDG_CTRL_DEC_LBW_SLV_ARPROT_1_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_LBW_SLV_ARPROT_1_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_LBW_SLV_ARPROT_2 */
#define VDEC_BRDG_CTRL_DEC_LBW_SLV_ARPROT_2_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_LBW_SLV_ARPROT_2_VAL_M 0x1

/* VDEC_BRDG_CTRL_DEC_AXI_LEGAL_AXSIZE */
#define VDEC_BRDG_CTRL_DEC_AXI_LEGAL_AXSIZE_HBW_LEGAL_AWSIZE_S 0
#define VDEC_BRDG_CTRL_DEC_AXI_LEGAL_AXSIZE_HBW_LEGAL_AWSIZE_M 0x7
#define VDEC_BRDG_CTRL_DEC_AXI_LEGAL_AXSIZE_HBW_LEGAL_ARSIZE_S 3
#define VDEC_BRDG_CTRL_DEC_AXI_LEGAL_AXSIZE_HBW_LEGAL_ARSIZE_M 0x38
#define VDEC_BRDG_CTRL_DEC_AXI_LEGAL_AXSIZE_LBW_LEGAL_AWSIZE_S 6
#define VDEC_BRDG_CTRL_DEC_AXI_LEGAL_AXSIZE_LBW_LEGAL_AWSIZE_M 0x1C0

/* VDEC_BRDG_CTRL_ARC_MSG_MASK */
#define VDEC_BRDG_CTRL_ARC_MSG_MASK_VAL_S 0
#define VDEC_BRDG_CTRL_ARC_MSG_MASK_VAL_M 0x1

/* VDEC_BRDG_CTRL_ARC_START_LBW_WDATA */
#define VDEC_BRDG_CTRL_ARC_START_LBW_WDATA_VAL_S 0
#define VDEC_BRDG_CTRL_ARC_START_LBW_WDATA_VAL_M 0xFF

/* VDEC_BRDG_CTRL_ARC_FINISH_LBW_WDATA */
#define VDEC_BRDG_CTRL_ARC_FINISH_LBW_WDATA_VAL_S 0
#define VDEC_BRDG_CTRL_ARC_FINISH_LBW_WDATA_VAL_M 0xFF

/* VDEC_BRDG_CTRL_HWEVENT_TRACE_SEL */
#define VDEC_BRDG_CTRL_HWEVENT_TRACE_SEL_VAL_S 0
#define VDEC_BRDG_CTRL_HWEVENT_TRACE_SEL_VAL_M 0x7

/* VDEC_BRDG_CTRL_HWEVENT_TRACE_ADDR */
#define VDEC_BRDG_CTRL_HWEVENT_TRACE_ADDR_VAL_S 0
#define VDEC_BRDG_CTRL_HWEVENT_TRACE_ADDR_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DEC_FREE_RUN_CNT_L */
#define VDEC_BRDG_CTRL_DEC_FREE_RUN_CNT_L_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_FREE_RUN_CNT_L_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DEC_FREE_RUN_CNT_H */
#define VDEC_BRDG_CTRL_DEC_FREE_RUN_CNT_H_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_FREE_RUN_CNT_H_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DEC_FREE_RUN_SET_VALUE_L */
#define VDEC_BRDG_CTRL_DEC_FREE_RUN_SET_VALUE_L_IND_S 0
#define VDEC_BRDG_CTRL_DEC_FREE_RUN_SET_VALUE_L_IND_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DEC_FREE_RUN_SET_VALUE_H */
#define VDEC_BRDG_CTRL_DEC_FREE_RUN_SET_VALUE_H_IND_S 0
#define VDEC_BRDG_CTRL_DEC_FREE_RUN_SET_VALUE_H_IND_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DEC_BUSY_CNT_L */
#define VDEC_BRDG_CTRL_DEC_BUSY_CNT_L_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_BUSY_CNT_L_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DEC_BUSY_CNT_H */
#define VDEC_BRDG_CTRL_DEC_BUSY_CNT_H_VAL_S 0
#define VDEC_BRDG_CTRL_DEC_BUSY_CNT_H_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DEC_BUSY_SET_VALUE_L */
#define VDEC_BRDG_CTRL_DEC_BUSY_SET_VALUE_L_IND_S 0
#define VDEC_BRDG_CTRL_DEC_BUSY_SET_VALUE_L_IND_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DEC_BUSY_SET_VALUE_H */
#define VDEC_BRDG_CTRL_DEC_BUSY_SET_VALUE_H_IND_S 0
#define VDEC_BRDG_CTRL_DEC_BUSY_SET_VALUE_H_IND_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_STAT_CNTR_EN */
#define VDEC_BRDG_CTRL_STAT_CNTR_EN_VAL_S 0
#define VDEC_BRDG_CTRL_STAT_CNTR_EN_VAL_M 0x1

/* VDEC_BRDG_CTRL_VCD_INTR_MASK */
#define VDEC_BRDG_CTRL_VCD_INTR_MASK_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_INTR_MASK_VAL_M 0x1

/* VDEC_BRDG_CTRL_VCD_MSIX_FLOW_MASK */
#define VDEC_BRDG_CTRL_VCD_MSIX_FLOW_MASK_APB_WR_S 0
#define VDEC_BRDG_CTRL_VCD_MSIX_FLOW_MASK_APB_WR_M 0x1
#define VDEC_BRDG_CTRL_VCD_MSIX_FLOW_MASK_APB_RD_S 1
#define VDEC_BRDG_CTRL_VCD_MSIX_FLOW_MASK_APB_RD_M 0x2
#define VDEC_BRDG_CTRL_VCD_MSIX_FLOW_MASK_LBW_S 2
#define VDEC_BRDG_CTRL_VCD_MSIX_FLOW_MASK_LBW_M 0x4

/* VDEC_BRDG_CTRL_VCD_WAIT_CNTR */
#define VDEC_BRDG_CTRL_VCD_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_VCD_MSIX_WAIT_CNTR */
#define VDEC_BRDG_CTRL_VCD_MSIX_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_MSIX_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_STAT_VCD_WAIT_CNTR */
#define VDEC_BRDG_CTRL_STAT_VCD_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_STAT_VCD_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_STAT_VCD_MSIX_WAIT_CNTR */
#define VDEC_BRDG_CTRL_STAT_VCD_MSIX_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_STAT_VCD_MSIX_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_VCD_SWREG1_ADDR */
#define VDEC_BRDG_CTRL_VCD_SWREG1_ADDR_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_SWREG1_ADDR_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_VCD_APB_WR_ADDR */
#define VDEC_BRDG_CTRL_VCD_APB_WR_ADDR_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_APB_WR_ADDR_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_VCD_APB_WR_DATA */
#define VDEC_BRDG_CTRL_VCD_APB_WR_DATA_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_APB_WR_DATA_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWPROT_0 */
#define VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWPROT_0_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWPROT_0_VAL_M 0x1

/* VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWPROT_1 */
#define VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWPROT_1_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWPROT_1_VAL_M 0x1

/* VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWPROT_2 */
#define VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWPROT_2_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWPROT_2_VAL_M 0x1

/* VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWADDR_L */
#define VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWADDR_L_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWADDR_L_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWADDR_H */
#define VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWADDR_H_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_CPLQ_HBW_AWADDR_H_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_VCD_MSIX_LBW_AWPROT_0 */
#define VDEC_BRDG_CTRL_VCD_MSIX_LBW_AWPROT_0_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_MSIX_LBW_AWPROT_0_VAL_M 0x1

/* VDEC_BRDG_CTRL_VCD_MSIX_LBW_AWPROT_1 */
#define VDEC_BRDG_CTRL_VCD_MSIX_LBW_AWPROT_1_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_MSIX_LBW_AWPROT_1_VAL_M 0x1

/* VDEC_BRDG_CTRL_VCD_MSIX_LBW_AWPROT_2 */
#define VDEC_BRDG_CTRL_VCD_MSIX_LBW_AWPROT_2_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_MSIX_LBW_AWPROT_2_VAL_M 0x1

/* VDEC_BRDG_CTRL_VCD_MSIX_LBW_AWADDR */
#define VDEC_BRDG_CTRL_VCD_MSIX_LBW_AWADDR_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_MSIX_LBW_AWADDR_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_VCD_MSIX_LBW_WDATA */
#define VDEC_BRDG_CTRL_VCD_MSIX_LBW_WDATA_VAL_S 0
#define VDEC_BRDG_CTRL_VCD_MSIX_LBW_WDATA_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_L2C_INTR_MASK */
#define VDEC_BRDG_CTRL_L2C_INTR_MASK_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_INTR_MASK_VAL_M 0x1

/* VDEC_BRDG_CTRL_L2C_MSIX_FLOW_MASK */
#define VDEC_BRDG_CTRL_L2C_MSIX_FLOW_MASK_APB_WR_S 0
#define VDEC_BRDG_CTRL_L2C_MSIX_FLOW_MASK_APB_WR_M 0x1
#define VDEC_BRDG_CTRL_L2C_MSIX_FLOW_MASK_APB_RD_S 1
#define VDEC_BRDG_CTRL_L2C_MSIX_FLOW_MASK_APB_RD_M 0x2
#define VDEC_BRDG_CTRL_L2C_MSIX_FLOW_MASK_LBW_S 2
#define VDEC_BRDG_CTRL_L2C_MSIX_FLOW_MASK_LBW_M 0x4

/* VDEC_BRDG_CTRL_L2C_WAIT_CNTR */
#define VDEC_BRDG_CTRL_L2C_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_L2C_MSIX_WAIT_CNTR */
#define VDEC_BRDG_CTRL_L2C_MSIX_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_MSIX_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_STAT_L2C_WAIT_CNTR */
#define VDEC_BRDG_CTRL_STAT_L2C_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_STAT_L2C_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_STAT_L2C_MSIX_WAIT_CNTR */
#define VDEC_BRDG_CTRL_STAT_L2C_MSIX_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_STAT_L2C_MSIX_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_L2C_SWREG1_ADDR */
#define VDEC_BRDG_CTRL_L2C_SWREG1_ADDR_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_SWREG1_ADDR_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_L2C_APB_WR_ADDR */
#define VDEC_BRDG_CTRL_L2C_APB_WR_ADDR_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_APB_WR_ADDR_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_L2C_APB_WR_DATA */
#define VDEC_BRDG_CTRL_L2C_APB_WR_DATA_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_APB_WR_DATA_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWPROT_0 */
#define VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWPROT_0_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWPROT_0_VAL_M 0x1

/* VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWPROT_1 */
#define VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWPROT_1_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWPROT_1_VAL_M 0x1

/* VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWPROT_2 */
#define VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWPROT_2_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWPROT_2_VAL_M 0x1

/* VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWADDR_L */
#define VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWADDR_L_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWADDR_L_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWADDR_H */
#define VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWADDR_H_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_CPLQ_HBW_AWADDR_H_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_L2C_MSIX_LBW_AWPROT_0 */
#define VDEC_BRDG_CTRL_L2C_MSIX_LBW_AWPROT_0_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_MSIX_LBW_AWPROT_0_VAL_M 0x1

/* VDEC_BRDG_CTRL_L2C_MSIX_LBW_AWPROT_1 */
#define VDEC_BRDG_CTRL_L2C_MSIX_LBW_AWPROT_1_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_MSIX_LBW_AWPROT_1_VAL_M 0x1

/* VDEC_BRDG_CTRL_L2C_MSIX_LBW_AWPROT_2 */
#define VDEC_BRDG_CTRL_L2C_MSIX_LBW_AWPROT_2_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_MSIX_LBW_AWPROT_2_VAL_M 0x1

/* VDEC_BRDG_CTRL_L2C_MSIX_LBW_AWADDR */
#define VDEC_BRDG_CTRL_L2C_MSIX_LBW_AWADDR_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_MSIX_LBW_AWADDR_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_L2C_MSIX_LBW_WDATA */
#define VDEC_BRDG_CTRL_L2C_MSIX_LBW_WDATA_VAL_S 0
#define VDEC_BRDG_CTRL_L2C_MSIX_LBW_WDATA_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_NRM_INTR_MASK */
#define VDEC_BRDG_CTRL_NRM_INTR_MASK_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_INTR_MASK_VAL_M 0x1

/* VDEC_BRDG_CTRL_NRM_MSIX_FLOW_MASK */
#define VDEC_BRDG_CTRL_NRM_MSIX_FLOW_MASK_APB_WR_S 0
#define VDEC_BRDG_CTRL_NRM_MSIX_FLOW_MASK_APB_WR_M 0x1
#define VDEC_BRDG_CTRL_NRM_MSIX_FLOW_MASK_APB_RD_S 1
#define VDEC_BRDG_CTRL_NRM_MSIX_FLOW_MASK_APB_RD_M 0x2
#define VDEC_BRDG_CTRL_NRM_MSIX_FLOW_MASK_LBW_S 2
#define VDEC_BRDG_CTRL_NRM_MSIX_FLOW_MASK_LBW_M 0x4

/* VDEC_BRDG_CTRL_NRM_WAIT_CNTR */
#define VDEC_BRDG_CTRL_NRM_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_NRM_MSIX_WAIT_CNTR */
#define VDEC_BRDG_CTRL_NRM_MSIX_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_MSIX_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_STAT_NRM_WAIT_CNTR */
#define VDEC_BRDG_CTRL_STAT_NRM_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_STAT_NRM_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_STAT_NRM_MSIX_WAIT_CNTR */
#define VDEC_BRDG_CTRL_STAT_NRM_MSIX_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_STAT_NRM_MSIX_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_NRM_SWREG1_ADDR */
#define VDEC_BRDG_CTRL_NRM_SWREG1_ADDR_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_SWREG1_ADDR_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_NRM_APB_WR_ADDR */
#define VDEC_BRDG_CTRL_NRM_APB_WR_ADDR_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_APB_WR_ADDR_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_NRM_APB_WR_DATA */
#define VDEC_BRDG_CTRL_NRM_APB_WR_DATA_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_APB_WR_DATA_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWPROT_0 */
#define VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWPROT_0_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWPROT_0_VAL_M 0x1

/* VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWPROT_1 */
#define VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWPROT_1_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWPROT_1_VAL_M 0x1

/* VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWPROT_2 */
#define VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWPROT_2_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWPROT_2_VAL_M 0x1

/* VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWADDR_L */
#define VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWADDR_L_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWADDR_L_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWADDR_H */
#define VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWADDR_H_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_CPLQ_HBW_AWADDR_H_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_NRM_MSIX_LBW_AWPROT_0 */
#define VDEC_BRDG_CTRL_NRM_MSIX_LBW_AWPROT_0_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_MSIX_LBW_AWPROT_0_VAL_M 0x1

/* VDEC_BRDG_CTRL_NRM_MSIX_LBW_AWPROT_1 */
#define VDEC_BRDG_CTRL_NRM_MSIX_LBW_AWPROT_1_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_MSIX_LBW_AWPROT_1_VAL_M 0x1

/* VDEC_BRDG_CTRL_NRM_MSIX_LBW_AWPROT_2 */
#define VDEC_BRDG_CTRL_NRM_MSIX_LBW_AWPROT_2_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_MSIX_LBW_AWPROT_2_VAL_M 0x1

/* VDEC_BRDG_CTRL_NRM_MSIX_LBW_AWADDR */
#define VDEC_BRDG_CTRL_NRM_MSIX_LBW_AWADDR_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_MSIX_LBW_AWADDR_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_NRM_MSIX_LBW_WDATA */
#define VDEC_BRDG_CTRL_NRM_MSIX_LBW_WDATA_VAL_S 0
#define VDEC_BRDG_CTRL_NRM_MSIX_LBW_WDATA_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_ABNRM_INTR_MASK */
#define VDEC_BRDG_CTRL_ABNRM_INTR_MASK_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_INTR_MASK_VAL_M 0x1

/* VDEC_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK */
#define VDEC_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK_APB_WR_S 0
#define VDEC_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK_APB_WR_M 0x1
#define VDEC_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK_APB_RD_S 1
#define VDEC_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK_APB_RD_M 0x2
#define VDEC_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK_LBW_S 2
#define VDEC_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK_LBW_M 0x4

/* VDEC_BRDG_CTRL_ABNRM_WAIT_CNTR */
#define VDEC_BRDG_CTRL_ABNRM_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_ABNRM_MSIX_WAIT_CNTR */
#define VDEC_BRDG_CTRL_ABNRM_MSIX_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_MSIX_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_STAT_ABNRM_WAIT_CNTR */
#define VDEC_BRDG_CTRL_STAT_ABNRM_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_STAT_ABNRM_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_STAT_ABNRM_MSIX_WAIT_CNTR */
#define VDEC_BRDG_CTRL_STAT_ABNRM_MSIX_WAIT_CNTR_VAL_S 0
#define VDEC_BRDG_CTRL_STAT_ABNRM_MSIX_WAIT_CNTR_VAL_M 0xFFFFFF

/* VDEC_BRDG_CTRL_ABNRM_SWREG1_ADDR */
#define VDEC_BRDG_CTRL_ABNRM_SWREG1_ADDR_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_SWREG1_ADDR_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_ABNRM_APB_WR_ADDR */
#define VDEC_BRDG_CTRL_ABNRM_APB_WR_ADDR_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_APB_WR_ADDR_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_ABNRM_APB_WR_DATA */
#define VDEC_BRDG_CTRL_ABNRM_APB_WR_DATA_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_APB_WR_DATA_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWPROT_0 */
#define VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWPROT_0_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWPROT_0_VAL_M 0x1

/* VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWPROT_1 */
#define VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWPROT_1_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWPROT_1_VAL_M 0x1

/* VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWPROT_2 */
#define VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWPROT_2_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWPROT_2_VAL_M 0x1

/* VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWADDR_L */
#define VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWADDR_L_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWADDR_L_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWADDR_H */
#define VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWADDR_H_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_CPLQ_HBW_AWADDR_H_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_AWPROT_0 */
#define VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_AWPROT_0_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_AWPROT_0_VAL_M 0x1

/* VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_AWPROT_1 */
#define VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_AWPROT_1_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_AWPROT_1_VAL_M 0x1

/* VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_AWPROT_2 */
#define VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_AWPROT_2_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_AWPROT_2_VAL_M 0x1

/* VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_AWADDR */
#define VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_AWADDR_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_AWADDR_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_WDATA */
#define VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_WDATA_VAL_S 0
#define VDEC_BRDG_CTRL_ABNRM_MSIX_LBW_WDATA_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_AXI_SPLIT_BRESP_ERR_ID */
#define VDEC_BRDG_CTRL_AXI_SPLIT_BRESP_ERR_ID_ID_S 0
#define VDEC_BRDG_CTRL_AXI_SPLIT_BRESP_ERR_ID_ID_M 0xFF

/* VDEC_BRDG_CTRL_AXI_SPLIT_CFG */
#define VDEC_BRDG_CTRL_AXI_SPLIT_CFG_FORCE_RESP_OK_S 0
#define VDEC_BRDG_CTRL_AXI_SPLIT_CFG_FORCE_RESP_OK_M 0x1
#define VDEC_BRDG_CTRL_AXI_SPLIT_CFG_FORCE_WR_BUF_S 1
#define VDEC_BRDG_CTRL_AXI_SPLIT_CFG_FORCE_WR_BUF_M 0x2
#define VDEC_BRDG_CTRL_AXI_SPLIT_CFG_NUM_RD_OS_S 8
#define VDEC_BRDG_CTRL_AXI_SPLIT_CFG_NUM_RD_OS_M 0xFF00
#define VDEC_BRDG_CTRL_AXI_SPLIT_CFG_NUM_WR_OS_S 16
#define VDEC_BRDG_CTRL_AXI_SPLIT_CFG_NUM_WR_OS_M 0xFF0000

/* VDEC_BRDG_CTRL_AXI_SPLIT_NO_WR_INFLIGHT */
#define VDEC_BRDG_CTRL_AXI_SPLIT_NO_WR_INFLIGHT_VAL_S 0
#define VDEC_BRDG_CTRL_AXI_SPLIT_NO_WR_INFLIGHT_VAL_M 0x1

/* VDEC_BRDG_CTRL_HWEVENT_MASK */
#define VDEC_BRDG_CTRL_HWEVENT_MASK_MASK_S 1
#define VDEC_BRDG_CTRL_HWEVENT_MASK_MASK_M 0x2

/* VDEC_BRDG_CTRL_HWEVENT_CNTXT */
#define VDEC_BRDG_CTRL_HWEVENT_CNTXT_VAL_S 0
#define VDEC_BRDG_CTRL_HWEVENT_CNTXT_VAL_M 0xFFFF

/* VDEC_BRDG_CTRL_LBW_SLV_TERM_ERR_RESP */
#define VDEC_BRDG_CTRL_LBW_SLV_TERM_ERR_RESP_ERR_RESP_S 0
#define VDEC_BRDG_CTRL_LBW_SLV_TERM_ERR_RESP_ERR_RESP_M 0x1

/* VDEC_BRDG_CTRL_LBW_MSTR_TERM_ERR_RESP */
#define VDEC_BRDG_CTRL_LBW_MSTR_TERM_ERR_RESP_ERR_RESP_S 0
#define VDEC_BRDG_CTRL_LBW_MSTR_TERM_ERR_RESP_ERR_RESP_M 0x3

/* VDEC_BRDG_CTRL_DEC_HBW_MSTR_ERR_RESP */
#define VDEC_BRDG_CTRL_DEC_HBW_MSTR_ERR_RESP_WR_ERR_RESP_S 0
#define VDEC_BRDG_CTRL_DEC_HBW_MSTR_ERR_RESP_WR_ERR_RESP_M 0x3
#define VDEC_BRDG_CTRL_DEC_HBW_MSTR_ERR_RESP_RD_ERR_RESP_S 2
#define VDEC_BRDG_CTRL_DEC_HBW_MSTR_ERR_RESP_RD_ERR_RESP_M 0xC

/* VDEC_BRDG_CTRL_HBW_VIOL_TERM_STATUS */
#define VDEC_BRDG_CTRL_HBW_VIOL_TERM_STATUS_AW_STA_S 0
#define VDEC_BRDG_CTRL_HBW_VIOL_TERM_STATUS_AW_STA_M 0x1
#define VDEC_BRDG_CTRL_HBW_VIOL_TERM_STATUS_AR_STA_S 1
#define VDEC_BRDG_CTRL_HBW_VIOL_TERM_STATUS_AR_STA_M 0x2

/* VDEC_BRDG_CTRL_HBW_LAST_AWADDR_TERM_L */
#define VDEC_BRDG_CTRL_HBW_LAST_AWADDR_TERM_L_VAL_S 0
#define VDEC_BRDG_CTRL_HBW_LAST_AWADDR_TERM_L_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_HBW_LAST_AWADDR_TERM_H */
#define VDEC_BRDG_CTRL_HBW_LAST_AWADDR_TERM_H_VAL_S 0
#define VDEC_BRDG_CTRL_HBW_LAST_AWADDR_TERM_H_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_HBW_LAST_ARADDR_TERM_L */
#define VDEC_BRDG_CTRL_HBW_LAST_ARADDR_TERM_L_VAL_S 0
#define VDEC_BRDG_CTRL_HBW_LAST_ARADDR_TERM_L_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_HBW_LAST_ARADDR_TERM_H */
#define VDEC_BRDG_CTRL_HBW_LAST_ARADDR_TERM_H_VAL_S 0
#define VDEC_BRDG_CTRL_HBW_LAST_ARADDR_TERM_H_VAL_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DBG_APB_WIN */
#define VDEC_BRDG_CTRL_DBG_APB_WIN_EN_S 0
#define VDEC_BRDG_CTRL_DBG_APB_WIN_EN_M 0x1

/* VDEC_BRDG_CTRL_DBG_APB_MASK */
#define VDEC_BRDG_CTRL_DBG_APB_MASK_ADDR_S 0
#define VDEC_BRDG_CTRL_DBG_APB_MASK_ADDR_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DBG_APB_BASE0 */
#define VDEC_BRDG_CTRL_DBG_APB_BASE0_ADDR_S 0
#define VDEC_BRDG_CTRL_DBG_APB_BASE0_ADDR_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DBG_APB_BASE1 */
#define VDEC_BRDG_CTRL_DBG_APB_BASE1_ADDR_S 0
#define VDEC_BRDG_CTRL_DBG_APB_BASE1_ADDR_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DBG_APB_BASE2 */
#define VDEC_BRDG_CTRL_DBG_APB_BASE2_ADDR_S 0
#define VDEC_BRDG_CTRL_DBG_APB_BASE2_ADDR_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DBG_APB_BASE3 */
#define VDEC_BRDG_CTRL_DBG_APB_BASE3_ADDR_S 0
#define VDEC_BRDG_CTRL_DBG_APB_BASE3_ADDR_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DBG_APB_BASE4 */
#define VDEC_BRDG_CTRL_DBG_APB_BASE4_ADDR_S 0
#define VDEC_BRDG_CTRL_DBG_APB_BASE4_ADDR_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DBG_APB_BASE5 */
#define VDEC_BRDG_CTRL_DBG_APB_BASE5_ADDR_S 0
#define VDEC_BRDG_CTRL_DBG_APB_BASE5_ADDR_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DBG_APB_BASE6 */
#define VDEC_BRDG_CTRL_DBG_APB_BASE6_ADDR_S 0
#define VDEC_BRDG_CTRL_DBG_APB_BASE6_ADDR_M 0xFFFFFFFF

/* VDEC_BRDG_CTRL_DBG_APB_BASE7 */
#define VDEC_BRDG_CTRL_DBG_APB_BASE7_ADDR_S 0
#define VDEC_BRDG_CTRL_DBG_APB_BASE7_ADDR_M 0xFFFFFFFF

#endif /* ASIC_REG_VDEC_BRDG_CTRL_MASKS_H_ */
