/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2019-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

#ifndef GRECO_MASKS_H_
#define GRECO_MASKS_H_

#include "../include/greco/asic_reg/greco_regs.h"

/* PCI CONFIGURATION SPACE */
#define mmPCI_CONFIG_ELBI_ADDR		0xFF0
#define mmPCI_CONFIG_ELBI_DATA		0xFF4
#define mmPCI_CONFIG_ELBI_CTRL		0xFF8
#define PCI_CONFIG_ELBI_CTRL_WRITE	(1 << 31)

#define mmPCI_CONFIG_ELBI_STS		0xFFC
#define PCI_CONFIG_ELBI_STS_ERR		(1 << 30)
#define PCI_CONFIG_ELBI_STS_DONE	(1 << 31)
#define PCI_CONFIG_ELBI_STS_MASK	(PCI_CONFIG_ELBI_STS_ERR | \
					PCI_CONFIG_ELBI_STS_DONE)

/* Useful masks for bits in various registers */
#define QMAN_GLBL_ERR_CFG_MSG_EN_MASK	\
	((0xF << DCORE0_PDMA0_QM_GLBL_ERR_CFG_PQF_ERR_MSG_EN_SHIFT) | \
	(0x1F << DCORE0_PDMA0_QM_GLBL_ERR_CFG_CQF_ERR_MSG_EN_SHIFT) | \
	(0x1F << DCORE0_PDMA0_QM_GLBL_ERR_CFG_CP_ERR_MSG_EN_SHIFT))

#define QMAN_GLBL_ERR_CFG_STOP_ON_ERR_EN_MASK	\
	((0xF << DCORE0_PDMA0_QM_GLBL_ERR_CFG_PQF_STOP_ON_ERR_SHIFT) | \
	(0x1F << DCORE0_PDMA0_QM_GLBL_ERR_CFG_CQF_STOP_ON_ERR_SHIFT) | \
	(0x1F << DCORE0_PDMA0_QM_GLBL_ERR_CFG_CP_STOP_ON_ERR_SHIFT) | \
	(0x1 << DCORE0_PDMA0_QM_GLBL_ERR_CFG_ARB_STOP_ON_ERR_SHIFT))

#define QMAN_MAKE_TRUSTED	\
	((0xF << DCORE0_PDMA0_QM_GLBL_PROT_PQF_SHIFT) | \
	(0x1 << DCORE0_PDMA0_QM_GLBL_PROT_ERR_SHIFT) | \
	(0x1 << DCORE0_PDMA0_QM_GLBL_PROT_PQC_SHIFT))

#define QMAN_MAKE_TRUSTED_TEST_MODE	\
	((0xF << DCORE0_PDMA0_QM_GLBL_PROT_PQF_SHIFT) | \
	(0xF << DCORE0_PDMA0_QM_GLBL_PROT_CQF_SHIFT) | \
	(0x1 << DCORE0_PDMA0_QM_GLBL_PROT_ERR_SHIFT) | \
	(0x1 << DCORE0_PDMA0_QM_GLBL_PROT_PQC_SHIFT))

#define QMAN_ENABLE		\
	((0xF << DCORE0_PDMA0_QM_GLBL_CFG0_PQF_EN_SHIFT) | \
	(0x1F << DCORE0_PDMA0_QM_GLBL_CFG0_CQF_EN_SHIFT) | \
	(0x1F << DCORE0_PDMA0_QM_GLBL_CFG0_CP_EN_SHIFT))

#define QM_GLBL_CFG1_PQF_STOP	\
	DCORE0_PDMA0_QM_GLBL_CFG1_PQF_STOP_MASK

#define QM_GLBL_CFG1_CQF_STOP	\
	DCORE0_PDMA0_QM_GLBL_CFG1_CQF_STOP_MASK

#define QM_GLBL_CFG1_CP_STOP	\
	DCORE0_PDMA0_QM_GLBL_CFG1_CP_STOP_MASK

#define QM_PQC_LBW_WDATA	\
	((1 << DCORE0_SYNC_MNGR_OBJS_SOB_OBJ_VAL_SHIFT) | \
	(1 << DCORE0_SYNC_MNGR_OBJS_SOB_OBJ_INC_SHIFT))

#define TPC_BINNING		\
	(DCORE0_TPCIF_RTR3_CTRL_MODE_TPC_BIN_D0_MASK | \
	DCORE0_TPCIF_RTR3_CTRL_MODE_TPC_BIN_D1_MASK)

#define DEC_BINNING		\
	(DCORE0_TPCIF_RTR3_CTRL_MODE_DEC04_BIN_MASK | \
	DCORE0_TPCIF_RTR3_CTRL_MODE_DEC59_BIN_MASK)

#define PSOC_ETR_AXICTL_PROTCTRLBIT1_SHIFT	1
#define PSOC_ETR_AXICTL_PROTCTRLBIT0_MASK	0x1
#define PSOC_ETR_AXICTL_PROTCTRLBIT1_MASK	0x2
#define PSOC_ETR_AXICTL_WRBURSTLEN_MASK		0xF00

#define MMU_STATIC_MULTI_PAGE_SIZE_HOP3_PAGE_SIZE_MASK \
	REG_FIELD_MASK(DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE, HOP3_PAGE_SIZE)
#define MMU_STATIC_MULTI_PAGE_SIZE_CFG_8_BITS_HOP_MODE_EN_MASK \
	REG_FIELD_MASK(DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE, \
			CFG_8_BITS_HOP_MODE_EN)
#define STLB_HOP_CONFIGURATION_LAST_HOP_MASK \
	REG_FIELD_MASK(DCORE0_HMMU0_STLB_HOP_CONFIGURATION, LAST_HOP)
#define STLB_HOP_CONFIGURATION_ONLY_LARGE_PAGE_MASK \
	REG_FIELD_MASK(DCORE0_HMMU0_STLB_HOP_CONFIGURATION, ONLY_LARGE_PAGE)

#define CPU_RESET_ASSERT	(\
			1 << CPU_CA53_CFG_ARM_RST_CONTROL_NMBISTRESET_SHIFT)

#define CPU_RESET_CORE0_DEASSERT	(\
			1 << CPU_CA53_CFG_ARM_RST_CONTROL_NCPUPORESET_SHIFT |\
			1 << CPU_CA53_CFG_ARM_RST_CONTROL_NCORERESET_SHIFT |\
			1 << CPU_CA53_CFG_ARM_RST_CONTROL_NL2RESET_SHIFT |\
			1 << CPU_CA53_CFG_ARM_RST_CONTROL_NMBISTRESET_SHIFT)

#define QM_ARB_ERR_MSG_EN_CHOISE_OVF_MASK	0x1
#define QM_ARB_ERR_MSG_EN_CHOISE_WDT_MASK	0x2
#define QM_ARB_ERR_MSG_EN_AXI_LBW_ERR_MASK	0x4

#define QM_ARB_ERR_MSG_EN_MASK		(\
					QM_ARB_ERR_MSG_EN_CHOISE_OVF_MASK |\
					QM_ARB_ERR_MSG_EN_CHOISE_WDT_MASK |\
					QM_ARB_ERR_MSG_EN_AXI_LBW_ERR_MASK)

#define PCIE_AUX_FLR_CTRL_HW_CTRL_MASK	0x1
#define PCIE_AUX_FLR_CTRL_INT_MASK_MASK	0x2

#define PLL_DIV_CFG_FBDIV_MASK		GENMASK(11, 0)
#define PLL_DIV_CFG_POSTDIV1_MASK	GENMASK(18, 16)
#define PLL_DIV_CFG_POSTDIV2_MASK	GENMASK(22, 20)
#define PLL_DIV_CFG_REFDIV_MASK		GENMASK(29, 24)

#define PLL_CTRL_DIV_SEL_REF_CLK		0
#define PLL_CTRL_DIV_SEL_PLL_CLK		1
#define PLL_CTRL_DIV_SEL_DIVIDED_REF_CLK	2
#define PLL_CTRL_DIV_SEL_DIVIDED_PLL_CLK	3

/* QM_IDLE_MASK is valid for all engines QM idle check */
#define QM_IDLE_MASK	(DCORE0_DDMA_QM_GLBL_STS0_PQF_IDLE_MASK | \
			DCORE0_DDMA_QM_GLBL_STS0_CQF_IDLE_MASK | \
			DCORE0_DDMA_QM_GLBL_STS0_CP_IDLE_MASK)

/* CGM_IDLE_MASK is valid for all engines CGM idle check */
#define CGM_IDLE_MASK	DCORE0_DDMA_CORE_KDMA_CGM_STS_AGENT_IDLE_MASK

/*
 * DCORE0_TPC0_CFG_STATUS_SB_EMPTY_MASK is not in TPC_IDLE_MASK due to a bug
 * in setting its value
 */
#define TPC_IDLE_MASK	(DCORE0_TPC0_CFG_STATUS_SCALAR_PIPE_EMPTY_MASK | \
			DCORE0_TPC0_CFG_STATUS_VECTOR_PIPE_EMPTY_MASK | \
			DCORE0_TPC0_CFG_STATUS_IQ_EMPTY_MASK | \
			DCORE0_TPC0_CFG_STATUS_QM_IDLE_MASK | \
			DCORE0_TPC0_CFG_STATUS_QM_RDY_MASK)

#define DCORE0_MME_CTRL_LO_ARCH_STATUS_SB_A_EMPTY_MASK		0x100
#define DCORE0_MME_CTRL_LO_ARCH_STATUS_SB_B_EMPTY_MASK		0x200
#define DCORE0_MME_CTRL_LO_ARCH_STATUS_SB_L_EMPTY_MASK		0x400
#define DCORE0_MME_CTRL_LO_ARCH_STATUS_SB_CIN_EMPTY_MASK	0x800
#define DCORE0_MME_CTRL_LO_ARCH_STATUS_SM_IDLE_MASK		0x1000
#define DCORE0_MME_CTRL_LO_ARCH_STATUS_WBC_AXI_IDLE_MASK	0x2000
#define DCORE0_MME_CTRL_LO_ARCH_STATUS_QM_RDY_MASK		0x80000000

/* Ignore DCORE0_MME_CTRL_LO_ARCH_STATUS_QM_IDLE_MASK due to bug in status */
#define MME_ARCH_IDLE_MASK	\
			(DCORE0_MME_CTRL_LO_ARCH_STATUS_SB_A_EMPTY_MASK | \
			DCORE0_MME_CTRL_LO_ARCH_STATUS_SB_B_EMPTY_MASK | \
			DCORE0_MME_CTRL_LO_ARCH_STATUS_SB_L_EMPTY_MASK | \
			DCORE0_MME_CTRL_LO_ARCH_STATUS_SB_CIN_EMPTY_MASK | \
			DCORE0_MME_CTRL_LO_ARCH_STATUS_SM_IDLE_MASK | \
			DCORE0_MME_CTRL_LO_ARCH_STATUS_WBC_AXI_IDLE_MASK | \
			DCORE0_MME_CTRL_LO_ARCH_STATUS_QM_RDY_MASK)


#define AXUSER_HB_SEC_ASID_MASK	0x3FF
#define AXUSER_HB_SEC_MMBP_MASK	0x400

#define MMUBP_ASID_MASK	(AXUSER_HB_SEC_ASID_MASK | AXUSER_HB_SEC_MMBP_MASK)

#define ROT_MSS_HALT_WBC_MASK	BIT(0)
#define ROT_MSS_HALT_SB_MASK	BIT(1)

#endif /* GRECO_MASKS_H_ */
