/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE1_XBAR_DMA_PLL_ASIF_SLV_REGS_H_
#define ASIC_REG_DCORE1_XBAR_DMA_PLL_ASIF_SLV_REGS_H_

/*
 *****************************************
 *   DCORE1_XBAR_DMA_PLL_ASIF_SLV
 *   (Prototype: ASIF_SLV)
 *****************************************
 */

#define mmDCORE1_XBAR_DMA_PLL_ASIF_SLV_ASIF_SLV_STATUS 0x4D51360

#define mmDCORE1_XBAR_DMA_PLL_ASIF_SLV_ASIF_SLV_CFG 0x4D51364

#define mmDCORE1_XBAR_DMA_PLL_ASIF_SLV_ASIF_SLV_ERROR 0x4D51368

#define mmDCORE1_XBAR_DMA_PLL_ASIF_SLV_ASIF_SLV_INTR_MASK 0x4D5136C

#define mmDCORE1_XBAR_DMA_PLL_ASIF_SLV_ASIF_CORE_CFG 0x4D51370

#define mmDCORE1_XBAR_DMA_PLL_ASIF_SLV_ASIF_CORE_DBG_CNT 0x4D51374

#define mmDCORE1_XBAR_DMA_PLL_ASIF_SLV_ASIF_CORE_DBG_CNT_CLR 0x4D51378

#define mmDCORE1_XBAR_DMA_PLL_ASIF_SLV_ASIF_CORE_TIMEOUT_CFG 0x4D5137C

#define mmDCORE1_XBAR_DMA_PLL_ASIF_SLV_ASIF_ERR_INTR_CAUSE 0x4D51380

#define mmDCORE1_XBAR_DMA_PLL_ASIF_SLV_ASIF_ERR_INTR_CLEAR 0x4D51384

#define mmDCORE1_XBAR_DMA_PLL_ASIF_SLV_ASIF_ERR_INTR_MASK 0x4D51388

#define mmDCORE1_XBAR_DMA_PLL_ASIF_SLV_ASIF_SLV_DBG_0 0x4D51390

#define mmDCORE1_XBAR_DMA_PLL_ASIF_SLV_ASIF_SLV_DBG_1 0x4D51394

#endif /* ASIC_REG_DCORE1_XBAR_DMA_PLL_ASIF_SLV_REGS_H_ */
