/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_XBAR_MMU_PLL_ASIF_SLV_REGS_H_
#define ASIC_REG_DCORE0_XBAR_MMU_PLL_ASIF_SLV_REGS_H_

/*
 *****************************************
 *   DCORE0_XBAR_MMU_PLL_ASIF_SLV
 *   (Prototype: ASIF_SLV)
 *****************************************
 */

#define mmDCORE0_XBAR_MMU_PLL_ASIF_SLV_ASIF_SLV_STATUS 0x4D42360

#define mmDCORE0_XBAR_MMU_PLL_ASIF_SLV_ASIF_SLV_CFG 0x4D42364

#define mmDCORE0_XBAR_MMU_PLL_ASIF_SLV_ASIF_SLV_ERROR 0x4D42368

#define mmDCORE0_XBAR_MMU_PLL_ASIF_SLV_ASIF_SLV_INTR_MASK 0x4D4236C

#define mmDCORE0_XBAR_MMU_PLL_ASIF_SLV_ASIF_CORE_CFG 0x4D42370

#define mmDCORE0_XBAR_MMU_PLL_ASIF_SLV_ASIF_CORE_DBG_CNT 0x4D42374

#define mmDCORE0_XBAR_MMU_PLL_ASIF_SLV_ASIF_CORE_DBG_CNT_CLR 0x4D42378

#define mmDCORE0_XBAR_MMU_PLL_ASIF_SLV_ASIF_CORE_TIMEOUT_CFG 0x4D4237C

#define mmDCORE0_XBAR_MMU_PLL_ASIF_SLV_ASIF_ERR_INTR_CAUSE 0x4D42380

#define mmDCORE0_XBAR_MMU_PLL_ASIF_SLV_ASIF_ERR_INTR_CLEAR 0x4D42384

#define mmDCORE0_XBAR_MMU_PLL_ASIF_SLV_ASIF_ERR_INTR_MASK 0x4D42388

#define mmDCORE0_XBAR_MMU_PLL_ASIF_SLV_ASIF_SLV_DBG_0 0x4D42390

#define mmDCORE0_XBAR_MMU_PLL_ASIF_SLV_ASIF_SLV_DBG_1 0x4D42394

#endif /* ASIC_REG_DCORE0_XBAR_MMU_PLL_ASIF_SLV_REGS_H_ */
