/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_HBM0_MC0BIST0_MASKS_H_
#define ASIC_REG_HBM0_MC0BIST0_MASKS_H_

/*
 *****************************************
 *   HBM0_MC0BIST0
 *   (Prototype: AXI_MEM_BIST)
 *****************************************
 */

/* HBM0_MC0BIST0_BIST_START */
#define HBM0_MC0BIST0_BIST_START_VAL_SHIFT 0
#define HBM0_MC0BIST0_BIST_START_VAL_MASK 0x1

/* HBM0_MC0BIST0_WR_REP_NUM */
#define HBM0_MC0BIST0_WR_REP_NUM_VAL_SHIFT 0
#define HBM0_MC0BIST0_WR_REP_NUM_VAL_MASK 0xFFFF

/* HBM0_MC0BIST0_WR_DELAY */
#define HBM0_MC0BIST0_WR_DELAY_VAL_SHIFT 0
#define HBM0_MC0BIST0_WR_DELAY_VAL_MASK 0xFFFF

/* HBM0_MC0BIST0_WR_BLOCK_SIZE */
#define HBM0_MC0BIST0_WR_BLOCK_SIZE_VAL_SHIFT 0
#define HBM0_MC0BIST0_WR_BLOCK_SIZE_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_RD_REP_NUM */
#define HBM0_MC0BIST0_RD_REP_NUM_VAL_SHIFT 0
#define HBM0_MC0BIST0_RD_REP_NUM_VAL_MASK 0xFFFF

/* HBM0_MC0BIST0_RD_DELAY */
#define HBM0_MC0BIST0_RD_DELAY_VAL_SHIFT 0
#define HBM0_MC0BIST0_RD_DELAY_VAL_MASK 0xFFFF

/* HBM0_MC0BIST0_RD_BLOCK_SIZE */
#define HBM0_MC0BIST0_RD_BLOCK_SIZE_VAL_SHIFT 0
#define HBM0_MC0BIST0_RD_BLOCK_SIZE_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_STOP_ON_ERR */
#define HBM0_MC0BIST0_STOP_ON_ERR_VAL_SHIFT 0
#define HBM0_MC0BIST0_STOP_ON_ERR_VAL_MASK 0x1

/* HBM0_MC0BIST0_ADDR_MODE */
#define HBM0_MC0BIST0_ADDR_MODE_VAL_SHIFT 0
#define HBM0_MC0BIST0_ADDR_MODE_VAL_MASK 0x3

/* HBM0_MC0BIST0_ADDR_INCR_STRIDE */
#define HBM0_MC0BIST0_ADDR_INCR_STRIDE_VAL_SHIFT 0
#define HBM0_MC0BIST0_ADDR_INCR_STRIDE_VAL_MASK 0xFFFF

/* HBM0_MC0BIST0_ADDR_INCR_INIT */
#define HBM0_MC0BIST0_ADDR_INCR_INIT_VAL_SHIFT 0
#define HBM0_MC0BIST0_ADDR_INCR_INIT_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_ADDR_PSEUDO_POLY */
#define HBM0_MC0BIST0_ADDR_PSEUDO_POLY_VAL_SHIFT 0
#define HBM0_MC0BIST0_ADDR_PSEUDO_POLY_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_ADDR_PSEUDO_SEED */
#define HBM0_MC0BIST0_ADDR_PSEUDO_SEED_VAL_SHIFT 0
#define HBM0_MC0BIST0_ADDR_PSEUDO_SEED_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_ADDR_MEM_STRIDE */
#define HBM0_MC0BIST0_ADDR_MEM_STRIDE_VAL_SHIFT 0
#define HBM0_MC0BIST0_ADDR_MEM_STRIDE_VAL_MASK 0xFFFF

/* HBM0_MC0BIST0_WDATA_MODE */
#define HBM0_MC0BIST0_WDATA_MODE_VAL_SHIFT 0
#define HBM0_MC0BIST0_WDATA_MODE_VAL_MASK 0x7

/* HBM0_MC0BIST0_WDATA_PSEUDO_POLY */
#define HBM0_MC0BIST0_WDATA_PSEUDO_POLY_VAL_SHIFT 0
#define HBM0_MC0BIST0_WDATA_PSEUDO_POLY_VAL_MASK 0xFFFF

/* HBM0_MC0BIST0_WDATA_PSEUDO_SEED */
#define HBM0_MC0BIST0_WDATA_PSEUDO_SEED_VAL_SHIFT 0
#define HBM0_MC0BIST0_WDATA_PSEUDO_SEED_VAL_MASK 0xFFFF

/* HBM0_MC0BIST0_WDATA_MEM_START */
#define HBM0_MC0BIST0_WDATA_MEM_START_VAL_SHIFT 0
#define HBM0_MC0BIST0_WDATA_MEM_START_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_WDATA_MEM_END */
#define HBM0_MC0BIST0_WDATA_MEM_END_VAL_SHIFT 0
#define HBM0_MC0BIST0_WDATA_MEM_END_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_RDATA_COMP_MASK */
#define HBM0_MC0BIST0_RDATA_COMP_MASK_VAL_SHIFT 0
#define HBM0_MC0BIST0_RDATA_COMP_MASK_VAL_MASK 0xFFFF

/* HBM0_MC0BIST0_MISMATCH_CNT */
#define HBM0_MC0BIST0_MISMATCH_CNT_VAL_SHIFT 0
#define HBM0_MC0BIST0_MISMATCH_CNT_VAL_MASK 0xFFFF

/* HBM0_MC0BIST0_MISMATCH_FIRST_ADDR */
#define HBM0_MC0BIST0_MISMATCH_FIRST_ADDR_VAL_SHIFT 0
#define HBM0_MC0BIST0_MISMATCH_FIRST_ADDR_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_MISMATCH_LAST_ADDR */
#define HBM0_MC0BIST0_MISMATCH_LAST_ADDR_VAL_SHIFT 0
#define HBM0_MC0BIST0_MISMATCH_LAST_ADDR_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_MISMATCH_LOWEST_ADDR */
#define HBM0_MC0BIST0_MISMATCH_LOWEST_ADDR_VAL_SHIFT 0
#define HBM0_MC0BIST0_MISMATCH_LOWEST_ADDR_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_MISMATCH_HIGHEST_ADDR */
#define HBM0_MC0BIST0_MISMATCH_HIGHEST_ADDR_VAL_SHIFT 0
#define HBM0_MC0BIST0_MISMATCH_HIGHEST_ADDR_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_BRESP_ERR_CNT */
#define HBM0_MC0BIST0_BRESP_ERR_CNT_VAL_SHIFT 0
#define HBM0_MC0BIST0_BRESP_ERR_CNT_VAL_MASK 0xFFFF

/* HBM0_MC0BIST0_RRESP_ERR_CNT */
#define HBM0_MC0BIST0_RRESP_ERR_CNT_VAL_SHIFT 0
#define HBM0_MC0BIST0_RRESP_ERR_CNT_VAL_MASK 0xFFFF

/* HBM0_MC0BIST0_FIRST_MISMATCH_EXPECTED */
#define HBM0_MC0BIST0_FIRST_MISMATCH_EXPECTED_VAL_SHIFT 0
#define HBM0_MC0BIST0_FIRST_MISMATCH_EXPECTED_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_FIRST_MISMATCH_RECEIVED */
#define HBM0_MC0BIST0_FIRST_MISMATCH_RECEIVED_VAL_SHIFT 0
#define HBM0_MC0BIST0_FIRST_MISMATCH_RECEIVED_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_LOOP_NUM */
#define HBM0_MC0BIST0_LOOP_NUM_VAL_SHIFT 0
#define HBM0_MC0BIST0_LOOP_NUM_VAL_MASK 0xFFFF

/* HBM0_MC0BIST0_FORCE_CLEAR */
#define HBM0_MC0BIST0_FORCE_CLEAR_VAL_SHIFT 0
#define HBM0_MC0BIST0_FORCE_CLEAR_VAL_MASK 0x1

/* HBM0_MC0BIST0_BIST_DONE */
#define HBM0_MC0BIST0_BIST_DONE_VAL_SHIFT 0
#define HBM0_MC0BIST0_BIST_DONE_VAL_MASK 0x1

/* HBM0_MC0BIST0_WSTRB */
#define HBM0_MC0BIST0_WSTRB_VAL_SHIFT 0
#define HBM0_MC0BIST0_WSTRB_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_AXSIZE */
#define HBM0_MC0BIST0_AXSIZE_VAL_SHIFT 0
#define HBM0_MC0BIST0_AXSIZE_VAL_MASK 0x7

/* HBM0_MC0BIST0_AXUSER */
#define HBM0_MC0BIST0_AXUSER_VAL_SHIFT 0
#define HBM0_MC0BIST0_AXUSER_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_AXPROT */
#define HBM0_MC0BIST0_AXPROT_VAL_SHIFT 0
#define HBM0_MC0BIST0_AXPROT_VAL_MASK 0x7

/* HBM0_MC0BIST0_AXCACHE */
#define HBM0_MC0BIST0_AXCACHE_VAL_SHIFT 0
#define HBM0_MC0BIST0_AXCACHE_VAL_MASK 0xF

/* HBM0_MC0BIST0_AXLOCK */
#define HBM0_MC0BIST0_AXLOCK_VAL_SHIFT 0
#define HBM0_MC0BIST0_AXLOCK_VAL_MASK 0x1

/* HBM0_MC0BIST0_AXLEN */
#define HBM0_MC0BIST0_AXLEN_VAL_SHIFT 0
#define HBM0_MC0BIST0_AXLEN_VAL_MASK 0xFF

/* HBM0_MC0BIST0_WR_RD */
#define HBM0_MC0BIST0_WR_RD_WAIT_FOR_B_SHIFT 0
#define HBM0_MC0BIST0_WR_RD_WAIT_FOR_B_MASK 0x1
#define HBM0_MC0BIST0_WR_RD_WAIT_FOR_R_SHIFT 1
#define HBM0_MC0BIST0_WR_RD_WAIT_FOR_R_MASK 0x2
#define HBM0_MC0BIST0_WR_RD_DELAY_WR2RD_EN_SHIFT 2
#define HBM0_MC0BIST0_WR_RD_DELAY_WR2RD_EN_MASK 0x4
#define HBM0_MC0BIST0_WR_RD_WR_PRIO_OVER_RD_SHIFT 3
#define HBM0_MC0BIST0_WR_RD_WR_PRIO_OVER_RD_MASK 0x8

/* HBM0_MC0BIST0_WOA_CNT */
#define HBM0_MC0BIST0_WOA_CNT_VAL_SHIFT 0
#define HBM0_MC0BIST0_WOA_CNT_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_ROA_CNT */
#define HBM0_MC0BIST0_ROA_CNT_VAL_SHIFT 0
#define HBM0_MC0BIST0_ROA_CNT_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_PRESENT_STATE */
#define HBM0_MC0BIST0_PRESENT_STATE_VAL_SHIFT 0
#define HBM0_MC0BIST0_PRESENT_STATE_VAL_MASK 0xF

/* HBM0_MC0BIST0_PREVIOUS_STATE */
#define HBM0_MC0BIST0_PREVIOUS_STATE_VAL_SHIFT 0
#define HBM0_MC0BIST0_PREVIOUS_STATE_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_WBLOCK_SIZE_CNT */
#define HBM0_MC0BIST0_WBLOCK_SIZE_CNT_VAL_SHIFT 0
#define HBM0_MC0BIST0_WBLOCK_SIZE_CNT_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_RBLOCK_SIZE_CNT */
#define HBM0_MC0BIST0_RBLOCK_SIZE_CNT_VAL_SHIFT 0
#define HBM0_MC0BIST0_RBLOCK_SIZE_CNT_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_AWLEN_CNT */
#define HBM0_MC0BIST0_AWLEN_CNT_VAL_SHIFT 0
#define HBM0_MC0BIST0_AWLEN_CNT_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_ARLEN_CNT */
#define HBM0_MC0BIST0_ARLEN_CNT_VAL_SHIFT 0
#define HBM0_MC0BIST0_ARLEN_CNT_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_RLEN_CNT */
#define HBM0_MC0BIST0_RLEN_CNT_VAL_SHIFT 0
#define HBM0_MC0BIST0_RLEN_CNT_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_WRBLOCK_FENCE_EN */
#define HBM0_MC0BIST0_WRBLOCK_FENCE_EN_VAL_SHIFT 0
#define HBM0_MC0BIST0_WRBLOCK_FENCE_EN_VAL_MASK 0x1

/* HBM0_MC0BIST0_EXPECTED_MISMATCH_SEL */
#define HBM0_MC0BIST0_EXPECTED_MISMATCH_SEL_VAL_SHIFT 0
#define HBM0_MC0BIST0_EXPECTED_MISMATCH_SEL_VAL_MASK 0xFFFFFFFF

/* HBM0_MC0BIST0_RECEIVED_MISMATCH_SEL */
#define HBM0_MC0BIST0_RECEIVED_MISMATCH_SEL_VAL_SHIFT 0
#define HBM0_MC0BIST0_RECEIVED_MISMATCH_SEL_VAL_MASK 0xFFFFFFFF

#endif /* ASIC_REG_HBM0_MC0BIST0_MASKS_H_ */
