/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_HBM_PHY_INITENG_MASKS_H_
#define ASIC_REG_HBM_PHY_INITENG_MASKS_H_

/*
 *****************************************
 *   HBM_PHY_INITENG
 *   (Prototype: HBM_PHY_P0_INITGEN)
 *****************************************
 */

/* HBM_PHY_INITENG_INITSEQREG0S0 */
#define HBM_PHY_INITENG_INITSEQREG0S0_INITSEQREG0S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG0S0_INITSEQREG0S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG0S1 */
#define HBM_PHY_INITENG_INITSEQREG0S1_INITSEQREG0S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG0S1_INITSEQREG0S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG0S2 */
#define HBM_PHY_INITENG_INITSEQREG0S2_INITSEQREG0S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG0S2_INITSEQREG0S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG1S0 */
#define HBM_PHY_INITENG_INITSEQREG1S0_INITSEQREG1S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG1S0_INITSEQREG1S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG1S1 */
#define HBM_PHY_INITENG_INITSEQREG1S1_INITSEQREG1S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG1S1_INITSEQREG1S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG1S2 */
#define HBM_PHY_INITENG_INITSEQREG1S2_INITSEQREG1S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG1S2_INITSEQREG1S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG2S0 */
#define HBM_PHY_INITENG_INITSEQREG2S0_INITSEQREG2S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG2S0_INITSEQREG2S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG2S1 */
#define HBM_PHY_INITENG_INITSEQREG2S1_INITSEQREG2S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG2S1_INITSEQREG2S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG2S2 */
#define HBM_PHY_INITENG_INITSEQREG2S2_INITSEQREG2S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG2S2_INITSEQREG2S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG3S0 */
#define HBM_PHY_INITENG_INITSEQREG3S0_INITSEQREG3S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG3S0_INITSEQREG3S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG3S1 */
#define HBM_PHY_INITENG_INITSEQREG3S1_INITSEQREG3S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG3S1_INITSEQREG3S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG3S2 */
#define HBM_PHY_INITENG_INITSEQREG3S2_INITSEQREG3S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG3S2_INITSEQREG3S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG4S0 */
#define HBM_PHY_INITENG_INITSEQREG4S0_INITSEQREG4S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG4S0_INITSEQREG4S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG4S1 */
#define HBM_PHY_INITENG_INITSEQREG4S1_INITSEQREG4S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG4S1_INITSEQREG4S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG4S2 */
#define HBM_PHY_INITENG_INITSEQREG4S2_INITSEQREG4S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG4S2_INITSEQREG4S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG5S0 */
#define HBM_PHY_INITENG_INITSEQREG5S0_INITSEQREG5S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG5S0_INITSEQREG5S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG5S1 */
#define HBM_PHY_INITENG_INITSEQREG5S1_INITSEQREG5S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG5S1_INITSEQREG5S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG5S2 */
#define HBM_PHY_INITENG_INITSEQREG5S2_INITSEQREG5S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG5S2_INITSEQREG5S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG6S0 */
#define HBM_PHY_INITENG_INITSEQREG6S0_INITSEQREG6S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG6S0_INITSEQREG6S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG6S1 */
#define HBM_PHY_INITENG_INITSEQREG6S1_INITSEQREG6S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG6S1_INITSEQREG6S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG6S2 */
#define HBM_PHY_INITENG_INITSEQREG6S2_INITSEQREG6S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG6S2_INITSEQREG6S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG7S0 */
#define HBM_PHY_INITENG_INITSEQREG7S0_INITSEQREG7S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG7S0_INITSEQREG7S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG7S1 */
#define HBM_PHY_INITENG_INITSEQREG7S1_INITSEQREG7S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG7S1_INITSEQREG7S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG7S2 */
#define HBM_PHY_INITENG_INITSEQREG7S2_INITSEQREG7S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG7S2_INITSEQREG7S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG8S0 */
#define HBM_PHY_INITENG_INITSEQREG8S0_INITSEQREG8S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG8S0_INITSEQREG8S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG8S1 */
#define HBM_PHY_INITENG_INITSEQREG8S1_INITSEQREG8S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG8S1_INITSEQREG8S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG8S2 */
#define HBM_PHY_INITENG_INITSEQREG8S2_INITSEQREG8S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG8S2_INITSEQREG8S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG9S0 */
#define HBM_PHY_INITENG_INITSEQREG9S0_INITSEQREG9S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG9S0_INITSEQREG9S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG9S1 */
#define HBM_PHY_INITENG_INITSEQREG9S1_INITSEQREG9S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG9S1_INITSEQREG9S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG9S2 */
#define HBM_PHY_INITENG_INITSEQREG9S2_INITSEQREG9S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG9S2_INITSEQREG9S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG10S0 */
#define HBM_PHY_INITENG_INITSEQREG10S0_INITSEQREG10S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG10S0_INITSEQREG10S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG10S1 */
#define HBM_PHY_INITENG_INITSEQREG10S1_INITSEQREG10S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG10S1_INITSEQREG10S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG10S2 */
#define HBM_PHY_INITENG_INITSEQREG10S2_INITSEQREG10S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG10S2_INITSEQREG10S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG11S0 */
#define HBM_PHY_INITENG_INITSEQREG11S0_INITSEQREG11S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG11S0_INITSEQREG11S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG11S1 */
#define HBM_PHY_INITENG_INITSEQREG11S1_INITSEQREG11S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG11S1_INITSEQREG11S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG11S2 */
#define HBM_PHY_INITENG_INITSEQREG11S2_INITSEQREG11S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG11S2_INITSEQREG11S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG12S0 */
#define HBM_PHY_INITENG_INITSEQREG12S0_INITSEQREG12S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG12S0_INITSEQREG12S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG12S1 */
#define HBM_PHY_INITENG_INITSEQREG12S1_INITSEQREG12S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG12S1_INITSEQREG12S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG12S2 */
#define HBM_PHY_INITENG_INITSEQREG12S2_INITSEQREG12S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG12S2_INITSEQREG12S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG13S0 */
#define HBM_PHY_INITENG_INITSEQREG13S0_INITSEQREG13S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG13S0_INITSEQREG13S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG13S1 */
#define HBM_PHY_INITENG_INITSEQREG13S1_INITSEQREG13S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG13S1_INITSEQREG13S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG13S2 */
#define HBM_PHY_INITENG_INITSEQREG13S2_INITSEQREG13S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG13S2_INITSEQREG13S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG14S0 */
#define HBM_PHY_INITENG_INITSEQREG14S0_INITSEQREG14S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG14S0_INITSEQREG14S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG14S1 */
#define HBM_PHY_INITENG_INITSEQREG14S1_INITSEQREG14S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG14S1_INITSEQREG14S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG14S2 */
#define HBM_PHY_INITENG_INITSEQREG14S2_INITSEQREG14S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG14S2_INITSEQREG14S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG15S0 */
#define HBM_PHY_INITENG_INITSEQREG15S0_INITSEQREG15S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG15S0_INITSEQREG15S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG15S1 */
#define HBM_PHY_INITENG_INITSEQREG15S1_INITSEQREG15S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG15S1_INITSEQREG15S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG15S2 */
#define HBM_PHY_INITENG_INITSEQREG15S2_INITSEQREG15S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG15S2_INITSEQREG15S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG16S0 */
#define HBM_PHY_INITENG_INITSEQREG16S0_INITSEQREG16S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG16S0_INITSEQREG16S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG16S1 */
#define HBM_PHY_INITENG_INITSEQREG16S1_INITSEQREG16S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG16S1_INITSEQREG16S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG16S2 */
#define HBM_PHY_INITENG_INITSEQREG16S2_INITSEQREG16S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG16S2_INITSEQREG16S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG17S0 */
#define HBM_PHY_INITENG_INITSEQREG17S0_INITSEQREG17S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG17S0_INITSEQREG17S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG17S1 */
#define HBM_PHY_INITENG_INITSEQREG17S1_INITSEQREG17S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG17S1_INITSEQREG17S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG17S2 */
#define HBM_PHY_INITENG_INITSEQREG17S2_INITSEQREG17S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG17S2_INITSEQREG17S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG18S0 */
#define HBM_PHY_INITENG_INITSEQREG18S0_INITSEQREG18S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG18S0_INITSEQREG18S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG18S1 */
#define HBM_PHY_INITENG_INITSEQREG18S1_INITSEQREG18S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG18S1_INITSEQREG18S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG18S2 */
#define HBM_PHY_INITENG_INITSEQREG18S2_INITSEQREG18S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG18S2_INITSEQREG18S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG19S0 */
#define HBM_PHY_INITENG_INITSEQREG19S0_INITSEQREG19S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG19S0_INITSEQREG19S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG19S1 */
#define HBM_PHY_INITENG_INITSEQREG19S1_INITSEQREG19S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG19S1_INITSEQREG19S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG19S2 */
#define HBM_PHY_INITENG_INITSEQREG19S2_INITSEQREG19S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG19S2_INITSEQREG19S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG20S0 */
#define HBM_PHY_INITENG_INITSEQREG20S0_INITSEQREG20S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG20S0_INITSEQREG20S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG20S1 */
#define HBM_PHY_INITENG_INITSEQREG20S1_INITSEQREG20S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG20S1_INITSEQREG20S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG20S2 */
#define HBM_PHY_INITENG_INITSEQREG20S2_INITSEQREG20S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG20S2_INITSEQREG20S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG21S0 */
#define HBM_PHY_INITENG_INITSEQREG21S0_INITSEQREG21S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG21S0_INITSEQREG21S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG21S1 */
#define HBM_PHY_INITENG_INITSEQREG21S1_INITSEQREG21S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG21S1_INITSEQREG21S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG21S2 */
#define HBM_PHY_INITENG_INITSEQREG21S2_INITSEQREG21S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG21S2_INITSEQREG21S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG22S0 */
#define HBM_PHY_INITENG_INITSEQREG22S0_INITSEQREG22S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG22S0_INITSEQREG22S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG22S1 */
#define HBM_PHY_INITENG_INITSEQREG22S1_INITSEQREG22S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG22S1_INITSEQREG22S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG22S2 */
#define HBM_PHY_INITENG_INITSEQREG22S2_INITSEQREG22S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG22S2_INITSEQREG22S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG23S0 */
#define HBM_PHY_INITENG_INITSEQREG23S0_INITSEQREG23S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG23S0_INITSEQREG23S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG23S1 */
#define HBM_PHY_INITENG_INITSEQREG23S1_INITSEQREG23S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG23S1_INITSEQREG23S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG23S2 */
#define HBM_PHY_INITENG_INITSEQREG23S2_INITSEQREG23S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG23S2_INITSEQREG23S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG24S0 */
#define HBM_PHY_INITENG_INITSEQREG24S0_INITSEQREG24S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG24S0_INITSEQREG24S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG24S1 */
#define HBM_PHY_INITENG_INITSEQREG24S1_INITSEQREG24S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG24S1_INITSEQREG24S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG24S2 */
#define HBM_PHY_INITENG_INITSEQREG24S2_INITSEQREG24S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG24S2_INITSEQREG24S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG25S0 */
#define HBM_PHY_INITENG_INITSEQREG25S0_INITSEQREG25S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG25S0_INITSEQREG25S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG25S1 */
#define HBM_PHY_INITENG_INITSEQREG25S1_INITSEQREG25S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG25S1_INITSEQREG25S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG25S2 */
#define HBM_PHY_INITENG_INITSEQREG25S2_INITSEQREG25S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG25S2_INITSEQREG25S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG26S0 */
#define HBM_PHY_INITENG_INITSEQREG26S0_INITSEQREG26S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG26S0_INITSEQREG26S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG26S1 */
#define HBM_PHY_INITENG_INITSEQREG26S1_INITSEQREG26S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG26S1_INITSEQREG26S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG26S2 */
#define HBM_PHY_INITENG_INITSEQREG26S2_INITSEQREG26S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG26S2_INITSEQREG26S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG27S0 */
#define HBM_PHY_INITENG_INITSEQREG27S0_INITSEQREG27S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG27S0_INITSEQREG27S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG27S1 */
#define HBM_PHY_INITENG_INITSEQREG27S1_INITSEQREG27S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG27S1_INITSEQREG27S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG27S2 */
#define HBM_PHY_INITENG_INITSEQREG27S2_INITSEQREG27S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG27S2_INITSEQREG27S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG28S0 */
#define HBM_PHY_INITENG_INITSEQREG28S0_INITSEQREG28S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG28S0_INITSEQREG28S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG28S1 */
#define HBM_PHY_INITENG_INITSEQREG28S1_INITSEQREG28S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG28S1_INITSEQREG28S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG28S2 */
#define HBM_PHY_INITENG_INITSEQREG28S2_INITSEQREG28S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG28S2_INITSEQREG28S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG29S0 */
#define HBM_PHY_INITENG_INITSEQREG29S0_INITSEQREG29S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG29S0_INITSEQREG29S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG29S1 */
#define HBM_PHY_INITENG_INITSEQREG29S1_INITSEQREG29S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG29S1_INITSEQREG29S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG29S2 */
#define HBM_PHY_INITENG_INITSEQREG29S2_INITSEQREG29S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG29S2_INITSEQREG29S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG30S0 */
#define HBM_PHY_INITENG_INITSEQREG30S0_INITSEQREG30S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG30S0_INITSEQREG30S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG30S1 */
#define HBM_PHY_INITENG_INITSEQREG30S1_INITSEQREG30S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG30S1_INITSEQREG30S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG30S2 */
#define HBM_PHY_INITENG_INITSEQREG30S2_INITSEQREG30S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG30S2_INITSEQREG30S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG31S0 */
#define HBM_PHY_INITENG_INITSEQREG31S0_INITSEQREG31S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG31S0_INITSEQREG31S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG31S1 */
#define HBM_PHY_INITENG_INITSEQREG31S1_INITSEQREG31S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG31S1_INITSEQREG31S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG31S2 */
#define HBM_PHY_INITENG_INITSEQREG31S2_INITSEQREG31S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG31S2_INITSEQREG31S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG32S0 */
#define HBM_PHY_INITENG_INITSEQREG32S0_INITSEQREG32S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG32S0_INITSEQREG32S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG32S1 */
#define HBM_PHY_INITENG_INITSEQREG32S1_INITSEQREG32S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG32S1_INITSEQREG32S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG32S2 */
#define HBM_PHY_INITENG_INITSEQREG32S2_INITSEQREG32S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG32S2_INITSEQREG32S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG33S0 */
#define HBM_PHY_INITENG_INITSEQREG33S0_INITSEQREG33S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG33S0_INITSEQREG33S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG33S1 */
#define HBM_PHY_INITENG_INITSEQREG33S1_INITSEQREG33S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG33S1_INITSEQREG33S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG33S2 */
#define HBM_PHY_INITENG_INITSEQREG33S2_INITSEQREG33S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG33S2_INITSEQREG33S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG34S0 */
#define HBM_PHY_INITENG_INITSEQREG34S0_INITSEQREG34S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG34S0_INITSEQREG34S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG34S1 */
#define HBM_PHY_INITENG_INITSEQREG34S1_INITSEQREG34S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG34S1_INITSEQREG34S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG34S2 */
#define HBM_PHY_INITENG_INITSEQREG34S2_INITSEQREG34S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG34S2_INITSEQREG34S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG35S0 */
#define HBM_PHY_INITENG_INITSEQREG35S0_INITSEQREG35S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG35S0_INITSEQREG35S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG35S1 */
#define HBM_PHY_INITENG_INITSEQREG35S1_INITSEQREG35S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG35S1_INITSEQREG35S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG35S2 */
#define HBM_PHY_INITENG_INITSEQREG35S2_INITSEQREG35S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG35S2_INITSEQREG35S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG36S0 */
#define HBM_PHY_INITENG_INITSEQREG36S0_INITSEQREG36S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG36S0_INITSEQREG36S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG36S1 */
#define HBM_PHY_INITENG_INITSEQREG36S1_INITSEQREG36S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG36S1_INITSEQREG36S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG36S2 */
#define HBM_PHY_INITENG_INITSEQREG36S2_INITSEQREG36S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG36S2_INITSEQREG36S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG37S0 */
#define HBM_PHY_INITENG_INITSEQREG37S0_INITSEQREG37S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG37S0_INITSEQREG37S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG37S1 */
#define HBM_PHY_INITENG_INITSEQREG37S1_INITSEQREG37S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG37S1_INITSEQREG37S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG37S2 */
#define HBM_PHY_INITENG_INITSEQREG37S2_INITSEQREG37S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG37S2_INITSEQREG37S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG38S0 */
#define HBM_PHY_INITENG_INITSEQREG38S0_INITSEQREG38S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG38S0_INITSEQREG38S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG38S1 */
#define HBM_PHY_INITENG_INITSEQREG38S1_INITSEQREG38S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG38S1_INITSEQREG38S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG38S2 */
#define HBM_PHY_INITENG_INITSEQREG38S2_INITSEQREG38S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG38S2_INITSEQREG38S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG39S0 */
#define HBM_PHY_INITENG_INITSEQREG39S0_INITSEQREG39S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG39S0_INITSEQREG39S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG39S1 */
#define HBM_PHY_INITENG_INITSEQREG39S1_INITSEQREG39S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG39S1_INITSEQREG39S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG39S2 */
#define HBM_PHY_INITENG_INITSEQREG39S2_INITSEQREG39S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG39S2_INITSEQREG39S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG40S0 */
#define HBM_PHY_INITENG_INITSEQREG40S0_INITSEQREG40S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG40S0_INITSEQREG40S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG40S1 */
#define HBM_PHY_INITENG_INITSEQREG40S1_INITSEQREG40S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG40S1_INITSEQREG40S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG40S2 */
#define HBM_PHY_INITENG_INITSEQREG40S2_INITSEQREG40S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG40S2_INITSEQREG40S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG41S0 */
#define HBM_PHY_INITENG_INITSEQREG41S0_INITSEQREG41S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG41S0_INITSEQREG41S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG41S1 */
#define HBM_PHY_INITENG_INITSEQREG41S1_INITSEQREG41S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG41S1_INITSEQREG41S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG41S2 */
#define HBM_PHY_INITENG_INITSEQREG41S2_INITSEQREG41S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG41S2_INITSEQREG41S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG42S0 */
#define HBM_PHY_INITENG_INITSEQREG42S0_INITSEQREG42S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG42S0_INITSEQREG42S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG42S1 */
#define HBM_PHY_INITENG_INITSEQREG42S1_INITSEQREG42S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG42S1_INITSEQREG42S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG42S2 */
#define HBM_PHY_INITENG_INITSEQREG42S2_INITSEQREG42S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG42S2_INITSEQREG42S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG43S0 */
#define HBM_PHY_INITENG_INITSEQREG43S0_INITSEQREG43S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG43S0_INITSEQREG43S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG43S1 */
#define HBM_PHY_INITENG_INITSEQREG43S1_INITSEQREG43S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG43S1_INITSEQREG43S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG43S2 */
#define HBM_PHY_INITENG_INITSEQREG43S2_INITSEQREG43S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG43S2_INITSEQREG43S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG44S0 */
#define HBM_PHY_INITENG_INITSEQREG44S0_INITSEQREG44S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG44S0_INITSEQREG44S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG44S1 */
#define HBM_PHY_INITENG_INITSEQREG44S1_INITSEQREG44S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG44S1_INITSEQREG44S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG44S2 */
#define HBM_PHY_INITENG_INITSEQREG44S2_INITSEQREG44S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG44S2_INITSEQREG44S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG45S0 */
#define HBM_PHY_INITENG_INITSEQREG45S0_INITSEQREG45S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG45S0_INITSEQREG45S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG45S1 */
#define HBM_PHY_INITENG_INITSEQREG45S1_INITSEQREG45S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG45S1_INITSEQREG45S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG45S2 */
#define HBM_PHY_INITENG_INITSEQREG45S2_INITSEQREG45S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG45S2_INITSEQREG45S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG46S0 */
#define HBM_PHY_INITENG_INITSEQREG46S0_INITSEQREG46S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG46S0_INITSEQREG46S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG46S1 */
#define HBM_PHY_INITENG_INITSEQREG46S1_INITSEQREG46S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG46S1_INITSEQREG46S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG46S2 */
#define HBM_PHY_INITENG_INITSEQREG46S2_INITSEQREG46S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG46S2_INITSEQREG46S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG47S0 */
#define HBM_PHY_INITENG_INITSEQREG47S0_INITSEQREG47S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG47S0_INITSEQREG47S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG47S1 */
#define HBM_PHY_INITENG_INITSEQREG47S1_INITSEQREG47S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG47S1_INITSEQREG47S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG47S2 */
#define HBM_PHY_INITENG_INITSEQREG47S2_INITSEQREG47S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG47S2_INITSEQREG47S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG48S0 */
#define HBM_PHY_INITENG_INITSEQREG48S0_INITSEQREG48S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG48S0_INITSEQREG48S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG48S1 */
#define HBM_PHY_INITENG_INITSEQREG48S1_INITSEQREG48S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG48S1_INITSEQREG48S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG48S2 */
#define HBM_PHY_INITENG_INITSEQREG48S2_INITSEQREG48S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG48S2_INITSEQREG48S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG49S0 */
#define HBM_PHY_INITENG_INITSEQREG49S0_INITSEQREG49S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG49S0_INITSEQREG49S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG49S1 */
#define HBM_PHY_INITENG_INITSEQREG49S1_INITSEQREG49S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG49S1_INITSEQREG49S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG49S2 */
#define HBM_PHY_INITENG_INITSEQREG49S2_INITSEQREG49S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG49S2_INITSEQREG49S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG50S0 */
#define HBM_PHY_INITENG_INITSEQREG50S0_INITSEQREG50S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG50S0_INITSEQREG50S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG50S1 */
#define HBM_PHY_INITENG_INITSEQREG50S1_INITSEQREG50S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG50S1_INITSEQREG50S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG50S2 */
#define HBM_PHY_INITENG_INITSEQREG50S2_INITSEQREG50S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG50S2_INITSEQREG50S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG51S0 */
#define HBM_PHY_INITENG_INITSEQREG51S0_INITSEQREG51S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG51S0_INITSEQREG51S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG51S1 */
#define HBM_PHY_INITENG_INITSEQREG51S1_INITSEQREG51S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG51S1_INITSEQREG51S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG51S2 */
#define HBM_PHY_INITENG_INITSEQREG51S2_INITSEQREG51S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG51S2_INITSEQREG51S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG52S0 */
#define HBM_PHY_INITENG_INITSEQREG52S0_INITSEQREG52S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG52S0_INITSEQREG52S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG52S1 */
#define HBM_PHY_INITENG_INITSEQREG52S1_INITSEQREG52S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG52S1_INITSEQREG52S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG52S2 */
#define HBM_PHY_INITENG_INITSEQREG52S2_INITSEQREG52S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG52S2_INITSEQREG52S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG53S0 */
#define HBM_PHY_INITENG_INITSEQREG53S0_INITSEQREG53S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG53S0_INITSEQREG53S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG53S1 */
#define HBM_PHY_INITENG_INITSEQREG53S1_INITSEQREG53S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG53S1_INITSEQREG53S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG53S2 */
#define HBM_PHY_INITENG_INITSEQREG53S2_INITSEQREG53S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG53S2_INITSEQREG53S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG54S0 */
#define HBM_PHY_INITENG_INITSEQREG54S0_INITSEQREG54S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG54S0_INITSEQREG54S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG54S1 */
#define HBM_PHY_INITENG_INITSEQREG54S1_INITSEQREG54S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG54S1_INITSEQREG54S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG54S2 */
#define HBM_PHY_INITENG_INITSEQREG54S2_INITSEQREG54S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG54S2_INITSEQREG54S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG55S0 */
#define HBM_PHY_INITENG_INITSEQREG55S0_INITSEQREG55S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG55S0_INITSEQREG55S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG55S1 */
#define HBM_PHY_INITENG_INITSEQREG55S1_INITSEQREG55S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG55S1_INITSEQREG55S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG55S2 */
#define HBM_PHY_INITENG_INITSEQREG55S2_INITSEQREG55S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG55S2_INITSEQREG55S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG56S0 */
#define HBM_PHY_INITENG_INITSEQREG56S0_INITSEQREG56S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG56S0_INITSEQREG56S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG56S1 */
#define HBM_PHY_INITENG_INITSEQREG56S1_INITSEQREG56S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG56S1_INITSEQREG56S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG56S2 */
#define HBM_PHY_INITENG_INITSEQREG56S2_INITSEQREG56S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG56S2_INITSEQREG56S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG57S0 */
#define HBM_PHY_INITENG_INITSEQREG57S0_INITSEQREG57S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG57S0_INITSEQREG57S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG57S1 */
#define HBM_PHY_INITENG_INITSEQREG57S1_INITSEQREG57S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG57S1_INITSEQREG57S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG57S2 */
#define HBM_PHY_INITENG_INITSEQREG57S2_INITSEQREG57S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG57S2_INITSEQREG57S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG58S0 */
#define HBM_PHY_INITENG_INITSEQREG58S0_INITSEQREG58S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG58S0_INITSEQREG58S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG58S1 */
#define HBM_PHY_INITENG_INITSEQREG58S1_INITSEQREG58S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG58S1_INITSEQREG58S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG58S2 */
#define HBM_PHY_INITENG_INITSEQREG58S2_INITSEQREG58S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG58S2_INITSEQREG58S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG59S0 */
#define HBM_PHY_INITENG_INITSEQREG59S0_INITSEQREG59S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG59S0_INITSEQREG59S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG59S1 */
#define HBM_PHY_INITENG_INITSEQREG59S1_INITSEQREG59S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG59S1_INITSEQREG59S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG59S2 */
#define HBM_PHY_INITENG_INITSEQREG59S2_INITSEQREG59S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG59S2_INITSEQREG59S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG60S0 */
#define HBM_PHY_INITENG_INITSEQREG60S0_INITSEQREG60S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG60S0_INITSEQREG60S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG60S1 */
#define HBM_PHY_INITENG_INITSEQREG60S1_INITSEQREG60S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG60S1_INITSEQREG60S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG60S2 */
#define HBM_PHY_INITENG_INITSEQREG60S2_INITSEQREG60S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG60S2_INITSEQREG60S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG61S0 */
#define HBM_PHY_INITENG_INITSEQREG61S0_INITSEQREG61S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG61S0_INITSEQREG61S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG61S1 */
#define HBM_PHY_INITENG_INITSEQREG61S1_INITSEQREG61S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG61S1_INITSEQREG61S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG61S2 */
#define HBM_PHY_INITENG_INITSEQREG61S2_INITSEQREG61S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG61S2_INITSEQREG61S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG62S0 */
#define HBM_PHY_INITENG_INITSEQREG62S0_INITSEQREG62S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG62S0_INITSEQREG62S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG62S1 */
#define HBM_PHY_INITENG_INITSEQREG62S1_INITSEQREG62S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG62S1_INITSEQREG62S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG62S2 */
#define HBM_PHY_INITENG_INITSEQREG62S2_INITSEQREG62S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG62S2_INITSEQREG62S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG63S0 */
#define HBM_PHY_INITENG_INITSEQREG63S0_INITSEQREG63S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG63S0_INITSEQREG63S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG63S1 */
#define HBM_PHY_INITENG_INITSEQREG63S1_INITSEQREG63S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG63S1_INITSEQREG63S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQREG63S2 */
#define HBM_PHY_INITENG_INITSEQREG63S2_INITSEQREG63S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQREG63S2_INITSEQREG63S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQPRE0S0 */
#define HBM_PHY_INITENG_INITSEQPRE0S0_INITSEQPRE0S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQPRE0S0_INITSEQPRE0S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQPRE0S1 */
#define HBM_PHY_INITENG_INITSEQPRE0S1_INITSEQPRE0S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQPRE0S1_INITSEQPRE0S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQPRE0S2 */
#define HBM_PHY_INITENG_INITSEQPRE0S2_INITSEQPRE0S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQPRE0S2_INITSEQPRE0S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQPRE1S0 */
#define HBM_PHY_INITENG_INITSEQPRE1S0_INITSEQPRE1S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQPRE1S0_INITSEQPRE1S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQPRE1S1 */
#define HBM_PHY_INITENG_INITSEQPRE1S1_INITSEQPRE1S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQPRE1S1_INITSEQPRE1S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQPRE1S2 */
#define HBM_PHY_INITENG_INITSEQPRE1S2_INITSEQPRE1S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQPRE1S2_INITSEQPRE1S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQPOST0S0 */
#define HBM_PHY_INITENG_INITSEQPOST0S0_INITSEQPOST0S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQPOST0S0_INITSEQPOST0S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQPOST0S1 */
#define HBM_PHY_INITENG_INITSEQPOST0S1_INITSEQPOST0S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQPOST0S1_INITSEQPOST0S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQPOST0S2 */
#define HBM_PHY_INITENG_INITSEQPOST0S2_INITSEQPOST0S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQPOST0S2_INITSEQPOST0S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQPOST1S0 */
#define HBM_PHY_INITENG_INITSEQPOST1S0_INITSEQPOST1S0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQPOST1S0_INITSEQPOST1S0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQPOST1S1 */
#define HBM_PHY_INITENG_INITSEQPOST1S1_INITSEQPOST1S1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQPOST1S1_INITSEQPOST1S1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQPOST1S2 */
#define HBM_PHY_INITENG_INITSEQPOST1S2_INITSEQPOST1S2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQPOST1S2_INITSEQPOST1S2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQDISABLEFLAG0 */
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG0_INITSEQDISABLEFLAG0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG0_INITSEQDISABLEFLAG0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQDISABLEFLAG1 */
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG1_INITSEQDISABLEFLAG1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG1_INITSEQDISABLEFLAG1_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQDISABLEFLAG2 */
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG2_INITSEQDISABLEFLAG2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG2_INITSEQDISABLEFLAG2_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQDISABLEFLAG3 */
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG3_INITSEQDISABLEFLAG3_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG3_INITSEQDISABLEFLAG3_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQDISABLEFLAG4 */
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG4_INITSEQDISABLEFLAG4_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG4_INITSEQDISABLEFLAG4_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQDISABLEFLAG5 */
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG5_INITSEQDISABLEFLAG5_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG5_INITSEQDISABLEFLAG5_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQDISABLEFLAG6 */
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG6_INITSEQDISABLEFLAG6_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG6_INITSEQDISABLEFLAG6_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQDISABLEFLAG7 */
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG7_INITSEQDISABLEFLAG7_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDISABLEFLAG7_INITSEQDISABLEFLAG7_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQGPR1_P0 */
#define HBM_PHY_INITENG_INITSEQGPR1_P0_INITSEQGPR1_P0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQGPR1_P0_INITSEQGPR1_P0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQGPR2_P0 */
#define HBM_PHY_INITENG_INITSEQGPR2_P0_INITSEQGPR2_P0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQGPR2_P0_INITSEQGPR2_P0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQGPR3_P0 */
#define HBM_PHY_INITENG_INITSEQGPR3_P0_INITSEQGPR3_P0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQGPR3_P0_INITSEQGPR3_P0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQSTARTVECTOR0 */
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR0_INITSEQSTARTVEC0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR0_INITSEQSTARTVEC0_MASK 0x3F

/* HBM_PHY_INITENG_INITSEQSTARTVECTOR1 */
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR1_INITSEQSTARTVEC1_SHIFT 0
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR1_INITSEQSTARTVEC1_MASK 0x3F

/* HBM_PHY_INITENG_INITSEQSTARTVECTOR2 */
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR2_INITSEQSTARTVEC2_SHIFT 0
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR2_INITSEQSTARTVEC2_MASK 0x3F

/* HBM_PHY_INITENG_INITSEQSTARTVECTOR3 */
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR3_INITSEQSTARTVEC3_SHIFT 0
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR3_INITSEQSTARTVEC3_MASK 0x3F

/* HBM_PHY_INITENG_INITSEQSTARTVECTOR4 */
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR4_INITSEQSTARTVEC4_SHIFT 0
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR4_INITSEQSTARTVEC4_MASK 0x3F

/* HBM_PHY_INITENG_INITSEQSTARTVECTOR5 */
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR5_INITSEQSTARTVEC5_SHIFT 0
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR5_INITSEQSTARTVEC5_MASK 0x3F

/* HBM_PHY_INITENG_INITSEQSTARTVECTOR6 */
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR6_INITSEQSTARTVEC6_SHIFT 0
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR6_INITSEQSTARTVEC6_MASK 0x3F

/* HBM_PHY_INITENG_INITSEQSTARTVECTOR7 */
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR7_INITSEQSTARTVEC7_SHIFT 0
#define HBM_PHY_INITENG_INITSEQSTARTVECTOR7_INITSEQSTARTVEC7_MASK 0x3F

/* HBM_PHY_INITENG_INITSEQWAITCONDSEL */
#define HBM_PHY_INITENG_INITSEQWAITCONDSEL_INITSEQWAITCONDSEL_SHIFT 0
#define HBM_PHY_INITENG_INITSEQWAITCONDSEL_INITSEQWAITCONDSEL_MASK 0x7

/* HBM_PHY_INITENG_INITSEQDLY0_P0 */
#define HBM_PHY_INITENG_INITSEQDLY0_P0_INITSEQDLY0_P0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDLY0_P0_INITSEQDLY0_P0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQDLY1_P0 */
#define HBM_PHY_INITENG_INITSEQDLY1_P0_INITSEQDLY1_P0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDLY1_P0_INITSEQDLY1_P0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQDLY2_P0 */
#define HBM_PHY_INITENG_INITSEQDLY2_P0_INITSEQDLY2_P0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDLY2_P0_INITSEQDLY2_P0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQDLY3_P0 */
#define HBM_PHY_INITENG_INITSEQDLY3_P0_INITSEQDLY3_P0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDLY3_P0_INITSEQDLY3_P0_MASK 0xFFFF

/* HBM_PHY_INITENG_INITSEQOVERRIDE */
#define HBM_PHY_INITENG_INITSEQOVERRIDE_INITSEQFORCESTARTVECTOR_SHIFT 0
#define HBM_PHY_INITENG_INITSEQOVERRIDE_INITSEQFORCESTARTVECTOR_MASK 0xF
#define HBM_PHY_INITENG_INITSEQOVERRIDE_INITSEQFORCESTART_SHIFT 4
#define HBM_PHY_INITENG_INITSEQOVERRIDE_INITSEQFORCESTART_MASK 0x10
#define HBM_PHY_INITENG_INITSEQOVERRIDE_INITSEQFORCESTOP_SHIFT 5
#define HBM_PHY_INITENG_INITSEQOVERRIDE_INITSEQFORCESTOP_MASK 0x20
#define HBM_PHY_INITENG_INITSEQOVERRIDE_INITSEQBLOCKREQUESTS_SHIFT 6
#define HBM_PHY_INITENG_INITSEQOVERRIDE_INITSEQBLOCKREQUESTS_MASK 0x40
#define HBM_PHY_INITENG_INITSEQOVERRIDE_INITSEQBLOCKACK_SHIFT 7
#define HBM_PHY_INITENG_INITSEQOVERRIDE_INITSEQBLOCKACK_MASK 0x80
#define HBM_PHY_INITENG_INITSEQOVERRIDE_DISABLETERMINATEFLAG_SHIFT 8
#define HBM_PHY_INITENG_INITSEQOVERRIDE_DISABLETERMINATEFLAG_MASK 0x100
#define HBM_PHY_INITENG_INITSEQOVERRIDE_SELECTDFIFREQTOGPRMUX_SHIFT 9
#define HBM_PHY_INITENG_INITSEQOVERRIDE_SELECTDFIFREQTOGPRMUX_MASK 0x200

/* HBM_PHY_INITENG_INITSEQDFIFREQXLAT0 */
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT0_INITSEQDFIFREQXLATVAL0_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT0_INITSEQDFIFREQXLATVAL0_MASK 0xF
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT0_INITSEQDFIFREQXLATVAL1_SHIFT 4
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT0_INITSEQDFIFREQXLATVAL1_MASK 0xF0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT0_INITSEQDFIFREQXLATVAL2_SHIFT 8
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT0_INITSEQDFIFREQXLATVAL2_MASK 0xF00
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT0_INITSEQDFIFREQXLATVAL3_SHIFT 12
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT0_INITSEQDFIFREQXLATVAL3_MASK 0xF000

/* HBM_PHY_INITENG_INITSEQDFIFREQXLAT1 */
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT1_INITSEQDFIFREQXLATVAL4_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT1_INITSEQDFIFREQXLATVAL4_MASK 0xF
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT1_INITSEQDFIFREQXLATVAL5_SHIFT 4
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT1_INITSEQDFIFREQXLATVAL5_MASK 0xF0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT1_INITSEQDFIFREQXLATVAL6_SHIFT 8
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT1_INITSEQDFIFREQXLATVAL6_MASK 0xF00
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT1_INITSEQDFIFREQXLATVAL7_SHIFT 12
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT1_INITSEQDFIFREQXLATVAL7_MASK 0xF000

/* HBM_PHY_INITENG_INITSEQDFIFREQXLAT2 */
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT2_INITSEQDFIFREQXLATVAL8_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT2_INITSEQDFIFREQXLATVAL8_MASK 0xF
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT2_INITSEQDFIFREQXLATVAL9_SHIFT 4
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT2_INITSEQDFIFREQXLATVAL9_MASK 0xF0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT2_INITSEQDFIFREQXLATVAL10_SHIFT 8
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT2_INITSEQDFIFREQXLATVAL10_MASK 0xF00
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT2_INITSEQDFIFREQXLATVAL11_SHIFT 12
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT2_INITSEQDFIFREQXLATVAL11_MASK 0xF000

/* HBM_PHY_INITENG_INITSEQDFIFREQXLAT3 */
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT3_INITSEQDFIFREQXLATVAL12_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT3_INITSEQDFIFREQXLATVAL12_MASK 0xF
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT3_INITSEQDFIFREQXLATVAL13_SHIFT 4
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT3_INITSEQDFIFREQXLATVAL13_MASK 0xF0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT3_INITSEQDFIFREQXLATVAL14_SHIFT 8
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT3_INITSEQDFIFREQXLATVAL14_MASK 0xF00
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT3_INITSEQDFIFREQXLATVAL15_SHIFT 12
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT3_INITSEQDFIFREQXLATVAL15_MASK 0xF000

/* HBM_PHY_INITENG_INITSEQDFIFREQXLAT4 */
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT4_INITSEQDFIFREQXLATVAL16_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT4_INITSEQDFIFREQXLATVAL16_MASK 0xF
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT4_INITSEQDFIFREQXLATVAL17_SHIFT 4
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT4_INITSEQDFIFREQXLATVAL17_MASK 0xF0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT4_INITSEQDFIFREQXLATVAL18_SHIFT 8
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT4_INITSEQDFIFREQXLATVAL18_MASK 0xF00
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT4_INITSEQDFIFREQXLATVAL19_SHIFT 12
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT4_INITSEQDFIFREQXLATVAL19_MASK 0xF000

/* HBM_PHY_INITENG_INITSEQDFIFREQXLAT5 */
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT5_INITSEQDFIFREQXLATVAL20_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT5_INITSEQDFIFREQXLATVAL20_MASK 0xF
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT5_INITSEQDFIFREQXLATVAL21_SHIFT 4
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT5_INITSEQDFIFREQXLATVAL21_MASK 0xF0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT5_INITSEQDFIFREQXLATVAL22_SHIFT 8
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT5_INITSEQDFIFREQXLATVAL22_MASK 0xF00
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT5_INITSEQDFIFREQXLATVAL23_SHIFT 12
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT5_INITSEQDFIFREQXLATVAL23_MASK 0xF000

/* HBM_PHY_INITENG_INITSEQDFIFREQXLAT6 */
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT6_INITSEQDFIFREQXLATVAL24_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT6_INITSEQDFIFREQXLATVAL24_MASK 0xF
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT6_INITSEQDFIFREQXLATVAL25_SHIFT 4
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT6_INITSEQDFIFREQXLATVAL25_MASK 0xF0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT6_INITSEQDFIFREQXLATVAL26_SHIFT 8
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT6_INITSEQDFIFREQXLATVAL26_MASK 0xF00
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT6_INITSEQDFIFREQXLATVAL27_SHIFT 12
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT6_INITSEQDFIFREQXLATVAL27_MASK 0xF000

/* HBM_PHY_INITENG_INITSEQDFIFREQXLAT7 */
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT7_INITSEQDFIFREQXLATVAL28_SHIFT 0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT7_INITSEQDFIFREQXLATVAL28_MASK 0xF
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT7_INITSEQDFIFREQXLATVAL29_SHIFT 4
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT7_INITSEQDFIFREQXLATVAL29_MASK 0xF0
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT7_INITSEQDFIFREQXLATVAL30_SHIFT 8
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT7_INITSEQDFIFREQXLATVAL30_MASK 0xF00
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT7_INITSEQDFIFREQXLATVAL31_SHIFT 12
#define HBM_PHY_INITENG_INITSEQDFIFREQXLAT7_INITSEQDFIFREQXLATVAL31_MASK 0xF000

#endif /* ASIC_REG_HBM_PHY_INITENG_MASKS_H_ */
