/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC0_TMR_AXUSER_TMR_FSM_REGS_H_
#define ASIC_REG_NIC0_TMR_AXUSER_TMR_FSM_REGS_H_

/*
 *****************************************
 *   NIC0_TMR_AXUSER_TMR_FSM
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmNIC0_TMR_AXUSER_TMR_FSM_HB_ASID 0x5448E20

#define mmNIC0_TMR_AXUSER_TMR_FSM_HB_MMU_BP 0x5448E24

#define mmNIC0_TMR_AXUSER_TMR_FSM_HB_STRONG_ORDER 0x5448E28

#define mmNIC0_TMR_AXUSER_TMR_FSM_HB_NO_SNOOP 0x5448E2C

#define mmNIC0_TMR_AXUSER_TMR_FSM_HB_WR_REDUCTION 0x5448E30

#define mmNIC0_TMR_AXUSER_TMR_FSM_HB_RD_ATOMIC 0x5448E34

#define mmNIC0_TMR_AXUSER_TMR_FSM_HB_QOS 0x5448E38

#define mmNIC0_TMR_AXUSER_TMR_FSM_HB_RSVD 0x5448E3C

#define mmNIC0_TMR_AXUSER_TMR_FSM_HB_EMEM_CPAGE 0x5448E40

#define mmNIC0_TMR_AXUSER_TMR_FSM_HB_CORE 0x5448E44

#define mmNIC0_TMR_AXUSER_TMR_FSM_E2E_COORD 0x5448E48

#define mmNIC0_TMR_AXUSER_TMR_FSM_HB_WR_OVRD_LO 0x5448E50

#define mmNIC0_TMR_AXUSER_TMR_FSM_HB_WR_OVRD_HI 0x5448E54

#define mmNIC0_TMR_AXUSER_TMR_FSM_HB_RD_OVRD_LO 0x5448E58

#define mmNIC0_TMR_AXUSER_TMR_FSM_HB_RD_OVRD_HI 0x5448E5C

#define mmNIC0_TMR_AXUSER_TMR_FSM_LB_COORD 0x5448E60

#define mmNIC0_TMR_AXUSER_TMR_FSM_LB_LOCK 0x5448E64

#define mmNIC0_TMR_AXUSER_TMR_FSM_LB_RSVD 0x5448E68

#define mmNIC0_TMR_AXUSER_TMR_FSM_LB_OVRD 0x5448E6C

#endif /* ASIC_REG_NIC0_TMR_AXUSER_TMR_FSM_REGS_H_ */
