/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC0_MSTR_IF_CORE_LBW_REGS_H_
#define ASIC_REG_NIC0_MSTR_IF_CORE_LBW_REGS_H_

/*
 *****************************************
 *   NIC0_MSTR_IF_CORE_LBW
 *   (Prototype: MSTR_IF_LBW_CORE)
 *****************************************
 */

#define mmNIC0_MSTR_IF_CORE_LBW_AXPROT_OVRD 0x5455D80

#define mmNIC0_MSTR_IF_CORE_LBW_RL_WR 0x5455D84

#define mmNIC0_MSTR_IF_CORE_LBW_RL_RD 0x5455D88

#define mmNIC0_MSTR_IF_CORE_LBW_MAX_OUTSTANDING_WR_TOTAL 0x5455D8C

#define mmNIC0_MSTR_IF_CORE_LBW_MAX_OUTSTANDING_RD_TOTAL 0x5455D90

#define mmNIC0_MSTR_IF_CORE_LBW_MAX_OUTSTANDING_EN 0x5455D94

#define mmNIC0_MSTR_IF_CORE_LBW_MSG_EN 0x5455D98

#define mmNIC0_MSTR_IF_CORE_LBW_MSG_AXI 0x5455D9C

#define mmNIC0_MSTR_IF_CORE_LBW_MSG_AWADDR 0x5455DA0

#define mmNIC0_MSTR_IF_CORE_LBW_MSG_AWUSER 0x5455DA4

#define mmNIC0_MSTR_IF_CORE_LBW_MSG_AWID 0x5455DA8

#define mmNIC0_MSTR_IF_CORE_LBW_MSG_ID_OFFSET 0x5455DAC

#define mmNIC0_MSTR_IF_CORE_LBW_MSG_AXI_SLVERR 0x5455DB0

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_RANGE_EN_0 0x5455DC0

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_RANGE_EN_1 0x5455DC4

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_RANGE_EN_2 0x5455DC8

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_RANGE_EN_3 0x5455DCC

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_BASE_ADDR_0 0x5455DD0

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_BASE_ADDR_1 0x5455DD4

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_BASE_ADDR_2 0x5455DD8

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_BASE_ADDR_3 0x5455DDC

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_ADDR_MASK_0 0x5455DE0

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_ADDR_MASK_1 0x5455DE4

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_ADDR_MASK_2 0x5455DE8

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_ADDR_MASK_3 0x5455DEC

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_TRGT_ADDR_0 0x5455DF0

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_TRGT_ADDR_1 0x5455DF4

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_TRGT_ADDR_2 0x5455DF8

#define mmNIC0_MSTR_IF_CORE_LBW_AXADDR_OVRD_TRGT_ADDR_3 0x5455DFC

#endif /* ASIC_REG_NIC0_MSTR_IF_CORE_LBW_REGS_H_ */
