/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC0_QPC0_AXUSER_ERR_FIFO_REGS_H_
#define ASIC_REG_NIC0_QPC0_AXUSER_ERR_FIFO_REGS_H_

/*
 *****************************************
 *   NIC0_QPC0_AXUSER_ERR_FIFO
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_HB_ASID 0x541FD60

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_HB_MMU_BP 0x541FD64

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_HB_STRONG_ORDER 0x541FD68

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_HB_NO_SNOOP 0x541FD6C

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_HB_WR_REDUCTION 0x541FD70

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_HB_RD_ATOMIC 0x541FD74

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_HB_QOS 0x541FD78

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_HB_RSVD 0x541FD7C

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_HB_EMEM_CPAGE 0x541FD80

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_HB_CORE 0x541FD84

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_E2E_COORD 0x541FD88

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_HB_WR_OVRD_LO 0x541FD90

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_HB_WR_OVRD_HI 0x541FD94

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_HB_RD_OVRD_LO 0x541FD98

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_HB_RD_OVRD_HI 0x541FD9C

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_LB_COORD 0x541FDA0

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_LB_LOCK 0x541FDA4

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_LB_RSVD 0x541FDA8

#define mmNIC0_QPC0_AXUSER_ERR_FIFO_LB_OVRD 0x541FDAC

#endif /* ASIC_REG_NIC0_QPC0_AXUSER_ERR_FIFO_REGS_H_ */
