/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_REGS_H_
#define ASIC_REG_NIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_REGS_H_

/*
 *****************************************
 *   NIC0_QPC0_AXUSER_EV_QUE_LBW_INTR
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_HB_ASID 0x541FD00

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_HB_MMU_BP 0x541FD04

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_HB_STRONG_ORDER 0x541FD08

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_HB_NO_SNOOP 0x541FD0C

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_HB_WR_REDUCTION 0x541FD10

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_HB_RD_ATOMIC 0x541FD14

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_HB_QOS 0x541FD18

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_HB_RSVD 0x541FD1C

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_HB_EMEM_CPAGE 0x541FD20

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_HB_CORE 0x541FD24

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_E2E_COORD 0x541FD28

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_HB_WR_OVRD_LO 0x541FD30

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_HB_WR_OVRD_HI 0x541FD34

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_HB_RD_OVRD_LO 0x541FD38

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_HB_RD_OVRD_HI 0x541FD3C

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_LB_COORD 0x541FD40

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_LB_LOCK 0x541FD44

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_LB_RSVD 0x541FD48

#define mmNIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_LB_OVRD 0x541FD4C

#endif /* ASIC_REG_NIC0_QPC0_AXUSER_EV_QUE_LBW_INTR_REGS_H_ */
