/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC0_MAC_GLOB_STAT_CONTROL_REG_MASKS_H_
#define ASIC_REG_NIC0_MAC_GLOB_STAT_CONTROL_REG_MASKS_H_

/*
 *****************************************
 *   NIC0_MAC_GLOB_STAT_CONTROL_REG
 *   (Prototype: MAC_CONTROL_REG)
 *****************************************
 */

/* NIC0_MAC_GLOB_STAT_CONTROL_REG_DATA_HI */
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_DATA_HI_DATAHI_SHIFT 0
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_DATA_HI_DATAHI_MASK 0xFFFFFFFF

/* NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_STATUS */
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_STATUS_RXBUSY_SHIFT 0
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_STATUS_RXBUSY_MASK 0x1
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_STATUS_TXBUSY_SHIFT 1
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_STATUS_TXBUSY_MASK 0x2

/* NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONFIG */
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONFIG_SATURATE_SHIFT 0
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONFIG_SATURATE_MASK 0x1
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONFIG_CLEARONREAD_SHIFT 1
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONFIG_CLEARONREAD_MASK 0x2
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONFIG_F_RESET_SHIFT 31
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONFIG_F_RESET_MASK 0x80000000

/* NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONTROL */
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONTROL_PORTMASK_SHIFT 0
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONTROL_PORTMASK_MASK 0xFF
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONTROL_RESERVED_27_SHIFT 27
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONTROL_RESERVED_27_MASK 0x8000000
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONTROL_RESERVED_28_SHIFT 28
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONTROL_RESERVED_28_MASK 0x10000000
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONTROL_CLEARPRE_SHIFT 29
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONTROL_CLEARPRE_MASK 0x20000000
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONTROL_CMDCLEARRX_SHIFT 30
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONTROL_CMDCLEARRX_MASK 0x40000000
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONTROL_CMDCLEARTX_SHIFT 31
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_STATN_CONTROL_CMDCLEARTX_MASK 0x80000000

/* NIC0_MAC_GLOB_STAT_CONTROL_REG_CVALUE_LO */
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_CVALUE_LO_CVALUELO_SHIFT 0
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_CVALUE_LO_CVALUELO_MASK 0xFFFFFFFF

/* NIC0_MAC_GLOB_STAT_CONTROL_REG_CVALUE_HI */
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_CVALUE_HI_CVALUEHI_SHIFT 0
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_CVALUE_HI_CVALUEHI_MASK 0xFFFFFFFF

/* NIC0_MAC_GLOB_STAT_CONTROL_REG_DATA_HI2 */
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_DATA_HI2_DATAHI2_SHIFT 0
#define NIC0_MAC_GLOB_STAT_CONTROL_REG_DATA_HI2_DATAHI2_MASK 0xFFFFFFFF

#endif /* ASIC_REG_NIC0_MAC_GLOB_STAT_CONTROL_REG_MASKS_H_ */
