/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_REGS_H_
#define ASIC_REG_NIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_REGS_H_

/*
 *****************************************
 *   NIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_HB_ASID 0x541FC40

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_HB_MMU_BP 0x541FC44

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_HB_STRONG_ORDER 0x541FC48

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_HB_NO_SNOOP 0x541FC4C

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_HB_WR_REDUCTION 0x541FC50

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_HB_RD_ATOMIC 0x541FC54

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_HB_QOS 0x541FC58

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_HB_RSVD 0x541FC5C

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_HB_EMEM_CPAGE 0x541FC60

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_HB_CORE 0x541FC64

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_E2E_COORD 0x541FC68

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_HB_WR_OVRD_LO 0x541FC70

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_HB_WR_OVRD_HI 0x541FC74

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_HB_RD_OVRD_LO 0x541FC78

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_HB_RD_OVRD_HI 0x541FC7C

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_LB_COORD 0x541FC80

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_LB_LOCK 0x541FC84

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_LB_RSVD 0x541FC88

#define mmNIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_LB_OVRD 0x541FC8C

#endif /* ASIC_REG_NIC0_QPC0_AXUSER_TXWQE_LBW_QMAN_BP_REGS_H_ */
