/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_AUTONOMOUS_CONTROL_MASKS_H_
#define ASIC_REG_AUTONOMOUS_CONTROL_MASKS_H_

/*
 *****************************************
 *   AUTONOMOUS_CONTROL
 *   (Prototype: AUTONOMOUS_CONTROL)
 *****************************************
 */

/* AUTONOMOUS_CONTROL_CTRL */
#define AUTONOMOUS_CONTROL_CTRL_EN_S 0
#define AUTONOMOUS_CONTROL_CTRL_EN_M 0x1
#define AUTONOMOUS_CONTROL_CTRL_NUM_CMD_S 4
#define AUTONOMOUS_CONTROL_CTRL_NUM_CMD_M 0xF0

/* AUTONOMOUS_CONTROL_IP_PROT */
#define AUTONOMOUS_CONTROL_IP_PROT_VAL_S 0
#define AUTONOMOUS_CONTROL_IP_PROT_VAL_M 0x7

/* AUTONOMOUS_CONTROL_LBW_PROT */
#define AUTONOMOUS_CONTROL_LBW_PROT_VAL_S 0
#define AUTONOMOUS_CONTROL_LBW_PROT_VAL_M 0x7

/* AUTONOMOUS_CONTROL_POLLING_MASK */
#define AUTONOMOUS_CONTROL_POLLING_MASK_VAL_S 0
#define AUTONOMOUS_CONTROL_POLLING_MASK_VAL_M 0xFFFFFFFF

/* AUTONOMOUS_CONTROL_STATUS */
#define AUTONOMOUS_CONTROL_STATUS_APB_ERR_S 0
#define AUTONOMOUS_CONTROL_STATUS_APB_ERR_M 0x1
#define AUTONOMOUS_CONTROL_STATUS_CMD_ERR_S 1
#define AUTONOMOUS_CONTROL_STATUS_CMD_ERR_M 0x2
#define AUTONOMOUS_CONTROL_STATUS_IDLE_S 2
#define AUTONOMOUS_CONTROL_STATUS_IDLE_M 0x4
#define AUTONOMOUS_CONTROL_STATUS_APB_ERR_INDEX_S 4
#define AUTONOMOUS_CONTROL_STATUS_APB_ERR_INDEX_M 0xF0
#define AUTONOMOUS_CONTROL_STATUS_CMD_ERR_INDEX_S 8
#define AUTONOMOUS_CONTROL_STATUS_CMD_ERR_INDEX_M 0xF00
#define AUTONOMOUS_CONTROL_STATUS_CURRENT_INDEX_S 16
#define AUTONOMOUS_CONTROL_STATUS_CURRENT_INDEX_M 0xF0000

/* AUTONOMOUS_CONTROL_CMD_ENTRY */
#define AUTONOMOUS_CONTROL_CMD_ENTRY_VAL_S 0
#define AUTONOMOUS_CONTROL_CMD_ENTRY_VAL_M 0xF

/* AUTONOMOUS_CONTROL_ADDR_ENTRY */
#define AUTONOMOUS_CONTROL_ADDR_ENTRY_VAL_S 0
#define AUTONOMOUS_CONTROL_ADDR_ENTRY_VAL_M 0xFFFFFFFF

/* AUTONOMOUS_CONTROL_DATA_ENTRY */
#define AUTONOMOUS_CONTROL_DATA_ENTRY_VAL_S 0
#define AUTONOMOUS_CONTROL_DATA_ENTRY_VAL_M 0xFFFFFFFF

#endif /* ASIC_REG_AUTONOMOUS_CONTROL_MASKS_H_ */
