/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_ETR_MASKS_H_
#define ASIC_REG_ETR_MASKS_H_

/*
 *****************************************
 *   ETR
 *   (Prototype: ETR)
 *****************************************
 */

/* ETR_RSZ */
#define ETR_RSZ_ETR_S 0
#define ETR_RSZ_ETR_M 0x7FFFFFFF

/* ETR_STS */
#define ETR_STS_FULL_S 0
#define ETR_STS_FULL_M 0x1
#define ETR_STS_TRIGGERED_S 1
#define ETR_STS_TRIGGERED_M 0x2
#define ETR_STS_TMCREADY_S 2
#define ETR_STS_TMCREADY_M 0x4
#define ETR_STS_FTEMPTY_S 3
#define ETR_STS_FTEMPTY_M 0x8
#define ETR_STS_EMPTY_S 4
#define ETR_STS_EMPTY_M 0x10
#define ETR_STS_MEMERR_S 5
#define ETR_STS_MEMERR_M 0x20

/* ETR_RRD */
#define ETR_RRD_VAL_S 0
#define ETR_RRD_VAL_M 0xFFFFFFFF

/* ETR_RRP */
#define ETR_RRP_VAL_S 0
#define ETR_RRP_VAL_M 0xFFFFFFFF

/* ETR_RWP */
#define ETR_RWP_VAL_S 0
#define ETR_RWP_VAL_M 0xFFFFFFFF

/* ETR_TRG */
#define ETR_TRG_VAL_S 0
#define ETR_TRG_VAL_M 0xFFFFFFFF

/* ETR_CTL */
#define ETR_CTL_TRACECAPTEN_S 0
#define ETR_CTL_TRACECAPTEN_M 0x1

/* ETR_RWD */
#define ETR_RWD_VAL_S 0
#define ETR_RWD_VAL_M 0xFFFFFFFF

/* ETR_MODE */
#define ETR_MODE_VAL_S 0
#define ETR_MODE_VAL_M 0x3

/* ETR_LBUFLEVEL */
#define ETR_LBUFLEVEL_VAL_S 0
#define ETR_LBUFLEVEL_VAL_M 0x7FFFFFFF

/* ETR_CBUFLEVEL */
#define ETR_CBUFLEVEL_VAL_S 0
#define ETR_CBUFLEVEL_VAL_M 0x7FFFFFFF

/* ETR_BUFWM */
#define ETR_BUFWM_VAL_S 0
#define ETR_BUFWM_VAL_M 0x3FFFFFFF

/* ETR_RRPHI */
#define ETR_RRPHI_VAL_S 0
#define ETR_RRPHI_VAL_M 0xFF

/* ETR_RWPHI */
#define ETR_RWPHI_VAL_S 0
#define ETR_RWPHI_VAL_M 0xFF

/* ETR_AXICTL */
#define ETR_AXICTL_PROTCTRLBIT0_S 0
#define ETR_AXICTL_PROTCTRLBIT0_M 0x1
#define ETR_AXICTL_PROTCTRLBIT1_S 1
#define ETR_AXICTL_PROTCTRLBIT1_M 0x2
#define ETR_AXICTL_CACHECTRLBIT0_S 2
#define ETR_AXICTL_CACHECTRLBIT0_M 0x4
#define ETR_AXICTL_CACHECTRLBIT1_S 3
#define ETR_AXICTL_CACHECTRLBIT1_M 0x8
#define ETR_AXICTL_CACHECTRLBIT2_S 4
#define ETR_AXICTL_CACHECTRLBIT2_M 0x10
#define ETR_AXICTL_CACHECTRLBIT3_S 5
#define ETR_AXICTL_CACHECTRLBIT3_M 0x20
#define ETR_AXICTL_SCATTERGATHERMODE_S 7
#define ETR_AXICTL_SCATTERGATHERMODE_M 0x80
#define ETR_AXICTL_WRBURSTLEN_S 8
#define ETR_AXICTL_WRBURSTLEN_M 0xF00

/* ETR_DBALO */
#define ETR_DBALO_BUFADDRLO_S 0
#define ETR_DBALO_BUFADDRLO_M 0xFFFFFFFF

/* ETR_DBAHI */
#define ETR_DBAHI_BUFADDRHI_S 0
#define ETR_DBAHI_BUFADDRHI_M 0xFF

/* ETR_FFSR */
#define ETR_FFSR_FLINPROG_S 0
#define ETR_FFSR_FLINPROG_M 0x1
#define ETR_FFSR_FTSTOPPED_S 1
#define ETR_FFSR_FTSTOPPED_M 0x2

/* ETR_FFCR */
#define ETR_FFCR_ENFT_S 0
#define ETR_FFCR_ENFT_M 0x1
#define ETR_FFCR_ENTI_S 1
#define ETR_FFCR_ENTI_M 0x2
#define ETR_FFCR_FONFLIN_S 4
#define ETR_FFCR_FONFLIN_M 0x10
#define ETR_FFCR_FONTRIGEVT_S 5
#define ETR_FFCR_FONTRIGEVT_M 0x20
#define ETR_FFCR_FLUSHMAN_S 6
#define ETR_FFCR_FLUSHMAN_M 0x40
#define ETR_FFCR_TRIGONTRIGIN_S 8
#define ETR_FFCR_TRIGONTRIGIN_M 0x100
#define ETR_FFCR_TRIGONTRIGEVT_S 9
#define ETR_FFCR_TRIGONTRIGEVT_M 0x200
#define ETR_FFCR_TRIGONFL_S 10
#define ETR_FFCR_TRIGONFL_M 0x400
#define ETR_FFCR_STOPONFL_S 12
#define ETR_FFCR_STOPONFL_M 0x1000
#define ETR_FFCR_STOPONTRIGEVT_S 13
#define ETR_FFCR_STOPONTRIGEVT_M 0x2000

/* ETR_PSCR */
#define ETR_PSCR_PSCOUNT_S 0
#define ETR_PSCR_PSCOUNT_M 0x1F

/* ETR_ITMISCOP0 */
#define ETR_ITMISCOP0_ACQCOMP_S 0
#define ETR_ITMISCOP0_ACQCOMP_M 0x1
#define ETR_ITMISCOP0_FULL_S 1
#define ETR_ITMISCOP0_FULL_M 0x2

/* ETR_ITTRFLIN */
#define ETR_ITTRFLIN_TRIGIN_S 0
#define ETR_ITTRFLIN_TRIGIN_M 0x1
#define ETR_ITTRFLIN_FLUSHIN_S 1
#define ETR_ITTRFLIN_FLUSHIN_M 0x2

/* ETR_ITATBDATA0 */
#define ETR_ITATBDATA0_ATDATASBIT0_S 0
#define ETR_ITATBDATA0_ATDATASBIT0_M 0x1
#define ETR_ITATBDATA0_ATDATASBIT7_S 1
#define ETR_ITATBDATA0_ATDATASBIT7_M 0x2
#define ETR_ITATBDATA0_ATDATASBIT15_S 2
#define ETR_ITATBDATA0_ATDATASBIT15_M 0x4
#define ETR_ITATBDATA0_ATDATASBIT23_S 3
#define ETR_ITATBDATA0_ATDATASBIT23_M 0x8
#define ETR_ITATBDATA0_ATDATASBIT31_S 4
#define ETR_ITATBDATA0_ATDATASBIT31_M 0x10
#define ETR_ITATBDATA0_ATDATASBIT39_S 5
#define ETR_ITATBDATA0_ATDATASBIT39_M 0x20
#define ETR_ITATBDATA0_ATDATASBIT47_S 6
#define ETR_ITATBDATA0_ATDATASBIT47_M 0x40
#define ETR_ITATBDATA0_ATDATASBIT55_S 7
#define ETR_ITATBDATA0_ATDATASBIT55_M 0x80
#define ETR_ITATBDATA0_ATDATASBIT63_S 8
#define ETR_ITATBDATA0_ATDATASBIT63_M 0x100

/* ETR_ITATBCTR2 */
#define ETR_ITATBCTR2_ATREADYS_S 0
#define ETR_ITATBCTR2_ATREADYS_M 0x1
#define ETR_ITATBCTR2_AFVALIDS_S 1
#define ETR_ITATBCTR2_AFVALIDS_M 0x2
#define ETR_ITATBCTR2_SYNCREQS_S 2
#define ETR_ITATBCTR2_SYNCREQS_M 0x4

/* ETR_ITATBCTR1 */
#define ETR_ITATBCTR1_ATIDS_S 0
#define ETR_ITATBCTR1_ATIDS_M 0x7F

/* ETR_ITATBCTR0 */
#define ETR_ITATBCTR0_ATVALIDS_S 0
#define ETR_ITATBCTR0_ATVALIDS_M 0x1
#define ETR_ITATBCTR0_AFREADYS_S 1
#define ETR_ITATBCTR0_AFREADYS_M 0x2
#define ETR_ITATBCTR0_ATBYTESS_S 8
#define ETR_ITATBCTR0_ATBYTESS_M 0x700

/* ETR_ITCTRL */
#define ETR_ITCTRL_INTEGRATION_MODE_S 0
#define ETR_ITCTRL_INTEGRATION_MODE_M 0x1

/* ETR_CLAIMSET */
#define ETR_CLAIMSET_VAL_S 0
#define ETR_CLAIMSET_VAL_M 0xF

/* ETR_CLAIMCLR */
#define ETR_CLAIMCLR_VAL_S 0
#define ETR_CLAIMCLR_VAL_M 0xF

/* ETR_LAR */
#define ETR_LAR_ACCESS_W_S 0
#define ETR_LAR_ACCESS_W_M 0xFFFFFFFF

/* ETR_LSR */
#define ETR_LSR_LOCKEXIST_S 0
#define ETR_LSR_LOCKEXIST_M 0x1
#define ETR_LSR_LOCKGRANT_S 1
#define ETR_LSR_LOCKGRANT_M 0x2
#define ETR_LSR_LOCKTYPE_S 2
#define ETR_LSR_LOCKTYPE_M 0x4

/* ETR_AUTHSTATUS */
#define ETR_AUTHSTATUS_NSID_S 0
#define ETR_AUTHSTATUS_NSID_M 0x3
#define ETR_AUTHSTATUS_NSNID_S 2
#define ETR_AUTHSTATUS_NSNID_M 0xC
#define ETR_AUTHSTATUS_SID_S 4
#define ETR_AUTHSTATUS_SID_M 0x30
#define ETR_AUTHSTATUS_SNID_S 6
#define ETR_AUTHSTATUS_SNID_M 0xC0

/* ETR_DEVID */
#define ETR_DEVID_ATBINPORTCOUNT_S 0
#define ETR_DEVID_ATBINPORTCOUNT_M 0x1F
#define ETR_DEVID_CLKSCHEME_S 5
#define ETR_DEVID_CLKSCHEME_M 0x20
#define ETR_DEVID_CONFIGTYPE_S 6
#define ETR_DEVID_CONFIGTYPE_M 0xC0
#define ETR_DEVID_MEMWIDTH_S 8
#define ETR_DEVID_MEMWIDTH_M 0x700
#define ETR_DEVID_WBUF_DEPTH_S 11
#define ETR_DEVID_WBUF_DEPTH_M 0x3800

/* ETR_DEVTYPE */
#define ETR_DEVTYPE_MAJOR_TYPE_S 0
#define ETR_DEVTYPE_MAJOR_TYPE_M 0xF
#define ETR_DEVTYPE_SUB_TYPE_S 4
#define ETR_DEVTYPE_SUB_TYPE_M 0xF0

/* ETR_PERIPHID4 */
#define ETR_PERIPHID4_JEP106_CONT_S 0
#define ETR_PERIPHID4_JEP106_CONT_M 0xF
#define ETR_PERIPHID4_FOURKB_COUNT_S 4
#define ETR_PERIPHID4_FOURKB_COUNT_M 0xF0

/* ETR_PERIPHID5 */
#define ETR_PERIPHID5_VAL_S 0
#define ETR_PERIPHID5_VAL_M 0xFFFFFFFF

/* ETR_PERIPHID6 */
#define ETR_PERIPHID6_VAL_S 0
#define ETR_PERIPHID6_VAL_M 0xFFFFFFFF

/* ETR_PERIPHID7 */
#define ETR_PERIPHID7_VAL_S 0
#define ETR_PERIPHID7_VAL_M 0xFFFFFFFF

/* ETR_PERIPHID0 */
#define ETR_PERIPHID0_PART_NUMBER_BITS7TO0_S 0
#define ETR_PERIPHID0_PART_NUMBER_BITS7TO0_M 0xFF

/* ETR_PERIPHID1 */
#define ETR_PERIPHID1_PART_NUMBER_BITS11TO8_S 0
#define ETR_PERIPHID1_PART_NUMBER_BITS11TO8_M 0xF
#define ETR_PERIPHID1_JEP106_BITS3TO0_S 4
#define ETR_PERIPHID1_JEP106_BITS3TO0_M 0xF0

/* ETR_PERIPHID2 */
#define ETR_PERIPHID2_JEP106_BITS6TO4_S 0
#define ETR_PERIPHID2_JEP106_BITS6TO4_M 0x7
#define ETR_PERIPHID2_JEDEC_S 3
#define ETR_PERIPHID2_JEDEC_M 0x8
#define ETR_PERIPHID2_REVISION_S 4
#define ETR_PERIPHID2_REVISION_M 0xF0

/* ETR_PERIPHID3 */
#define ETR_PERIPHID3_CUSTOMER_MODIFIED_S 0
#define ETR_PERIPHID3_CUSTOMER_MODIFIED_M 0xF
#define ETR_PERIPHID3_REVAND_S 4
#define ETR_PERIPHID3_REVAND_M 0xF0

/* ETR_COMPID0 */
#define ETR_COMPID0_PREAMBLE_S 0
#define ETR_COMPID0_PREAMBLE_M 0xFF

/* ETR_COMPID1 */
#define ETR_COMPID1_PREAMBLE_S 0
#define ETR_COMPID1_PREAMBLE_M 0xF
#define ETR_COMPID1_F_CLASS_S 4
#define ETR_COMPID1_F_CLASS_M 0xF0

/* ETR_COMPID2 */
#define ETR_COMPID2_PREAMBLE_S 0
#define ETR_COMPID2_PREAMBLE_M 0xFF

/* ETR_COMPID3 */
#define ETR_COMPID3_PREAMBLE_S 0
#define ETR_COMPID3_PREAMBLE_M 0xFF

#endif /* ASIC_REG_ETR_MASKS_H_ */
