/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_HBM_PHY_P0_MASTER_REGS_H_
#define ASIC_REG_HBM_PHY_P0_MASTER_REGS_H_

/*
 *****************************************
 *   HBM_PHY_P0_MASTER
 *   (Prototype: HBM_PHY_P0_MASTER)
 *****************************************
 */

#define mmHBM_PHY_P0_MASTER_MASTERCTRL 0x0

#define mmHBM_PHY_P0_MASTER_PUBMODE 0x4

#define mmHBM_PHY_P0_MASTER_TRAINCTRL 0x8

#define mmHBM_PHY_P0_MASTER_TRAINSTATUS 0xC

#define mmHBM_PHY_P0_MASTER_P1500CTRL 0x10

#define mmHBM_PHY_P0_MASTER_LANEREPAIRCTRL 0x14

#define mmHBM_PHY_P0_MASTER_LANEREPAIRSTATUS 0x18

#define mmHBM_PHY_P0_MASTER_TRAINCFG 0x1C

#define mmHBM_PHY_P0_MASTER_CLOCKINGCTRL 0x20

#define mmHBM_PHY_P0_MASTER_TESTBUMPCNTRL 0x24

#define mmHBM_PHY_P0_MASTER_RSVDMST 0x28

#define mmHBM_PHY_P0_MASTER_CHNSTATUS 0x2C

#define mmHBM_PHY_P0_MASTER_MISCSTATUS 0x30

#define mmHBM_PHY_P0_MASTER_PSTATE 0x34

#define mmHBM_PHY_P0_MASTER_CMDSEQREG0 0x38

#define mmHBM_PHY_P0_MASTER_CMDSEQREG1 0x3C

#define mmHBM_PHY_P0_MASTER_CMDSEQREG2 0x40

#define mmHBM_PHY_P0_MASTER_CMDSEQREG3 0x44

#define mmHBM_PHY_P0_MASTER_CMDSEQREG4 0x48

#define mmHBM_PHY_P0_MASTER_CMDSEQREG5 0x4C

#define mmHBM_PHY_P0_MASTER_CMDSEQREG6 0x50

#define mmHBM_PHY_P0_MASTER_CMDSEQREG7 0x54

#define mmHBM_PHY_P0_MASTER_CMDSEQREG8 0x58

#define mmHBM_PHY_P0_MASTER_CMDSEQREG9 0x5C

#define mmHBM_PHY_P0_MASTER_CMDSEQREG10 0x60

#define mmHBM_PHY_P0_MASTER_CMDSEQREG11 0x64

#define mmHBM_PHY_P0_MASTER_CMDSEQREG12 0x68

#define mmHBM_PHY_P0_MASTER_CMDSEQREG13 0x6C

#define mmHBM_PHY_P0_MASTER_CMDSEQREG14 0x70

#define mmHBM_PHY_P0_MASTER_CMDSEQREG15 0x74

#define mmHBM_PHY_P0_MASTER_CMDSEQCTRL0 0x78

#define mmHBM_PHY_P0_MASTER_CMDSEQCTRL1 0x7C

#define mmHBM_PHY_P0_MASTER_CMDSEQSTATUS 0x80

#define mmHBM_PHY_P0_MASTER_CMDREPEAT 0x84

#define mmHBM_PHY_P0_MASTER_WSOREADSTATUS 0x88

#define mmHBM_PHY_P0_MASTER_WSOREADDATA0 0x8C

#define mmHBM_PHY_P0_MASTER_WSOREADDATA1 0x90

#define mmHBM_PHY_P0_MASTER_P1500TIMING0 0x94

#define mmHBM_PHY_P0_MASTER_P1500TIMING1 0x98

#define mmHBM_PHY_P0_MASTER_MR0 0x9C

#define mmHBM_PHY_P0_MASTER_MR1 0xA0

#define mmHBM_PHY_P0_MASTER_MR2 0xA4

#define mmHBM_PHY_P0_MASTER_MR3 0xA8

#define mmHBM_PHY_P0_MASTER_MR4 0xAC

#define mmHBM_PHY_P0_MASTER_MR5 0xB0

#define mmHBM_PHY_P0_MASTER_MR6 0xB4

#define mmHBM_PHY_P0_MASTER_MR7 0xB8

#define mmHBM_PHY_P0_MASTER_DRAMTIMING0 0xBC

#define mmHBM_PHY_P0_MASTER_DRAMTIMING1 0xC0

#define mmHBM_PHY_P0_MASTER_DRAMTIMING2 0xC4

#define mmHBM_PHY_P0_MASTER_DRAMTIMING3 0xC8

#define mmHBM_PHY_P0_MASTER_DRAMTIMING4 0xCC

#define mmHBM_PHY_P0_MASTER_DRAMTIMING5 0xD0

#define mmHBM_PHY_P0_MASTER_DRAMTIMING6 0xD4

#define mmHBM_PHY_P0_MASTER_DRAMTIMING7 0xD8

#define mmHBM_PHY_P0_MASTER_DRAMCMD0 0xDC

#define mmHBM_PHY_P0_MASTER_DRAMCMD1 0xE0

#define mmHBM_PHY_P0_MASTER_DRAMCMD2 0xE4

#define mmHBM_PHY_P0_MASTER_DRAMCMD3 0xE8

#define mmHBM_PHY_P0_MASTER_DRAMDEVICEID0 0xEC

#define mmHBM_PHY_P0_MASTER_DRAMDEVICEID1 0xF0

#define mmHBM_PHY_P0_MASTER_DRAMDEVICEID2 0xF4

#define mmHBM_PHY_P0_MASTER_DRAMDEVICEID3 0xF8

#define mmHBM_PHY_P0_MASTER_DRAMDEVICEID4 0xFC

#define mmHBM_PHY_P0_MASTER_DRAMDEVICEID5 0x100

#define mmHBM_PHY_P0_MASTER_LCDLCONTROL 0x104

#define mmHBM_PHY_P0_MASTER_VREFINGLOBAL_P0 0x108

#define mmHBM_PHY_P0_MASTER_VREFINDACSTATUS 0x10C

#define mmHBM_PHY_P0_MASTER_DFIINITCOMPLETE 0x110

#define mmHBM_PHY_P0_MASTER_CALCMPSTARTUPTIME_P0 0x114

#define mmHBM_PHY_P0_MASTER_CALINITVALS 0x118

#define mmHBM_PHY_P0_MASTER_CALINITVALS2 0x11C

#define mmHBM_PHY_P0_MASTER_CALSAMPLETIME_P0 0x120

#define mmHBM_PHY_P0_MASTER_CALOFFSETSAMPLETIME_P0 0x124

#define mmHBM_PHY_P0_MASTER_CALOFFSETS 0x128

#define mmHBM_PHY_P0_MASTER_CALCMPR5OVR 0x12C

#define mmHBM_PHY_P0_MASTER_CALSCALECTRL 0x130

#define mmHBM_PHY_P0_MASTER_CALRUN 0x134

#define mmHBM_PHY_P0_MASTER_CALZAP 0x138

#define mmHBM_PHY_P0_MASTER_CALBUSY 0x13C

#define mmHBM_PHY_P0_MASTER_CALMISC 0x140

#define mmHBM_PHY_P0_MASTER_CALMISC2 0x144

#define mmHBM_PHY_P0_MASTER_CALCMPR5 0x148

#define mmHBM_PHY_P0_MASTER_TXCAL 0x14C

#define mmHBM_PHY_P0_MASTER_CALCMPINVERT 0x150

#define mmHBM_PHY_P0_MASTER_CALCMPANACNTRL 0x154

#define mmHBM_PHY_P0_MASTER_RSVDMD 0x158

#define mmHBM_PHY_P0_MASTER_MIDSTACKTXCAL 0x15C

#define mmHBM_PHY_P0_MASTER_TESTOUTTXCALDATOVR 0x160

#define mmHBM_PHY_P0_MASTER_CLOCKGATECTRL 0x164

#define mmHBM_PHY_P0_MASTER_PLLCTRL0 0x168

#define mmHBM_PHY_P0_MASTER_PLLCTRL1_P0 0x16C

#define mmHBM_PHY_P0_MASTER_PLLCTRL2_P0 0x170

#define mmHBM_PHY_P0_MASTER_PLLCTRL3 0x174

#define mmHBM_PHY_P0_MASTER_PLLCTRL4_P0 0x178

#define mmHBM_PHY_P0_MASTER_BISTCTRL0 0x17C

#define mmHBM_PHY_P0_MASTER_BISTCTRL1 0x180

#define mmHBM_PHY_P0_MASTER_PUBMODECTRL0 0x184

#define mmHBM_PHY_P0_MASTER_PUBMODECTRL1 0x188

#define mmHBM_PHY_P0_MASTER_PUBMODECTRL2 0x18C

#define mmHBM_PHY_P0_MASTER_PUBMODECTRL3 0x190

#define mmHBM_PHY_P0_MASTER_PUBMODECTRL4 0x194

#define mmHBM_PHY_P0_MASTER_BISTSTATUS 0x198

#define mmHBM_PHY_P0_MASTER_PLLPWRDN 0x19C

#define mmHBM_PHY_P0_MASTER_PLLTESTMODE_P0 0x1A0

#define mmHBM_PHY_P0_MASTER_PLLSTATUS 0x1A4

#define mmHBM_PHY_P0_MASTER_PLLTST 0x1A8

#define mmHBM_PHY_P0_MASTER_PLLLOCKSTATUS 0x1AC

#define mmHBM_PHY_P0_MASTER_PORCONTROL 0x1B0

#define mmHBM_PHY_P0_MASTER_TXRDPTRINIT 0x1B4

#define mmHBM_PHY_P0_MASTER_CUSTPUBREV 0x1B8

#define mmHBM_PHY_P0_MASTER_CUSTPHYREV 0x1BC

#define mmHBM_PHY_P0_MASTER_PUBREV 0x1C0

#define mmHBM_PHY_P0_MASTER_PHYREV 0x1C4

#define mmHBM_PHY_P0_MASTER_DRAMTIMING8 0x1C8

#define mmHBM_PHY_P0_MASTER_VREFSETTLINGTIME_P0 0x1CC

#endif /* ASIC_REG_HBM_PHY_P0_MASTER_REGS_H_ */
