/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_MC_CH_MASKS_H_
#define ASIC_REG_MC_CH_MASKS_H_

/*
 *****************************************
 *   MC_CH
 *   (Prototype: MC_CH)
 *****************************************
 */

/* MC_CH_AXI_ADMAP_BA_0 */
#define MC_CH_AXI_ADMAP_BA_0_VAL_S 0
#define MC_CH_AXI_ADMAP_BA_0_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_BA_1 */
#define MC_CH_AXI_ADMAP_BA_1_VAL_S 0
#define MC_CH_AXI_ADMAP_BA_1_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_BG_0 */
#define MC_CH_AXI_ADMAP_BG_0_VAL_S 0
#define MC_CH_AXI_ADMAP_BG_0_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_BG_1 */
#define MC_CH_AXI_ADMAP_BG_1_VAL_S 0
#define MC_CH_AXI_ADMAP_BG_1_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_COL_0 */
#define MC_CH_AXI_ADMAP_COL_0_VAL_S 0
#define MC_CH_AXI_ADMAP_COL_0_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_COL_1 */
#define MC_CH_AXI_ADMAP_COL_1_VAL_S 0
#define MC_CH_AXI_ADMAP_COL_1_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_COL_2 */
#define MC_CH_AXI_ADMAP_COL_2_VAL_S 0
#define MC_CH_AXI_ADMAP_COL_2_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_COL_3 */
#define MC_CH_AXI_ADMAP_COL_3_VAL_S 0
#define MC_CH_AXI_ADMAP_COL_3_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_COL_4 */
#define MC_CH_AXI_ADMAP_COL_4_VAL_S 0
#define MC_CH_AXI_ADMAP_COL_4_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_0 */
#define MC_CH_AXI_ADMAP_ROW_0_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_0_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_1 */
#define MC_CH_AXI_ADMAP_ROW_1_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_1_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_2 */
#define MC_CH_AXI_ADMAP_ROW_2_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_2_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_3 */
#define MC_CH_AXI_ADMAP_ROW_3_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_3_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_4 */
#define MC_CH_AXI_ADMAP_ROW_4_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_4_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_5 */
#define MC_CH_AXI_ADMAP_ROW_5_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_5_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_6 */
#define MC_CH_AXI_ADMAP_ROW_6_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_6_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_7 */
#define MC_CH_AXI_ADMAP_ROW_7_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_7_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_8 */
#define MC_CH_AXI_ADMAP_ROW_8_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_8_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_9 */
#define MC_CH_AXI_ADMAP_ROW_9_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_9_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_10 */
#define MC_CH_AXI_ADMAP_ROW_10_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_10_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_11 */
#define MC_CH_AXI_ADMAP_ROW_11_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_11_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_12 */
#define MC_CH_AXI_ADMAP_ROW_12_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_12_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_13 */
#define MC_CH_AXI_ADMAP_ROW_13_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_13_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_ROW_14 */
#define MC_CH_AXI_ADMAP_ROW_14_VAL_S 0
#define MC_CH_AXI_ADMAP_ROW_14_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_SID_0 */
#define MC_CH_AXI_ADMAP_SID_0_VAL_S 0
#define MC_CH_AXI_ADMAP_SID_0_VAL_M 0x3F

/* MC_CH_AXI_ADMAP_SID_1 */
#define MC_CH_AXI_ADMAP_SID_1_VAL_S 0
#define MC_CH_AXI_ADMAP_SID_1_VAL_M 0x3F

/* MC_CH_AXI_GLBL_CFG */
#define MC_CH_AXI_GLBL_CFG_RMW_RD_QOS_S 4
#define MC_CH_AXI_GLBL_CFG_RMW_RD_QOS_M 0x30
#define MC_CH_AXI_GLBL_CFG_RMW_SCH_PRIO_DIS_S 24
#define MC_CH_AXI_GLBL_CFG_RMW_SCH_PRIO_DIS_M 0x1000000
#define MC_CH_AXI_GLBL_CFG_RMW_SCH_ARB_CRED_EN_S 25
#define MC_CH_AXI_GLBL_CFG_RMW_SCH_ARB_CRED_EN_M 0x2000000
#define MC_CH_AXI_GLBL_CFG_SCH_RDY_TO_AW_S 28
#define MC_CH_AXI_GLBL_CFG_SCH_RDY_TO_AW_M 0x10000000
#define MC_CH_AXI_GLBL_CFG_SCH_RDY_TO_AR_S 29
#define MC_CH_AXI_GLBL_CFG_SCH_RDY_TO_AR_M 0x20000000

/* MC_CH_AXI_PE_RESET */
#define MC_CH_AXI_PE_RESET_VAL_S 0
#define MC_CH_AXI_PE_RESET_VAL_M 0xF

/* MC_CH_AXI_PE_SM */
#define MC_CH_AXI_PE_SM_STATE_S 0
#define MC_CH_AXI_PE_SM_STATE_M 0xF

/* MC_CH_AXI_RD_LVL */
#define MC_CH_AXI_RD_LVL_RCLIP_S 0
#define MC_CH_AXI_RD_LVL_RCLIP_M 0xFF
#define MC_CH_AXI_RD_LVL_RDB_S 8
#define MC_CH_AXI_RD_LVL_RDB_M 0xFF00
#define MC_CH_AXI_RD_LVL_RRESP_STD_S 16
#define MC_CH_AXI_RD_LVL_RRESP_STD_M 0x30000
#define MC_CH_AXI_RD_LVL_RRESP_RMW_S 20
#define MC_CH_AXI_RD_LVL_RRESP_RMW_M 0x300000

/* MC_CH_AXI_RRESP_CONSMD_CRED */
#define MC_CH_AXI_RRESP_CONSMD_CRED_VAL_S 0
#define MC_CH_AXI_RRESP_CONSMD_CRED_VAL_M 0xFF

/* MC_CH_AXI_RMW_LVL */
#define MC_CH_AXI_RMW_LVL_RD_FIFO_S 0
#define MC_CH_AXI_RMW_LVL_RD_FIFO_M 0xFF
#define MC_CH_AXI_RMW_LVL_CRED_S 8
#define MC_CH_AXI_RMW_LVL_CRED_M 0xFF00
#define MC_CH_AXI_RMW_LVL_ID_ALC_S 16
#define MC_CH_AXI_RMW_LVL_ID_ALC_M 0xFF0000
#define MC_CH_AXI_RMW_LVL_WDB_RMW0_CB_S 24
#define MC_CH_AXI_RMW_LVL_WDB_RMW0_CB_M 0xF000000
#define MC_CH_AXI_RMW_LVL_WDB_RMW1_CB_S 28
#define MC_CH_AXI_RMW_LVL_WDB_RMW1_CB_M 0xF0000000

/* MC_CH_AXI_STALL_CNT_FORCE_TH */
#define MC_CH_AXI_STALL_CNT_FORCE_TH_VAL_S 0
#define MC_CH_AXI_STALL_CNT_FORCE_TH_VAL_M 0x3FF

/* MC_CH_AXI_STALL_CNT */
#define MC_CH_AXI_STALL_CNT_RD_S 0
#define MC_CH_AXI_STALL_CNT_RD_M 0xFF
#define MC_CH_AXI_STALL_CNT_WR_S 16
#define MC_CH_AXI_STALL_CNT_WR_M 0xFF0000

/* MC_CH_AXI_TRACK_ADDR */
#define MC_CH_AXI_TRACK_ADDR_COL_S 0
#define MC_CH_AXI_TRACK_ADDR_COL_M 0x7
#define MC_CH_AXI_TRACK_ADDR_ROW_S 3
#define MC_CH_AXI_TRACK_ADDR_ROW_M 0x3FFF8
#define MC_CH_AXI_TRACK_ADDR_BA_S 18
#define MC_CH_AXI_TRACK_ADDR_BA_M 0xC0000
#define MC_CH_AXI_TRACK_ADDR_BG_S 20
#define MC_CH_AXI_TRACK_ADDR_BG_M 0x300000
#define MC_CH_AXI_TRACK_ADDR_SID_S 22
#define MC_CH_AXI_TRACK_ADDR_SID_M 0x400000

/* MC_CH_AXI_TRACK_CFG */
#define MC_CH_AXI_TRACK_CFG_COL_EN_S 0
#define MC_CH_AXI_TRACK_CFG_COL_EN_M 0x1
#define MC_CH_AXI_TRACK_CFG_ROW_EN_S 1
#define MC_CH_AXI_TRACK_CFG_ROW_EN_M 0x2
#define MC_CH_AXI_TRACK_CFG_BA_EN_S 2
#define MC_CH_AXI_TRACK_CFG_BA_EN_M 0x4
#define MC_CH_AXI_TRACK_CFG_BG_EN_S 3
#define MC_CH_AXI_TRACK_CFG_BG_EN_M 0x8
#define MC_CH_AXI_TRACK_CFG_SID_EN_S 4
#define MC_CH_AXI_TRACK_CFG_SID_EN_M 0x10
#define MC_CH_AXI_TRACK_CFG_TYP_S 7
#define MC_CH_AXI_TRACK_CFG_TYP_M 0x80

/* MC_CH_AXI_TRACK_OCCUR */
#define MC_CH_AXI_TRACK_OCCUR_VAL_S 0
#define MC_CH_AXI_TRACK_OCCUR_VAL_M 0x7

/* MC_CH_AXI_TRACK_STS_ADDR */
#define MC_CH_AXI_TRACK_STS_ADDR_COL_S 0
#define MC_CH_AXI_TRACK_STS_ADDR_COL_M 0x7
#define MC_CH_AXI_TRACK_STS_ADDR_ROW_S 3
#define MC_CH_AXI_TRACK_STS_ADDR_ROW_M 0x3FFF8
#define MC_CH_AXI_TRACK_STS_ADDR_BA_S 18
#define MC_CH_AXI_TRACK_STS_ADDR_BA_M 0xC0000
#define MC_CH_AXI_TRACK_STS_ADDR_BG_S 20
#define MC_CH_AXI_TRACK_STS_ADDR_BG_M 0x300000
#define MC_CH_AXI_TRACK_STS_ADDR_SID_S 22
#define MC_CH_AXI_TRACK_STS_ADDR_SID_M 0x400000
#define MC_CH_AXI_TRACK_STS_ADDR_QOS_S 28
#define MC_CH_AXI_TRACK_STS_ADDR_QOS_M 0x30000000

/* MC_CH_AXI_TRACK_STS_CLIP_ID */
#define MC_CH_AXI_TRACK_STS_CLIP_ID_VAL_S 0
#define MC_CH_AXI_TRACK_STS_CLIP_ID_VAL_M 0xFF

/* MC_CH_AXI_TRACK_STS_PROPS */
#define MC_CH_AXI_TRACK_STS_PROPS_WAW_S 0
#define MC_CH_AXI_TRACK_STS_PROPS_WAW_M 0x1
#define MC_CH_AXI_TRACK_STS_PROPS_RAW_S 1
#define MC_CH_AXI_TRACK_STS_PROPS_RAW_M 0x2
#define MC_CH_AXI_TRACK_STS_PROPS_RMW_S 2
#define MC_CH_AXI_TRACK_STS_PROPS_RMW_M 0x4
#define MC_CH_AXI_TRACK_STS_PROPS_RMW_LOCAL_S 3
#define MC_CH_AXI_TRACK_STS_PROPS_RMW_LOCAL_M 0x8
#define MC_CH_AXI_TRACK_STS_PROPS_RMW_NOLOCAL_S 4
#define MC_CH_AXI_TRACK_STS_PROPS_RMW_NOLOCAL_M 0x10
#define MC_CH_AXI_TRACK_STS_PROPS_RMW_FWD_S 5
#define MC_CH_AXI_TRACK_STS_PROPS_RMW_FWD_M 0x20
#define MC_CH_AXI_TRACK_STS_PROPS_AXI_RLAST_S 6
#define MC_CH_AXI_TRACK_STS_PROPS_AXI_RLAST_M 0x40
#define MC_CH_AXI_TRACK_STS_PROPS_VLD_S 31
#define MC_CH_AXI_TRACK_STS_PROPS_VLD_M 0x80000000

/* MC_CH_AXI_WR_LVL */
#define MC_CH_AXI_WR_LVL_WCLIP_S 0
#define MC_CH_AXI_WR_LVL_WCLIP_M 0xFF
#define MC_CH_AXI_WR_LVL_RMW_CNT_S 8
#define MC_CH_AXI_WR_LVL_RMW_CNT_M 0xFF00
#define MC_CH_AXI_WR_LVL_WRESP_S 16
#define MC_CH_AXI_WR_LVL_WRESP_M 0xFF0000

/* MC_CH_AXIS_CLIP_SIZE */
#define MC_CH_AXIS_CLIP_SIZE_WCLIP_0_S 0
#define MC_CH_AXIS_CLIP_SIZE_WCLIP_0_M 0xFF
#define MC_CH_AXIS_CLIP_SIZE_RCLIP_0_S 8
#define MC_CH_AXIS_CLIP_SIZE_RCLIP_0_M 0xFF00
#define MC_CH_AXIS_CLIP_SIZE_WCLIP_1_S 16
#define MC_CH_AXIS_CLIP_SIZE_WCLIP_1_M 0xFF0000
#define MC_CH_AXIS_CLIP_SIZE_RCLIP_1_S 24
#define MC_CH_AXIS_CLIP_SIZE_RCLIP_1_M 0xFF000000

/* MC_CH_AXIS_RMW_CRED */
#define MC_CH_AXIS_RMW_CRED_MAX_0_S 0
#define MC_CH_AXIS_RMW_CRED_MAX_0_M 0x1F
#define MC_CH_AXIS_RMW_CRED_EN_0_S 7
#define MC_CH_AXIS_RMW_CRED_EN_0_M 0x80
#define MC_CH_AXIS_RMW_CRED_MAX_1_S 8
#define MC_CH_AXIS_RMW_CRED_MAX_1_M 0x1F00
#define MC_CH_AXIS_RMW_CRED_EN_1_S 15
#define MC_CH_AXIS_RMW_CRED_EN_1_M 0x8000

/* MC_CH_AXIS_RMW_RSVD */
#define MC_CH_AXIS_RMW_RSVD_NUM_S 0
#define MC_CH_AXIS_RMW_RSVD_NUM_M 0x1F

/* MC_CH_AXIS_RRESP_CFG */
#define MC_CH_AXIS_RRESP_CFG_MASK_S 0
#define MC_CH_AXIS_RRESP_CFG_MASK_M 0x3
#define MC_CH_AXIS_RRESP_CFG_MAX_RS_CRED_STD_S 8
#define MC_CH_AXIS_RRESP_CFG_MAX_RS_CRED_STD_M 0x1F00

/* MC_CH_AXIS_WRESP_CFG */
#define MC_CH_AXIS_WRESP_CFG_TYP_S 0
#define MC_CH_AXIS_WRESP_CFG_TYP_M 0x3
#define MC_CH_AXIS_WRESP_CFG_MASK_S 8
#define MC_CH_AXIS_WRESP_CFG_MASK_M 0x300

/* MC_CH_AXI_IND_STS_REQ */
#define MC_CH_AXI_IND_STS_REQ_ENTRY_S 0
#define MC_CH_AXI_IND_STS_REQ_ENTRY_M 0x7F
#define MC_CH_AXI_IND_STS_REQ_SEL_S 8
#define MC_CH_AXI_IND_STS_REQ_SEL_M 0x300
#define MC_CH_AXI_IND_STS_REQ_VLD_S 31
#define MC_CH_AXI_IND_STS_REQ_VLD_M 0x80000000

/* MC_CH_AXI_IND_STS_RSP */
#define MC_CH_AXI_IND_STS_RSP_VAL_S 0
#define MC_CH_AXI_IND_STS_RSP_VAL_M 0xFFFFFFFF

/* MC_CH_AXI_ERR_STS */
#define MC_CH_AXI_ERR_STS_BRESP_OVF_0_S 0
#define MC_CH_AXI_ERR_STS_BRESP_OVF_0_M 0x1
#define MC_CH_AXI_ERR_STS_RCLIP_FL_OVF_0_S 1
#define MC_CH_AXI_ERR_STS_RCLIP_FL_OVF_0_M 0x2
#define MC_CH_AXI_ERR_STS_RDB_FL_OVF_0_S 2
#define MC_CH_AXI_ERR_STS_RDB_FL_OVF_0_M 0x4
#define MC_CH_AXI_ERR_STS_RMW_FWD_OVF_0_S 3
#define MC_CH_AXI_ERR_STS_RMW_FWD_OVF_0_M 0x8
#define MC_CH_AXI_ERR_STS_RMW_RD_OVF_0_S 4
#define MC_CH_AXI_ERR_STS_RMW_RD_OVF_0_M 0x10
#define MC_CH_AXI_ERR_STS_RMW_FL_OVF_0_S 5
#define MC_CH_AXI_ERR_STS_RMW_FL_OVF_0_M 0x20
#define MC_CH_AXI_ERR_STS_RRESP_OVF_0_S 6
#define MC_CH_AXI_ERR_STS_RRESP_OVF_0_M 0x40
#define MC_CH_AXI_ERR_STS_WCLIP_FL_OVF_0_S 7
#define MC_CH_AXI_ERR_STS_WCLIP_FL_OVF_0_M 0x80
#define MC_CH_AXI_ERR_STS_WCLIP_LL_POP_NHEAD_0_S 8
#define MC_CH_AXI_ERR_STS_WCLIP_LL_POP_NHEAD_0_M 0x100
#define MC_CH_AXI_ERR_STS_BRESP_OVF_1_S 16
#define MC_CH_AXI_ERR_STS_BRESP_OVF_1_M 0x10000
#define MC_CH_AXI_ERR_STS_RCLIP_FL_OVF_1_S 17
#define MC_CH_AXI_ERR_STS_RCLIP_FL_OVF_1_M 0x20000
#define MC_CH_AXI_ERR_STS_RDB_FL_OVF_1_S 18
#define MC_CH_AXI_ERR_STS_RDB_FL_OVF_1_M 0x40000
#define MC_CH_AXI_ERR_STS_RMW_FWD_OVF_1_S 19
#define MC_CH_AXI_ERR_STS_RMW_FWD_OVF_1_M 0x80000
#define MC_CH_AXI_ERR_STS_RMW_RD_OVF_1_S 20
#define MC_CH_AXI_ERR_STS_RMW_RD_OVF_1_M 0x100000
#define MC_CH_AXI_ERR_STS_RMW_FL_OVF_1_S 21
#define MC_CH_AXI_ERR_STS_RMW_FL_OVF_1_M 0x200000
#define MC_CH_AXI_ERR_STS_RRESP_OVF_1_S 22
#define MC_CH_AXI_ERR_STS_RRESP_OVF_1_M 0x400000
#define MC_CH_AXI_ERR_STS_WCLIP_FL_OVF_1_S 23
#define MC_CH_AXI_ERR_STS_WCLIP_FL_OVF_1_M 0x800000
#define MC_CH_AXI_ERR_STS_WCLIP_LL_POP_NHEAD_1_S 24
#define MC_CH_AXI_ERR_STS_WCLIP_LL_POP_NHEAD_1_M 0x1000000

/* MC_CH_RSCH_ENABLE */
#define MC_CH_RSCH_ENABLE_RD_PC0_VAL_S 0
#define MC_CH_RSCH_ENABLE_RD_PC0_VAL_M 0x1
#define MC_CH_RSCH_ENABLE_WR_PC0_VAL_S 1
#define MC_CH_RSCH_ENABLE_WR_PC0_VAL_M 0x2
#define MC_CH_RSCH_ENABLE_RD_PC1_VAL_S 2
#define MC_CH_RSCH_ENABLE_RD_PC1_VAL_M 0x4
#define MC_CH_RSCH_ENABLE_WR_PC1_VAL_S 3
#define MC_CH_RSCH_ENABLE_WR_PC1_VAL_M 0x8

/* MC_CH_RSCH_MAX_PAGE */
#define MC_CH_RSCH_MAX_PAGE_VAL_S 0
#define MC_CH_RSCH_MAX_PAGE_VAL_M 0xFF

/* MC_CH_RSCH_POOL_NUM_OCC_ENTRIES */
#define MC_CH_RSCH_POOL_NUM_OCC_ENTRIES_WR_PC0_S 0
#define MC_CH_RSCH_POOL_NUM_OCC_ENTRIES_WR_PC0_M 0xFF
#define MC_CH_RSCH_POOL_NUM_OCC_ENTRIES_WR_PC1_S 8
#define MC_CH_RSCH_POOL_NUM_OCC_ENTRIES_WR_PC1_M 0xFF00
#define MC_CH_RSCH_POOL_NUM_OCC_ENTRIES_RD_PC0_S 16
#define MC_CH_RSCH_POOL_NUM_OCC_ENTRIES_RD_PC0_M 0xFF0000
#define MC_CH_RSCH_POOL_NUM_OCC_ENTRIES_RD_PC1_S 24
#define MC_CH_RSCH_POOL_NUM_OCC_ENTRIES_RD_PC1_M 0xFF000000

/* MC_CH_RSCH_RD_ALMOST_EMPTY_LEVEL */
#define MC_CH_RSCH_RD_ALMOST_EMPTY_LEVEL_OCC_MIN_LEVEL_S 0
#define MC_CH_RSCH_RD_ALMOST_EMPTY_LEVEL_OCC_MIN_LEVEL_M 0xFF
#define MC_CH_RSCH_RD_ALMOST_EMPTY_LEVEL_VALID_MIN_LEVEL_S 8
#define MC_CH_RSCH_RD_ALMOST_EMPTY_LEVEL_VALID_MIN_LEVEL_M 0xFF00

/* MC_CH_RSCH_RD_BG_SCORE */
#define MC_CH_RSCH_RD_BG_SCORE_VAL_S 0
#define MC_CH_RSCH_RD_BG_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_RD_LATENCY_LEVEL */
#define MC_CH_RSCH_RD_LATENCY_LEVEL_VAL_S 0
#define MC_CH_RSCH_RD_LATENCY_LEVEL_VAL_M 0x3FF

/* MC_CH_RSCH_RD_LATENCY_LEVEL_QOS0_SCORE */
#define MC_CH_RSCH_RD_LATENCY_LEVEL_QOS0_SCORE_VAL_S 0
#define MC_CH_RSCH_RD_LATENCY_LEVEL_QOS0_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_RD_LATENCY_LEVEL_QOS1_SCORE */
#define MC_CH_RSCH_RD_LATENCY_LEVEL_QOS1_SCORE_VAL_S 0
#define MC_CH_RSCH_RD_LATENCY_LEVEL_QOS1_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_RD_LATENCY_LEVEL_QOS2_SCORE */
#define MC_CH_RSCH_RD_LATENCY_LEVEL_QOS2_SCORE_VAL_S 0
#define MC_CH_RSCH_RD_LATENCY_LEVEL_QOS2_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_RD_LATENCY_LEVEL_QOS3_SCORE */
#define MC_CH_RSCH_RD_LATENCY_LEVEL_QOS3_SCORE_VAL_S 0
#define MC_CH_RSCH_RD_LATENCY_LEVEL_QOS3_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_RD_LATENCY_LEVEL_SAT_SCORE */
#define MC_CH_RSCH_RD_LATENCY_LEVEL_SAT_SCORE_VAL_S 0
#define MC_CH_RSCH_RD_LATENCY_LEVEL_SAT_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_RD_MASK_STALL_CNT */
#define MC_CH_RSCH_RD_MASK_STALL_CNT_VAL_S 0
#define MC_CH_RSCH_RD_MASK_STALL_CNT_VAL_M 0x1

/* MC_CH_RSCH_RD_MIN_SATURATED */
#define MC_CH_RSCH_RD_MIN_SATURATED_VAL_S 0
#define MC_CH_RSCH_RD_MIN_SATURATED_VAL_M 0xFF

/* MC_CH_RSCH_RD_MIN_STREAM_LENGTH */
#define MC_CH_RSCH_RD_MIN_STREAM_LENGTH_VAL_S 0
#define MC_CH_RSCH_RD_MIN_STREAM_LENGTH_VAL_M 0x3FF

/* MC_CH_RSCH_RD_OPEN_PAGE_SCORE */
#define MC_CH_RSCH_RD_OPEN_PAGE_SCORE_VAL_S 0
#define MC_CH_RSCH_RD_OPEN_PAGE_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_RD_QOS_ALMOST_FULL_TH */
#define MC_CH_RSCH_RD_QOS_ALMOST_FULL_TH_VAL_S 0
#define MC_CH_RSCH_RD_QOS_ALMOST_FULL_TH_VAL_M 0x3FF

/* MC_CH_RSCH_RD_SAT_HIGH_RPSB */
#define MC_CH_RSCH_RD_SAT_HIGH_RPSB_VAL_S 0
#define MC_CH_RSCH_RD_SAT_HIGH_RPSB_VAL_M 0xFF

/* MC_CH_RSCH_RD_SAT_HIGH_SCORE */
#define MC_CH_RSCH_RD_SAT_HIGH_SCORE_VAL_S 0
#define MC_CH_RSCH_RD_SAT_HIGH_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_RD_SAT_MED_RPSB */
#define MC_CH_RSCH_RD_SAT_MED_RPSB_VAL_S 0
#define MC_CH_RSCH_RD_SAT_MED_RPSB_VAL_M 0xFF

/* MC_CH_RSCH_RD_SAT_MED_SCORE */
#define MC_CH_RSCH_RD_SAT_MED_SCORE_VAL_S 0
#define MC_CH_RSCH_RD_SAT_MED_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_RD_SID_SCORE */
#define MC_CH_RSCH_RD_SID_SCORE_VAL_S 0
#define MC_CH_RSCH_RD_SID_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_RD_SWITCH_LATENCY_LEVEL_QOS0 */
#define MC_CH_RSCH_RD_SWITCH_LATENCY_LEVEL_QOS0_VAL_S 0
#define MC_CH_RSCH_RD_SWITCH_LATENCY_LEVEL_QOS0_VAL_M 0x3FF

/* MC_CH_RSCH_RD_SWITCH_LATENCY_LEVEL_QOS1 */
#define MC_CH_RSCH_RD_SWITCH_LATENCY_LEVEL_QOS1_VAL_S 0
#define MC_CH_RSCH_RD_SWITCH_LATENCY_LEVEL_QOS1_VAL_M 0x3FF

/* MC_CH_RSCH_RD_SWITCH_LATENCY_LEVEL_QOS2 */
#define MC_CH_RSCH_RD_SWITCH_LATENCY_LEVEL_QOS2_VAL_S 0
#define MC_CH_RSCH_RD_SWITCH_LATENCY_LEVEL_QOS2_VAL_M 0x3FF

/* MC_CH_RSCH_RD_SWITCH_LATENCY_LEVEL_QOS3 */
#define MC_CH_RSCH_RD_SWITCH_LATENCY_LEVEL_QOS3_VAL_S 0
#define MC_CH_RSCH_RD_SWITCH_LATENCY_LEVEL_QOS3_VAL_M 0x3FF

/* MC_CH_RSCH_RD_SWITCH_LATENCY_MAX */
#define MC_CH_RSCH_RD_SWITCH_LATENCY_MAX_VAL_S 0
#define MC_CH_RSCH_RD_SWITCH_LATENCY_MAX_VAL_M 0x3FF
#define MC_CH_RSCH_RD_SWITCH_LATENCY_MAX_DISABLE_S 10
#define MC_CH_RSCH_RD_SWITCH_LATENCY_MAX_DISABLE_M 0x400

/* MC_CH_RSCH_RD_SWITCH_OCCUPANCY_LEVEL_QOS0 */
#define MC_CH_RSCH_RD_SWITCH_OCCUPANCY_LEVEL_QOS0_VAL_S 0
#define MC_CH_RSCH_RD_SWITCH_OCCUPANCY_LEVEL_QOS0_VAL_M 0xFF

/* MC_CH_RSCH_RD_SWITCH_OCCUPANCY_LEVEL_QOS1 */
#define MC_CH_RSCH_RD_SWITCH_OCCUPANCY_LEVEL_QOS1_VAL_S 0
#define MC_CH_RSCH_RD_SWITCH_OCCUPANCY_LEVEL_QOS1_VAL_M 0xFF

/* MC_CH_RSCH_RD_SWITCH_OCCUPANCY_LEVEL_QOS2 */
#define MC_CH_RSCH_RD_SWITCH_OCCUPANCY_LEVEL_QOS2_VAL_S 0
#define MC_CH_RSCH_RD_SWITCH_OCCUPANCY_LEVEL_QOS2_VAL_M 0xFF

/* MC_CH_RSCH_RD_SWITCH_OCCUPANCY_LEVEL_QOS3 */
#define MC_CH_RSCH_RD_SWITCH_OCCUPANCY_LEVEL_QOS3_VAL_S 0
#define MC_CH_RSCH_RD_SWITCH_OCCUPANCY_LEVEL_QOS3_VAL_M 0xFF

/* MC_CH_RSCH_RDB_CREDIT_INIT */
#define MC_CH_RSCH_RDB_CREDIT_INIT_VAL_S 0
#define MC_CH_RSCH_RDB_CREDIT_INIT_VAL_M 0xFF

/* MC_CH_RSCH_REF_ARB_TH_VAL */
#define MC_CH_RSCH_REF_ARB_TH_VAL_VAL_S 0
#define MC_CH_RSCH_REF_ARB_TH_VAL_VAL_M 0x1FFFF

/* MC_CH_RSCH_RWS_TRAN_CNTR_OPTION */
#define MC_CH_RSCH_RWS_TRAN_CNTR_OPTION_VAL_S 0
#define MC_CH_RSCH_RWS_TRAN_CNTR_OPTION_VAL_M 0x1

/* MC_CH_RSCH_WR_ALMOST_EMPTY_LEVEL */
#define MC_CH_RSCH_WR_ALMOST_EMPTY_LEVEL_OCC_MIN_LEVEL_S 0
#define MC_CH_RSCH_WR_ALMOST_EMPTY_LEVEL_OCC_MIN_LEVEL_M 0xFF
#define MC_CH_RSCH_WR_ALMOST_EMPTY_LEVEL_VALID_MIN_LEVEL_S 8
#define MC_CH_RSCH_WR_ALMOST_EMPTY_LEVEL_VALID_MIN_LEVEL_M 0xFF00

/* MC_CH_RSCH_WR_BG_SCORE */
#define MC_CH_RSCH_WR_BG_SCORE_VAL_S 0
#define MC_CH_RSCH_WR_BG_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_WR_MASK_STALL_CNT */
#define MC_CH_RSCH_WR_MASK_STALL_CNT_VAL_S 0
#define MC_CH_RSCH_WR_MASK_STALL_CNT_VAL_M 0x1

/* MC_CH_RSCH_WR_MIN_SATURATED */
#define MC_CH_RSCH_WR_MIN_SATURATED_VAL_S 0
#define MC_CH_RSCH_WR_MIN_SATURATED_VAL_M 0xFF

/* MC_CH_RSCH_WR_MIN_STREAM_LENGTH */
#define MC_CH_RSCH_WR_MIN_STREAM_LENGTH_VAL_S 0
#define MC_CH_RSCH_WR_MIN_STREAM_LENGTH_VAL_M 0x3FF

/* MC_CH_RSCH_WR_OPEN_PAGE_SCORE */
#define MC_CH_RSCH_WR_OPEN_PAGE_SCORE_VAL_S 0
#define MC_CH_RSCH_WR_OPEN_PAGE_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_WR_QOS_ALMOST_FULL_TH */
#define MC_CH_RSCH_WR_QOS_ALMOST_FULL_TH_VAL_S 0
#define MC_CH_RSCH_WR_QOS_ALMOST_FULL_TH_VAL_M 0x3FF

/* MC_CH_RSCH_WR_SAT_HIGH_RPSB */
#define MC_CH_RSCH_WR_SAT_HIGH_RPSB_VAL_S 0
#define MC_CH_RSCH_WR_SAT_HIGH_RPSB_VAL_M 0xFF

/* MC_CH_RSCH_WR_SAT_HIGH_SCORE */
#define MC_CH_RSCH_WR_SAT_HIGH_SCORE_VAL_S 0
#define MC_CH_RSCH_WR_SAT_HIGH_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_WR_SAT_MED_RPSB */
#define MC_CH_RSCH_WR_SAT_MED_RPSB_VAL_S 0
#define MC_CH_RSCH_WR_SAT_MED_RPSB_VAL_M 0xFF

/* MC_CH_RSCH_WR_SAT_MED_SCORE */
#define MC_CH_RSCH_WR_SAT_MED_SCORE_VAL_S 0
#define MC_CH_RSCH_WR_SAT_MED_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_WR_SID_SCORE */
#define MC_CH_RSCH_WR_SID_SCORE_VAL_S 0
#define MC_CH_RSCH_WR_SID_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_WR_SWITCH_OCCUPANCY_LEVEL_QOS */
#define MC_CH_RSCH_WR_SWITCH_OCCUPANCY_LEVEL_QOS_VAL_S 0
#define MC_CH_RSCH_WR_SWITCH_OCCUPANCY_LEVEL_QOS_VAL_M 0xFF

/* MC_CH_RSCH_RD_QOS_AL_FULL */
#define MC_CH_RSCH_RD_QOS_AL_FULL_VAL_S 0
#define MC_CH_RSCH_RD_QOS_AL_FULL_VAL_M 0xF

/* MC_CH_RSCH_WR_QOS_AL_FULL */
#define MC_CH_RSCH_WR_QOS_AL_FULL_VAL_S 0
#define MC_CH_RSCH_WR_QOS_AL_FULL_VAL_M 0x3

/* MC_CH_RSCH_OCC_WATERMARKS */
#define MC_CH_RSCH_OCC_WATERMARKS_SWITCH_ON_EMPTY_S 0
#define MC_CH_RSCH_OCC_WATERMARKS_SWITCH_ON_EMPTY_M 0x1
#define MC_CH_RSCH_OCC_WATERMARKS_SWITCH_REQUEST_S 1
#define MC_CH_RSCH_OCC_WATERMARKS_SWITCH_REQUEST_M 0x2

/* MC_CH_RSCH_PFETCH_OPEN_SCORE */
#define MC_CH_RSCH_PFETCH_OPEN_SCORE_VAL_S 0
#define MC_CH_RSCH_PFETCH_OPEN_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_PFETCH_CLOSED_SCORE */
#define MC_CH_RSCH_PFETCH_CLOSED_SCORE_VAL_S 0
#define MC_CH_RSCH_PFETCH_CLOSED_SCORE_VAL_M 0xFF

/* MC_CH_RSCH_RWS_CNT */
#define MC_CH_RSCH_RWS_CNT_VAL_S 0
#define MC_CH_RSCH_RWS_CNT_VAL_M 0x7FF

/* MC_CH_RSCH_SEQ_REQ_CNT */
#define MC_CH_RSCH_SEQ_REQ_CNT_VAL_S 0
#define MC_CH_RSCH_SEQ_REQ_CNT_VAL_M 0x7FF

/* MC_CH_RSCH_LAT_CNT_DIV */
#define MC_CH_RSCH_LAT_CNT_DIV_VAL_S 0
#define MC_CH_RSCH_LAT_CNT_DIV_VAL_M 0xF

/* MC_CH_RSCH_PFT_CPL_SCORE_SEL */
#define MC_CH_RSCH_PFT_CPL_SCORE_SEL_VAL_S 0
#define MC_CH_RSCH_PFT_CPL_SCORE_SEL_VAL_M 0x1

/* MC_CH_RSCH_PREFETCH_NUM */
#define MC_CH_RSCH_PREFETCH_NUM_VAL_S 0
#define MC_CH_RSCH_PREFETCH_NUM_VAL_M 0xFF

/* MC_CH_SEQ_CATTRIP_THROT_EN */
#define MC_CH_SEQ_CATTRIP_THROT_EN_VAL_S 0
#define MC_CH_SEQ_CATTRIP_THROT_EN_VAL_M 0x1

/* MC_CH_SEQ_ENABLE */
#define MC_CH_SEQ_ENABLE_PC0_VAL_S 0
#define MC_CH_SEQ_ENABLE_PC0_VAL_M 0x1
#define MC_CH_SEQ_ENABLE_PC1_VAL_S 1
#define MC_CH_SEQ_ENABLE_PC1_VAL_M 0x2

/* MC_CH_SEQ_MONI_THROT_OFF */
#define MC_CH_SEQ_MONI_THROT_OFF_VAL_S 0
#define MC_CH_SEQ_MONI_THROT_OFF_VAL_M 0xFF

/* MC_CH_SEQ_MONI_THROT_ON */
#define MC_CH_SEQ_MONI_THROT_ON_VAL_S 0
#define MC_CH_SEQ_MONI_THROT_ON_VAL_M 0xFF

/* MC_CH_SEQ_MRS */
#define MC_CH_SEQ_MRS_CMD_NUM_S 0
#define MC_CH_SEQ_MRS_CMD_NUM_M 0xF
#define MC_CH_SEQ_MRS_CMD_VAL_S 4
#define MC_CH_SEQ_MRS_CMD_VAL_M 0xFF0

/* MC_CH_SEQ_MRS_STATE */
#define MC_CH_SEQ_MRS_STATE_VAL_S 0
#define MC_CH_SEQ_MRS_STATE_VAL_M 0x1

/* MC_CH_SEQ_MRS_COMMAND_TRIG */
#define MC_CH_SEQ_MRS_COMMAND_TRIG_VAL_S 0
#define MC_CH_SEQ_MRS_COMMAND_TRIG_VAL_M 0x1

/* MC_CH_SEQ_PWR */
#define MC_CH_SEQ_PWR_CMD_TYPE_S 0
#define MC_CH_SEQ_PWR_CMD_TYPE_M 0x3
#define MC_CH_SEQ_PWR_STATE_S 2
#define MC_CH_SEQ_PWR_STATE_M 0xC
#define MC_CH_SEQ_PWR_CK_DIS_SR_S 4
#define MC_CH_SEQ_PWR_CK_DIS_SR_M 0x10
#define MC_CH_SEQ_PWR_CK_DIS_PD_S 5
#define MC_CH_SEQ_PWR_CK_DIS_PD_M 0x20

/* MC_CH_SEQ_PWR_COMMAND_TRIG */
#define MC_CH_SEQ_PWR_COMMAND_TRIG_VAL_S 0
#define MC_CH_SEQ_PWR_COMMAND_TRIG_VAL_M 0x1

/* MC_CH_SEQ_REF_MODE */
#define MC_CH_SEQ_REF_MODE_VAL_S 0
#define MC_CH_SEQ_REF_MODE_VAL_M 0x3

/* MC_CH_SEQ_REFSB_BURST_NUM_HYSTERIC */
#define MC_CH_SEQ_REFSB_BURST_NUM_HYSTERIC_VAL_S 0
#define MC_CH_SEQ_REFSB_BURST_NUM_HYSTERIC_VAL_M 0xFF

/* MC_CH_SEQ_REFSB_BURST_NUM_URGENT */
#define MC_CH_SEQ_REFSB_BURST_NUM_URGENT_VAL_S 0
#define MC_CH_SEQ_REFSB_BURST_NUM_URGENT_VAL_M 0xFF

/* MC_CH_SEQ_REFSB_CNT_HYSTERIC_TH */
#define MC_CH_SEQ_REFSB_CNT_HYSTERIC_TH_VAL_S 0
#define MC_CH_SEQ_REFSB_CNT_HYSTERIC_TH_VAL_M 0xFF

/* MC_CH_SEQ_REFSB_CNT_URGENT_TH */
#define MC_CH_SEQ_REFSB_CNT_URGENT_TH_VAL_S 0
#define MC_CH_SEQ_REFSB_CNT_URGENT_TH_VAL_M 0xFF

/* MC_CH_SEQ_REFSB_GAP */
#define MC_CH_SEQ_REFSB_GAP_VAL_S 0
#define MC_CH_SEQ_REFSB_GAP_VAL_M 0xFF

/* MC_CH_SEQ_REFSB_PAGE_HIT_DISABLE */
#define MC_CH_SEQ_REFSB_PAGE_HIT_DISABLE_VAL_S 0
#define MC_CH_SEQ_REFSB_PAGE_HIT_DISABLE_VAL_M 0x1

/* MC_CH_SEQ_RESYNC_STATE */
#define MC_CH_SEQ_RESYNC_STATE_CH0_PS0_S 0
#define MC_CH_SEQ_RESYNC_STATE_CH0_PS0_M 0x1
#define MC_CH_SEQ_RESYNC_STATE_CH0_PS1_S 1
#define MC_CH_SEQ_RESYNC_STATE_CH0_PS1_M 0x2

/* MC_CH_SEQ_RESYNC_TRIGGER */
#define MC_CH_SEQ_RESYNC_TRIGGER_CH0_PS0_S 0
#define MC_CH_SEQ_RESYNC_TRIGGER_CH0_PS0_M 0x1
#define MC_CH_SEQ_RESYNC_TRIGGER_CH0_PS1_S 1
#define MC_CH_SEQ_RESYNC_TRIGGER_CH0_PS1_M 0x2

/* MC_CH_SEQ_SWITCH_HYSTERIC_CNT */
#define MC_CH_SEQ_SWITCH_HYSTERIC_CNT_VAL_S 0
#define MC_CH_SEQ_SWITCH_HYSTERIC_CNT_VAL_M 0xFFFFFFFF

/* MC_CH_SEQ_SWITCH_URGENT_CNT */
#define MC_CH_SEQ_SWITCH_URGENT_CNT_VAL_S 0
#define MC_CH_SEQ_SWITCH_URGENT_CNT_VAL_M 0xFFFFFFFF

/* MC_CH_SEQ_TCCD_L */
#define MC_CH_SEQ_TCCD_L_VAL_S 0
#define MC_CH_SEQ_TCCD_L_VAL_M 0xFF

/* MC_CH_SEQ_TCCD_R */
#define MC_CH_SEQ_TCCD_R_VAL_S 0
#define MC_CH_SEQ_TCCD_R_VAL_M 0xFF

/* MC_CH_SEQ_TCCD_S */
#define MC_CH_SEQ_TCCD_S_VAL_S 0
#define MC_CH_SEQ_TCCD_S_VAL_M 0xFF

/* MC_CH_SEQ_TCKPDE */
#define MC_CH_SEQ_TCKPDE_VAL_S 0
#define MC_CH_SEQ_TCKPDE_VAL_M 0x1F

/* MC_CH_SEQ_TCKSRE */
#define MC_CH_SEQ_TCKSRE_VAL_S 0
#define MC_CH_SEQ_TCKSRE_VAL_M 0x1F

/* MC_CH_SEQ_TCKSRX */
#define MC_CH_SEQ_TCKSRX_VAL_S 0
#define MC_CH_SEQ_TCKSRX_VAL_M 0x1F

/* MC_CH_SEQ_TFAW */
#define MC_CH_SEQ_TFAW_VAL_S 0
#define MC_CH_SEQ_TFAW_VAL_M 0xFF

/* MC_CH_SEQ_TMOD */
#define MC_CH_SEQ_TMOD_VAL_S 0
#define MC_CH_SEQ_TMOD_VAL_M 0xFF

/* MC_CH_SEQ_TRAS */
#define MC_CH_SEQ_TRAS_VAL_S 0
#define MC_CH_SEQ_TRAS_VAL_M 0xFF

/* MC_CH_SEQ_TRCD_RD */
#define MC_CH_SEQ_TRCD_RD_VAL_S 0
#define MC_CH_SEQ_TRCD_RD_VAL_M 0xFF

/* MC_CH_SEQ_TRCD_WR */
#define MC_CH_SEQ_TRCD_WR_VAL_S 0
#define MC_CH_SEQ_TRCD_WR_VAL_M 0xFF

/* MC_CH_SEQ_TREFI */
#define MC_CH_SEQ_TREFI_VAL_S 0
#define MC_CH_SEQ_TREFI_VAL_M 0xFFFF

/* MC_CH_SEQ_TREFI_TH */
#define MC_CH_SEQ_TREFI_TH_VAL_S 0
#define MC_CH_SEQ_TREFI_TH_VAL_M 0xFFFF

/* MC_CH_SEQ_TREFISB_ADJ */
#define MC_CH_SEQ_TREFISB_ADJ_VAL_S 0
#define MC_CH_SEQ_TREFISB_ADJ_VAL_M 0xFFFF

/* MC_CH_SEQ_TRFC */
#define MC_CH_SEQ_TRFC_VAL_S 0
#define MC_CH_SEQ_TRFC_VAL_M 0x1FF

/* MC_CH_SEQ_TRFCSB */
#define MC_CH_SEQ_TRFCSB_VAL_S 0
#define MC_CH_SEQ_TRFCSB_VAL_M 0xFF

/* MC_CH_SEQ_TRP */
#define MC_CH_SEQ_TRP_VAL_S 0
#define MC_CH_SEQ_TRP_VAL_M 0xFF

/* MC_CH_SEQ_TRRD_L */
#define MC_CH_SEQ_TRRD_L_VAL_S 0
#define MC_CH_SEQ_TRRD_L_VAL_M 0xFF

/* MC_CH_SEQ_TRRD_S */
#define MC_CH_SEQ_TRRD_S_VAL_S 0
#define MC_CH_SEQ_TRRD_S_VAL_M 0xFF

/* MC_CH_SEQ_TRREFD */
#define MC_CH_SEQ_TRREFD_VAL_S 0
#define MC_CH_SEQ_TRREFD_VAL_M 0xFF

/* MC_CH_SEQ_TRTP */
#define MC_CH_SEQ_TRTP_VAL_S 0
#define MC_CH_SEQ_TRTP_VAL_M 0xFF

/* MC_CH_SEQ_TRTW */
#define MC_CH_SEQ_TRTW_VAL_S 0
#define MC_CH_SEQ_TRTW_VAL_M 0xFF

/* MC_CH_SEQ_TWTP */
#define MC_CH_SEQ_TWTP_VAL_S 0
#define MC_CH_SEQ_TWTP_VAL_M 0xFF

/* MC_CH_SEQ_TWTR_L */
#define MC_CH_SEQ_TWTR_L_VAL_S 0
#define MC_CH_SEQ_TWTR_L_VAL_M 0xFF

/* MC_CH_SEQ_TWTR_S */
#define MC_CH_SEQ_TWTR_S_VAL_S 0
#define MC_CH_SEQ_TWTR_S_VAL_M 0xFF

/* MC_CH_SEQ_TWTRAP */
#define MC_CH_SEQ_TWTRAP_VAL_S 0
#define MC_CH_SEQ_TWTRAP_VAL_M 0xFF

/* MC_CH_SEQ_TXP */
#define MC_CH_SEQ_TXP_VAL_S 0
#define MC_CH_SEQ_TXP_VAL_M 0x1F

/* MC_CH_SEQ_TXS */
#define MC_CH_SEQ_TXS_VAL_S 0
#define MC_CH_SEQ_TXS_VAL_M 0x1FF

/* MC_CH_SEQ_CBQ_FIFO_FULL_TH */
#define MC_CH_SEQ_CBQ_FIFO_FULL_TH_VAL_S 0
#define MC_CH_SEQ_CBQ_FIFO_FULL_TH_VAL_M 0xFF

/* MC_CH_DFI_CAERR_CNT */
#define MC_CH_DFI_CAERR_CNT_VAL_S 0
#define MC_CH_DFI_CAERR_CNT_VAL_M 0xFFFFFFFF

/* MC_CH_DFI_CAERR_LAST_CMD_EVEN */
#define MC_CH_DFI_CAERR_LAST_CMD_EVEN_COL_S 0
#define MC_CH_DFI_CAERR_LAST_CMD_EVEN_COL_M 0x3FFFF
#define MC_CH_DFI_CAERR_LAST_CMD_EVEN_ROW_S 18
#define MC_CH_DFI_CAERR_LAST_CMD_EVEN_ROW_M 0xFFFC0000

/* MC_CH_DFI_CAERR_LAST_CMD_ODD */
#define MC_CH_DFI_CAERR_LAST_CMD_ODD_COL_S 0
#define MC_CH_DFI_CAERR_LAST_CMD_ODD_COL_M 0x3FFFF
#define MC_CH_DFI_CAERR_LAST_CMD_ODD_ROW_S 18
#define MC_CH_DFI_CAERR_LAST_CMD_ODD_ROW_M 0xFFFC0000

/* MC_CH_DFI_DERR_LAST_CMD */
#define MC_CH_DFI_DERR_LAST_CMD_COL_S 0
#define MC_CH_DFI_DERR_LAST_CMD_COL_M 0x3F
#define MC_CH_DFI_DERR_LAST_CMD_BG_S 6
#define MC_CH_DFI_DERR_LAST_CMD_BG_M 0xC0
#define MC_CH_DFI_DERR_LAST_CMD_BA_S 8
#define MC_CH_DFI_DERR_LAST_CMD_BA_M 0x300
#define MC_CH_DFI_DERR_LAST_CMD_SID_S 10
#define MC_CH_DFI_DERR_LAST_CMD_SID_M 0x400
#define MC_CH_DFI_DERR_LAST_CMD_DERR_S 11
#define MC_CH_DFI_DERR_LAST_CMD_DERR_M 0x7800

/* MC_CH_DFI_ECC_DERR_CNT */
#define MC_CH_DFI_ECC_DERR_CNT_VAL_S 0
#define MC_CH_DFI_ECC_DERR_CNT_VAL_M 0xFFFFFFFF

/* MC_CH_DFI_ECC_SERR_CNT */
#define MC_CH_DFI_ECC_SERR_CNT_VAL_S 0
#define MC_CH_DFI_ECC_SERR_CNT_VAL_M 0xFFFFFFFF

/* MC_CH_DFI_ECC_SEC_THLD */
#define MC_CH_DFI_ECC_SEC_THLD_VAL_S 0
#define MC_CH_DFI_ECC_SEC_THLD_VAL_M 0xFFFFFFFF

/* MC_CH_DFI_ERR_CTL */
#define MC_CH_DFI_ERR_CTL_CA_ERR_RESUME_S 0
#define MC_CH_DFI_ERR_CTL_CA_ERR_RESUME_M 0x1
#define MC_CH_DFI_ERR_CTL_WR_DQ_ERR_RESUME_S 1
#define MC_CH_DFI_ERR_CTL_WR_DQ_ERR_RESUME_M 0x2
#define MC_CH_DFI_ERR_CTL_RD_ERR_RESUME_S 2
#define MC_CH_DFI_ERR_CTL_RD_ERR_RESUME_M 0x4
#define MC_CH_DFI_ERR_CTL_RST_CA_ERR_CNT_S 3
#define MC_CH_DFI_ERR_CTL_RST_CA_ERR_CNT_M 0x8
#define MC_CH_DFI_ERR_CTL_RST_WR_DQ_ERR_CNT_S 4
#define MC_CH_DFI_ERR_CTL_RST_WR_DQ_ERR_CNT_M 0x10
#define MC_CH_DFI_ERR_CTL_RST_SERR_ERR_CNT_S 5
#define MC_CH_DFI_ERR_CTL_RST_SERR_ERR_CNT_M 0x20
#define MC_CH_DFI_ERR_CTL_RST_DERR_ERR_CNT_S 6
#define MC_CH_DFI_ERR_CTL_RST_DERR_ERR_CNT_M 0x40
#define MC_CH_DFI_ERR_CTL_RST_PAR_ERR_CNT_S 7
#define MC_CH_DFI_ERR_CTL_RST_PAR_ERR_CNT_M 0x80

/* MC_CH_DFI_ERR_INJ_EN */
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_ROW_S 0
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_ROW_M 0x1
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_COL_S 1
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_COL_M 0x2
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_WR_DATA_0_S 2
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_WR_DATA_0_M 0x4
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_WR_DATA_1_S 3
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_WR_DATA_1_M 0x8
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_WR_DATA_2_S 4
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_WR_DATA_2_M 0x10
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_WR_DATA_3_S 5
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_WR_DATA_3_M 0x20
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_RD_DATA_0_S 6
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_RD_DATA_0_M 0x40
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_RD_DATA_1_S 7
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_RD_DATA_1_M 0x80
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_RD_DATA_2_S 8
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_RD_DATA_2_M 0x100
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_RD_DATA_3_S 9
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_RD_DATA_3_M 0x200
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_ECC_0_S 10
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_ECC_0_M 0x400
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_ECC_1_S 11
#define MC_CH_DFI_ERR_INJ_EN_ENABLE_ECC_1_M 0x800

/* MC_CH_DFI_ERR_INJ_CTL */
#define MC_CH_DFI_ERR_INJ_CTL_R_S 0
#define MC_CH_DFI_ERR_INJ_CTL_R_M 0x3
#define MC_CH_DFI_ERR_INJ_CTL_C_S 2
#define MC_CH_DFI_ERR_INJ_CTL_C_M 0xC
#define MC_CH_DFI_ERR_INJ_CTL_RD_DW0_S 4
#define MC_CH_DFI_ERR_INJ_CTL_RD_DW0_M 0x30
#define MC_CH_DFI_ERR_INJ_CTL_RD_DW1_S 6
#define MC_CH_DFI_ERR_INJ_CTL_RD_DW1_M 0xC0
#define MC_CH_DFI_ERR_INJ_CTL_RD_DW2_S 8
#define MC_CH_DFI_ERR_INJ_CTL_RD_DW2_M 0x300
#define MC_CH_DFI_ERR_INJ_CTL_RD_DW3_S 10
#define MC_CH_DFI_ERR_INJ_CTL_RD_DW3_M 0xC00
#define MC_CH_DFI_ERR_INJ_CTL_WR_DW0_S 12
#define MC_CH_DFI_ERR_INJ_CTL_WR_DW0_M 0x3000
#define MC_CH_DFI_ERR_INJ_CTL_WR_DW1_S 14
#define MC_CH_DFI_ERR_INJ_CTL_WR_DW1_M 0xC000
#define MC_CH_DFI_ERR_INJ_CTL_WR_DW2_S 16
#define MC_CH_DFI_ERR_INJ_CTL_WR_DW2_M 0x30000
#define MC_CH_DFI_ERR_INJ_CTL_WR_DW3_S 18
#define MC_CH_DFI_ERR_INJ_CTL_WR_DW3_M 0xC0000
#define MC_CH_DFI_ERR_INJ_CTL_ECC_PC0_S 20
#define MC_CH_DFI_ERR_INJ_CTL_ECC_PC0_M 0x300000
#define MC_CH_DFI_ERR_INJ_CTL_ECC_PC1_S 22
#define MC_CH_DFI_ERR_INJ_CTL_ECC_PC1_M 0xC00000

/* MC_CH_DFI_MC_CHANNEL_CFG */
#define MC_CH_DFI_MC_CHANNEL_CFG_PC0_CBUS_CYC_S 0
#define MC_CH_DFI_MC_CHANNEL_CFG_PC0_CBUS_CYC_M 0x1
#define MC_CH_DFI_MC_CHANNEL_CFG_PC1_CBUS_CYC_S 1
#define MC_CH_DFI_MC_CHANNEL_CFG_PC1_CBUS_CYC_M 0x2
#define MC_CH_DFI_MC_CHANNEL_CFG_PWRDN_OVR_DFI_S 3
#define MC_CH_DFI_MC_CHANNEL_CFG_PWRDN_OVR_DFI_M 0x8
#define MC_CH_DFI_MC_CHANNEL_CFG_T_AXI_WR_CYC_S 4
#define MC_CH_DFI_MC_CHANNEL_CFG_T_AXI_WR_CYC_M 0x30
#define MC_CH_DFI_MC_CHANNEL_CFG_DFI_REFSB_EVEN_S 6
#define MC_CH_DFI_MC_CHANNEL_CFG_DFI_REFSB_EVEN_M 0x40

/* MC_CH_DFI_PAR_ERR_CNT */
#define MC_CH_DFI_PAR_ERR_CNT_VAL_S 0
#define MC_CH_DFI_PAR_ERR_CNT_VAL_M 0xFFFFFFFF

/* MC_CH_DFI_PHY_INIT_START */
#define MC_CH_DFI_PHY_INIT_START_VAL_S 0
#define MC_CH_DFI_PHY_INIT_START_VAL_M 0x1

/* MC_CH_DFI_PHY_CFG */
#define MC_CH_DFI_PHY_CFG_DFI_ECC_ENABLE_S 0
#define MC_CH_DFI_PHY_CFG_DFI_ECC_ENABLE_M 0x1
#define MC_CH_DFI_PHY_CFG_PARITY_RL_S 1
#define MC_CH_DFI_PHY_CFG_PARITY_RL_M 0x6
#define MC_CH_DFI_PHY_CFG_T_RD_DATA_EN_S 3
#define MC_CH_DFI_PHY_CFG_T_RD_DATA_EN_M 0x1F8
#define MC_CH_DFI_PHY_CFG_T_PHY_WR_DATA_S 9
#define MC_CH_DFI_PHY_CFG_T_PHY_WR_DATA_M 0xE00
#define MC_CH_DFI_PHY_CFG_T_PHY_WR_LAT_S 13
#define MC_CH_DFI_PHY_CFG_T_PHY_WR_LAT_M 0x1E000
#define MC_CH_DFI_PHY_CFG_RD_DQ_PARITY_ENABLE_S 17
#define MC_CH_DFI_PHY_CFG_RD_DQ_PARITY_ENABLE_M 0x20000
#define MC_CH_DFI_PHY_CFG_WR_DBI_ENABLE_S 18
#define MC_CH_DFI_PHY_CFG_WR_DBI_ENABLE_M 0x40000
#define MC_CH_DFI_PHY_CFG_RD_DBI_ENABLE_S 19
#define MC_CH_DFI_PHY_CFG_RD_DBI_ENABLE_M 0x80000
#define MC_CH_DFI_PHY_CFG_DFI_CR2DFI_FREQUENCY_S 21
#define MC_CH_DFI_PHY_CFG_DFI_CR2DFI_FREQUENCY_M 0x3E00000
#define MC_CH_DFI_PHY_CFG_PHY_UPDATE_DLY_T_S 26
#define MC_CH_DFI_PHY_CFG_PHY_UPDATE_DLY_T_M 0x7C000000
#define MC_CH_DFI_PHY_CFG_DFI_DM_ENABLE_S 31
#define MC_CH_DFI_PHY_CFG_DFI_DM_ENABLE_M 0x80000000

/* MC_CH_DFI_PHY_CFG_2 */
#define MC_CH_DFI_PHY_CFG_2_CTRLUPD_MAX_T_S 0
#define MC_CH_DFI_PHY_CFG_2_CTRLUPD_MAX_T_M 0x7F
#define MC_CH_DFI_PHY_CFG_2_CA_PARITY_ENABLE_S 7
#define MC_CH_DFI_PHY_CFG_2_CA_PARITY_ENABLE_M 0x80
#define MC_CH_DFI_PHY_CFG_2_WR_DQ_PARITY_ENABLE_S 8
#define MC_CH_DFI_PHY_CFG_2_WR_DQ_PARITY_ENABLE_M 0x100
#define MC_CH_DFI_PHY_CFG_2_DFI_ADDRESS_XOR_ENABLE_S 9
#define MC_CH_DFI_PHY_CFG_2_DFI_ADDRESS_XOR_ENABLE_M 0x200
#define MC_CH_DFI_PHY_CFG_2_DFI_MC_PHY_UPD_INTERVAL_S 10
#define MC_CH_DFI_PHY_CFG_2_DFI_MC_PHY_UPD_INTERVAL_M 0x3FFC00
#define MC_CH_DFI_PHY_CFG_2_DFI_MC_PHY_UPD_INT_EN_S 22
#define MC_CH_DFI_PHY_CFG_2_DFI_MC_PHY_UPD_INT_EN_M 0x400000
#define MC_CH_DFI_PHY_CFG_2_DFI_PHY_RESET_DONE_S 23
#define MC_CH_DFI_PHY_CFG_2_DFI_PHY_RESET_DONE_M 0x800000
#define MC_CH_DFI_PHY_CFG_2_DFI_LP_ENABLE_S 24
#define MC_CH_DFI_PHY_CFG_2_DFI_LP_ENABLE_M 0x1000000
#define MC_CH_DFI_PHY_CFG_2_DFI_LP_WAKEUP_S 25
#define MC_CH_DFI_PHY_CFG_2_DFI_LP_WAKEUP_M 0x1E000000
#define MC_CH_DFI_PHY_CFG_2_DFI_CATTRIP_ENABLE_S 29
#define MC_CH_DFI_PHY_CFG_2_DFI_CATTRIP_ENABLE_M 0x20000000
#define MC_CH_DFI_PHY_CFG_2_DFI_MCBIST_ECC_MODE_S 30
#define MC_CH_DFI_PHY_CFG_2_DFI_MCBIST_ECC_MODE_M 0x40000000

/* MC_CH_DFI_PHY_CFG_CH */
#define MC_CH_DFI_PHY_CFG_CH_TRIGGER_PHYUPDATE_S 0
#define MC_CH_DFI_PHY_CFG_CH_TRIGGER_PHYUPDATE_M 0x1
#define MC_CH_DFI_PHY_CFG_CH_DRAM_CLK_DISABLE_S 1
#define MC_CH_DFI_PHY_CFG_CH_DRAM_CLK_DISABLE_M 0x2
#define MC_CH_DFI_PHY_CFG_CH_PC_GRANT_SEL_VEC_S 2
#define MC_CH_DFI_PHY_CFG_CH_PC_GRANT_SEL_VEC_M 0x3FFC
#define MC_CH_DFI_PHY_CFG_CH_PC_GRANT_ENABLE_VEC_S 14
#define MC_CH_DFI_PHY_CFG_CH_PC_GRANT_ENABLE_VEC_M 0x3FFC000
#define MC_CH_DFI_PHY_CFG_CH_DFI_STALL_PC_S 26
#define MC_CH_DFI_PHY_CFG_CH_DFI_STALL_PC_M 0xC000000
#define MC_CH_DFI_PHY_CFG_CH_DFI_TRIGGER_CKE_FLIP_S 28
#define MC_CH_DFI_PHY_CFG_CH_DFI_TRIGGER_CKE_FLIP_M 0x10000000

/* MC_CH_DFI_PHY_CMD_CTL_CH */
#define MC_CH_DFI_PHY_CMD_CTL_CH_DFI_CMD_CTL_TRIGGER_S 0
#define MC_CH_DFI_PHY_CMD_CTL_CH_DFI_CMD_CTL_TRIGGER_M 0x1
#define MC_CH_DFI_PHY_CMD_CTL_CH_DFI_CMD_CTL_ODD_CYC_S 1
#define MC_CH_DFI_PHY_CMD_CTL_CH_DFI_CMD_CTL_ODD_CYC_M 0x2
#define MC_CH_DFI_PHY_CMD_CTL_CH_DFI_CMD_CTL_EVEN_CYC_S 2
#define MC_CH_DFI_PHY_CMD_CTL_CH_DFI_CMD_CTL_EVEN_CYC_M 0x4
#define MC_CH_DFI_PHY_CMD_CTL_CH_DFI_CMD_CTL_COL_VLD_S 3
#define MC_CH_DFI_PHY_CMD_CTL_CH_DFI_CMD_CTL_COL_VLD_M 0x8
#define MC_CH_DFI_PHY_CMD_CTL_CH_DFI_CMD_CTL_ROW_VLD_S 4
#define MC_CH_DFI_PHY_CMD_CTL_CH_DFI_CMD_CTL_ROW_VLD_M 0x10

/* MC_CH_DFI_PHY_CMD_DATA_EVEN_CH */
#define MC_CH_DFI_PHY_CMD_DATA_EVEN_CH_DFI_CMD_DATA_COL_S 0
#define MC_CH_DFI_PHY_CMD_DATA_EVEN_CH_DFI_CMD_DATA_COL_M 0x3FFFF
#define MC_CH_DFI_PHY_CMD_DATA_EVEN_CH_DFI_CMD_DATA_ROW_S 18
#define MC_CH_DFI_PHY_CMD_DATA_EVEN_CH_DFI_CMD_DATA_ROW_M 0xFFFC0000

/* MC_CH_DFI_PHY_CMD_DATA_ODD_CH */
#define MC_CH_DFI_PHY_CMD_DATA_ODD_CH_DFI_CMD_DATA_COL_S 0
#define MC_CH_DFI_PHY_CMD_DATA_ODD_CH_DFI_CMD_DATA_COL_M 0x3FFFF
#define MC_CH_DFI_PHY_CMD_DATA_ODD_CH_DFI_CMD_DATA_ROW_S 18
#define MC_CH_DFI_PHY_CMD_DATA_ODD_CH_DFI_CMD_DATA_ROW_M 0xFFFC0000

/* MC_CH_DFI_PHY_REMAP_CMD */
#define MC_CH_DFI_PHY_REMAP_CMD_ROW_RED_ADDR_S 0
#define MC_CH_DFI_PHY_REMAP_CMD_ROW_RED_ADDR_M 0xF
#define MC_CH_DFI_PHY_REMAP_CMD_COL_RED_ADDR_S 4
#define MC_CH_DFI_PHY_REMAP_CMD_COL_RED_ADDR_M 0xF0

/* MC_CH_DFI_PHY_REMAP_DQ_1 */
#define MC_CH_DFI_PHY_REMAP_DQ_1_RED_DATA_REMAP_S 0
#define MC_CH_DFI_PHY_REMAP_DQ_1_RED_DATA_REMAP_M 0xFFFFFFFF

/* MC_CH_DFI_PHY_REMAP_DQ_2 */
#define MC_CH_DFI_PHY_REMAP_DQ_2_RED_DATA_REMAP_S 0
#define MC_CH_DFI_PHY_REMAP_DQ_2_RED_DATA_REMAP_M 0xFFFFFFFF

/* MC_CH_DFI_PHY_INIT_COMPLETE */
#define MC_CH_DFI_PHY_INIT_COMPLETE_VAL_S 0
#define MC_CH_DFI_PHY_INIT_COMPLETE_VAL_M 0x1

/* MC_CH_DFI_PHY_STS */
#define MC_CH_DFI_PHY_STS_DFI_RD_PIPE_EMPTY_S 1
#define MC_CH_DFI_PHY_STS_DFI_RD_PIPE_EMPTY_M 0x6
#define MC_CH_DFI_PHY_STS_DFI_WR_PIPE_EMPTY_S 3
#define MC_CH_DFI_PHY_STS_DFI_WR_PIPE_EMPTY_M 0x18

/* MC_CH_DFI_RD_ERR_REP_ADDR */
#define MC_CH_DFI_RD_ERR_REP_ADDR_SID_S 0
#define MC_CH_DFI_RD_ERR_REP_ADDR_SID_M 0x1
#define MC_CH_DFI_RD_ERR_REP_ADDR_BG_S 1
#define MC_CH_DFI_RD_ERR_REP_ADDR_BG_M 0x6
#define MC_CH_DFI_RD_ERR_REP_ADDR_BA_S 3
#define MC_CH_DFI_RD_ERR_REP_ADDR_BA_M 0x18
#define MC_CH_DFI_RD_ERR_REP_ADDR_COL_S 5
#define MC_CH_DFI_RD_ERR_REP_ADDR_COL_M 0x7E0
#define MC_CH_DFI_RD_ERR_REP_ADDR_ROW_S 11
#define MC_CH_DFI_RD_ERR_REP_ADDR_ROW_M 0x3FFF800

/* MC_CH_DFI_RD_ERR_REP_DATA */
#define MC_CH_DFI_RD_ERR_REP_DATA_VAL_S 0
#define MC_CH_DFI_RD_ERR_REP_DATA_VAL_M 0xFFFFFFFF

/* MC_CH_DFI_RD_ERR_REP_DM */
#define MC_CH_DFI_RD_ERR_REP_DM_VAL_S 0
#define MC_CH_DFI_RD_ERR_REP_DM_VAL_M 0xFFFFFFFF

/* MC_CH_DFI_RD_ERR_REP_ERR */
#define MC_CH_DFI_RD_ERR_REP_ERR_PAR_ERR_S 0
#define MC_CH_DFI_RD_ERR_REP_ERR_PAR_ERR_M 0xFF
#define MC_CH_DFI_RD_ERR_REP_ERR_PAR_DATA_S 8
#define MC_CH_DFI_RD_ERR_REP_ERR_PAR_DATA_M 0xFF00
#define MC_CH_DFI_RD_ERR_REP_ERR_SERR_S 16
#define MC_CH_DFI_RD_ERR_REP_ERR_SERR_M 0xF0000
#define MC_CH_DFI_RD_ERR_REP_ERR_DERR_S 20
#define MC_CH_DFI_RD_ERR_REP_ERR_DERR_M 0xF00000

/* MC_CH_DFI_RD_ERR_REP_SYNDROME */
#define MC_CH_DFI_RD_ERR_REP_SYNDROME_VAL_S 0
#define MC_CH_DFI_RD_ERR_REP_SYNDROME_VAL_M 0xFFFFFFFF

/* MC_CH_DFI_STS_REGS */
#define MC_CH_DFI_STS_REGS_DFI_DBG_RD_CMD_CNT_0_S 0
#define MC_CH_DFI_STS_REGS_DFI_DBG_RD_CMD_CNT_0_M 0x3F
#define MC_CH_DFI_STS_REGS_DFI_DBG_RD_CMD_CNT_1_S 6
#define MC_CH_DFI_STS_REGS_DFI_DBG_RD_CMD_CNT_1_M 0xFC0
#define MC_CH_DFI_STS_REGS_DFI_DBG_WR_CMD_CNT_0_S 12
#define MC_CH_DFI_STS_REGS_DFI_DBG_WR_CMD_CNT_0_M 0xF000
#define MC_CH_DFI_STS_REGS_DFI_DBG_WR_CMD_CNT_1_S 16
#define MC_CH_DFI_STS_REGS_DFI_DBG_WR_CMD_CNT_1_M 0xF0000

/* MC_CH_DFI_WR_DERR_CNT */
#define MC_CH_DFI_WR_DERR_CNT_VAL_S 0
#define MC_CH_DFI_WR_DERR_CNT_VAL_M 0xFFFFFFFF

/* MC_CH_AUTO_PWR */
#define MC_CH_AUTO_PWR_PDE_TMO_S 0
#define MC_CH_AUTO_PWR_PDE_TMO_M 0xFFFF
#define MC_CH_AUTO_PWR_SRE_TMO_S 16
#define MC_CH_AUTO_PWR_SRE_TMO_M 0xFFFF0000

/* MC_CH_AUTO_PWR_EN */
#define MC_CH_AUTO_PWR_EN_PDE_S 0
#define MC_CH_AUTO_PWR_EN_PDE_M 0x1
#define MC_CH_AUTO_PWR_EN_SRE_S 1
#define MC_CH_AUTO_PWR_EN_SRE_M 0x2
#define MC_CH_AUTO_PWR_EN_PDX_S 2
#define MC_CH_AUTO_PWR_EN_PDX_M 0x4
#define MC_CH_AUTO_PWR_EN_SRX_S 3
#define MC_CH_AUTO_PWR_EN_SRX_M 0x8

/* MC_CH_BANKS_REMAIN_REFSB_SET */
#define MC_CH_BANKS_REMAIN_REFSB_SET_PC0_S 0
#define MC_CH_BANKS_REMAIN_REFSB_SET_PC0_M 0x1F
#define MC_CH_BANKS_REMAIN_REFSB_SET_PC1_S 8
#define MC_CH_BANKS_REMAIN_REFSB_SET_PC1_M 0x1F00

/* MC_CH_BIST_EN */
#define MC_CH_BIST_EN_VAL_S 0
#define MC_CH_BIST_EN_VAL_M 0x3

/* MC_CH_C_BUS_ENTRIES */
#define MC_CH_C_BUS_ENTRIES_PC0_S 0
#define MC_CH_C_BUS_ENTRIES_PC0_M 0xF
#define MC_CH_C_BUS_ENTRIES_PC1_S 4
#define MC_CH_C_BUS_ENTRIES_PC1_M 0xF0

/* MC_CH_DBG_CURRENT_STREAM_RD_NWR */
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH0_PC0_S 0
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH0_PC0_M 0x1
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH0_PC1_S 1
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH0_PC1_M 0x2
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH1_PC0_S 2
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH1_PC0_M 0x4
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH1_PC1_S 3
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH1_PC1_M 0x8
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH2_PC0_S 4
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH2_PC0_M 0x10
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH2_PC1_S 5
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH2_PC1_M 0x20
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH3_PC0_S 6
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH3_PC0_M 0x40
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH3_PC1_S 7
#define MC_CH_DBG_CURRENT_STREAM_RD_NWR_CH3_PC1_M 0x80

/* MC_CH_DBG_STS_TRACK_DFIM_LAST */
#define MC_CH_DBG_STS_TRACK_DFIM_LAST_VAL_S 0
#define MC_CH_DBG_STS_TRACK_DFIM_LAST_VAL_M 0x1

/* MC_CH_DBG_TRACK_EN */
#define MC_CH_DBG_TRACK_EN_VAL_S 0
#define MC_CH_DBG_TRACK_EN_VAL_M 0x1

/* MC_CH_ECC_CFG */
#define MC_CH_ECC_CFG_EN_S 0
#define MC_CH_ECC_CFG_EN_M 0x1

/* MC_CH_MC_EMPTY_INDICATIONS */
#define MC_CH_MC_EMPTY_INDICATIONS_AXIS_EMPTY_PC0_S 0
#define MC_CH_MC_EMPTY_INDICATIONS_AXIS_EMPTY_PC0_M 0x1
#define MC_CH_MC_EMPTY_INDICATIONS_AXIS_EMPTY_PC1_S 1
#define MC_CH_MC_EMPTY_INDICATIONS_AXIS_EMPTY_PC1_M 0x2
#define MC_CH_MC_EMPTY_INDICATIONS_MC_SEQ_IDLE_PC0_S 2
#define MC_CH_MC_EMPTY_INDICATIONS_MC_SEQ_IDLE_PC0_M 0x4
#define MC_CH_MC_EMPTY_INDICATIONS_MC_SEQ_IDLE_PC1_S 3
#define MC_CH_MC_EMPTY_INDICATIONS_MC_SEQ_IDLE_PC1_M 0x8
#define MC_CH_MC_EMPTY_INDICATIONS_RSCH_EMPTY_RD_PC0_S 4
#define MC_CH_MC_EMPTY_INDICATIONS_RSCH_EMPTY_RD_PC0_M 0x10
#define MC_CH_MC_EMPTY_INDICATIONS_RSCH_EMPTY_RD_PC1_S 5
#define MC_CH_MC_EMPTY_INDICATIONS_RSCH_EMPTY_RD_PC1_M 0x20
#define MC_CH_MC_EMPTY_INDICATIONS_CMD_GEN_EMPTY_PC0_S 6
#define MC_CH_MC_EMPTY_INDICATIONS_CMD_GEN_EMPTY_PC0_M 0x40
#define MC_CH_MC_EMPTY_INDICATIONS_CMD_GEN_EMPTY_PC1_S 7
#define MC_CH_MC_EMPTY_INDICATIONS_CMD_GEN_EMPTY_PC1_M 0x80
#define MC_CH_MC_EMPTY_INDICATIONS_DFI_RD_PIPE_EMPTY_PC0_S 8
#define MC_CH_MC_EMPTY_INDICATIONS_DFI_RD_PIPE_EMPTY_PC0_M 0x100
#define MC_CH_MC_EMPTY_INDICATIONS_DFI_RD_PIPE_EMPTY_PC1_S 9
#define MC_CH_MC_EMPTY_INDICATIONS_DFI_RD_PIPE_EMPTY_PC1_M 0x200
#define MC_CH_MC_EMPTY_INDICATIONS_DFI_WR_PIPE_EMPTY_PC0_S 10
#define MC_CH_MC_EMPTY_INDICATIONS_DFI_WR_PIPE_EMPTY_PC0_M 0x400
#define MC_CH_MC_EMPTY_INDICATIONS_DFI_WR_PIPE_EMPTY_PC1_S 11
#define MC_CH_MC_EMPTY_INDICATIONS_DFI_WR_PIPE_EMPTY_PC1_M 0x800
#define MC_CH_MC_EMPTY_INDICATIONS_RSCH_EMPTY_WR_PC0_S 12
#define MC_CH_MC_EMPTY_INDICATIONS_RSCH_EMPTY_WR_PC0_M 0x1000
#define MC_CH_MC_EMPTY_INDICATIONS_RSCH_EMPTY_WR_PC1_S 13
#define MC_CH_MC_EMPTY_INDICATIONS_RSCH_EMPTY_WR_PC1_M 0x2000

/* MC_CH_NUM_ENTRIES_VALID_FOR_ARB */
#define MC_CH_NUM_ENTRIES_VALID_FOR_ARB_WR_PC0_S 0
#define MC_CH_NUM_ENTRIES_VALID_FOR_ARB_WR_PC0_M 0xFF
#define MC_CH_NUM_ENTRIES_VALID_FOR_ARB_WR_PC1_S 8
#define MC_CH_NUM_ENTRIES_VALID_FOR_ARB_WR_PC1_M 0xFF00
#define MC_CH_NUM_ENTRIES_VALID_FOR_ARB_RD_PC0_S 16
#define MC_CH_NUM_ENTRIES_VALID_FOR_ARB_RD_PC0_M 0xFF0000
#define MC_CH_NUM_ENTRIES_VALID_FOR_ARB_RD_PC1_S 24
#define MC_CH_NUM_ENTRIES_VALID_FOR_ARB_RD_PC1_M 0xFF000000

/* MC_CH_NUM_NON_CLOSED_PAGES */
#define MC_CH_NUM_NON_CLOSED_PAGES_PC0_S 0
#define MC_CH_NUM_NON_CLOSED_PAGES_PC0_M 0xFF
#define MC_CH_NUM_NON_CLOSED_PAGES_PC1_S 8
#define MC_CH_NUM_NON_CLOSED_PAGES_PC1_M 0xFF00

/* MC_CH_NUM_PAGE_HIT */
#define MC_CH_NUM_PAGE_HIT_WR_PC0_S 0
#define MC_CH_NUM_PAGE_HIT_WR_PC0_M 0xFF
#define MC_CH_NUM_PAGE_HIT_WR_PC1_S 8
#define MC_CH_NUM_PAGE_HIT_WR_PC1_M 0xFF00
#define MC_CH_NUM_PAGE_HIT_RD_PC0_S 16
#define MC_CH_NUM_PAGE_HIT_RD_PC0_M 0xFF0000
#define MC_CH_NUM_PAGE_HIT_RD_PC1_S 24
#define MC_CH_NUM_PAGE_HIT_RD_PC1_M 0xFF000000

/* MC_CH_PAGE_TABLE_NON_CLOSED */
#define MC_CH_PAGE_TABLE_NON_CLOSED_VAL_S 0
#define MC_CH_PAGE_TABLE_NON_CLOSED_VAL_M 0xFFFFFFFF

/* MC_CH_RD_POOL_SAT_BANKS_HIGH */
#define MC_CH_RD_POOL_SAT_BANKS_HIGH_VAL_S 0
#define MC_CH_RD_POOL_SAT_BANKS_HIGH_VAL_M 0xFFFFFFFF

/* MC_CH_RD_POOL_SAT_BANKS_MED */
#define MC_CH_RD_POOL_SAT_BANKS_MED_VAL_S 0
#define MC_CH_RD_POOL_SAT_BANKS_MED_VAL_M 0xFFFFFFFF

/* MC_CH_TRACK_REG_SCHD_POOL */
#define MC_CH_TRACK_REG_SCHD_POOL_WR_SCHED_S 0
#define MC_CH_TRACK_REG_SCHD_POOL_WR_SCHED_M 0x1F
#define MC_CH_TRACK_REG_SCHD_POOL_WR_NUM_SAME_S 8
#define MC_CH_TRACK_REG_SCHD_POOL_WR_NUM_SAME_M 0x7F00
#define MC_CH_TRACK_REG_SCHD_POOL_WR_RMW_S 15
#define MC_CH_TRACK_REG_SCHD_POOL_WR_RMW_M 0x8000
#define MC_CH_TRACK_REG_SCHD_POOL_RD_SCHED_S 16
#define MC_CH_TRACK_REG_SCHD_POOL_RD_SCHED_M 0x1F0000
#define MC_CH_TRACK_REG_SCHD_POOL_RD_NUM_SAME_S 24
#define MC_CH_TRACK_REG_SCHD_POOL_RD_NUM_SAME_M 0x7F000000
#define MC_CH_TRACK_REG_SCHD_POOL_RD_RMW_S 31
#define MC_CH_TRACK_REG_SCHD_POOL_RD_RMW_M 0x80000000

/* MC_CH_TRACK_SEQ */
#define MC_CH_TRACK_SEQ_LAST_TRAN_COMMAND_PC0_S 0
#define MC_CH_TRACK_SEQ_LAST_TRAN_COMMAND_PC0_M 0x1
#define MC_CH_TRACK_SEQ_ISSUED_ACT_PC0_S 1
#define MC_CH_TRACK_SEQ_ISSUED_ACT_PC0_M 0x2
#define MC_CH_TRACK_SEQ_IDENTIFIED_PAGE_HIT_PC0_S 2
#define MC_CH_TRACK_SEQ_IDENTIFIED_PAGE_HIT_PC0_M 0x4
#define MC_CH_TRACK_SEQ_LAST_TRAN_COMMAND_PC1_S 8
#define MC_CH_TRACK_SEQ_LAST_TRAN_COMMAND_PC1_M 0x100
#define MC_CH_TRACK_SEQ_ISSUED_ACT_PC1_S 9
#define MC_CH_TRACK_SEQ_ISSUED_ACT_PC1_M 0x200
#define MC_CH_TRACK_SEQ_IDENTIFIED_PAGE_HIT_PC1_S 10
#define MC_CH_TRACK_SEQ_IDENTIFIED_PAGE_HIT_PC1_M 0x400

/* MC_CH_TRACK_TRAN_MASKED_HC */
#define MC_CH_TRACK_TRAN_MASKED_HC_WR_PC0_S 0
#define MC_CH_TRACK_TRAN_MASKED_HC_WR_PC0_M 0x1
#define MC_CH_TRACK_TRAN_MASKED_HC_WR_PC1_S 1
#define MC_CH_TRACK_TRAN_MASKED_HC_WR_PC1_M 0x2
#define MC_CH_TRACK_TRAN_MASKED_HC_RD_PC0_S 2
#define MC_CH_TRACK_TRAN_MASKED_HC_RD_PC0_M 0x4
#define MC_CH_TRACK_TRAN_MASKED_HC_RD_PC1_S 3
#define MC_CH_TRACK_TRAN_MASKED_HC_RD_PC1_M 0x8

/* MC_CH_TRAN_WON_ARB_SCORE */
#define MC_CH_TRAN_WON_ARB_SCORE_PC0_S 0
#define MC_CH_TRAN_WON_ARB_SCORE_PC0_M 0x7FF
#define MC_CH_TRAN_WON_ARB_SCORE_PC1_S 16
#define MC_CH_TRAN_WON_ARB_SCORE_PC1_M 0x7FF0000

/* MC_CH_WR_POOL_SAT_BANKS_HIGH */
#define MC_CH_WR_POOL_SAT_BANKS_HIGH_VAL_S 0
#define MC_CH_WR_POOL_SAT_BANKS_HIGH_VAL_M 0xFFFFFFFF

/* MC_CH_WR_POOL_SAT_BANKS_MED */
#define MC_CH_WR_POOL_SAT_BANKS_MED_VAL_S 0
#define MC_CH_WR_POOL_SAT_BANKS_MED_VAL_M 0xFFFFFFFF

/* MC_CH_SCRB_ENABLE */
#define MC_CH_SCRB_ENABLE_VAL_S 0
#define MC_CH_SCRB_ENABLE_VAL_M 0x1

/* MC_CH_SCRB_RELOAD */
#define MC_CH_SCRB_RELOAD_VAL_S 0
#define MC_CH_SCRB_RELOAD_VAL_M 0x1

/* MC_CH_SCRB_START_ADDR */
#define MC_CH_SCRB_START_ADDR_VAL_S 0
#define MC_CH_SCRB_START_ADDR_VAL_M 0xFFFFFFFF

/* MC_CH_SCRB_END_ADDR */
#define MC_CH_SCRB_END_ADDR_VAL_S 0
#define MC_CH_SCRB_END_ADDR_VAL_M 0xFFFFFFFF

/* MC_CH_SCRB_CONFIG */
#define MC_CH_SCRB_CONFIG_AUTORESTART_S 0
#define MC_CH_SCRB_CONFIG_AUTORESTART_M 0x1
#define MC_CH_SCRB_CONFIG_STOP_ON_ERR_S 1
#define MC_CH_SCRB_CONFIG_STOP_ON_ERR_M 0x2
#define MC_CH_SCRB_CONFIG_NO_WRITEBACK_S 2
#define MC_CH_SCRB_CONFIG_NO_WRITEBACK_M 0x4

/* MC_CH_SCRB_CNTR */
#define MC_CH_SCRB_CNTR_VAL_S 0
#define MC_CH_SCRB_CNTR_VAL_M 0xFFFFFFFF

/* MC_CH_SCRB_SERR_CNTR */
#define MC_CH_SCRB_SERR_CNTR_VAL_S 0
#define MC_CH_SCRB_SERR_CNTR_VAL_M 0xFFFFFFFF

/* MC_CH_SCRB_SERR_CNTR_RST */
#define MC_CH_SCRB_SERR_CNTR_RST_VAL_S 0
#define MC_CH_SCRB_SERR_CNTR_RST_VAL_M 0x1

/* MC_CH_SCRB_ARUSER */
#define MC_CH_SCRB_ARUSER_VAL_S 0
#define MC_CH_SCRB_ARUSER_VAL_M 0xFFFFFFFF

/* MC_CH_SCRB_AWUSER */
#define MC_CH_SCRB_AWUSER_VAL_S 0
#define MC_CH_SCRB_AWUSER_VAL_M 0xFFFFFFFF

/* MC_CH_SCRB_WUSER */
#define MC_CH_SCRB_WUSER_VAL_S 0
#define MC_CH_SCRB_WUSER_VAL_M 0xFFFFFFFF

#endif /* ASIC_REG_MC_CH_MASKS_H_ */
