/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_MME_CTRL_LO_MASKS_H_
#define ASIC_REG_MME_CTRL_LO_MASKS_H_

/*
 *****************************************
 *   MME_CTRL_LO
 *   (Prototype: MME_CTRL_LO)
 *****************************************
 */

/* MME_CTRL_LO_ARCH_STATUS_MASTER */
#define MME_CTRL_LO_ARCH_STATUS_MASTER_AGU_IN_S 0
#define MME_CTRL_LO_ARCH_STATUS_MASTER_AGU_IN_M 0xF
#define MME_CTRL_LO_ARCH_STATUS_MASTER_EU_S 4
#define MME_CTRL_LO_ARCH_STATUS_MASTER_EU_M 0x10
#define MME_CTRL_LO_ARCH_STATUS_MASTER_AP_S 5
#define MME_CTRL_LO_ARCH_STATUS_MASTER_AP_M 0x20
#define MME_CTRL_LO_ARCH_STATUS_MASTER_AGU_COUT_S 6
#define MME_CTRL_LO_ARCH_STATUS_MASTER_AGU_COUT_M 0x40
#define MME_CTRL_LO_ARCH_STATUS_MASTER_AGU_DMA_O_S 7
#define MME_CTRL_LO_ARCH_STATUS_MASTER_AGU_DMA_O_M 0x80
#define MME_CTRL_LO_ARCH_STATUS_MASTER_SB_IN_EMPTY_S 8
#define MME_CTRL_LO_ARCH_STATUS_MASTER_SB_IN_EMPTY_M 0xF00
#define MME_CTRL_LO_ARCH_STATUS_MASTER_AGU_COUT_SM_IDLE_S 12
#define MME_CTRL_LO_ARCH_STATUS_MASTER_AGU_COUT_SM_IDLE_M 0x1000
#define MME_CTRL_LO_ARCH_STATUS_MASTER_AGU_DMA_O_SM_IDLE_S 13
#define MME_CTRL_LO_ARCH_STATUS_MASTER_AGU_DMA_O_SM_IDLE_M 0x2000
#define MME_CTRL_LO_ARCH_STATUS_MASTER_WBC_AXI_IDLE_S 14
#define MME_CTRL_LO_ARCH_STATUS_MASTER_WBC_AXI_IDLE_M 0x4000
#define MME_CTRL_LO_ARCH_STATUS_MASTER_SB_IN_AXI_IDLE_S 16
#define MME_CTRL_LO_ARCH_STATUS_MASTER_SB_IN_AXI_IDLE_M 0xF0000
#define MME_CTRL_LO_ARCH_STATUS_MASTER_ACCUM_FREE_S 20
#define MME_CTRL_LO_ARCH_STATUS_MASTER_ACCUM_FREE_M 0x700000
#define MME_CTRL_LO_ARCH_STATUS_MASTER_QM_IDLE_S 30
#define MME_CTRL_LO_ARCH_STATUS_MASTER_QM_IDLE_M 0x40000000
#define MME_CTRL_LO_ARCH_STATUS_MASTER_QM_RDY_S 31
#define MME_CTRL_LO_ARCH_STATUS_MASTER_QM_RDY_M 0x80000000

/* MME_CTRL_LO_ARCH_STATUS_SLAVE */
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_AGU_IN_S 0
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_AGU_IN_M 0xF
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_EU_S 4
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_EU_M 0x10
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_AP_S 5
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_AP_M 0x20
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_AGU_COUT_S 6
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_AGU_COUT_M 0x40
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_AGU_DMA_O_S 7
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_AGU_DMA_O_M 0x80
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_SB_IN_EMPTY_S 8
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_SB_IN_EMPTY_M 0xF00
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_AGU_COUT_SM_IDLE_S 12
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_AGU_COUT_SM_IDLE_M 0x1000
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_AGU_DMA_O_SM_IDLE_S 13
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_AGU_DMA_O_SM_IDLE_M 0x2000
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_WBC_AXI_IDLE_S 14
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_WBC_AXI_IDLE_M 0x4000
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_SB_IN_AXI_IDLE_S 16
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_SB_IN_AXI_IDLE_M 0xF0000
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_ACCUM_FREE_S 20
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_ACCUM_FREE_M 0x700000
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_QM_IDLE_S 30
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_QM_IDLE_M 0x40000000
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_QM_RDY_S 31
#define MME_CTRL_LO_ARCH_STATUS_SLAVE_QM_RDY_M 0x80000000

/* MME_CTRL_LO_ARCH_A_SS */
#define MME_CTRL_LO_ARCH_A_SS_MINUS_1_S 0
#define MME_CTRL_LO_ARCH_A_SS_MINUS_1_M 0xFFFFFFFF

/* MME_CTRL_LO_ARCH_B_SS */
#define MME_CTRL_LO_ARCH_B_SS_MINUS_1_S 0
#define MME_CTRL_LO_ARCH_B_SS_MINUS_1_M 0xFFFFFFFF

/* MME_CTRL_LO_ARCH_COUT_SS */
#define MME_CTRL_LO_ARCH_COUT_SS_MINUS_1_S 0
#define MME_CTRL_LO_ARCH_COUT_SS_MINUS_1_M 0xFFFFFFFF

/* MME_CTRL_LO_CMD */
#define MME_CTRL_LO_CMD_AGU_IN_S 0
#define MME_CTRL_LO_CMD_AGU_IN_M 0xF
#define MME_CTRL_LO_CMD_EU_S 4
#define MME_CTRL_LO_CMD_EU_M 0x10
#define MME_CTRL_LO_CMD_AP_S 5
#define MME_CTRL_LO_CMD_AP_M 0x20
#define MME_CTRL_LO_CMD_AGU_COUT_S 6
#define MME_CTRL_LO_CMD_AGU_COUT_M 0x40
#define MME_CTRL_LO_CMD_AGU_DMA_O_S 7
#define MME_CTRL_LO_CMD_AGU_DMA_O_M 0x80
#define MME_CTRL_LO_CMD_COPY_AND_INC_S 8
#define MME_CTRL_LO_CMD_COPY_AND_INC_M 0x100
#define MME_CTRL_LO_CMD_DESC_SEL_S 9
#define MME_CTRL_LO_CMD_DESC_SEL_M 0x600
#define MME_CTRL_LO_CMD_MASK_IDLE_IND_S 11
#define MME_CTRL_LO_CMD_MASK_IDLE_IND_M 0x800
#define MME_CTRL_LO_CMD_NULL_DESC_S 12
#define MME_CTRL_LO_CMD_NULL_DESC_M 0x1000
#define MME_CTRL_LO_CMD_DMA_MODE_S 13
#define MME_CTRL_LO_CMD_DMA_MODE_M 0x2000
#define MME_CTRL_LO_CMD_NULL_DMA_DESC_S 14
#define MME_CTRL_LO_CMD_NULL_DMA_DESC_M 0x4000

/* MME_CTRL_LO_QM_STALL */
#define MME_CTRL_LO_QM_STALL_V_S 0
#define MME_CTRL_LO_QM_STALL_V_M 0x1

/* MME_CTRL_LO_LOG_SHADOW_LO */
#define MME_CTRL_LO_LOG_SHADOW_LO_MASK_0_S 0
#define MME_CTRL_LO_LOG_SHADOW_LO_MASK_0_M 0xFFFF
#define MME_CTRL_LO_LOG_SHADOW_LO_MASK_1_S 16
#define MME_CTRL_LO_LOG_SHADOW_LO_MASK_1_M 0xFFFF0000

/* MME_CTRL_LO_LOG_SHADOW_HI */
#define MME_CTRL_LO_LOG_SHADOW_HI_MASK_2_S 0
#define MME_CTRL_LO_LOG_SHADOW_HI_MASK_2_M 0xFFFF
#define MME_CTRL_LO_LOG_SHADOW_HI_MASK_3_S 16
#define MME_CTRL_LO_LOG_SHADOW_HI_MASK_3_M 0xFFFF0000

/* MME_CTRL_LO_SYNC_OBJECT_FIFO_TH */
#define MME_CTRL_LO_SYNC_OBJECT_FIFO_TH_V_S 0
#define MME_CTRL_LO_SYNC_OBJECT_FIFO_TH_V_M 0x1F

/* MME_CTRL_LO_EUS_ROLLUP_DLY_DW0 */
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_S 0
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_M 0xF
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE0_S 4
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE0_M 0xF0
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE1_S 8
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE1_M 0xF00
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE2_S 12
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE2_M 0xF000
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE3_S 16
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE3_M 0xF0000
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE4_S 20
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE4_M 0xF00000
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE5_S 24
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE5_M 0x7000000
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE6_S 27
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE6_M 0x38000000

/* MME_CTRL_LO_EUS_ROLLUP_DLY_DW1 */
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW1_FP_PE7_S 0
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW1_FP_PE7_M 0x7
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW1_FP_PE_HI_S 3
#define MME_CTRL_LO_EUS_ROLLUP_DLY_DW1_FP_PE_HI_M 0x38

/* MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F16 */
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F16_DLY_S 0
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F16_DLY_M 0xFFF
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F16_EN_S 31
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F16_EN_M 0x80000000

/* MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F8 */
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F8_DLY_S 0
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F8_DLY_M 0xFFF
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F8_EN_S 31
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F8_EN_M 0x80000000

/* MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32 */
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32_DLY_S 0
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32_DLY_M 0xFFF
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32_EN_S 31
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32_EN_M 0x80000000

/* MME_CTRL_LO_EUS_ROLLUP_CD_PROT_TF32 */
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_TF32_DLY_S 0
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_TF32_DLY_M 0xFFF
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_TF32_EN_S 31
#define MME_CTRL_LO_EUS_ROLLUP_CD_PROT_TF32_EN_M 0x80000000

/* MME_CTRL_LO_PCU_RL_DESC0 */
#define MME_CTRL_LO_PCU_RL_DESC0_RL_RST_TOKEN_S 0
#define MME_CTRL_LO_PCU_RL_DESC0_RL_RST_TOKEN_M 0xFFFF
#define MME_CTRL_LO_PCU_RL_DESC0_RL_TIMEOUT_S 16
#define MME_CTRL_LO_PCU_RL_DESC0_RL_TIMEOUT_M 0xFF0000
#define MME_CTRL_LO_PCU_RL_DESC0_RL_DUMMY2REAL_PERIOD_S 24
#define MME_CTRL_LO_PCU_RL_DESC0_RL_DUMMY2REAL_PERIOD_M 0xFF000000

/* MME_CTRL_LO_PCU_RL_TOKEN_UPDATE */
#define MME_CTRL_LO_PCU_RL_TOKEN_UPDATE_INC_VAL_S 0
#define MME_CTRL_LO_PCU_RL_TOKEN_UPDATE_INC_VAL_M 0xFFFF
#define MME_CTRL_LO_PCU_RL_TOKEN_UPDATE_DEC_VAL_S 16
#define MME_CTRL_LO_PCU_RL_TOKEN_UPDATE_DEC_VAL_M 0xFFFF0000

/* MME_CTRL_LO_PCU_RL_TH */
#define MME_CTRL_LO_PCU_RL_TH_POOL_TH_DEC_S 0
#define MME_CTRL_LO_PCU_RL_TH_POOL_TH_DEC_M 0xFFFF
#define MME_CTRL_LO_PCU_RL_TH_DUMMY_REAL_DIFF_TH_S 16
#define MME_CTRL_LO_PCU_RL_TH_DUMMY_REAL_DIFF_TH_M 0xFFFF0000

/* MME_CTRL_LO_PCU_RL_MIN */
#define MME_CTRL_LO_PCU_RL_MIN_AVG_MIN_TO_FORCE_DUMMY_S 0
#define MME_CTRL_LO_PCU_RL_MIN_AVG_MIN_TO_FORCE_DUMMY_M 0xFFFF
#define MME_CTRL_LO_PCU_RL_MIN_TOKEN_MIN_VAL_S 16
#define MME_CTRL_LO_PCU_RL_MIN_TOKEN_MIN_VAL_M 0xFFFF0000

/* MME_CTRL_LO_PCU_RL_CTRL_EN */
#define MME_CTRL_LO_PCU_RL_CTRL_EN_PCU_DISABLE_S 0
#define MME_CTRL_LO_PCU_RL_CTRL_EN_PCU_DISABLE_M 0x1
#define MME_CTRL_LO_PCU_RL_CTRL_EN_MIN_VAL_PROT_EN_S 1
#define MME_CTRL_LO_PCU_RL_CTRL_EN_MIN_VAL_PROT_EN_M 0x2

/* MME_CTRL_LO_PCU_RL_HISTORY_LOG_SIZE */
#define MME_CTRL_LO_PCU_RL_HISTORY_LOG_SIZE_ALL_MACS_S 0
#define MME_CTRL_LO_PCU_RL_HISTORY_LOG_SIZE_ALL_MACS_M 0x7
#define MME_CTRL_LO_PCU_RL_HISTORY_LOG_SIZE_REAL_MACS_S 3
#define MME_CTRL_LO_PCU_RL_HISTORY_LOG_SIZE_REAL_MACS_M 0x18

/* MME_CTRL_LO_PCU_DUMMY_A_BF16 */
#define MME_CTRL_LO_PCU_DUMMY_A_BF16_ODD_S 0
#define MME_CTRL_LO_PCU_DUMMY_A_BF16_ODD_M 0xFFFF
#define MME_CTRL_LO_PCU_DUMMY_A_BF16_EVEN_S 16
#define MME_CTRL_LO_PCU_DUMMY_A_BF16_EVEN_M 0xFFFF0000

/* MME_CTRL_LO_PCU_DUMMY_B_BF16 */
#define MME_CTRL_LO_PCU_DUMMY_B_BF16_ODD_S 0
#define MME_CTRL_LO_PCU_DUMMY_B_BF16_ODD_M 0xFFFF
#define MME_CTRL_LO_PCU_DUMMY_B_BF16_EVEN_S 16
#define MME_CTRL_LO_PCU_DUMMY_B_BF16_EVEN_M 0xFFFF0000

/* MME_CTRL_LO_PCU_DUMMY_A_FP16 */
#define MME_CTRL_LO_PCU_DUMMY_A_FP16_ODD_S 0
#define MME_CTRL_LO_PCU_DUMMY_A_FP16_ODD_M 0xFFFF
#define MME_CTRL_LO_PCU_DUMMY_A_FP16_EVEN_S 16
#define MME_CTRL_LO_PCU_DUMMY_A_FP16_EVEN_M 0xFFFF0000

/* MME_CTRL_LO_PCU_DUMMY_B_FP16 */
#define MME_CTRL_LO_PCU_DUMMY_B_FP16_ODD_S 0
#define MME_CTRL_LO_PCU_DUMMY_B_FP16_ODD_M 0xFFFF
#define MME_CTRL_LO_PCU_DUMMY_B_FP16_EVEN_S 16
#define MME_CTRL_LO_PCU_DUMMY_B_FP16_EVEN_M 0xFFFF0000

/* MME_CTRL_LO_PCU_DUMMY_F8 */
#define MME_CTRL_LO_PCU_DUMMY_F8_A_VAL_ODD_S 0
#define MME_CTRL_LO_PCU_DUMMY_F8_A_VAL_ODD_M 0xFF
#define MME_CTRL_LO_PCU_DUMMY_F8_A_VAL_EVEN_S 8
#define MME_CTRL_LO_PCU_DUMMY_F8_A_VAL_EVEN_M 0xFF00
#define MME_CTRL_LO_PCU_DUMMY_F8_B_VAL_ODD_S 16
#define MME_CTRL_LO_PCU_DUMMY_F8_B_VAL_ODD_M 0xFF0000
#define MME_CTRL_LO_PCU_DUMMY_F8_B_VAL_EVEN_S 24
#define MME_CTRL_LO_PCU_DUMMY_F8_B_VAL_EVEN_M 0xFF000000

/* MME_CTRL_LO_PCU_DUMMY_A_FP32_ODD */
#define MME_CTRL_LO_PCU_DUMMY_A_FP32_ODD_V_S 0
#define MME_CTRL_LO_PCU_DUMMY_A_FP32_ODD_V_M 0xFFFFFFFF

/* MME_CTRL_LO_PCU_DUMMY_A_FP32_EVEN */
#define MME_CTRL_LO_PCU_DUMMY_A_FP32_EVEN_V_S 0
#define MME_CTRL_LO_PCU_DUMMY_A_FP32_EVEN_V_M 0xFFFFFFFF

/* MME_CTRL_LO_PCU_DUMMY_B_FP32_ODD */
#define MME_CTRL_LO_PCU_DUMMY_B_FP32_ODD_V_S 0
#define MME_CTRL_LO_PCU_DUMMY_B_FP32_ODD_V_M 0xFFFFFFFF

/* MME_CTRL_LO_PCU_DUMMY_B_FP32_EVEN */
#define MME_CTRL_LO_PCU_DUMMY_B_FP32_EVEN_V_S 0
#define MME_CTRL_LO_PCU_DUMMY_B_FP32_EVEN_V_M 0xFFFFFFFF

/* MME_CTRL_LO_PCU_DUMMY_A_TF32_ODD */
#define MME_CTRL_LO_PCU_DUMMY_A_TF32_ODD_V_S 0
#define MME_CTRL_LO_PCU_DUMMY_A_TF32_ODD_V_M 0xFFFFFFFF

/* MME_CTRL_LO_PCU_DUMMY_A_TF32_EVEN */
#define MME_CTRL_LO_PCU_DUMMY_A_TF32_EVEN_V_S 0
#define MME_CTRL_LO_PCU_DUMMY_A_TF32_EVEN_V_M 0xFFFFFFFF

/* MME_CTRL_LO_PCU_DUMMY_B_TF32_ODD */
#define MME_CTRL_LO_PCU_DUMMY_B_TF32_ODD_V_S 0
#define MME_CTRL_LO_PCU_DUMMY_B_TF32_ODD_V_M 0xFFFFFFFF

/* MME_CTRL_LO_PCU_DUMMY_B_TF32_EVEN */
#define MME_CTRL_LO_PCU_DUMMY_B_TF32_EVEN_V_S 0
#define MME_CTRL_LO_PCU_DUMMY_B_TF32_EVEN_V_M 0xFFFFFFFF

/* MME_CTRL_LO_EU */
#define MME_CTRL_LO_EU_POWER_SAVE_DISABLE_S 0
#define MME_CTRL_LO_EU_POWER_SAVE_DISABLE_M 0x1
#define MME_CTRL_LO_EU_FP_PYR_CLOSE_CGATE_EN_S 1
#define MME_CTRL_LO_EU_FP_PYR_CLOSE_CGATE_EN_M 0x2
#define MME_CTRL_LO_EU_FP_CLS_CLOSE_CGATE_EN_S 2
#define MME_CTRL_LO_EU_FP_CLS_CLOSE_CGATE_EN_M 0x4
#define MME_CTRL_LO_EU_FP_CLOSE_CGATE_DLY_S 8
#define MME_CTRL_LO_EU_FP_CLOSE_CGATE_DLY_M 0xFFF00
#define MME_CTRL_LO_EU_FP_CLOSE_CGATE_ON_DESC_S 20
#define MME_CTRL_LO_EU_FP_CLOSE_CGATE_ON_DESC_M 0x100000
#define MME_CTRL_LO_EU_FP_ROLLUP_CDC_STALL_DIS_S 21
#define MME_CTRL_LO_EU_FP_ROLLUP_CDC_STALL_DIS_M 0x200000

/* MME_CTRL_LO_COUT_AGU_SM_INFLIGHT_CNTR */
#define MME_CTRL_LO_COUT_AGU_SM_INFLIGHT_CNTR_V_S 0
#define MME_CTRL_LO_COUT_AGU_SM_INFLIGHT_CNTR_V_M 0xFFFFFFFF

/* MME_CTRL_LO_COUT_AGU_SM_TOTAL_CNTR */
#define MME_CTRL_LO_COUT_AGU_SM_TOTAL_CNTR_V_S 0
#define MME_CTRL_LO_COUT_AGU_SM_TOTAL_CNTR_V_M 0xFFFFFFFF

/* MME_CTRL_LO_DMA_AGU_SM_INFLIGHT_CNTR */
#define MME_CTRL_LO_DMA_AGU_SM_INFLIGHT_CNTR_V_S 0
#define MME_CTRL_LO_DMA_AGU_SM_INFLIGHT_CNTR_V_M 0xFFFFFFFF

/* MME_CTRL_LO_DMA_AGU_SM_TOTAL_CNTR */
#define MME_CTRL_LO_DMA_AGU_SM_TOTAL_CNTR_V_S 0
#define MME_CTRL_LO_DMA_AGU_SM_TOTAL_CNTR_V_M 0xFFFFFFFF

/* MME_CTRL_LO_PCU_RL_SAT_SEC */
#define MME_CTRL_LO_PCU_RL_SAT_SEC_VAL_S 0
#define MME_CTRL_LO_PCU_RL_SAT_SEC_VAL_M 0xFFFFF
#define MME_CTRL_LO_PCU_RL_SAT_SEC_SEL_S 31
#define MME_CTRL_LO_PCU_RL_SAT_SEC_SEL_M 0x80000000

/* MME_CTRL_LO_EU0_REDUN_CLK_EN */
#define MME_CTRL_LO_EU0_REDUN_CLK_EN_V_S 0
#define MME_CTRL_LO_EU0_REDUN_CLK_EN_V_M 0x1FFFF

/* MME_CTRL_LO_EU1_REDUN_CLK_EN */
#define MME_CTRL_LO_EU1_REDUN_CLK_EN_V_S 0
#define MME_CTRL_LO_EU1_REDUN_CLK_EN_V_M 0x1FFFF

/* MME_CTRL_LO_REDUN */
#define MME_CTRL_LO_REDUN_EU0_S 0
#define MME_CTRL_LO_REDUN_EU0_M 0x3F
#define MME_CTRL_LO_REDUN_EU1_S 8
#define MME_CTRL_LO_REDUN_EU1_M 0x3F00

/* MME_CTRL_LO_EU_ISOLATION_DIS */
#define MME_CTRL_LO_EU_ISOLATION_DIS_EU0_S 0
#define MME_CTRL_LO_EU_ISOLATION_DIS_EU0_M 0x1
#define MME_CTRL_LO_EU_ISOLATION_DIS_EU1_S 1
#define MME_CTRL_LO_EU_ISOLATION_DIS_EU1_M 0x2

/* MME_CTRL_LO_QM */
#define MME_CTRL_LO_QM_STOP_ON_SB_ERR_S 0
#define MME_CTRL_LO_QM_STOP_ON_SB_ERR_M 0x1
#define MME_CTRL_LO_QM_STOP_ON_WAP_AXI_ERR_S 1
#define MME_CTRL_LO_QM_STOP_ON_WAP_AXI_ERR_M 0x2
#define MME_CTRL_LO_QM_STOP_ON_ARC_AXI_ERR_S 2
#define MME_CTRL_LO_QM_STOP_ON_ARC_AXI_ERR_M 0x4
#define MME_CTRL_LO_QM_STOP_ON_SIG_AXI_ERR_S 3
#define MME_CTRL_LO_QM_STOP_ON_SIG_AXI_ERR_M 0x8
#define MME_CTRL_LO_QM_STOP_ON_ARC_SERR_S 4
#define MME_CTRL_LO_QM_STOP_ON_ARC_SERR_M 0x10
#define MME_CTRL_LO_QM_STOP_ON_ARC_DERR_S 5
#define MME_CTRL_LO_QM_STOP_ON_ARC_DERR_M 0x20
#define MME_CTRL_LO_QM_STOP_ON_ACC_SERR_S 6
#define MME_CTRL_LO_QM_STOP_ON_ACC_SERR_M 0x40
#define MME_CTRL_LO_QM_STOP_ON_ACC_DERR_S 7
#define MME_CTRL_LO_QM_STOP_ON_ACC_DERR_M 0x80
#define MME_CTRL_LO_QM_STOP_ON_SB_SERR_S 8
#define MME_CTRL_LO_QM_STOP_ON_SB_SERR_M 0x100
#define MME_CTRL_LO_QM_STOP_ON_SB_DERR_S 9
#define MME_CTRL_LO_QM_STOP_ON_SB_DERR_M 0x200
#define MME_CTRL_LO_QM_STOP_ON_NUMERIC_ERR_S 10
#define MME_CTRL_LO_QM_STOP_ON_NUMERIC_ERR_M 0x400
#define MME_CTRL_LO_QM_DBG_HALT_EN_S 11
#define MME_CTRL_LO_QM_DBG_HALT_EN_M 0x800
#define MME_CTRL_LO_QM_EXT_ADDR_ERR_EN_S 12
#define MME_CTRL_LO_QM_EXT_ADDR_ERR_EN_M 0x1000
#define MME_CTRL_LO_QM_FENCE_ON_COUT_SM_INFLIGHT_S 13
#define MME_CTRL_LO_QM_FENCE_ON_COUT_SM_INFLIGHT_M 0x2000
#define MME_CTRL_LO_QM_FENCE_ON_DMA_SM_INFLIGHT_S 14
#define MME_CTRL_LO_QM_FENCE_ON_DMA_SM_INFLIGHT_M 0x4000

/* MME_CTRL_LO_EARLY_RELEASE_STATUS */
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_AGU_COUT_MASTER_S 0
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_AGU_COUT_MASTER_M 0xF
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_AGU_COUT_SLAVE_S 4
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_AGU_COUT_SLAVE_M 0xF0
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_AP_BRAIN_MASTER_S 8
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_AP_BRAIN_MASTER_M 0xF00
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_AP_BRAIN_SLAVE_S 12
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_AP_BRAIN_SLAVE_M 0xF000
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_EU_BRAIN_MASTER_S 16
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_EU_BRAIN_MASTER_M 0xF0000
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_EU_BRAIN_SLAVE_S 20
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_EU_BRAIN_SLAVE_M 0xF00000
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_DMA_COUT_MASTER_S 24
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_DMA_COUT_MASTER_M 0xF000000
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_DMA_COUT_SLAVE_S 28
#define MME_CTRL_LO_EARLY_RELEASE_STATUS_DMA_COUT_SLAVE_M 0xF0000000

/* MME_CTRL_LO_INTR_CAUSE */
#define MME_CTRL_LO_INTR_CAUSE_V_S 0
#define MME_CTRL_LO_INTR_CAUSE_V_M 0x3FFFFF

/* MME_CTRL_LO_INTR_MASK */
#define MME_CTRL_LO_INTR_MASK_V_S 0
#define MME_CTRL_LO_INTR_MASK_V_M 0x3FFFFF

/* MME_CTRL_LO_INTR_CLEAR */
#define MME_CTRL_LO_INTR_CLEAR_V_S 0
#define MME_CTRL_LO_INTR_CLEAR_V_M 0x3FFFFF

/* MME_CTRL_LO_REDUN_PSOC_SEL_SEC */
#define MME_CTRL_LO_REDUN_PSOC_SEL_SEC_EU0_S 0
#define MME_CTRL_LO_REDUN_PSOC_SEL_SEC_EU0_M 0x1
#define MME_CTRL_LO_REDUN_PSOC_SEL_SEC_EU1_S 1
#define MME_CTRL_LO_REDUN_PSOC_SEL_SEC_EU1_M 0x2

/* MME_CTRL_LO_BIST */
#define MME_CTRL_LO_BIST_FUNC_MODE_S 0
#define MME_CTRL_LO_BIST_FUNC_MODE_M 0x1
#define MME_CTRL_LO_BIST_APB_SW_MODE_S 1
#define MME_CTRL_LO_BIST_APB_SW_MODE_M 0x2

/* MME_CTRL_LO_EU_RL_ENABLE */
#define MME_CTRL_LO_EU_RL_ENABLE_V_S 0
#define MME_CTRL_LO_EU_RL_ENABLE_V_M 0x1

/* MME_CTRL_LO_EU_RL_TOKEN_SEL */
#define MME_CTRL_LO_EU_RL_TOKEN_SEL_STAT_S 0
#define MME_CTRL_LO_EU_RL_TOKEN_SEL_STAT_M 0x1

/* MME_CTRL_LO_EU_RL_CFG */
#define MME_CTRL_LO_EU_RL_CFG_RST_TOKEN_S 0
#define MME_CTRL_LO_EU_RL_CFG_RST_TOKEN_M 0xFF
#define MME_CTRL_LO_EU_RL_CFG_TIMEOUT_S 8
#define MME_CTRL_LO_EU_RL_CFG_TIMEOUT_M 0xFF00
#define MME_CTRL_LO_EU_RL_CFG_SATURATION_S 16
#define MME_CTRL_LO_EU_RL_CFG_SATURATION_M 0xFF0000
#define MME_CTRL_LO_EU_RL_CFG_DATA_SIZE_S 24
#define MME_CTRL_LO_EU_RL_CFG_DATA_SIZE_M 0xFF000000

/* MME_CTRL_LO_PCU_DBG_MASTER_DW0 */
#define MME_CTRL_LO_PCU_DBG_MASTER_DW0_FSM_STATE_S 0
#define MME_CTRL_LO_PCU_DBG_MASTER_DW0_FSM_STATE_M 0x1
#define MME_CTRL_LO_PCU_DBG_MASTER_DW0_REAL_POOL_TOKENS_S 8
#define MME_CTRL_LO_PCU_DBG_MASTER_DW0_REAL_POOL_TOKENS_M 0xFFFFF00

/* MME_CTRL_LO_PCU_DBG_MASTER_DW1 */
#define MME_CTRL_LO_PCU_DBG_MASTER_DW1_ALL_POOL_TOKENS_S 0
#define MME_CTRL_LO_PCU_DBG_MASTER_DW1_ALL_POOL_TOKENS_M 0xFFFFF

/* MME_CTRL_LO_PCU_DBG_MASTER_DW2 */
#define MME_CTRL_LO_PCU_DBG_MASTER_DW2_BUBBLE_CYC_CNTR_S 0
#define MME_CTRL_LO_PCU_DBG_MASTER_DW2_BUBBLE_CYC_CNTR_M 0xFFFF
#define MME_CTRL_LO_PCU_DBG_MASTER_DW2_DUMMY_CYC_CNTR_S 16
#define MME_CTRL_LO_PCU_DBG_MASTER_DW2_DUMMY_CYC_CNTR_M 0xFFFF0000

/* MME_CTRL_LO_PCU_DBG_MASTER_DW3 */
#define MME_CTRL_LO_PCU_DBG_MASTER_DW3_REAL_MACS_HISTORY_S 0
#define MME_CTRL_LO_PCU_DBG_MASTER_DW3_REAL_MACS_HISTORY_M 0xFFFF
#define MME_CTRL_LO_PCU_DBG_MASTER_DW3_ALL_MACS_HISTORY_S 16
#define MME_CTRL_LO_PCU_DBG_MASTER_DW3_ALL_MACS_HISTORY_M 0xFFFF0000

/* MME_CTRL_LO_PCU_DBG_MASTER_WKL_ID */
#define MME_CTRL_LO_PCU_DBG_MASTER_WKL_ID_B_S 0
#define MME_CTRL_LO_PCU_DBG_MASTER_WKL_ID_B_M 0xFFFFFFFF

/* MME_CTRL_LO_PCU_DBG_SLAVE_DW0 */
#define MME_CTRL_LO_PCU_DBG_SLAVE_DW0_FSM_STATE_S 0
#define MME_CTRL_LO_PCU_DBG_SLAVE_DW0_FSM_STATE_M 0x1
#define MME_CTRL_LO_PCU_DBG_SLAVE_DW0_REAL_POOL_TOKENS_S 8
#define MME_CTRL_LO_PCU_DBG_SLAVE_DW0_REAL_POOL_TOKENS_M 0xFFFFF00

/* MME_CTRL_LO_PCU_DBG_SLAVE_DW1 */
#define MME_CTRL_LO_PCU_DBG_SLAVE_DW1_ALL_POOL_TOKENS_S 0
#define MME_CTRL_LO_PCU_DBG_SLAVE_DW1_ALL_POOL_TOKENS_M 0xFFFFF

/* MME_CTRL_LO_PCU_DBG_SLAVE_DW2 */
#define MME_CTRL_LO_PCU_DBG_SLAVE_DW2_BUBBLE_CYC_CNTR_S 0
#define MME_CTRL_LO_PCU_DBG_SLAVE_DW2_BUBBLE_CYC_CNTR_M 0xFFFF
#define MME_CTRL_LO_PCU_DBG_SLAVE_DW2_DUMMY_CYC_CNTR_S 16
#define MME_CTRL_LO_PCU_DBG_SLAVE_DW2_DUMMY_CYC_CNTR_M 0xFFFF0000

/* MME_CTRL_LO_PCU_DBG_SLAVE_DW3 */
#define MME_CTRL_LO_PCU_DBG_SLAVE_DW3_REAL_MACS_HISTORY_S 0
#define MME_CTRL_LO_PCU_DBG_SLAVE_DW3_REAL_MACS_HISTORY_M 0xFFFF
#define MME_CTRL_LO_PCU_DBG_SLAVE_DW3_ALL_MACS_HISTORY_S 16
#define MME_CTRL_LO_PCU_DBG_SLAVE_DW3_ALL_MACS_HISTORY_M 0xFFFF0000

/* MME_CTRL_LO_PCU_DBG_SLAVE_WKL_ID */
#define MME_CTRL_LO_PCU_DBG_SLAVE_WKL_ID_B_S 0
#define MME_CTRL_LO_PCU_DBG_SLAVE_WKL_ID_B_M 0xFFFFFFFF

/* MME_CTRL_LO_ETF_MEM_WRAP_RM */
#define MME_CTRL_LO_ETF_MEM_WRAP_RM_V_S 0
#define MME_CTRL_LO_ETF_MEM_WRAP_RM_V_M 0x3FFFFFFF

/* MME_CTRL_LO_SLV_AXI2APB */
#define MME_CTRL_LO_SLV_AXI2APB_MSK_ERROR_RSP_S 0
#define MME_CTRL_LO_SLV_AXI2APB_MSK_ERROR_RSP_M 0x1
#define MME_CTRL_LO_SLV_AXI2APB_BLOCK_PARTIAL_STRB_S 1
#define MME_CTRL_LO_SLV_AXI2APB_BLOCK_PARTIAL_STRB_M 0x2
#define MME_CTRL_LO_SLV_AXI2APB_SPL_ERROR_RSP_S 2
#define MME_CTRL_LO_SLV_AXI2APB_SPL_ERROR_RSP_M 0x4

/* MME_CTRL_LO_SIG_STALL */
#define MME_CTRL_LO_SIG_STALL_V_S 0
#define MME_CTRL_LO_SIG_STALL_V_M 0x1

/* MME_CTRL_LO_SIG */
#define MME_CTRL_LO_SIG_STOP_ON_SB_ERR_S 0
#define MME_CTRL_LO_SIG_STOP_ON_SB_ERR_M 0x1
#define MME_CTRL_LO_SIG_STOP_ON_WAP_AXI_ERR_S 1
#define MME_CTRL_LO_SIG_STOP_ON_WAP_AXI_ERR_M 0x2
#define MME_CTRL_LO_SIG_STOP_ON_ARC_AXI_ERR_S 2
#define MME_CTRL_LO_SIG_STOP_ON_ARC_AXI_ERR_M 0x4
#define MME_CTRL_LO_SIG_STOP_ON_SIG_AXI_ERR_S 3
#define MME_CTRL_LO_SIG_STOP_ON_SIG_AXI_ERR_M 0x8
#define MME_CTRL_LO_SIG_STOP_ON_ARC_SERR_S 4
#define MME_CTRL_LO_SIG_STOP_ON_ARC_SERR_M 0x10
#define MME_CTRL_LO_SIG_STOP_ON_ARC_DERR_S 5
#define MME_CTRL_LO_SIG_STOP_ON_ARC_DERR_M 0x20
#define MME_CTRL_LO_SIG_STOP_ON_ACC_SERR_S 6
#define MME_CTRL_LO_SIG_STOP_ON_ACC_SERR_M 0x40
#define MME_CTRL_LO_SIG_STOP_ON_ACC_DERR_S 7
#define MME_CTRL_LO_SIG_STOP_ON_ACC_DERR_M 0x80
#define MME_CTRL_LO_SIG_STOP_ON_SB_SERR_S 8
#define MME_CTRL_LO_SIG_STOP_ON_SB_SERR_M 0x100
#define MME_CTRL_LO_SIG_STOP_ON_SB_DERR_S 9
#define MME_CTRL_LO_SIG_STOP_ON_SB_DERR_M 0x200
#define MME_CTRL_LO_SIG_STOP_ON_NUMERIC_ERR_S 10
#define MME_CTRL_LO_SIG_STOP_ON_NUMERIC_ERR_M 0x400

/* MME_CTRL_LO_LOG_ARCH_MASK */
#define MME_CTRL_LO_LOG_ARCH_MASK_MASTER_S 0
#define MME_CTRL_LO_LOG_ARCH_MASK_MASTER_M 0xFF
#define MME_CTRL_LO_LOG_ARCH_MASK_SLAVE_S 8
#define MME_CTRL_LO_LOG_ARCH_MASK_SLAVE_M 0xFF00

/* MME_CTRL_LO_AGU_ERR_WKL_ID */
#define MME_CTRL_LO_AGU_ERR_WKL_ID_V_S 0
#define MME_CTRL_LO_AGU_ERR_WKL_ID_V_M 0xFFFFFFFF

/* MME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT0 */
#define MME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT0_V_S 0
#define MME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT0_V_M 0x1FFFF

/* MME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT1 */
#define MME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT1_V_S 0
#define MME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT1_V_M 0x1FFFF

/* MME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT2 */
#define MME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT2_V_S 0
#define MME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT2_V_M 0x1FFFF

/* MME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT3 */
#define MME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT3_V_S 0
#define MME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT3_V_M 0x1FFFF

/* MME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT0 */
#define MME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT0_V_S 0
#define MME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT0_V_M 0x1FFFF

/* MME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT1 */
#define MME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT1_V_S 0
#define MME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT1_V_M 0x1FFFF

/* MME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT2 */
#define MME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT2_V_S 0
#define MME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT2_V_M 0x1FFFF

/* MME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT3 */
#define MME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT3_V_S 0
#define MME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT3_V_M 0x1FFFF

/* MME_CTRL_LO_SBTE0_DBG_ADDR_SPLIT0 */
#define MME_CTRL_LO_SBTE0_DBG_ADDR_SPLIT0_V_S 0
#define MME_CTRL_LO_SBTE0_DBG_ADDR_SPLIT0_V_M 0xFFFFF

/* MME_CTRL_LO_SBTE0_DBG_ADDR_SPLIT1 */
#define MME_CTRL_LO_SBTE0_DBG_ADDR_SPLIT1_V_S 0
#define MME_CTRL_LO_SBTE0_DBG_ADDR_SPLIT1_V_M 0xFFFFF

/* MME_CTRL_LO_SBTE1_DBG_ADDR_SPLIT0 */
#define MME_CTRL_LO_SBTE1_DBG_ADDR_SPLIT0_V_S 0
#define MME_CTRL_LO_SBTE1_DBG_ADDR_SPLIT0_V_M 0xFFFFF

/* MME_CTRL_LO_SBTE1_DBG_ADDR_SPLIT1 */
#define MME_CTRL_LO_SBTE1_DBG_ADDR_SPLIT1_V_S 0
#define MME_CTRL_LO_SBTE1_DBG_ADDR_SPLIT1_V_M 0xFFFFF

/* MME_CTRL_LO_HBW_CLK_ENABLER_DIS */
#define MME_CTRL_LO_HBW_CLK_ENABLER_DIS_AXI_S 0
#define MME_CTRL_LO_HBW_CLK_ENABLER_DIS_AXI_M 0x1
#define MME_CTRL_LO_HBW_CLK_ENABLER_DIS_APB_S 1
#define MME_CTRL_LO_HBW_CLK_ENABLER_DIS_APB_M 0x2

/* MME_CTRL_LO_MISC */
#define MME_CTRL_LO_MISC_ACC_ID_LSB_MASK_DIS_S 0
#define MME_CTRL_LO_MISC_ACC_ID_LSB_MASK_DIS_M 0x1
#define MME_CTRL_LO_MISC_EU_A_CLIP_INF_INPUT_S 3
#define MME_CTRL_LO_MISC_EU_A_CLIP_INF_INPUT_M 0x8
#define MME_CTRL_LO_MISC_EU_B_CLIP_INF_INPUT_S 4
#define MME_CTRL_LO_MISC_EU_B_CLIP_INF_INPUT_M 0x10
#define MME_CTRL_LO_MISC_SB_TR_MODE_H_MIN_A_S 8
#define MME_CTRL_LO_MISC_SB_TR_MODE_H_MIN_A_M 0x7F00
#define MME_CTRL_LO_MISC_SB_TR_MODE_H_MIN_B_S 16
#define MME_CTRL_LO_MISC_SB_TR_MODE_H_MIN_B_M 0x7F0000
#define MME_CTRL_LO_MISC_CMD_TRIG_SOC_SEL_S 24
#define MME_CTRL_LO_MISC_CMD_TRIG_SOC_SEL_M 0x1000000

/* MME_CTRL_LO_SO_AWPROT_BIT0 */
#define MME_CTRL_LO_SO_AWPROT_BIT0_V_S 0
#define MME_CTRL_LO_SO_AWPROT_BIT0_V_M 0x1

/* MME_CTRL_LO_SO_AWPROT_BIT1 */
#define MME_CTRL_LO_SO_AWPROT_BIT1_V_S 0
#define MME_CTRL_LO_SO_AWPROT_BIT1_V_M 0x1

/* MME_CTRL_LO_SO_AWPROT_BIT2 */
#define MME_CTRL_LO_SO_AWPROT_BIT2_V_S 0
#define MME_CTRL_LO_SO_AWPROT_BIT2_V_M 0x1

/* MME_CTRL_LO_DMA_SO_AWPROT_BIT0 */
#define MME_CTRL_LO_DMA_SO_AWPROT_BIT0_V_S 0
#define MME_CTRL_LO_DMA_SO_AWPROT_BIT0_V_M 0x1

/* MME_CTRL_LO_DMA_SO_AWPROT_BIT1 */
#define MME_CTRL_LO_DMA_SO_AWPROT_BIT1_V_S 0
#define MME_CTRL_LO_DMA_SO_AWPROT_BIT1_V_M 0x1

/* MME_CTRL_LO_DMA_SO_AWPROT_BIT2 */
#define MME_CTRL_LO_DMA_SO_AWPROT_BIT2_V_S 0
#define MME_CTRL_LO_DMA_SO_AWPROT_BIT2_V_M 0x1

/* MME_CTRL_LO_ARCH_DMA_A_SS */
#define MME_CTRL_LO_ARCH_DMA_A_SS_MINUS_1_S 0
#define MME_CTRL_LO_ARCH_DMA_A_SS_MINUS_1_M 0xFFFFFFFF

/* MME_CTRL_LO_ARCH_DMA_B_SS */
#define MME_CTRL_LO_ARCH_DMA_B_SS_MINUS_1_S 0
#define MME_CTRL_LO_ARCH_DMA_B_SS_MINUS_1_M 0xFFFFFFFF

/* MME_CTRL_LO_ARCH_DMA_COUT_SS */
#define MME_CTRL_LO_ARCH_DMA_COUT_SS_MINUS_1_S 0
#define MME_CTRL_LO_ARCH_DMA_COUT_SS_MINUS_1_M 0xFFFFFFFF

#endif /* ASIC_REG_MME_CTRL_LO_MASKS_H_ */
