/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_MME_CTRL_LO_REGS_H_
#define ASIC_REG_MME_CTRL_LO_REGS_H_

/*
 *****************************************
 *   MME_CTRL_LO
 *   (Prototype: MME_CTRL_LO)
 *****************************************
 */

#define mmMME_CTRL_LO_ARCH_STATUS_MASTER 0x0

#define mmMME_CTRL_LO_ARCH_STATUS_SLAVE 0x4

#define mmMME_CTRL_LO_ARCH_A_SS 0x1E0

#define mmMME_CTRL_LO_ARCH_B_SS 0x1E4

#define mmMME_CTRL_LO_ARCH_COUT_SS 0x210

#define mmMME_CTRL_LO_CMD 0x300

#define mmMME_CTRL_LO_QM_STALL 0x400

#define mmMME_CTRL_LO_LOG_SHADOW_LO 0x404

#define mmMME_CTRL_LO_LOG_SHADOW_HI 0x408

#define mmMME_CTRL_LO_SYNC_OBJECT_FIFO_TH 0x40C

#define mmMME_CTRL_LO_EUS_ROLLUP_DLY_DW0 0x410

#define mmMME_CTRL_LO_EUS_ROLLUP_DLY_DW1 0x414

#define mmMME_CTRL_LO_EUS_ROLLUP_CD_PROT_F16 0x418

#define mmMME_CTRL_LO_EUS_ROLLUP_CD_PROT_F8 0x41C

#define mmMME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32 0x420

#define mmMME_CTRL_LO_EUS_ROLLUP_CD_PROT_TF32 0x424

#define mmMME_CTRL_LO_PCU_RL_DESC0 0x428

#define mmMME_CTRL_LO_PCU_RL_TOKEN_UPDATE 0x42C

#define mmMME_CTRL_LO_PCU_RL_TH 0x430

#define mmMME_CTRL_LO_PCU_RL_MIN 0x434

#define mmMME_CTRL_LO_PCU_RL_CTRL_EN 0x438

#define mmMME_CTRL_LO_PCU_RL_HISTORY_LOG_SIZE 0x43C

#define mmMME_CTRL_LO_PCU_DUMMY_A_BF16 0x440

#define mmMME_CTRL_LO_PCU_DUMMY_B_BF16 0x444

#define mmMME_CTRL_LO_PCU_DUMMY_A_FP16 0x448

#define mmMME_CTRL_LO_PCU_DUMMY_B_FP16 0x44C

#define mmMME_CTRL_LO_PCU_DUMMY_F8 0x450

#define mmMME_CTRL_LO_PCU_DUMMY_A_FP32_ODD 0x454

#define mmMME_CTRL_LO_PCU_DUMMY_A_FP32_EVEN 0x458

#define mmMME_CTRL_LO_PCU_DUMMY_B_FP32_ODD 0x45C

#define mmMME_CTRL_LO_PCU_DUMMY_B_FP32_EVEN 0x460

#define mmMME_CTRL_LO_PCU_DUMMY_A_TF32_ODD 0x464

#define mmMME_CTRL_LO_PCU_DUMMY_A_TF32_EVEN 0x468

#define mmMME_CTRL_LO_PCU_DUMMY_B_TF32_ODD 0x46C

#define mmMME_CTRL_LO_PCU_DUMMY_B_TF32_EVEN 0x470

#define mmMME_CTRL_LO_EU 0x478

#define mmMME_CTRL_LO_COUT_AGU_SM_INFLIGHT_CNTR 0x47C

#define mmMME_CTRL_LO_COUT_AGU_SM_TOTAL_CNTR 0x480

#define mmMME_CTRL_LO_DMA_AGU_SM_INFLIGHT_CNTR 0x484

#define mmMME_CTRL_LO_DMA_AGU_SM_TOTAL_CNTR 0x488

#define mmMME_CTRL_LO_PCU_RL_SAT_SEC 0x48C

#define mmMME_CTRL_LO_EU0_REDUN_CLK_EN 0x490

#define mmMME_CTRL_LO_EU1_REDUN_CLK_EN 0x494

#define mmMME_CTRL_LO_REDUN 0x498

#define mmMME_CTRL_LO_EU_ISOLATION_DIS 0x49C

#define mmMME_CTRL_LO_QM 0x4A0

#define mmMME_CTRL_LO_EARLY_RELEASE_STATUS 0x4A4

#define mmMME_CTRL_LO_INTR_CAUSE 0x4A8

#define mmMME_CTRL_LO_INTR_MASK 0x4AC

#define mmMME_CTRL_LO_INTR_CLEAR 0x4B0

#define mmMME_CTRL_LO_REDUN_PSOC_SEL_SEC 0x4B4

#define mmMME_CTRL_LO_BIST 0x4B8

#define mmMME_CTRL_LO_EU_RL_ENABLE 0x4BC

#define mmMME_CTRL_LO_EU_RL_TOKEN_SEL 0x4C0

#define mmMME_CTRL_LO_EU_RL_CFG 0x4C4

#define mmMME_CTRL_LO_PCU_DBG_MASTER_DW0 0x4C8

#define mmMME_CTRL_LO_PCU_DBG_MASTER_DW1 0x4CC

#define mmMME_CTRL_LO_PCU_DBG_MASTER_DW2 0x4D0

#define mmMME_CTRL_LO_PCU_DBG_MASTER_DW3 0x4D4

#define mmMME_CTRL_LO_PCU_DBG_MASTER_WKL_ID 0x4D8

#define mmMME_CTRL_LO_PCU_DBG_SLAVE_DW0 0x4DC

#define mmMME_CTRL_LO_PCU_DBG_SLAVE_DW1 0x4E0

#define mmMME_CTRL_LO_PCU_DBG_SLAVE_DW2 0x4E4

#define mmMME_CTRL_LO_PCU_DBG_SLAVE_DW3 0x4E8

#define mmMME_CTRL_LO_PCU_DBG_SLAVE_WKL_ID 0x4EC

#define mmMME_CTRL_LO_ETF_MEM_WRAP_RM 0x4F0

#define mmMME_CTRL_LO_SLV_AXI2APB 0x4F4

#define mmMME_CTRL_LO_SIG_STALL 0x4F8

#define mmMME_CTRL_LO_SIG 0x4FC

#define mmMME_CTRL_LO_LOG_ARCH_MASK 0x500

#define mmMME_CTRL_LO_AGU_ERR_WKL_ID 0x504

#define mmMME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT0 0x508

#define mmMME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT1 0x50C

#define mmMME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT2 0x510

#define mmMME_CTRL_LO_SBTE0_HBW_ADDR_SPLIT3 0x514

#define mmMME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT0 0x518

#define mmMME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT1 0x51C

#define mmMME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT2 0x520

#define mmMME_CTRL_LO_SBTE1_HBW_ADDR_SPLIT3 0x524

#define mmMME_CTRL_LO_SBTE0_DBG_ADDR_SPLIT0 0x528

#define mmMME_CTRL_LO_SBTE0_DBG_ADDR_SPLIT1 0x52C

#define mmMME_CTRL_LO_SBTE1_DBG_ADDR_SPLIT0 0x530

#define mmMME_CTRL_LO_SBTE1_DBG_ADDR_SPLIT1 0x534

#define mmMME_CTRL_LO_HBW_CLK_ENABLER_DIS 0x538

#define mmMME_CTRL_LO_MISC 0x53C

#define mmMME_CTRL_LO_SO_AWPROT_BIT0 0x540

#define mmMME_CTRL_LO_SO_AWPROT_BIT1 0x544

#define mmMME_CTRL_LO_SO_AWPROT_BIT2 0x548

#define mmMME_CTRL_LO_DMA_SO_AWPROT_BIT0 0x54C

#define mmMME_CTRL_LO_DMA_SO_AWPROT_BIT1 0x550

#define mmMME_CTRL_LO_DMA_SO_AWPROT_BIT2 0x554

#define mmMME_CTRL_LO_ARCH_DMA_A_SS 0x9E0

#define mmMME_CTRL_LO_ARCH_DMA_B_SS 0x9E4

#define mmMME_CTRL_LO_ARCH_DMA_COUT_SS 0xA10

#endif /* ASIC_REG_MME_CTRL_LO_REGS_H_ */
