/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_MSTR_IF_AXPROT_LBW_MASKS_H_
#define ASIC_REG_MSTR_IF_AXPROT_LBW_MASKS_H_

/*
 *****************************************
 *   MSTR_IF_AXPROT_LBW
 *   (Prototype: AXPROT)
 *****************************************
 */

/* MSTR_IF_AXPROT_LBW_ARPROT_0_OVRD */
#define MSTR_IF_AXPROT_LBW_ARPROT_0_OVRD_OVRD_EN_S 0
#define MSTR_IF_AXPROT_LBW_ARPROT_0_OVRD_OVRD_EN_M 0x1
#define MSTR_IF_AXPROT_LBW_ARPROT_0_OVRD_VAL_S 4
#define MSTR_IF_AXPROT_LBW_ARPROT_0_OVRD_VAL_M 0x10

/* MSTR_IF_AXPROT_LBW_ARPROT_1_OVRD */
#define MSTR_IF_AXPROT_LBW_ARPROT_1_OVRD_OVRD_EN_S 0
#define MSTR_IF_AXPROT_LBW_ARPROT_1_OVRD_OVRD_EN_M 0x1
#define MSTR_IF_AXPROT_LBW_ARPROT_1_OVRD_VAL_S 4
#define MSTR_IF_AXPROT_LBW_ARPROT_1_OVRD_VAL_M 0x10

/* MSTR_IF_AXPROT_LBW_ARPROT_2_OVRD */
#define MSTR_IF_AXPROT_LBW_ARPROT_2_OVRD_OVRD_EN_S 0
#define MSTR_IF_AXPROT_LBW_ARPROT_2_OVRD_OVRD_EN_M 0x1
#define MSTR_IF_AXPROT_LBW_ARPROT_2_OVRD_VAL_S 4
#define MSTR_IF_AXPROT_LBW_ARPROT_2_OVRD_VAL_M 0x10

/* MSTR_IF_AXPROT_LBW_AWPROT_0_OVRD */
#define MSTR_IF_AXPROT_LBW_AWPROT_0_OVRD_OVRD_EN_S 0
#define MSTR_IF_AXPROT_LBW_AWPROT_0_OVRD_OVRD_EN_M 0x1
#define MSTR_IF_AXPROT_LBW_AWPROT_0_OVRD_VAL_S 4
#define MSTR_IF_AXPROT_LBW_AWPROT_0_OVRD_VAL_M 0x10

/* MSTR_IF_AXPROT_LBW_AWPROT_1_OVRD */
#define MSTR_IF_AXPROT_LBW_AWPROT_1_OVRD_OVRD_EN_S 0
#define MSTR_IF_AXPROT_LBW_AWPROT_1_OVRD_OVRD_EN_M 0x1
#define MSTR_IF_AXPROT_LBW_AWPROT_1_OVRD_VAL_S 4
#define MSTR_IF_AXPROT_LBW_AWPROT_1_OVRD_VAL_M 0x10

/* MSTR_IF_AXPROT_LBW_AWPROT_2_OVRD */
#define MSTR_IF_AXPROT_LBW_AWPROT_2_OVRD_OVRD_EN_S 0
#define MSTR_IF_AXPROT_LBW_AWPROT_2_OVRD_OVRD_EN_M 0x1
#define MSTR_IF_AXPROT_LBW_AWPROT_2_OVRD_VAL_S 4
#define MSTR_IF_AXPROT_LBW_AWPROT_2_OVRD_VAL_M 0x10

#endif /* ASIC_REG_MSTR_IF_AXPROT_LBW_MASKS_H_ */
