/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PCIE_AUX_MASKS_H_
#define ASIC_REG_PCIE_AUX_MASKS_H_

/*
 *****************************************
 *   PCIE_AUX
 *   (Prototype: PCIE_AUX)
 *****************************************
 */

/* PCIE_AUX_APB_TIMEOUT */
#define PCIE_AUX_APB_TIMEOUT_BYPASS_S 0
#define PCIE_AUX_APB_TIMEOUT_BYPASS_M 0x1

/* PCIE_AUX_SW_GENERAL_PURPOSE */
#define PCIE_AUX_SW_GENERAL_PURPOSE_VAL_S 0
#define PCIE_AUX_SW_GENERAL_PURPOSE_VAL_M 0xFFFFFFFF

/* PCIE_AUX_PHY_INIT */
#define PCIE_AUX_PHY_INIT_IND_S 0
#define PCIE_AUX_PHY_INIT_IND_M 0x1

/* PCIE_AUX_BAR0_START_L */
#define PCIE_AUX_BAR0_START_L_VAL_S 0
#define PCIE_AUX_BAR0_START_L_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR0_START_H */
#define PCIE_AUX_BAR0_START_H_VAL_S 0
#define PCIE_AUX_BAR0_START_H_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR1_START */
#define PCIE_AUX_BAR1_START_VAL_S 0
#define PCIE_AUX_BAR1_START_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR2_START_L */
#define PCIE_AUX_BAR2_START_L_VAL_S 0
#define PCIE_AUX_BAR2_START_L_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR2_START_H */
#define PCIE_AUX_BAR2_START_H_VAL_S 0
#define PCIE_AUX_BAR2_START_H_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR3_START */
#define PCIE_AUX_BAR3_START_VAL_S 0
#define PCIE_AUX_BAR3_START_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR4_START_L */
#define PCIE_AUX_BAR4_START_L_VAL_S 0
#define PCIE_AUX_BAR4_START_L_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR4_START_H */
#define PCIE_AUX_BAR4_START_H_VAL_S 0
#define PCIE_AUX_BAR4_START_H_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR5_START */
#define PCIE_AUX_BAR5_START_VAL_S 0
#define PCIE_AUX_BAR5_START_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR0_LIMIT_L */
#define PCIE_AUX_BAR0_LIMIT_L_VAL_S 0
#define PCIE_AUX_BAR0_LIMIT_L_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR0_LIMIT_H */
#define PCIE_AUX_BAR0_LIMIT_H_VAL_S 0
#define PCIE_AUX_BAR0_LIMIT_H_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR1_LIMIT */
#define PCIE_AUX_BAR1_LIMIT_VAL_S 0
#define PCIE_AUX_BAR1_LIMIT_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR2_LIMIT_L */
#define PCIE_AUX_BAR2_LIMIT_L_VAL_S 0
#define PCIE_AUX_BAR2_LIMIT_L_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR2_LIMIT_H */
#define PCIE_AUX_BAR2_LIMIT_H_VAL_S 0
#define PCIE_AUX_BAR2_LIMIT_H_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR3_LIMIT */
#define PCIE_AUX_BAR3_LIMIT_VAL_S 0
#define PCIE_AUX_BAR3_LIMIT_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR4_LIMIT_L */
#define PCIE_AUX_BAR4_LIMIT_L_VAL_S 0
#define PCIE_AUX_BAR4_LIMIT_L_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR4_LIMIT_H */
#define PCIE_AUX_BAR4_LIMIT_H_VAL_S 0
#define PCIE_AUX_BAR4_LIMIT_H_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BAR5_LIMIT */
#define PCIE_AUX_BAR5_LIMIT_VAL_S 0
#define PCIE_AUX_BAR5_LIMIT_VAL_M 0xFFFFFFFF

/* PCIE_AUX_BUS_MASTER_EN */
#define PCIE_AUX_BUS_MASTER_EN_VAL_S 0
#define PCIE_AUX_BUS_MASTER_EN_VAL_M 0x1

/* PCIE_AUX_MEM_SPACE_EN */
#define PCIE_AUX_MEM_SPACE_EN_VAL_S 0
#define PCIE_AUX_MEM_SPACE_EN_VAL_M 0x1

/* PCIE_AUX_MAX_RD_REQ_SIZE */
#define PCIE_AUX_MAX_RD_REQ_SIZE_VAL_S 0
#define PCIE_AUX_MAX_RD_REQ_SIZE_VAL_M 0x7

/* PCIE_AUX_MAX_PAYLOAD_SIZE */
#define PCIE_AUX_MAX_PAYLOAD_SIZE_VAL_S 0
#define PCIE_AUX_MAX_PAYLOAD_SIZE_VAL_M 0x7

/* PCIE_AUX_EXT_TAG_EN */
#define PCIE_AUX_EXT_TAG_EN_VAL_S 0
#define PCIE_AUX_EXT_TAG_EN_VAL_M 0x1

/* PCIE_AUX_RCB */
#define PCIE_AUX_RCB_VAL_S 0
#define PCIE_AUX_RCB_VAL_M 0x1

/* PCIE_AUX_PM_NO_SOFT_RST */
#define PCIE_AUX_PM_NO_SOFT_RST_VAL_S 0
#define PCIE_AUX_PM_NO_SOFT_RST_VAL_M 0x1

/* PCIE_AUX_PBUS_NUM */
#define PCIE_AUX_PBUS_NUM_VAL_S 0
#define PCIE_AUX_PBUS_NUM_VAL_M 0xFF

/* PCIE_AUX_PBUS_DEV_NUM */
#define PCIE_AUX_PBUS_DEV_NUM_VAL_S 0
#define PCIE_AUX_PBUS_DEV_NUM_VAL_M 0x1F

/* PCIE_AUX_NO_SNOOP_EN */
#define PCIE_AUX_NO_SNOOP_EN_VAL_S 0
#define PCIE_AUX_NO_SNOOP_EN_VAL_M 0x1

/* PCIE_AUX_RELAX_ORDER_EN */
#define PCIE_AUX_RELAX_ORDER_EN_VAL_S 0
#define PCIE_AUX_RELAX_ORDER_EN_VAL_M 0x1

/* PCIE_AUX_HP_SLOT_CTRL_ACCESS */
#define PCIE_AUX_HP_SLOT_CTRL_ACCESS_VAL_S 0
#define PCIE_AUX_HP_SLOT_CTRL_ACCESS_VAL_M 0x1

/* PCIE_AUX_DLL_STATE_CHGED_EN */
#define PCIE_AUX_DLL_STATE_CHGED_EN_VAL_S 0
#define PCIE_AUX_DLL_STATE_CHGED_EN_VAL_M 0x1

/* PCIE_AUX_CMP_CPLED_INT_EN */
#define PCIE_AUX_CMP_CPLED_INT_EN_VAL_S 0
#define PCIE_AUX_CMP_CPLED_INT_EN_VAL_M 0x1

/* PCIE_AUX_HP_INT_EN */
#define PCIE_AUX_HP_INT_EN_VAL_S 0
#define PCIE_AUX_HP_INT_EN_VAL_M 0x1

/* PCIE_AUX_PRE_DET_CHGEN_EN */
#define PCIE_AUX_PRE_DET_CHGEN_EN_VAL_S 0
#define PCIE_AUX_PRE_DET_CHGEN_EN_VAL_M 0x1

/* PCIE_AUX_MRL_SENSOR_CHGED_EN */
#define PCIE_AUX_MRL_SENSOR_CHGED_EN_VAL_S 0
#define PCIE_AUX_MRL_SENSOR_CHGED_EN_VAL_M 0x1

/* PCIE_AUX_PWR_FAULT_DET_EN */
#define PCIE_AUX_PWR_FAULT_DET_EN_VAL_S 0
#define PCIE_AUX_PWR_FAULT_DET_EN_VAL_M 0x1

/* PCIE_AUX_ATTEN_BUTTON_PRESSED_EN */
#define PCIE_AUX_ATTEN_BUTTON_PRESSED_EN_VAL_S 0
#define PCIE_AUX_ATTEN_BUTTON_PRESSED_EN_VAL_M 0x1

/* PCIE_AUX_PF_FLR_ACTIVE */
#define PCIE_AUX_PF_FLR_ACTIVE_IDX_S 0
#define PCIE_AUX_PF_FLR_ACTIVE_IDX_M 0x1

/* PCIE_AUX_PF_FLR_DONE */
#define PCIE_AUX_PF_FLR_DONE_IDX_S 0
#define PCIE_AUX_PF_FLR_DONE_IDX_M 0x1

/* PCIE_AUX_FLR_INT */
#define PCIE_AUX_FLR_INT_IND_S 0
#define PCIE_AUX_FLR_INT_IND_M 0x1

/* PCIE_AUX_FLR_CTRL */
#define PCIE_AUX_FLR_CTRL_HW_CTRL_S 0
#define PCIE_AUX_FLR_CTRL_HW_CTRL_M 0x1
#define PCIE_AUX_FLR_CTRL_INT_MASK_S 1
#define PCIE_AUX_FLR_CTRL_INT_MASK_M 0x2
#define PCIE_AUX_FLR_CTRL_FSM_EN_S 2
#define PCIE_AUX_FLR_CTRL_FSM_EN_M 0x4
#define PCIE_AUX_FLR_CTRL_WD_CTRL_S 3
#define PCIE_AUX_FLR_CTRL_WD_CTRL_M 0x8

/* PCIE_AUX_FLR_WD_THRESHOLD */
#define PCIE_AUX_FLR_WD_THRESHOLD_VAL_S 0
#define PCIE_AUX_FLR_WD_THRESHOLD_VAL_M 0xFFFFFFFF

/* PCIE_AUX_LTSSM_EN */
#define PCIE_AUX_LTSSM_EN_IND_S 0
#define PCIE_AUX_LTSSM_EN_IND_M 0x1
#define PCIE_AUX_LTSSM_EN_MASK_S 1
#define PCIE_AUX_LTSSM_EN_MASK_M 0x2

/* PCIE_AUX_SYS_INTR */
#define PCIE_AUX_SYS_INTR_IND_S 0
#define PCIE_AUX_SYS_INTR_IND_M 0x1

/* PCIE_AUX_INT_DISABLE */
#define PCIE_AUX_INT_DISABLE_IND_S 0
#define PCIE_AUX_INT_DISABLE_IND_M 0x1

/* PCIE_AUX_SMLH_LINK_UP */
#define PCIE_AUX_SMLH_LINK_UP_IND_S 0
#define PCIE_AUX_SMLH_LINK_UP_IND_M 0x1

/* PCIE_AUX_PM_CURR_STATE */
#define PCIE_AUX_PM_CURR_STATE_VAL_S 0
#define PCIE_AUX_PM_CURR_STATE_VAL_M 0x7

/* PCIE_AUX_RDLH_LINK_UP */
#define PCIE_AUX_RDLH_LINK_UP_IND_S 0
#define PCIE_AUX_RDLH_LINK_UP_IND_M 0x1

/* PCIE_AUX_BRDG_SLV_XFER_PENDING */
#define PCIE_AUX_BRDG_SLV_XFER_PENDING_IND_S 0
#define PCIE_AUX_BRDG_SLV_XFER_PENDING_IND_M 0x1

/* PCIE_AUX_BRDG_DBI_XFER_PENDING */
#define PCIE_AUX_BRDG_DBI_XFER_PENDING_IND_S 0
#define PCIE_AUX_BRDG_DBI_XFER_PENDING_IND_M 0x1

/* PCIE_AUX_AUTO_SP_DIS */
#define PCIE_AUX_AUTO_SP_DIS_IND_S 0
#define PCIE_AUX_AUTO_SP_DIS_IND_M 0x1

/* PCIE_AUX_DBI */
#define PCIE_AUX_DBI_IO_S 12
#define PCIE_AUX_DBI_IO_M 0x1000
#define PCIE_AUX_DBI_BAR_S 13
#define PCIE_AUX_DBI_BAR_M 0xE000
#define PCIE_AUX_DBI_PF_NUM_S 16
#define PCIE_AUX_DBI_PF_NUM_M 0x1F0000
#define PCIE_AUX_DBI_VF_ACTIVE_S 21
#define PCIE_AUX_DBI_VF_ACTIVE_M 0x200000
#define PCIE_AUX_DBI_VF_NUM_S 22
#define PCIE_AUX_DBI_VF_NUM_M 0x3FC00000
#define PCIE_AUX_DBI_ROM_S 30
#define PCIE_AUX_DBI_ROM_M 0x40000000
#define PCIE_AUX_DBI_CS2_S 31
#define PCIE_AUX_DBI_CS2_M 0x80000000

/* PCIE_AUX_DBI_32 */
#define PCIE_AUX_DBI_32_IND_S 0
#define PCIE_AUX_DBI_32_IND_M 0x1

/* PCIE_AUX_DIAG_STATUS_BUS */
#define PCIE_AUX_DIAG_STATUS_BUS_VAL_S 0
#define PCIE_AUX_DIAG_STATUS_BUS_VAL_M 0xFFFFFFFF

/* PCIE_AUX_CDM_RAS_DES_EC_INFO */
#define PCIE_AUX_CDM_RAS_DES_EC_INFO_VAL_S 0
#define PCIE_AUX_CDM_RAS_DES_EC_INFO_VAL_M 0x3F

/* PCIE_AUX_CDM_RAS_DES_SD_COMMON */
#define PCIE_AUX_CDM_RAS_DES_SD_COMMON_VAL_S 0
#define PCIE_AUX_CDM_RAS_DES_SD_COMMON_VAL_M 0xFFFFFFFF

/* PCIE_AUX_APP_RAS_DES_TBA_CTRL */
#define PCIE_AUX_APP_RAS_DES_TBA_CTRL_VAL_S 0
#define PCIE_AUX_APP_RAS_DES_TBA_CTRL_VAL_M 0x3

/* PCIE_AUX_PM_MASTER_STATE */
#define PCIE_AUX_PM_MASTER_STATE_VAL_S 0
#define PCIE_AUX_PM_MASTER_STATE_VAL_M 0x1F

/* PCIE_AUX_PM_SLAVE_STATE */
#define PCIE_AUX_PM_SLAVE_STATE_VAL_S 0
#define PCIE_AUX_PM_SLAVE_STATE_VAL_M 0x1F

/* PCIE_AUX_PM_DSTATE */
#define PCIE_AUX_PM_DSTATE_VAL_S 0
#define PCIE_AUX_PM_DSTATE_VAL_M 0x7

/* PCIE_AUX_PM_PME_EN */
#define PCIE_AUX_PM_PME_EN_VAL_S 0
#define PCIE_AUX_PM_PME_EN_VAL_M 0x1

/* PCIE_AUX_PM_LINKST_IN_L0S */
#define PCIE_AUX_PM_LINKST_IN_L0S_VAL_S 0
#define PCIE_AUX_PM_LINKST_IN_L0S_VAL_M 0x1

/* PCIE_AUX_PM_LINKST_IN_L1 */
#define PCIE_AUX_PM_LINKST_IN_L1_VAL_S 0
#define PCIE_AUX_PM_LINKST_IN_L1_VAL_M 0x1

/* PCIE_AUX_PM_LINKST_IN_L2 */
#define PCIE_AUX_PM_LINKST_IN_L2_VAL_S 0
#define PCIE_AUX_PM_LINKST_IN_L2_VAL_M 0x1

/* PCIE_AUX_PM_LINKST_L2_EXIT */
#define PCIE_AUX_PM_LINKST_L2_EXIT_VAL_S 0
#define PCIE_AUX_PM_LINKST_L2_EXIT_VAL_M 0x1

/* PCIE_AUX_PM_STATUS */
#define PCIE_AUX_PM_STATUS_VAL_S 0
#define PCIE_AUX_PM_STATUS_VAL_M 0x1

/* PCIE_AUX_APP_READY_ENTER_L23 */
#define PCIE_AUX_APP_READY_ENTER_L23_IND_S 0
#define PCIE_AUX_APP_READY_ENTER_L23_IND_M 0x1

/* PCIE_AUX_APP_XFER_PENDING */
#define PCIE_AUX_APP_XFER_PENDING_IND_S 0
#define PCIE_AUX_APP_XFER_PENDING_IND_M 0x1

/* PCIE_AUX_APP_REQ_L1 */
#define PCIE_AUX_APP_REQ_L1_ENTER_S 0
#define PCIE_AUX_APP_REQ_L1_ENTER_M 0x1
#define PCIE_AUX_APP_REQ_L1_EXIT_S 1
#define PCIE_AUX_APP_REQ_L1_EXIT_M 0x2

/* PCIE_AUX_AUX_PM_EN */
#define PCIE_AUX_AUX_PM_EN_VAL_S 0
#define PCIE_AUX_AUX_PM_EN_VAL_M 0x1

/* PCIE_AUX_APPS_PM_XMT_PME */
#define PCIE_AUX_APPS_PM_XMT_PME_IND_S 0
#define PCIE_AUX_APPS_PM_XMT_PME_IND_M 0x1

/* PCIE_AUX_OUTBAND_PWRUP_CMD */
#define PCIE_AUX_OUTBAND_PWRUP_CMD_IND_S 0
#define PCIE_AUX_OUTBAND_PWRUP_CMD_IND_M 0x1

/* PCIE_AUX_PERST */
#define PCIE_AUX_PERST_RISING_INTR_S 0
#define PCIE_AUX_PERST_RISING_INTR_M 0x1
#define PCIE_AUX_PERST_FALLING_INTR_S 1
#define PCIE_AUX_PERST_FALLING_INTR_M 0x2

/* PCIE_AUX_DBI_RO_WR_DISABLE */
#define PCIE_AUX_DBI_RO_WR_DISABLE_VAL_S 0
#define PCIE_AUX_DBI_RO_WR_DISABLE_VAL_M 0x1

/* PCIE_AUX_HOLD_PHY_RST */
#define PCIE_AUX_HOLD_PHY_RST_VAL_S 0
#define PCIE_AUX_HOLD_PHY_RST_VAL_M 0x1

/* PCIE_AUX_TLP_INTERNAL_ERR_REP */
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_UNCOR_INTERNAL_ERR_S 0
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_UNCOR_INTERNAL_ERR_M 0x1
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_RCVR_OVERFLOW_ERR_S 1
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_RCVR_OVERFLOW_ERR_M 0x2
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_FC_PROTOCOL_ERR_S 2
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_FC_PROTOCOL_ERR_M 0x4
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_MLF_TLP_ERR_S 3
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_MLF_TLP_ERR_M 0x8
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_SURPRISE_DOWN_ERR_S 4
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_SURPRISE_DOWN_ERR_M 0x10
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_DL_PROTOCOL_ER_S 5
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_DL_PROTOCOL_ER_M 0x20
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_ECRC_ERR_S 6
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_ECRC_ERR_M 0x40
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_CORRECTED_INT_ERR_S 7
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_CORRECTED_INT_ERR_M 0x80
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_REPLAY_NUM_ROLLOVER_ERR_S 8
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_REPLAY_NUM_ROLLOVER_ERR_M 0x100
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_REPLAY_TIMER_TIMEOUT_ERR_S 9
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_REPLAY_TIMER_TIMEOUT_ERR_M 0x200
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_BAD_DLLP_ERR_S 10
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_BAD_DLLP_ERR_M 0x400
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_BAD_TLP_ERR_S 11
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_BAD_TLP_ERR_M 0x800
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_RCVR_ERR_S 12
#define PCIE_AUX_TLP_INTERNAL_ERR_REP_RCVR_ERR_M 0x1000

/* PCIE_AUX_APP_SRIS_MODE */
#define PCIE_AUX_APP_SRIS_MODE_VAL_S 0
#define PCIE_AUX_APP_SRIS_MODE_VAL_M 0x1

/* PCIE_AUX_BUS_MSTR_EN_CLR_INTR */
#define PCIE_AUX_BUS_MSTR_EN_CLR_INTR_INTR_S 0
#define PCIE_AUX_BUS_MSTR_EN_CLR_INTR_INTR_M 0x1

/* PCIE_AUX_BUS_MSTR_EN_CLR_INTR_MASK */
#define PCIE_AUX_BUS_MSTR_EN_CLR_INTR_MASK_MASK_S 0
#define PCIE_AUX_BUS_MSTR_EN_CLR_INTR_MASK_MASK_M 0x1

/* PCIE_AUX_EMERGENCY_PWR_RED_DET */
#define PCIE_AUX_EMERGENCY_PWR_RED_DET_CTRL_IND_S 0
#define PCIE_AUX_EMERGENCY_PWR_RED_DET_CTRL_IND_M 0x1
#define PCIE_AUX_EMERGENCY_PWR_RED_DET_PWRBRK_N_S 1
#define PCIE_AUX_EMERGENCY_PWR_RED_DET_PWRBRK_N_M 0x2

/* PCIE_AUX_EM_PWR_RED_DET_ENTRY_INTR */
#define PCIE_AUX_EM_PWR_RED_DET_ENTRY_INTR_INTR_S 0
#define PCIE_AUX_EM_PWR_RED_DET_ENTRY_INTR_INTR_M 0x1

/* PCIE_AUX_EM_PWR_RED_DET_EXIT_INTR */
#define PCIE_AUX_EM_PWR_RED_DET_EXIT_INTR_INTR_S 0
#define PCIE_AUX_EM_PWR_RED_DET_EXIT_INTR_INTR_M 0x1

/* PCIE_AUX_EM_PWR_RED_DET_INTR_CTRL */
#define PCIE_AUX_EM_PWR_RED_DET_INTR_CTRL_MASK_ENTRY_INTR_S 0
#define PCIE_AUX_EM_PWR_RED_DET_INTR_CTRL_MASK_ENTRY_INTR_M 0x1
#define PCIE_AUX_EM_PWR_RED_DET_INTR_CTRL_MASK_EXIT_INTR_S 1
#define PCIE_AUX_EM_PWR_RED_DET_INTR_CTRL_MASK_EXIT_INTR_M 0x2
#define PCIE_AUX_EM_PWR_RED_DET_INTR_CTRL_INTR_SRC_S 2
#define PCIE_AUX_EM_PWR_RED_DET_INTR_CTRL_INTR_SRC_M 0x4

/* PCIE_AUX_VPD_INTR */
#define PCIE_AUX_VPD_INTR_INTR_S 0
#define PCIE_AUX_VPD_INTR_INTR_M 0x1

/* PCIE_AUX_VPD_INTR_MASK */
#define PCIE_AUX_VPD_INTR_MASK_MASK_S 0
#define PCIE_AUX_VPD_INTR_MASK_MASK_M 0x1

/* PCIE_AUX_PWR_BUDGET_FUNC_NUM */
#define PCIE_AUX_PWR_BUDGET_FUNC_NUM_VAL_S 0
#define PCIE_AUX_PWR_BUDGET_FUNC_NUM_VAL_M 0x7

/* PCIE_AUX_PWR_BUDGET_DATA_SEL */
#define PCIE_AUX_PWR_BUDGET_DATA_SEL_VAL_S 0
#define PCIE_AUX_PWR_BUDGET_DATA_SEL_VAL_M 0xFF

/* PCIE_AUX_PWR_BUDGET_SEL */
#define PCIE_AUX_PWR_BUDGET_SEL_VAL_S 0
#define PCIE_AUX_PWR_BUDGET_SEL_VAL_M 0x1

/* PCIE_AUX_PWR_BUDGET_DATA */
#define PCIE_AUX_PWR_BUDGET_DATA_VAL_S 0
#define PCIE_AUX_PWR_BUDGET_DATA_VAL_M 0xFFFFFFFF

/* PCIE_AUX_RST_CTRL_WITH_PERST */
#define PCIE_AUX_RST_CTRL_WITH_PERST_EN_S 0
#define PCIE_AUX_RST_CTRL_WITH_PERST_EN_M 0x1

/* PCIE_AUX_HOST_TERM_CTRL */
#define PCIE_AUX_HOST_TERM_CTRL_MSTR_WR_TERM_S 0
#define PCIE_AUX_HOST_TERM_CTRL_MSTR_WR_TERM_M 0x1
#define PCIE_AUX_HOST_TERM_CTRL_MSTR_RD_TERM_S 1
#define PCIE_AUX_HOST_TERM_CTRL_MSTR_RD_TERM_M 0x2
#define PCIE_AUX_HOST_TERM_CTRL_MSTR_BRESP_TERM_S 2
#define PCIE_AUX_HOST_TERM_CTRL_MSTR_BRESP_TERM_M 0xC
#define PCIE_AUX_HOST_TERM_CTRL_MSTR_RRESP_TERM_S 4
#define PCIE_AUX_HOST_TERM_CTRL_MSTR_RRESP_TERM_M 0x30
#define PCIE_AUX_HOST_TERM_CTRL_ELBI_WR_TERM_S 6
#define PCIE_AUX_HOST_TERM_CTRL_ELBI_WR_TERM_M 0x40
#define PCIE_AUX_HOST_TERM_CTRL_ELBI_RD_TERM_S 7
#define PCIE_AUX_HOST_TERM_CTRL_ELBI_RD_TERM_M 0x80
#define PCIE_AUX_HOST_TERM_CTRL_ELBI_BRESP_TERM_S 8
#define PCIE_AUX_HOST_TERM_CTRL_ELBI_BRESP_TERM_M 0x300
#define PCIE_AUX_HOST_TERM_CTRL_ELBI_RRESP_TERM_S 10
#define PCIE_AUX_HOST_TERM_CTRL_ELBI_RRESP_TERM_M 0xC00

/* PCIE_AUX_ECO_INTR */
#define PCIE_AUX_ECO_INTR_IND_S 0
#define PCIE_AUX_ECO_INTR_IND_M 0x1

/* PCIE_AUX_ECO_INTR_MASK */
#define PCIE_AUX_ECO_INTR_MASK_VAL_S 0
#define PCIE_AUX_ECO_INTR_MASK_VAL_M 0x1

/* PCIE_AUX_BOOT_TERM_EN */
#define PCIE_AUX_BOOT_TERM_EN_VAL_S 0
#define PCIE_AUX_BOOT_TERM_EN_VAL_M 0x1

/* PCIE_AUX_BOOT_TERM_CLR */
#define PCIE_AUX_BOOT_TERM_CLR_CLR_S 0
#define PCIE_AUX_BOOT_TERM_CLR_CLR_M 0x1

#endif /* ASIC_REG_PCIE_AUX_MASKS_H_ */
