/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PDMA_CH_B_MASKS_H_
#define ASIC_REG_PDMA_CH_B_MASKS_H_

/*
 *****************************************
 *   PDMA_CH_B
 *   (Prototype: PDMA_CH_B)
 *****************************************
 */

/* PDMA_CH_B_HBW_AXCACHE */
#define PDMA_CH_B_HBW_AXCACHE_RD_S 0
#define PDMA_CH_B_HBW_AXCACHE_RD_M 0xF
#define PDMA_CH_B_HBW_AXCACHE_WR_S 4
#define PDMA_CH_B_HBW_AXCACHE_WR_M 0xF0

/* PDMA_CH_B_LBW_AXCACHE */
#define PDMA_CH_B_LBW_AXCACHE_RD_S 0
#define PDMA_CH_B_LBW_AXCACHE_RD_M 0xF
#define PDMA_CH_B_LBW_AXCACHE_WR_S 4
#define PDMA_CH_B_LBW_AXCACHE_WR_M 0xF0

/* PDMA_CH_B_PROT_PRIVLG */
#define PDMA_CH_B_PROT_PRIVLG_VAL_S 0
#define PDMA_CH_B_PROT_PRIVLG_VAL_M 0x1

/* PDMA_CH_B_PROT_SECURE */
#define PDMA_CH_B_PROT_SECURE_VAL_S 0
#define PDMA_CH_B_PROT_SECURE_VAL_M 0x1

/* PDMA_CH_B_ECMPLTN_Q_AXCACHE */
#define PDMA_CH_B_ECMPLTN_Q_AXCACHE_WR_S 0
#define PDMA_CH_B_ECMPLTN_Q_AXCACHE_WR_M 0xF

/* PDMA_CH_B_ECMPLTN_Q_PROT_PRIVLG */
#define PDMA_CH_B_ECMPLTN_Q_PROT_PRIVLG_VAL_S 0
#define PDMA_CH_B_ECMPLTN_Q_PROT_PRIVLG_VAL_M 0x1

/* PDMA_CH_B_ECMPLTN_Q_PROT_SECURE */
#define PDMA_CH_B_ECMPLTN_Q_PROT_SECURE_VAL_S 0
#define PDMA_CH_B_ECMPLTN_Q_PROT_SECURE_VAL_M 0x1

/* PDMA_CH_B_ERR_ENABLE */
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_HBW_RD_RSP_ERR_S 0
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_HBW_RD_RSP_ERR_M 0x1
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_HBW_RD_RSP_ERR_S 1
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_HBW_RD_RSP_ERR_M 0x2
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENGINE_TIMEOUT_S 2
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENGINE_TIMEOUT_M 0x4
#define PDMA_CH_B_ERR_ENABLE_EN_STALL_ENGINE_TIMEOUT_S 3
#define PDMA_CH_B_ERR_ENABLE_EN_STALL_ENGINE_TIMEOUT_M 0x8
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_LBW_RD_RSP_ERR_S 4
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_LBW_RD_RSP_ERR_M 0x10
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_LBW_RD_RSP_ERR_S 5
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_LBW_RD_RSP_ERR_M 0x20
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_HBW_WR_RSP_ERR_S 6
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_HBW_WR_RSP_ERR_M 0x40
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_HBW_WR_RSP_ERR_S 7
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_HBW_WR_RSP_ERR_M 0x80
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_LBW_WR_RSP_ERR_S 8
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_LBW_WR_RSP_ERR_M 0x100
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_LBW_WR_RSP_ERR_S 9
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_LBW_WR_RSP_ERR_M 0x200
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_MSG_WR_ERR_S 10
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_MSG_WR_ERR_M 0x400
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_MSG_WR_ERR_S 11
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_MSG_WR_ERR_M 0x800
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_NAN_DETECT_S 12
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_NAN_DETECT_M 0x1000
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_NAN_DETECT_S 13
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_NAN_DETECT_M 0x2000
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_INF_DETECT_S 14
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_INF_DETECT_M 0x4000
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_INF_DETECT_S 15
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_INF_DETECT_M 0x8000
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_LBW_CH_NUM_EXCEED_S 16
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_LBW_CH_NUM_EXCEED_M 0x10000
#define PDMA_CH_B_ERR_ENABLE_EN_STL_LBW_CH_NUM_EXCEED_S 17
#define PDMA_CH_B_ERR_ENABLE_EN_STL_LBW_CH_NUM_EXCEED_M 0x20000
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_SRC_RANGE_ERR_S 18
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_SRC_RANGE_ERR_M 0x40000
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_SRC_RANGE_ERR_S 19
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_SRC_RANGE_ERR_M 0x80000
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_DST_RANGE_ERR_S 20
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_ENG_DST_RANGE_ERR_M 0x100000
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_DST_RANGE_ERR_S 21
#define PDMA_CH_B_ERR_ENABLE_EN_STL_ENG_DST_RANGE_ERR_M 0x200000
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_DESC_OVF_ERR_S 22
#define PDMA_CH_B_ERR_ENABLE_EN_MSG_DESC_OVF_ERR_M 0x400000
#define PDMA_CH_B_ERR_ENABLE_EN_STL_DESC_OVF_ERR_S 23
#define PDMA_CH_B_ERR_ENABLE_EN_STL_DESC_OVF_ERR_M 0x800000

/* PDMA_CH_B_ERR_STATUS */
#define PDMA_CH_B_ERR_STATUS_ENG_HBW_RD_RSP_ERR_S 0
#define PDMA_CH_B_ERR_STATUS_ENG_HBW_RD_RSP_ERR_M 0x1
#define PDMA_CH_B_ERR_STATUS_ENG_TIMEOUT_ERR_S 1
#define PDMA_CH_B_ERR_STATUS_ENG_TIMEOUT_ERR_M 0x2
#define PDMA_CH_B_ERR_STATUS_ENG_LBW_RD_RSP_ERR_S 2
#define PDMA_CH_B_ERR_STATUS_ENG_LBW_RD_RSP_ERR_M 0x4
#define PDMA_CH_B_ERR_STATUS_ENG_HBW_WR_RSP_ERR_S 3
#define PDMA_CH_B_ERR_STATUS_ENG_HBW_WR_RSP_ERR_M 0x8
#define PDMA_CH_B_ERR_STATUS_ENG_LBW_WR_RSP_ERR_S 4
#define PDMA_CH_B_ERR_STATUS_ENG_LBW_WR_RSP_ERR_M 0x10
#define PDMA_CH_B_ERR_STATUS_ENG_MSG_WR_ERR_S 5
#define PDMA_CH_B_ERR_STATUS_ENG_MSG_WR_ERR_M 0x20
#define PDMA_CH_B_ERR_STATUS_ENG_NAN_DET_S 6
#define PDMA_CH_B_ERR_STATUS_ENG_NAN_DET_M 0x40
#define PDMA_CH_B_ERR_STATUS_ENG_INF_DET_S 7
#define PDMA_CH_B_ERR_STATUS_ENG_INF_DET_M 0x80
#define PDMA_CH_B_ERR_STATUS_ENG_M_INF_DET_S 8
#define PDMA_CH_B_ERR_STATUS_ENG_M_INF_DET_M 0x100
#define PDMA_CH_B_ERR_STATUS_LBW_CHN_NUM_EXC_S 9
#define PDMA_CH_B_ERR_STATUS_LBW_CHN_NUM_EXC_M 0x200
#define PDMA_CH_B_ERR_STATUS_SRC_RANGE_ERR_S 10
#define PDMA_CH_B_ERR_STATUS_SRC_RANGE_ERR_M 0x400
#define PDMA_CH_B_ERR_STATUS_SRC_NAN_DET_S 11
#define PDMA_CH_B_ERR_STATUS_SRC_NAN_DET_M 0x800
#define PDMA_CH_B_ERR_STATUS_SRC_INF_DET_S 12
#define PDMA_CH_B_ERR_STATUS_SRC_INF_DET_M 0x1000
#define PDMA_CH_B_ERR_STATUS_SRC_M_INF_DET_S 13
#define PDMA_CH_B_ERR_STATUS_SRC_M_INF_DET_M 0x2000
#define PDMA_CH_B_ERR_STATUS_DST_RANGE_ERR_S 14
#define PDMA_CH_B_ERR_STATUS_DST_RANGE_ERR_M 0x4000
#define PDMA_CH_B_ERR_STATUS_DST_NAN_DET_S 15
#define PDMA_CH_B_ERR_STATUS_DST_NAN_DET_M 0x8000
#define PDMA_CH_B_ERR_STATUS_DST_INF_DET_S 16
#define PDMA_CH_B_ERR_STATUS_DST_INF_DET_M 0x10000
#define PDMA_CH_B_ERR_STATUS_DST_M_INF_DET_S 17
#define PDMA_CH_B_ERR_STATUS_DST_M_INF_DET_M 0x20000
#define PDMA_CH_B_ERR_STATUS_DESC_OVF_S 18
#define PDMA_CH_B_ERR_STATUS_DESC_OVF_M 0x40000
#define PDMA_CH_B_ERR_STATUS_VALID_S 31
#define PDMA_CH_B_ERR_STATUS_VALID_M 0x80000000

/* PDMA_CH_B_ERR_CTX_ID */
#define PDMA_CH_B_ERR_CTX_ID_VAL_S 0
#define PDMA_CH_B_ERR_CTX_ID_VAL_M 0xFFFFFFFF

/* PDMA_CH_B_ERR_MSG_ADDR_LO */
#define PDMA_CH_B_ERR_MSG_ADDR_LO_VAL_S 0
#define PDMA_CH_B_ERR_MSG_ADDR_LO_VAL_M 0xFFFFFFFF

/* PDMA_CH_B_ERR_MSG_ADDR_HI */
#define PDMA_CH_B_ERR_MSG_ADDR_HI_VAL_S 0
#define PDMA_CH_B_ERR_MSG_ADDR_HI_VAL_M 0xFFFFFFFF

/* PDMA_CH_B_IDLE_IND_MASK */
#define PDMA_CH_B_IDLE_IND_MASK_DESC_S 0
#define PDMA_CH_B_IDLE_IND_MASK_DESC_M 0x1
#define PDMA_CH_B_IDLE_IND_MASK_COMP_S 1
#define PDMA_CH_B_IDLE_IND_MASK_COMP_M 0x2
#define PDMA_CH_B_IDLE_IND_MASK_INSTAGE_S 2
#define PDMA_CH_B_IDLE_IND_MASK_INSTAGE_M 0x4
#define PDMA_CH_B_IDLE_IND_MASK_CORE_S 3
#define PDMA_CH_B_IDLE_IND_MASK_CORE_M 0x8

/* PDMA_CH_B_CH_PRIORITY */
#define PDMA_CH_B_CH_PRIORITY_VAL_S 0
#define PDMA_CH_B_CH_PRIORITY_VAL_M 0x7

/* PDMA_CH_B_CH_LBW */
#define PDMA_CH_B_CH_LBW_VAL_S 0
#define PDMA_CH_B_CH_LBW_VAL_M 0x1

/* PDMA_CH_B_CFG */
#define PDMA_CH_B_CFG_HALT_S 0
#define PDMA_CH_B_CFG_HALT_M 0x1
#define PDMA_CH_B_CFG_FLUSH_S 1
#define PDMA_CH_B_CFG_FLUSH_M 0x2

/* PDMA_CH_B_STS */
#define PDMA_CH_B_STS_IS_BUSY_S 0
#define PDMA_CH_B_STS_IS_BUSY_M 0x1
#define PDMA_CH_B_STS_IS_HALT_S 1
#define PDMA_CH_B_STS_IS_HALT_M 0x2

/* PDMA_CH_B_CFG1 */
#define PDMA_CH_B_CFG1_STOP_ON_ERR_S 0
#define PDMA_CH_B_CFG1_STOP_ON_ERR_M 0x1

/* PDMA_CH_B_ERR_MSG_WDATA */
#define PDMA_CH_B_ERR_MSG_WDATA_VAL_S 0
#define PDMA_CH_B_ERR_MSG_WDATA_VAL_M 0xFFFFFFFF

/* PDMA_CH_B_DBG_STS */
#define PDMA_CH_B_DBG_STS_GSKT_EMPTY_S 0
#define PDMA_CH_B_DBG_STS_GSKT_EMPTY_M 0x1
#define PDMA_CH_B_DBG_STS_GSKT_FULL_S 1
#define PDMA_CH_B_DBG_STS_GSKT_FULL_M 0x2
#define PDMA_CH_B_DBG_STS_TE_CH_BUSY_S 2
#define PDMA_CH_B_DBG_STS_TE_CH_BUSY_M 0x4
#define PDMA_CH_B_DBG_STS_WR_COMP_FIFO_EMPTY_S 3
#define PDMA_CH_B_DBG_STS_WR_COMP_FIFO_EMPTY_M 0x8
#define PDMA_CH_B_DBG_STS_WR_COMP_FIFO_FULL_S 4
#define PDMA_CH_B_DBG_STS_WR_COMP_FIFO_FULL_M 0x10
#define PDMA_CH_B_DBG_STS_SRC_DESC_FIFO_EMPTY_S 5
#define PDMA_CH_B_DBG_STS_SRC_DESC_FIFO_EMPTY_M 0x20
#define PDMA_CH_B_DBG_STS_SRC_DESC_FIFO_FULL_S 6
#define PDMA_CH_B_DBG_STS_SRC_DESC_FIFO_FULL_M 0x40
#define PDMA_CH_B_DBG_STS_INSTAGE_FULL_S 7
#define PDMA_CH_B_DBG_STS_INSTAGE_FULL_M 0x80
#define PDMA_CH_B_DBG_STS_INSTAGE_EMPTY_S 8
#define PDMA_CH_B_DBG_STS_INSTAGE_EMPTY_M 0x100
#define PDMA_CH_B_DBG_STS_RD_AGU_CS_S 9
#define PDMA_CH_B_DBG_STS_RD_AGU_CS_M 0x200
#define PDMA_CH_B_DBG_STS_WR_AGU_CS_S 10
#define PDMA_CH_B_DBG_STS_WR_AGU_CS_M 0x400
#define PDMA_CH_B_DBG_STS_CORE_IDLE_STS_S 11
#define PDMA_CH_B_DBG_STS_CORE_IDLE_STS_M 0x800
#define PDMA_CH_B_DBG_STS_DESC_CNT_STS_S 12
#define PDMA_CH_B_DBG_STS_DESC_CNT_STS_M 0x1F000
#define PDMA_CH_B_DBG_STS_COMP_CNT_STS_S 17
#define PDMA_CH_B_DBG_STS_COMP_CNT_STS_M 0x3E0000
#define PDMA_CH_B_DBG_STS_WR_FIFO_FULL_S 22
#define PDMA_CH_B_DBG_STS_WR_FIFO_FULL_M 0x400000

/* PDMA_CH_B_STS_RD_CTX_SEL */
#define PDMA_CH_B_STS_RD_CTX_SEL_VAL_S 0
#define PDMA_CH_B_STS_RD_CTX_SEL_VAL_M 0x7
#define PDMA_CH_B_STS_RD_CTX_SEL_STRIDE_S 8
#define PDMA_CH_B_STS_RD_CTX_SEL_STRIDE_M 0x100

/* PDMA_CH_B_STS_RD_CTX_SIZE */
#define PDMA_CH_B_STS_RD_CTX_SIZE_VAL_S 0
#define PDMA_CH_B_STS_RD_CTX_SIZE_VAL_M 0xFFFFFFFF

/* PDMA_CH_B_STS_RD_CTX_BASE_LO */
#define PDMA_CH_B_STS_RD_CTX_BASE_LO_VAL_S 0
#define PDMA_CH_B_STS_RD_CTX_BASE_LO_VAL_M 0xFFFFFFFF

/* PDMA_CH_B_STS_RD_CTX_BASE_HI */
#define PDMA_CH_B_STS_RD_CTX_BASE_HI_VAL_S 0
#define PDMA_CH_B_STS_RD_CTX_BASE_HI_VAL_M 0xFFFFFFFF

/* PDMA_CH_B_STS_RD_CTX_ID */
#define PDMA_CH_B_STS_RD_CTX_ID_VAL_S 0
#define PDMA_CH_B_STS_RD_CTX_ID_VAL_M 0xFFFFFFFF

/* PDMA_CH_B_STS_WR_CTX_SEL */
#define PDMA_CH_B_STS_WR_CTX_SEL_VAL_S 0
#define PDMA_CH_B_STS_WR_CTX_SEL_VAL_M 0x7
#define PDMA_CH_B_STS_WR_CTX_SEL_STRIDE_S 8
#define PDMA_CH_B_STS_WR_CTX_SEL_STRIDE_M 0x100

/* PDMA_CH_B_STS_WR_CTX_SIZE */
#define PDMA_CH_B_STS_WR_CTX_SIZE_VAL_S 0
#define PDMA_CH_B_STS_WR_CTX_SIZE_VAL_M 0xFFFFFFFF

/* PDMA_CH_B_STS_WR_CTX_BASE_LO */
#define PDMA_CH_B_STS_WR_CTX_BASE_LO_VAL_S 0
#define PDMA_CH_B_STS_WR_CTX_BASE_LO_VAL_M 0xFFFFFFFF

/* PDMA_CH_B_STS_WR_CTX_BASE_HI */
#define PDMA_CH_B_STS_WR_CTX_BASE_HI_VAL_S 0
#define PDMA_CH_B_STS_WR_CTX_BASE_HI_VAL_M 0xFFFFFFFF

/* PDMA_CH_B_STS_WR_CTX_ID */
#define PDMA_CH_B_STS_WR_CTX_ID_VAL_S 0
#define PDMA_CH_B_STS_WR_CTX_ID_VAL_M 0xFFFFFFFF

/* PDMA_CH_B_PWRLP_STS0 */
#define PDMA_CH_B_PWRLP_STS0_RLVL_S 0
#define PDMA_CH_B_PWRLP_STS0_RLVL_M 0xFF
#define PDMA_CH_B_PWRLP_STS0_WLVL_S 8
#define PDMA_CH_B_PWRLP_STS0_WLVL_M 0xFF00
#define PDMA_CH_B_PWRLP_STS0_RCNT_S 16
#define PDMA_CH_B_PWRLP_STS0_RCNT_M 0xFF0000
#define PDMA_CH_B_PWRLP_STS0_WCNT_S 24
#define PDMA_CH_B_PWRLP_STS0_WCNT_M 0xFF000000

/* PDMA_CH_B_PWRLP_STS1 */
#define PDMA_CH_B_PWRLP_STS1_RFULL_S 0
#define PDMA_CH_B_PWRLP_STS1_RFULL_M 0x1
#define PDMA_CH_B_PWRLP_STS1_WFULL_S 1
#define PDMA_CH_B_PWRLP_STS1_WFULL_M 0x2

/* PDMA_CH_B_ERR_INT_MASK */
#define PDMA_CH_B_ERR_INT_MASK_ENG_HBW_RD_RSP_ERR_S 0
#define PDMA_CH_B_ERR_INT_MASK_ENG_HBW_RD_RSP_ERR_M 0x1
#define PDMA_CH_B_ERR_INT_MASK_ENG_TIMEOUT_ERR_S 1
#define PDMA_CH_B_ERR_INT_MASK_ENG_TIMEOUT_ERR_M 0x2
#define PDMA_CH_B_ERR_INT_MASK_ENG_LBW_RD_RSP_ERR_S 2
#define PDMA_CH_B_ERR_INT_MASK_ENG_LBW_RD_RSP_ERR_M 0x4
#define PDMA_CH_B_ERR_INT_MASK_ENG_HBW_WR_RSP_ERR_S 3
#define PDMA_CH_B_ERR_INT_MASK_ENG_HBW_WR_RSP_ERR_M 0x8
#define PDMA_CH_B_ERR_INT_MASK_ENG_LBW_WR_RSP_ERR_S 4
#define PDMA_CH_B_ERR_INT_MASK_ENG_LBW_WR_RSP_ERR_M 0x10
#define PDMA_CH_B_ERR_INT_MASK_ENG_MSG_WR_ERR_S 5
#define PDMA_CH_B_ERR_INT_MASK_ENG_MSG_WR_ERR_M 0x20
#define PDMA_CH_B_ERR_INT_MASK_ENG_NAN_DET_S 6
#define PDMA_CH_B_ERR_INT_MASK_ENG_NAN_DET_M 0x40
#define PDMA_CH_B_ERR_INT_MASK_ENG_INF_DET_S 7
#define PDMA_CH_B_ERR_INT_MASK_ENG_INF_DET_M 0x80
#define PDMA_CH_B_ERR_INT_MASK_ENG_M_INF_DET_S 8
#define PDMA_CH_B_ERR_INT_MASK_ENG_M_INF_DET_M 0x100
#define PDMA_CH_B_ERR_INT_MASK_LBW_CHN_NUM_EXC_S 9
#define PDMA_CH_B_ERR_INT_MASK_LBW_CHN_NUM_EXC_M 0x200
#define PDMA_CH_B_ERR_INT_MASK_SRC_RANGE_ERR_S 10
#define PDMA_CH_B_ERR_INT_MASK_SRC_RANGE_ERR_M 0x400
#define PDMA_CH_B_ERR_INT_MASK_SRC_NAN_DET_S 11
#define PDMA_CH_B_ERR_INT_MASK_SRC_NAN_DET_M 0x800
#define PDMA_CH_B_ERR_INT_MASK_SRC_INF_DET_S 12
#define PDMA_CH_B_ERR_INT_MASK_SRC_INF_DET_M 0x1000
#define PDMA_CH_B_ERR_INT_MASK_SRC_M_INF_DET_S 13
#define PDMA_CH_B_ERR_INT_MASK_SRC_M_INF_DET_M 0x2000
#define PDMA_CH_B_ERR_INT_MASK_DST_RANGE_ERR_S 14
#define PDMA_CH_B_ERR_INT_MASK_DST_RANGE_ERR_M 0x4000
#define PDMA_CH_B_ERR_INT_MASK_DST_NAN_DET_S 15
#define PDMA_CH_B_ERR_INT_MASK_DST_NAN_DET_M 0x8000
#define PDMA_CH_B_ERR_INT_MASK_DST_INF_DET_S 16
#define PDMA_CH_B_ERR_INT_MASK_DST_INF_DET_M 0x10000
#define PDMA_CH_B_ERR_INT_MASK_DST_M_INF_DET_S 17
#define PDMA_CH_B_ERR_INT_MASK_DST_M_INF_DET_M 0x20000
#define PDMA_CH_B_ERR_INT_MASK_DESC_OVF_S 18
#define PDMA_CH_B_ERR_INT_MASK_DESC_OVF_M 0x40000

/* PDMA_CH_B_CFG_HBW_RSB_DATA_OCCUPANCY */
#define PDMA_CH_B_CFG_HBW_RSB_DATA_OCCUPANCY_VAL_S 0
#define PDMA_CH_B_CFG_HBW_RSB_DATA_OCCUPANCY_VAL_M 0xFFFFFFFF

/* PDMA_CH_B_CFG_HBW_RSB_MD_OCCUPANCY */
#define PDMA_CH_B_CFG_HBW_RSB_MD_OCCUPANCY_VAL_S 0
#define PDMA_CH_B_CFG_HBW_RSB_MD_OCCUPANCY_VAL_M 0xFFFFFFFF

/* PDMA_CH_B_MAX_WR_COMP_INFLIGHT */
#define PDMA_CH_B_MAX_WR_COMP_INFLIGHT_VAL_S 0
#define PDMA_CH_B_MAX_WR_COMP_INFLIGHT_VAL_M 0x7F

#endif /* ASIC_REG_PDMA_CH_B_MASKS_H_ */
