/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PSOC_BOOT_CONF_REGS_H_
#define ASIC_REG_PSOC_BOOT_CONF_REGS_H_

/*
 *****************************************
 *   PSOC_BOOT_CONF
 *   (Prototype: PSOC_BOOT_CONF)
 *****************************************
 */

#define mmPSOC_BOOT_CONF_BTM_RST_FIFO_CTRL 0x0

#define mmPSOC_BOOT_CONF_BTM_RST_FIFO_STS 0x4

#define mmPSOC_BOOT_CONF_BTM_RST_FIFO_HEAD 0x8

#define mmPSOC_BOOT_CONF_BOOT_STRAP_PINS_L 0x20

#define mmPSOC_BOOT_CONF_BOOT_STRAP_PINS_H 0x24

#define mmPSOC_BOOT_CONF_FLR_RST 0x30

#define mmPSOC_BOOT_CONF_FW_RST 0x34

#define mmPSOC_BOOT_CONF_MNL_RST 0x38

#define mmPSOC_BOOT_CONF_ECC_DERR_RST 0x3C

#define mmPSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART 0x44

#define mmPSOC_BOOT_CONF_SECURE_GEN_CNT_CTRL 0x50

#define mmPSOC_BOOT_CONF_SECURE_GEN_CNT_STS 0x54

#define mmPSOC_BOOT_CONF_BTM_GEN_CNT_CTRL 0x58

#define mmPSOC_BOOT_CONF_BTM_GEN_CNT_STS 0x5C

#define mmPSOC_BOOT_CONF_BOOT_GLOBAL_WD_CFG 0x60

#define mmPSOC_BOOT_CONF_BOOT_GLOBAL_WD_CTRL 0x64

#define mmPSOC_BOOT_CONF_BOOT_GLOBAL_WD_STS 0x68

#define mmPSOC_BOOT_CONF_BOOT_GLOBAL_WD_ACTION 0x6C

#define mmPSOC_BOOT_CONF_BOOT_GLOBAL_WD_INFO 0x70

#define mmPSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART 0x74

#define mmPSOC_BOOT_CONF_BTM_EFUSE_RD_0 0x80

#define mmPSOC_BOOT_CONF_BTM_EFUSE_RD_1 0x84

#define mmPSOC_BOOT_CONF_COLD_RST_REG_0 0x100

#define mmPSOC_BOOT_CONF_COLD_RST_REG_1 0x104

#define mmPSOC_BOOT_CONF_COLD_RST_REG_2 0x108

#define mmPSOC_BOOT_CONF_COLD_RST_REG_3 0x10C

#define mmPSOC_BOOT_CONF_COLD_RST_REG_4 0x110

#define mmPSOC_BOOT_CONF_COLD_RST_REG_5 0x114

#define mmPSOC_BOOT_CONF_COLD_RST_REG_6 0x118

#define mmPSOC_BOOT_CONF_COLD_RST_REG_7 0x11C

#define mmPSOC_BOOT_CONF_COLD_RST_REG_8 0x120

#define mmPSOC_BOOT_CONF_COLD_RST_REG_9 0x124

#define mmPSOC_BOOT_CONF_COLD_RST_REG_10 0x128

#define mmPSOC_BOOT_CONF_COLD_RST_REG_11 0x12C

#define mmPSOC_BOOT_CONF_COLD_RST_REG_12 0x130

#define mmPSOC_BOOT_CONF_COLD_RST_REG_13 0x134

#define mmPSOC_BOOT_CONF_COLD_RST_REG_14 0x138

#define mmPSOC_BOOT_CONF_COLD_RST_REG_15 0x13C

#define mmPSOC_BOOT_CONF_COLD_RST_REG_16 0x140

#define mmPSOC_BOOT_CONF_COLD_RST_REG_17 0x144

#define mmPSOC_BOOT_CONF_COLD_RST_REG_18 0x148

#define mmPSOC_BOOT_CONF_COLD_RST_REG_19 0x14C

#define mmPSOC_BOOT_CONF_COLD_RST_REG_20 0x150

#define mmPSOC_BOOT_CONF_COLD_RST_REG_21 0x154

#define mmPSOC_BOOT_CONF_COLD_RST_REG_22 0x158

#define mmPSOC_BOOT_CONF_COLD_RST_REG_23 0x15C

#define mmPSOC_BOOT_CONF_COLD_RST_REG_24 0x160

#define mmPSOC_BOOT_CONF_COLD_RST_REG_25 0x164

#define mmPSOC_BOOT_CONF_COLD_RST_REG_26 0x168

#define mmPSOC_BOOT_CONF_COLD_RST_REG_27 0x16C

#define mmPSOC_BOOT_CONF_COLD_RST_REG_28 0x170

#define mmPSOC_BOOT_CONF_COLD_RST_REG_29 0x174

#define mmPSOC_BOOT_CONF_COLD_RST_REG_30 0x178

#define mmPSOC_BOOT_CONF_COLD_RST_REG_31 0x17C

#define mmPSOC_BOOT_CONF_TPC_ISO_L 0x700

#define mmPSOC_BOOT_CONF_TPC_ISO_H 0x704

#define mmPSOC_BOOT_CONF_VDEC_ISO 0x708

#define mmPSOC_BOOT_CONF_HBM_ISO 0x70C

#define mmPSOC_BOOT_CONF_MME_REDUN_HDCORE0 0x710

#define mmPSOC_BOOT_CONF_MME_REDUN_HDCORE1 0x714

#define mmPSOC_BOOT_CONF_MME_REDUN_HDCORE2 0x718

#define mmPSOC_BOOT_CONF_MME_REDUN_HDCORE3 0x71C

#define mmPSOC_BOOT_CONF_ROT_ISO 0x720

#define mmPSOC_BOOT_CONF_PDMA_ISO 0x724

#define mmPSOC_BOOT_CONF_SM_ISO 0x728

#define mmPSOC_BOOT_CONF_ARC_FARM_ISO 0x72C

#define mmPSOC_BOOT_CONF_NIC_ISO 0x730

#define mmPSOC_BOOT_CONF_MME_ISO 0x734

#define mmPSOC_BOOT_CONF_EDMA_ISO 0x738

#define mmPSOC_BOOT_CONF_HDCORE_HBM_CONNECT 0x740

#define mmPSOC_BOOT_CONF_TPC_SPARE_CONNECT 0x744

#define mmPSOC_BOOT_CONF_ROT_CLS 0x748

#define mmPSOC_BOOT_CONF_D0_PIF_ISO 0x750

#define mmPSOC_BOOT_CONF_D1_PIF_ISO 0x754

#endif /* ASIC_REG_PSOC_BOOT_CONF_REGS_H_ */
