/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PSOC_SECURITY_REGS_H_
#define ASIC_REG_PSOC_SECURITY_REGS_H_

/*
 *****************************************
 *   PSOC_SECURITY
 *   (Prototype: PSOC_SECURITY)
 *****************************************
 */

#define mmPSOC_SECURITY_FW_RST 0x0

#define mmPSOC_SECURITY_MIN_FW_VERSION 0x10

#define mmPSOC_SECURITY_PREV_MIN_FW_VERSION 0x14

#define mmPSOC_SECURITY_CURRENT_FW_VERSION 0x18

#define mmPSOC_SECURITY_KEU_USED 0x20

#define mmPSOC_SECURITY_PRI_IMG_STATUS 0x24

#define mmPSOC_SECURITY_SEC_IMG_STATUS 0x28

#define mmPSOC_SECURITY_PRI_IMG_FW_VER 0x2C

#define mmPSOC_SECURITY_SEC_IMG_FW_VER 0x30

#define mmPSOC_SECURITY_STATUS 0x40

#define mmPSOC_SECURITY_KEY_REVOKE 0xF0

#define mmPSOC_SECURITY_PUBLIC_KEY_0_0 0x100

#define mmPSOC_SECURITY_PUBLIC_KEY_0_1 0x104

#define mmPSOC_SECURITY_PUBLIC_KEY_0_2 0x108

#define mmPSOC_SECURITY_PUBLIC_KEY_0_3 0x10C

#define mmPSOC_SECURITY_PUBLIC_KEY_0_4 0x110

#define mmPSOC_SECURITY_PUBLIC_KEY_0_5 0x114

#define mmPSOC_SECURITY_PUBLIC_KEY_0_6 0x118

#define mmPSOC_SECURITY_PUBLIC_KEY_0_7 0x11C

#define mmPSOC_SECURITY_PUBLIC_KEY_0_8 0x120

#define mmPSOC_SECURITY_PUBLIC_KEY_0_9 0x124

#define mmPSOC_SECURITY_PUBLIC_KEY_0_10 0x128

#define mmPSOC_SECURITY_PUBLIC_KEY_0_11 0x12C

#define mmPSOC_SECURITY_PUBLIC_KEY_1_0 0x130

#define mmPSOC_SECURITY_PUBLIC_KEY_1_1 0x134

#define mmPSOC_SECURITY_PUBLIC_KEY_1_2 0x138

#define mmPSOC_SECURITY_PUBLIC_KEY_1_3 0x13C

#define mmPSOC_SECURITY_PUBLIC_KEY_1_4 0x140

#define mmPSOC_SECURITY_PUBLIC_KEY_1_5 0x144

#define mmPSOC_SECURITY_PUBLIC_KEY_1_6 0x148

#define mmPSOC_SECURITY_PUBLIC_KEY_1_7 0x14C

#define mmPSOC_SECURITY_PUBLIC_KEY_1_8 0x150

#define mmPSOC_SECURITY_PUBLIC_KEY_1_9 0x154

#define mmPSOC_SECURITY_PUBLIC_KEY_1_10 0x158

#define mmPSOC_SECURITY_PUBLIC_KEY_1_11 0x15C

#define mmPSOC_SECURITY_PUBLIC_KEY_2_0 0x160

#define mmPSOC_SECURITY_PUBLIC_KEY_2_1 0x164

#define mmPSOC_SECURITY_PUBLIC_KEY_2_2 0x168

#define mmPSOC_SECURITY_PUBLIC_KEY_2_3 0x16C

#define mmPSOC_SECURITY_PUBLIC_KEY_2_4 0x170

#define mmPSOC_SECURITY_PUBLIC_KEY_2_5 0x174

#define mmPSOC_SECURITY_PUBLIC_KEY_2_6 0x178

#define mmPSOC_SECURITY_PUBLIC_KEY_2_7 0x17C

#define mmPSOC_SECURITY_PUBLIC_KEY_2_8 0x180

#define mmPSOC_SECURITY_PUBLIC_KEY_2_9 0x184

#define mmPSOC_SECURITY_PUBLIC_KEY_2_10 0x188

#define mmPSOC_SECURITY_PUBLIC_KEY_2_11 0x18C

#define mmPSOC_SECURITY_PUBLIC_KEY_3_0 0x190

#define mmPSOC_SECURITY_PUBLIC_KEY_3_1 0x194

#define mmPSOC_SECURITY_PUBLIC_KEY_3_2 0x198

#define mmPSOC_SECURITY_PUBLIC_KEY_3_3 0x19C

#define mmPSOC_SECURITY_PUBLIC_KEY_3_4 0x1A0

#define mmPSOC_SECURITY_PUBLIC_KEY_3_5 0x1A4

#define mmPSOC_SECURITY_PUBLIC_KEY_3_6 0x1A8

#define mmPSOC_SECURITY_PUBLIC_KEY_3_7 0x1AC

#define mmPSOC_SECURITY_PUBLIC_KEY_3_8 0x1B0

#define mmPSOC_SECURITY_PUBLIC_KEY_3_9 0x1B4

#define mmPSOC_SECURITY_PUBLIC_KEY_3_10 0x1B8

#define mmPSOC_SECURITY_PUBLIC_KEY_3_11 0x1BC

#define mmPSOC_SECURITY_PUBLIC_KEY_4_0 0x1C0

#define mmPSOC_SECURITY_PUBLIC_KEY_4_1 0x1C4

#define mmPSOC_SECURITY_PUBLIC_KEY_4_2 0x1C8

#define mmPSOC_SECURITY_PUBLIC_KEY_4_3 0x1CC

#define mmPSOC_SECURITY_PUBLIC_KEY_4_4 0x1D0

#define mmPSOC_SECURITY_PUBLIC_KEY_4_5 0x1D4

#define mmPSOC_SECURITY_PUBLIC_KEY_4_6 0x1D8

#define mmPSOC_SECURITY_PUBLIC_KEY_4_7 0x1DC

#define mmPSOC_SECURITY_PUBLIC_KEY_4_8 0x1E0

#define mmPSOC_SECURITY_PUBLIC_KEY_4_9 0x1E4

#define mmPSOC_SECURITY_PUBLIC_KEY_4_10 0x1E8

#define mmPSOC_SECURITY_PUBLIC_KEY_4_11 0x1EC

#define mmPSOC_SECURITY_SPARE_KEY_0 0x1F0

#define mmPSOC_SECURITY_SPARE_KEY_1 0x1F4

#define mmPSOC_SECURITY_SPARE_KEY_2 0x1F8

#define mmPSOC_SECURITY_SPARE_KEY_3 0x1FC

#define mmPSOC_SECURITY_SW_STATUS_0 0x200

#define mmPSOC_SECURITY_SW_STATUS_1 0x204

#define mmPSOC_SECURITY_SW_STATUS_2 0x208

#define mmPSOC_SECURITY_SW_STATUS_3 0x20C

#define mmPSOC_SECURITY_SW_STATUS_4 0x210

#define mmPSOC_SECURITY_SW_STATUS_5 0x214

#define mmPSOC_SECURITY_SW_STATUS_6 0x218

#define mmPSOC_SECURITY_SW_STATUS_7 0x21C

#endif /* ASIC_REG_PSOC_SECURITY_REGS_H_ */
