/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PSOC_BOOT_CONF_MASKS_H_
#define ASIC_REG_PSOC_BOOT_CONF_MASKS_H_

/*
 *****************************************
 *   PSOC_BOOT_CONF
 *   (Prototype: PSOC_BOOT_CONF)
 *****************************************
 */

/* PSOC_BOOT_CONF_BTM_RST_FIFO_CTRL */
#define PSOC_BOOT_CONF_BTM_RST_FIFO_CTRL_POP_S 0
#define PSOC_BOOT_CONF_BTM_RST_FIFO_CTRL_POP_M 0x1
#define PSOC_BOOT_CONF_BTM_RST_FIFO_CTRL_FLUSH_S 1
#define PSOC_BOOT_CONF_BTM_RST_FIFO_CTRL_FLUSH_M 0x2

/* PSOC_BOOT_CONF_BTM_RST_FIFO_STS */
#define PSOC_BOOT_CONF_BTM_RST_FIFO_STS_EMPTY_S 0
#define PSOC_BOOT_CONF_BTM_RST_FIFO_STS_EMPTY_M 0x1
#define PSOC_BOOT_CONF_BTM_RST_FIFO_STS_FULL_S 1
#define PSOC_BOOT_CONF_BTM_RST_FIFO_STS_FULL_M 0x2
#define PSOC_BOOT_CONF_BTM_RST_FIFO_STS_FILL_LEVEL_S 16
#define PSOC_BOOT_CONF_BTM_RST_FIFO_STS_FILL_LEVEL_M 0xFFFF0000

/* PSOC_BOOT_CONF_BTM_RST_FIFO_HEAD */
#define PSOC_BOOT_CONF_BTM_RST_FIFO_HEAD_VAL_S 0
#define PSOC_BOOT_CONF_BTM_RST_FIFO_HEAD_VAL_M 0xFFFFFFFF

/* PSOC_BOOT_CONF_BOOT_STRAP_PINS_L */
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_DUMP_DIS_S 0
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_DUMP_DIS_M 0x1
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_DUMP_SEL_S 1
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_DUMP_SEL_M 0xFFFE
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_DUMP_SEL_LSB_S 16
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_DUMP_SEL_LSB_M 0x1F0000
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_CPOL_S 21
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_CPOL_M 0x200000
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_CPHA_S 22
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_CPHA_M 0x400000
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_MEM_REPAIR_S 23
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_MEM_REPAIR_M 0x800000
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_EFUSE_OVERRIDE_S 24
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_EFUSE_OVERRIDE_M 0x1000000
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_SECURE_BOOT_ENABLE_S 25
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_SECURE_BOOT_ENABLE_M 0x2000000
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_CPU_PLL_CFG_S 26
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_CPU_PLL_CFG_M 0x4000000
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_BTL_ROM_EN_S 27
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_BTL_ROM_EN_M 0x8000000
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_BTL_DISABLE_S 28
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_BTL_DISABLE_M 0x10000000
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_REPAIR_DIV_S 29
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_REPAIR_DIV_M 0x20000000
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_RESERVED_S 30
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_L_RESERVED_M 0xC0000000

/* PSOC_BOOT_CONF_BOOT_STRAP_PINS_H */
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_H_MODULE_ID_S 0
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_H_MODULE_ID_M 0x1F
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_H_SRIS_S 5
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_H_SRIS_M 0x20
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_H_SRNS_S 6
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_H_SRNS_M 0x40
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_H_ADD_SSC_S 7
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_H_ADD_SSC_M 0x80
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_H_DIE_ID_S 8
#define PSOC_BOOT_CONF_BOOT_STRAP_PINS_H_DIE_ID_M 0x100

/* PSOC_BOOT_CONF_FLR_RST */
#define PSOC_BOOT_CONF_FLR_RST_MASK_S 0
#define PSOC_BOOT_CONF_FLR_RST_MASK_M 0x1

/* PSOC_BOOT_CONF_FW_RST */
#define PSOC_BOOT_CONF_FW_RST_MASK_S 0
#define PSOC_BOOT_CONF_FW_RST_MASK_M 0x1

/* PSOC_BOOT_CONF_MNL_RST */
#define PSOC_BOOT_CONF_MNL_RST_MASK_S 0
#define PSOC_BOOT_CONF_MNL_RST_MASK_M 0x1

/* PSOC_BOOT_CONF_ECC_DERR_RST */
#define PSOC_BOOT_CONF_ECC_DERR_RST_MASK_S 0
#define PSOC_BOOT_CONF_ECC_DERR_RST_MASK_M 0x1

/* PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART */
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_EN_S 0
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_EN_M 0x1
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_MNL_RST_EN_S 4
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_MNL_RST_EN_M 0x10
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_WD_RST_EN_S 5
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_WD_RST_EN_M 0x20
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_SW_RST_EN_S 6
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_SW_RST_EN_M 0x40
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_SOFT_RST_EN_S 7
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_SOFT_RST_EN_M 0x80
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_PRST_RST_EN_S 8
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_PRST_RST_EN_M 0x100
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_FLR_RST_EN_S 9
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_FLR_RST_EN_M 0x200
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_FW_RST_EN_S 10
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_FW_RST_EN_M 0x400
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_ECC_DERR_RST_EN_S 11
#define PSOC_BOOT_CONF_BTM_GRAD_RST_DONE_RESTART_ECC_DERR_RST_EN_M 0x800

/* PSOC_BOOT_CONF_SECURE_GEN_CNT_CTRL */
#define PSOC_BOOT_CONF_SECURE_GEN_CNT_CTRL_SET_VALUE_S 0
#define PSOC_BOOT_CONF_SECURE_GEN_CNT_CTRL_SET_VALUE_M 0x1F
#define PSOC_BOOT_CONF_SECURE_GEN_CNT_CTRL_SET_S 16
#define PSOC_BOOT_CONF_SECURE_GEN_CNT_CTRL_SET_M 0x10000
#define PSOC_BOOT_CONF_SECURE_GEN_CNT_CTRL_INC_S 17
#define PSOC_BOOT_CONF_SECURE_GEN_CNT_CTRL_INC_M 0x20000
#define PSOC_BOOT_CONF_SECURE_GEN_CNT_CTRL_DEC_S 18
#define PSOC_BOOT_CONF_SECURE_GEN_CNT_CTRL_DEC_M 0x40000
#define PSOC_BOOT_CONF_SECURE_GEN_CNT_CTRL_DIS_S 19
#define PSOC_BOOT_CONF_SECURE_GEN_CNT_CTRL_DIS_M 0x80000

/* PSOC_BOOT_CONF_SECURE_GEN_CNT_STS */
#define PSOC_BOOT_CONF_SECURE_GEN_CNT_STS_VAL_S 0
#define PSOC_BOOT_CONF_SECURE_GEN_CNT_STS_VAL_M 0x1F
#define PSOC_BOOT_CONF_SECURE_GEN_CNT_STS_ACTIVE_S 16
#define PSOC_BOOT_CONF_SECURE_GEN_CNT_STS_ACTIVE_M 0x10000

/* PSOC_BOOT_CONF_BTM_GEN_CNT_CTRL */
#define PSOC_BOOT_CONF_BTM_GEN_CNT_CTRL_SET_VALUE_S 0
#define PSOC_BOOT_CONF_BTM_GEN_CNT_CTRL_SET_VALUE_M 0xFFFF
#define PSOC_BOOT_CONF_BTM_GEN_CNT_CTRL_SET_S 16
#define PSOC_BOOT_CONF_BTM_GEN_CNT_CTRL_SET_M 0x10000
#define PSOC_BOOT_CONF_BTM_GEN_CNT_CTRL_INC_S 17
#define PSOC_BOOT_CONF_BTM_GEN_CNT_CTRL_INC_M 0x20000
#define PSOC_BOOT_CONF_BTM_GEN_CNT_CTRL_DEC_S 18
#define PSOC_BOOT_CONF_BTM_GEN_CNT_CTRL_DEC_M 0x40000
#define PSOC_BOOT_CONF_BTM_GEN_CNT_CTRL_DIS_S 19
#define PSOC_BOOT_CONF_BTM_GEN_CNT_CTRL_DIS_M 0x80000

/* PSOC_BOOT_CONF_BTM_GEN_CNT_STS */
#define PSOC_BOOT_CONF_BTM_GEN_CNT_STS_VAL_S 0
#define PSOC_BOOT_CONF_BTM_GEN_CNT_STS_VAL_M 0xFFFF
#define PSOC_BOOT_CONF_BTM_GEN_CNT_STS_ACTIVE_S 16
#define PSOC_BOOT_CONF_BTM_GEN_CNT_STS_ACTIVE_M 0x10000

/* PSOC_BOOT_CONF_BOOT_GLOBAL_WD_CFG */
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_CFG_VAL_S 0
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_CFG_VAL_M 0xFFFFFFF

/* PSOC_BOOT_CONF_BOOT_GLOBAL_WD_CTRL */
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_CTRL_SET_VALUE_S 0
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_CTRL_SET_VALUE_M 0xFFFFFFF
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_CTRL_SET_S 28
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_CTRL_SET_M 0x10000000
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_CTRL_DEC_S 29
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_CTRL_DEC_M 0x20000000
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_CTRL_INC_S 30
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_CTRL_INC_M 0x40000000
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_CTRL_DIS_S 31
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_CTRL_DIS_M 0x80000000

/* PSOC_BOOT_CONF_BOOT_GLOBAL_WD_STS */
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_STS_VAL_S 0
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_STS_VAL_M 0xFFFFFFF
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_STS_ACTIVE_S 28
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_STS_ACTIVE_M 0x10000000
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_STS_LAST_EXPR_S 29
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_STS_LAST_EXPR_M 0x20000000
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_STS_FIRST_EXPR_S 30
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_STS_FIRST_EXPR_M 0x40000000

/* PSOC_BOOT_CONF_BOOT_GLOBAL_WD_ACTION */
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_ACTION_NEXT_STATE_EN_S 0
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_ACTION_NEXT_STATE_EN_M 0x1
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_ACTION_NEXT_STATE_S 8
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_ACTION_NEXT_STATE_M 0xFF00

/* PSOC_BOOT_CONF_BOOT_GLOBAL_WD_INFO */
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_INFO_LAST_RST_SRC_S 0
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_INFO_LAST_RST_SRC_M 0xFF
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_INFO_LAST_BTM_FSM_STATE_S 8
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_INFO_LAST_BTM_FSM_STATE_M 0xFF00
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_INFO_FIRST_RST_SRC_S 16
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_INFO_FIRST_RST_SRC_M 0xFF0000
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_INFO_FIRST_BTM_FSM_STATE_S 24
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_INFO_FIRST_BTM_FSM_STATE_M 0xFF000000

/* PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART */
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_EN_S 0
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_EN_M 0x1
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_MNL_RST_EN_S 1
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_MNL_RST_EN_M 0x2
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_WD_RST_EN_S 2
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_WD_RST_EN_M 0x4
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_SW_RST_EN_S 3
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_SW_RST_EN_M 0x8
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_SOFT_RST_EN_S 4
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_SOFT_RST_EN_M 0x10
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_PRST_RST_EN_S 5
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_PRST_RST_EN_M 0x20
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_FLR_RST_EN_S 6
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_FLR_RST_EN_M 0x40
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_FW_RST_EN_S 7
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_FW_RST_EN_M 0x80
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_ECC_DERR_RST_EN_S 8
#define PSOC_BOOT_CONF_BOOT_GLOBAL_WD_RESTART_ECC_DERR_RST_EN_M 0x100

/* PSOC_BOOT_CONF_BTM_EFUSE_RD */
#define PSOC_BOOT_CONF_BTM_EFUSE_RD_VAL_S 0
#define PSOC_BOOT_CONF_BTM_EFUSE_RD_VAL_M 0xFFFFFFFF

/* PSOC_BOOT_CONF_COLD_RST_REG */
#define PSOC_BOOT_CONF_COLD_RST_REG_VAL_S 0
#define PSOC_BOOT_CONF_COLD_RST_REG_VAL_M 0xFFFFFFFF

/* PSOC_BOOT_CONF_TPC_ISO_L */
#define PSOC_BOOT_CONF_TPC_ISO_L_ISO_EN_S 0
#define PSOC_BOOT_CONF_TPC_ISO_L_ISO_EN_M 0xFFFFFFFF

/* PSOC_BOOT_CONF_TPC_ISO_H */
#define PSOC_BOOT_CONF_TPC_ISO_H_ISO_EN_S 0
#define PSOC_BOOT_CONF_TPC_ISO_H_ISO_EN_M 0xF

/* PSOC_BOOT_CONF_VDEC_ISO */
#define PSOC_BOOT_CONF_VDEC_ISO_ISO_EN_S 0
#define PSOC_BOOT_CONF_VDEC_ISO_ISO_EN_M 0xFF

/* PSOC_BOOT_CONF_HBM_ISO */
#define PSOC_BOOT_CONF_HBM_ISO_ISO_EN_S 0
#define PSOC_BOOT_CONF_HBM_ISO_ISO_EN_M 0xF

/* PSOC_BOOT_CONF_MME_REDUN_HDCORE0 */
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE0_MME0_S 0
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE0_MME0_M 0x3F
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE0_MME1_S 6
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE0_MME1_M 0xFC0

/* PSOC_BOOT_CONF_MME_REDUN_HDCORE1 */
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE1_MME0_S 0
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE1_MME0_M 0x3F
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE1_MME1_S 6
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE1_MME1_M 0xFC0

/* PSOC_BOOT_CONF_MME_REDUN_HDCORE2 */
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE2_MME0_S 0
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE2_MME0_M 0x3F
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE2_MME1_S 6
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE2_MME1_M 0xFC0

/* PSOC_BOOT_CONF_MME_REDUN_HDCORE3 */
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE3_MME0_S 0
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE3_MME0_M 0x3F
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE3_MME1_S 6
#define PSOC_BOOT_CONF_MME_REDUN_HDCORE3_MME1_M 0xFC0

/* PSOC_BOOT_CONF_ROT_ISO */
#define PSOC_BOOT_CONF_ROT_ISO_ISO_EN_S 0
#define PSOC_BOOT_CONF_ROT_ISO_ISO_EN_M 0xF

/* PSOC_BOOT_CONF_PDMA_ISO */
#define PSOC_BOOT_CONF_PDMA_ISO_ISO_EN_S 0
#define PSOC_BOOT_CONF_PDMA_ISO_ISO_EN_M 0x1

/* PSOC_BOOT_CONF_SM_ISO */
#define PSOC_BOOT_CONF_SM_ISO_ISO_EN_S 0
#define PSOC_BOOT_CONF_SM_ISO_ISO_EN_M 0xF

/* PSOC_BOOT_CONF_ARC_FARM_ISO */
#define PSOC_BOOT_CONF_ARC_FARM_ISO_ISO_EN_S 0
#define PSOC_BOOT_CONF_ARC_FARM_ISO_ISO_EN_M 0xF

/* PSOC_BOOT_CONF_NIC_ISO */
#define PSOC_BOOT_CONF_NIC_ISO_ISO_EN_S 0
#define PSOC_BOOT_CONF_NIC_ISO_ISO_EN_M 0x3F

/* PSOC_BOOT_CONF_MME_ISO */
#define PSOC_BOOT_CONF_MME_ISO_ISO_EN_S 0
#define PSOC_BOOT_CONF_MME_ISO_ISO_EN_M 0xF

/* PSOC_BOOT_CONF_EDMA_ISO */
#define PSOC_BOOT_CONF_EDMA_ISO_ISO_EN_S 0
#define PSOC_BOOT_CONF_EDMA_ISO_ISO_EN_M 0x3

/* PSOC_BOOT_CONF_HDCORE_HBM_CONNECT */
#define PSOC_BOOT_CONF_HDCORE_HBM_CONNECT_SEL_S 0
#define PSOC_BOOT_CONF_HDCORE_HBM_CONNECT_SEL_M 0xF

/* PSOC_BOOT_CONF_TPC_SPARE_CONNECT */
#define PSOC_BOOT_CONF_TPC_SPARE_CONNECT_ECLS0_TPC_SPARE_S 0
#define PSOC_BOOT_CONF_TPC_SPARE_CONNECT_ECLS0_TPC_SPARE_M 0x1
#define PSOC_BOOT_CONF_TPC_SPARE_CONNECT_ECLS0_STLB_CONN_S 1
#define PSOC_BOOT_CONF_TPC_SPARE_CONNECT_ECLS0_STLB_CONN_M 0x2
#define PSOC_BOOT_CONF_TPC_SPARE_CONNECT_ECLS1_TPC_SPARE_S 2
#define PSOC_BOOT_CONF_TPC_SPARE_CONNECT_ECLS1_TPC_SPARE_M 0x4
#define PSOC_BOOT_CONF_TPC_SPARE_CONNECT_ECLS1_STLB_CONN_S 3
#define PSOC_BOOT_CONF_TPC_SPARE_CONNECT_ECLS1_STLB_CONN_M 0x8

/* PSOC_BOOT_CONF_ROT_CLS */
#define PSOC_BOOT_CONF_ROT_CLS_SEL_S 0
#define PSOC_BOOT_CONF_ROT_CLS_SEL_M 0x3

/* PSOC_BOOT_CONF_D0_PIF_ISO */
#define PSOC_BOOT_CONF_D0_PIF_ISO_ISO_EN_S 0
#define PSOC_BOOT_CONF_D0_PIF_ISO_ISO_EN_M 0x1

/* PSOC_BOOT_CONF_D1_PIF_ISO */
#define PSOC_BOOT_CONF_D1_PIF_ISO_ISO_EN_S 0
#define PSOC_BOOT_CONF_D1_PIF_ISO_ISO_EN_M 0x1

#endif /* ASIC_REG_PSOC_BOOT_CONF_MASKS_H_ */
