/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_ROTATOR_MASKS_H_
#define ASIC_REG_ROTATOR_MASKS_H_

/*
 *****************************************
 *   ROTATOR
 *   (Prototype: ROTATOR)
 *****************************************
 */

/* ROTATOR_CPL_MSG_AXI */
#define ROTATOR_CPL_MSG_AXI_CACHE_S 0
#define ROTATOR_CPL_MSG_AXI_CACHE_M 0xF

/* ROTATOR_AWPROT_0_CPL_MSG */
#define ROTATOR_AWPROT_0_CPL_MSG_VAL_S 0
#define ROTATOR_AWPROT_0_CPL_MSG_VAL_M 0x1

/* ROTATOR_AWPROT_1_CPL_MSG */
#define ROTATOR_AWPROT_1_CPL_MSG_VAL_S 0
#define ROTATOR_AWPROT_1_CPL_MSG_VAL_M 0x1

/* ROTATOR_AWPROT_2_CPL_MSG */
#define ROTATOR_AWPROT_2_CPL_MSG_VAL_S 0
#define ROTATOR_AWPROT_2_CPL_MSG_VAL_M 0x1

/* ROTATOR_CPL_MSG_THRESHOLD */
#define ROTATOR_CPL_MSG_THRESHOLD_VAL_S 0
#define ROTATOR_CPL_MSG_THRESHOLD_VAL_M 0x1F

/* ROTATOR_RSB_CFG */
#define ROTATOR_RSB_CFG_CACHE_DISABLE_S 0
#define ROTATOR_RSB_CFG_CACHE_DISABLE_M 0x1
#define ROTATOR_RSB_CFG_ENABLE_CGATE_S 1
#define ROTATOR_RSB_CFG_ENABLE_CGATE_M 0x2
#define ROTATOR_RSB_CFG_DATA_OCCUPANCY_SEL_S 4
#define ROTATOR_RSB_CFG_DATA_OCCUPANCY_SEL_M 0x70
#define ROTATOR_RSB_CFG_AXI_128BYTE_S 8
#define ROTATOR_RSB_CFG_AXI_128BYTE_M 0x100

/* ROTATOR_ARPROT_0_RSB */
#define ROTATOR_ARPROT_0_RSB_VAL_S 0
#define ROTATOR_ARPROT_0_RSB_VAL_M 0x1

/* ROTATOR_ARPROT_1_RSB */
#define ROTATOR_ARPROT_1_RSB_VAL_S 0
#define ROTATOR_ARPROT_1_RSB_VAL_M 0x1

/* ROTATOR_ARPROT_2_RSB */
#define ROTATOR_ARPROT_2_RSB_VAL_S 0
#define ROTATOR_ARPROT_2_RSB_VAL_M 0x1

/* ROTATOR_ARPROT_0_MRSB */
#define ROTATOR_ARPROT_0_MRSB_VAL_S 0
#define ROTATOR_ARPROT_0_MRSB_VAL_M 0x1

/* ROTATOR_ARPROT_1_MRSB */
#define ROTATOR_ARPROT_1_MRSB_VAL_S 0
#define ROTATOR_ARPROT_1_MRSB_VAL_M 0x1

/* ROTATOR_ARPROT_2_MRSB */
#define ROTATOR_ARPROT_2_MRSB_VAL_S 0
#define ROTATOR_ARPROT_2_MRSB_VAL_M 0x1

/* ROTATOR_ARPROT_0_GRSB */
#define ROTATOR_ARPROT_0_GRSB_VAL_S 0
#define ROTATOR_ARPROT_0_GRSB_VAL_M 0x1

/* ROTATOR_ARPROT_1_GRSB */
#define ROTATOR_ARPROT_1_GRSB_VAL_S 0
#define ROTATOR_ARPROT_1_GRSB_VAL_M 0x1

/* ROTATOR_ARPROT_2_GRSB */
#define ROTATOR_ARPROT_2_GRSB_VAL_S 0
#define ROTATOR_ARPROT_2_GRSB_VAL_M 0x1

/* ROTATOR_DISABLE_PAD_CALC */
#define ROTATOR_DISABLE_PAD_CALC_VAL_S 0
#define ROTATOR_DISABLE_PAD_CALC_VAL_M 0x7

/* ROTATOR_RSB_CAM_MAX_SIZE */
#define ROTATOR_RSB_CAM_MAX_SIZE_DATA_S 0
#define ROTATOR_RSB_CAM_MAX_SIZE_DATA_M 0xFFFF
#define ROTATOR_RSB_CAM_MAX_SIZE_MD_S 16
#define ROTATOR_RSB_CAM_MAX_SIZE_MD_M 0xFFFF0000

/* ROTATOR_RSB_MAX_OS */
#define ROTATOR_RSB_MAX_OS_VAL_S 0
#define ROTATOR_RSB_MAX_OS_VAL_M 0xFFFF

/* ROTATOR_RSB_RL */
#define ROTATOR_RSB_RL_SATURATION_S 0
#define ROTATOR_RSB_RL_SATURATION_M 0xFF
#define ROTATOR_RSB_RL_TIMEOUT_S 8
#define ROTATOR_RSB_RL_TIMEOUT_M 0xFF00
#define ROTATOR_RSB_RL_RST_TOKEN_S 16
#define ROTATOR_RSB_RL_RST_TOKEN_M 0xFF0000
#define ROTATOR_RSB_RL_RATE_LIMITER_EN_S 24
#define ROTATOR_RSB_RL_RATE_LIMITER_EN_M 0x1000000

/* ROTATOR_MRSB_RL */
#define ROTATOR_MRSB_RL_RST_TOKEN_S 0
#define ROTATOR_MRSB_RL_RST_TOKEN_M 0xFF

/* ROTATOR_GRSB_RL */
#define ROTATOR_GRSB_RL_RST_TOKEN_S 0
#define ROTATOR_GRSB_RL_RST_TOKEN_M 0xFF

/* ROTATOR_RSB_INFLIGHTS */
#define ROTATOR_RSB_INFLIGHTS_VAL_S 0
#define ROTATOR_RSB_INFLIGHTS_VAL_M 0xFFFFFFFF

/* ROTATOR_RSB_OCCUPANCY */
#define ROTATOR_RSB_OCCUPANCY_VAL_S 0
#define ROTATOR_RSB_OCCUPANCY_VAL_M 0xFFFFFFFF

/* ROTATOR_RSB_OCCUPANCY_DATA */
#define ROTATOR_RSB_OCCUPANCY_DATA_VAL_S 0
#define ROTATOR_RSB_OCCUPANCY_DATA_VAL_M 0xFFFFFFFF

/* ROTATOR_MRSB_OCCUPANCY_DATA */
#define ROTATOR_MRSB_OCCUPANCY_DATA_VAL_S 0
#define ROTATOR_MRSB_OCCUPANCY_DATA_VAL_M 0xFFFFFFFF

/* ROTATOR_GRSB_OCCUPANCY_DATA */
#define ROTATOR_GRSB_OCCUPANCY_DATA_VAL_S 0
#define ROTATOR_GRSB_OCCUPANCY_DATA_VAL_M 0xFFFFFFFF

/* ROTATOR_RSB_OCCUPANCY_MD */
#define ROTATOR_RSB_OCCUPANCY_MD_VAL_S 0
#define ROTATOR_RSB_OCCUPANCY_MD_VAL_M 0xFFFFFFFF

/* ROTATOR_MRSB_OCCUPANCY_MD */
#define ROTATOR_MRSB_OCCUPANCY_MD_VAL_S 0
#define ROTATOR_MRSB_OCCUPANCY_MD_VAL_M 0xFFFFFFFF

/* ROTATOR_GRSB_OCCUPANCY_MD */
#define ROTATOR_GRSB_OCCUPANCY_MD_VAL_S 0
#define ROTATOR_GRSB_OCCUPANCY_MD_VAL_M 0xFFFFFFFF

/* ROTATOR_RSB_INFO */
#define ROTATOR_RSB_INFO_EMPTY_S 0
#define ROTATOR_RSB_INFO_EMPTY_M 0x1
#define ROTATOR_RSB_INFO_AXI_IDLE_S 1
#define ROTATOR_RSB_INFO_AXI_IDLE_M 0x2

/* ROTATOR_WBC_CTRL */
#define ROTATOR_WBC_CTRL_REQ_WEIGHTS_ROT_S 0
#define ROTATOR_WBC_CTRL_REQ_WEIGHTS_ROT_M 0xFF
#define ROTATOR_WBC_CTRL_REQ_WEIGHTS_RSL_S 8
#define ROTATOR_WBC_CTRL_REQ_WEIGHTS_RSL_M 0xFF00

/* ROTATOR_WCH_AGG_CFG */
#define ROTATOR_WCH_AGG_CFG_AGGR_BYPASS_S 0
#define ROTATOR_WCH_AGG_CFG_AGGR_BYPASS_M 0x1
#define ROTATOR_WCH_AGG_CFG_BURST_EN_S 1
#define ROTATOR_WCH_AGG_CFG_BURST_EN_M 0x2
#define ROTATOR_WCH_AGG_CFG_IDLE_TIMEOUT_EN_S 2
#define ROTATOR_WCH_AGG_CFG_IDLE_TIMEOUT_EN_M 0x4
#define ROTATOR_WCH_AGG_CFG_IDLE_TIMEOUT_S 3
#define ROTATOR_WCH_AGG_CFG_IDLE_TIMEOUT_M 0x7FFF8
#define ROTATOR_WCH_AGG_CFG_DIS_NULL_REQ_S 19
#define ROTATOR_WCH_AGG_CFG_DIS_NULL_REQ_M 0x80000
#define ROTATOR_WCH_AGG_CFG_DISABLE_PARTIAL_S 20
#define ROTATOR_WCH_AGG_CFG_DISABLE_PARTIAL_M 0x100000
#define ROTATOR_WCH_AGG_CFG_WR_AXI_AGG_CACHE_DIS_ROT_S 21
#define ROTATOR_WCH_AGG_CFG_WR_AXI_AGG_CACHE_DIS_ROT_M 0x200000
#define ROTATOR_WCH_AGG_CFG_WR_AXI_AGG_CACHE_DIS_RSL_S 22
#define ROTATOR_WCH_AGG_CFG_WR_AXI_AGG_CACHE_DIS_RSL_M 0x400000
#define ROTATOR_WCH_AGG_CFG_DONT_AGG_ON_REDUCTION_S 23
#define ROTATOR_WCH_AGG_CFG_DONT_AGG_ON_REDUCTION_M 0x800000

/* ROTATOR_AWPROT_0_WCH_ROT */
#define ROTATOR_AWPROT_0_WCH_ROT_VAL_S 0
#define ROTATOR_AWPROT_0_WCH_ROT_VAL_M 0x1

/* ROTATOR_AWPROT_1_WCH_ROT */
#define ROTATOR_AWPROT_1_WCH_ROT_VAL_S 0
#define ROTATOR_AWPROT_1_WCH_ROT_VAL_M 0x1

/* ROTATOR_AWPROT_2_WCH_ROT */
#define ROTATOR_AWPROT_2_WCH_ROT_VAL_S 0
#define ROTATOR_AWPROT_2_WCH_ROT_VAL_M 0x1

/* ROTATOR_AWPROT_0_WCH_RSL */
#define ROTATOR_AWPROT_0_WCH_RSL_VAL_S 0
#define ROTATOR_AWPROT_0_WCH_RSL_VAL_M 0x1

/* ROTATOR_AWPROT_1_WCH_RSL */
#define ROTATOR_AWPROT_1_WCH_RSL_VAL_S 0
#define ROTATOR_AWPROT_1_WCH_RSL_VAL_M 0x1

/* ROTATOR_AWPROT_2_WCH_RSL */
#define ROTATOR_AWPROT_2_WCH_RSL_VAL_S 0
#define ROTATOR_AWPROT_2_WCH_RSL_VAL_M 0x1

/* ROTATOR_WBC_MAX_OUTSTANDING */
#define ROTATOR_WBC_MAX_OUTSTANDING_VAL_S 0
#define ROTATOR_WBC_MAX_OUTSTANDING_VAL_M 0xFFFF

/* ROTATOR_WBC_RL */
#define ROTATOR_WBC_RL_SATURATION_S 0
#define ROTATOR_WBC_RL_SATURATION_M 0xFF
#define ROTATOR_WBC_RL_TIMEOUT_S 8
#define ROTATOR_WBC_RL_TIMEOUT_M 0xFF00
#define ROTATOR_WBC_RL_RATE_LIMITER_EN_S 16
#define ROTATOR_WBC_RL_RATE_LIMITER_EN_M 0x10000

/* ROTATOR_WBC_RL_RST_TOKEN */
#define ROTATOR_WBC_RL_RST_TOKEN_RST_TOKEN_ROT_S 0
#define ROTATOR_WBC_RL_RST_TOKEN_RST_TOKEN_ROT_M 0xFF
#define ROTATOR_WBC_RL_RST_TOKEN_RST_TOKEN_RSL_S 16
#define ROTATOR_WBC_RL_RST_TOKEN_RST_TOKEN_RSL_M 0xFF0000

/* ROTATOR_WBC_INFLIGHTS */
#define ROTATOR_WBC_INFLIGHTS_VAL_S 0
#define ROTATOR_WBC_INFLIGHTS_VAL_M 0xFFFF

/* ROTATOR_WBC_INFO */
#define ROTATOR_WBC_INFO_EMPTY_S 0
#define ROTATOR_WBC_INFO_EMPTY_M 0x1
#define ROTATOR_WBC_INFO_AXI_IDLE_S 1
#define ROTATOR_WBC_INFO_AXI_IDLE_M 0x2

/* ROTATOR_WBC_MON */
#define ROTATOR_WBC_MON_CNT_S 0
#define ROTATOR_WBC_MON_CNT_M 0x1
#define ROTATOR_WBC_MON_TS_S 8
#define ROTATOR_WBC_MON_TS_M 0x300
#define ROTATOR_WBC_MON_CONTEXT_ID_S 16
#define ROTATOR_WBC_MON_CONTEXT_ID_M 0xFFFF0000

/* ROTATOR_CLK_EN */
#define ROTATOR_CLK_EN_LBW_CFG_DIS_S 0
#define ROTATOR_CLK_EN_LBW_CFG_DIS_M 0x1
#define ROTATOR_CLK_EN_DBG_CFG_DIS_S 4
#define ROTATOR_CLK_EN_DBG_CFG_DIS_M 0x10
#define ROTATOR_CLK_EN_SB_EMPTY_MASK_S 5
#define ROTATOR_CLK_EN_SB_EMPTY_MASK_M 0x20
#define ROTATOR_CLK_EN_DBG_TRIGOUT_REQ_DIS_S 6
#define ROTATOR_CLK_EN_DBG_TRIGOUT_REQ_DIS_M 0x40

/* ROTATOR_QMAN_CFG */
#define ROTATOR_QMAN_CFG_FORCE_STOP_S 0
#define ROTATOR_QMAN_CFG_FORCE_STOP_M 0x1

/* ROTATOR_ERR_CFG */
#define ROTATOR_ERR_CFG_STOP_ON_ERR_S 0
#define ROTATOR_ERR_CFG_STOP_ON_ERR_M 0x1

/* ROTATOR_MSS_HALT */
#define ROTATOR_MSS_HALT_VAL_S 0
#define ROTATOR_MSS_HALT_VAL_M 0x7

/* ROTATOR_MSS_STS */
#define ROTATOR_MSS_STS_IS_HALT_S 0
#define ROTATOR_MSS_STS_IS_HALT_M 0x1

/* ROTATOR_MSS_SEI_CLEAR */
#define ROTATOR_MSS_SEI_CLEAR_I0_S 0
#define ROTATOR_MSS_SEI_CLEAR_I0_M 0x1
#define ROTATOR_MSS_SEI_CLEAR_I1_S 1
#define ROTATOR_MSS_SEI_CLEAR_I1_M 0x2
#define ROTATOR_MSS_SEI_CLEAR_I2_S 2
#define ROTATOR_MSS_SEI_CLEAR_I2_M 0x4
#define ROTATOR_MSS_SEI_CLEAR_I3_S 3
#define ROTATOR_MSS_SEI_CLEAR_I3_M 0x8
#define ROTATOR_MSS_SEI_CLEAR_I4_S 4
#define ROTATOR_MSS_SEI_CLEAR_I4_M 0x10
#define ROTATOR_MSS_SEI_CLEAR_I5_S 5
#define ROTATOR_MSS_SEI_CLEAR_I5_M 0x20
#define ROTATOR_MSS_SEI_CLEAR_I6_S 6
#define ROTATOR_MSS_SEI_CLEAR_I6_M 0x40
#define ROTATOR_MSS_SEI_CLEAR_I7_S 7
#define ROTATOR_MSS_SEI_CLEAR_I7_M 0x80
#define ROTATOR_MSS_SEI_CLEAR_I8_S 8
#define ROTATOR_MSS_SEI_CLEAR_I8_M 0x100
#define ROTATOR_MSS_SEI_CLEAR_I9_S 9
#define ROTATOR_MSS_SEI_CLEAR_I9_M 0x200
#define ROTATOR_MSS_SEI_CLEAR_I10_S 10
#define ROTATOR_MSS_SEI_CLEAR_I10_M 0x400
#define ROTATOR_MSS_SEI_CLEAR_I11_S 11
#define ROTATOR_MSS_SEI_CLEAR_I11_M 0x800

/* ROTATOR_MSS_SEI_MASK */
#define ROTATOR_MSS_SEI_MASK_VAL_S 0
#define ROTATOR_MSS_SEI_MASK_VAL_M 0xFFF

/* ROTATOR_MSS_SEI_CAUSE */
#define ROTATOR_MSS_SEI_CAUSE_I0_S 0
#define ROTATOR_MSS_SEI_CAUSE_I0_M 0x1
#define ROTATOR_MSS_SEI_CAUSE_I1_S 1
#define ROTATOR_MSS_SEI_CAUSE_I1_M 0x2
#define ROTATOR_MSS_SEI_CAUSE_I2_S 2
#define ROTATOR_MSS_SEI_CAUSE_I2_M 0x4
#define ROTATOR_MSS_SEI_CAUSE_I3_S 3
#define ROTATOR_MSS_SEI_CAUSE_I3_M 0x8
#define ROTATOR_MSS_SEI_CAUSE_I4_S 4
#define ROTATOR_MSS_SEI_CAUSE_I4_M 0x10
#define ROTATOR_MSS_SEI_CAUSE_I5_S 5
#define ROTATOR_MSS_SEI_CAUSE_I5_M 0x20
#define ROTATOR_MSS_SEI_CAUSE_I6_S 6
#define ROTATOR_MSS_SEI_CAUSE_I6_M 0x40
#define ROTATOR_MSS_SEI_CAUSE_I7_S 7
#define ROTATOR_MSS_SEI_CAUSE_I7_M 0x80
#define ROTATOR_MSS_SEI_CAUSE_I8_S 8
#define ROTATOR_MSS_SEI_CAUSE_I8_M 0x100
#define ROTATOR_MSS_SEI_CAUSE_I9_S 9
#define ROTATOR_MSS_SEI_CAUSE_I9_M 0x200
#define ROTATOR_MSS_SEI_CAUSE_I10_S 10
#define ROTATOR_MSS_SEI_CAUSE_I10_M 0x400
#define ROTATOR_MSS_SEI_CAUSE_I11_S 11
#define ROTATOR_MSS_SEI_CAUSE_I11_M 0x800

/* ROTATOR_MSS_SPI_CLEAR */
#define ROTATOR_MSS_SPI_CLEAR_I0_S 0
#define ROTATOR_MSS_SPI_CLEAR_I0_M 0x1
#define ROTATOR_MSS_SPI_CLEAR_I1_S 1
#define ROTATOR_MSS_SPI_CLEAR_I1_M 0x2
#define ROTATOR_MSS_SPI_CLEAR_I2_S 2
#define ROTATOR_MSS_SPI_CLEAR_I2_M 0x4
#define ROTATOR_MSS_SPI_CLEAR_I3_S 3
#define ROTATOR_MSS_SPI_CLEAR_I3_M 0x8
#define ROTATOR_MSS_SPI_CLEAR_I4_S 4
#define ROTATOR_MSS_SPI_CLEAR_I4_M 0x10
#define ROTATOR_MSS_SPI_CLEAR_I5_S 5
#define ROTATOR_MSS_SPI_CLEAR_I5_M 0x20
#define ROTATOR_MSS_SPI_CLEAR_I6_S 6
#define ROTATOR_MSS_SPI_CLEAR_I6_M 0x40
#define ROTATOR_MSS_SPI_CLEAR_I7_S 7
#define ROTATOR_MSS_SPI_CLEAR_I7_M 0x80
#define ROTATOR_MSS_SPI_CLEAR_I8_S 8
#define ROTATOR_MSS_SPI_CLEAR_I8_M 0x100

/* ROTATOR_MSS_SPI_MASK */
#define ROTATOR_MSS_SPI_MASK_VAL_S 0
#define ROTATOR_MSS_SPI_MASK_VAL_M 0x1FF

/* ROTATOR_MSS_SPI_CAUSE */
#define ROTATOR_MSS_SPI_CAUSE_I0_S 0
#define ROTATOR_MSS_SPI_CAUSE_I0_M 0x1
#define ROTATOR_MSS_SPI_CAUSE_I1_S 1
#define ROTATOR_MSS_SPI_CAUSE_I1_M 0x2
#define ROTATOR_MSS_SPI_CAUSE_I2_S 2
#define ROTATOR_MSS_SPI_CAUSE_I2_M 0x4
#define ROTATOR_MSS_SPI_CAUSE_I3_S 3
#define ROTATOR_MSS_SPI_CAUSE_I3_M 0x8
#define ROTATOR_MSS_SPI_CAUSE_I4_S 4
#define ROTATOR_MSS_SPI_CAUSE_I4_M 0x10
#define ROTATOR_MSS_SPI_CAUSE_I5_S 5
#define ROTATOR_MSS_SPI_CAUSE_I5_M 0x20
#define ROTATOR_MSS_SPI_CAUSE_I6_S 6
#define ROTATOR_MSS_SPI_CAUSE_I6_M 0x40
#define ROTATOR_MSS_SPI_CAUSE_I7_S 7
#define ROTATOR_MSS_SPI_CAUSE_I7_M 0x80
#define ROTATOR_MSS_SPI_CAUSE_I8_S 8
#define ROTATOR_MSS_SPI_CAUSE_I8_M 0x100

/* ROTATOR_DBG_CONTEXT_ID_CONTROL */
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_RSB_RR_ERROR_SEL_S 0
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_RSB_RR_ERROR_SEL_M 0x1
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_RSB_NUM_ERROR_SEL_S 1
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_RSB_NUM_ERROR_SEL_M 0x2
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_RSB_SLV_ERROR_SEL_S 2
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_RSB_SLV_ERROR_SEL_M 0x4
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_MRSB_RR_ERROR_SEL_S 3
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_MRSB_RR_ERROR_SEL_M 0x8
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_MRSB_NUM_ERROR_SEL_S 4
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_MRSB_NUM_ERROR_SEL_M 0x10
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_MRSB_SLV_ERROR_SEL_S 5
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_MRSB_SLV_ERROR_SEL_M 0x20
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_GRSB_RR_ERROR_SEL_S 6
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_GRSB_RR_ERROR_SEL_M 0x40
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_GRSB_NUM_ERROR_SEL_S 7
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_GRSB_NUM_ERROR_SEL_M 0x80
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_GRSB_SLV_ERROR_SEL_S 8
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_GRSB_SLV_ERROR_SEL_M 0x100
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH0_RR_ERROR_SEL_S 9
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH0_RR_ERROR_SEL_M 0x200
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH0_PINF_ERROR_SEL_S 10
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH0_PINF_ERROR_SEL_M 0x400
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH0_NINF_ERROR_SEL_S 11
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH0_NINF_ERROR_SEL_M 0x800
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH0_NAN_ERROR_SEL_S 12
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH0_NAN_ERROR_SEL_M 0x1000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH0_SLV_ERROR_SEL_S 13
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH0_SLV_ERROR_SEL_M 0x2000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH1_RR_ERROR_SEL_S 14
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH1_RR_ERROR_SEL_M 0x4000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH1_PINF_ERROR_SEL_S 15
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH1_PINF_ERROR_SEL_M 0x8000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH1_NINF_ERROR_SEL_S 16
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH1_NINF_ERROR_SEL_M 0x10000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH1_NAN_ERROR_SEL_S 17
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH1_NAN_ERROR_SEL_M 0x20000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH1_SLV_ERROR_SEL_S 18
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_WCH_CH1_SLV_ERROR_SEL_M 0x40000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_RINTERP_PINF_ERROR_SEL_S 19
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_RINTERP_PINF_ERROR_SEL_M 0x80000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_RINTERP_NINF_ERROR_SEL_S 20
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_RINTERP_NINF_ERROR_SEL_M 0x100000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_RINTERP_NAN_ERROR_SEL_S 21
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_RINTERP_NAN_ERROR_SEL_M 0x200000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_MINTERP_PINF_ERROR_SEL_S 22
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_MINTERP_PINF_ERROR_SEL_M 0x400000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_MINTERP_NINF_ERROR_SEL_S 23
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_MINTERP_NINF_ERROR_SEL_M 0x800000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_MINTERP_NAN_ERROR_SEL_S 24
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_MINTERP_NAN_ERROR_SEL_M 0x1000000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_COORD_PINF_ERROR_SEL_S 25
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_COORD_PINF_ERROR_SEL_M 0x2000000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_COORD_NINF_ERROR_SEL_S 26
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_COORD_NINF_ERROR_SEL_M 0x4000000
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_COORD_NAN_ERROR_SEL_S 27
#define ROTATOR_DBG_CONTEXT_ID_CONTROL_COORD_NAN_ERROR_SEL_M 0x8000000

/* ROTATOR_RSB_ERR_STATUS */
#define ROTATOR_RSB_ERR_STATUS_RSB_RR_ERROR_S 0
#define ROTATOR_RSB_ERR_STATUS_RSB_RR_ERROR_M 0x1
#define ROTATOR_RSB_ERR_STATUS_RSB_NUM_ERROR_S 1
#define ROTATOR_RSB_ERR_STATUS_RSB_NUM_ERROR_M 0x2
#define ROTATOR_RSB_ERR_STATUS_RSB_SLV_ERROR_S 2
#define ROTATOR_RSB_ERR_STATUS_RSB_SLV_ERROR_M 0x4
#define ROTATOR_RSB_ERR_STATUS_MRSB_RR_ERROR_S 3
#define ROTATOR_RSB_ERR_STATUS_MRSB_RR_ERROR_M 0x8
#define ROTATOR_RSB_ERR_STATUS_MRSB_NUM_ERROR_S 4
#define ROTATOR_RSB_ERR_STATUS_MRSB_NUM_ERROR_M 0x10
#define ROTATOR_RSB_ERR_STATUS_MRSB_SLV_ERROR_S 5
#define ROTATOR_RSB_ERR_STATUS_MRSB_SLV_ERROR_M 0x20
#define ROTATOR_RSB_ERR_STATUS_GRSB_RR_ERROR_S 6
#define ROTATOR_RSB_ERR_STATUS_GRSB_RR_ERROR_M 0x40
#define ROTATOR_RSB_ERR_STATUS_GRSB_NUM_ERROR_S 7
#define ROTATOR_RSB_ERR_STATUS_GRSB_NUM_ERROR_M 0x80
#define ROTATOR_RSB_ERR_STATUS_GRSB_SLV_ERROR_S 8
#define ROTATOR_RSB_ERR_STATUS_GRSB_SLV_ERROR_M 0x100

/* ROTATOR_GRSB_MRSB_ERR_CONTEXT_ID */
#define ROTATOR_GRSB_MRSB_ERR_CONTEXT_ID_GRSB_S 0
#define ROTATOR_GRSB_MRSB_ERR_CONTEXT_ID_GRSB_M 0xFFFF
#define ROTATOR_GRSB_MRSB_ERR_CONTEXT_ID_MRSB_S 16
#define ROTATOR_GRSB_MRSB_ERR_CONTEXT_ID_MRSB_M 0xFFFF0000

/* ROTATOR_RSB_ERR_CONTEXT_ID */
#define ROTATOR_RSB_ERR_CONTEXT_ID_RSB_S 0
#define ROTATOR_RSB_ERR_CONTEXT_ID_RSB_M 0xFFFF

/* ROTATOR_WCH_ERR_STATUS */
#define ROTATOR_WCH_ERR_STATUS_WCH_CH0_RR_ERROR_S 0
#define ROTATOR_WCH_ERR_STATUS_WCH_CH0_RR_ERROR_M 0x1
#define ROTATOR_WCH_ERR_STATUS_WCH_CH0_PINF_ERROR_S 1
#define ROTATOR_WCH_ERR_STATUS_WCH_CH0_PINF_ERROR_M 0x2
#define ROTATOR_WCH_ERR_STATUS_WCH_CH0_NINF_ERROR_S 2
#define ROTATOR_WCH_ERR_STATUS_WCH_CH0_NINF_ERROR_M 0x4
#define ROTATOR_WCH_ERR_STATUS_WCH_CH0_NAN_ERROR_S 3
#define ROTATOR_WCH_ERR_STATUS_WCH_CH0_NAN_ERROR_M 0x8
#define ROTATOR_WCH_ERR_STATUS_WCH_CH0_SLV_ERROR_S 4
#define ROTATOR_WCH_ERR_STATUS_WCH_CH0_SLV_ERROR_M 0x10
#define ROTATOR_WCH_ERR_STATUS_WCH_CH1_RR_ERROR_S 5
#define ROTATOR_WCH_ERR_STATUS_WCH_CH1_RR_ERROR_M 0x20
#define ROTATOR_WCH_ERR_STATUS_WCH_CH1_PINF_ERROR_S 6
#define ROTATOR_WCH_ERR_STATUS_WCH_CH1_PINF_ERROR_M 0x40
#define ROTATOR_WCH_ERR_STATUS_WCH_CH1_NINF_ERROR_S 7
#define ROTATOR_WCH_ERR_STATUS_WCH_CH1_NINF_ERROR_M 0x80
#define ROTATOR_WCH_ERR_STATUS_WCH_CH1_NAN_ERROR_S 8
#define ROTATOR_WCH_ERR_STATUS_WCH_CH1_NAN_ERROR_M 0x100
#define ROTATOR_WCH_ERR_STATUS_WCH_CH1_SLV_ERROR_S 9
#define ROTATOR_WCH_ERR_STATUS_WCH_CH1_SLV_ERROR_M 0x200

/* ROTATOR_WCH_ERR_CONTEXT_ID */
#define ROTATOR_WCH_ERR_CONTEXT_ID_CHANNEL0_S 0
#define ROTATOR_WCH_ERR_CONTEXT_ID_CHANNEL0_M 0xFFFF
#define ROTATOR_WCH_ERR_CONTEXT_ID_CHANNEL1_S 16
#define ROTATOR_WCH_ERR_CONTEXT_ID_CHANNEL1_M 0xFFFF0000

/* ROTATOR_IP_NUM_ERR_STATUS */
#define ROTATOR_IP_NUM_ERR_STATUS_RINTERP_PINF_ERROR_S 0
#define ROTATOR_IP_NUM_ERR_STATUS_RINTERP_PINF_ERROR_M 0x1
#define ROTATOR_IP_NUM_ERR_STATUS_RINTERP_NINF_ERROR_S 1
#define ROTATOR_IP_NUM_ERR_STATUS_RINTERP_NINF_ERROR_M 0x2
#define ROTATOR_IP_NUM_ERR_STATUS_RINTERP_NAN_ERROR_S 2
#define ROTATOR_IP_NUM_ERR_STATUS_RINTERP_NAN_ERROR_M 0x4
#define ROTATOR_IP_NUM_ERR_STATUS_MINTERP_PINF_ERROR_S 3
#define ROTATOR_IP_NUM_ERR_STATUS_MINTERP_PINF_ERROR_M 0x8
#define ROTATOR_IP_NUM_ERR_STATUS_MINTERP_NINF_ERROR_S 4
#define ROTATOR_IP_NUM_ERR_STATUS_MINTERP_NINF_ERROR_M 0x10
#define ROTATOR_IP_NUM_ERR_STATUS_MINTERP_NAN_ERROR_S 5
#define ROTATOR_IP_NUM_ERR_STATUS_MINTERP_NAN_ERROR_M 0x20
#define ROTATOR_IP_NUM_ERR_STATUS_COORD_PINF_ERROR_S 6
#define ROTATOR_IP_NUM_ERR_STATUS_COORD_PINF_ERROR_M 0x40
#define ROTATOR_IP_NUM_ERR_STATUS_COORD_NINF_ERROR_S 7
#define ROTATOR_IP_NUM_ERR_STATUS_COORD_NINF_ERROR_M 0x80
#define ROTATOR_IP_NUM_ERR_STATUS_COORD_NAN_ERROR_S 8
#define ROTATOR_IP_NUM_ERR_STATUS_COORD_NAN_ERROR_M 0x100

/* ROTATOR_RINTERP_MINTERP_NUM_ERR_CONTEXT_ID */
#define ROTATOR_RINTERP_MINTERP_NUM_ERR_CONTEXT_ID_RINTERP_S 0
#define ROTATOR_RINTERP_MINTERP_NUM_ERR_CONTEXT_ID_RINTERP_M 0xFFFF
#define ROTATOR_RINTERP_MINTERP_NUM_ERR_CONTEXT_ID_MINTERP_S 16
#define ROTATOR_RINTERP_MINTERP_NUM_ERR_CONTEXT_ID_MINTERP_M 0xFFFF0000

/* ROTATOR_COORD_NUM_ERR_CONTEXT_ID */
#define ROTATOR_COORD_NUM_ERR_CONTEXT_ID_COORD_S 0
#define ROTATOR_COORD_NUM_ERR_CONTEXT_ID_COORD_M 0xFFFF

/* ROTATOR_MSS_ROT_APB_AXI2APB_CFG */
#define ROTATOR_MSS_ROT_APB_AXI2APB_CFG_MSK_ERROR_RSP_S 0
#define ROTATOR_MSS_ROT_APB_AXI2APB_CFG_MSK_ERROR_RSP_M 0x1
#define ROTATOR_MSS_ROT_APB_AXI2APB_CFG_BLOCK_PARTIAL_STRB_S 1
#define ROTATOR_MSS_ROT_APB_AXI2APB_CFG_BLOCK_PARTIAL_STRB_M 0x2
#define ROTATOR_MSS_ROT_APB_AXI2APB_CFG_SPL_ERROR_RSP_S 2
#define ROTATOR_MSS_ROT_APB_AXI2APB_CFG_SPL_ERROR_RSP_M 0x4

/* ROTATOR_CORE_CFG */
#define ROTATOR_CORE_CFG_NM1_EN_S 0
#define ROTATOR_CORE_CFG_NM1_EN_M 0x1

/* ROTATOR_ROT_MAX_OS */
#define ROTATOR_ROT_MAX_OS_VAL_S 0
#define ROTATOR_ROT_MAX_OS_VAL_M 0x7FF
#define ROTATOR_ROT_MAX_OS_THROTTLE_VAL_S 16
#define ROTATOR_ROT_MAX_OS_THROTTLE_VAL_M 0x7FF0000

/* ROTATOR_MESH_MAX_OS */
#define ROTATOR_MESH_MAX_OS_VAL_S 0
#define ROTATOR_MESH_MAX_OS_VAL_M 0x7FF
#define ROTATOR_MESH_MAX_OS_THROTTLE_VAL_S 16
#define ROTATOR_MESH_MAX_OS_THROTTLE_VAL_M 0x7FF0000

/* ROTATOR_GRAD_MAX_OS */
#define ROTATOR_GRAD_MAX_OS_VAL_S 0
#define ROTATOR_GRAD_MAX_OS_VAL_M 0x7FF
#define ROTATOR_GRAD_MAX_OS_THROTTLE_VAL_S 16
#define ROTATOR_GRAD_MAX_OS_THROTTLE_VAL_M 0x7FF0000

/* ROTATOR_CFG_RS_TRC */
#define ROTATOR_CFG_RS_TRC_FREQ_S 0
#define ROTATOR_CFG_RS_TRC_FREQ_M 0xFFFF
#define ROTATOR_CFG_RS_TRC_EN_S 16
#define ROTATOR_CFG_RS_TRC_EN_M 0x10000

/* ROTATOR_RSB_LL_THRESHOLD */
#define ROTATOR_RSB_LL_THRESHOLD_VAL_S 0
#define ROTATOR_RSB_LL_THRESHOLD_VAL_M 0x3FF

/* ROTATOR_NUM_CONV_CFG */
#define ROTATOR_NUM_CONV_CFG_CLIP_FP_S 0
#define ROTATOR_NUM_CONV_CFG_CLIP_FP_M 0x1
#define ROTATOR_NUM_CONV_CFG_CLIP_INPUT_INF_S 1
#define ROTATOR_NUM_CONV_CFG_CLIP_INPUT_INF_M 0x2
#define ROTATOR_NUM_CONV_CFG_FTZ_EN_S 2
#define ROTATOR_NUM_CONV_CFG_FTZ_EN_M 0x4

/* ROTATOR_PLRU */
#define ROTATOR_PLRU_MODE_S 0
#define ROTATOR_PLRU_MODE_M 0x1

#endif /* ASIC_REG_ROTATOR_MASKS_H_ */
