/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_RTR_CTRL_RR_LBW_MASKS_H_
#define ASIC_REG_RTR_CTRL_RR_LBW_MASKS_H_

/*
 *****************************************
 *   RTR_CTRL_RR_LBW
 *   (Prototype: RR_LBW_CORE)
 *****************************************
 */

/* RTR_CTRL_RR_LBW_SEC_RANGE_EN_SHORT */
#define RTR_CTRL_RR_LBW_SEC_RANGE_EN_SHORT_WR_S 0
#define RTR_CTRL_RR_LBW_SEC_RANGE_EN_SHORT_WR_M 0x1
#define RTR_CTRL_RR_LBW_SEC_RANGE_EN_SHORT_RD_S 4
#define RTR_CTRL_RR_LBW_SEC_RANGE_EN_SHORT_RD_M 0x10

/* RTR_CTRL_RR_LBW_SEC_RANGE_MIN_SHORT */
#define RTR_CTRL_RR_LBW_SEC_RANGE_MIN_SHORT_VAL_S 12
#define RTR_CTRL_RR_LBW_SEC_RANGE_MIN_SHORT_VAL_M 0x1FFFF000

/* RTR_CTRL_RR_LBW_SEC_RANGE_MAX_SHORT */
#define RTR_CTRL_RR_LBW_SEC_RANGE_MAX_SHORT_VAL_S 12
#define RTR_CTRL_RR_LBW_SEC_RANGE_MAX_SHORT_VAL_M 0x1FFFF000

/* RTR_CTRL_RR_LBW_SEC_RANGE_MASK_SHORT */
#define RTR_CTRL_RR_LBW_SEC_RANGE_MASK_SHORT_VAL_S 12
#define RTR_CTRL_RR_LBW_SEC_RANGE_MASK_SHORT_VAL_M 0x1FFFF000

/* RTR_CTRL_RR_LBW_PRIV_RANGE_EN_SHORT */
#define RTR_CTRL_RR_LBW_PRIV_RANGE_EN_SHORT_WR_S 0
#define RTR_CTRL_RR_LBW_PRIV_RANGE_EN_SHORT_WR_M 0x1
#define RTR_CTRL_RR_LBW_PRIV_RANGE_EN_SHORT_RD_S 4
#define RTR_CTRL_RR_LBW_PRIV_RANGE_EN_SHORT_RD_M 0x10

/* RTR_CTRL_RR_LBW_PRIV_RANGE_EN_SHORT_13 */
#define RTR_CTRL_RR_LBW_PRIV_RANGE_EN_SHORT_13_WR_S 0
#define RTR_CTRL_RR_LBW_PRIV_RANGE_EN_SHORT_13_WR_M 0x1
#define RTR_CTRL_RR_LBW_PRIV_RANGE_EN_SHORT_13_RD_S 4
#define RTR_CTRL_RR_LBW_PRIV_RANGE_EN_SHORT_13_RD_M 0x10

/* RTR_CTRL_RR_LBW_PRIV_RANGE_MIN_SHORT */
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MIN_SHORT_VAL_S 12
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MIN_SHORT_VAL_M 0x1FFFF000

/* RTR_CTRL_RR_LBW_PRIV_RANGE_MIN_SHORT_13 */
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MIN_SHORT_13_VAL_S 12
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MIN_SHORT_13_VAL_M 0x1FFFF000

/* RTR_CTRL_RR_LBW_PRIV_RANGE_MAX_SHORT */
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MAX_SHORT_VAL_S 12
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MAX_SHORT_VAL_M 0x1FFFF000

/* RTR_CTRL_RR_LBW_PRIV_RANGE_MAX_SHORT_13 */
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MAX_SHORT_13_VAL_S 12
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MAX_SHORT_13_VAL_M 0x1FFFF000

/* RTR_CTRL_RR_LBW_PRIV_RANGE_MASK_SHORT */
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MASK_SHORT_VAL_S 12
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MASK_SHORT_VAL_M 0x1FFFF000

/* RTR_CTRL_RR_LBW_PRIV_RANGE_MASK_SHORT_13 */
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MASK_SHORT_13_VAL_S 12
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MASK_SHORT_13_VAL_M 0x1FFFF000

/* RTR_CTRL_RR_LBW_SEC_RANGE_EN */
#define RTR_CTRL_RR_LBW_SEC_RANGE_EN_WR_S 0
#define RTR_CTRL_RR_LBW_SEC_RANGE_EN_WR_M 0x1
#define RTR_CTRL_RR_LBW_SEC_RANGE_EN_RD_S 4
#define RTR_CTRL_RR_LBW_SEC_RANGE_EN_RD_M 0x10

/* RTR_CTRL_RR_LBW_SEC_RANGE_MIN */
#define RTR_CTRL_RR_LBW_SEC_RANGE_MIN_VAL_S 2
#define RTR_CTRL_RR_LBW_SEC_RANGE_MIN_VAL_M 0x1FFFFFFC

/* RTR_CTRL_RR_LBW_SEC_RANGE_MAX */
#define RTR_CTRL_RR_LBW_SEC_RANGE_MAX_VAL_S 2
#define RTR_CTRL_RR_LBW_SEC_RANGE_MAX_VAL_M 0x1FFFFFFC

/* RTR_CTRL_RR_LBW_SEC_RANGE_MASK */
#define RTR_CTRL_RR_LBW_SEC_RANGE_MASK_VAL_S 2
#define RTR_CTRL_RR_LBW_SEC_RANGE_MASK_VAL_M 0x1FFFFFFC

/* RTR_CTRL_RR_LBW_PRIV_RANGE_EN */
#define RTR_CTRL_RR_LBW_PRIV_RANGE_EN_WR_S 0
#define RTR_CTRL_RR_LBW_PRIV_RANGE_EN_WR_M 0x1
#define RTR_CTRL_RR_LBW_PRIV_RANGE_EN_RD_S 4
#define RTR_CTRL_RR_LBW_PRIV_RANGE_EN_RD_M 0x10

/* RTR_CTRL_RR_LBW_PRIV_RANGE_MIN */
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MIN_VAL_S 2
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MIN_VAL_M 0x1FFFFFFC

/* RTR_CTRL_RR_LBW_PRIV_RANGE_MAX */
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MAX_VAL_S 2
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MAX_VAL_M 0x1FFFFFFC

/* RTR_CTRL_RR_LBW_PRIV_RANGE_MASK */
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MASK_VAL_S 2
#define RTR_CTRL_RR_LBW_PRIV_RANGE_MASK_VAL_M 0x1FFFFFFC

/* RTR_CTRL_RR_LBW_SEC_HIT_AW */
#define RTR_CTRL_RR_LBW_SEC_HIT_AW_VAL_S 0
#define RTR_CTRL_RR_LBW_SEC_HIT_AW_VAL_M 0x3FFFF

/* RTR_CTRL_RR_LBW_PRIV_HIT_AW */
#define RTR_CTRL_RR_LBW_PRIV_HIT_AW_VAL_S 0
#define RTR_CTRL_RR_LBW_PRIV_HIT_AW_VAL_M 0x3FFFF

/* RTR_CTRL_RR_LBW_SEC_HIT_AR */
#define RTR_CTRL_RR_LBW_SEC_HIT_AR_VAL_S 0
#define RTR_CTRL_RR_LBW_SEC_HIT_AR_VAL_M 0x3FFFF

/* RTR_CTRL_RR_LBW_PRIV_HIT_AR */
#define RTR_CTRL_RR_LBW_PRIV_HIT_AR_VAL_S 0
#define RTR_CTRL_RR_LBW_PRIV_HIT_AR_VAL_M 0x3FFFF

/* RTR_CTRL_RR_LBW_EFUSE_CTRL */
#define RTR_CTRL_RR_LBW_EFUSE_CTRL_SET_ONCE_S 0
#define RTR_CTRL_RR_LBW_EFUSE_CTRL_SET_ONCE_M 0x1

/* RTR_CTRL_RR_LBW_EFUSE_STAT */
#define RTR_CTRL_RR_LBW_EFUSE_STAT_SET_DONE_S 0
#define RTR_CTRL_RR_LBW_EFUSE_STAT_SET_DONE_M 0x1

#endif /* ASIC_REG_RTR_CTRL_RR_LBW_MASKS_H_ */
