/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_TPC_QM_MASKS_H_
#define ASIC_REG_TPC_QM_MASKS_H_

/*
 *****************************************
 *   TPC_QM
 *   (Prototype: TPC_NON_TENSOR_DESCRIPTOR)
 *****************************************
 */

/* TPC_QM_KERNEL_BASE_ADDRESS_LOW */
#define TPC_QM_KERNEL_BASE_ADDRESS_LOW_V_S 0
#define TPC_QM_KERNEL_BASE_ADDRESS_LOW_V_M 0xFFFFFFFF

/* TPC_QM_KERNEL_BASE_ADDRESS_HIGH */
#define TPC_QM_KERNEL_BASE_ADDRESS_HIGH_V_S 0
#define TPC_QM_KERNEL_BASE_ADDRESS_HIGH_V_M 0xFFFFFFFF

/* TPC_QM_KERNEL_CONFIG */
#define TPC_QM_KERNEL_CONFIG_SMALL_VLM_S 0
#define TPC_QM_KERNEL_CONFIG_SMALL_VLM_M 0x1
#define TPC_QM_KERNEL_CONFIG_ASO_EVICT_L0_S 1
#define TPC_QM_KERNEL_CONFIG_ASO_EVICT_L0_M 0x2
#define TPC_QM_KERNEL_CONFIG_NUM_VALID_SRFS_S 2
#define TPC_QM_KERNEL_CONFIG_NUM_VALID_SRFS_M 0x1FC
#define TPC_QM_KERNEL_CONFIG_RD_RATE_LIMIT_RST_TOKEN_S 9
#define TPC_QM_KERNEL_CONFIG_RD_RATE_LIMIT_RST_TOKEN_M 0x1FE00
#define TPC_QM_KERNEL_CONFIG_WR_RATE_LIMIT_RST_TOKEN_S 17
#define TPC_QM_KERNEL_CONFIG_WR_RATE_LIMIT_RST_TOKEN_M 0x1FE0000
#define TPC_QM_KERNEL_CONFIG_IRF_32BIT_COMPATIBILTY_S 25
#define TPC_QM_KERNEL_CONFIG_IRF_32BIT_COMPATIBILTY_M 0x2000000
#define TPC_QM_KERNEL_CONFIG_CCL_DIS_S 26
#define TPC_QM_KERNEL_CONFIG_CCL_DIS_M 0x4000000
#define TPC_QM_KERNEL_CONFIG_IRF_DIM0_LAST_48BIT_MODE_S 27
#define TPC_QM_KERNEL_CONFIG_IRF_DIM0_LAST_48BIT_MODE_M 0x8000000

/* TPC_QM_POWER_LOOP */
#define TPC_QM_POWER_LOOP_START_EN_S 0
#define TPC_QM_POWER_LOOP_START_EN_M 0x1
#define TPC_QM_POWER_LOOP_END_EN_S 1
#define TPC_QM_POWER_LOOP_END_EN_M 0x2
#define TPC_QM_POWER_LOOP_PAYLOAD_S 4
#define TPC_QM_POWER_LOOP_PAYLOAD_M 0xFF0

/* TPC_QM_SMT_EN */
#define TPC_QM_SMT_EN_SMT_EN_S 0
#define TPC_QM_SMT_EN_SMT_EN_M 0x1

/* TPC_QM_QOS */
#define TPC_QM_QOS_QOS_S 0
#define TPC_QM_QOS_QOS_M 0xF

/* TPC_QM_MCID_FAST_CFG */
#define TPC_QM_MCID_FAST_CFG_MCID_S 0
#define TPC_QM_MCID_FAST_CFG_MCID_M 0xFFFF
#define TPC_QM_MCID_FAST_CFG_MASK_S 16
#define TPC_QM_MCID_FAST_CFG_MASK_M 0xFFFF0000

/* TPC_QM_CLASS_FAST_CFG */
#define TPC_QM_CLASS_FAST_CFG_CLAS_S 0
#define TPC_QM_CLASS_FAST_CFG_CLAS_M 0x3
#define TPC_QM_CLASS_FAST_CFG_MASK_S 2
#define TPC_QM_CLASS_FAST_CFG_MASK_M 0x3FFFC

/* TPC_QM_KERNEL_ID */
#define TPC_QM_KERNEL_ID_V_S 0
#define TPC_QM_KERNEL_ID_V_M 0xFFFF

/* TPC_QM_KERNEL_ID_INC */
#define TPC_QM_KERNEL_ID_INC_V_S 0
#define TPC_QM_KERNEL_ID_INC_V_M 0xFF

/* TPC_QM_ACTIVE_THRD */
#define TPC_QM_ACTIVE_THRD_ACTIVE_THRD_S 0
#define TPC_QM_ACTIVE_THRD_ACTIVE_THRD_M 0xF

/* TPC_QM_SRF */
#define TPC_QM_SRF_V_S 0
#define TPC_QM_SRF_V_M 0xFFFFFFFF

/* TPC_QM_ICACHE_AXI_CFG */
#define TPC_QM_ICACHE_AXI_CFG_ARCACH_S 0
#define TPC_QM_ICACHE_AXI_CFG_ARCACH_M 0xF
#define TPC_QM_ICACHE_AXI_CFG_MCID_S 4
#define TPC_QM_ICACHE_AXI_CFG_MCID_M 0xFFFF0
#define TPC_QM_ICACHE_AXI_CFG_CLAS_S 20
#define TPC_QM_ICACHE_AXI_CFG_CLAS_M 0x300000

/* TPC_QM_LKUP_AXI_CFG */
#define TPC_QM_LKUP_AXI_CFG_ARCACHE_S 0
#define TPC_QM_LKUP_AXI_CFG_ARCACHE_M 0xF
#define TPC_QM_LKUP_AXI_CFG_MCID_S 4
#define TPC_QM_LKUP_AXI_CFG_MCID_M 0xFFFF0
#define TPC_QM_LKUP_AXI_CFG_CLAS_S 20
#define TPC_QM_LKUP_AXI_CFG_CLAS_M 0x300000

/* TPC_QM_DCACHE_AXI_CFG */
#define TPC_QM_DCACHE_AXI_CFG_AWCACHE_S 0
#define TPC_QM_DCACHE_AXI_CFG_AWCACHE_M 0xF
#define TPC_QM_DCACHE_AXI_CFG_MCID_S 4
#define TPC_QM_DCACHE_AXI_CFG_MCID_M 0xFFFF0
#define TPC_QM_DCACHE_AXI_CFG_CLAS_S 20
#define TPC_QM_DCACHE_AXI_CFG_CLAS_M 0x300000

/* TPC_QM_CLASS_L2_PREF */
#define TPC_QM_CLASS_L2_PREF_CLAS_S 0
#define TPC_QM_CLASS_L2_PREF_CLAS_M 0x3

/* TPC_QM_CLASS_CTRL_L1_PREF_LD */
#define TPC_QM_CLASS_CTRL_L1_PREF_LD_CLAS_S 0
#define TPC_QM_CLASS_CTRL_L1_PREF_LD_CLAS_M 0x3
#define TPC_QM_CLASS_CTRL_L1_PREF_LD_SEL_CLASS_SRC_S 2
#define TPC_QM_CLASS_CTRL_L1_PREF_LD_SEL_CLASS_SRC_M 0x4

/* TPC_QM_HALT_ZERO_SQZ */
#define TPC_QM_HALT_ZERO_SQZ_HALT_ZERO_SQZ_S 0
#define TPC_QM_HALT_ZERO_SQZ_HALT_ZERO_SQZ_M 0x1

/* TPC_QM_RMW_CLIP_FP */
#define TPC_QM_RMW_CLIP_FP_RMW_CLIP_FP_S 0
#define TPC_QM_RMW_CLIP_FP_RMW_CLIP_FP_M 0x1

/* TPC_QM_SYNC_MSG_MODE_SMT4 */
#define TPC_QM_SYNC_MSG_MODE_SMT4_V_S 0
#define TPC_QM_SYNC_MSG_MODE_SMT4_V_M 0x1

/* TPC_QM_LD_DEFAULT_HBW_AXI_CFG */
#define TPC_QM_LD_DEFAULT_HBW_AXI_CFG_MCID_S 0
#define TPC_QM_LD_DEFAULT_HBW_AXI_CFG_MCID_M 0xFFFF
#define TPC_QM_LD_DEFAULT_HBW_AXI_CFG_CLAS_S 16
#define TPC_QM_LD_DEFAULT_HBW_AXI_CFG_CLAS_M 0x30000
#define TPC_QM_LD_DEFAULT_HBW_AXI_CFG_ARCACHE_S 18
#define TPC_QM_LD_DEFAULT_HBW_AXI_CFG_ARCACHE_M 0x3C0000

/* TPC_QM_ST_DEFAULT_HBW_AXI_CFG */
#define TPC_QM_ST_DEFAULT_HBW_AXI_CFG_MCID_S 0
#define TPC_QM_ST_DEFAULT_HBW_AXI_CFG_MCID_M 0xFFFF
#define TPC_QM_ST_DEFAULT_HBW_AXI_CFG_CLAS_S 16
#define TPC_QM_ST_DEFAULT_HBW_AXI_CFG_CLAS_M 0x30000
#define TPC_QM_ST_DEFAULT_HBW_AXI_CFG_AWCACHE_S 18
#define TPC_QM_ST_DEFAULT_HBW_AXI_CFG_AWCACHE_M 0x3C0000

/* TPC_QM_DCACHE_PREF_WINDOW_INIT */
#define TPC_QM_DCACHE_PREF_WINDOW_INIT_L1_PREF_WINDOW_INIT_VAL_S 0
#define TPC_QM_DCACHE_PREF_WINDOW_INIT_L1_PREF_WINDOW_INIT_VAL_M 0xFF
#define TPC_QM_DCACHE_PREF_WINDOW_INIT_L2_PREF_WINDOW_INIT_VAL_S 8
#define TPC_QM_DCACHE_PREF_WINDOW_INIT_L2_PREF_WINDOW_INIT_VAL_M 0xFF00
#define TPC_QM_DCACHE_PREF_WINDOW_INIT_L1_PREF_WINDOW_INIT_EN_S 16
#define TPC_QM_DCACHE_PREF_WINDOW_INIT_L1_PREF_WINDOW_INIT_EN_M 0x10000
#define TPC_QM_DCACHE_PREF_WINDOW_INIT_L2_PREF_WINDOW_INIT_EN_S 17
#define TPC_QM_DCACHE_PREF_WINDOW_INIT_L2_PREF_WINDOW_INIT_EN_M 0x20000

/* TPC_QM_DCACHE_PREF_DYNAMIC_WINDOW */
#define TPC_QM_DCACHE_PREF_DYNAMIC_WINDOW_L1_PREF_WINDOW_INC_VAL_S 0
#define TPC_QM_DCACHE_PREF_DYNAMIC_WINDOW_L1_PREF_WINDOW_INC_VAL_M 0xFF
#define TPC_QM_DCACHE_PREF_DYNAMIC_WINDOW_L2_PREF_WINDOW_INC_VAL_S 8
#define TPC_QM_DCACHE_PREF_DYNAMIC_WINDOW_L2_PREF_WINDOW_INC_VAL_M 0xFF00
#define TPC_QM_DCACHE_PREF_DYNAMIC_WINDOW_L1_PREF_WINDOW_INC_EN_S 16
#define TPC_QM_DCACHE_PREF_DYNAMIC_WINDOW_L1_PREF_WINDOW_INC_EN_M 0x10000
#define TPC_QM_DCACHE_PREF_DYNAMIC_WINDOW_L2_PREF_WINDOW_INC_EN_S 17
#define TPC_QM_DCACHE_PREF_DYNAMIC_WINDOW_L2_PREF_WINDOW_INC_EN_M 0x20000
#define TPC_QM_DCACHE_PREF_DYNAMIC_WINDOW_L1_PREF_WINDOW_DEC_EN_S 18
#define TPC_QM_DCACHE_PREF_DYNAMIC_WINDOW_L1_PREF_WINDOW_DEC_EN_M 0x40000
#define TPC_QM_DCACHE_PREF_DYNAMIC_WINDOW_L2_PREF_WINDOW_DEC_EN_S 19
#define TPC_QM_DCACHE_PREF_DYNAMIC_WINDOW_L2_PREF_WINDOW_DEC_EN_M 0x80000

/* TPC_QM_DCACHE_PREF_L1_WINDOW_LIMIT */
#define TPC_QM_DCACHE_PREF_L1_WINDOW_LIMIT_L1_PREF_WINDOW_MAX_S 0
#define TPC_QM_DCACHE_PREF_L1_WINDOW_LIMIT_L1_PREF_WINDOW_MAX_M 0xFF
#define TPC_QM_DCACHE_PREF_L1_WINDOW_LIMIT_L1_PREF_WINDOW_MIN_S 8
#define TPC_QM_DCACHE_PREF_L1_WINDOW_LIMIT_L1_PREF_WINDOW_MIN_M 0xFF00
#define TPC_QM_DCACHE_PREF_L1_WINDOW_LIMIT_L1_SUM_WINDOW_LIMIT_S 16
#define TPC_QM_DCACHE_PREF_L1_WINDOW_LIMIT_L1_SUM_WINDOW_LIMIT_M 0xFF0000
#define TPC_QM_DCACHE_PREF_L1_WINDOW_LIMIT_L1_INC_LOW_TH_S 24
#define TPC_QM_DCACHE_PREF_L1_WINDOW_LIMIT_L1_INC_LOW_TH_M 0xF000000
#define TPC_QM_DCACHE_PREF_L1_WINDOW_LIMIT_L1_INC_UPPER_TH_S 28
#define TPC_QM_DCACHE_PREF_L1_WINDOW_LIMIT_L1_INC_UPPER_TH_M 0xF0000000

/* TPC_QM_DCACHE_PREF_L2_WINDOW_LIMIT */
#define TPC_QM_DCACHE_PREF_L2_WINDOW_LIMIT_L2_PREF_WINDOW_MAX_S 0
#define TPC_QM_DCACHE_PREF_L2_WINDOW_LIMIT_L2_PREF_WINDOW_MAX_M 0xFF
#define TPC_QM_DCACHE_PREF_L2_WINDOW_LIMIT_L2_PREF_WINDOW_MIN_S 8
#define TPC_QM_DCACHE_PREF_L2_WINDOW_LIMIT_L2_PREF_WINDOW_MIN_M 0xFF00
#define TPC_QM_DCACHE_PREF_L2_WINDOW_LIMIT_L2_SUM_WINDOW_LIMIT_S 16
#define TPC_QM_DCACHE_PREF_L2_WINDOW_LIMIT_L2_SUM_WINDOW_LIMIT_M 0xFF0000
#define TPC_QM_DCACHE_PREF_L2_WINDOW_LIMIT_L2_INC_LOW_TH_S 24
#define TPC_QM_DCACHE_PREF_L2_WINDOW_LIMIT_L2_INC_LOW_TH_M 0xF000000
#define TPC_QM_DCACHE_PREF_L2_WINDOW_LIMIT_L2_INC_UPPER_TH_S 28
#define TPC_QM_DCACHE_PREF_L2_WINDOW_LIMIT_L2_INC_UPPER_TH_M 0xF0000000

/* TPC_QM_DCACHE_STALL_LENGTH_THR */
#define TPC_QM_DCACHE_STALL_LENGTH_THR_PREF_L1_TH_S 0
#define TPC_QM_DCACHE_STALL_LENGTH_THR_PREF_L1_TH_M 0xFFFF
#define TPC_QM_DCACHE_STALL_LENGTH_THR_PREF_L2_TH_S 16
#define TPC_QM_DCACHE_STALL_LENGTH_THR_PREF_L2_TH_M 0xFFFF0000

/* TPC_QM_IRF44_SAT */
#define TPC_QM_IRF44_SAT_EN_S 0
#define TPC_QM_IRF44_SAT_EN_M 0x1

/* TPC_QM_IRF44_SAT_LOW */
#define TPC_QM_IRF44_SAT_LOW_VAL_S 0
#define TPC_QM_IRF44_SAT_LOW_VAL_M 0xFFFFFFFF

/* TPC_QM_IRF44_SAT_HIGH */
#define TPC_QM_IRF44_SAT_HIGH_VAL_S 0
#define TPC_QM_IRF44_SAT_HIGH_VAL_M 0xFFF

/* TPC_QM_TSB_ST_DIRECT_MODE */
#define TPC_QM_TSB_ST_DIRECT_MODE_VAL_S 0
#define TPC_QM_TSB_ST_DIRECT_MODE_VAL_M 0x3

#endif /* ASIC_REG_TPC_QM_MASKS_H_ */
