/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_XBAR_MESH_PLL_ASIF_SLV_REGS_H_
#define ASIC_REG_DCORE0_XBAR_MESH_PLL_ASIF_SLV_REGS_H_

/*
 *****************************************
 *   DCORE0_XBAR_MESH_PLL_ASIF_SLV
 *   (Prototype: ASIF_SLV)
 *****************************************
 */

#define mmDCORE0_XBAR_MESH_PLL_ASIF_SLV_ASIF_SLV_STATUS 0x4D44360

#define mmDCORE0_XBAR_MESH_PLL_ASIF_SLV_ASIF_SLV_CFG 0x4D44364

#define mmDCORE0_XBAR_MESH_PLL_ASIF_SLV_ASIF_SLV_ERROR 0x4D44368

#define mmDCORE0_XBAR_MESH_PLL_ASIF_SLV_ASIF_SLV_INTR_MASK 0x4D4436C

#define mmDCORE0_XBAR_MESH_PLL_ASIF_SLV_ASIF_CORE_CFG 0x4D44370

#define mmDCORE0_XBAR_MESH_PLL_ASIF_SLV_ASIF_CORE_DBG_CNT 0x4D44374

#define mmDCORE0_XBAR_MESH_PLL_ASIF_SLV_ASIF_CORE_DBG_CNT_CLR 0x4D44378

#define mmDCORE0_XBAR_MESH_PLL_ASIF_SLV_ASIF_CORE_TIMEOUT_CFG 0x4D4437C

#define mmDCORE0_XBAR_MESH_PLL_ASIF_SLV_ASIF_ERR_INTR_CAUSE 0x4D44380

#define mmDCORE0_XBAR_MESH_PLL_ASIF_SLV_ASIF_ERR_INTR_CLEAR 0x4D44384

#define mmDCORE0_XBAR_MESH_PLL_ASIF_SLV_ASIF_ERR_INTR_MASK 0x4D44388

#define mmDCORE0_XBAR_MESH_PLL_ASIF_SLV_ASIF_SLV_DBG_0 0x4D44390

#define mmDCORE0_XBAR_MESH_PLL_ASIF_SLV_ASIF_SLV_DBG_1 0x4D44394

#endif /* ASIC_REG_DCORE0_XBAR_MESH_PLL_ASIF_SLV_REGS_H_ */
