/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_HBM_PHY_CHAN_CHAN0_DWORD0_MASKS_H_
#define ASIC_REG_HBM_PHY_CHAN_CHAN0_DWORD0_MASKS_H_

/*
 *****************************************
 *   HBM_PHY_CHAN_CHAN0_DWORD0
 *   (Prototype: HBM_PHY_P0_CHANX_DWORD)
 *****************************************
 */

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWREMAP */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWREMAP_BYTE0REMAP_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWREMAP_BYTE0REMAP_MASK 0xF
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWREMAP_BYTE1REMAP_SHIFT 4
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWREMAP_BYTE1REMAP_MASK 0xF0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWREMAP_BYTE2REMAP_SHIFT 8
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWREMAP_BYTE2REMAP_MASK 0xF00
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWREMAP_BYTE3REMAP_SHIFT 12
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWREMAP_BYTE3REMAP_MASK 0xF000

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWLANEDISLN15LN0 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLANEDISLN15LN0_DWLANEDISLN15LN0_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLANEDISLN15LN0_DWLANEDISLN15LN0_MASK 0xFFFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWLANEDISLN31LN16 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLANEDISLN31LN16_DWLANEDISLN31LN16_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLANEDISLN31LN16_DWLANEDISLN31LN16_MASK \
0xFFFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWLANEDISLN47LN32 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLANEDISLN47LN32_DWLANEDISLN47LN32_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLANEDISLN47LN32_DWLANEDISLN47LN32_MASK \
0xFFFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWERRSTATUS */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWERRSTATUS_PHYDERR_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWERRSTATUS_PHYDERR_MASK 0x1
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWERRSTATUS_RDPARERR_SHIFT 1
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWERRSTATUS_RDPARERR_MASK 0x2

/* HBM_PHY_CHAN_CHAN0_DWORD0_RSVDDWORD */
#define HBM_PHY_CHAN_CHAN0_DWORD0_RSVDDWORD_RSVDDWORD_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_RSVDDWORD_RSVDDWORD_MASK 0xFFFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DFIMRL_P0 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DFIMRL_P0_DFIMRL_P0_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DFIMRL_P0_DFIMRL_P0_MASK 0x1F

/* HBM_PHY_CHAN_CHAN0_DWORD0_RXCTRL_P0 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCTRL_P0_RXFIFOPOPADJ_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCTRL_P0_RXFIFOPOPADJ_MASK 0x3
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCTRL_P0_RXRDQSSEL_SHIFT 2
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCTRL_P0_RXRDQSSEL_MASK 0x4

/* HBM_PHY_CHAN_CHAN0_DWORD0_TXCTRL_P0 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXCTRL_P0_TXENSETUP_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXCTRL_P0_TXENSETUP_MASK 0x3
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXCTRL_P0_TXENHOLD_SHIFT 2
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXCTRL_P0_TXENHOLD_MASK 0xC

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLSEL */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLSEL_DWLCDLSEL_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLSEL_DWLCDLSEL_MASK 0x3

/* HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKMINDLY */
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKMINDLY_RXCLKMINDLY_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKMINDLY_RXCLKMINDLY_MASK 0x7F

/* HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKNMINDLY */
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKNMINDLY_RXCLKNMINDLY_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKNMINDLY_RXCLKNMINDLY_MASK 0x7F

/* HBM_PHY_CHAN_CHAN0_DWORD0_TXDQMINDLY */
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXDQMINDLY_TXDQMINDLY_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXDQMINDLY_TXDQMINDLY_MASK 0xFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKMAXDLY */
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKMAXDLY_RXCLKMAXDLY_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKMAXDLY_RXCLKMAXDLY_MASK 0x3F

/* HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKNMAXDLY */
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKNMAXDLY_RXCLKNMAXDLY_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKNMAXDLY_RXCLKNMAXDLY_MASK 0x3F

/* HBM_PHY_CHAN_CHAN0_DWORD0_TXDQMAXDLY */
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXDQMAXDLY_TXDQMAXDLY_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXDQMAXDLY_TXDQMAXDLY_MASK 0xFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKDLY_P0 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKDLY_P0_RXCLKDLY_P0_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKDLY_P0_RXCLKDLY_P0_MASK 0x3F

/* HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKNDLY_P0 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKNDLY_P0_RXCLKNDLY_P0_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKNDLY_P0_RXCLKNDLY_P0_MASK 0x3F

/* HBM_PHY_CHAN_CHAN0_DWORD0_TXDQSDLY_P0 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXDQSDLY_P0_TXDQSDLY_P0_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXDQSDLY_P0_TXDQSDLY_P0_MASK 0xFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_TXDQDLY_P0 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXDQDLY_P0_TXDQDLY_P0_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXDQDLY_P0_TXDQDLY_P0_MASK 0xFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLCTRL */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLCTRL_TXDQDLYUPD_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLCTRL_TXDQDLYUPD_MASK 0x1
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLCTRL_TXDQSDLYUPD_SHIFT 1
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLCTRL_TXDQSDLYUPD_MASK 0x2
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLCTRL_RXCLKDLYUPD_SHIFT 2
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLCTRL_RXCLKDLYUPD_MASK 0x4
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLCTRL_RXCLKNDLYUPD_SHIFT 3
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLCTRL_RXCLKNDLYUPD_MASK 0x8

/* HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKLCDL1UI */
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKLCDL1UI_RXCLKLCDL1UI_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKLCDL1UI_RXCLKLCDL1UI_MASK 0x3FF

/* HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKNLCDL1UI */
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKNLCDL1UI_RXCLKNLCDL1UI_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_RXCLKNLCDL1UI_RXCLKNLCDL1UI_MASK 0x3FF

/* HBM_PHY_CHAN_CHAN0_DWORD0_TXDQSLCDL1UI */
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXDQSLCDL1UI_TXDQSLCDL1UI_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXDQSLCDL1UI_TXDQSLCDL1UI_MASK 0x3FF

/* HBM_PHY_CHAN_CHAN0_DWORD0_TXDQLCDL1UI */
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXDQLCDL1UI_TXDQLCDL1UI_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_TXDQLCDL1UI_TXDQLCDL1UI_MASK 0x3FF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLCALPHDETOUT */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLCALPHDETOUT_DWLCDLCALPHDETOUT_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWLCDLCALPHDETOUT_DWLCDLCALPHDETOUT_MASK 0xF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDLYTESTCNTRINGOSC */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDLYTESTCNTRINGOSC_DWDLYTESTCNTRINGOSC_SHIFT \
0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDLYTESTCNTRINGOSC_DWDLYTESTCNTRINGOSC_MASK \
0xFFFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB0DATASEL_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB0DATASEL_MASK 0x7
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB0SERIALDATA_SHIFT 3
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB0SERIALDATA_MASK 0x8
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB1DATASEL_SHIFT 4
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB1DATASEL_MASK 0x70
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB1SERIALDATA_SHIFT 7
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB1SERIALDATA_MASK 0x80
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB2DATASEL_SHIFT 8
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB2DATASEL_MASK 0x700
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB2SERIALDATA_SHIFT 11
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB2SERIALDATA_MASK 0x800
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB3DATASEL_SHIFT 12
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB3DATASEL_MASK 0x7000
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB3SERIALDATA_SHIFT 15
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATACTRL_DWDB3SERIALDATA_MASK 0x8000

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDB0DATA0 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB0DATA0_DWDB0DATA0_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB0DATA0_DWDB0DATA0_MASK 0xFFFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDB0DATA1 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB0DATA1_DWDB0DATA1_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB0DATA1_DWDB0DATA1_MASK 0xF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDB1DATA0 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB1DATA0_DWDB1DATA0_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB1DATA0_DWDB1DATA0_MASK 0xFFFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDB1DATA1 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB1DATA1_DWDB1DATA1_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB1DATA1_DWDB1DATA1_MASK 0xF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDB2DATA0 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB2DATA0_DWDB2DATA0_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB2DATA0_DWDB2DATA0_MASK 0xFFFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDB2DATA1 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB2DATA1_DWDB2DATA1_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB2DATA1_DWDB2DATA1_MASK 0xF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDB3DATA0 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB3DATA0_DWDB3DATA0_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB3DATA0_DWDB3DATA0_MASK 0xFFFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDB3DATA1 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB3DATA1_DWDB3DATA1_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB3DATA1_DWDB3DATA1_MASK 0xF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDATASTATUS0 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATASTATUS0_DWDATAERR_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATASTATUS0_DWDATAERR_MASK 0x1
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATASTATUS0_DWDATAERRCNT_SHIFT 1
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATASTATUS0_DWDATAERRCNT_MASK 0x1E
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATASTATUS0_DWDATABEATERR_SHIFT 5
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATASTATUS0_DWDATABEATERR_MASK 0x60
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATASTATUS0_DWRDQSBITERR_SHIFT 7
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATASTATUS0_DWRDQSBITERR_MASK 0x180

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDATASTATUS1 */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATASTATUS1_DWREADDATA_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDATASTATUS1_DWREADDATA_MASK 0xFFFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDB0DATABITERR */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB0DATABITERR_DWDB0DATABITERR_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB0DATABITERR_DWDB0DATABITERR_MASK 0xFFFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDB1DATABITERR */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB1DATABITERR_DWDB1DATABITERR_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB1DATABITERR_DWDB1DATABITERR_MASK 0xFFFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDB2DATABITERR */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB2DATABITERR_DWDB2DATABITERR_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB2DATABITERR_DWDB2DATABITERR_MASK 0xFFFF

/* HBM_PHY_CHAN_CHAN0_DWORD0_DWDB3DATABITERR */
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB3DATABITERR_DWDB3DATABITERR_SHIFT 0
#define HBM_PHY_CHAN_CHAN0_DWORD0_DWDB3DATABITERR_DWDB3DATABITERR_MASK 0xFFFF

#endif /* ASIC_REG_HBM_PHY_CHAN_CHAN0_DWORD0_MASKS_H_ */
