/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_HBM_PHY_CHAN_CHAN0_AWORD_REGS_H_
#define ASIC_REG_HBM_PHY_CHAN_CHAN0_AWORD_REGS_H_

/*
 *****************************************
 *   HBM_PHY_CHAN_CHAN0_AWORD
 *   (Prototype: HBM_PHY_P0_CHANX_AWORD)
 *****************************************
 */

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWREMAP 0x2000

#define mmHBM_PHY_CHAN_CHAN0_AWORD_IOCTRL 0x2004

#define mmHBM_PHY_CHAN_CHAN0_AWORD_REMAPCTRL 0x2008

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWLANEDISLN15LN0 0x200C

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWLANEDISLN23LN16 0x2010

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWERRSTATUS 0x2014

#define mmHBM_PHY_CHAN_CHAN0_AWORD_RSVDAWORD 0x2018

#define mmHBM_PHY_CHAN_CHAN0_AWORD_PHYCTLUPDGOODCTR 0x201C

#define mmHBM_PHY_CHAN_CHAN0_AWORD_PHYCTLUPDFAILCTR 0x2020

#define mmHBM_PHY_CHAN_CHAN0_AWORD_CTLPHYUPDGOODCTR 0x2024

#define mmHBM_PHY_CHAN_CHAN0_AWORD_CHANENABLE 0x2028

#define mmHBM_PHY_CHAN_CHAN0_AWORD_CMDRDPTRINITVAL_P0 0x202C

#define mmHBM_PHY_CHAN_CHAN0_AWORD_ACRDLAT 0x2030

#define mmHBM_PHY_CHAN_CHAN0_AWORD_RESETFIFO 0x2034

#define mmHBM_PHY_CHAN_CHAN0_AWORD_RXPWRDN 0x2038

#define mmHBM_PHY_CHAN_CHAN0_AWORD_LOOPBACKCTRL 0x203C

#define mmHBM_PHY_CHAN_CHAN0_AWORD_DFIPHYUPD 0x2040

#define mmHBM_PHY_CHAN_CHAN0_AWORD_PHYPERFCTREN 0x2044

#define mmHBM_PHY_CHAN_CHAN0_AWORD_CALCTRL 0x2048

#define mmHBM_PHY_CHAN_CHAN0_AWORD_DWORDTXCALDATOVR 0x204C

#define mmHBM_PHY_CHAN_CHAN0_AWORD_DWORDTXCALSTROBEOVR 0x2050

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWTXCALDATOVR 0x2054

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWTXCALSTROBEOVR 0x2058

#define mmHBM_PHY_CHAN_CHAN0_AWORD_LCDLCALPHASE 0x205C

#define mmHBM_PHY_CHAN_CHAN0_AWORD_LCDLCALCTRL 0x2060

#define mmHBM_PHY_CHAN_CHAN0_AWORD_LCDLTRAINPARAM 0x2064

#define mmHBM_PHY_CHAN_CHAN0_AWORD_LCDLGAINCTL_P0 0x2068

#define mmHBM_PHY_CHAN_CHAN0_AWORD_LCDLLOCKPARAM_P0 0x206C

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWLCDLSEL 0x2074

#define mmHBM_PHY_CHAN_CHAN0_AWORD_DLYTESTSEQ 0x2078

#define mmHBM_PHY_CHAN_CHAN0_AWORD_DLYTESTCNTDFICLKIV 0x207C

#define mmHBM_PHY_CHAN_CHAN0_AWORD_TXACMINDLY 0x2080

#define mmHBM_PHY_CHAN_CHAN0_AWORD_TXACMAXDLY 0x2084

#define mmHBM_PHY_CHAN_CHAN0_AWORD_TXACDLY_P0 0x2088

#define mmHBM_PHY_CHAN_CHAN0_AWORD_TXCKDLY_P0 0x208C

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWLCDLCTRL 0x2094

#define mmHBM_PHY_CHAN_CHAN0_AWORD_TXACLCDL1UI 0x2098

#define mmHBM_PHY_CHAN_CHAN0_AWORD_TXCKLCDL1UI 0x209C

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWLCDLCALPHDETOUT 0x20A0

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWDLYTESTCNTRINGOSC 0x20A4

#define mmHBM_PHY_CHAN_CHAN0_AWORD_DLYTESTCNTDFICLK 0x20A8

#define mmHBM_PHY_CHAN_CHAN0_AWORD_DRAMPARAM0_P0 0x20AC

#define mmHBM_PHY_CHAN_CHAN0_AWORD_DRAMPARAM1_P0 0x20B0

#define mmHBM_PHY_CHAN_CHAN0_AWORD_DATACTRL 0x20B4

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWDATACTRL 0x20B8

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWDATA0 0x20BC

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWDATA1 0x20C0

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWDATASTATUS0 0x20C4

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWDATASTATUS1 0x20C8

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWDATABITERR0 0x20CC

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWDATABITERR1 0x20D0

#define mmHBM_PHY_CHAN_CHAN0_AWORD_RDQSCTRL 0x20D4

#define mmHBM_PHY_CHAN_CHAN0_AWORD_AWDATA2 0x20D8

#endif /* ASIC_REG_HBM_PHY_CHAN_CHAN0_AWORD_REGS_H_ */
