/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC0_PHY_MASKS_H_
#define ASIC_REG_NIC0_PHY_MASKS_H_

/*
 *****************************************
 *   NIC0_PHY
 *   (Prototype: PRT_PHY)
 *****************************************
 */

/* NIC0_PHY_PHY_RX_STS */
#define NIC0_PHY_PHY_RX_STS_PHY_READY_SHIFT 0
#define NIC0_PHY_PHY_RX_STS_PHY_READY_MASK 0x1
#define NIC0_PHY_PHY_RX_STS_SIGNAL_DETECT_SHIFT 1
#define NIC0_PHY_PHY_RX_STS_SIGNAL_DETECT_MASK 0x2
#define NIC0_PHY_PHY_RX_STS_PLL_LOCK_SHIFT 2
#define NIC0_PHY_PHY_RX_STS_PLL_LOCK_MASK 0x4
#define NIC0_PHY_PHY_RX_STS_PHY_RX_CLK_TICK_SHIFT 3
#define NIC0_PHY_PHY_RX_STS_PHY_RX_CLK_TICK_MASK 0x8

/* NIC0_PHY_PHY_RX_CFG */
#define NIC0_PHY_PHY_RX_CFG_SW_PHY_READY_SHIFT 0
#define NIC0_PHY_PHY_RX_CFG_SW_PHY_READY_MASK 0x1
#define NIC0_PHY_PHY_RX_CFG_SW_PHY_READY_OVERRIDE_SHIFT 1
#define NIC0_PHY_PHY_RX_CFG_SW_PHY_READY_OVERRIDE_MASK 0x2

/* NIC0_PHY_PHY_TX_STS */
#define NIC0_PHY_PHY_TX_STS_PRT_TX_CLK_TICK_SHIFT 0
#define NIC0_PHY_PHY_TX_STS_PRT_TX_CLK_TICK_MASK 0x1
#define NIC0_PHY_PHY_TX_STS_PLL_LOCK_SHIFT 1
#define NIC0_PHY_PHY_TX_STS_PLL_LOCK_MASK 0x2

/* NIC0_PHY_PHY_RST_CFG */
#define NIC0_PHY_PHY_RST_CFG_PHY_CFG_SW_RST_N_SHIFT 0
#define NIC0_PHY_PHY_RST_CFG_PHY_CFG_SW_RST_N_MASK 0x1

/* NIC0_PHY_PHY_CFG_ADDR */
#define NIC0_PHY_PHY_CFG_ADDR_EN_PHY0_ADDR_OVRD_SHIFT 0
#define NIC0_PHY_PHY_CFG_ADDR_EN_PHY0_ADDR_OVRD_MASK 0x1
#define NIC0_PHY_PHY_CFG_ADDR_EN_PHY1_ADDR_OVRD_SHIFT 1
#define NIC0_PHY_PHY_CFG_ADDR_EN_PHY1_ADDR_OVRD_MASK 0x2
#define NIC0_PHY_PHY_CFG_ADDR_ADDR_OVRD_SHIFT 16
#define NIC0_PHY_PHY_CFG_ADDR_ADDR_OVRD_MASK 0xFFFF0000

/* NIC0_PHY_PHY_LINK_STS_INTR */
#define NIC0_PHY_PHY_LINK_STS_INTR_MASK_SHIFT 0
#define NIC0_PHY_PHY_LINK_STS_INTR_MASK_MASK 0x1
#define NIC0_PHY_PHY_LINK_STS_INTR_CLEAR_SHIFT 1
#define NIC0_PHY_PHY_LINK_STS_INTR_CLEAR_MASK 0x2

/* NIC0_PHY_PHY_IDDQ */
#define NIC0_PHY_PHY_IDDQ_IDDQ_SHIFT 0
#define NIC0_PHY_PHY_IDDQ_IDDQ_MASK 0x1

/* NIC0_PHY_PHY_ASYNC_LANE_SWAP */
#define NIC0_PHY_PHY_ASYNC_LANE_SWAP_SERDES0_TX0_SWAP_ID_SHIFT 0
#define NIC0_PHY_PHY_ASYNC_LANE_SWAP_SERDES0_TX0_SWAP_ID_MASK 0x3
#define NIC0_PHY_PHY_ASYNC_LANE_SWAP_SERDES0_TX1_SWAP_ID_SHIFT 2
#define NIC0_PHY_PHY_ASYNC_LANE_SWAP_SERDES0_TX1_SWAP_ID_MASK 0xC
#define NIC0_PHY_PHY_ASYNC_LANE_SWAP_SERDES1_TX0_SWAP_ID_SHIFT 4
#define NIC0_PHY_PHY_ASYNC_LANE_SWAP_SERDES1_TX0_SWAP_ID_MASK 0x30
#define NIC0_PHY_PHY_ASYNC_LANE_SWAP_SERDES1_TX1_SWAP_ID_SHIFT 6
#define NIC0_PHY_PHY_ASYNC_LANE_SWAP_SERDES1_TX1_SWAP_ID_MASK 0xC0

#endif /* ASIC_REG_NIC0_PHY_MASKS_H_ */
