/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_ARC_AF_ENG_MASKS_H_
#define ASIC_REG_ARC_AF_ENG_MASKS_H_

/*
 *****************************************
 *   ARC_AF_ENG
 *   (Prototype: ARC_AF_ENG)
 *****************************************
 */

/* ARC_AF_ENG_SB_MAX_SIZE */
#define ARC_AF_ENG_SB_MAX_SIZE_MS_DATA_S 0
#define ARC_AF_ENG_SB_MAX_SIZE_MS_DATA_M 0xFFFF
#define ARC_AF_ENG_SB_MAX_SIZE_MS_MD_S 16
#define ARC_AF_ENG_SB_MAX_SIZE_MS_MD_M 0xFFFF0000

/* ARC_AF_ENG_SB_FORCE_MISS */
#define ARC_AF_ENG_SB_FORCE_MISS_FMISS_S 0
#define ARC_AF_ENG_SB_FORCE_MISS_FMISS_M 0x1

/* ARC_AF_ENG_SB_MAX */
#define ARC_AF_ENG_SB_MAX_OS_S 0
#define ARC_AF_ENG_SB_MAX_OS_M 0xFFFF

/* ARC_AF_ENG_SB_RL */
#define ARC_AF_ENG_SB_RL_RATE_LIMITER_EN_S 0
#define ARC_AF_ENG_SB_RL_RATE_LIMITER_EN_M 0x1
#define ARC_AF_ENG_SB_RL_RL_SATURATION_S 1
#define ARC_AF_ENG_SB_RL_RL_SATURATION_M 0x1FE
#define ARC_AF_ENG_SB_RL_RL_TIMEOUT_S 9
#define ARC_AF_ENG_SB_RL_RL_TIMEOUT_M 0x1FE00

/* ARC_AF_ENG_SB_HALT */
#define ARC_AF_ENG_SB_HALT_VAL_S 0
#define ARC_AF_ENG_SB_HALT_VAL_M 0x1

/* ARC_AF_ENG_DCCM_HALT */
#define ARC_AF_ENG_DCCM_HALT_VAL_S 0
#define ARC_AF_ENG_DCCM_HALT_VAL_M 0x1

/* ARC_AF_ENG_SB_ARCACHE */
#define ARC_AF_ENG_SB_ARCACHE_ARCACHE_S 0
#define ARC_AF_ENG_SB_ARCACHE_ARCACHE_M 0x7F
#define ARC_AF_ENG_SB_ARCACHE_ARPROT_S 8
#define ARC_AF_ENG_SB_ARCACHE_ARPROT_M 0xFFFF00

/* ARC_AF_ENG_SB_OCCUPANCY */
#define ARC_AF_ENG_SB_OCCUPANCY_VAL_S 0
#define ARC_AF_ENG_SB_OCCUPANCY_VAL_M 0xFFFFFFFF

/* ARC_AF_ENG_SB_INFLIGHTS */
#define ARC_AF_ENG_SB_INFLIGHTS_VAL_S 0
#define ARC_AF_ENG_SB_INFLIGHTS_VAL_M 0xFFFFFFFF

/* ARC_AF_ENG_SB_PROT */
#define ARC_AF_ENG_SB_PROT_PRIV_S 0
#define ARC_AF_ENG_SB_PROT_PRIV_M 0x1

/* ARC_AF_ENG_SB_AXI_128BYTE */
#define ARC_AF_ENG_SB_AXI_128BYTE_EN_S 0
#define ARC_AF_ENG_SB_AXI_128BYTE_EN_M 0x1

/* ARC_AF_ENG_AF_STATUS_REG */
#define ARC_AF_ENG_AF_STATUS_REG_STATE_S 0
#define ARC_AF_ENG_AF_STATUS_REG_STATE_M 0x7
#define ARC_AF_ENG_AF_STATUS_REG_FULLNESS_S 4
#define ARC_AF_ENG_AF_STATUS_REG_FULLNESS_M 0xFFFF0

/* ARC_AF_ENG_AF_INTR_CAUSE */
#define ARC_AF_ENG_AF_INTR_CAUSE_SLV_ERR_LEGACY_S 0
#define ARC_AF_ENG_AF_INTR_CAUSE_SLV_ERR_LEGACY_M 0x1
#define ARC_AF_ENG_AF_INTR_CAUSE_SLV_ERR_S 1
#define ARC_AF_ENG_AF_INTR_CAUSE_SLV_ERR_M 0x2
#define ARC_AF_ENG_AF_INTR_CAUSE_RR_DBG_S 2
#define ARC_AF_ENG_AF_INTR_CAUSE_RR_DBG_M 0x4
#define ARC_AF_ENG_AF_INTR_CAUSE_NUM_ERR_S 3
#define ARC_AF_ENG_AF_INTR_CAUSE_NUM_ERR_M 0x8
#define ARC_AF_ENG_AF_INTR_CAUSE_DCCM_ERR_S 4
#define ARC_AF_ENG_AF_INTR_CAUSE_DCCM_ERR_M 0x10
#define ARC_AF_ENG_AF_INTR_CAUSE_LBW_STALL_S 5
#define ARC_AF_ENG_AF_INTR_CAUSE_LBW_STALL_M 0x20
#define ARC_AF_ENG_AF_INTR_CAUSE_CNTX_S 16
#define ARC_AF_ENG_AF_INTR_CAUSE_CNTX_M 0xFFFF0000

/* ARC_AF_ENG_AF_INTR_MASK */
#define ARC_AF_ENG_AF_INTR_MASK_SLV_ERR_LEGACY_S 0
#define ARC_AF_ENG_AF_INTR_MASK_SLV_ERR_LEGACY_M 0x1
#define ARC_AF_ENG_AF_INTR_MASK_SLV_ERR_S 1
#define ARC_AF_ENG_AF_INTR_MASK_SLV_ERR_M 0x2
#define ARC_AF_ENG_AF_INTR_MASK_RR_DBG_S 2
#define ARC_AF_ENG_AF_INTR_MASK_RR_DBG_M 0x4
#define ARC_AF_ENG_AF_INTR_MASK_NUM_ERR_S 3
#define ARC_AF_ENG_AF_INTR_MASK_NUM_ERR_M 0x8
#define ARC_AF_ENG_AF_INTR_MASK_DCCM_ERR_S 4
#define ARC_AF_ENG_AF_INTR_MASK_DCCM_ERR_M 0x10
#define ARC_AF_ENG_AF_INTR_MASK_LBW_STALL_ERR_S 5
#define ARC_AF_ENG_AF_INTR_MASK_LBW_STALL_ERR_M 0x20

/* ARC_AF_ENG_AF_INTR_CLEAR */
#define ARC_AF_ENG_AF_INTR_CLEAR_SLV_ERR_LEGACY_S 0
#define ARC_AF_ENG_AF_INTR_CLEAR_SLV_ERR_LEGACY_M 0x1
#define ARC_AF_ENG_AF_INTR_CLEAR_SLV_ERR_S 1
#define ARC_AF_ENG_AF_INTR_CLEAR_SLV_ERR_M 0x2
#define ARC_AF_ENG_AF_INTR_CLEAR_RR_DBG_S 2
#define ARC_AF_ENG_AF_INTR_CLEAR_RR_DBG_M 0x4
#define ARC_AF_ENG_AF_INTR_CLEAR_NUM_ERR_S 3
#define ARC_AF_ENG_AF_INTR_CLEAR_NUM_ERR_M 0x8
#define ARC_AF_ENG_AF_INTR_CLEAR_DCCM_ERR_S 4
#define ARC_AF_ENG_AF_INTR_CLEAR_DCCM_ERR_M 0x10
#define ARC_AF_ENG_AF_INTR_CLEAR_LBW_STALL_ERR_S 5
#define ARC_AF_ENG_AF_INTR_CLEAR_LBW_STALL_ERR_M 0x20

/* ARC_AF_ENG_SB_CFG_MISC */
#define ARC_AF_ENG_SB_CFG_MISC_ENABLE_CGATE_S 0
#define ARC_AF_ENG_SB_CFG_MISC_ENABLE_CGATE_M 0x1

/* ARC_AF_ENG_SB_DBG_STATUS */
#define ARC_AF_ENG_SB_DBG_STATUS_DBG_NOC_2_SB_BP_S 0
#define ARC_AF_ENG_SB_DBG_STATUS_DBG_NOC_2_SB_BP_M 0x1
#define ARC_AF_ENG_SB_DBG_STATUS_ALMOST_FULL0_S 1
#define ARC_AF_ENG_SB_DBG_STATUS_ALMOST_FULL0_M 0x2
#define ARC_AF_ENG_SB_DBG_STATUS_ALMOST_FULL1_S 2
#define ARC_AF_ENG_SB_DBG_STATUS_ALMOST_FULL1_M 0x4
#define ARC_AF_ENG_SB_DBG_STATUS_ALMOST_FULL2_S 3
#define ARC_AF_ENG_SB_DBG_STATUS_ALMOST_FULL2_M 0x8
#define ARC_AF_ENG_SB_DBG_STATUS_ALMOST_FULL3_S 4
#define ARC_AF_ENG_SB_DBG_STATUS_ALMOST_FULL3_M 0x10
#define ARC_AF_ENG_SB_DBG_STATUS_INITIATOR_BP_S 5
#define ARC_AF_ENG_SB_DBG_STATUS_INITIATOR_BP_M 0x20
#define ARC_AF_ENG_SB_DBG_STATUS_INITIATOR_BP_SB_FULL_S 6
#define ARC_AF_ENG_SB_DBG_STATUS_INITIATOR_BP_SB_FULL_M 0x40

/* ARC_AF_ENG_SB_MON_FIRST */
#define ARC_AF_ENG_SB_MON_FIRST_CNTX_S 0
#define ARC_AF_ENG_SB_MON_FIRST_CNTX_M 0xFFFF

/* ARC_AF_ENG_SB_MON_LAST */
#define ARC_AF_ENG_SB_MON_LAST_CNTX_S 0
#define ARC_AF_ENG_SB_MON_LAST_CNTX_M 0xFFFF

/* ARC_AF_ENG_AF_HOST_STREAM_BASE_L */
#define ARC_AF_ENG_AF_HOST_STREAM_BASE_L_LSB_S 0
#define ARC_AF_ENG_AF_HOST_STREAM_BASE_L_LSB_M 0xFFFFFFFF

/* ARC_AF_ENG_AF_HOST_STREAM_BASE_H */
#define ARC_AF_ENG_AF_HOST_STREAM_BASE_H_MSB_S 0
#define ARC_AF_ENG_AF_HOST_STREAM_BASE_H_MSB_M 0xFFFFFFFF

/* ARC_AF_ENG_AF_HOST_STREAM_SIZE */
#define ARC_AF_ENG_AF_HOST_STREAM_SIZE_LOG2_SIZE_S 0
#define ARC_AF_ENG_AF_HOST_STREAM_SIZE_LOG2_SIZE_M 0x1F

/* ARC_AF_ENG_AF_DCCM_STREAM_ADDR */
#define ARC_AF_ENG_AF_DCCM_STREAM_ADDR_ABASE_S 0
#define ARC_AF_ENG_AF_DCCM_STREAM_ADDR_ABASE_M 0xFFFF
#define ARC_AF_ENG_AF_DCCM_STREAM_ADDR_ASIZE_S 16
#define ARC_AF_ENG_AF_DCCM_STREAM_ADDR_ASIZE_M 0xFFFF0000

/* ARC_AF_ENG_AF_HOST_STREAM_PI */
#define ARC_AF_ENG_AF_HOST_STREAM_PI_OFFSET_S 0
#define ARC_AF_ENG_AF_HOST_STREAM_PI_OFFSET_M 0xFFFFFFFF

/* ARC_AF_ENG_AF_HOST_STREAM_CI */
#define ARC_AF_ENG_AF_HOST_STREAM_CI_OFFSET_S 0
#define ARC_AF_ENG_AF_HOST_STREAM_CI_OFFSET_M 0xFFFFFFFF

/* ARC_AF_ENG_AF_DCCM_STREAM_PI */
#define ARC_AF_ENG_AF_DCCM_STREAM_PI_PI_S 0
#define ARC_AF_ENG_AF_DCCM_STREAM_PI_PI_M 0xFFFF

/* ARC_AF_ENG_AF_DCCM_STREAM_CI */
#define ARC_AF_ENG_AF_DCCM_STREAM_CI_CI_S 0
#define ARC_AF_ENG_AF_DCCM_STREAM_CI_CI_M 0xFFFF

/* ARC_AF_ENG_AF_DCCM_MIN_THRESHOLD */
#define ARC_AF_ENG_AF_DCCM_MIN_THRESHOLD_VAL_S 0
#define ARC_AF_ENG_AF_DCCM_MIN_THRESHOLD_VAL_M 0xFFFFFFFF

/* ARC_AF_ENG_AF_STREAM_GLOBAL */
#define ARC_AF_ENG_AF_STREAM_GLOBAL_SPRIORITY_S 0
#define ARC_AF_ENG_AF_STREAM_GLOBAL_SPRIORITY_M 0x3

/* ARC_AF_ENG_AF_STREAM_MASK */
#define ARC_AF_ENG_AF_STREAM_MASK_VAL_S 0
#define ARC_AF_ENG_AF_STREAM_MASK_VAL_M 0x1

/* ARC_AF_ENG_AF_PRIO_WEIGHT */
#define ARC_AF_ENG_AF_PRIO_WEIGHT_VAL_S 0
#define ARC_AF_ENG_AF_PRIO_WEIGHT_VAL_M 0xFF

/* ARC_AF_ENG_AF_WR_DCCM */
#define ARC_AF_ENG_AF_WR_DCCM_OS_LIMIT_S 0
#define ARC_AF_ENG_AF_WR_DCCM_OS_LIMIT_M 0x1F
#define ARC_AF_ENG_AF_WR_DCCM_FIXED_ID_S 5
#define ARC_AF_ENG_AF_WR_DCCM_FIXED_ID_M 0x20
#define ARC_AF_ENG_AF_WR_DCCM_REORDER_EN_S 6
#define ARC_AF_ENG_AF_WR_DCCM_REORDER_EN_M 0x40
#define ARC_AF_ENG_AF_WR_DCCM_NICAG_DIS_S 7
#define ARC_AF_ENG_AF_WR_DCCM_NICAG_DIS_M 0x80

/* ARC_AF_ENG_AF_LBW_STALL */
#define ARC_AF_ENG_AF_LBW_STALL_STALL_CNTR_S 0
#define ARC_AF_ENG_AF_LBW_STALL_STALL_CNTR_M 0xFFFFFF
#define ARC_AF_ENG_AF_LBW_STALL_FIFO_THR_S 24
#define ARC_AF_ENG_AF_LBW_STALL_FIFO_THR_M 0x1F000000
#define ARC_AF_ENG_AF_LBW_STALL_STALL_EN_S 31
#define ARC_AF_ENG_AF_LBW_STALL_STALL_EN_M 0x80000000

/* ARC_AF_ENG_AF_DBG_PNC */
#define ARC_AF_ENG_AF_DBG_PNC_VAL_S 0
#define ARC_AF_ENG_AF_DBG_PNC_VAL_M 0xFFFFFFFF

/* ARC_AF_ENG_AF_DBG_STATE */
#define ARC_AF_ENG_AF_DBG_STATE_VAL_S 0
#define ARC_AF_ENG_AF_DBG_STATE_VAL_M 0xFFFFFFFF

#endif /* ASIC_REG_ARC_AF_ENG_MASKS_H_ */
