/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_ARC_AF_ENG_SEC_USER_ADAPT_REGS_H_
#define ASIC_REG_ARC_AF_ENG_SEC_USER_ADAPT_REGS_H_

/*
 *****************************************
 *   ARC_AF_ENG_SEC_USER_ADAPT
 *   (Prototype: AXUSER_HBW)
 *****************************************
 */

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_MMU_BYPASS 0x0

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_ASID 0x4

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_QOS 0x8

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_MCID 0xC

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_CLASS_TYPE 0x10

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_REDUCTION 0x14

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_ATOMIC 0x18

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_DOWN_CONV 0x1C

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_MMU_PF_EN 0x20

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_STRONG_ORDER 0x24

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_RESERVED 0x28

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_MMU_BYPASS_OVRD 0x30

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_ASID_OVRD 0x34

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_QOS_OVRD 0x38

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_MCID_OVRD 0x3C

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_CLASS_TYPE_OVRD 0x40

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_REDUCTION_OVRD 0x44

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_ATOMIC_OVRD 0x48

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_DOWN_CONV_OVRD 0x4C

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_MMU_PF_EN_OVRD 0x50

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_STRONG_ORDER_OVRD 0x54

#define mmARC_AF_ENG_SEC_USER_ADAPT_HB_RESERVED_OVRD 0x58

#endif /* ASIC_REG_ARC_AF_ENG_SEC_USER_ADAPT_REGS_H_ */
