/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_EDMA_CHN_MASKS_H_
#define ASIC_REG_EDMA_CHN_MASKS_H_

/*
 *****************************************
 *   EDMA_CHN
 *   (Prototype: EDMA_CHN)
 *****************************************
 */

/* EDMA_CHN_IDLE_IND_MASK */
#define EDMA_CHN_IDLE_IND_MASK_DESC_S 0
#define EDMA_CHN_IDLE_IND_MASK_DESC_M 0x1
#define EDMA_CHN_IDLE_IND_MASK_COMP_S 1
#define EDMA_CHN_IDLE_IND_MASK_COMP_M 0x2
#define EDMA_CHN_IDLE_IND_MASK_INSTAGE_S 2
#define EDMA_CHN_IDLE_IND_MASK_INSTAGE_M 0x4
#define EDMA_CHN_IDLE_IND_MASK_CORE_S 3
#define EDMA_CHN_IDLE_IND_MASK_CORE_M 0x8

/* EDMA_CHN_HBW_AXCACHE */
#define EDMA_CHN_HBW_AXCACHE_RD_S 0
#define EDMA_CHN_HBW_AXCACHE_RD_M 0xF
#define EDMA_CHN_HBW_AXCACHE_WR_S 4
#define EDMA_CHN_HBW_AXCACHE_WR_M 0xF0

/* EDMA_CHN_LBW_AXCACHE */
#define EDMA_CHN_LBW_AXCACHE_RD_S 0
#define EDMA_CHN_LBW_AXCACHE_RD_M 0xF
#define EDMA_CHN_LBW_AXCACHE_WR_S 4
#define EDMA_CHN_LBW_AXCACHE_WR_M 0xF0

/* EDMA_CHN_PROT_PRIVLG */
#define EDMA_CHN_PROT_PRIVLG_VAL_S 0
#define EDMA_CHN_PROT_PRIVLG_VAL_M 0x1

/* EDMA_CHN_PROT_SECURE */
#define EDMA_CHN_PROT_SECURE_VAL_S 0
#define EDMA_CHN_PROT_SECURE_VAL_M 0x1

/* EDMA_CHN_ERR_ENABLE */
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_HBW_RD_RSP_ERR_S 0
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_HBW_RD_RSP_ERR_M 0x1
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_HBW_RD_RSP_ERR_S 1
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_HBW_RD_RSP_ERR_M 0x2
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENGINE_TIMEOUT_S 2
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENGINE_TIMEOUT_M 0x4
#define EDMA_CHN_ERR_ENABLE_EN_STALL_ENGINE_TIMEOUT_S 3
#define EDMA_CHN_ERR_ENABLE_EN_STALL_ENGINE_TIMEOUT_M 0x8
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_LBW_RD_RSP_ERR_S 4
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_LBW_RD_RSP_ERR_M 0x10
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_LBW_RD_RSP_ERR_S 5
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_LBW_RD_RSP_ERR_M 0x20
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_HBW_WR_RSP_ERR_S 6
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_HBW_WR_RSP_ERR_M 0x40
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_HBW_WR_RSP_ERR_S 7
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_HBW_WR_RSP_ERR_M 0x80
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_LBW_WR_RSP_ERR_S 8
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_LBW_WR_RSP_ERR_M 0x100
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_LBW_WR_RSP_ERR_S 9
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_LBW_WR_RSP_ERR_M 0x200
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_MSG_WR_ERR_S 10
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_MSG_WR_ERR_M 0x400
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_MSG_WR_ERR_S 11
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_MSG_WR_ERR_M 0x800
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_NAN_DETECT_S 12
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_NAN_DETECT_M 0x1000
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_NAN_DETECT_S 13
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_NAN_DETECT_M 0x2000
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_INF_DETECT_S 14
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_INF_DETECT_M 0x4000
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_INF_DETECT_S 15
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_INF_DETECT_M 0x8000
#define EDMA_CHN_ERR_ENABLE_EN_MSG_LBW_CH_NUM_EXCEED_S 16
#define EDMA_CHN_ERR_ENABLE_EN_MSG_LBW_CH_NUM_EXCEED_M 0x10000
#define EDMA_CHN_ERR_ENABLE_EN_STL_LBW_CH_NUM_EXCEED_S 17
#define EDMA_CHN_ERR_ENABLE_EN_STL_LBW_CH_NUM_EXCEED_M 0x20000
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_SRC_RANGE_ERR_S 18
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_SRC_RANGE_ERR_M 0x40000
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_SRC_RANGE_ERR_S 19
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_SRC_RANGE_ERR_M 0x80000
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_DST_RANGE_ERR_S 20
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_DST_RANGE_ERR_M 0x100000
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_DST_RANGE_ERR_S 21
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_DST_RANGE_ERR_M 0x200000
#define EDMA_CHN_ERR_ENABLE_EN_MSG_DESC_OVF_ERR_S 22
#define EDMA_CHN_ERR_ENABLE_EN_MSG_DESC_OVF_ERR_M 0x400000
#define EDMA_CHN_ERR_ENABLE_EN_STL_DESC_OVF_ERR_S 23
#define EDMA_CHN_ERR_ENABLE_EN_STL_DESC_OVF_ERR_M 0x800000
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_BAD_CONFIG_ERR_S 24
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_BAD_CONFIG_ERR_M 0x1000000
#define EDMA_CHN_ERR_ENABLE_EN_MSG_TE_DESC_FIFO_OVF_S 25
#define EDMA_CHN_ERR_ENABLE_EN_MSG_TE_DESC_FIFO_OVF_M 0x2000000
#define EDMA_CHN_ERR_ENABLE_EN_STL_TE_DESC_FIFO_OVF_S 26
#define EDMA_CHN_ERR_ENABLE_EN_STL_TE_DESC_FIFO_OVF_M 0x4000000
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_INF_INP_DETECT_S 27
#define EDMA_CHN_ERR_ENABLE_EN_MSG_ENG_INF_INP_DETECT_M 0x8000000
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_INF_INP_DETECT_S 28
#define EDMA_CHN_ERR_ENABLE_EN_STL_ENG_INF_INP_DETECT_M 0x10000000

/* EDMA_CHN_ERR_STATUS */
#define EDMA_CHN_ERR_STATUS_ENG_HBW_RD_RSP_ERR_S 0
#define EDMA_CHN_ERR_STATUS_ENG_HBW_RD_RSP_ERR_M 0x1
#define EDMA_CHN_ERR_STATUS_ENG_TIMEOUT_ERR_S 1
#define EDMA_CHN_ERR_STATUS_ENG_TIMEOUT_ERR_M 0x2
#define EDMA_CHN_ERR_STATUS_ENG_LBW_RD_RSP_ERR_S 2
#define EDMA_CHN_ERR_STATUS_ENG_LBW_RD_RSP_ERR_M 0x4
#define EDMA_CHN_ERR_STATUS_ENG_HBW_WR_RSP_ERR_S 3
#define EDMA_CHN_ERR_STATUS_ENG_HBW_WR_RSP_ERR_M 0x8
#define EDMA_CHN_ERR_STATUS_ENG_LBW_WR_RSP_ERR_S 4
#define EDMA_CHN_ERR_STATUS_ENG_LBW_WR_RSP_ERR_M 0x10
#define EDMA_CHN_ERR_STATUS_ENG_MSG_WR_ERR_S 5
#define EDMA_CHN_ERR_STATUS_ENG_MSG_WR_ERR_M 0x20
#define EDMA_CHN_ERR_STATUS_ENG_NAN_DET_S 6
#define EDMA_CHN_ERR_STATUS_ENG_NAN_DET_M 0x40
#define EDMA_CHN_ERR_STATUS_ENG_INF_DET_S 7
#define EDMA_CHN_ERR_STATUS_ENG_INF_DET_M 0x80
#define EDMA_CHN_ERR_STATUS_ENG_M_INF_DET_S 8
#define EDMA_CHN_ERR_STATUS_ENG_M_INF_DET_M 0x100
#define EDMA_CHN_ERR_STATUS_LBW_CHN_NUM_EXC_S 9
#define EDMA_CHN_ERR_STATUS_LBW_CHN_NUM_EXC_M 0x200
#define EDMA_CHN_ERR_STATUS_SRC_RANGE_ERR_S 10
#define EDMA_CHN_ERR_STATUS_SRC_RANGE_ERR_M 0x400
#define EDMA_CHN_ERR_STATUS_SRC_NAN_DET_S 11
#define EDMA_CHN_ERR_STATUS_SRC_NAN_DET_M 0x800
#define EDMA_CHN_ERR_STATUS_SRC_INF_DET_S 12
#define EDMA_CHN_ERR_STATUS_SRC_INF_DET_M 0x1000
#define EDMA_CHN_ERR_STATUS_SRC_M_INF_DET_S 13
#define EDMA_CHN_ERR_STATUS_SRC_M_INF_DET_M 0x2000
#define EDMA_CHN_ERR_STATUS_DST_RANGE_ERR_S 14
#define EDMA_CHN_ERR_STATUS_DST_RANGE_ERR_M 0x4000
#define EDMA_CHN_ERR_STATUS_DST_NAN_DET_S 15
#define EDMA_CHN_ERR_STATUS_DST_NAN_DET_M 0x8000
#define EDMA_CHN_ERR_STATUS_DST_INF_DET_S 16
#define EDMA_CHN_ERR_STATUS_DST_INF_DET_M 0x10000
#define EDMA_CHN_ERR_STATUS_DST_M_INF_DET_S 17
#define EDMA_CHN_ERR_STATUS_DST_M_INF_DET_M 0x20000
#define EDMA_CHN_ERR_STATUS_DESC_OVF_S 18
#define EDMA_CHN_ERR_STATUS_DESC_OVF_M 0x40000
#define EDMA_CHN_ERR_STATUS_ENG_BAD_CONFIG_ERR_S 19
#define EDMA_CHN_ERR_STATUS_ENG_BAD_CONFIG_ERR_M 0x80000
#define EDMA_CHN_ERR_STATUS_TE_DESC_FIFO_OVF_S 20
#define EDMA_CHN_ERR_STATUS_TE_DESC_FIFO_OVF_M 0x100000
#define EDMA_CHN_ERR_STATUS_ENG_INF_INPUT_DET_S 21
#define EDMA_CHN_ERR_STATUS_ENG_INF_INPUT_DET_M 0x200000
#define EDMA_CHN_ERR_STATUS_VALID_S 31
#define EDMA_CHN_ERR_STATUS_VALID_M 0x80000000

/* EDMA_CHN_ERR_CTX_ID */
#define EDMA_CHN_ERR_CTX_ID_VAL_S 0
#define EDMA_CHN_ERR_CTX_ID_VAL_M 0xFFFFFFFF

/* EDMA_CHN_ERR_MSG_ADDR_LO */
#define EDMA_CHN_ERR_MSG_ADDR_LO_VAL_S 0
#define EDMA_CHN_ERR_MSG_ADDR_LO_VAL_M 0xFFFFFFFF

/* EDMA_CHN_ERR_MSG_ADDR_HI */
#define EDMA_CHN_ERR_MSG_ADDR_HI_VAL_S 0
#define EDMA_CHN_ERR_MSG_ADDR_HI_VAL_M 0xFFFFFFFF

/* EDMA_CHN_CFG */
#define EDMA_CHN_CFG_HALT_S 0
#define EDMA_CHN_CFG_HALT_M 0x1
#define EDMA_CHN_CFG_FLUSH_S 1
#define EDMA_CHN_CFG_FLUSH_M 0x2

/* EDMA_CHN_STS */
#define EDMA_CHN_STS_IS_BUSY_S 0
#define EDMA_CHN_STS_IS_BUSY_M 0x1
#define EDMA_CHN_STS_IS_HALT_S 1
#define EDMA_CHN_STS_IS_HALT_M 0x2

/* EDMA_CHN_CFG1 */
#define EDMA_CHN_CFG1_STOP_ON_ERR_S 0
#define EDMA_CHN_CFG1_STOP_ON_ERR_M 0x1

/* EDMA_CHN_ERR_MSG_WDATA */
#define EDMA_CHN_ERR_MSG_WDATA_VAL_S 0
#define EDMA_CHN_ERR_MSG_WDATA_VAL_M 0xFFFFFFFF

/* EDMA_CHN_DBG_STS */
#define EDMA_CHN_DBG_STS_GSKT_EMPTY_S 0
#define EDMA_CHN_DBG_STS_GSKT_EMPTY_M 0x1
#define EDMA_CHN_DBG_STS_GSKT_FULL_S 1
#define EDMA_CHN_DBG_STS_GSKT_FULL_M 0x2
#define EDMA_CHN_DBG_STS_TE_CH_BUSY_S 2
#define EDMA_CHN_DBG_STS_TE_CH_BUSY_M 0x4
#define EDMA_CHN_DBG_STS_WR_COMP_FIFO_EMPTY_S 3
#define EDMA_CHN_DBG_STS_WR_COMP_FIFO_EMPTY_M 0x8
#define EDMA_CHN_DBG_STS_WR_COMP_FIFO_FULL_S 4
#define EDMA_CHN_DBG_STS_WR_COMP_FIFO_FULL_M 0x10
#define EDMA_CHN_DBG_STS_SRC_DESC_FIFO_EMPTY_S 5
#define EDMA_CHN_DBG_STS_SRC_DESC_FIFO_EMPTY_M 0x20
#define EDMA_CHN_DBG_STS_SRC_DESC_FIFO_FULL_S 6
#define EDMA_CHN_DBG_STS_SRC_DESC_FIFO_FULL_M 0x40
#define EDMA_CHN_DBG_STS_INSTAGE_FULL_S 7
#define EDMA_CHN_DBG_STS_INSTAGE_FULL_M 0x80
#define EDMA_CHN_DBG_STS_INSTAGE_EMPTY_S 8
#define EDMA_CHN_DBG_STS_INSTAGE_EMPTY_M 0x100
#define EDMA_CHN_DBG_STS_RD_AGU_CS_S 9
#define EDMA_CHN_DBG_STS_RD_AGU_CS_M 0x200
#define EDMA_CHN_DBG_STS_WR_AGU_CS_S 10
#define EDMA_CHN_DBG_STS_WR_AGU_CS_M 0x400
#define EDMA_CHN_DBG_STS_CORE_IDLE_STS_S 11
#define EDMA_CHN_DBG_STS_CORE_IDLE_STS_M 0x800
#define EDMA_CHN_DBG_STS_DESC_CNT_STS_S 12
#define EDMA_CHN_DBG_STS_DESC_CNT_STS_M 0x1F000
#define EDMA_CHN_DBG_STS_COMP_CNT_STS_S 17
#define EDMA_CHN_DBG_STS_COMP_CNT_STS_M 0x3E0000
#define EDMA_CHN_DBG_STS_WR_FIFO_FULL_S 22
#define EDMA_CHN_DBG_STS_WR_FIFO_FULL_M 0x400000

/* EDMA_CHN_STS_RD_CTX_SEL */
#define EDMA_CHN_STS_RD_CTX_SEL_VAL_S 0
#define EDMA_CHN_STS_RD_CTX_SEL_VAL_M 0x7
#define EDMA_CHN_STS_RD_CTX_SEL_STRIDE_S 8
#define EDMA_CHN_STS_RD_CTX_SEL_STRIDE_M 0x100

/* EDMA_CHN_STS_RD_CTX_SIZE */
#define EDMA_CHN_STS_RD_CTX_SIZE_VAL_S 0
#define EDMA_CHN_STS_RD_CTX_SIZE_VAL_M 0xFFFFFFFF

/* EDMA_CHN_STS_RD_CTX_BASE_LO */
#define EDMA_CHN_STS_RD_CTX_BASE_LO_VAL_S 0
#define EDMA_CHN_STS_RD_CTX_BASE_LO_VAL_M 0xFFFFFFFF

/* EDMA_CHN_STS_RD_CTX_BASE_HI */
#define EDMA_CHN_STS_RD_CTX_BASE_HI_VAL_S 0
#define EDMA_CHN_STS_RD_CTX_BASE_HI_VAL_M 0xFFFFFFFF

/* EDMA_CHN_STS_RD_CTX_ID */
#define EDMA_CHN_STS_RD_CTX_ID_VAL_S 0
#define EDMA_CHN_STS_RD_CTX_ID_VAL_M 0xFFFFFFFF

/* EDMA_CHN_STS_WR_CTX_SEL */
#define EDMA_CHN_STS_WR_CTX_SEL_VAL_S 0
#define EDMA_CHN_STS_WR_CTX_SEL_VAL_M 0x7
#define EDMA_CHN_STS_WR_CTX_SEL_STRIDE_S 8
#define EDMA_CHN_STS_WR_CTX_SEL_STRIDE_M 0x100

/* EDMA_CHN_STS_WR_CTX_SIZE */
#define EDMA_CHN_STS_WR_CTX_SIZE_VAL_S 0
#define EDMA_CHN_STS_WR_CTX_SIZE_VAL_M 0xFFFFFFFF

/* EDMA_CHN_STS_WR_CTX_BASE_LO */
#define EDMA_CHN_STS_WR_CTX_BASE_LO_VAL_S 0
#define EDMA_CHN_STS_WR_CTX_BASE_LO_VAL_M 0xFFFFFFFF

/* EDMA_CHN_STS_WR_CTX_BASE_HI */
#define EDMA_CHN_STS_WR_CTX_BASE_HI_VAL_S 0
#define EDMA_CHN_STS_WR_CTX_BASE_HI_VAL_M 0xFFFFFFFF

/* EDMA_CHN_STS_WR_CTX_ID */
#define EDMA_CHN_STS_WR_CTX_ID_VAL_S 0
#define EDMA_CHN_STS_WR_CTX_ID_VAL_M 0xFFFFFFFF

/* EDMA_CHN_PWRLP_STS0 */
#define EDMA_CHN_PWRLP_STS0_RLVL_S 0
#define EDMA_CHN_PWRLP_STS0_RLVL_M 0xFF
#define EDMA_CHN_PWRLP_STS0_WLVL_S 8
#define EDMA_CHN_PWRLP_STS0_WLVL_M 0xFF00
#define EDMA_CHN_PWRLP_STS0_RCNT_S 16
#define EDMA_CHN_PWRLP_STS0_RCNT_M 0xFF0000
#define EDMA_CHN_PWRLP_STS0_WCNT_S 24
#define EDMA_CHN_PWRLP_STS0_WCNT_M 0xFF000000

/* EDMA_CHN_PWRLP_STS1 */
#define EDMA_CHN_PWRLP_STS1_RFULL_S 0
#define EDMA_CHN_PWRLP_STS1_RFULL_M 0x1
#define EDMA_CHN_PWRLP_STS1_WFULL_S 1
#define EDMA_CHN_PWRLP_STS1_WFULL_M 0x2

/* EDMA_CHN_CONVERT_CFG */
#define EDMA_CHN_CONVERT_CFG_CLIP_INPUT_INF_S 0
#define EDMA_CHN_CONVERT_CFG_CLIP_INPUT_INF_M 0x1
#define EDMA_CHN_CONVERT_CFG_FP8_143_NO_INF_NAN_S 1
#define EDMA_CHN_CONVERT_CFG_FP8_143_NO_INF_NAN_M 0x6
#define EDMA_CHN_CONVERT_CFG_FP8_152_NO_INF_NAN_S 3
#define EDMA_CHN_CONVERT_CFG_FP8_152_NO_INF_NAN_M 0x18
#define EDMA_CHN_CONVERT_CFG_FTZ_EN_S 5
#define EDMA_CHN_CONVERT_CFG_FTZ_EN_M 0x20
#define EDMA_CHN_CONVERT_CFG_STOCH_FTZ_S 6
#define EDMA_CHN_CONVERT_CFG_STOCH_FTZ_M 0x40

/* EDMA_CHN_LFSR_CH_SEED */
#define EDMA_CHN_LFSR_CH_SEED_VAL_S 0
#define EDMA_CHN_LFSR_CH_SEED_VAL_M 0xFFFFFFFF

/* EDMA_CHN_ERR_INT_MASK */
#define EDMA_CHN_ERR_INT_MASK_ENG_HBW_RD_RSP_ERR_S 0
#define EDMA_CHN_ERR_INT_MASK_ENG_HBW_RD_RSP_ERR_M 0x1
#define EDMA_CHN_ERR_INT_MASK_ENG_TIMEOUT_ERR_S 1
#define EDMA_CHN_ERR_INT_MASK_ENG_TIMEOUT_ERR_M 0x2
#define EDMA_CHN_ERR_INT_MASK_ENG_LBW_RD_RSP_ERR_S 2
#define EDMA_CHN_ERR_INT_MASK_ENG_LBW_RD_RSP_ERR_M 0x4
#define EDMA_CHN_ERR_INT_MASK_ENG_HBW_WR_RSP_ERR_S 3
#define EDMA_CHN_ERR_INT_MASK_ENG_HBW_WR_RSP_ERR_M 0x8
#define EDMA_CHN_ERR_INT_MASK_ENG_LBW_WR_RSP_ERR_S 4
#define EDMA_CHN_ERR_INT_MASK_ENG_LBW_WR_RSP_ERR_M 0x10
#define EDMA_CHN_ERR_INT_MASK_ENG_MSG_WR_ERR_S 5
#define EDMA_CHN_ERR_INT_MASK_ENG_MSG_WR_ERR_M 0x20
#define EDMA_CHN_ERR_INT_MASK_ENG_NAN_DET_S 6
#define EDMA_CHN_ERR_INT_MASK_ENG_NAN_DET_M 0x40
#define EDMA_CHN_ERR_INT_MASK_ENG_INF_DET_S 7
#define EDMA_CHN_ERR_INT_MASK_ENG_INF_DET_M 0x80
#define EDMA_CHN_ERR_INT_MASK_ENG_M_INF_DET_S 8
#define EDMA_CHN_ERR_INT_MASK_ENG_M_INF_DET_M 0x100
#define EDMA_CHN_ERR_INT_MASK_LBW_CHN_NUM_EXC_S 9
#define EDMA_CHN_ERR_INT_MASK_LBW_CHN_NUM_EXC_M 0x200
#define EDMA_CHN_ERR_INT_MASK_SRC_RANGE_ERR_S 10
#define EDMA_CHN_ERR_INT_MASK_SRC_RANGE_ERR_M 0x400
#define EDMA_CHN_ERR_INT_MASK_SRC_NAN_DET_S 11
#define EDMA_CHN_ERR_INT_MASK_SRC_NAN_DET_M 0x800
#define EDMA_CHN_ERR_INT_MASK_SRC_INF_DET_S 12
#define EDMA_CHN_ERR_INT_MASK_SRC_INF_DET_M 0x1000
#define EDMA_CHN_ERR_INT_MASK_SRC_M_INF_DET_S 13
#define EDMA_CHN_ERR_INT_MASK_SRC_M_INF_DET_M 0x2000
#define EDMA_CHN_ERR_INT_MASK_DST_RANGE_ERR_S 14
#define EDMA_CHN_ERR_INT_MASK_DST_RANGE_ERR_M 0x4000
#define EDMA_CHN_ERR_INT_MASK_DST_NAN_DET_S 15
#define EDMA_CHN_ERR_INT_MASK_DST_NAN_DET_M 0x8000
#define EDMA_CHN_ERR_INT_MASK_DST_INF_DET_S 16
#define EDMA_CHN_ERR_INT_MASK_DST_INF_DET_M 0x10000
#define EDMA_CHN_ERR_INT_MASK_DST_M_INF_DET_S 17
#define EDMA_CHN_ERR_INT_MASK_DST_M_INF_DET_M 0x20000
#define EDMA_CHN_ERR_INT_MASK_DESC_OVF_S 18
#define EDMA_CHN_ERR_INT_MASK_DESC_OVF_M 0x40000
#define EDMA_CHN_ERR_INT_MASK_ENG_BAD_CONFIG_ERR_S 19
#define EDMA_CHN_ERR_INT_MASK_ENG_BAD_CONFIG_ERR_M 0x80000
#define EDMA_CHN_ERR_INT_MASK_TE_DESC_FIFO_OVF_S 20
#define EDMA_CHN_ERR_INT_MASK_TE_DESC_FIFO_OVF_M 0x100000
#define EDMA_CHN_ERR_INT_MASK_ENG_INF_INPUT_DET_S 21
#define EDMA_CHN_ERR_INT_MASK_ENG_INF_INPUT_DET_M 0x200000

/* EDMA_CHN_CFG_RSB_DATA_OCCUPANCY */
#define EDMA_CHN_CFG_RSB_DATA_OCCUPANCY_VAL_S 0
#define EDMA_CHN_CFG_RSB_DATA_OCCUPANCY_VAL_M 0xFFFFFFFF

/* EDMA_CHN_CFG_RSB_MD_OCCUPANCY */
#define EDMA_CHN_CFG_RSB_MD_OCCUPANCY_VAL_S 0
#define EDMA_CHN_CFG_RSB_MD_OCCUPANCY_VAL_M 0xFFFFFFFF

/* EDMA_CHN_MAX_WR_COMP_INFLIGHT */
#define EDMA_CHN_MAX_WR_COMP_INFLIGHT_VAL_S 0
#define EDMA_CHN_MAX_WR_COMP_INFLIGHT_VAL_M 0x3F

#endif /* ASIC_REG_EDMA_CHN_MASKS_H_ */
