/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_MMU_MASKS_H_
#define ASIC_REG_MMU_MASKS_H_

/*
 *****************************************
 *   MMU
 *   (Prototype: MMU)
 *****************************************
 */

/* MMU_TRACE_CTRL */
#define MMU_TRACE_CTRL_TRACE_ENABLE_S 0
#define MMU_TRACE_CTRL_TRACE_ENABLE_M 0x1

/* MMU_PAGE_ERROR_CAPTURE */
#define MMU_PAGE_ERROR_CAPTURE_VA_63_32_S 0
#define MMU_PAGE_ERROR_CAPTURE_VA_63_32_M 0xFFFFFFFF

/* MMU_PAGE_ERROR_CAPTURE_VA */
#define MMU_PAGE_ERROR_CAPTURE_VA_VA_31_0_S 0
#define MMU_PAGE_ERROR_CAPTURE_VA_VA_31_0_M 0xFFFFFFFF

/* MMU_ACCESS_ERROR_CAPTURE */
#define MMU_ACCESS_ERROR_CAPTURE_VA_63_32_S 0
#define MMU_ACCESS_ERROR_CAPTURE_VA_63_32_M 0xFFFFFFFF

/* MMU_ACCESS_ERROR_CAPTURE_VA */
#define MMU_ACCESS_ERROR_CAPTURE_VA_VA_31_0_S 0
#define MMU_ACCESS_ERROR_CAPTURE_VA_VA_31_0_M 0xFFFFFFFF

/* MMU_ACCESS_PAGE_ERROR_VALID */
#define MMU_ACCESS_PAGE_ERROR_VALID_PAGE_ERR_VALID_ENTRY_S 0
#define MMU_ACCESS_PAGE_ERROR_VALID_PAGE_ERR_VALID_ENTRY_M 0x1
#define MMU_ACCESS_PAGE_ERROR_VALID_ACCESS_ERR_VALID_ENTRY_S 1
#define MMU_ACCESS_PAGE_ERROR_VALID_ACCESS_ERR_VALID_ENTRY_M 0x2

/* MMU_MMU_BYPASS */
#define MMU_MMU_BYPASS_R_S 0
#define MMU_MMU_BYPASS_R_M 0x1

/* MMU_STATIC_MULTI_PAGE_SIZE */
#define MMU_STATIC_MULTI_PAGE_SIZE_HOP5_PAGE_SIZE_S 0
#define MMU_STATIC_MULTI_PAGE_SIZE_HOP5_PAGE_SIZE_M 0xF
#define MMU_STATIC_MULTI_PAGE_SIZE_HOP4_PAGE_SIZE_S 4
#define MMU_STATIC_MULTI_PAGE_SIZE_HOP4_PAGE_SIZE_M 0xF0
#define MMU_STATIC_MULTI_PAGE_SIZE_HOP3_PAGE_SIZE_S 8
#define MMU_STATIC_MULTI_PAGE_SIZE_HOP3_PAGE_SIZE_M 0xF00
#define MMU_STATIC_MULTI_PAGE_SIZE_HOP2_PAGE_SIZE_S 12
#define MMU_STATIC_MULTI_PAGE_SIZE_HOP2_PAGE_SIZE_M 0xF000
#define MMU_STATIC_MULTI_PAGE_SIZE_HOP1_PAGE_SIZE_S 16
#define MMU_STATIC_MULTI_PAGE_SIZE_HOP1_PAGE_SIZE_M 0xF0000
#define MMU_STATIC_MULTI_PAGE_SIZE_CFG_8_BITS_HOP_MODE_EN_S 20
#define MMU_STATIC_MULTI_PAGE_SIZE_CFG_8_BITS_HOP_MODE_EN_M 0x100000

/* MMU_PAGE_FAULT_ID_LSB */
#define MMU_PAGE_FAULT_ID_LSB_PAGE_FAULT_ID_31_0_S 0
#define MMU_PAGE_FAULT_ID_LSB_PAGE_FAULT_ID_31_0_M 0xFFFFFFFF

/* MMU_PAGE_FAULT_ID_MSB */
#define MMU_PAGE_FAULT_ID_MSB_PAGE_FAULT_ID_63_32_S 0
#define MMU_PAGE_FAULT_ID_MSB_PAGE_FAULT_ID_63_32_M 0xFFFFFFFF

/* MMU_PAGE_ACCESS_ID_LSB */
#define MMU_PAGE_ACCESS_ID_LSB_PAGE_ACCESS_ID_31_0_S 0
#define MMU_PAGE_ACCESS_ID_LSB_PAGE_ACCESS_ID_31_0_M 0xFFFFFFFF

/* MMU_PAGE_ACCESS_ID_MSB */
#define MMU_PAGE_ACCESS_ID_MSB_PAGE_ACCESS_ID_63_32_S 0
#define MMU_PAGE_ACCESS_ID_MSB_PAGE_ACCESS_ID_63_32_M 0xFFFFFFFF

/* MMU_RAZWI_WRITE_VLD */
#define MMU_RAZWI_WRITE_VLD_R_S 0
#define MMU_RAZWI_WRITE_VLD_R_M 0x1

/* MMU_RAZWI_WRITE_ID_31_0 */
#define MMU_RAZWI_WRITE_ID_31_0_R_S 0
#define MMU_RAZWI_WRITE_ID_31_0_R_M 0xFFFFFFFF

/* MMU_RAZWI_WRITE_ID_63_32 */
#define MMU_RAZWI_WRITE_ID_63_32_R_S 0
#define MMU_RAZWI_WRITE_ID_63_32_R_M 0xFFFFFFFF

/* MMU_RAZWI_READ_VLD */
#define MMU_RAZWI_READ_VLD_R_S 0
#define MMU_RAZWI_READ_VLD_R_M 0x1

/* MMU_RAZWI_READ_ID_31_0 */
#define MMU_RAZWI_READ_ID_31_0_R_S 0
#define MMU_RAZWI_READ_ID_31_0_R_M 0xFFFFFFFF

/* MMU_RAZWI_READ_ID_63_32 */
#define MMU_RAZWI_READ_ID_63_32_R_S 0
#define MMU_RAZWI_READ_ID_63_32_R_M 0xFFFFFFFF

/* MMU_RAZWI_ADDR_LSB */
#define MMU_RAZWI_ADDR_LSB_ADDR_S 0
#define MMU_RAZWI_ADDR_LSB_ADDR_M 0xFFFFFFFF

/* MMU_RAZWI_ADDR_MSB */
#define MMU_RAZWI_ADDR_MSB_ADDR_S 0
#define MMU_RAZWI_ADDR_MSB_ADDR_M 0xFFFFFFFF

/* MMU_INV_START_RANGE_LO */
#define MMU_INV_START_RANGE_LO_INV_START_RANGE_LO_S 12
#define MMU_INV_START_RANGE_LO_INV_START_RANGE_LO_M 0xFFFFF000

/* MMU_INV_START_RANGE_HI */
#define MMU_INV_START_RANGE_HI_INV_START_RANGE_HI_S 0
#define MMU_INV_START_RANGE_HI_INV_START_RANGE_HI_M 0xFFFFFFFF

/* MMU_INV_END_RANGE_LO */
#define MMU_INV_END_RANGE_LO_INV_END_RANGE_LO_S 12
#define MMU_INV_END_RANGE_LO_INV_END_RANGE_LO_M 0xFFFFF000

/* MMU_INV_END_RANGE_HI */
#define MMU_INV_END_RANGE_HI_INV_END_RANGE_HI_S 0
#define MMU_INV_END_RANGE_HI_INV_END_RANGE_HI_M 0xFFFFFFFF

/* MMU_INV_ASID */
#define MMU_INV_ASID_INV_ASID_S 0
#define MMU_INV_ASID_INV_ASID_M 0x3FF

/* MMU_INV_ASID_EN */
#define MMU_INV_ASID_EN_INV_ASID_EN_S 0
#define MMU_INV_ASID_EN_INV_ASID_EN_M 0x1

/* MMU_INV_RANGE_TRIGGER */
#define MMU_INV_RANGE_TRIGGER_INV_EN_S 0
#define MMU_INV_RANGE_TRIGGER_INV_EN_M 0x1

/* MMU_INV_ALL_START */
#define MMU_INV_ALL_START_INV_ALL_START_S 0
#define MMU_INV_ALL_START_INV_ALL_START_M 0x1

/* MMU_INV_CPL_ADDR */
#define MMU_INV_CPL_ADDR_INV_CPL_MSG_ADDR_S 0
#define MMU_INV_CPL_ADDR_INV_CPL_MSG_ADDR_M 0x1FFFFFFF

/* MMU_INV_CPL_DATA */
#define MMU_INV_CPL_DATA_INV_CPL_MSG_DATA_S 0
#define MMU_INV_CPL_DATA_INV_CPL_MSG_DATA_M 0xFFFFFFFF

/* MMU_FAULTQ_BASE_ADDR_LO */
#define MMU_FAULTQ_BASE_ADDR_LO_FAULTQ_BASE_ADDR_LO_S 0
#define MMU_FAULTQ_BASE_ADDR_LO_FAULTQ_BASE_ADDR_LO_M 0xFFFFFFFF

/* MMU_FAULTQ_BASE_ADDR_HI */
#define MMU_FAULTQ_BASE_ADDR_HI_FAULTQ_BASE_ADDR_HI_S 0
#define MMU_FAULTQ_BASE_ADDR_HI_FAULTQ_BASE_ADDR_HI_M 0xFFFFFFFF

/* MMU_FAULTQ_PI */
#define MMU_FAULTQ_PI_FAULTQ_PI_LO_S 0
#define MMU_FAULTQ_PI_FAULTQ_PI_LO_M 0xFFFFFFFF

/* MMU_FAULTQ_CI */
#define MMU_FAULTQ_CI_FAULTQ_CI_LO_S 0
#define MMU_FAULTQ_CI_FAULTQ_CI_LO_M 0xFFFFFFFF

/* MMU_FAULTQ_SIZE */
#define MMU_FAULTQ_SIZE_FAULTQ_SIZE_S 0
#define MMU_FAULTQ_SIZE_FAULTQ_SIZE_M 0xFFFFFFFF

/* MMU_FAULTQ_MAX_THSHLD */
#define MMU_FAULTQ_MAX_THSHLD_FAULTQ_MAX_THSHLD_S 0
#define MMU_FAULTQ_MAX_THSHLD_FAULTQ_MAX_THSHLD_M 0xFFFFFFFF

/* MMU_FAULTQ_MAX_THSLD_INTR_ADD */
#define MMU_FAULTQ_MAX_THSLD_INTR_ADD_FAULTQ_MAX_THSLD_INTR_ADD_S 0
#define MMU_FAULTQ_MAX_THSLD_INTR_ADD_FAULTQ_MAX_THSLD_INTR_ADD_M 0x1FFFFFFF

/* MMU_FAULTQ_MAX_THSLD_INTR_DAT */
#define MMU_FAULTQ_MAX_THSLD_INTR_DAT_FAULTQ_MAX_THSLD_INTR_DAT_S 0
#define MMU_FAULTQ_MAX_THSLD_INTR_DAT_FAULTQ_MAX_THSLD_INTR_DAT_M 0xFFFFFFFF

/* MMU_FAULTQ_MAX_THSLD_INT_MASK */
#define MMU_FAULTQ_MAX_THSLD_INT_MASK_FAULTQ_MAX_THSLD_INT_MASK_S 0
#define MMU_FAULTQ_MAX_THSLD_INT_MASK_FAULTQ_MAX_THSLD_INT_MASK_M 0x1

/* MMU_FAULTQ_STATUS */
#define MMU_FAULTQ_STATUS_FAULTQ_EMPTY_S 0
#define MMU_FAULTQ_STATUS_FAULTQ_EMPTY_M 0x1
#define MMU_FAULTQ_STATUS_FAULTQ_FULL_S 1
#define MMU_FAULTQ_STATUS_FAULTQ_FULL_M 0x2

/* MMU_FAULTQ_MSIX_ADDR */
#define MMU_FAULTQ_MSIX_ADDR_FAULTQ_MSIX_ADDR_S 0
#define MMU_FAULTQ_MSIX_ADDR_FAULTQ_MSIX_ADDR_M 0x1FFFFFFF

/* MMU_FAULTQ_MSIX_DATA */
#define MMU_FAULTQ_MSIX_DATA_FAULTQ_MSIX_DATA_S 0
#define MMU_FAULTQ_MSIX_DATA_FAULTQ_MSIX_DATA_M 0xFFFFFFFF

/* MMU_PTW_RESUME */
#define MMU_PTW_RESUME_PTW_ID_S 0
#define MMU_PTW_RESUME_PTW_ID_M 0xFFFF
#define MMU_PTW_RESUME_ERROR_RESUME_PTW_S 16
#define MMU_PTW_RESUME_ERROR_RESUME_PTW_M 0x10000

/* MMU_SET_SCRAMBLE_REG_0 */
#define MMU_SET_SCRAMBLE_REG_0_H3_MATRIX_0_S 0
#define MMU_SET_SCRAMBLE_REG_0_H3_MATRIX_0_M 0x1F
#define MMU_SET_SCRAMBLE_REG_0_H3_MATRIX_1_S 5
#define MMU_SET_SCRAMBLE_REG_0_H3_MATRIX_1_M 0x3E0
#define MMU_SET_SCRAMBLE_REG_0_H3_MATRIX_2_S 10
#define MMU_SET_SCRAMBLE_REG_0_H3_MATRIX_2_M 0x7C00
#define MMU_SET_SCRAMBLE_REG_0_H3_MATRIX_3_S 15
#define MMU_SET_SCRAMBLE_REG_0_H3_MATRIX_3_M 0xF8000
#define MMU_SET_SCRAMBLE_REG_0_H3_MATRIX_4_S 20
#define MMU_SET_SCRAMBLE_REG_0_H3_MATRIX_4_M 0x1F00000
#define MMU_SET_SCRAMBLE_REG_0_H3_MATRIX_5_S 25
#define MMU_SET_SCRAMBLE_REG_0_H3_MATRIX_5_M 0x3E000000

/* MMU_SET_SCRAMBLE_REG_1 */
#define MMU_SET_SCRAMBLE_REG_1_H3_MATRIX_6_S 0
#define MMU_SET_SCRAMBLE_REG_1_H3_MATRIX_6_M 0x1F
#define MMU_SET_SCRAMBLE_REG_1_H3_MATRIX_7_S 5
#define MMU_SET_SCRAMBLE_REG_1_H3_MATRIX_7_M 0x3E0
#define MMU_SET_SCRAMBLE_REG_1_H3_MATRIX_8_S 10
#define MMU_SET_SCRAMBLE_REG_1_H3_MATRIX_8_M 0x7C00
#define MMU_SET_SCRAMBLE_REG_1_H3_MATRIX_9_S 15
#define MMU_SET_SCRAMBLE_REG_1_H3_MATRIX_9_M 0xF8000
#define MMU_SET_SCRAMBLE_REG_1_H3_MATRIX_10_S 20
#define MMU_SET_SCRAMBLE_REG_1_H3_MATRIX_10_M 0x1F00000
#define MMU_SET_SCRAMBLE_REG_1_H3_MATRIX_11_S 25
#define MMU_SET_SCRAMBLE_REG_1_H3_MATRIX_11_M 0x3E000000

/* MMU_SET_SCRAMBLE_REG_2 */
#define MMU_SET_SCRAMBLE_REG_2_H3_MATRIX_12_S 0
#define MMU_SET_SCRAMBLE_REG_2_H3_MATRIX_12_M 0x1F
#define MMU_SET_SCRAMBLE_REG_2_H3_MATRIX_13_S 5
#define MMU_SET_SCRAMBLE_REG_2_H3_MATRIX_13_M 0x3E0
#define MMU_SET_SCRAMBLE_REG_2_H3_MATRIX_14_S 10
#define MMU_SET_SCRAMBLE_REG_2_H3_MATRIX_14_M 0x7C00
#define MMU_SET_SCRAMBLE_REG_2_H3_MATRIX_15_S 15
#define MMU_SET_SCRAMBLE_REG_2_H3_MATRIX_15_M 0xF8000
#define MMU_SET_SCRAMBLE_REG_2_H3_MATRIX_16_S 20
#define MMU_SET_SCRAMBLE_REG_2_H3_MATRIX_16_M 0x1F00000
#define MMU_SET_SCRAMBLE_REG_2_H3_MATRIX_17_S 25
#define MMU_SET_SCRAMBLE_REG_2_H3_MATRIX_17_M 0x3E000000

/* MMU_SET_SCRAMBLE_REG_3 */
#define MMU_SET_SCRAMBLE_REG_3_H3_MATRIX_18_S 0
#define MMU_SET_SCRAMBLE_REG_3_H3_MATRIX_18_M 0x1F
#define MMU_SET_SCRAMBLE_REG_3_H3_MATRIX_19_S 5
#define MMU_SET_SCRAMBLE_REG_3_H3_MATRIX_19_M 0x3E0
#define MMU_SET_SCRAMBLE_REG_3_H3_MATRIX_20_S 10
#define MMU_SET_SCRAMBLE_REG_3_H3_MATRIX_20_M 0x7C00
#define MMU_SET_SCRAMBLE_REG_3_H3_MATRIX_21_S 15
#define MMU_SET_SCRAMBLE_REG_3_H3_MATRIX_21_M 0xF8000
#define MMU_SET_SCRAMBLE_REG_3_H3_MATRIX_22_S 20
#define MMU_SET_SCRAMBLE_REG_3_H3_MATRIX_22_M 0x1F00000
#define MMU_SET_SCRAMBLE_REG_3_H3_MATRIX_23_S 25
#define MMU_SET_SCRAMBLE_REG_3_H3_MATRIX_23_M 0x3E000000

/* MMU_SET_SCRAMBLE_REG_4 */
#define MMU_SET_SCRAMBLE_REG_4_H3_MATRIX_24_S 0
#define MMU_SET_SCRAMBLE_REG_4_H3_MATRIX_24_M 0x1F
#define MMU_SET_SCRAMBLE_REG_4_H3_MATRIX_25_S 5
#define MMU_SET_SCRAMBLE_REG_4_H3_MATRIX_25_M 0x3E0

/* MMU_FEATURE_CONTROL */
#define MMU_FEATURE_CONTROL_FOLLOWER_EN_S 0
#define MMU_FEATURE_CONTROL_FOLLOWER_EN_M 0x1
#define MMU_FEATURE_CONTROL_FOLLOWER_NUM_LIMIT_S 1
#define MMU_FEATURE_CONTROL_FOLLOWER_NUM_LIMIT_M 0x7FE
#define MMU_FEATURE_CONTROL_ODP_EN_S 11
#define MMU_FEATURE_CONTROL_ODP_EN_M 0x800
#define MMU_FEATURE_CONTROL_PTW_RD_VIA_PIF_S 12
#define MMU_FEATURE_CONTROL_PTW_RD_VIA_PIF_M 0x1000
#define MMU_FEATURE_CONTROL_PREFETCH_1_CLINE_DISABLE_S 13
#define MMU_FEATURE_CONTROL_PREFETCH_1_CLINE_DISABLE_M 0x2000
#define MMU_FEATURE_CONTROL_NON_LINEAR_EN_S 14
#define MMU_FEATURE_CONTROL_NON_LINEAR_EN_M 0x4000
#define MMU_FEATURE_CONTROL_ENABLE_8B_PTW_FETCH_S 15
#define MMU_FEATURE_CONTROL_ENABLE_8B_PTW_FETCH_M 0x8000
#define MMU_FEATURE_CONTROL_DISABLE_PREFETCH_PAGCROSS_S 16
#define MMU_FEATURE_CONTROL_DISABLE_PREFETCH_PAGCROSS_M 0x10000
#define MMU_FEATURE_CONTROL_SKIP_NON_IDLE_SLICES_S 17
#define MMU_FEATURE_CONTROL_SKIP_NON_IDLE_SLICES_M 0x20000
#define MMU_FEATURE_CONTROL_FORCE_INV_ALL_PREFETCHER_S 18
#define MMU_FEATURE_CONTROL_FORCE_INV_ALL_PREFETCHER_M 0x40000

/* MMU_PAGE_FAULT_USER_BITS */
#define MMU_PAGE_FAULT_USER_BITS_RUSER_RESPONSE_S 0
#define MMU_PAGE_FAULT_USER_BITS_RUSER_RESPONSE_M 0xFF
#define MMU_PAGE_FAULT_USER_BITS_BUSER_RESPONSE_S 8
#define MMU_PAGE_FAULT_USER_BITS_BUSER_RESPONSE_M 0xFF00

/* MMU_FAULTQ_AW_CACHE */
#define MMU_FAULTQ_AW_CACHE_FAULTQ_AW_CACHE_S 0
#define MMU_FAULTQ_AW_CACHE_FAULTQ_AW_CACHE_M 0xF

/* MMU_FAULTQ_AW_PROT */
#define MMU_FAULTQ_AW_PROT_FAULTQ_AW_PROT_S 0
#define MMU_FAULTQ_AW_PROT_FAULTQ_AW_PROT_M 0x7

/* MMU_FAULTQ_AW_LOCK */
#define MMU_FAULTQ_AW_LOCK_FAULTQ_AW_LOCK_S 0
#define MMU_FAULTQ_AW_LOCK_FAULTQ_AW_LOCK_M 0x1

/* MMU_FAULTQ_MSIX_AW_LOCK */
#define MMU_FAULTQ_MSIX_AW_LOCK_FAULTQ_MSIX_AW_LOCK_S 0
#define MMU_FAULTQ_MSIX_AW_LOCK_FAULTQ_MSIX_AW_LOCK_M 0x1

/* MMU_FAULTQ_MSIX_AW_CACHE */
#define MMU_FAULTQ_MSIX_AW_CACHE_FAULTQ_MSIX_AW_CACHE_S 0
#define MMU_FAULTQ_MSIX_AW_CACHE_FAULTQ_MSIX_AW_CACHE_M 0xF

/* MMU_FAULTQ_MSIX_AW_PROT */
#define MMU_FAULTQ_MSIX_AW_PROT_FAULTQ_MSIX_AW_PROT_S 0
#define MMU_FAULTQ_MSIX_AW_PROT_FAULTQ_MSIX_AW_PROT_M 0x7

/* MMU_DRAIN_TIMEOUT_VAL_HI */
#define MMU_DRAIN_TIMEOUT_VAL_HI_DRAIN_TIMEOUT_VAL_HI_S 0
#define MMU_DRAIN_TIMEOUT_VAL_HI_DRAIN_TIMEOUT_VAL_HI_M 0xFF

/* MMU_DRAIN_CTRL */
#define MMU_DRAIN_CTRL_DRAIN_ENABLE_S 0
#define MMU_DRAIN_CTRL_DRAIN_ENABLE_M 0x1
#define MMU_DRAIN_CTRL_DRAIN_RD_RESP_S 1
#define MMU_DRAIN_CTRL_DRAIN_RD_RESP_M 0x6
#define MMU_DRAIN_CTRL_DRAIN_WR_RESP_S 3
#define MMU_DRAIN_CTRL_DRAIN_WR_RESP_M 0x18

/* MMU_PREFETCH_USER_IDX */
#define MMU_PREFETCH_USER_IDX_PREFETCH_USER_IDX_S 0
#define MMU_PREFETCH_USER_IDX_PREFETCH_USER_IDX_M 0x3F

/* MMU_DRAIN_TIMEOUT_VAL_LO */
#define MMU_DRAIN_TIMEOUT_VAL_LO_DRAIN_TIMEOUT_VAL_LO_S 0
#define MMU_DRAIN_TIMEOUT_VAL_LO_DRAIN_TIMEOUT_VAL_LO_M 0xFFFFFFFF

/* MMU_PLRU_MODE_SEL */
#define MMU_PLRU_MODE_SEL_PLRU_MODE_SEL_S 0
#define MMU_PLRU_MODE_SEL_PLRU_MODE_SEL_M 0x1

/* MMU_SPI_MASK */
#define MMU_SPI_MASK_R_S 0
#define MMU_SPI_MASK_R_M 0xFFFFFFFF

/* MMU_SPI_STATUS */
#define MMU_SPI_STATUS_I0_S 0
#define MMU_SPI_STATUS_I0_M 0x1
#define MMU_SPI_STATUS_I1_S 1
#define MMU_SPI_STATUS_I1_M 0x2
#define MMU_SPI_STATUS_I2_S 2
#define MMU_SPI_STATUS_I2_M 0x4
#define MMU_SPI_STATUS_I3_S 3
#define MMU_SPI_STATUS_I3_M 0x8

/* MMU_SEI_MASK */
#define MMU_SEI_MASK_R_S 0
#define MMU_SEI_MASK_R_M 0xFFFFFFFF

/* MMU_SEI_STATUS */
#define MMU_SEI_STATUS_I0_S 0
#define MMU_SEI_STATUS_I0_M 0x1
#define MMU_SEI_STATUS_I1_S 1
#define MMU_SEI_STATUS_I1_M 0x2
#define MMU_SEI_STATUS_I2_S 2
#define MMU_SEI_STATUS_I2_M 0x4
#define MMU_SEI_STATUS_I3_S 3
#define MMU_SEI_STATUS_I3_M 0x8
#define MMU_SEI_STATUS_I4_S 4
#define MMU_SEI_STATUS_I4_M 0x10
#define MMU_SEI_STATUS_I5_S 5
#define MMU_SEI_STATUS_I5_M 0x20
#define MMU_SEI_STATUS_I6_S 6
#define MMU_SEI_STATUS_I6_M 0x40
#define MMU_SEI_STATUS_I7_S 7
#define MMU_SEI_STATUS_I7_M 0x80
#define MMU_SEI_STATUS_I8_S 8
#define MMU_SEI_STATUS_I8_M 0x100
#define MMU_SEI_STATUS_I9_S 9
#define MMU_SEI_STATUS_I9_M 0x200
#define MMU_SEI_STATUS_I10_S 10
#define MMU_SEI_STATUS_I10_M 0x400
#define MMU_SEI_STATUS_I11_S 11
#define MMU_SEI_STATUS_I11_M 0x800

/* MMU_REI_MASK */
#define MMU_REI_MASK_R_S 0
#define MMU_REI_MASK_R_M 0xFFFFFFFF

/* MMU_REI_STATUS */
#define MMU_REI_STATUS_I0_S 0
#define MMU_REI_STATUS_I0_M 0x1
#define MMU_REI_STATUS_I1_S 1
#define MMU_REI_STATUS_I1_M 0x2
#define MMU_REI_STATUS_I2_S 2
#define MMU_REI_STATUS_I2_M 0x4
#define MMU_REI_STATUS_I3_S 3
#define MMU_REI_STATUS_I3_M 0x8

/* MMU_DBG_REG_0 */
#define MMU_DBG_REG_0_R_S 0
#define MMU_DBG_REG_0_R_M 0xFFFFFFFF

#endif /* ASIC_REG_MMU_MASKS_H_ */
