/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PARC_GLOBAL_CONF_REGS_H_
#define ASIC_REG_PARC_GLOBAL_CONF_REGS_H_

/*
 *****************************************
 *   PARC_GLOBAL_CONF
 *   (Prototype: PARC_GLOBAL_CONF)
 *****************************************
 */

#define mmPARC_GLOBAL_CONF_HBW_SLV_ADDR_MSB 0x0

#define mmPARC_GLOBAL_CONF_HBW_SLV_ADDR_MSB_MASK 0x4

#define mmPARC_GLOBAL_CONF_SLV_ISOLATE_INPUTS 0x8

#define mmPARC_GLOBAL_CONF_LBW_MST_XUSER_CTRL 0xC

#define mmPARC_GLOBAL_CONF_HBW_MST_MASK_REQ 0x10

#define mmPARC_GLOBAL_CONF_HBW_MST_OUTSTAND_TRANS 0x14

#define mmPARC_GLOBAL_CONF_HBW_SLV_TERM_MIN_ADDR_LSB 0x18

#define mmPARC_GLOBAL_CONF_HBW_SLV_TERM_MIN_ADDR_MSB 0x1C

#define mmPARC_GLOBAL_CONF_HBW_SLV_TERM_MAX_ADDR_LSB 0x20

#define mmPARC_GLOBAL_CONF_HBW_SLV_TERM_MAX_ADDR_MSB 0x24

#define mmPARC_GLOBAL_CONF_HBW_SLV_TERM_CTRL 0x28

#define mmPARC_GLOBAL_CONF_LBW_SLV_TERM_MIN_ADDR 0x2C

#define mmPARC_GLOBAL_CONF_LBW_SLV_TERM_MAX_ADDR 0x30

#define mmPARC_GLOBAL_CONF_LBW_SLV_TERM_CTRL 0x34

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_CTRL 0x54

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MIN_AD0_L 0x58

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MIN_AD0_H 0x5C

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MIN_AD1_L 0x60

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MIN_AD1_H 0x64

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MIN_AD2_L 0x68

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MIN_AD2_H 0x6C

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MIN_AD3_L 0x70

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MIN_AD3_H 0x74

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MAX_AD0_L 0x78

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MAX_AD0_H 0x7C

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MAX_AD1_L 0x80

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MAX_AD1_H 0x84

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MAX_AD2_L 0x88

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MAX_AD2_H 0x8C

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MAX_AD3_L 0x90

#define mmPARC_GLOBAL_CONF_HBW_MST_TERM_RD_MAX_AD3_H 0x94

#define mmPARC_GLOBAL_CONF_PRT_MEM_REPAIR_DATA 0xA0

#define mmPARC_GLOBAL_CONF_PRT_MEM_REPAIR_CLK 0xA4

#define mmPARC_GLOBAL_CONF_PRT_MEM_REPAIR_RST 0xA8

#define mmPARC_GLOBAL_CONF_MAILBOX_CTRL 0xF8

#define mmPARC_GLOBAL_CONF_MAILBOX_ADDR 0xFC

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_0 0x100

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_1 0x104

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_2 0x108

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_3 0x10C

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_4 0x110

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_5 0x114

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_6 0x118

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_7 0x11C

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_8 0x120

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_9 0x124

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_10 0x128

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_11 0x12C

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_12 0x130

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_13 0x134

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_14 0x138

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_15 0x13C

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_16 0x140

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_17 0x144

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_18 0x148

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_19 0x14C

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_20 0x150

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_21 0x154

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_22 0x158

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_23 0x15C

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_24 0x160

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_25 0x164

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_26 0x168

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_27 0x16C

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_28 0x170

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_29 0x174

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_30 0x178

#define mmPARC_GLOBAL_CONF_MAILBOX_REG_31 0x17C

#define mmPARC_GLOBAL_CONF_FW_SRAM_AP_CTRL 0x180

#define mmPARC_GLOBAL_CONF_FW_SRAM_TERM_RESP 0x184

#define mmPARC_GLOBAL_CONF_BOOTROM_SRAM_AXI_RESP 0x188

#define mmPARC_GLOBAL_CONF_BOOTROM_AXI_SPLIT_CFG 0x18C

#define mmPARC_GLOBAL_CONF_BOOTROM_TERM_RESP 0x190

#define mmPARC_GLOBAL_CONF_SPI_DMA_CTRL 0x194

#define mmPARC_GLOBAL_CONF_SPI_DMA_STATUS 0x198

#define mmPARC_GLOBAL_CONF_SPI_DMA_DST_ADDR_H 0x19C

#define mmPARC_GLOBAL_CONF_SPI_DMA_DST_ADDR_L 0x1A0

#define mmPARC_GLOBAL_CONF_SPI_DMA_RESP 0x1A4

#define mmPARC_GLOBAL_CONF_SPI_DMA_BAUDR 0x1AC

#define mmPARC_GLOBAL_CONF_SPI_DMA_CRC 0x1B0

#define mmPARC_GLOBAL_CONF_SPI_DMA_WR_FL_CTRL 0x1B4

#define mmPARC_GLOBAL_CONF_SPI_DMA_WR_FL_STS 0x1B8

#define mmPARC_GLOBAL_CONF_SPI_DMA_FSM_OVRD 0x1BC

#define mmPARC_GLOBAL_CONF_FW_SRAM_INIT_STS 0x1C4

#define mmPARC_GLOBAL_CONF_FW_SRAM_PARTIAL_WR_STS 0x1C8

#define mmPARC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL1_0 0x1D0

#define mmPARC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL1_1 0x1D4

#define mmPARC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL1_2 0x1D8

#define mmPARC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL2_0 0x1E0

#define mmPARC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL2_1 0x1E4

#define mmPARC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL2_2 0x1E8

#define mmPARC_GLOBAL_CONF_ARC_CBU_AXI_SPLIT_CTRL1_0 0x1F0

#define mmPARC_GLOBAL_CONF_ARC_CBU_AXI_SPLIT_CTRL1_1 0x1F4

#define mmPARC_GLOBAL_CONF_ARC_CBU_AXI_SPLIT_CTRL1_2 0x1F8

#define mmPARC_GLOBAL_CONF_ARC_CBU_AXI_SPLIT_CTRL2_0 0x200

#define mmPARC_GLOBAL_CONF_ARC_CBU_AXI_SPLIT_CTRL2_1 0x204

#define mmPARC_GLOBAL_CONF_ARC_CBU_AXI_SPLIT_CTRL2_2 0x208

#define mmPARC_GLOBAL_CONF_IC_LBW_ARC_UM_CTRL 0x210

#define mmPARC_GLOBAL_CONF_IC_LBW_ARC_UM_STS0 0x214

#define mmPARC_GLOBAL_CONF_IC_LBW_ARC_UM_STS1 0x218

#define mmPARC_GLOBAL_CONF_IC_LBW_ARC_UM_STS 0x21C

#define mmPARC_GLOBAL_CONF_IC_LBW_PARC_UM_CTRL 0x220

#define mmPARC_GLOBAL_CONF_IC_LBW_PARC_UM_STS0 0x224

#define mmPARC_GLOBAL_CONF_IC_LBW_PARC_UM_STS1 0x228

#define mmPARC_GLOBAL_CONF_IC_LBW_PARC_UM_STS 0x22C

#define mmPARC_GLOBAL_CONF_IC_TERM 0x230

#define mmPARC_GLOBAL_CONF_IC_HBW_ERR_ADDR_LSB 0x240

#define mmPARC_GLOBAL_CONF_IC_HBW_ERR_ADDR_MSB 0x244

#define mmPARC_GLOBAL_CONF_IC_HBW_ERR_INFO 0x248

#define mmPARC_GLOBAL_CONF_IC_LBW_ERR_ADDR_LSB 0x250

#define mmPARC_GLOBAL_CONF_IC_LBW_ERR_ADDR_MSB 0x254

#define mmPARC_GLOBAL_CONF_IC_LBW_ERR_INFO 0x258

#define mmPARC_GLOBAL_CONF_IC_CBU_ERR_ADDR_LSB 0x260

#define mmPARC_GLOBAL_CONF_IC_CBU_ERR_ADDR_MSB 0x264

#define mmPARC_GLOBAL_CONF_IC_CBU_ERR_INFO 0x268

#define mmPARC_GLOBAL_CONF_IC_ARC_ERR_ADDR_LSB 0x270

#define mmPARC_GLOBAL_CONF_IC_ARC_ERR_ADDR_MSB 0x274

#define mmPARC_GLOBAL_CONF_IC_ARC_ERR_INFO 0x278

#define mmPARC_GLOBAL_CONF_ACCESS_PROT_CTRL 0x2A0

#define mmPARC_GLOBAL_CONF_ACCESS_PROT_INFO_STS 0x2A4

#define mmPARC_GLOBAL_CONF_ACCESS_PROT_INFO0 0x2A8

#define mmPARC_GLOBAL_CONF_ACCESS_PROT_INFO1 0x2AC

#define mmPARC_GLOBAL_CONF_MST_HBW_DRAIN_CFG 0x2B0

#define mmPARC_GLOBAL_CONF_MST_HBW_DRAIN_TIMEOUT 0x2B4

#define mmPARC_GLOBAL_CONF_MST_HBW_DRAIN_STATUS 0x2B8

#define mmPARC_GLOBAL_CONF_MST_HBW_DRAIN_TIMEOUT_BP 0x2BC

#define mmPARC_GLOBAL_CONF_MST_HBW_DRAIN_BP_EXIT 0x2C0

#define mmPARC_GLOBAL_CONF_MST_LBW_DRAIN_CFG 0x2D0

#define mmPARC_GLOBAL_CONF_MST_LBW_DRAIN_TIMEOUT 0x2D4

#define mmPARC_GLOBAL_CONF_MST_LBW_DRAIN_STATUS 0x2D8

#define mmPARC_GLOBAL_CONF_MST_LBW_DRAIN_TIMEOUT_BP 0x2DC

#define mmPARC_GLOBAL_CONF_MST_LBW_DRAIN_BP_EXIT 0x2E0

#define mmPARC_GLOBAL_CONF_ARC_WD_INTR_CTRL_CLEAR_0 0x300

#define mmPARC_GLOBAL_CONF_ARC_WD_INTR_CTRL_CLEAR_1 0x304

#define mmPARC_GLOBAL_CONF_ARC_WD_INTR_CTRL_CLEAR_2 0x308

#define mmPARC_GLOBAL_CONF_ARC_WD_INTR_CTRL_MASK_0 0x310

#define mmPARC_GLOBAL_CONF_ARC_WD_INTR_CTRL_MASK_1 0x314

#define mmPARC_GLOBAL_CONF_ARC_WD_INTR_CTRL_MASK_2 0x318

#define mmPARC_GLOBAL_CONF_ARC_WD_INTR_CTRL_CAUSE_0 0x320

#define mmPARC_GLOBAL_CONF_ARC_WD_INTR_CTRL_CAUSE_1 0x324

#define mmPARC_GLOBAL_CONF_ARC_WD_INTR_CTRL_CAUSE_2 0x328

#define mmPARC_GLOBAL_CONF_ARC0_ENG_STS_INTR_CTRL_CLEAR_0 0x330

#define mmPARC_GLOBAL_CONF_ARC0_ENG_STS_INTR_CTRL_CLEAR_1 0x334

#define mmPARC_GLOBAL_CONF_ARC0_ENG_STS_INTR_CTRL_CLEAR_2 0x338

#define mmPARC_GLOBAL_CONF_ARC0_ENG_STS_INTR_CTRL_CLEAR_3 0x33C

#define mmPARC_GLOBAL_CONF_ARC0_ENG_STS_INTR_CTRL_MASK_0 0x340

#define mmPARC_GLOBAL_CONF_ARC0_ENG_STS_INTR_CTRL_MASK_1 0x344

#define mmPARC_GLOBAL_CONF_ARC0_ENG_STS_INTR_CTRL_MASK_2 0x348

#define mmPARC_GLOBAL_CONF_ARC0_ENG_STS_INTR_CTRL_MASK_3 0x34C

#define mmPARC_GLOBAL_CONF_ARC0_ENG_STS_INTR_CTRL_CAUSE_0 0x350

#define mmPARC_GLOBAL_CONF_ARC0_ENG_STS_INTR_CTRL_CAUSE_1 0x354

#define mmPARC_GLOBAL_CONF_ARC0_ENG_STS_INTR_CTRL_CAUSE_2 0x358

#define mmPARC_GLOBAL_CONF_ARC0_ENG_STS_INTR_CTRL_CAUSE_3 0x35C

#define mmPARC_GLOBAL_CONF_ARC1_ENG_STS_INTR_CTRL_CLEAR_0 0x360

#define mmPARC_GLOBAL_CONF_ARC1_ENG_STS_INTR_CTRL_CLEAR_1 0x364

#define mmPARC_GLOBAL_CONF_ARC1_ENG_STS_INTR_CTRL_CLEAR_2 0x368

#define mmPARC_GLOBAL_CONF_ARC1_ENG_STS_INTR_CTRL_CLEAR_3 0x36C

#define mmPARC_GLOBAL_CONF_ARC1_ENG_STS_INTR_CTRL_MASK_0 0x370

#define mmPARC_GLOBAL_CONF_ARC1_ENG_STS_INTR_CTRL_MASK_1 0x374

#define mmPARC_GLOBAL_CONF_ARC1_ENG_STS_INTR_CTRL_MASK_2 0x378

#define mmPARC_GLOBAL_CONF_ARC1_ENG_STS_INTR_CTRL_MASK_3 0x37C

#define mmPARC_GLOBAL_CONF_ARC1_ENG_STS_INTR_CTRL_CAUSE_0 0x380

#define mmPARC_GLOBAL_CONF_ARC1_ENG_STS_INTR_CTRL_CAUSE_1 0x384

#define mmPARC_GLOBAL_CONF_ARC1_ENG_STS_INTR_CTRL_CAUSE_2 0x388

#define mmPARC_GLOBAL_CONF_ARC1_ENG_STS_INTR_CTRL_CAUSE_3 0x38C

#define mmPARC_GLOBAL_CONF_ARC2_ENG_STS_INTR_CTRL_CLEAR_0 0x390

#define mmPARC_GLOBAL_CONF_ARC2_ENG_STS_INTR_CTRL_CLEAR_1 0x394

#define mmPARC_GLOBAL_CONF_ARC2_ENG_STS_INTR_CTRL_CLEAR_2 0x398

#define mmPARC_GLOBAL_CONF_ARC2_ENG_STS_INTR_CTRL_CLEAR_3 0x39C

#define mmPARC_GLOBAL_CONF_ARC2_ENG_STS_INTR_CTRL_MASK_0 0x3A0

#define mmPARC_GLOBAL_CONF_ARC2_ENG_STS_INTR_CTRL_MASK_1 0x3A4

#define mmPARC_GLOBAL_CONF_ARC2_ENG_STS_INTR_CTRL_MASK_2 0x3A8

#define mmPARC_GLOBAL_CONF_ARC2_ENG_STS_INTR_CTRL_MASK_3 0x3AC

#define mmPARC_GLOBAL_CONF_ARC2_ENG_STS_INTR_CTRL_CAUSE_0 0x3B0

#define mmPARC_GLOBAL_CONF_ARC2_ENG_STS_INTR_CTRL_CAUSE_1 0x3B4

#define mmPARC_GLOBAL_CONF_ARC2_ENG_STS_INTR_CTRL_CAUSE_2 0x3B8

#define mmPARC_GLOBAL_CONF_ARC2_ENG_STS_INTR_CTRL_CAUSE_3 0x3BC

#define mmPARC_GLOBAL_CONF_ARC_HW_FIFO_INTR_CTRL_CLEAR_0 0x3C0

#define mmPARC_GLOBAL_CONF_ARC_HW_FIFO_INTR_CTRL_CLEAR_1 0x3C4

#define mmPARC_GLOBAL_CONF_ARC_HW_FIFO_INTR_CTRL_CLEAR_2 0x3C8

#define mmPARC_GLOBAL_CONF_ARC_HW_FIFO_INTR_CTRL_MASK_0 0x3D0

#define mmPARC_GLOBAL_CONF_ARC_HW_FIFO_INTR_CTRL_MASK_1 0x3D4

#define mmPARC_GLOBAL_CONF_ARC_HW_FIFO_INTR_CTRL_MASK_2 0x3D8

#define mmPARC_GLOBAL_CONF_ARC_HW_FIFO_INTR_CTRL_CAUSE_0 0x3E0

#define mmPARC_GLOBAL_CONF_ARC_HW_FIFO_INTR_CTRL_CAUSE_1 0x3E4

#define mmPARC_GLOBAL_CONF_ARC_HW_FIFO_INTR_CTRL_CAUSE_2 0x3E8

#define mmPARC_GLOBAL_CONF_ARC_AUX2APB_INTR_CTRL_CLEAR 0x3F0

#define mmPARC_GLOBAL_CONF_ARC_AUX2APB_INTR_CTRL_MASK 0x3F4

#define mmPARC_GLOBAL_CONF_ARC_AUX2APB_INTR_CTRL_CAUSE 0x3F8

#define mmPARC_GLOBAL_CONF_DRAIN_INTR_CTRL_CLEAR 0x400

#define mmPARC_GLOBAL_CONF_DRAIN_INTR_CTRL_MASK 0x404

#define mmPARC_GLOBAL_CONF_DRAIN_INTR_CTRL_CAUSE 0x408

#define mmPARC_GLOBAL_CONF_SEI_INTR_CTRL_CLEAR 0x410

#define mmPARC_GLOBAL_CONF_SEI_INTR_CTRL_MASK 0x414

#define mmPARC_GLOBAL_CONF_SEI_INTR_CTRL_CAUSE 0x418

#define mmPARC_GLOBAL_CONF_ECO_INTR_CTRL_CLEAR 0x420

#define mmPARC_GLOBAL_CONF_ECO_INTR_CTRL_MASK 0x424

#define mmPARC_GLOBAL_CONF_ECO_INTR_CTRL_CAUSE 0x428

#define mmPARC_GLOBAL_CONF_BOOTROM_AXI_SPLIT_OS_CFG 0x4A0

#define mmPARC_GLOBAL_CONF_SPI_DMA_BRESP_OVRD 0x4A8

#define mmPARC_GLOBAL_CONF_ARC_JT_SEL 0x500

#define mmPARC_GLOBAL_CONF_DBG_SLV_TERM_CTRL 0x600

#endif /* ASIC_REG_PARC_GLOBAL_CONF_REGS_H_ */
