/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PCIE_WRAP_DBI_GW_M1_MASKS_H_
#define ASIC_REG_PCIE_WRAP_DBI_GW_M1_MASKS_H_

/*
 *****************************************
 *   PCIE_WRAP_DBI_GW_M1
 *   (Prototype: ACCESS_PROT)
 *****************************************
 */

/* PCIE_WRAP_DBI_GW_M1_ADDR_CTRL */
#define PCIE_WRAP_DBI_GW_M1_ADDR_CTRL_WIN_EN_S 0
#define PCIE_WRAP_DBI_GW_M1_ADDR_CTRL_WIN_EN_M 0x1

/* PCIE_WRAP_DBI_GW_M1_ADDR_MASK */
#define PCIE_WRAP_DBI_GW_M1_ADDR_MASK_BITWISE_EN_S 0
#define PCIE_WRAP_DBI_GW_M1_ADDR_MASK_BITWISE_EN_M 0xFFFFFFFF

/* PCIE_WRAP_DBI_GW_M1_MIN_ADDR */
#define PCIE_WRAP_DBI_GW_M1_MIN_ADDR_VAL_S 0
#define PCIE_WRAP_DBI_GW_M1_MIN_ADDR_VAL_M 0xFFFFFFFF

/* PCIE_WRAP_DBI_GW_M1_MAX_ADDR */
#define PCIE_WRAP_DBI_GW_M1_MAX_ADDR_VAL_S 0
#define PCIE_WRAP_DBI_GW_M1_MAX_ADDR_VAL_M 0xFFFFFFFF

/* PCIE_WRAP_DBI_GW_M1_PROT_CTRL */
#define PCIE_WRAP_DBI_GW_M1_PROT_CTRL_PRIO_WR_S 0
#define PCIE_WRAP_DBI_GW_M1_PROT_CTRL_PRIO_WR_M 0x3
#define PCIE_WRAP_DBI_GW_M1_PROT_CTRL_PRIO_RD_S 2
#define PCIE_WRAP_DBI_GW_M1_PROT_CTRL_PRIO_RD_M 0xC
#define PCIE_WRAP_DBI_GW_M1_PROT_CTRL_PRIO_EN_S 4
#define PCIE_WRAP_DBI_GW_M1_PROT_CTRL_PRIO_EN_M 0x10

/* PCIE_WRAP_DBI_GW_M1_TERM_RESP */
#define PCIE_WRAP_DBI_GW_M1_TERM_RESP_PSLVERR_S 0
#define PCIE_WRAP_DBI_GW_M1_TERM_RESP_PSLVERR_M 0x1

/* PCIE_WRAP_DBI_GW_M1_INFO_FIFO_STS */
#define PCIE_WRAP_DBI_GW_M1_INFO_FIFO_STS_EMPTY_S 0
#define PCIE_WRAP_DBI_GW_M1_INFO_FIFO_STS_EMPTY_M 0x1
#define PCIE_WRAP_DBI_GW_M1_INFO_FIFO_STS_FULL_S 1
#define PCIE_WRAP_DBI_GW_M1_INFO_FIFO_STS_FULL_M 0x2

/* PCIE_WRAP_DBI_GW_M1_INFO_FIFO_DATA0 */
#define PCIE_WRAP_DBI_GW_M1_INFO_FIFO_DATA0_ADDR_S 0
#define PCIE_WRAP_DBI_GW_M1_INFO_FIFO_DATA0_ADDR_M 0xFFFFFFFF

/* PCIE_WRAP_DBI_GW_M1_INFO_FIFO_DATA1 */
#define PCIE_WRAP_DBI_GW_M1_INFO_FIFO_DATA1_USER_S 0
#define PCIE_WRAP_DBI_GW_M1_INFO_FIFO_DATA1_USER_M 0x3FFFFFFF
#define PCIE_WRAP_DBI_GW_M1_INFO_FIFO_DATA1_PROT_S 30
#define PCIE_WRAP_DBI_GW_M1_INFO_FIFO_DATA1_PROT_M 0xC0000000

#endif /* ASIC_REG_PCIE_WRAP_DBI_GW_M1_MASKS_H_ */
