/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PDMA_CMN_B_PQM_CMN_B_REGS_H_
#define ASIC_REG_PDMA_CMN_B_PQM_CMN_B_REGS_H_

/*
 *****************************************
 *   PDMA_CMN_B_PQM_CMN_B
 *   (Prototype: PQM_CMN_B)
 *****************************************
 */

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_0 0x0

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_1 0x4

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_2 0x8

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_3 0xC

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_4 0x10

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_5 0x14

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_6 0x18

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_7 0x1C

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_8 0x20

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_9 0x24

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_10 0x28

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_11 0x2C

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_12 0x30

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_13 0x34

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_14 0x38

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_15 0x3C

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_16 0x40

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_17 0x44

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_18 0x48

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_19 0x4C

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_20 0x50

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_21 0x54

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_22 0x58

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_23 0x5C

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_24 0x60

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_25 0x64

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_26 0x68

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_27 0x6C

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_28 0x70

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_29 0x74

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_30 0x78

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_31 0x7C

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_32 0x80

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_33 0x84

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_34 0x88

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_35 0x8C

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_36 0x90

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_37 0x94

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_38 0x98

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_39 0x9C

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_40 0xA0

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_41 0xA4

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_42 0xA8

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_43 0xAC

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_44 0xB0

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_45 0xB4

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_46 0xB8

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_47 0xBC

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_48 0xC0

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_49 0xC4

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_50 0xC8

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_51 0xCC

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_52 0xD0

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_53 0xD4

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_54 0xD8

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_55 0xDC

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_56 0xE0

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_57 0xE4

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_58 0xE8

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_59 0xEC

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_60 0xF0

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_61 0xF4

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_62 0xF8

#define mmPDMA_CMN_B_PQM_CMN_B_WR64_BASE_ADDR_63 0xFC

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_0 0x100

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_1 0x104

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_2 0x108

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_3 0x10C

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_4 0x110

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_5 0x114

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_6 0x118

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_7 0x11C

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_8 0x120

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_9 0x124

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_10 0x128

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_11 0x12C

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_12 0x130

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_13 0x134

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_14 0x138

#define mmPDMA_CMN_B_PQM_CMN_B_CP_MSG_BASE_ADDR_15 0x13C

#define mmPDMA_CMN_B_PQM_CMN_B_PDMA_BASE_ADDR 0x140

#define mmPDMA_CMN_B_PQM_CMN_B_CH_A_BASE_ADDR 0x144

#define mmPDMA_CMN_B_PQM_CMN_B_LPDMA_BASE_ADDR 0x148

#define mmPDMA_CMN_B_PQM_CMN_B_CTRL_MAIN_ADDR 0x14C

#define mmPDMA_CMN_B_PQM_CMN_B_COMMIT_ADDR 0x150

#define mmPDMA_CMN_B_PQM_CMN_B_CP_BARRIER_CFG 0x154

#define mmPDMA_CMN_B_PQM_CMN_B_CGM_CFG 0x158

#define mmPDMA_CMN_B_PQM_CMN_B_CGM_STS 0x15C

#define mmPDMA_CMN_B_PQM_CMN_B_CGM_CFG1 0x160

#define mmPDMA_CMN_B_PQM_CMN_B_GLBL_STS 0x164

#define mmPDMA_CMN_B_PQM_CMN_B_GLBL_CP_STS 0x168

#define mmPDMA_CMN_B_PQM_CMN_B_GLBL_CQ_STS 0x16C

#define mmPDMA_CMN_B_PQM_CMN_B_GLBL_CQ_CQE_HI 0x170

#define mmPDMA_CMN_B_PQM_CMN_B_GLBL_CQ_CQE_LO 0x174

#define mmPDMA_CMN_B_PQM_CMN_B_GLBL_CQ_CL_IDLE_0 0x178

#define mmPDMA_CMN_B_PQM_CMN_B_GLBL_CQ_CL_IDLE_1 0x17C

#define mmPDMA_CMN_B_PQM_CMN_B_GLBL_CQ_CL_VLD_0 0x180

#define mmPDMA_CMN_B_PQM_CMN_B_GLBL_CQ_CL_VLD_1 0x184

#define mmPDMA_CMN_B_PQM_CMN_B_GLBL_CQ_CL_CH_0 0x188

#define mmPDMA_CMN_B_PQM_CMN_B_GLBL_CQ_CL_CH_1 0x18C

#define mmPDMA_CMN_B_PQM_CMN_B_GLBL_CQ_CL_CH_2 0x190

#define mmPDMA_CMN_B_PQM_CMN_B_GLBL_CQ_CL_CH_3 0x194

#define mmPDMA_CMN_B_PQM_CMN_B_CFG 0x198

#define mmPDMA_CMN_B_PQM_CMN_B_DBG_CHANNEL_FILTER 0x19C

#define mmPDMA_CMN_B_PQM_CMN_B_SEI_STATUS 0x1A0

#define mmPDMA_CMN_B_PQM_CMN_B_SEI_MASK 0x1A4

#endif /* ASIC_REG_PDMA_CMN_B_PQM_CMN_B_REGS_H_ */
