/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PDUP_ENG_MASKS_H_
#define ASIC_REG_PDUP_ENG_MASKS_H_

/*
 *****************************************
 *   PDUP_ENG
 *   (Prototype: PDUP_ENG)
 *****************************************
 */

/* PDUP_ENG_DUP_ADDR_GR_0 */
#define PDUP_ENG_DUP_ADDR_GR_0_VAL_S 0
#define PDUP_ENG_DUP_ADDR_GR_0_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_ADDR_GR_1 */
#define PDUP_ENG_DUP_ADDR_GR_1_VAL_S 0
#define PDUP_ENG_DUP_ADDR_GR_1_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_ADDR_GR_2 */
#define PDUP_ENG_DUP_ADDR_GR_2_VAL_S 0
#define PDUP_ENG_DUP_ADDR_GR_2_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_ADDR_GR_3 */
#define PDUP_ENG_DUP_ADDR_GR_3_VAL_S 0
#define PDUP_ENG_DUP_ADDR_GR_3_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_ADDR_GR_4 */
#define PDUP_ENG_DUP_ADDR_GR_4_VAL_S 0
#define PDUP_ENG_DUP_ADDR_GR_4_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_ADDR_GR_5 */
#define PDUP_ENG_DUP_ADDR_GR_5_VAL_S 0
#define PDUP_ENG_DUP_ADDR_GR_5_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_ADDR_GR_6 */
#define PDUP_ENG_DUP_ADDR_GR_6_VAL_S 0
#define PDUP_ENG_DUP_ADDR_GR_6_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_ADDR_GR_7 */
#define PDUP_ENG_DUP_ADDR_GR_7_VAL_S 0
#define PDUP_ENG_DUP_ADDR_GR_7_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_ADDR_GR_8 */
#define PDUP_ENG_DUP_ADDR_GR_8_VAL_S 0
#define PDUP_ENG_DUP_ADDR_GR_8_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_ADDR_GR_9 */
#define PDUP_ENG_DUP_ADDR_GR_9_VAL_S 0
#define PDUP_ENG_DUP_ADDR_GR_9_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_ADDR_GR_10 */
#define PDUP_ENG_DUP_ADDR_GR_10_VAL_S 0
#define PDUP_ENG_DUP_ADDR_GR_10_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_ADDR_GR_11 */
#define PDUP_ENG_DUP_ADDR_GR_11_VAL_S 0
#define PDUP_ENG_DUP_ADDR_GR_11_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_ADDR_GR_12 */
#define PDUP_ENG_DUP_ADDR_GR_12_VAL_S 0
#define PDUP_ENG_DUP_ADDR_GR_12_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_ADDR_GR_13 */
#define PDUP_ENG_DUP_ADDR_GR_13_VAL_S 0
#define PDUP_ENG_DUP_ADDR_GR_13_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_MASK_GR_0 */
#define PDUP_ENG_DUP_MASK_GR_0_VAL_S 0
#define PDUP_ENG_DUP_MASK_GR_0_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_MASK_GR_1 */
#define PDUP_ENG_DUP_MASK_GR_1_VAL_S 0
#define PDUP_ENG_DUP_MASK_GR_1_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_MASK_GR_2 */
#define PDUP_ENG_DUP_MASK_GR_2_VAL_S 0
#define PDUP_ENG_DUP_MASK_GR_2_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_MASK_GR_3 */
#define PDUP_ENG_DUP_MASK_GR_3_VAL_S 0
#define PDUP_ENG_DUP_MASK_GR_3_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_MASK_GR_4 */
#define PDUP_ENG_DUP_MASK_GR_4_VAL_S 0
#define PDUP_ENG_DUP_MASK_GR_4_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_MASK_GR_5 */
#define PDUP_ENG_DUP_MASK_GR_5_VAL_S 0
#define PDUP_ENG_DUP_MASK_GR_5_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_MASK_GR_6 */
#define PDUP_ENG_DUP_MASK_GR_6_VAL_S 0
#define PDUP_ENG_DUP_MASK_GR_6_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_MASK_GR_7 */
#define PDUP_ENG_DUP_MASK_GR_7_VAL_S 0
#define PDUP_ENG_DUP_MASK_GR_7_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_MASK_GR_8 */
#define PDUP_ENG_DUP_MASK_GR_8_VAL_S 0
#define PDUP_ENG_DUP_MASK_GR_8_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_MASK_GR_9 */
#define PDUP_ENG_DUP_MASK_GR_9_VAL_S 0
#define PDUP_ENG_DUP_MASK_GR_9_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_MASK_GR_10 */
#define PDUP_ENG_DUP_MASK_GR_10_VAL_S 0
#define PDUP_ENG_DUP_MASK_GR_10_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_MASK_GR_11 */
#define PDUP_ENG_DUP_MASK_GR_11_VAL_S 0
#define PDUP_ENG_DUP_MASK_GR_11_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_MASK_GR_12 */
#define PDUP_ENG_DUP_MASK_GR_12_VAL_S 0
#define PDUP_ENG_DUP_MASK_GR_12_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_MASK_GR_13 */
#define PDUP_ENG_DUP_MASK_GR_13_VAL_S 0
#define PDUP_ENG_DUP_MASK_GR_13_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_OFFSET_GR_0 */
#define PDUP_ENG_DUP_OFFSET_GR_0_VAL_S 0
#define PDUP_ENG_DUP_OFFSET_GR_0_VAL_M 0xFF

/* PDUP_ENG_DUP_OFFSET_GR_1 */
#define PDUP_ENG_DUP_OFFSET_GR_1_VAL_S 0
#define PDUP_ENG_DUP_OFFSET_GR_1_VAL_M 0xFF

/* PDUP_ENG_DUP_OFFSET_GR_2 */
#define PDUP_ENG_DUP_OFFSET_GR_2_VAL_S 0
#define PDUP_ENG_DUP_OFFSET_GR_2_VAL_M 0xFF

/* PDUP_ENG_DUP_OFFSET_GR_3 */
#define PDUP_ENG_DUP_OFFSET_GR_3_VAL_S 0
#define PDUP_ENG_DUP_OFFSET_GR_3_VAL_M 0xFF

/* PDUP_ENG_DUP_OFFSET_GR_4 */
#define PDUP_ENG_DUP_OFFSET_GR_4_VAL_S 0
#define PDUP_ENG_DUP_OFFSET_GR_4_VAL_M 0xFF

/* PDUP_ENG_DUP_OFFSET_GR_5 */
#define PDUP_ENG_DUP_OFFSET_GR_5_VAL_S 0
#define PDUP_ENG_DUP_OFFSET_GR_5_VAL_M 0xFF

/* PDUP_ENG_DUP_OFFSET_GR_6 */
#define PDUP_ENG_DUP_OFFSET_GR_6_VAL_S 0
#define PDUP_ENG_DUP_OFFSET_GR_6_VAL_M 0xFF

/* PDUP_ENG_DUP_OFFSET_GR_7 */
#define PDUP_ENG_DUP_OFFSET_GR_7_VAL_S 0
#define PDUP_ENG_DUP_OFFSET_GR_7_VAL_M 0xFF

/* PDUP_ENG_DUP_OFFSET_GR_8 */
#define PDUP_ENG_DUP_OFFSET_GR_8_VAL_S 0
#define PDUP_ENG_DUP_OFFSET_GR_8_VAL_M 0xFF

/* PDUP_ENG_DUP_OFFSET_GR_9 */
#define PDUP_ENG_DUP_OFFSET_GR_9_VAL_S 0
#define PDUP_ENG_DUP_OFFSET_GR_9_VAL_M 0xFF

/* PDUP_ENG_DUP_OFFSET_GR_10 */
#define PDUP_ENG_DUP_OFFSET_GR_10_VAL_S 0
#define PDUP_ENG_DUP_OFFSET_GR_10_VAL_M 0xFF

/* PDUP_ENG_DUP_OFFSET_GR_11 */
#define PDUP_ENG_DUP_OFFSET_GR_11_VAL_S 0
#define PDUP_ENG_DUP_OFFSET_GR_11_VAL_M 0xFF

/* PDUP_ENG_DUP_OFFSET_GR_12 */
#define PDUP_ENG_DUP_OFFSET_GR_12_VAL_S 0
#define PDUP_ENG_DUP_OFFSET_GR_12_VAL_M 0xFF

/* PDUP_ENG_DUP_OFFSET_GR_13 */
#define PDUP_ENG_DUP_OFFSET_GR_13_VAL_S 0
#define PDUP_ENG_DUP_OFFSET_GR_13_VAL_M 0xFF

/* PDUP_ENG_DUP_UC_GR_0 */
#define PDUP_ENG_DUP_UC_GR_0_ADDR_S 0
#define PDUP_ENG_DUP_UC_GR_0_ADDR_M 0x1FFFFFFF
#define PDUP_ENG_DUP_UC_GR_0_EN_S 31
#define PDUP_ENG_DUP_UC_GR_0_EN_M 0x80000000

/* PDUP_ENG_DUP_UC_GR_1 */
#define PDUP_ENG_DUP_UC_GR_1_ADDR_S 0
#define PDUP_ENG_DUP_UC_GR_1_ADDR_M 0x1FFFFFFF
#define PDUP_ENG_DUP_UC_GR_1_EN_S 31
#define PDUP_ENG_DUP_UC_GR_1_EN_M 0x80000000

/* PDUP_ENG_DUP_UC_GR_2 */
#define PDUP_ENG_DUP_UC_GR_2_ADDR_S 0
#define PDUP_ENG_DUP_UC_GR_2_ADDR_M 0x1FFFFFFF
#define PDUP_ENG_DUP_UC_GR_2_EN_S 31
#define PDUP_ENG_DUP_UC_GR_2_EN_M 0x80000000

/* PDUP_ENG_DUP_UC_GR_3 */
#define PDUP_ENG_DUP_UC_GR_3_ADDR_S 0
#define PDUP_ENG_DUP_UC_GR_3_ADDR_M 0x1FFFFFFF
#define PDUP_ENG_DUP_UC_GR_3_EN_S 31
#define PDUP_ENG_DUP_UC_GR_3_EN_M 0x80000000

/* PDUP_ENG_DUP_UC_GR_4 */
#define PDUP_ENG_DUP_UC_GR_4_ADDR_S 0
#define PDUP_ENG_DUP_UC_GR_4_ADDR_M 0x1FFFFFFF
#define PDUP_ENG_DUP_UC_GR_4_EN_S 31
#define PDUP_ENG_DUP_UC_GR_4_EN_M 0x80000000

/* PDUP_ENG_DUP_UC_GR_5 */
#define PDUP_ENG_DUP_UC_GR_5_ADDR_S 0
#define PDUP_ENG_DUP_UC_GR_5_ADDR_M 0x1FFFFFFF
#define PDUP_ENG_DUP_UC_GR_5_EN_S 31
#define PDUP_ENG_DUP_UC_GR_5_EN_M 0x80000000

/* PDUP_ENG_DUP_UC_GR_6 */
#define PDUP_ENG_DUP_UC_GR_6_ADDR_S 0
#define PDUP_ENG_DUP_UC_GR_6_ADDR_M 0x1FFFFFFF
#define PDUP_ENG_DUP_UC_GR_6_EN_S 31
#define PDUP_ENG_DUP_UC_GR_6_EN_M 0x80000000

/* PDUP_ENG_DUP_UC_GR_7 */
#define PDUP_ENG_DUP_UC_GR_7_ADDR_S 0
#define PDUP_ENG_DUP_UC_GR_7_ADDR_M 0x1FFFFFFF
#define PDUP_ENG_DUP_UC_GR_7_EN_S 31
#define PDUP_ENG_DUP_UC_GR_7_EN_M 0x80000000

/* PDUP_ENG_DUP_UC_GR_8 */
#define PDUP_ENG_DUP_UC_GR_8_ADDR_S 0
#define PDUP_ENG_DUP_UC_GR_8_ADDR_M 0x1FFFFFFF
#define PDUP_ENG_DUP_UC_GR_8_EN_S 31
#define PDUP_ENG_DUP_UC_GR_8_EN_M 0x80000000

/* PDUP_ENG_DUP_UC_GR_9 */
#define PDUP_ENG_DUP_UC_GR_9_ADDR_S 0
#define PDUP_ENG_DUP_UC_GR_9_ADDR_M 0x1FFFFFFF
#define PDUP_ENG_DUP_UC_GR_9_EN_S 31
#define PDUP_ENG_DUP_UC_GR_9_EN_M 0x80000000

/* PDUP_ENG_DUP_UC_GR_10 */
#define PDUP_ENG_DUP_UC_GR_10_ADDR_S 0
#define PDUP_ENG_DUP_UC_GR_10_ADDR_M 0x1FFFFFFF
#define PDUP_ENG_DUP_UC_GR_10_EN_S 31
#define PDUP_ENG_DUP_UC_GR_10_EN_M 0x80000000

/* PDUP_ENG_DUP_UC_GR_11 */
#define PDUP_ENG_DUP_UC_GR_11_ADDR_S 0
#define PDUP_ENG_DUP_UC_GR_11_ADDR_M 0x1FFFFFFF
#define PDUP_ENG_DUP_UC_GR_11_EN_S 31
#define PDUP_ENG_DUP_UC_GR_11_EN_M 0x80000000

/* PDUP_ENG_DUP_UC_GR_12 */
#define PDUP_ENG_DUP_UC_GR_12_ADDR_S 0
#define PDUP_ENG_DUP_UC_GR_12_ADDR_M 0x1FFFFFFF
#define PDUP_ENG_DUP_UC_GR_12_EN_S 31
#define PDUP_ENG_DUP_UC_GR_12_EN_M 0x80000000

/* PDUP_ENG_DUP_UC_GR_13 */
#define PDUP_ENG_DUP_UC_GR_13_ADDR_S 0
#define PDUP_ENG_DUP_UC_GR_13_ADDR_M 0x1FFFFFFF
#define PDUP_ENG_DUP_UC_GR_13_EN_S 31
#define PDUP_ENG_DUP_UC_GR_13_EN_M 0x80000000

/* PDUP_ENG_DUP_CONTROL_HALT */
#define PDUP_ENG_DUP_CONTROL_HALT_VAL_S 0
#define PDUP_ENG_DUP_CONTROL_HALT_VAL_M 0x1

/* PDUP_ENG_DUP_CONTROL_MODE */
#define PDUP_ENG_DUP_CONTROL_MODE_MC_MODE_S 0
#define PDUP_ENG_DUP_CONTROL_MODE_MC_MODE_M 0x1
#define PDUP_ENG_DUP_CONTROL_MODE_OVF_MODE_S 4
#define PDUP_ENG_DUP_CONTROL_MODE_OVF_MODE_M 0x10

/* PDUP_ENG_DUP_CONFIG */
#define PDUP_ENG_DUP_CONFIG_GRP_NUM_S 0
#define PDUP_ENG_DUP_CONFIG_GRP_NUM_M 0xFF
#define PDUP_ENG_DUP_CONFIG_ADDR_NUM_S 8
#define PDUP_ENG_DUP_CONFIG_ADDR_NUM_M 0xFF00
#define PDUP_ENG_DUP_CONFIG_FIFO_SIZE_S 16
#define PDUP_ENG_DUP_CONFIG_FIFO_SIZE_M 0xFF0000

/* PDUP_ENG_DUP_INFLIGHT_LIMIT */
#define PDUP_ENG_DUP_INFLIGHT_LIMIT_VAL_S 0
#define PDUP_ENG_DUP_INFLIGHT_LIMIT_VAL_M 0x3FF

/* PDUP_ENG_DUP_STATUS */
#define PDUP_ENG_DUP_STATUS_DUP_INFLIGHT_S 0
#define PDUP_ENG_DUP_STATUS_DUP_INFLIGHT_M 0x3FF
#define PDUP_ENG_DUP_STATUS_FIFO_FULLNESS_S 16
#define PDUP_ENG_DUP_STATUS_FIFO_FULLNESS_M 0x3FF0000
#define PDUP_ENG_DUP_STATUS_BUSY_S 31
#define PDUP_ENG_DUP_STATUS_BUSY_M 0x80000000

/* PDUP_ENG_DUP_FIFO_FULL_TH */
#define PDUP_ENG_DUP_FIFO_FULL_TH_VAL_S 0
#define PDUP_ENG_DUP_FIFO_FULL_TH_VAL_M 0x7FF

/* PDUP_ENG_DUP_BUSER_RESPONSE */
#define PDUP_ENG_DUP_BUSER_RESPONSE_PUSH_S 0
#define PDUP_ENG_DUP_BUSER_RESPONSE_PUSH_M 0xFF
#define PDUP_ENG_DUP_BUSER_RESPONSE_ENG_CFG_S 8
#define PDUP_ENG_DUP_BUSER_RESPONSE_ENG_CFG_M 0xFF00
#define PDUP_ENG_DUP_BUSER_RESPONSE_NOC_CFG_S 16
#define PDUP_ENG_DUP_BUSER_RESPONSE_NOC_CFG_M 0xFF0000

/* PDUP_ENG_DUP_SEI_INTR_STS */
#define PDUP_ENG_DUP_SEI_INTR_STS_VAL_S 0
#define PDUP_ENG_DUP_SEI_INTR_STS_VAL_M 0xFF

/* PDUP_ENG_DUP_SEI_INTR_CLR */
#define PDUP_ENG_DUP_SEI_INTR_CLR_VAL_S 0
#define PDUP_ENG_DUP_SEI_INTR_CLR_VAL_M 0xFF

/* PDUP_ENG_DUP_SEI_INTR_MASK */
#define PDUP_ENG_DUP_SEI_INTR_MASK_VAL_S 0
#define PDUP_ENG_DUP_SEI_INTR_MASK_VAL_M 0xFF

/* PDUP_ENG_DUP_PUSH_MIN_ADDR */
#define PDUP_ENG_DUP_PUSH_MIN_ADDR_VAL_S 0
#define PDUP_ENG_DUP_PUSH_MIN_ADDR_VAL_M 0xFFFF

/* PDUP_ENG_DUP_PUSH_MAX_ADDR */
#define PDUP_ENG_DUP_PUSH_MAX_ADDR_VAL_S 0
#define PDUP_ENG_DUP_PUSH_MAX_ADDR_VAL_M 0xFFFF

/* PDUP_ENG_DUP_CFG_MIN_ADDR */
#define PDUP_ENG_DUP_CFG_MIN_ADDR_VAL_S 0
#define PDUP_ENG_DUP_CFG_MIN_ADDR_VAL_M 0xFFFF

/* PDUP_ENG_DUP_CFG_MAX_ADDR */
#define PDUP_ENG_DUP_CFG_MAX_ADDR_VAL_S 0
#define PDUP_ENG_DUP_CFG_MAX_ADDR_VAL_M 0xFFFF

/* PDUP_ENG_DUP_PUSH_BLOCK_DUP_CFG_EN */
#define PDUP_ENG_DUP_PUSH_BLOCK_DUP_CFG_EN_VAL_S 0
#define PDUP_ENG_DUP_PUSH_BLOCK_DUP_CFG_EN_VAL_M 0x1

/* PDUP_ENG_DUP_CFG_BLOCK_DUP_PUSH_EN */
#define PDUP_ENG_DUP_CFG_BLOCK_DUP_PUSH_EN_VAL_S 0
#define PDUP_ENG_DUP_CFG_BLOCK_DUP_PUSH_EN_VAL_M 0x1

/* PDUP_ENG_ENG2DUP_FORK_WIN_EN */
#define PDUP_ENG_ENG2DUP_FORK_WIN_EN_VAL_S 0
#define PDUP_ENG_ENG2DUP_FORK_WIN_EN_VAL_M 0x3

/* PDUP_ENG_ENG2DUP_FORK_MIN_ADDR0 */
#define PDUP_ENG_ENG2DUP_FORK_MIN_ADDR0_VAL_S 0
#define PDUP_ENG_ENG2DUP_FORK_MIN_ADDR0_VAL_M 0x1FFFFFFF

/* PDUP_ENG_ENG2DUP_FORK_MAX_ADDR0 */
#define PDUP_ENG_ENG2DUP_FORK_MAX_ADDR0_VAL_S 0
#define PDUP_ENG_ENG2DUP_FORK_MAX_ADDR0_VAL_M 0x1FFFFFFF

/* PDUP_ENG_ENG2DUP_FORK_MASK_ADDR0 */
#define PDUP_ENG_ENG2DUP_FORK_MASK_ADDR0_VAL_S 0
#define PDUP_ENG_ENG2DUP_FORK_MASK_ADDR0_VAL_M 0x1FFFFFFF

/* PDUP_ENG_ENG2DUP_FORK_MIN_ADDR1 */
#define PDUP_ENG_ENG2DUP_FORK_MIN_ADDR1_VAL_S 0
#define PDUP_ENG_ENG2DUP_FORK_MIN_ADDR1_VAL_M 0x1FFFFFFF

/* PDUP_ENG_ENG2DUP_FORK_MAX_ADDR1 */
#define PDUP_ENG_ENG2DUP_FORK_MAX_ADDR1_VAL_S 0
#define PDUP_ENG_ENG2DUP_FORK_MAX_ADDR1_VAL_M 0x1FFFFFFF

/* PDUP_ENG_ENG2DUP_FORK_MASK_ADDR1 */
#define PDUP_ENG_ENG2DUP_FORK_MASK_ADDR1_VAL_S 0
#define PDUP_ENG_ENG2DUP_FORK_MASK_ADDR1_VAL_M 0x1FFFFFFF

/* PDUP_ENG_ENG2DUP_FORK_TERMINATE_BRESP */
#define PDUP_ENG_ENG2DUP_FORK_TERMINATE_BRESP_VAL_S 0
#define PDUP_ENG_ENG2DUP_FORK_TERMINATE_BRESP_VAL_M 0x3

/* PDUP_ENG_ENG2DUP_FORK_TERMINATE_RRESP */
#define PDUP_ENG_ENG2DUP_FORK_TERMINATE_RRESP_VAL_S 0
#define PDUP_ENG_ENG2DUP_FORK_TERMINATE_RRESP_VAL_M 0x3

/* PDUP_ENG_ENG2DUP_FORK_ARADDR_INTR_INFO */
#define PDUP_ENG_ENG2DUP_FORK_ARADDR_INTR_INFO_VAL_S 0
#define PDUP_ENG_ENG2DUP_FORK_ARADDR_INTR_INFO_VAL_M 0x1FFFFFFF

/* PDUP_ENG_ENG2DUP_FORK_AWADDR_INTR_INFO */
#define PDUP_ENG_ENG2DUP_FORK_AWADDR_INTR_INFO_VAL_S 0
#define PDUP_ENG_ENG2DUP_FORK_AWADDR_INTR_INFO_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_AXI2APB_CFG */
#define PDUP_ENG_DUP_AXI2APB_CFG_MASK_ERR_RSP_S 0
#define PDUP_ENG_DUP_AXI2APB_CFG_MASK_ERR_RSP_M 0x1
#define PDUP_ENG_DUP_AXI2APB_CFG_BLK_PARTIAL_STRB_S 4
#define PDUP_ENG_DUP_AXI2APB_CFG_BLK_PARTIAL_STRB_M 0x10
#define PDUP_ENG_DUP_AXI2APB_CFG_SPL_ERR_RSP_S 8
#define PDUP_ENG_DUP_AXI2APB_CFG_SPL_ERR_RSP_M 0x100

/* PDUP_ENG_DUP_APB_FORK_MAX_ADDR0 */
#define PDUP_ENG_DUP_APB_FORK_MAX_ADDR0_VAL_S 0
#define PDUP_ENG_DUP_APB_FORK_MAX_ADDR0_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_APB_FORK_MAX_ADDR1 */
#define PDUP_ENG_DUP_APB_FORK_MAX_ADDR1_VAL_S 0
#define PDUP_ENG_DUP_APB_FORK_MAX_ADDR1_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_APB_FORK_MAX_ADDR2 */
#define PDUP_ENG_DUP_APB_FORK_MAX_ADDR2_VAL_S 0
#define PDUP_ENG_DUP_APB_FORK_MAX_ADDR2_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_PUSH_TERMINATOR_BRESP */
#define PDUP_ENG_DUP_PUSH_TERMINATOR_BRESP_VAL_S 0
#define PDUP_ENG_DUP_PUSH_TERMINATOR_BRESP_VAL_M 0x3

/* PDUP_ENG_DUP_PUSH_TERMINATOR_RRESP */
#define PDUP_ENG_DUP_PUSH_TERMINATOR_RRESP_VAL_S 0
#define PDUP_ENG_DUP_PUSH_TERMINATOR_RRESP_VAL_M 0x3

/* PDUP_ENG_DUP_DBG_LAST_GRP */
#define PDUP_ENG_DUP_DBG_LAST_GRP_VAL_S 0
#define PDUP_ENG_DUP_DBG_LAST_GRP_VAL_M 0x1F

/* PDUP_ENG_DUP_DBG_LAST_WDATA */
#define PDUP_ENG_DUP_DBG_LAST_WDATA_VAL_S 0
#define PDUP_ENG_DUP_DBG_LAST_WDATA_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_DBG_LAST_AWADDR */
#define PDUP_ENG_DUP_DBG_LAST_AWADDR_VAL_S 0
#define PDUP_ENG_DUP_DBG_LAST_AWADDR_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_DBG_PREV_WDATA */
#define PDUP_ENG_DUP_DBG_PREV_WDATA_VAL_S 0
#define PDUP_ENG_DUP_DBG_PREV_WDATA_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_DBG_PREV_AWADDR */
#define PDUP_ENG_DUP_DBG_PREV_AWADDR_VAL_S 0
#define PDUP_ENG_DUP_DBG_PREV_AWADDR_VAL_M 0x1FFFFFFF

/* PDUP_ENG_DUP_DBG_TOTAL_SERVED_REQ */
#define PDUP_ENG_DUP_DBG_TOTAL_SERVED_REQ_VAL_S 0
#define PDUP_ENG_DUP_DBG_TOTAL_SERVED_REQ_VAL_M 0xFFFFFFFF

/* PDUP_ENG_DUP_DBG_TOTAL_WR_REQ_CNT */
#define PDUP_ENG_DUP_DBG_TOTAL_WR_REQ_CNT_VAL_S 0
#define PDUP_ENG_DUP_DBG_TOTAL_WR_REQ_CNT_VAL_M 0xFFFFFFFF

#endif /* ASIC_REG_PDUP_ENG_MASKS_H_ */
