/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_SOB_OBJS_MASKS_H_
#define ASIC_REG_SOB_OBJS_MASKS_H_

/*
 *****************************************
 *   SOB_OBJS
 *   (Prototype: SOB_OBJS)
 *****************************************
 */

/* SOB_OBJS_SOB_OBJ_0 */
#define SOB_OBJS_SOB_OBJ_0_VAL_S 0
#define SOB_OBJS_SOB_OBJ_0_VAL_M 0x7FFF
#define SOB_OBJS_SOB_OBJ_0_LONG_SOB_S 24
#define SOB_OBJS_SOB_OBJ_0_LONG_SOB_M 0x1000000
#define SOB_OBJS_SOB_OBJ_0_ZERO_SOB_CNT_S 28
#define SOB_OBJS_SOB_OBJ_0_ZERO_SOB_CNT_M 0x10000000
#define SOB_OBJS_SOB_OBJ_0_TRACE_EVICT_S 30
#define SOB_OBJS_SOB_OBJ_0_TRACE_EVICT_M 0x40000000
#define SOB_OBJS_SOB_OBJ_0_INC_S 31
#define SOB_OBJS_SOB_OBJ_0_INC_M 0x80000000

/* SOB_OBJS_MON_PAY_ADDRL_0 */
#define SOB_OBJS_MON_PAY_ADDRL_0_ADDRL_S 0
#define SOB_OBJS_MON_PAY_ADDRL_0_ADDRL_M 0xFFFFFFFF

/* SOB_OBJS_MON_PAY_ADDRH_0 */
#define SOB_OBJS_MON_PAY_ADDRH_0_ADDRH_S 0
#define SOB_OBJS_MON_PAY_ADDRH_0_ADDRH_M 0xFFFFFFFF

/* SOB_OBJS_MON_PAY_DATA_0 */
#define SOB_OBJS_MON_PAY_DATA_0_DATA_S 0
#define SOB_OBJS_MON_PAY_DATA_0_DATA_M 0xFFFFFFFF

/* SOB_OBJS_MON_ARM_0 */
#define SOB_OBJS_MON_ARM_0_SID_S 0
#define SOB_OBJS_MON_ARM_0_SID_M 0xFF
#define SOB_OBJS_MON_ARM_0_MASK_S 8
#define SOB_OBJS_MON_ARM_0_MASK_M 0xFF00
#define SOB_OBJS_MON_ARM_0_SOP_S 16
#define SOB_OBJS_MON_ARM_0_SOP_M 0x10000
#define SOB_OBJS_MON_ARM_0_SOD_S 17
#define SOB_OBJS_MON_ARM_0_SOD_M 0xFFFE0000

/* SOB_OBJS_MON_CONFIG_0 */
#define SOB_OBJS_MON_CONFIG_0_LONG_SOB_S 0
#define SOB_OBJS_MON_CONFIG_0_LONG_SOB_M 0x1
#define SOB_OBJS_MON_CONFIG_0_CQ_EN_S 4
#define SOB_OBJS_MON_CONFIG_0_CQ_EN_M 0x10
#define SOB_OBJS_MON_CONFIG_0_LBW_EN_S 8
#define SOB_OBJS_MON_CONFIG_0_LBW_EN_M 0x100
#define SOB_OBJS_MON_CONFIG_0_SM_DATA_CONFIG_S 15
#define SOB_OBJS_MON_CONFIG_0_SM_DATA_CONFIG_M 0x8000
#define SOB_OBJS_MON_CONFIG_0_MSB_SID_S 16
#define SOB_OBJS_MON_CONFIG_0_MSB_SID_M 0xF0000
#define SOB_OBJS_MON_CONFIG_0_AUTO_ZERO_S 20
#define SOB_OBJS_MON_CONFIG_0_AUTO_ZERO_M 0x100000
#define SOB_OBJS_MON_CONFIG_0_WR_NUM_S 24
#define SOB_OBJS_MON_CONFIG_0_WR_NUM_M 0xF000000
#define SOB_OBJS_MON_CONFIG_0_LONG_HIGH_GROUP_S 31
#define SOB_OBJS_MON_CONFIG_0_LONG_HIGH_GROUP_M 0x80000000

/* SOB_OBJS_MON_STATUS_0 */
#define SOB_OBJS_MON_STATUS_0_VALID_S 0
#define SOB_OBJS_MON_STATUS_0_VALID_M 0x1
#define SOB_OBJS_MON_STATUS_0_PENDING_S 1
#define SOB_OBJS_MON_STATUS_0_PENDING_M 0x1FE
#define SOB_OBJS_MON_STATUS_0_PROT_S 9
#define SOB_OBJS_MON_STATUS_0_PROT_M 0x200
#define SOB_OBJS_MON_STATUS_0_PRIV_S 10
#define SOB_OBJS_MON_STATUS_0_PRIV_M 0x400

/* SOB_OBJS_CQ_DIRECT */
#define SOB_OBJS_CQ_DIRECT_VAL_S 0
#define SOB_OBJS_CQ_DIRECT_VAL_M 0xFFFFFFFF

/* SOB_OBJS_SM_SEC_0 */
#define SOB_OBJS_SM_SEC_0_SEC_VEC_S 0
#define SOB_OBJS_SM_SEC_0_SEC_VEC_M 0xFFFFFFFF

/* SOB_OBJS_SM_PRIV_0 */
#define SOB_OBJS_SM_PRIV_0_PRIV_S 0
#define SOB_OBJS_SM_PRIV_0_PRIV_M 0xFFFFFFFF

/* SOB_OBJS_SOB_OBJ_1 */
#define SOB_OBJS_SOB_OBJ_1_VAL_S 0
#define SOB_OBJS_SOB_OBJ_1_VAL_M 0x7FFF
#define SOB_OBJS_SOB_OBJ_1_LONG_SOB_S 24
#define SOB_OBJS_SOB_OBJ_1_LONG_SOB_M 0x1000000
#define SOB_OBJS_SOB_OBJ_1_ZERO_SOB_CNT_S 28
#define SOB_OBJS_SOB_OBJ_1_ZERO_SOB_CNT_M 0x10000000
#define SOB_OBJS_SOB_OBJ_1_TRACE_EVICT_S 30
#define SOB_OBJS_SOB_OBJ_1_TRACE_EVICT_M 0x40000000
#define SOB_OBJS_SOB_OBJ_1_INC_S 31
#define SOB_OBJS_SOB_OBJ_1_INC_M 0x80000000

/* SOB_OBJS_MON_PAY_ADDRL_1 */
#define SOB_OBJS_MON_PAY_ADDRL_1_ADDRL_S 0
#define SOB_OBJS_MON_PAY_ADDRL_1_ADDRL_M 0xFFFFFFFF

/* SOB_OBJS_MON_PAY_ADDRH_1 */
#define SOB_OBJS_MON_PAY_ADDRH_1_ADDRH_S 0
#define SOB_OBJS_MON_PAY_ADDRH_1_ADDRH_M 0xFFFFFFFF

/* SOB_OBJS_MON_PAY_DATA_1 */
#define SOB_OBJS_MON_PAY_DATA_1_DATA_S 0
#define SOB_OBJS_MON_PAY_DATA_1_DATA_M 0xFFFFFFFF

/* SOB_OBJS_MON_ARM_1 */
#define SOB_OBJS_MON_ARM_1_SID_S 0
#define SOB_OBJS_MON_ARM_1_SID_M 0xFF
#define SOB_OBJS_MON_ARM_1_MASK_S 8
#define SOB_OBJS_MON_ARM_1_MASK_M 0xFF00
#define SOB_OBJS_MON_ARM_1_SOP_S 16
#define SOB_OBJS_MON_ARM_1_SOP_M 0x10000
#define SOB_OBJS_MON_ARM_1_SOD_S 17
#define SOB_OBJS_MON_ARM_1_SOD_M 0xFFFE0000

/* SOB_OBJS_MON_CONFIG_1 */
#define SOB_OBJS_MON_CONFIG_1_LONG_SOB_S 0
#define SOB_OBJS_MON_CONFIG_1_LONG_SOB_M 0x1
#define SOB_OBJS_MON_CONFIG_1_CQ_EN_S 4
#define SOB_OBJS_MON_CONFIG_1_CQ_EN_M 0x10
#define SOB_OBJS_MON_CONFIG_1_LBW_EN_S 8
#define SOB_OBJS_MON_CONFIG_1_LBW_EN_M 0x100
#define SOB_OBJS_MON_CONFIG_1_SM_DATA_CONFIG_S 15
#define SOB_OBJS_MON_CONFIG_1_SM_DATA_CONFIG_M 0x8000
#define SOB_OBJS_MON_CONFIG_1_MSB_SID_S 16
#define SOB_OBJS_MON_CONFIG_1_MSB_SID_M 0xF0000
#define SOB_OBJS_MON_CONFIG_1_AUTO_ZERO_S 20
#define SOB_OBJS_MON_CONFIG_1_AUTO_ZERO_M 0x100000
#define SOB_OBJS_MON_CONFIG_1_WR_NUM_S 24
#define SOB_OBJS_MON_CONFIG_1_WR_NUM_M 0xF000000
#define SOB_OBJS_MON_CONFIG_1_LONG_HIGH_GROUP_S 31
#define SOB_OBJS_MON_CONFIG_1_LONG_HIGH_GROUP_M 0x80000000

/* SOB_OBJS_MON_STATUS_1 */
#define SOB_OBJS_MON_STATUS_1_VALID_S 0
#define SOB_OBJS_MON_STATUS_1_VALID_M 0x1
#define SOB_OBJS_MON_STATUS_1_PENDING_S 1
#define SOB_OBJS_MON_STATUS_1_PENDING_M 0x1FE
#define SOB_OBJS_MON_STATUS_1_PROT_S 9
#define SOB_OBJS_MON_STATUS_1_PROT_M 0x200
#define SOB_OBJS_MON_STATUS_1_PRIV_S 10
#define SOB_OBJS_MON_STATUS_1_PRIV_M 0x400

/* SOB_OBJS_SM_SEC_1 */
#define SOB_OBJS_SM_SEC_1_SEC_VEC_S 0
#define SOB_OBJS_SM_SEC_1_SEC_VEC_M 0xFFFFFFFF

/* SOB_OBJS_SM_PRIV_1 */
#define SOB_OBJS_SM_PRIV_1_PRIV_S 0
#define SOB_OBJS_SM_PRIV_1_PRIV_M 0xFFFFFFFF

#endif /* ASIC_REG_SOB_OBJS_MASKS_H_ */
