/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2022 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

#ifndef GAUDI3_REG_MAP_H_
#define GAUDI3_REG_MAP_H_

/*
 * PSOC scratch-pad registers
 */
#define mmPID_STATUS_REG			mmGLOBAL_CONF_SCRATCHPAD_1
#define mmCPU_BOOT_DEV_STS0			mmGLOBAL_CONF_SCRATCHPAD_20
#define mmCPU_BOOT_DEV_STS1			mmGLOBAL_CONF_SCRATCHPAD_21
#define mmCPU_CMD_STATUS_TO_HOST		mmGLOBAL_CONF_SCRATCHPAD_23
#define mmCPU_BOOT_ERR0				mmGLOBAL_CONF_SCRATCHPAD_24
#define mmCPU_BOOT_ERR1				mmGLOBAL_CONF_SCRATCHPAD_25
#define mmUPD_STS				mmGLOBAL_CONF_SCRATCHPAD_26
#define mmUPD_CMD				mmGLOBAL_CONF_SCRATCHPAD_27
#define mmHW_STATE				mmCPU_IF_KMD_HW_DIRTY_STATUS

#define mmUPD_PENDING_STS			mmD0_PSOC_GLOBAL_CONF_COLD_RST_FLOPS_3

#define mmVUART0_TX_DATA			mmD0_PCIE_AUX_SW_GENERAL_PURPOSE_0
#define mmVUART0_TX_STATUS			mmD0_PCIE_AUX_SW_GENERAL_PURPOSE_1
#define mmVUART1_TX_DATA			mmD0_PCIE_AUX_SW_GENERAL_PURPOSE_4
#define mmVUART1_TX_STATUS			mmD0_PCIE_AUX_SW_GENERAL_PURPOSE_5

#define mmD0_PIF_ARC_ERROR			mmD0_PIF_ARC_SPECIAL_GLBL_SPARE_0
#define mmD1_PIF_ARC_ERROR			mmD1_PIF_ARC_SPECIAL_GLBL_SPARE_0
#define mmD0_PIF_ARC_STATUS			mmD0_PIF_ARC_SPECIAL_GLBL_SPARE_1
#define mmD1_PIF_ARC_STATUS			mmD1_PIF_ARC_SPECIAL_GLBL_SPARE_1

/* PID command registers - values TBD */
#define mmPID_CMD_REQ_REG			0
#define mmPID_CMD_REQ_REG_HI			0
#define mmPID_CMD_RSP_REG			0
#define mmPID_CMD_RSP_REG_HI			0
#define mmPID_CMD_TELEMETRY_REG_0		0
#define mmPID_CMD_TELEMETRY_REG_0_HI		0
#define mmPID_CMD_TELEMETRY_REG_1		0
#define mmPID_CMD_TELEMETRY_REG_1_HI		0

/* HBM status register for pre-silicon use */
#define mmHBM_STS				mmD0_PSOC_GLOBAL_CONF_SCRATCHPAD_31

#endif /* GAUDI3_REG_MAP_H_ */
