/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_CPU_MSTR_IF_CORE_HBW_REGS_H_
#define ASIC_REG_CPU_MSTR_IF_CORE_HBW_REGS_H_

/*
 *****************************************
 *   CPU_MSTR_IF_CORE_HBW
 *   (Prototype: MSTR_IF_HBW_CORE)
 *****************************************
 */

#define mmCPU_MSTR_IF_CORE_HBW_AXPROT_OVRD 0x4C3D00

#define mmCPU_MSTR_IF_CORE_HBW_RL_WR 0x4C3D04

#define mmCPU_MSTR_IF_CORE_HBW_RL_RD 0x4C3D08

#define mmCPU_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_PCI 0x4C3D0C

#define mmCPU_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_EXTMEM 0x4C3D10

#define mmCPU_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_SRAM 0x4C3D14

#define mmCPU_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_REST 0x4C3D18

#define mmCPU_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_TOTAL 0x4C3D1C

#define mmCPU_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_PCI 0x4C3D20

#define mmCPU_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_EXTMEM 0x4C3D24

#define mmCPU_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_SRAM 0x4C3D28

#define mmCPU_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_REST 0x4C3D2C

#define mmCPU_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_TOTAL 0x4C3D30

#define mmCPU_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_EN 0x4C3D34

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_EXTMEM_EN 0x4C3D38

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_PERM_SEL 0x4C3D3C

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_0 0x4C3D40

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_1 0x4C3D44

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_2 0x4C3D48

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_3 0x4C3D4C

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_4 0x4C3D50

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_5 0x4C3D54

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_6 0x4C3D58

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_7 0x4C3D5C

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_8 0x4C3D60

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_9 0x4C3D64

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_10 0x4C3D68

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_11 0x4C3D6C

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_12 0x4C3D70

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_13 0x4C3D74

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_14 0x4C3D78

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_15 0x4C3D7C

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_16 0x4C3D80

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_17 0x4C3D84

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_18 0x4C3D88

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_19 0x4C3D8C

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_20 0x4C3D90

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_21 0x4C3D94

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_22 0x4C3D98

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_23 0x4C3D9C

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_24 0x4C3DA0

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_25 0x4C3DA4

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_26 0x4C3DA8

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_27 0x4C3DAC

#define mmCPU_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_28 0x4C3DB0

#define mmCPU_MSTR_IF_CORE_HBW_CORE_MODE 0x4C3DB4

#define mmCPU_MSTR_IF_CORE_HBW_EXTMEM_ID_LOC 0x4C3DB8

#define mmCPU_MSTR_IF_CORE_HBW_CRDT_ARB_DBG 0x4C3DBC

#endif /* ASIC_REG_CPU_MSTR_IF_CORE_HBW_REGS_H_ */
