/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_HMMU0_SCRAMB_OUT_MASKS_H_
#define ASIC_REG_DCORE0_HMMU0_SCRAMB_OUT_MASKS_H_

/*
 *****************************************
 *   DCORE0_HMMU0_SCRAMB_OUT
 *   (Prototype: HMMU_OUT_SCRAMBLER)
 *****************************************
 */

/* DCORE0_HMMU0_SCRAMB_OUT_SCRAMBLER_CTRL */
#define DCORE0_HMMU0_SCRAMB_OUT_SCRAMBLER_CTRL_SCRAMBLER_SCRAM_EN_SHIFT 0
#define DCORE0_HMMU0_SCRAMB_OUT_SCRAMBLER_CTRL_SCRAMBLER_SCRAM_EN_MASK 0x1
#define DCORE0_HMMU0_SCRAMB_OUT_SCRAMBLER_CTRL_PERMUTATION_SELECT_SHIFT 1
#define DCORE0_HMMU0_SCRAMB_OUT_SCRAMBLER_CTRL_PERMUTATION_SELECT_MASK 0x1E

/* DCORE0_HMMU0_SCRAMB_OUT_SCRAMBLER_MATRIX */
#define DCORE0_HMMU0_SCRAMB_OUT_SCRAMBLER_MATRIX_SCRAMBLER_MATRIX_SHIFT 0
#define DCORE0_HMMU0_SCRAMB_OUT_SCRAMBLER_MATRIX_SCRAMBLER_MATRIX_MASK \
0x1FFFFFFF

/* DCORE0_HMMU0_SCRAMB_OUT_DDR_PARAMETERS */
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_PARAMETERS_DDR_SIZE_SHIFT 0
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_PARAMETERS_DDR_SIZE_MASK 0x3
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_PARAMETERS_ECC_TYPE_SHIFT 2
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_PARAMETERS_ECC_TYPE_MASK 0xC
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_PARAMETERS_PROTECTED_REGION_NUM_SHIFT 4
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_PARAMETERS_PROTECTED_REGION_NUM_MASK 0xF0
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_PARAMETERS_CORE_SEPARATION_EN_SHIFT 8
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_PARAMETERS_CORE_SEPARATION_EN_MASK 0x100
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_PARAMETERS_SINGLE_DDR_SHIFT 9
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_PARAMETERS_SINGLE_DDR_MASK 0x200
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_PARAMETERS_DDR_CH_LSB_BIT_LOCATION_SHIFT 10
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_PARAMETERS_DDR_CH_LSB_BIT_LOCATION_MASK \
0x1FC00

/* DCORE0_HMMU0_SCRAMB_OUT_FORCE_REMAP_EN */
#define DCORE0_HMMU0_SCRAMB_OUT_FORCE_REMAP_EN_ORDER_BITS_FORCE_EN_SHIFT 0
#define DCORE0_HMMU0_SCRAMB_OUT_FORCE_REMAP_EN_ORDER_BITS_FORCE_EN_MASK 0x1

/* DCORE0_HMMU0_SCRAMB_OUT_ORDER_BITS_FORCE_VALUES */
#define \
DCORE0_HMMU0_SCRAMB_OUT_ORDER_BITS_FORCE_VALUES_ODER_BITS_FORCE_VALUE_SHIFT \
0
#define \
DCORE0_HMMU0_SCRAMB_OUT_ORDER_BITS_FORCE_VALUES_ODER_BITS_FORCE_VALUE_MASK \
0x3F

/* DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_CONFIG */
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_CONFIG_CLOSE_MMU_CLOCK_GATE_EN_SHIFT \
0
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_CONFIG_CLOSE_MMU_CLOCK_GATE_EN_MASK \
0x1
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_CONFIG_CLOSE_HPC_CLOCK_GATE_EN_SHIFT \
1
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_CONFIG_CLOSE_HPC_CLOCK_GATE_EN_MASK \
0x2
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_CONFIG_MMU_CG_RESET_COUNTER_SHIFT 2
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_CONFIG_MMU_CG_RESET_COUNTER_MASK 0x4
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_CONFIG_HPC_CG_RESET_COUNTER_SHIFT 3
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_CONFIG_HPC_CG_RESET_COUNTER_MASK 0x8
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_CONFIG_SAMPLE_MMU_LATENCY_EN_SHIFT 4
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_CONFIG_SAMPLE_MMU_LATENCY_EN_MASK \
0x10
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_CONFIG_SAMPLE_HPC_LATENCY_EN_SHIFT 5
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_CONFIG_SAMPLE_HPC_LATENCY_EN_MASK \
0x20

/* DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_ACTIVE */
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_ACTIVE_MMU_CLOCK_ACTIVE_SHIFT 0
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_ACTIVE_MMU_CLOCK_ACTIVE_MASK 0x1
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_ACTIVE_HPC_CLOCK_ACTIVE_SHIFT 1
#define DCORE0_HMMU0_SCRAMB_OUT_CLOCK_GATE_ACTIVE_HPC_CLOCK_ACTIVE_MASK 0x2

/* DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDR_REMAP_LUT */
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDR_REMAP_LUT_REMAP_LUT_SHIFT 0
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDR_REMAP_LUT_REMAP_LUT_MASK 0xFF

/* DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDRESS_SHIFT_ALIGN */
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDRESS_SHIFT_ALIGN_WR_SHIFT_EN_SHIFT 0
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDRESS_SHIFT_ALIGN_WR_SHIFT_EN_MASK 0x1
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDRESS_SHIFT_ALIGN_WR_SHIFT_OFFSET_SHIFT 1
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDRESS_SHIFT_ALIGN_WR_SHIFT_OFFSET_MASK \
0x7E
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDRESS_SHIFT_ALIGN_WR_SHIFT_WIDTH_SHIFT 7
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDRESS_SHIFT_ALIGN_WR_SHIFT_WIDTH_MASK \
0x1F80
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDRESS_SHIFT_ALIGN_RD_SHIFT_EN_SHIFT 13
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDRESS_SHIFT_ALIGN_RD_SHIFT_EN_MASK 0x2000
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDRESS_SHIFT_ALIGN_RD_SHIFT_OFFSET_SHIFT 14
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDRESS_SHIFT_ALIGN_RD_SHIFT_OFFSET_MASK \
0xFC000
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDRESS_SHIFT_ALIGN_RD_SHIFT_WIDTH_SHIFT 20
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_ADDRESS_SHIFT_ALIGN_RD_SHIFT_WIDTH_MASK \
0x3F00000

/* DCORE0_HMMU0_SCRAMB_OUT_DDR_BIST_ENABLE */
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_BIST_ENABLE_DDR_BIST_ENABLE_SHIFT 0
#define DCORE0_HMMU0_SCRAMB_OUT_DDR_BIST_ENABLE_DDR_BIST_ENABLE_MASK 0xF

#endif /* ASIC_REG_DCORE0_HMMU0_SCRAMB_OUT_MASKS_H_ */
