/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_REGS_H_
#define ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B
 *   (Prototype: MME_TENSOR)
 *****************************************
 */

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_VALID_ELEMENTS_0 0x1C3130

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_VALID_ELEMENTS_1 0x1C3134

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_VALID_ELEMENTS_2 0x1C3138

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_VALID_ELEMENTS_3 0x1C313C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_VALID_ELEMENTS_4 0x1C3140

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_LOOP_STRIDE_0 0x1C3144

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_LOOP_STRIDE_1 0x1C3148

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_LOOP_STRIDE_2 0x1C314C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_LOOP_STRIDE_3 0x1C3150

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_LOOP_STRIDE_4 0x1C3154

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_ROI_SIZE_0 0x1C3158

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_ROI_SIZE_1 0x1C315C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_ROI_SIZE_2 0x1C3160

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_ROI_SIZE_3 0x1C3164

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_SPATIAL_STRIDES_0 0x1C3168

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_SPATIAL_STRIDES_1 0x1C316C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_SPATIAL_STRIDES_2 0x1C3170

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_SPATIAL_STRIDES_3 0x1C3174

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_START_OFFSET_0 0x1C3178

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_START_OFFSET_1 0x1C317C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_START_OFFSET_2 0x1C3180

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_START_OFFSET_3 0x1C3184

#endif /* ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_B_REGS_H_ */
