/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_REGS_H_
#define ASIC_REG_DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_CORE 0xA6900

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_E2E 0xA6904

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_HB_SEC 0xA6908

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_HB_PCIE 0xA690C

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_HB_DDR_QOS 0xA6910

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_HB_DDR_CPAGE 0xA6914

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_HB_REDUCTION 0xA6918

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_HB_RSVD 0xA691C

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_HB_OVRD_LO 0xA6920

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_HB_OVRD_HI 0xA6924

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_LB_COORD 0xA6930

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_LB_LOCK 0xA6934

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_LB_RSVD 0xA6938

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_LB_OVRD 0xA693C

#endif /* ASIC_REG_DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_L2C_REGS_H_ */
