/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_REGS_H_
#define ASIC_REG_DCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_CORE 0xB2C00

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_E2E 0xB2C04

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_HB_SEC 0xB2C08

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_HB_PCIE 0xB2C0C

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_HB_DDR_QOS 0xB2C10

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_HB_DDR_CPAGE 0xB2C14

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_HB_REDUCTION 0xB2C18

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_HB_RSVD 0xB2C1C

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_HB_OVRD_LO 0xB2C20

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_HB_OVRD_HI 0xB2C24

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_LB_COORD 0xB2C30

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_LB_LOCK 0xB2C34

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_LB_RSVD 0xB2C38

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_LB_OVRD 0xB2C3C

#endif /* ASIC_REG_DCORE0_VDEC3_BRDG_CTRL_AXUSER_DEC_REGS_H_ */
