/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_REGS_H_
#define ASIC_REG_DCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_CORE 0xB2800

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_E2E 0xB2804

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_HB_SEC 0xB2808

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_HB_PCIE 0xB280C

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_HB_DDR_QOS 0xB2810

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_HB_DDR_CPAGE 0xB2814

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_HB_REDUCTION 0xB2818

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_HB_RSVD 0xB281C

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_HB_OVRD_LO 0xB2820

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_HB_OVRD_HI 0xB2824

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_LB_COORD 0xB2830

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_LB_LOCK 0xB2834

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_LB_RSVD 0xB2838

#define mmDCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_LB_OVRD 0xB283C

#endif /* ASIC_REG_DCORE0_VDEC3_BRDG_CTRL_AXUSER_MSIX_VCD_REGS_H_ */
