/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_REGS_H_
#define ASIC_REG_DCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_REGS_H_

/*
 *****************************************
 *   DCORE0_KDMA_MSTR_IF_RR_PRVT_LBW
 *   (Prototype: RANGE_REG_LBW)
 *****************************************
 */

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_SHORT_0 0x10B600

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_SHORT_1 0x10B604

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_SHORT_2 0x10B608

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_SHORT_3 0x10B60C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_SHORT_4 0x10B610

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_SHORT_5 0x10B614

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_SHORT_6 0x10B618

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_SHORT_7 0x10B61C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_SHORT_8 0x10B620

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_SHORT_9 0x10B624

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_SHORT_10 0x10B628

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_SHORT_11 0x10B62C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_SHORT_12 0x10B630

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_SHORT_13 0x10B634

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_SHORT_0 0x10B638

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_SHORT_1 0x10B63C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_SHORT_2 0x10B640

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_SHORT_3 0x10B644

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_SHORT_4 0x10B648

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_SHORT_5 0x10B64C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_SHORT_6 0x10B650

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_SHORT_7 0x10B654

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_SHORT_8 0x10B658

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_SHORT_9 0x10B65C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_SHORT_10 0x10B660

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_SHORT_11 0x10B664

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_SHORT_12 0x10B668

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_SHORT_13 0x10B66C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_SHORT_0 0x10B670

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_SHORT_1 0x10B674

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_SHORT_2 0x10B678

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_SHORT_3 0x10B67C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_SHORT_4 0x10B680

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_SHORT_5 0x10B684

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_SHORT_6 0x10B688

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_SHORT_7 0x10B68C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_SHORT_8 0x10B690

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_SHORT_9 0x10B694

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_SHORT_10 0x10B698

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_SHORT_11 0x10B69C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_SHORT_12 0x10B6A0

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_SHORT_13 0x10B6A4

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_SHORT_0 0x10B6A8

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_SHORT_1 0x10B6AC

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_SHORT_2 0x10B6B0

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_SHORT_3 0x10B6B4

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_SHORT_4 0x10B6B8

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_SHORT_5 0x10B6BC

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_SHORT_6 0x10B6C0

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_SHORT_7 0x10B6C4

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_SHORT_8 0x10B6C8

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_SHORT_9 0x10B6CC

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_SHORT_10 0x10B6D0

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_SHORT_11 0x10B6D4

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_SHORT_12 0x10B6D8

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_SHORT_13 0x10B6DC

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_0 0x10B6E0

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_1 0x10B6E4

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_2 0x10B6E8

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MIN_3 0x10B6EC

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_0 0x10B6F0

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_1 0x10B6F4

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_2 0x10B6F8

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_RANGE_MAX_3 0x10B6FC

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_0 0x10B700

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_1 0x10B704

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_2 0x10B708

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MIN_3 0x10B70C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_0 0x10B710

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_1 0x10B714

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_2 0x10B718

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_RANGE_MAX_3 0x10B71C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_HIT_AW 0x10B720

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_HIT_AW 0x10B724

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_SEC_HIT_AR 0x10B728

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_PRIV_HIT_AR 0x10B72C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_AW_RAZWI 0x10B730

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_AR_RAZWI 0x10B734

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_AW_RAZWI_XY 0x10B738

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_AR_RAZWI_XY 0x10B73C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_AW_RAZWI_HAPPENED 0x10B740

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_AR_RAZWI_HAPPENED 0x10B744

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_RAZWI_ERR_RESP 0x10B748

#endif /* ASIC_REG_DCORE0_KDMA_MSTR_IF_RR_PRVT_LBW_REGS_H_ */
