/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_REGS_H_
#define ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A
 *   (Prototype: MME_TENSOR)
 *****************************************
 */

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_VALID_ELEMENTS_0 0x1C34D8

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_VALID_ELEMENTS_1 0x1C34DC

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_VALID_ELEMENTS_2 0x1C34E0

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_VALID_ELEMENTS_3 0x1C34E4

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_VALID_ELEMENTS_4 0x1C34E8

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_LOOP_STRIDE_0 0x1C34EC

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_LOOP_STRIDE_1 0x1C34F0

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_LOOP_STRIDE_2 0x1C34F4

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_LOOP_STRIDE_3 0x1C34F8

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_LOOP_STRIDE_4 0x1C34FC

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_ROI_SIZE_0 0x1C3500

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_ROI_SIZE_1 0x1C3504

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_ROI_SIZE_2 0x1C3508

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_ROI_SIZE_3 0x1C350C

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_SPATIAL_STRIDES_0 0x1C3510

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_SPATIAL_STRIDES_1 0x1C3514

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_SPATIAL_STRIDES_2 0x1C3518

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_SPATIAL_STRIDES_3 0x1C351C

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_START_OFFSET_0 0x1C3520

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_START_OFFSET_1 0x1C3524

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_START_OFFSET_2 0x1C3528

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_START_OFFSET_3 0x1C352C

#endif /* ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_A_REGS_H_ */
