/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_REGS_H_
#define ASIC_REG_DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_CORE 0xA6800

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_E2E 0xA6804

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_HB_SEC 0xA6808

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_HB_PCIE 0xA680C

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_HB_DDR_QOS 0xA6810

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_HB_DDR_CPAGE 0xA6814

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_HB_REDUCTION 0xA6818

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_HB_RSVD 0xA681C

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_HB_OVRD_LO 0xA6820

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_HB_OVRD_HI 0xA6824

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_LB_COORD 0xA6830

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_LB_LOCK 0xA6834

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_LB_RSVD 0xA6838

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_LB_OVRD 0xA683C

#endif /* ASIC_REG_DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_VCD_REGS_H_ */
