/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_REGS_H_
#define ASIC_REG_DCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_CORE 0xACC00

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_E2E 0xACC04

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_HB_SEC 0xACC08

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_HB_PCIE 0xACC0C

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_HB_DDR_QOS 0xACC10

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_HB_DDR_CPAGE 0xACC14

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_HB_REDUCTION 0xACC18

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_HB_RSVD 0xACC1C

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_HB_OVRD_LO 0xACC20

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_HB_OVRD_HI 0xACC24

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_LB_COORD 0xACC30

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_LB_LOCK 0xACC34

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_LB_RSVD 0xACC38

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_LB_OVRD 0xACC3C

#endif /* ASIC_REG_DCORE0_VDEC2_BRDG_CTRL_AXUSER_DEC_REGS_H_ */
