/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_REGS_H_
#define ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR
 *   (Prototype: MME_ADDRESS_DESCRIPTOR)
 *****************************************
 */

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_CIN_LOW 0x1C3088

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_CIN_HIGH 0x1C308C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_ACT_MD_LOW 0x1C3090

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_ACT_MD_HIGH 0x1C3094

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_LUT_LOW 0x1C3098

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_LUT_HIGH 0x1C309C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_COUT1_LOW 0x1C30A0

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_COUT1_HIGH 0x1C30A4

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_COUT0_LOW 0x1C30A8

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_COUT0_HIGH 0x1C30AC

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_A_LOW 0x1C30B0

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_A_HIGH 0x1C30B4

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_B_LOW 0x1C30B8

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_B_HIGH 0x1C30BC

#endif /* ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_BASE_ADDR_REGS_H_ */
