/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC2_BRDG_CTRL_REGS_H_
#define ASIC_REG_DCORE0_VDEC2_BRDG_CTRL_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC2_BRDG_CTRL
 *   (Prototype: VDEC_BRDG_CTRL)
 *****************************************
 */

#define mmDCORE0_VDEC2_BRDG_CTRL_FT_CH1_SEL 0xAC090

#define mmDCORE0_VDEC2_BRDG_CTRL_CGM_DISABLE 0xAC100

#define mmDCORE0_VDEC2_BRDG_CTRL_IDLE_MASK 0xAC104

#define mmDCORE0_VDEC2_BRDG_CTRL_APB_CGM_CNT 0xAC108

#define mmDCORE0_VDEC2_BRDG_CTRL_APB_ARB_WDOG_CNT 0xAC10C

#define mmDCORE0_VDEC2_BRDG_CTRL_GRACEFUL 0xAC110

#define mmDCORE0_VDEC2_BRDG_CTRL_CAUSE_INTR 0xAC120

#define mmDCORE0_VDEC2_BRDG_CTRL_CAUSE_INTR_MASK 0xAC130

#define mmDCORE0_VDEC2_BRDG_CTRL_VCD_GIC_INTR_MASK 0xAC160

#define mmDCORE0_VDEC2_BRDG_CTRL_L2C_GIC_INTR_MASK 0xAC170

#define mmDCORE0_VDEC2_BRDG_CTRL_NRM_GIC_INTR_MASK 0xAC180

#define mmDCORE0_VDEC2_BRDG_CTRL_ABNRM_GIC_INTR_MASK 0xAC190

#define mmDCORE0_VDEC2_BRDG_CTRL_DEC_HBW_AWPROT 0xAC1A0

#define mmDCORE0_VDEC2_BRDG_CTRL_DEC_HBW_ARPROT 0xAC1A4

#define mmDCORE0_VDEC2_BRDG_CTRL_DEC_LBW_AWPROT 0xAC1B0

#define mmDCORE0_VDEC2_BRDG_CTRL_DEC_LBW_ARPROT 0xAC1B4

#define mmDCORE0_VDEC2_BRDG_CTRL_ARC_MSG_MASK 0xAC200

#define mmDCORE0_VDEC2_BRDG_CTRL_ARC_START_LBW_AWPROT 0xAC210

#define mmDCORE0_VDEC2_BRDG_CTRL_ARC_START_LBW_AWADDR 0xAC220

#define mmDCORE0_VDEC2_BRDG_CTRL_ARC_START_LBW_WDATA 0xAC230

#define mmDCORE0_VDEC2_BRDG_CTRL_ARC_FINISH_LBW_AWPROT 0xAC240

#define mmDCORE0_VDEC2_BRDG_CTRL_ARC_FINISH_LBW_AWADDR 0xAC250

#define mmDCORE0_VDEC2_BRDG_CTRL_ARC_FINISH_LBW_WDATA 0xAC260

#define mmDCORE0_VDEC2_BRDG_CTRL_HWEVENT_TRACE_SEL 0xAC270

#define mmDCORE0_VDEC2_BRDG_CTRL_HWEVENT_TRACE_ADDR 0xAC280

#define mmDCORE0_VDEC2_BRDG_CTRL_DEC_FREE_RUN_CNT_L 0xAC290

#define mmDCORE0_VDEC2_BRDG_CTRL_DEC_FREE_RUN_CNT_H 0xAC294

#define mmDCORE0_VDEC2_BRDG_CTRL_DEC_FREE_RUN_SET_VALUE_L 0xAC2A0

#define mmDCORE0_VDEC2_BRDG_CTRL_DEC_FREE_RUN_SET_VALUE_H 0xAC2A4

#define mmDCORE0_VDEC2_BRDG_CTRL_DEC_BUSY_CNT_L 0xAC2B0

#define mmDCORE0_VDEC2_BRDG_CTRL_DEC_BUSY_CNT_H 0xAC2B4

#define mmDCORE0_VDEC2_BRDG_CTRL_DEC_BUSY_SET_VALUE_L 0xAC2C0

#define mmDCORE0_VDEC2_BRDG_CTRL_DEC_BUSY_SET_VALUE_H 0xAC2C4

#define mmDCORE0_VDEC2_BRDG_CTRL_STAT_CNTR_EN 0xAC2D0

#define mmDCORE0_VDEC2_BRDG_CTRL_VCD_INTR_MASK 0xAC300

#define mmDCORE0_VDEC2_BRDG_CTRL_VCD_MSIX_FLOW_MASK 0xAC310

#define mmDCORE0_VDEC2_BRDG_CTRL_VCD_WAIT_CNTR 0xAC320

#define mmDCORE0_VDEC2_BRDG_CTRL_VCD_MSIX_WAIT_CNTR 0xAC330

#define mmDCORE0_VDEC2_BRDG_CTRL_STAT_VCD_WAIT_CNTR 0xAC334

#define mmDCORE0_VDEC2_BRDG_CTRL_STAT_VCD_MSIX_WAIT_CNTR 0xAC338

#define mmDCORE0_VDEC2_BRDG_CTRL_VCD_SWREG1_ADDR 0xAC340

#define mmDCORE0_VDEC2_BRDG_CTRL_VCD_APB_WR_ADDR 0xAC350

#define mmDCORE0_VDEC2_BRDG_CTRL_VCD_APB_WR_DATA 0xAC360

#define mmDCORE0_VDEC2_BRDG_CTRL_VCD_CPLQ_HBW_AWPROT 0xAC380

#define mmDCORE0_VDEC2_BRDG_CTRL_VCD_CPLQ_HBW_AWADDR_L 0xAC390

#define mmDCORE0_VDEC2_BRDG_CTRL_VCD_CPLQ_HBW_AWADDR_H 0xAC394

#define mmDCORE0_VDEC2_BRDG_CTRL_VCD_MSIX_LBW_AWPROT 0xAC3C0

#define mmDCORE0_VDEC2_BRDG_CTRL_VCD_MSIX_LBW_AWADDR 0xAC3D0

#define mmDCORE0_VDEC2_BRDG_CTRL_VCD_MSIX_LBW_WDATA 0xAC3E0

#define mmDCORE0_VDEC2_BRDG_CTRL_L2C_INTR_MASK 0xAC400

#define mmDCORE0_VDEC2_BRDG_CTRL_L2C_MSIX_FLOW_MASK 0xAC410

#define mmDCORE0_VDEC2_BRDG_CTRL_L2C_WAIT_CNTR 0xAC420

#define mmDCORE0_VDEC2_BRDG_CTRL_L2C_MSIX_WAIT_CNTR 0xAC430

#define mmDCORE0_VDEC2_BRDG_CTRL_STAT_L2C_WAIT_CNTR 0xAC434

#define mmDCORE0_VDEC2_BRDG_CTRL_STAT_L2C_MSIX_WAIT_CNTR 0xAC438

#define mmDCORE0_VDEC2_BRDG_CTRL_L2C_SWREG1_ADDR 0xAC440

#define mmDCORE0_VDEC2_BRDG_CTRL_L2C_APB_WR_ADDR 0xAC450

#define mmDCORE0_VDEC2_BRDG_CTRL_L2C_APB_WR_DATA 0xAC460

#define mmDCORE0_VDEC2_BRDG_CTRL_L2C_CPLQ_HBW_AWPROT 0xAC480

#define mmDCORE0_VDEC2_BRDG_CTRL_L2C_CPLQ_HBW_AWADDR_L 0xAC490

#define mmDCORE0_VDEC2_BRDG_CTRL_L2C_CPLQ_HBW_AWADDR_H 0xAC494

#define mmDCORE0_VDEC2_BRDG_CTRL_L2C_MSIX_LBW_AWPROT 0xAC4C0

#define mmDCORE0_VDEC2_BRDG_CTRL_L2C_MSIX_LBW_AWADDR 0xAC4D0

#define mmDCORE0_VDEC2_BRDG_CTRL_L2C_MSIX_LBW_WDATA 0xAC4E0

#define mmDCORE0_VDEC2_BRDG_CTRL_NRM_INTR_MASK 0xAC500

#define mmDCORE0_VDEC2_BRDG_CTRL_NRM_MSIX_FLOW_MASK 0xAC510

#define mmDCORE0_VDEC2_BRDG_CTRL_NRM_WAIT_CNTR 0xAC520

#define mmDCORE0_VDEC2_BRDG_CTRL_NRM_MSIX_WAIT_CNTR 0xAC530

#define mmDCORE0_VDEC2_BRDG_CTRL_STAT_NRM_WAIT_CNTR 0xAC534

#define mmDCORE0_VDEC2_BRDG_CTRL_STAT_NRM_MSIX_WAIT_CNTR 0xAC538

#define mmDCORE0_VDEC2_BRDG_CTRL_NRM_SWREG1_ADDR 0xAC540

#define mmDCORE0_VDEC2_BRDG_CTRL_NRM_APB_WR_ADDR 0xAC550

#define mmDCORE0_VDEC2_BRDG_CTRL_NRM_APB_WR_DATA 0xAC560

#define mmDCORE0_VDEC2_BRDG_CTRL_NRM_CPLQ_HBW_AWPROT 0xAC580

#define mmDCORE0_VDEC2_BRDG_CTRL_NRM_CPLQ_HBW_AWADDR_L 0xAC590

#define mmDCORE0_VDEC2_BRDG_CTRL_NRM_CPLQ_HBW_AWADDR_H 0xAC594

#define mmDCORE0_VDEC2_BRDG_CTRL_NRM_MSIX_LBW_AWPROT 0xAC5C0

#define mmDCORE0_VDEC2_BRDG_CTRL_NRM_MSIX_LBW_AWADDR 0xAC5D0

#define mmDCORE0_VDEC2_BRDG_CTRL_NRM_MSIX_LBW_WDATA 0xAC5E0

#define mmDCORE0_VDEC2_BRDG_CTRL_ABNRM_INTR_MASK 0xAC600

#define mmDCORE0_VDEC2_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK 0xAC610

#define mmDCORE0_VDEC2_BRDG_CTRL_ABNRM_WAIT_CNTR 0xAC620

#define mmDCORE0_VDEC2_BRDG_CTRL_ABNRM_MSIX_WAIT_CNTR 0xAC630

#define mmDCORE0_VDEC2_BRDG_CTRL_STAT_ABNRM_WAIT_CNTR 0xAC634

#define mmDCORE0_VDEC2_BRDG_CTRL_STAT_ABNRM_MSIX_WAIT_CNTR 0xAC638

#define mmDCORE0_VDEC2_BRDG_CTRL_ABNRM_SWREG1_ADDR 0xAC640

#define mmDCORE0_VDEC2_BRDG_CTRL_ABNRM_APB_WR_ADDR 0xAC650

#define mmDCORE0_VDEC2_BRDG_CTRL_ABNRM_APB_WR_DATA 0xAC660

#define mmDCORE0_VDEC2_BRDG_CTRL_ABNRM_CPLQ_HBW_AWPROT 0xAC680

#define mmDCORE0_VDEC2_BRDG_CTRL_ABNRM_CPLQ_HBW_AWADDR_L 0xAC690

#define mmDCORE0_VDEC2_BRDG_CTRL_ABNRM_CPLQ_HBW_AWADDR_H 0xAC694

#define mmDCORE0_VDEC2_BRDG_CTRL_ABNRM_MSIX_LBW_AWPROT 0xAC6C0

#define mmDCORE0_VDEC2_BRDG_CTRL_ABNRM_MSIX_LBW_AWADDR 0xAC6D0

#define mmDCORE0_VDEC2_BRDG_CTRL_ABNRM_MSIX_LBW_WDATA 0xAC6E0

#endif /* ASIC_REG_DCORE0_VDEC2_BRDG_CTRL_REGS_H_ */
