/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_REGS_H_
#define ASIC_REG_DCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_REGS_H_

/*
 *****************************************
 *   DCORE0_KDMA_MSTR_IF_RR_PRVT_HBW
 *   (Prototype: RANGE_REG_HBW)
 *****************************************
 */

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MIN_SHORT_0 0x10B200

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MIN_SHORT_1 0x10B204

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MIN_SHORT_2 0x10B208

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MIN_SHORT_3 0x10B20C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MIN_SHORT_4 0x10B210

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MIN_SHORT_5 0x10B214

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MAX_SHORT_0 0x10B218

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MAX_SHORT_1 0x10B21C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MAX_SHORT_2 0x10B220

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MAX_SHORT_3 0x10B224

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MAX_SHORT_4 0x10B228

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MAX_SHORT_5 0x10B22C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MIN_SHORT_0 0x10B230

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MIN_SHORT_1 0x10B234

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MIN_SHORT_2 0x10B238

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MIN_SHORT_3 0x10B23C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MIN_SHORT_4 0x10B240

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MIN_SHORT_5 0x10B244

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MAX_SHORT_0 0x10B248

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MAX_SHORT_1 0x10B24C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MAX_SHORT_2 0x10B250

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MAX_SHORT_3 0x10B254

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MAX_SHORT_4 0x10B258

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MAX_SHORT_5 0x10B25C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MIN_HI_0 0x10B260

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MIN_HI_1 0x10B264

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MIN_HI_2 0x10B268

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MIN_HI_3 0x10B26C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MIN_LO_0 0x10B270

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MIN_LO_1 0x10B274

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MIN_LO_2 0x10B278

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MIN_LO_3 0x10B27C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MAX_HI_0 0x10B280

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MAX_HI_1 0x10B284

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MAX_HI_2 0x10B288

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MAX_HI_3 0x10B28C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MAX_LO_0 0x10B290

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MAX_LO_1 0x10B294

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MAX_LO_2 0x10B298

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_RANGE_MAX_LO_3 0x10B29C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MIN_HI_0 0x10B2A0

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MIN_HI_1 0x10B2A4

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MIN_HI_2 0x10B2A8

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MIN_HI_3 0x10B2AC

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MIN_LO_0 0x10B2B0

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MIN_LO_1 0x10B2B4

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MIN_LO_2 0x10B2B8

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MIN_LO_3 0x10B2BC

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MAX_HI_0 0x10B2C0

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MAX_HI_1 0x10B2C4

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MAX_HI_2 0x10B2C8

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MAX_HI_3 0x10B2CC

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MAX_LO_0 0x10B2D0

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MAX_LO_1 0x10B2D4

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MAX_LO_2 0x10B2D8

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_RANGE_MAX_LO_3 0x10B2DC

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_PCIE_EN 0x10B2E0

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_PCIE_EN 0x10B2E4

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_HIT_AW 0x10B2E8

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_HIT_AW 0x10B2EC

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_SEC_HIT_AR 0x10B2F0

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_PRIV_HIT_AR 0x10B2F4

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_AW_RAZWI_HI 0x10B2F8

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_AW_RAZWI_LO 0x10B2FC

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_AR_RAZWI_HI 0x10B300

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_AR_RAZWI_LO 0x10B304

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_AW_RAZWI_XY 0x10B308

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_AR_RAZWI_XY 0x10B30C

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_AW_RAZWI_HAPPENED 0x10B310

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_AR_RAZWI_HAPPENED 0x10B314

#define mmDCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_RAZWI_ERR_RESP 0x10B318

#endif /* ASIC_REG_DCORE0_KDMA_MSTR_IF_RR_PRVT_HBW_REGS_H_ */
