/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_REGS_H_
#define ASIC_REG_DCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_REGS_H_

/*
 *****************************************
 *   DCORE0_VSI_WRAP_MSTR_IF_CORE_HBW
 *   (Prototype: MSTR_IF_HBW_CORE)
 *****************************************
 */

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_AXPROT_OVRD 0xBED00

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_RL_WR 0xBED04

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_RL_RD 0xBED08

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_PCI 0xBED0C

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_EXTMEM 0xBED10

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_SRAM 0xBED14

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_REST 0xBED18

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_TOTAL 0xBED1C

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_PCI 0xBED20

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_EXTMEM 0xBED24

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_SRAM 0xBED28

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_REST 0xBED2C

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_TOTAL 0xBED30

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_EN 0xBED34

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_EXTMEM_EN 0xBED38

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_PERM_SEL 0xBED3C

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_0 0xBED40

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_1 0xBED44

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_2 0xBED48

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_3 0xBED4C

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_4 0xBED50

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_5 0xBED54

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_6 0xBED58

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_7 0xBED5C

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_8 0xBED60

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_9 0xBED64

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_10 0xBED68

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_11 0xBED6C

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_12 0xBED70

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_13 0xBED74

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_14 0xBED78

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_15 0xBED7C

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_16 0xBED80

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_17 0xBED84

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_18 0xBED88

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_19 0xBED8C

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_20 0xBED90

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_21 0xBED94

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_22 0xBED98

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_23 0xBED9C

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_24 0xBEDA0

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_25 0xBEDA4

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_26 0xBEDA8

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_27 0xBEDAC

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_28 0xBEDB0

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_CORE_MODE 0xBEDB4

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_EXTMEM_ID_LOC 0xBEDB8

#define mmDCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_CRDT_ARB_DBG 0xBEDBC

#endif /* ASIC_REG_DCORE0_VSI_WRAP_MSTR_IF_CORE_HBW_REGS_H_ */
