/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_REGS_H_
#define ASIC_REG_DCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_SBTEB_MSTR_IF_CORE_HBW
 *   (Prototype: MSTR_IF_HBW_CORE)
 *****************************************
 */

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_AXPROT_OVRD 0x1F1D00

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_RL_WR 0x1F1D04

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_RL_RD 0x1F1D08

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_PCI 0x1F1D0C

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_EXTMEM 0x1F1D10

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_SRAM 0x1F1D14

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_REST 0x1F1D18

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_TOTAL 0x1F1D1C

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_PCI 0x1F1D20

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_EXTMEM 0x1F1D24

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_SRAM 0x1F1D28

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_REST 0x1F1D2C

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_TOTAL 0x1F1D30

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_EN 0x1F1D34

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_EXTMEM_EN 0x1F1D38

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_PERM_SEL 0x1F1D3C

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_0 0x1F1D40

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_1 0x1F1D44

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_2 0x1F1D48

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_3 0x1F1D4C

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_4 0x1F1D50

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_5 0x1F1D54

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_6 0x1F1D58

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_7 0x1F1D5C

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_8 0x1F1D60

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_9 0x1F1D64

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_10 0x1F1D68

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_11 0x1F1D6C

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_12 0x1F1D70

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_13 0x1F1D74

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_14 0x1F1D78

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_15 0x1F1D7C

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_16 0x1F1D80

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_17 0x1F1D84

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_18 0x1F1D88

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_19 0x1F1D8C

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_20 0x1F1D90

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_21 0x1F1D94

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_22 0x1F1D98

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_23 0x1F1D9C

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_24 0x1F1DA0

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_25 0x1F1DA4

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_26 0x1F1DA8

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_27 0x1F1DAC

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_28 0x1F1DB0

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_CORE_MODE 0x1F1DB4

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_EXTMEM_ID_LOC 0x1F1DB8

#define mmDCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_CRDT_ARB_DBG 0x1F1DBC

#endif /* ASIC_REG_DCORE0_MME_SBTEB_MSTR_IF_CORE_HBW_REGS_H_ */
