/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_REGS_H_
#define ASIC_REG_DCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_CORE 0xA0C00

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_E2E 0xA0C04

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_HB_SEC 0xA0C08

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_HB_PCIE 0xA0C0C

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_HB_DDR_QOS 0xA0C10

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_HB_DDR_CPAGE 0xA0C14

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_HB_REDUCTION 0xA0C18

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_HB_RSVD 0xA0C1C

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_HB_OVRD_LO 0xA0C20

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_HB_OVRD_HI 0xA0C24

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_LB_COORD 0xA0C30

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_LB_LOCK 0xA0C34

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_LB_RSVD 0xA0C38

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_LB_OVRD 0xA0C3C

#endif /* ASIC_REG_DCORE0_VDEC0_BRDG_CTRL_AXUSER_DEC_REGS_H_ */
