/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_TPC2_QM_AXUSER_NONSECURED_REGS_H_
#define ASIC_REG_DCORE0_TPC2_QM_AXUSER_NONSECURED_REGS_H_

/*
 *****************************************
 *   DCORE0_TPC2_QM_AXUSER_NONSECURED
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_TPC2_QM_AXUSER_NONSECURED_CORE 0x20B40

#define mmDCORE0_TPC2_QM_AXUSER_NONSECURED_E2E 0x20B44

#define mmDCORE0_TPC2_QM_AXUSER_NONSECURED_HB_SEC 0x20B48

#define mmDCORE0_TPC2_QM_AXUSER_NONSECURED_HB_PCIE 0x20B4C

#define mmDCORE0_TPC2_QM_AXUSER_NONSECURED_HB_DDR_QOS 0x20B50

#define mmDCORE0_TPC2_QM_AXUSER_NONSECURED_HB_DDR_CPAGE 0x20B54

#define mmDCORE0_TPC2_QM_AXUSER_NONSECURED_HB_REDUCTION 0x20B58

#define mmDCORE0_TPC2_QM_AXUSER_NONSECURED_HB_RSVD 0x20B5C

#define mmDCORE0_TPC2_QM_AXUSER_NONSECURED_HB_OVRD_LO 0x20B60

#define mmDCORE0_TPC2_QM_AXUSER_NONSECURED_HB_OVRD_HI 0x20B64

#define mmDCORE0_TPC2_QM_AXUSER_NONSECURED_LB_COORD 0x20B70

#define mmDCORE0_TPC2_QM_AXUSER_NONSECURED_LB_LOCK 0x20B74

#define mmDCORE0_TPC2_QM_AXUSER_NONSECURED_LB_RSVD 0x20B78

#define mmDCORE0_TPC2_QM_AXUSER_NONSECURED_LB_OVRD 0x20B7C

#endif /* ASIC_REG_DCORE0_TPC2_QM_AXUSER_NONSECURED_REGS_H_ */
