/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_REGS_H_
#define ASIC_REG_DCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR
 *   (Prototype: MME_ADDRESS_DESCRIPTOR)
 *****************************************
 */

#define mmDCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_CIN_LOW 0x1C2988

#define mmDCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_CIN_HIGH 0x1C298C

#define mmDCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_ACT_MD_LOW 0x1C2990

#define mmDCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_ACT_MD_HIGH 0x1C2994

#define mmDCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_LUT_LOW 0x1C2998

#define mmDCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_LUT_HIGH 0x1C299C

#define mmDCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_COUT1_LOW 0x1C29A0

#define mmDCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_COUT1_HIGH 0x1C29A4

#define mmDCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_COUT0_LOW 0x1C29A8

#define mmDCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_COUT0_HIGH 0x1C29AC

#define mmDCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_A_LOW 0x1C29B0

#define mmDCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_A_HIGH 0x1C29B4

#define mmDCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_B_LOW 0x1C29B8

#define mmDCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_B_HIGH 0x1C29BC

#endif /* ASIC_REG_DCORE0_MME_CTRL_LO_SHADOW_1_BASE_ADDR_REGS_H_ */
