/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_KDMA_MSTR_IF_CORE_HBW_REGS_H_
#define ASIC_REG_DCORE0_KDMA_MSTR_IF_CORE_HBW_REGS_H_

/*
 *****************************************
 *   DCORE0_KDMA_MSTR_IF_CORE_HBW
 *   (Prototype: MSTR_IF_HBW_CORE)
 *****************************************
 */

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_AXPROT_OVRD 0x10BD00

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_RL_WR 0x10BD04

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_RL_RD 0x10BD08

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_PCI 0x10BD0C

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_EXTMEM 0x10BD10

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_SRAM 0x10BD14

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_REST 0x10BD18

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_TOTAL 0x10BD1C

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_PCI 0x10BD20

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_EXTMEM 0x10BD24

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_SRAM 0x10BD28

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_REST 0x10BD2C

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_TOTAL 0x10BD30

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_EN 0x10BD34

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_EXTMEM_EN 0x10BD38

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_PERM_SEL 0x10BD3C

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_0 0x10BD40

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_1 0x10BD44

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_2 0x10BD48

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_3 0x10BD4C

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_4 0x10BD50

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_5 0x10BD54

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_6 0x10BD58

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_7 0x10BD5C

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_8 0x10BD60

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_9 0x10BD64

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_10 0x10BD68

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_11 0x10BD6C

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_12 0x10BD70

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_13 0x10BD74

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_14 0x10BD78

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_15 0x10BD7C

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_16 0x10BD80

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_17 0x10BD84

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_18 0x10BD88

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_19 0x10BD8C

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_20 0x10BD90

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_21 0x10BD94

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_22 0x10BD98

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_23 0x10BD9C

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_24 0x10BDA0

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_25 0x10BDA4

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_26 0x10BDA8

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_27 0x10BDAC

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_28 0x10BDB0

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_CORE_MODE 0x10BDB4

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_EXTMEM_ID_LOC 0x10BDB8

#define mmDCORE0_KDMA_MSTR_IF_CORE_HBW_CRDT_ARB_DBG 0x10BDBC

#endif /* ASIC_REG_DCORE0_KDMA_MSTR_IF_CORE_HBW_REGS_H_ */
