/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_REGS_H_
#define ASIC_REG_DCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN
 *   (Prototype: MME_TENSOR)
 *****************************************
 */

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_VALID_ELEMENTS_0 0x1C2508

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_VALID_ELEMENTS_1 0x1C250C

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_VALID_ELEMENTS_2 0x1C2510

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_VALID_ELEMENTS_3 0x1C2514

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_VALID_ELEMENTS_4 0x1C2518

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_LOOP_STRIDE_0 0x1C251C

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_LOOP_STRIDE_1 0x1C2520

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_LOOP_STRIDE_2 0x1C2524

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_LOOP_STRIDE_3 0x1C2528

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_LOOP_STRIDE_4 0x1C252C

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_ROI_SIZE_0 0x1C2530

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_ROI_SIZE_1 0x1C2534

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_ROI_SIZE_2 0x1C2538

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_ROI_SIZE_3 0x1C253C

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_SPATIAL_STRIDES_0 0x1C2540

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_SPATIAL_STRIDES_1 0x1C2544

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_SPATIAL_STRIDES_2 0x1C2548

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_SPATIAL_STRIDES_3 0x1C254C

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_START_OFFSET_0 0x1C2550

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_START_OFFSET_1 0x1C2554

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_START_OFFSET_2 0x1C2558

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_START_OFFSET_3 0x1C255C

#endif /* ASIC_REG_DCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_CIN_REGS_H_ */
