/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_TPC1_QM_AXUSER_NONSECURED_REGS_H_
#define ASIC_REG_DCORE0_TPC1_QM_AXUSER_NONSECURED_REGS_H_

/*
 *****************************************
 *   DCORE0_TPC1_QM_AXUSER_NONSECURED
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_TPC1_QM_AXUSER_NONSECURED_CORE 0x10B40

#define mmDCORE0_TPC1_QM_AXUSER_NONSECURED_E2E 0x10B44

#define mmDCORE0_TPC1_QM_AXUSER_NONSECURED_HB_SEC 0x10B48

#define mmDCORE0_TPC1_QM_AXUSER_NONSECURED_HB_PCIE 0x10B4C

#define mmDCORE0_TPC1_QM_AXUSER_NONSECURED_HB_DDR_QOS 0x10B50

#define mmDCORE0_TPC1_QM_AXUSER_NONSECURED_HB_DDR_CPAGE 0x10B54

#define mmDCORE0_TPC1_QM_AXUSER_NONSECURED_HB_REDUCTION 0x10B58

#define mmDCORE0_TPC1_QM_AXUSER_NONSECURED_HB_RSVD 0x10B5C

#define mmDCORE0_TPC1_QM_AXUSER_NONSECURED_HB_OVRD_LO 0x10B60

#define mmDCORE0_TPC1_QM_AXUSER_NONSECURED_HB_OVRD_HI 0x10B64

#define mmDCORE0_TPC1_QM_AXUSER_NONSECURED_LB_COORD 0x10B70

#define mmDCORE0_TPC1_QM_AXUSER_NONSECURED_LB_LOCK 0x10B74

#define mmDCORE0_TPC1_QM_AXUSER_NONSECURED_LB_RSVD 0x10B78

#define mmDCORE0_TPC1_QM_AXUSER_NONSECURED_LB_OVRD 0x10B7C

#endif /* ASIC_REG_DCORE0_TPC1_QM_AXUSER_NONSECURED_REGS_H_ */
