/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_REGS_H_
#define ASIC_REG_DCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_CORE 0xB8900

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_E2E 0xB8904

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_HB_SEC 0xB8908

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_HB_PCIE 0xB890C

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_HB_DDR_QOS 0xB8910

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_HB_DDR_CPAGE 0xB8914

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_HB_REDUCTION 0xB8918

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_HB_RSVD 0xB891C

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_HB_OVRD_LO 0xB8920

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_HB_OVRD_HI 0xB8924

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_LB_COORD 0xB8930

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_LB_LOCK 0xB8934

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_LB_RSVD 0xB8938

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_LB_OVRD 0xB893C

#endif /* ASIC_REG_DCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_L2C_REGS_H_ */
