/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_DDMA_QM_AXUSER_NONSECURED_REGS_H_
#define ASIC_REG_DCORE0_DDMA_QM_AXUSER_NONSECURED_REGS_H_

/*
 *****************************************
 *   DCORE0_DDMA_QM_AXUSER_NONSECURED
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_DDMA_QM_AXUSER_NONSECURED_CORE 0xC0B40

#define mmDCORE0_DDMA_QM_AXUSER_NONSECURED_E2E 0xC0B44

#define mmDCORE0_DDMA_QM_AXUSER_NONSECURED_HB_SEC 0xC0B48

#define mmDCORE0_DDMA_QM_AXUSER_NONSECURED_HB_PCIE 0xC0B4C

#define mmDCORE0_DDMA_QM_AXUSER_NONSECURED_HB_DDR_QOS 0xC0B50

#define mmDCORE0_DDMA_QM_AXUSER_NONSECURED_HB_DDR_CPAGE 0xC0B54

#define mmDCORE0_DDMA_QM_AXUSER_NONSECURED_HB_REDUCTION 0xC0B58

#define mmDCORE0_DDMA_QM_AXUSER_NONSECURED_HB_RSVD 0xC0B5C

#define mmDCORE0_DDMA_QM_AXUSER_NONSECURED_HB_OVRD_LO 0xC0B60

#define mmDCORE0_DDMA_QM_AXUSER_NONSECURED_HB_OVRD_HI 0xC0B64

#define mmDCORE0_DDMA_QM_AXUSER_NONSECURED_LB_COORD 0xC0B70

#define mmDCORE0_DDMA_QM_AXUSER_NONSECURED_LB_LOCK 0xC0B74

#define mmDCORE0_DDMA_QM_AXUSER_NONSECURED_LB_RSVD 0xC0B78

#define mmDCORE0_DDMA_QM_AXUSER_NONSECURED_LB_OVRD 0xC0B7C

#endif /* ASIC_REG_DCORE0_DDMA_QM_AXUSER_NONSECURED_REGS_H_ */
