/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_SBTEB_MSTR_IF_AXUSER_REGS_H_
#define ASIC_REG_DCORE0_MME_SBTEB_MSTR_IF_AXUSER_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_SBTEB_MSTR_IF_AXUSER
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_MME_SBTEB_MSTR_IF_AXUSER_CORE 0x1F1A00

#define mmDCORE0_MME_SBTEB_MSTR_IF_AXUSER_E2E 0x1F1A04

#define mmDCORE0_MME_SBTEB_MSTR_IF_AXUSER_HB_SEC 0x1F1A08

#define mmDCORE0_MME_SBTEB_MSTR_IF_AXUSER_HB_PCIE 0x1F1A0C

#define mmDCORE0_MME_SBTEB_MSTR_IF_AXUSER_HB_DDR_QOS 0x1F1A10

#define mmDCORE0_MME_SBTEB_MSTR_IF_AXUSER_HB_DDR_CPAGE 0x1F1A14

#define mmDCORE0_MME_SBTEB_MSTR_IF_AXUSER_HB_REDUCTION 0x1F1A18

#define mmDCORE0_MME_SBTEB_MSTR_IF_AXUSER_HB_RSVD 0x1F1A1C

#define mmDCORE0_MME_SBTEB_MSTR_IF_AXUSER_HB_OVRD_LO 0x1F1A20

#define mmDCORE0_MME_SBTEB_MSTR_IF_AXUSER_HB_OVRD_HI 0x1F1A24

#define mmDCORE0_MME_SBTEB_MSTR_IF_AXUSER_LB_COORD 0x1F1A30

#define mmDCORE0_MME_SBTEB_MSTR_IF_AXUSER_LB_LOCK 0x1F1A34

#define mmDCORE0_MME_SBTEB_MSTR_IF_AXUSER_LB_RSVD 0x1F1A38

#define mmDCORE0_MME_SBTEB_MSTR_IF_AXUSER_LB_OVRD 0x1F1A3C

#endif /* ASIC_REG_DCORE0_MME_SBTEB_MSTR_IF_AXUSER_REGS_H_ */
