/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VSI_WRAP_REGS_H_
#define ASIC_REG_DCORE0_VSI_WRAP_REGS_H_

/*
 *****************************************
 *   DCORE0_VSI_WRAP
 *   (Prototype: VSI_WRAP)
 *****************************************
 */

#define mmDCORE0_VSI_WRAP_DEC_BIN_MASK 0xBF000

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_INT0 0xBF004

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_INT1 0xBF008

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_INT2 0xBF00C

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_CFG0 0xBF024

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_CFG1 0xBF028

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_CFG2 0xBF02C

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER0_OVRD_WR_EN 0xBF034

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER1_OVRD_WR_EN 0xBF038

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER2_OVRD_WR_EN 0xBF03C

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER0_OVRD_WR 0xBF044

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER1_OVRD_WR 0xBF048

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER2_OVRD_WR 0xBF04C

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER0_OVRD_RD_EN 0xBF054

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER1_OVRD_RD_EN 0xBF058

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER2_OVRD_RD_EN 0xBF05C

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER0_OVRD_RD 0xBF064

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER1_OVRD_RD 0xBF068

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER2_OVRD_RD 0xBF06C

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER0_OVRD_MSB_WR 0xBF074

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER1_OVRD_MSB_WR 0xBF078

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER2_OVRD_MSB_WR 0xBF07C

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER0_OVRD_MSB_RD 0xBF084

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER1_OVRD_MSB_RD 0xBF088

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_USER2_OVRD_MSB_RD 0xBF08C

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_PROT_CFG0 0xBF094

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_PROT_CFG1 0xBF098

#define mmDCORE0_VSI_WRAP_AXI_SPLIT_PROT_CFG2 0xBF09C

#define mmDCORE0_VSI_WRAP_WR_ARB_ALLOC 0xBF100

#define mmDCORE0_VSI_WRAP_RD_ARB_ALLOC 0xBF104

#define mmDCORE0_VSI_WRAP_HWEVENT_MASK 0xBF108

#define mmDCORE0_VSI_WRAP_DEC_ID_0 0xBF10C

#define mmDCORE0_VSI_WRAP_DEC_ID_1 0xBF110

#define mmDCORE0_VSI_WRAP_DEC_ID_2 0xBF114

#define mmDCORE0_VSI_WRAP_DEC_ID_3 0xBF118

#define mmDCORE0_VSI_WRAP_DEC_ID_4 0xBF11C

#define mmDCORE0_VSI_WRAP_HWEVENT_CNTXT_ID_0 0xBF120

#define mmDCORE0_VSI_WRAP_HWEVENT_CNTXT_ID_1 0xBF124

#define mmDCORE0_VSI_WRAP_HWEVENT_CNTXT_ID_2 0xBF128

#define mmDCORE0_VSI_WRAP_HWEVENT_CNTXT_ID_3 0xBF12C

#define mmDCORE0_VSI_WRAP_HWEVENT_CNTXT_ID_4 0xBF130

#define mmDCORE0_VSI_WRAP_HWEVENT_CNTXT_ID_5 0xBF134

#define mmDCORE0_VSI_WRAP_CAUSE 0xBF138

#define mmDCORE0_VSI_WRAP_INTR_MASK 0xBF13C

#endif /* ASIC_REG_DCORE0_VSI_WRAP_REGS_H_ */
