/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_ROT_MASKS_H_
#define ASIC_REG_DCORE0_ROT_MASKS_H_

/*
 *****************************************
 *   DCORE0_ROT
 *   (Prototype: ROTATOR)
 *****************************************
 */

/* DCORE0_ROT_KMD_MODE */
#define DCORE0_ROT_KMD_MODE_EN_SHIFT 0
#define DCORE0_ROT_KMD_MODE_EN_MASK 0x1

/* DCORE0_ROT_CPL_QUEUE_EN */
#define DCORE0_ROT_CPL_QUEUE_EN_Q_EN_SHIFT 1
#define DCORE0_ROT_CPL_QUEUE_EN_Q_EN_MASK 0x2

/* DCORE0_ROT_CPL_QUEUE_ADDR_L */
#define DCORE0_ROT_CPL_QUEUE_ADDR_L_VAL_SHIFT 0
#define DCORE0_ROT_CPL_QUEUE_ADDR_L_VAL_MASK 0xFFFFFFFF

/* DCORE0_ROT_CPL_QUEUE_ADDR_H */
#define DCORE0_ROT_CPL_QUEUE_ADDR_H_VAL_SHIFT 0
#define DCORE0_ROT_CPL_QUEUE_ADDR_H_VAL_MASK 0xFFFFFFFF

/* DCORE0_ROT_CPL_QUEUE_DATA */
#define DCORE0_ROT_CPL_QUEUE_DATA_VAL_SHIFT 0
#define DCORE0_ROT_CPL_QUEUE_DATA_VAL_MASK 0xFFFFFFFF

/* DCORE0_ROT_CPL_QUEUE_AWUSER */
#define DCORE0_ROT_CPL_QUEUE_AWUSER_VAL_SHIFT 0
#define DCORE0_ROT_CPL_QUEUE_AWUSER_VAL_MASK 0xFFFFFFFF

/* DCORE0_ROT_CPL_QUEUE_AXI */
#define DCORE0_ROT_CPL_QUEUE_AXI_CACHE_SHIFT 0
#define DCORE0_ROT_CPL_QUEUE_AXI_CACHE_MASK 0xF
#define DCORE0_ROT_CPL_QUEUE_AXI_PROT_SHIFT 4
#define DCORE0_ROT_CPL_QUEUE_AXI_PROT_MASK 0x70

/* DCORE0_ROT_CPL_MSG_THRESHOLD */
#define DCORE0_ROT_CPL_MSG_THRESHOLD_VAL_SHIFT 0
#define DCORE0_ROT_CPL_MSG_THRESHOLD_VAL_MASK 0x3F

/* DCORE0_ROT_CPL_MSG_AXI */
#define DCORE0_ROT_CPL_MSG_AXI_CACHE_SHIFT 0
#define DCORE0_ROT_CPL_MSG_AXI_CACHE_MASK 0xF
#define DCORE0_ROT_CPL_MSG_AXI_PROT_SHIFT 4
#define DCORE0_ROT_CPL_MSG_AXI_PROT_MASK 0x70

/* DCORE0_ROT_AXI_WB */
#define DCORE0_ROT_AXI_WB_CACHE_SHIFT 0
#define DCORE0_ROT_AXI_WB_CACHE_MASK 0xF
#define DCORE0_ROT_AXI_WB_PROT_SHIFT 4
#define DCORE0_ROT_AXI_WB_PROT_MASK 0x70

/* DCORE0_ROT_ERR_CFG */
#define DCORE0_ROT_ERR_CFG_STOP_ON_ERR_SHIFT 0
#define DCORE0_ROT_ERR_CFG_STOP_ON_ERR_MASK 0x1

/* DCORE0_ROT_ERR_STATUS */
#define DCORE0_ROT_ERR_STATUS_ROT_HBW_RD_SHIFT 0
#define DCORE0_ROT_ERR_STATUS_ROT_HBW_RD_MASK 0x1
#define DCORE0_ROT_ERR_STATUS_ROT_HBW_WR_SHIFT 1
#define DCORE0_ROT_ERR_STATUS_ROT_HBW_WR_MASK 0x2
#define DCORE0_ROT_ERR_STATUS_QMAN_HBW_RD_SHIFT 2
#define DCORE0_ROT_ERR_STATUS_QMAN_HBW_RD_MASK 0x4
#define DCORE0_ROT_ERR_STATUS_QMAN_HBW_WR_SHIFT 3
#define DCORE0_ROT_ERR_STATUS_QMAN_HBW_WR_MASK 0x8
#define DCORE0_ROT_ERR_STATUS_ROT_LBW_WR_SHIFT 4
#define DCORE0_ROT_ERR_STATUS_ROT_LBW_WR_MASK 0x10

/* DCORE0_ROT_WBC_MAX_AWID */
#define DCORE0_ROT_WBC_MAX_AWID_VAL_SHIFT 0
#define DCORE0_ROT_WBC_MAX_AWID_VAL_MASK 0xFFFF

/* DCORE0_ROT_WBC_MAX_OUTSTANDING */
#define DCORE0_ROT_WBC_MAX_OUTSTANDING_VAL_SHIFT 0
#define DCORE0_ROT_WBC_MAX_OUTSTANDING_VAL_MASK 0xFFFF

/* DCORE0_ROT_WBC_RL */
#define DCORE0_ROT_WBC_RL_SATURATION_SHIFT 0
#define DCORE0_ROT_WBC_RL_SATURATION_MASK 0xFF
#define DCORE0_ROT_WBC_RL_TIMEOUT_SHIFT 8
#define DCORE0_ROT_WBC_RL_TIMEOUT_MASK 0xFF00
#define DCORE0_ROT_WBC_RL_RST_TOKEN_SHIFT 16
#define DCORE0_ROT_WBC_RL_RST_TOKEN_MASK 0xFF0000
#define DCORE0_ROT_WBC_RL_RATE_LIMITER_EN_SHIFT 24
#define DCORE0_ROT_WBC_RL_RATE_LIMITER_EN_MASK 0x1000000

/* DCORE0_ROT_WBC_INFLIGHTS */
#define DCORE0_ROT_WBC_INFLIGHTS_VAL_SHIFT 0
#define DCORE0_ROT_WBC_INFLIGHTS_VAL_MASK 0xFFFF

/* DCORE0_ROT_WBC_INFO */
#define DCORE0_ROT_WBC_INFO_EMPTY_SHIFT 0
#define DCORE0_ROT_WBC_INFO_EMPTY_MASK 0x1
#define DCORE0_ROT_WBC_INFO_AXI_IDLE_SHIFT 1
#define DCORE0_ROT_WBC_INFO_AXI_IDLE_MASK 0x2

/* DCORE0_ROT_WBC_MON */
#define DCORE0_ROT_WBC_MON_CNT_SHIFT 0
#define DCORE0_ROT_WBC_MON_CNT_MASK 0x1
#define DCORE0_ROT_WBC_MON_TS_SHIFT 8
#define DCORE0_ROT_WBC_MON_TS_MASK 0x300
#define DCORE0_ROT_WBC_MON_CONTEXT_ID_SHIFT 16
#define DCORE0_ROT_WBC_MON_CONTEXT_ID_MASK 0xFFFF0000

/* DCORE0_ROT_RSB_CAM_MAX_SIZE */
#define DCORE0_ROT_RSB_CAM_MAX_SIZE_DATA_SHIFT 0
#define DCORE0_ROT_RSB_CAM_MAX_SIZE_DATA_MASK 0xFFFF
#define DCORE0_ROT_RSB_CAM_MAX_SIZE_MD_SHIFT 16
#define DCORE0_ROT_RSB_CAM_MAX_SIZE_MD_MASK 0xFFFF0000

/* DCORE0_ROT_RSB_CFG */
#define DCORE0_ROT_RSB_CFG_CACHE_DISABLE_SHIFT 0
#define DCORE0_ROT_RSB_CFG_CACHE_DISABLE_MASK 0x1
#define DCORE0_ROT_RSB_CFG_ENABLE_CGATE_SHIFT 1
#define DCORE0_ROT_RSB_CFG_ENABLE_CGATE_MASK 0x2

/* DCORE0_ROT_RSB_MAX_OS */
#define DCORE0_ROT_RSB_MAX_OS_VAL_SHIFT 0
#define DCORE0_ROT_RSB_MAX_OS_VAL_MASK 0xFFFF

/* DCORE0_ROT_RSB_RL */
#define DCORE0_ROT_RSB_RL_SATURATION_SHIFT 0
#define DCORE0_ROT_RSB_RL_SATURATION_MASK 0xFF
#define DCORE0_ROT_RSB_RL_TIMEOUT_SHIFT 8
#define DCORE0_ROT_RSB_RL_TIMEOUT_MASK 0xFF00
#define DCORE0_ROT_RSB_RL_RST_TOKEN_SHIFT 16
#define DCORE0_ROT_RSB_RL_RST_TOKEN_MASK 0xFF0000
#define DCORE0_ROT_RSB_RL_RATE_LIMITER_EN_SHIFT 24
#define DCORE0_ROT_RSB_RL_RATE_LIMITER_EN_MASK 0x1000000

/* DCORE0_ROT_RSB_INFLIGHTS */
#define DCORE0_ROT_RSB_INFLIGHTS_VAL_SHIFT 0
#define DCORE0_ROT_RSB_INFLIGHTS_VAL_MASK 0xFFFFFFFF

/* DCORE0_ROT_RSB_OCCUPANCY */
#define DCORE0_ROT_RSB_OCCUPANCY_VAL_SHIFT 0
#define DCORE0_ROT_RSB_OCCUPANCY_VAL_MASK 0xFFFFFFFF

/* DCORE0_ROT_RSB_INFO */
#define DCORE0_ROT_RSB_INFO_EMPTY_SHIFT 0
#define DCORE0_ROT_RSB_INFO_EMPTY_MASK 0x1
#define DCORE0_ROT_RSB_INFO_AXI_IDLE_SHIFT 1
#define DCORE0_ROT_RSB_INFO_AXI_IDLE_MASK 0x2

/* DCORE0_ROT_RSB_MON */
#define DCORE0_ROT_RSB_MON_CNT_SHIFT 0
#define DCORE0_ROT_RSB_MON_CNT_MASK 0x7F
#define DCORE0_ROT_RSB_MON_TS_SHIFT 8
#define DCORE0_ROT_RSB_MON_TS_MASK 0x300

/* DCORE0_ROT_RSB_MON_CONTEXT_ID */
#define DCORE0_ROT_RSB_MON_CONTEXT_ID_VAL_SHIFT 0
#define DCORE0_ROT_RSB_MON_CONTEXT_ID_VAL_MASK 0xFFFFFFFF

/* DCORE0_ROT_MSS_HALT */

/* DCORE0_ROT_MSS_SEI_STATUS */
#define DCORE0_ROT_MSS_SEI_STATUS_I0_SHIFT 0
#define DCORE0_ROT_MSS_SEI_STATUS_I0_MASK 0x1
#define DCORE0_ROT_MSS_SEI_STATUS_I1_SHIFT 1
#define DCORE0_ROT_MSS_SEI_STATUS_I1_MASK 0x2
#define DCORE0_ROT_MSS_SEI_STATUS_I2_SHIFT 2
#define DCORE0_ROT_MSS_SEI_STATUS_I2_MASK 0x4
#define DCORE0_ROT_MSS_SEI_STATUS_I3_SHIFT 3
#define DCORE0_ROT_MSS_SEI_STATUS_I3_MASK 0x8
#define DCORE0_ROT_MSS_SEI_STATUS_I4_SHIFT 4
#define DCORE0_ROT_MSS_SEI_STATUS_I4_MASK 0x10
#define DCORE0_ROT_MSS_SEI_STATUS_I5_SHIFT 5
#define DCORE0_ROT_MSS_SEI_STATUS_I5_MASK 0x20
#define DCORE0_ROT_MSS_SEI_STATUS_I6_SHIFT 6
#define DCORE0_ROT_MSS_SEI_STATUS_I6_MASK 0x40
#define DCORE0_ROT_MSS_SEI_STATUS_I7_SHIFT 7
#define DCORE0_ROT_MSS_SEI_STATUS_I7_MASK 0x80
#define DCORE0_ROT_MSS_SEI_STATUS_I8_SHIFT 8
#define DCORE0_ROT_MSS_SEI_STATUS_I8_MASK 0x100

/* DCORE0_ROT_MSS_SEI_MASK */
#define DCORE0_ROT_MSS_SEI_MASK_VAL_SHIFT 0
#define DCORE0_ROT_MSS_SEI_MASK_VAL_MASK 0x1FF

/* DCORE0_ROT_MSS_SPI_STATUS */
#define DCORE0_ROT_MSS_SPI_STATUS_I0_SHIFT 0
#define DCORE0_ROT_MSS_SPI_STATUS_I0_MASK 0x1
#define DCORE0_ROT_MSS_SPI_STATUS_I1_SHIFT 1
#define DCORE0_ROT_MSS_SPI_STATUS_I1_MASK 0x2
#define DCORE0_ROT_MSS_SPI_STATUS_I2_SHIFT 2
#define DCORE0_ROT_MSS_SPI_STATUS_I2_MASK 0x4
#define DCORE0_ROT_MSS_SPI_STATUS_I3_SHIFT 3
#define DCORE0_ROT_MSS_SPI_STATUS_I3_MASK 0x8
#define DCORE0_ROT_MSS_SPI_STATUS_I4_SHIFT 4
#define DCORE0_ROT_MSS_SPI_STATUS_I4_MASK 0x10
#define DCORE0_ROT_MSS_SPI_STATUS_I5_SHIFT 5
#define DCORE0_ROT_MSS_SPI_STATUS_I5_MASK 0x20
#define DCORE0_ROT_MSS_SPI_STATUS_I6_SHIFT 6
#define DCORE0_ROT_MSS_SPI_STATUS_I6_MASK 0x40
#define DCORE0_ROT_MSS_SPI_STATUS_I7_SHIFT 7
#define DCORE0_ROT_MSS_SPI_STATUS_I7_MASK 0x80

/* DCORE0_ROT_MSS_SPI_MASK */
#define DCORE0_ROT_MSS_SPI_MASK_VAL_SHIFT 0
#define DCORE0_ROT_MSS_SPI_MASK_VAL_MASK 0xFF

/* DCORE0_ROT_DISABLE_PAD_CALC */
#define DCORE0_ROT_DISABLE_PAD_CALC_VAL_SHIFT 0
#define DCORE0_ROT_DISABLE_PAD_CALC_VAL_MASK 0x1

/* DCORE0_ROT_QMAN_CFG */
#define DCORE0_ROT_QMAN_CFG_FORCE_STOP_SHIFT 0
#define DCORE0_ROT_QMAN_CFG_FORCE_STOP_MASK 0x1

/* DCORE0_ROT_CLK_EN */
#define DCORE0_ROT_CLK_EN_LBW_CFG_DIS_SHIFT 0
#define DCORE0_ROT_CLK_EN_LBW_CFG_DIS_MASK 0x1
#define DCORE0_ROT_CLK_EN_DBG_CFG_DIS_SHIFT 4
#define DCORE0_ROT_CLK_EN_DBG_CFG_DIS_MASK 0x10

#endif /* ASIC_REG_DCORE0_ROT_MASKS_H_ */
