/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_QM_AXUSER_NONSECURED_REGS_H_
#define ASIC_REG_DCORE0_MME_QM_AXUSER_NONSECURED_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_QM_AXUSER_NONSECURED
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_MME_QM_AXUSER_NONSECURED_CORE 0x1C0B40

#define mmDCORE0_MME_QM_AXUSER_NONSECURED_E2E 0x1C0B44

#define mmDCORE0_MME_QM_AXUSER_NONSECURED_HB_SEC 0x1C0B48

#define mmDCORE0_MME_QM_AXUSER_NONSECURED_HB_PCIE 0x1C0B4C

#define mmDCORE0_MME_QM_AXUSER_NONSECURED_HB_DDR_QOS 0x1C0B50

#define mmDCORE0_MME_QM_AXUSER_NONSECURED_HB_DDR_CPAGE 0x1C0B54

#define mmDCORE0_MME_QM_AXUSER_NONSECURED_HB_REDUCTION 0x1C0B58

#define mmDCORE0_MME_QM_AXUSER_NONSECURED_HB_RSVD 0x1C0B5C

#define mmDCORE0_MME_QM_AXUSER_NONSECURED_HB_OVRD_LO 0x1C0B60

#define mmDCORE0_MME_QM_AXUSER_NONSECURED_HB_OVRD_HI 0x1C0B64

#define mmDCORE0_MME_QM_AXUSER_NONSECURED_LB_COORD 0x1C0B70

#define mmDCORE0_MME_QM_AXUSER_NONSECURED_LB_LOCK 0x1C0B74

#define mmDCORE0_MME_QM_AXUSER_NONSECURED_LB_RSVD 0x1C0B78

#define mmDCORE0_MME_QM_AXUSER_NONSECURED_LB_OVRD 0x1C0B7C

#endif /* ASIC_REG_DCORE0_MME_QM_AXUSER_NONSECURED_REGS_H_ */
