/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_REGS_H_
#define ASIC_REG_DCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_CORE 0xA0800

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_E2E 0xA0804

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_HB_SEC 0xA0808

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_HB_PCIE 0xA080C

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_HB_DDR_QOS 0xA0810

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_HB_DDR_CPAGE 0xA0814

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_HB_REDUCTION 0xA0818

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_HB_RSVD 0xA081C

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_HB_OVRD_LO 0xA0820

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_HB_OVRD_HI 0xA0824

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_LB_COORD 0xA0830

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_LB_LOCK 0xA0834

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_LB_RSVD 0xA0838

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_LB_OVRD 0xA083C

#endif /* ASIC_REG_DCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_VCD_REGS_H_ */
