/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_REGS_H_
#define ASIC_REG_DCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_CORE 0xACA00

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_E2E 0xACA04

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_HB_SEC 0xACA08

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_HB_PCIE 0xACA0C

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_HB_DDR_QOS 0xACA10

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_HB_DDR_CPAGE 0xACA14

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_HB_REDUCTION 0xACA18

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_HB_RSVD 0xACA1C

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_HB_OVRD_LO 0xACA20

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_HB_OVRD_HI 0xACA24

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_LB_COORD 0xACA30

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_LB_LOCK 0xACA34

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_LB_RSVD 0xACA38

#define mmDCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_LB_OVRD 0xACA3C

#endif /* ASIC_REG_DCORE0_VDEC2_BRDG_CTRL_AXUSER_MSIX_NRM_REGS_H_ */
