/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_REGS_H_
#define ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT
 *   (Prototype: MME_TENSOR)
 *****************************************
 */

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_VALID_ELEMENTS_0 0x1C3588

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_VALID_ELEMENTS_1 0x1C358C

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_VALID_ELEMENTS_2 0x1C3590

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_VALID_ELEMENTS_3 0x1C3594

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_VALID_ELEMENTS_4 0x1C3598

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_LOOP_STRIDE_0 0x1C359C

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_LOOP_STRIDE_1 0x1C35A0

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_LOOP_STRIDE_2 0x1C35A4

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_LOOP_STRIDE_3 0x1C35A8

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_LOOP_STRIDE_4 0x1C35AC

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_ROI_SIZE_0 0x1C35B0

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_ROI_SIZE_1 0x1C35B4

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_ROI_SIZE_2 0x1C35B8

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_ROI_SIZE_3 0x1C35BC

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_SPATIAL_STRIDES_0 0x1C35C0

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_SPATIAL_STRIDES_1 0x1C35C4

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_SPATIAL_STRIDES_2 0x1C35C8

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_SPATIAL_STRIDES_3 0x1C35CC

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_START_OFFSET_0 0x1C35D0

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_START_OFFSET_1 0x1C35D4

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_START_OFFSET_2 0x1C35D8

#define mmDCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_START_OFFSET_3 0x1C35DC

#endif /* ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_3_TENSOR_COUT_REGS_H_ */
