/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_REGS_H_
#define ASIC_REG_DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_CORE 0xA6A00

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_E2E 0xA6A04

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_HB_SEC 0xA6A08

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_HB_PCIE 0xA6A0C

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_HB_DDR_QOS 0xA6A10

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_HB_DDR_CPAGE 0xA6A14

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_HB_REDUCTION 0xA6A18

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_HB_RSVD 0xA6A1C

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_HB_OVRD_LO 0xA6A20

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_HB_OVRD_HI 0xA6A24

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_LB_COORD 0xA6A30

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_LB_LOCK 0xA6A34

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_LB_RSVD 0xA6A38

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_LB_OVRD 0xA6A3C

#endif /* ASIC_REG_DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_NRM_REGS_H_ */
