/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_TPC4_QM_AXUSER_NONSECURED_REGS_H_
#define ASIC_REG_DCORE0_TPC4_QM_AXUSER_NONSECURED_REGS_H_

/*
 *****************************************
 *   DCORE0_TPC4_QM_AXUSER_NONSECURED
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_TPC4_QM_AXUSER_NONSECURED_CORE 0x40B40

#define mmDCORE0_TPC4_QM_AXUSER_NONSECURED_E2E 0x40B44

#define mmDCORE0_TPC4_QM_AXUSER_NONSECURED_HB_SEC 0x40B48

#define mmDCORE0_TPC4_QM_AXUSER_NONSECURED_HB_PCIE 0x40B4C

#define mmDCORE0_TPC4_QM_AXUSER_NONSECURED_HB_DDR_QOS 0x40B50

#define mmDCORE0_TPC4_QM_AXUSER_NONSECURED_HB_DDR_CPAGE 0x40B54

#define mmDCORE0_TPC4_QM_AXUSER_NONSECURED_HB_REDUCTION 0x40B58

#define mmDCORE0_TPC4_QM_AXUSER_NONSECURED_HB_RSVD 0x40B5C

#define mmDCORE0_TPC4_QM_AXUSER_NONSECURED_HB_OVRD_LO 0x40B60

#define mmDCORE0_TPC4_QM_AXUSER_NONSECURED_HB_OVRD_HI 0x40B64

#define mmDCORE0_TPC4_QM_AXUSER_NONSECURED_LB_COORD 0x40B70

#define mmDCORE0_TPC4_QM_AXUSER_NONSECURED_LB_LOCK 0x40B74

#define mmDCORE0_TPC4_QM_AXUSER_NONSECURED_LB_RSVD 0x40B78

#define mmDCORE0_TPC4_QM_AXUSER_NONSECURED_LB_OVRD 0x40B7C

#endif /* ASIC_REG_DCORE0_TPC4_QM_AXUSER_NONSECURED_REGS_H_ */
