/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_REGS_H_
#define ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT
 *   (Prototype: MME_TENSOR)
 *****************************************
 */

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_VALID_ELEMENTS_0 0x1C3188

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_VALID_ELEMENTS_1 0x1C318C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_VALID_ELEMENTS_2 0x1C3190

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_VALID_ELEMENTS_3 0x1C3194

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_VALID_ELEMENTS_4 0x1C3198

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_LOOP_STRIDE_0 0x1C319C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_LOOP_STRIDE_1 0x1C31A0

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_LOOP_STRIDE_2 0x1C31A4

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_LOOP_STRIDE_3 0x1C31A8

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_LOOP_STRIDE_4 0x1C31AC

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_ROI_SIZE_0 0x1C31B0

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_ROI_SIZE_1 0x1C31B4

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_ROI_SIZE_2 0x1C31B8

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_ROI_SIZE_3 0x1C31BC

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_SPATIAL_STRIDES_0 0x1C31C0

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_SPATIAL_STRIDES_1 0x1C31C4

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_SPATIAL_STRIDES_2 0x1C31C8

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_SPATIAL_STRIDES_3 0x1C31CC

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_START_OFFSET_0 0x1C31D0

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_START_OFFSET_1 0x1C31D4

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_START_OFFSET_2 0x1C31D8

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_START_OFFSET_3 0x1C31DC

#endif /* ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_COUT_REGS_H_ */
