/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_REGS_H_
#define ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN
 *   (Prototype: MME_TENSOR)
 *****************************************
 */

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_VALID_ELEMENTS_0 0x1C3008

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_VALID_ELEMENTS_1 0x1C300C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_VALID_ELEMENTS_2 0x1C3010

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_VALID_ELEMENTS_3 0x1C3014

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_VALID_ELEMENTS_4 0x1C3018

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_LOOP_STRIDE_0 0x1C301C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_LOOP_STRIDE_1 0x1C3020

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_LOOP_STRIDE_2 0x1C3024

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_LOOP_STRIDE_3 0x1C3028

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_LOOP_STRIDE_4 0x1C302C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_ROI_SIZE_0 0x1C3030

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_ROI_SIZE_1 0x1C3034

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_ROI_SIZE_2 0x1C3038

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_ROI_SIZE_3 0x1C303C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_SPATIAL_STRIDES_0 0x1C3040

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_SPATIAL_STRIDES_1 0x1C3044

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_SPATIAL_STRIDES_2 0x1C3048

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_SPATIAL_STRIDES_3 0x1C304C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_START_OFFSET_0 0x1C3050

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_START_OFFSET_1 0x1C3054

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_START_OFFSET_2 0x1C3058

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_START_OFFSET_3 0x1C305C

#endif /* ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_TENSOR_CIN_REGS_H_ */
