/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE1_DDMA_MSTR_IF_CORE_HBW_REGS_H_
#define ASIC_REG_DCORE1_DDMA_MSTR_IF_CORE_HBW_REGS_H_

/*
 *****************************************
 *   DCORE1_DDMA_MSTR_IF_CORE_HBW
 *   (Prototype: MSTR_IF_HBW_CORE)
 *****************************************
 */

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_AXPROT_OVRD 0x2C3D00

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_RL_WR 0x2C3D04

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_RL_RD 0x2C3D08

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_PCI 0x2C3D0C

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_EXTMEM 0x2C3D10

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_SRAM 0x2C3D14

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_REST 0x2C3D18

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_TOTAL 0x2C3D1C

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_PCI 0x2C3D20

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_EXTMEM 0x2C3D24

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_SRAM 0x2C3D28

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_REST 0x2C3D2C

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_TOTAL 0x2C3D30

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_EN 0x2C3D34

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_EXTMEM_EN 0x2C3D38

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_PERM_SEL 0x2C3D3C

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_0 0x2C3D40

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_1 0x2C3D44

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_2 0x2C3D48

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_3 0x2C3D4C

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_4 0x2C3D50

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_5 0x2C3D54

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_6 0x2C3D58

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_7 0x2C3D5C

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_8 0x2C3D60

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_9 0x2C3D64

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_10 0x2C3D68

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_11 0x2C3D6C

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_12 0x2C3D70

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_13 0x2C3D74

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_14 0x2C3D78

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_15 0x2C3D7C

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_16 0x2C3D80

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_17 0x2C3D84

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_18 0x2C3D88

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_19 0x2C3D8C

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_20 0x2C3D90

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_21 0x2C3D94

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_22 0x2C3D98

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_23 0x2C3D9C

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_24 0x2C3DA0

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_25 0x2C3DA4

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_26 0x2C3DA8

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_27 0x2C3DAC

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_28 0x2C3DB0

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_CORE_MODE 0x2C3DB4

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_EXTMEM_ID_LOC 0x2C3DB8

#define mmDCORE1_DDMA_MSTR_IF_CORE_HBW_CRDT_ARB_DBG 0x2C3DBC

#endif /* ASIC_REG_DCORE1_DDMA_MSTR_IF_CORE_HBW_REGS_H_ */
