/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC0_BRDG_CTRL_SPECIAL_REGS_H_
#define ASIC_REG_DCORE0_VDEC0_BRDG_CTRL_SPECIAL_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC0_BRDG_CTRL_SPECIAL
 *   (Prototype: SPECIAL_REGS)
 *****************************************
 */

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_0 0xA0E80

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_1 0xA0E84

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_2 0xA0E88

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_3 0xA0E8C

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_4 0xA0E90

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_5 0xA0E94

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_6 0xA0E98

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_7 0xA0E9C

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_8 0xA0EA0

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_9 0xA0EA4

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_10 0xA0EA8

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_11 0xA0EAC

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_12 0xA0EB0

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_13 0xA0EB4

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_14 0xA0EB8

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_15 0xA0EBC

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_16 0xA0EC0

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_17 0xA0EC4

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_18 0xA0EC8

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_19 0xA0ECC

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_20 0xA0ED0

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_21 0xA0ED4

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_22 0xA0ED8

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_23 0xA0EDC

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_24 0xA0EE0

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_25 0xA0EE4

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_26 0xA0EE8

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_27 0xA0EEC

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_28 0xA0EF0

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_29 0xA0EF4

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_30 0xA0EF8

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_PRIV_31 0xA0EFC

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_MEM_GW_DATA 0xA0F00

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_MEM_GW_REQ 0xA0F04

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_MEM_NUMOF 0xA0F0C

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_MEM_ECC_SEL 0xA0F10

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_MEM_ECC_CTL 0xA0F14

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_MEM_ECC_ERR_MASK 0xA0F18

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_MEM_ECC_GLBL_ERR_MASK 0xA0F1C

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_MEM_ECC_ERR_STS 0xA0F20

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_MEM_ECC_ERR_ADDR 0xA0F24

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_MEM_RM 0xA0F28

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_ERR_MASK 0xA0F40

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_ERR_ADDR 0xA0F44

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_ERR_CAUSE 0xA0F48

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SPARE_0 0xA0F60

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SPARE_1 0xA0F64

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SPARE_2 0xA0F68

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SPARE_3 0xA0F6C

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_0 0xA0F80

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_1 0xA0F84

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_2 0xA0F88

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_3 0xA0F8C

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_4 0xA0F90

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_5 0xA0F94

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_6 0xA0F98

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_7 0xA0F9C

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_8 0xA0FA0

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_9 0xA0FA4

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_10 0xA0FA8

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_11 0xA0FAC

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_12 0xA0FB0

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_13 0xA0FB4

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_14 0xA0FB8

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_15 0xA0FBC

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_16 0xA0FC0

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_17 0xA0FC4

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_18 0xA0FC8

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_19 0xA0FCC

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_20 0xA0FD0

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_21 0xA0FD4

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_22 0xA0FD8

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_23 0xA0FDC

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_24 0xA0FE0

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_25 0xA0FE4

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_26 0xA0FE8

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_27 0xA0FEC

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_28 0xA0FF0

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_29 0xA0FF4

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_30 0xA0FF8

#define mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_GLBL_SEC_31 0xA0FFC

#endif /* ASIC_REG_DCORE0_VDEC0_BRDG_CTRL_SPECIAL_REGS_H_ */
