/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_REGS_H_
#define ASIC_REG_DCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_CORE 0xB8800

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_E2E 0xB8804

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_HB_SEC 0xB8808

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_HB_PCIE 0xB880C

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_HB_DDR_QOS 0xB8810

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_HB_DDR_CPAGE 0xB8814

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_HB_REDUCTION 0xB8818

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_HB_RSVD 0xB881C

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_HB_OVRD_LO 0xB8820

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_HB_OVRD_HI 0xB8824

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_LB_COORD 0xB8830

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_LB_LOCK 0xB8834

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_LB_RSVD 0xB8838

#define mmDCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_LB_OVRD 0xB883C

#endif /* ASIC_REG_DCORE0_VDEC4_BRDG_CTRL_AXUSER_MSIX_VCD_REGS_H_ */
