/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_DDMA_CORE_CTX_REGS_H_
#define ASIC_REG_DCORE0_DDMA_CORE_CTX_REGS_H_

/*
 *****************************************
 *   DCORE0_DDMA_CORE_CTX
 *   (Prototype: DMA_CORE_CTX)
 *****************************************
 */

#define mmDCORE0_DDMA_CORE_CTX_RATE_LIM_TKN 0xC2840

#define mmDCORE0_DDMA_CORE_CTX_PWRLP 0xC2844

#define mmDCORE0_DDMA_CORE_CTX_TE_NUMROWS 0xC2848

#define mmDCORE0_DDMA_CORE_CTX_CTRL 0xC284C

#define mmDCORE0_DDMA_CORE_CTX_SRC_TSIZE_0 0xC2850

#define mmDCORE0_DDMA_CORE_CTX_SRC_TSIZE_1 0xC2854

#define mmDCORE0_DDMA_CORE_CTX_SRC_STRIDE_1 0xC2858

#define mmDCORE0_DDMA_CORE_CTX_SRC_TSIZE_2 0xC285C

#define mmDCORE0_DDMA_CORE_CTX_SRC_STRIDE_2 0xC2860

#define mmDCORE0_DDMA_CORE_CTX_SRC_TSIZE_3 0xC2864

#define mmDCORE0_DDMA_CORE_CTX_SRC_STRIDE_3 0xC2868

#define mmDCORE0_DDMA_CORE_CTX_SRC_TSIZE_4 0xC286C

#define mmDCORE0_DDMA_CORE_CTX_SRC_STRIDE_4 0xC2870

#define mmDCORE0_DDMA_CORE_CTX_DST_TSIZE_1 0xC2874

#define mmDCORE0_DDMA_CORE_CTX_DST_STRIDE_1 0xC2878

#define mmDCORE0_DDMA_CORE_CTX_DST_TSIZE_2 0xC287C

#define mmDCORE0_DDMA_CORE_CTX_DST_STRIDE_2 0xC2880

#define mmDCORE0_DDMA_CORE_CTX_DST_TSIZE_3 0xC2884

#define mmDCORE0_DDMA_CORE_CTX_DST_STRIDE_3 0xC2888

#define mmDCORE0_DDMA_CORE_CTX_DST_TSIZE_4 0xC288C

#define mmDCORE0_DDMA_CORE_CTX_DST_STRIDE_4 0xC2890

#define mmDCORE0_DDMA_CORE_CTX_WR_COMP_ADDR_HI 0xC2894

#define mmDCORE0_DDMA_CORE_CTX_WR_COMP_ADDR_LO 0xC2898

#define mmDCORE0_DDMA_CORE_CTX_WR_COMP_WDATA 0xC289C

#define mmDCORE0_DDMA_CORE_CTX_SRC_BASE_LO 0xC28A0

#define mmDCORE0_DDMA_CORE_CTX_SRC_BASE_HI 0xC28A4

#define mmDCORE0_DDMA_CORE_CTX_DST_BASE_LO 0xC28A8

#define mmDCORE0_DDMA_CORE_CTX_DST_BASE_HI 0xC28AC

#define mmDCORE0_DDMA_CORE_CTX_DST_TSIZE_0 0xC28B0

#define mmDCORE0_DDMA_CORE_CTX_COMMIT 0xC28B4

#endif /* ASIC_REG_DCORE0_DDMA_CORE_CTX_REGS_H_ */
