/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_KDMA_CORE_CTX_MASKS_H_
#define ASIC_REG_DCORE0_KDMA_CORE_CTX_MASKS_H_

/*
 *****************************************
 *   DCORE0_KDMA_CORE_CTX
 *   (Prototype: DMA_CORE_CTX)
 *****************************************
 */

/* DCORE0_KDMA_CORE_CTX_RATE_LIM_TKN */
#define DCORE0_KDMA_CORE_CTX_RATE_LIM_TKN_RD_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_RATE_LIM_TKN_RD_MASK 0xFF
#define DCORE0_KDMA_CORE_CTX_RATE_LIM_TKN_WR_SHIFT 16
#define DCORE0_KDMA_CORE_CTX_RATE_LIM_TKN_WR_MASK 0xFF0000

/* DCORE0_KDMA_CORE_CTX_PWRLP */
#define DCORE0_KDMA_CORE_CTX_PWRLP_DATA_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_PWRLP_DATA_MASK 0xFF
#define DCORE0_KDMA_CORE_CTX_PWRLP_EN_SHIFT 8
#define DCORE0_KDMA_CORE_CTX_PWRLP_EN_MASK 0x100

/* DCORE0_KDMA_CORE_CTX_TE_NUMROWS */
#define DCORE0_KDMA_CORE_CTX_TE_NUMROWS_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_TE_NUMROWS_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_CTRL */
#define DCORE0_KDMA_CORE_CTX_CTRL_TRANSPOSE_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_CTRL_TRANSPOSE_MASK 0x1
#define DCORE0_KDMA_CORE_CTX_CTRL_DTYPE_SHIFT 4
#define DCORE0_KDMA_CORE_CTX_CTRL_DTYPE_MASK 0x30
#define DCORE0_KDMA_CORE_CTX_CTRL_COMPRESS_SHIFT 8
#define DCORE0_KDMA_CORE_CTX_CTRL_COMPRESS_MASK 0x100
#define DCORE0_KDMA_CORE_CTX_CTRL_DECOMPRESS_SHIFT 9
#define DCORE0_KDMA_CORE_CTX_CTRL_DECOMPRESS_MASK 0x200
#define DCORE0_KDMA_CORE_CTX_CTRL_RD_UNCACHEABLE_SHIFT 12
#define DCORE0_KDMA_CORE_CTX_CTRL_RD_UNCACHEABLE_MASK 0x1000

/* DCORE0_KDMA_CORE_CTX_SRC_TSIZE_0 */
#define DCORE0_KDMA_CORE_CTX_SRC_TSIZE_0_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_SRC_TSIZE_0_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_SRC_TSIZE_1 */
#define DCORE0_KDMA_CORE_CTX_SRC_TSIZE_1_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_SRC_TSIZE_1_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_SRC_STRIDE_1 */
#define DCORE0_KDMA_CORE_CTX_SRC_STRIDE_1_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_SRC_STRIDE_1_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_SRC_TSIZE_2 */
#define DCORE0_KDMA_CORE_CTX_SRC_TSIZE_2_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_SRC_TSIZE_2_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_SRC_STRIDE_2 */
#define DCORE0_KDMA_CORE_CTX_SRC_STRIDE_2_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_SRC_STRIDE_2_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_SRC_TSIZE_3 */
#define DCORE0_KDMA_CORE_CTX_SRC_TSIZE_3_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_SRC_TSIZE_3_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_SRC_STRIDE_3 */
#define DCORE0_KDMA_CORE_CTX_SRC_STRIDE_3_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_SRC_STRIDE_3_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_SRC_TSIZE_4 */
#define DCORE0_KDMA_CORE_CTX_SRC_TSIZE_4_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_SRC_TSIZE_4_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_SRC_STRIDE_4 */
#define DCORE0_KDMA_CORE_CTX_SRC_STRIDE_4_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_SRC_STRIDE_4_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_DST_TSIZE_1 */
#define DCORE0_KDMA_CORE_CTX_DST_TSIZE_1_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_DST_TSIZE_1_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_DST_STRIDE_1 */
#define DCORE0_KDMA_CORE_CTX_DST_STRIDE_1_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_DST_STRIDE_1_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_DST_TSIZE_2 */
#define DCORE0_KDMA_CORE_CTX_DST_TSIZE_2_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_DST_TSIZE_2_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_DST_STRIDE_2 */
#define DCORE0_KDMA_CORE_CTX_DST_STRIDE_2_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_DST_STRIDE_2_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_DST_TSIZE_3 */
#define DCORE0_KDMA_CORE_CTX_DST_TSIZE_3_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_DST_TSIZE_3_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_DST_STRIDE_3 */
#define DCORE0_KDMA_CORE_CTX_DST_STRIDE_3_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_DST_STRIDE_3_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_DST_TSIZE_4 */
#define DCORE0_KDMA_CORE_CTX_DST_TSIZE_4_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_DST_TSIZE_4_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_DST_STRIDE_4 */
#define DCORE0_KDMA_CORE_CTX_DST_STRIDE_4_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_DST_STRIDE_4_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_WR_COMP_ADDR_HI */
#define DCORE0_KDMA_CORE_CTX_WR_COMP_ADDR_HI_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_WR_COMP_ADDR_HI_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_WR_COMP_ADDR_LO */
#define DCORE0_KDMA_CORE_CTX_WR_COMP_ADDR_LO_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_WR_COMP_ADDR_LO_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_WR_COMP_WDATA */
#define DCORE0_KDMA_CORE_CTX_WR_COMP_WDATA_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_WR_COMP_WDATA_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_SRC_BASE_LO */
#define DCORE0_KDMA_CORE_CTX_SRC_BASE_LO_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_SRC_BASE_LO_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_SRC_BASE_HI */
#define DCORE0_KDMA_CORE_CTX_SRC_BASE_HI_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_SRC_BASE_HI_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_DST_BASE_LO */
#define DCORE0_KDMA_CORE_CTX_DST_BASE_LO_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_DST_BASE_LO_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_DST_BASE_HI */
#define DCORE0_KDMA_CORE_CTX_DST_BASE_HI_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_DST_BASE_HI_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_DST_TSIZE_0 */
#define DCORE0_KDMA_CORE_CTX_DST_TSIZE_0_VAL_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_DST_TSIZE_0_VAL_MASK 0xFFFFFFFF

/* DCORE0_KDMA_CORE_CTX_COMMIT */
#define DCORE0_KDMA_CORE_CTX_COMMIT_WR_COMP_EN_SHIFT 0
#define DCORE0_KDMA_CORE_CTX_COMMIT_WR_COMP_EN_MASK 0x1
#define DCORE0_KDMA_CORE_CTX_COMMIT_ENDIAN_SWAP_SHIFT 1
#define DCORE0_KDMA_CORE_CTX_COMMIT_ENDIAN_SWAP_MASK 0x6
#define DCORE0_KDMA_CORE_CTX_COMMIT_MEM_SET_SHIFT 4
#define DCORE0_KDMA_CORE_CTX_COMMIT_MEM_SET_MASK 0x10
#define DCORE0_KDMA_CORE_CTX_COMMIT_CTX_ID_SHIFT 8
#define DCORE0_KDMA_CORE_CTX_COMMIT_CTX_ID_MASK 0xFFFF00
#define DCORE0_KDMA_CORE_CTX_COMMIT_LIN_SHIFT 31
#define DCORE0_KDMA_CORE_CTX_COMMIT_LIN_MASK 0x80000000

#endif /* ASIC_REG_DCORE0_KDMA_CORE_CTX_MASKS_H_ */
