/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_REGS_H_
#define ASIC_REG_DCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_REGS_H_

/*
 *****************************************
 *   DCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT
 *   (Prototype: E2E_CRED)
 *****************************************
 */

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_EMEM_EN 0xBE800

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_PCI_EN 0xBE804

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_EXTMEM_SB_RELEASE_EN 0xBE808

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_PCI_SB_RELEASE_EN 0xBE80C

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM0_CTR_CNT 0xBE810

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM1_CTR_CNT 0xBE814

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM2_CTR_CNT 0xBE818

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM3_CTR_CNT 0xBE81C

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM0_CTR_WRAP 0xBE820

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM1_CTR_WRAP 0xBE824

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM2_CTR_WRAP 0xBE828

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM3_CTR_WRAP 0xBE82C

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_EMEM_RD_SIZE_0 0xBE830

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_EMEM_RD_SIZE_1 0xBE834

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_EMEM_RD_SIZE_2 0xBE838

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_EMEM_RD_SIZE_3 0xBE83C

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_PCI_RD_SIZE 0xBE840

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_EMEM_WR_SIZE_0 0xBE844

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_EMEM_WR_SIZE_1 0xBE848

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_EMEM_WR_SIZE_2 0xBE84C

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_EMEM_WR_SIZE_3 0xBE850

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_PCI_WR_SIZE 0xBE854

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_PCI_CTR_WRAP 0xBE858

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_PCI_CTR_WRAP 0xBE85C

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_PCI_CTR_CNT 0xBE860

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_PCI_CTR_CNT 0xBE864

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM0_CTR_CNT 0xBE868

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM1_CTR_CNT 0xBE86C

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM2_CTR_CNT 0xBE870

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM3_CTR_CNT 0xBE874

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM0_CTR_WRAP 0xBE878

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM1_CTR_WRAP 0xBE87C

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM2_CTR_WRAP 0xBE880

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM3_CTR_WRAP 0xBE884

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_PCI_CTR_SET_EN 0xBE888

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_PCI_CTR_SET 0xBE88C

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM_CTR_SET_EN_0 0xBE890

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM_CTR_SET_EN_1 0xBE894

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM_CTR_SET_EN_2 0xBE898

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM_CTR_SET_EN_3 0xBE89C

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM_CTR_SET_0 0xBE8A0

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM_CTR_SET_1 0xBE8A4

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM_CTR_SET_2 0xBE8A8

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AW_EMEM_CTR_SET_3 0xBE8AC

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_PCI_CTR_SET_EN 0xBE8B0

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_PCI_CTR_SET 0xBE8B4

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM_CTR_SET_EN_0 0xBE8B8

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM_CTR_SET_EN_1 0xBE8BC

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM_CTR_SET_EN_2 0xBE8C0

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM_CTR_SET_EN_3 0xBE8C4

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM_CTR_SET_0 0xBE8C8

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM_CTR_SET_1 0xBE8CC

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM_CTR_SET_2 0xBE8D0

#define mmDCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_E2E_AR_EMEM_CTR_SET_3 0xBE8D4

#endif /* ASIC_REG_DCORE0_VSI_WRAP_MSTR_IF_E2E_CRDT_REGS_H_ */
