/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_REGS_H_
#define ASIC_REG_DCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A
 *   (Prototype: MME_TENSOR)
 *****************************************
 */

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_VALID_ELEMENTS_0 0x1C25D8

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_VALID_ELEMENTS_1 0x1C25DC

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_VALID_ELEMENTS_2 0x1C25E0

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_VALID_ELEMENTS_3 0x1C25E4

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_VALID_ELEMENTS_4 0x1C25E8

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_LOOP_STRIDE_0 0x1C25EC

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_LOOP_STRIDE_1 0x1C25F0

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_LOOP_STRIDE_2 0x1C25F4

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_LOOP_STRIDE_3 0x1C25F8

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_LOOP_STRIDE_4 0x1C25FC

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_ROI_SIZE_0 0x1C2600

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_ROI_SIZE_1 0x1C2604

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_ROI_SIZE_2 0x1C2608

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_ROI_SIZE_3 0x1C260C

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_SPATIAL_STRIDES_0 0x1C2610

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_SPATIAL_STRIDES_1 0x1C2614

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_SPATIAL_STRIDES_2 0x1C2618

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_SPATIAL_STRIDES_3 0x1C261C

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_START_OFFSET_0 0x1C2620

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_START_OFFSET_1 0x1C2624

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_START_OFFSET_2 0x1C2628

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_START_OFFSET_3 0x1C262C

#endif /* ASIC_REG_DCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_A_REGS_H_ */
