/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_REGS_H_
#define ASIC_REG_DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_CORE 0xA6B00

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_E2E 0xA6B04

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_HB_SEC 0xA6B08

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_HB_PCIE 0xA6B0C

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_HB_DDR_QOS 0xA6B10

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_HB_DDR_CPAGE 0xA6B14

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_HB_REDUCTION 0xA6B18

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_HB_RSVD 0xA6B1C

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_HB_OVRD_LO 0xA6B20

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_HB_OVRD_HI 0xA6B24

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_LB_COORD 0xA6B30

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_LB_LOCK 0xA6B34

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_LB_RSVD 0xA6B38

#define mmDCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_LB_OVRD 0xA6B3C

#endif /* ASIC_REG_DCORE0_VDEC1_BRDG_CTRL_AXUSER_MSIX_ABNRM_REGS_H_ */
