/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_TPC0_MSTR_IF_CORE_HBW_REGS_H_
#define ASIC_REG_DCORE0_TPC0_MSTR_IF_CORE_HBW_REGS_H_

/*
 *****************************************
 *   DCORE0_TPC0_MSTR_IF_CORE_HBW
 *   (Prototype: MSTR_IF_HBW_CORE)
 *****************************************
 */

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_AXPROT_OVRD 0x6D00

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_RL_WR 0x6D04

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_RL_RD 0x6D08

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_PCI 0x6D0C

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_EXTMEM 0x6D10

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_SRAM 0x6D14

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_REST 0x6D18

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_TOTAL 0x6D1C

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_PCI 0x6D20

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_EXTMEM 0x6D24

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_SRAM 0x6D28

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_REST 0x6D2C

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_TOTAL 0x6D30

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_EN 0x6D34

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_EXTMEM_EN 0x6D38

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_PERM_SEL 0x6D3C

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_0 0x6D40

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_1 0x6D44

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_2 0x6D48

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_3 0x6D4C

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_4 0x6D50

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_5 0x6D54

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_6 0x6D58

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_7 0x6D5C

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_8 0x6D60

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_9 0x6D64

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_10 0x6D68

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_11 0x6D6C

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_12 0x6D70

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_13 0x6D74

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_14 0x6D78

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_15 0x6D7C

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_16 0x6D80

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_17 0x6D84

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_18 0x6D88

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_19 0x6D8C

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_20 0x6D90

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_21 0x6D94

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_22 0x6D98

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_23 0x6D9C

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_24 0x6DA0

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_25 0x6DA4

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_26 0x6DA8

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_27 0x6DAC

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_28 0x6DB0

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_CORE_MODE 0x6DB4

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_EXTMEM_ID_LOC 0x6DB8

#define mmDCORE0_TPC0_MSTR_IF_CORE_HBW_CRDT_ARB_DBG 0x6DBC

#endif /* ASIC_REG_DCORE0_TPC0_MSTR_IF_CORE_HBW_REGS_H_ */
