/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_REGS_H_
#define ASIC_REG_DCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_REGS_H_

/*
 *****************************************
 *   DCORE1_VSI_WRAP_MSTR_IF_CORE_HBW
 *   (Prototype: MSTR_IF_HBW_CORE)
 *****************************************
 */

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_AXPROT_OVRD 0x2BED00

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_RL_WR 0x2BED04

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_RL_RD 0x2BED08

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_PCI 0x2BED0C

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_EXTMEM 0x2BED10

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_SRAM 0x2BED14

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_REST 0x2BED18

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_TOTAL 0x2BED1C

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_PCI 0x2BED20

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_EXTMEM 0x2BED24

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_SRAM 0x2BED28

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_REST 0x2BED2C

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_TOTAL 0x2BED30

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_EN 0x2BED34

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_EXTMEM_EN 0x2BED38

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_PERM_SEL 0x2BED3C

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_0 0x2BED40

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_1 0x2BED44

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_2 0x2BED48

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_3 0x2BED4C

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_4 0x2BED50

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_5 0x2BED54

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_6 0x2BED58

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_7 0x2BED5C

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_8 0x2BED60

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_9 0x2BED64

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_10 0x2BED68

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_11 0x2BED6C

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_12 0x2BED70

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_13 0x2BED74

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_14 0x2BED78

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_15 0x2BED7C

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_16 0x2BED80

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_17 0x2BED84

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_18 0x2BED88

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_19 0x2BED8C

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_20 0x2BED90

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_21 0x2BED94

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_22 0x2BED98

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_23 0x2BED9C

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_24 0x2BEDA0

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_25 0x2BEDA4

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_26 0x2BEDA8

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_27 0x2BEDAC

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_28 0x2BEDB0

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_CORE_MODE 0x2BEDB4

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_EXTMEM_ID_LOC 0x2BEDB8

#define mmDCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_CRDT_ARB_DBG 0x2BEDBC

#endif /* ASIC_REG_DCORE1_VSI_WRAP_MSTR_IF_CORE_HBW_REGS_H_ */
