/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_REGS_H_
#define ASIC_REG_DCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN
 *   (Prototype: MME_TENSOR)
 *****************************************
 */

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_VALID_ELEMENTS_0 0x1C2008

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_VALID_ELEMENTS_1 0x1C200C

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_VALID_ELEMENTS_2 0x1C2010

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_VALID_ELEMENTS_3 0x1C2014

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_VALID_ELEMENTS_4 0x1C2018

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_LOOP_STRIDE_0 0x1C201C

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_LOOP_STRIDE_1 0x1C2020

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_LOOP_STRIDE_2 0x1C2024

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_LOOP_STRIDE_3 0x1C2028

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_LOOP_STRIDE_4 0x1C202C

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_ROI_SIZE_0 0x1C2030

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_ROI_SIZE_1 0x1C2034

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_ROI_SIZE_2 0x1C2038

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_ROI_SIZE_3 0x1C203C

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_SPATIAL_STRIDES_0 0x1C2040

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_SPATIAL_STRIDES_1 0x1C2044

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_SPATIAL_STRIDES_2 0x1C2048

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_SPATIAL_STRIDES_3 0x1C204C

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_START_OFFSET_0 0x1C2050

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_START_OFFSET_1 0x1C2054

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_START_OFFSET_2 0x1C2058

#define mmDCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_START_OFFSET_3 0x1C205C

#endif /* ASIC_REG_DCORE0_MME_CTRL_LO_ARCH_TENSOR_CIN_REGS_H_ */
