/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_REGS_H_
#define ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END
 *   (Prototype: MME_NON_TENSOR_DESCRIPTOR)
 *****************************************
 */

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_MD_TYPE_LOW 0x1C32DC

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_MD_TYPE_HIGH 0x1C32E0

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_SB_REPEAT 0x1C32E4

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_RATE_LIMITER 0x1C32E8

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_USER_DATA 0x1C32EC

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_PERF_EVT_IN 0x1C32F0

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_PERF_EVT_OUT 0x1C32F4

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_PADDING_VALUE_A 0x1C32F8

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_PADDING_VALUE_B 0x1C32FC

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_PADDING_VALUE_C 0x1C3300

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_PCU 0x1C3304

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_POWER_LOOP 0x1C3308

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_WKL 0x1C330C

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_SPARE0 0x1C3310

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_SPARE1 0x1C3314

#define mmDCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_SPARE2 0x1C3318

#endif /* ASIC_REG_DCORE0_MME_CTRL_HI_SHADOW_2_NON_TENSOR_END_REGS_H_ */
