/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_KDMA_CORE_CTX_AXUSER_REGS_H_
#define ASIC_REG_DCORE0_KDMA_CORE_CTX_AXUSER_REGS_H_

/*
 *****************************************
 *   DCORE0_KDMA_CORE_CTX_AXUSER
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_KDMA_CORE_CTX_AXUSER_CORE 0x10A800

#define mmDCORE0_KDMA_CORE_CTX_AXUSER_E2E 0x10A804

#define mmDCORE0_KDMA_CORE_CTX_AXUSER_HB_SEC 0x10A808

#define mmDCORE0_KDMA_CORE_CTX_AXUSER_HB_PCIE 0x10A80C

#define mmDCORE0_KDMA_CORE_CTX_AXUSER_HB_DDR_QOS 0x10A810

#define mmDCORE0_KDMA_CORE_CTX_AXUSER_HB_DDR_CPAGE 0x10A814

#define mmDCORE0_KDMA_CORE_CTX_AXUSER_HB_REDUCTION 0x10A818

#define mmDCORE0_KDMA_CORE_CTX_AXUSER_HB_RSVD 0x10A81C

#define mmDCORE0_KDMA_CORE_CTX_AXUSER_HB_OVRD_LO 0x10A820

#define mmDCORE0_KDMA_CORE_CTX_AXUSER_HB_OVRD_HI 0x10A824

#define mmDCORE0_KDMA_CORE_CTX_AXUSER_LB_COORD 0x10A830

#define mmDCORE0_KDMA_CORE_CTX_AXUSER_LB_LOCK 0x10A834

#define mmDCORE0_KDMA_CORE_CTX_AXUSER_LB_RSVD 0x10A838

#define mmDCORE0_KDMA_CORE_CTX_AXUSER_LB_OVRD 0x10A83C

#endif /* ASIC_REG_DCORE0_KDMA_CORE_CTX_AXUSER_REGS_H_ */
