/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_REGS_H_
#define ASIC_REG_DCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_REGS_H_

/*
 *****************************************
 *   DCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT
 *   (Prototype: MME_TENSOR)
 *****************************************
 */

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_VALID_ELEMENTS_0 0x1C2688

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_VALID_ELEMENTS_1 0x1C268C

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_VALID_ELEMENTS_2 0x1C2690

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_VALID_ELEMENTS_3 0x1C2694

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_VALID_ELEMENTS_4 0x1C2698

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_LOOP_STRIDE_0 0x1C269C

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_LOOP_STRIDE_1 0x1C26A0

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_LOOP_STRIDE_2 0x1C26A4

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_LOOP_STRIDE_3 0x1C26A8

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_LOOP_STRIDE_4 0x1C26AC

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_ROI_SIZE_0 0x1C26B0

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_ROI_SIZE_1 0x1C26B4

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_ROI_SIZE_2 0x1C26B8

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_ROI_SIZE_3 0x1C26BC

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_SPATIAL_STRIDES_0 0x1C26C0

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_SPATIAL_STRIDES_1 0x1C26C4

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_SPATIAL_STRIDES_2 0x1C26C8

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_SPATIAL_STRIDES_3 0x1C26CC

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_START_OFFSET_0 0x1C26D0

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_START_OFFSET_1 0x1C26D4

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_START_OFFSET_2 0x1C26D8

#define mmDCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_START_OFFSET_3 0x1C26DC

#endif /* ASIC_REG_DCORE0_MME_CTRL_LO_SHADOW_0_TENSOR_COUT_REGS_H_ */
