/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_DCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_REGS_H_
#define ASIC_REG_DCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_REGS_H_

/*
 *****************************************
 *   DCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C
 *   (Prototype: AXUSER)
 *****************************************
 */

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_CORE 0xA0900

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_E2E 0xA0904

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_HB_SEC 0xA0908

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_HB_PCIE 0xA090C

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_HB_DDR_QOS 0xA0910

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_HB_DDR_CPAGE 0xA0914

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_HB_REDUCTION 0xA0918

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_HB_RSVD 0xA091C

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_HB_OVRD_LO 0xA0920

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_HB_OVRD_HI 0xA0924

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_LB_COORD 0xA0930

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_LB_LOCK 0xA0934

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_LB_RSVD 0xA0938

#define mmDCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_LB_OVRD 0xA093C

#endif /* ASIC_REG_DCORE0_VDEC0_BRDG_CTRL_AXUSER_MSIX_L2C_REGS_H_ */
