/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PMMU_HBW_MSTR_IF_CORE_HBW_REGS_H_
#define ASIC_REG_PMMU_HBW_MSTR_IF_CORE_HBW_REGS_H_

/*
 *****************************************
 *   PMMU_HBW_MSTR_IF_CORE_HBW
 *   (Prototype: MSTR_IF_HBW_CORE)
 *****************************************
 */

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_AXPROT_OVRD 0x502D00

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_RL_WR 0x502D04

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_RL_RD 0x502D08

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_PCI 0x502D0C

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_EXTMEM 0x502D10

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_SRAM 0x502D14

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_REST 0x502D18

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_TOTAL 0x502D1C

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_PCI 0x502D20

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_EXTMEM 0x502D24

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_SRAM 0x502D28

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_REST 0x502D2C

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_TOTAL 0x502D30

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_EN 0x502D34

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_EXTMEM_EN 0x502D38

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_PERM_SEL 0x502D3C

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_0 0x502D40

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_1 0x502D44

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_2 0x502D48

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_3 0x502D4C

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_4 0x502D50

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_5 0x502D54

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_6 0x502D58

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_7 0x502D5C

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_8 0x502D60

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_9 0x502D64

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_10 0x502D68

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_11 0x502D6C

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_12 0x502D70

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_13 0x502D74

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_14 0x502D78

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_15 0x502D7C

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_16 0x502D80

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_17 0x502D84

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_18 0x502D88

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_19 0x502D8C

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_20 0x502D90

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_21 0x502D94

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_22 0x502D98

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_23 0x502D9C

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_24 0x502DA0

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_25 0x502DA4

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_26 0x502DA8

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_27 0x502DAC

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_28 0x502DB0

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_CORE_MODE 0x502DB4

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_EXTMEM_ID_LOC 0x502DB8

#define mmPMMU_HBW_MSTR_IF_CORE_HBW_CRDT_ARB_DBG 0x502DBC

#endif /* ASIC_REG_PMMU_HBW_MSTR_IF_CORE_HBW_REGS_H_ */
