/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PSOC_MSTR_IF_RR_SHRD_LBW_REGS_H_
#define ASIC_REG_PSOC_MSTR_IF_RR_SHRD_LBW_REGS_H_

/*
 *****************************************
 *   PSOC_MSTR_IF_RR_SHRD_LBW
 *   (Prototype: RANGE_REG_LBW)
 *****************************************
 */

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_SHORT_0 0x47F400

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_SHORT_1 0x47F404

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_SHORT_2 0x47F408

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_SHORT_3 0x47F40C

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_SHORT_4 0x47F410

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_SHORT_5 0x47F414

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_SHORT_6 0x47F418

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_SHORT_7 0x47F41C

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_SHORT_8 0x47F420

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_SHORT_9 0x47F424

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_SHORT_10 0x47F428

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_SHORT_11 0x47F42C

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_SHORT_12 0x47F430

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_SHORT_13 0x47F434

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_SHORT_0 0x47F438

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_SHORT_1 0x47F43C

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_SHORT_2 0x47F440

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_SHORT_3 0x47F444

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_SHORT_4 0x47F448

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_SHORT_5 0x47F44C

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_SHORT_6 0x47F450

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_SHORT_7 0x47F454

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_SHORT_8 0x47F458

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_SHORT_9 0x47F45C

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_SHORT_10 0x47F460

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_SHORT_11 0x47F464

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_SHORT_12 0x47F468

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_SHORT_13 0x47F46C

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_SHORT_0 0x47F470

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_SHORT_1 0x47F474

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_SHORT_2 0x47F478

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_SHORT_3 0x47F47C

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_SHORT_4 0x47F480

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_SHORT_5 0x47F484

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_SHORT_6 0x47F488

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_SHORT_7 0x47F48C

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_SHORT_8 0x47F490

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_SHORT_9 0x47F494

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_SHORT_10 0x47F498

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_SHORT_11 0x47F49C

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_SHORT_12 0x47F4A0

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_SHORT_13 0x47F4A4

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_SHORT_0 0x47F4A8

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_SHORT_1 0x47F4AC

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_SHORT_2 0x47F4B0

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_SHORT_3 0x47F4B4

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_SHORT_4 0x47F4B8

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_SHORT_5 0x47F4BC

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_SHORT_6 0x47F4C0

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_SHORT_7 0x47F4C4

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_SHORT_8 0x47F4C8

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_SHORT_9 0x47F4CC

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_SHORT_10 0x47F4D0

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_SHORT_11 0x47F4D4

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_SHORT_12 0x47F4D8

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_SHORT_13 0x47F4DC

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_0 0x47F4E0

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_1 0x47F4E4

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_2 0x47F4E8

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MIN_3 0x47F4EC

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_0 0x47F4F0

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_1 0x47F4F4

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_2 0x47F4F8

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_RANGE_MAX_3 0x47F4FC

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_0 0x47F500

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_1 0x47F504

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_2 0x47F508

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MIN_3 0x47F50C

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_0 0x47F510

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_1 0x47F514

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_2 0x47F518

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_RANGE_MAX_3 0x47F51C

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_HIT_AW 0x47F520

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_HIT_AW 0x47F524

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_SEC_HIT_AR 0x47F528

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_PRIV_HIT_AR 0x47F52C

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_AW_RAZWI 0x47F530

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_AR_RAZWI 0x47F534

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_AW_RAZWI_XY 0x47F538

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_AR_RAZWI_XY 0x47F53C

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_AW_RAZWI_HAPPENED 0x47F540

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_AR_RAZWI_HAPPENED 0x47F544

#define mmPSOC_MSTR_IF_RR_SHRD_LBW_RAZWI_ERR_RESP 0x47F548

#endif /* ASIC_REG_PSOC_MSTR_IF_RR_SHRD_LBW_REGS_H_ */
