/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PSOC_MSTR_IF_CORE_HBW_REGS_H_
#define ASIC_REG_PSOC_MSTR_IF_CORE_HBW_REGS_H_

/*
 *****************************************
 *   PSOC_MSTR_IF_CORE_HBW
 *   (Prototype: MSTR_IF_HBW_CORE)
 *****************************************
 */

#define mmPSOC_MSTR_IF_CORE_HBW_AXPROT_OVRD 0x47FD00

#define mmPSOC_MSTR_IF_CORE_HBW_RL_WR 0x47FD04

#define mmPSOC_MSTR_IF_CORE_HBW_RL_RD 0x47FD08

#define mmPSOC_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_PCI 0x47FD0C

#define mmPSOC_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_EXTMEM 0x47FD10

#define mmPSOC_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_SRAM 0x47FD14

#define mmPSOC_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_REST 0x47FD18

#define mmPSOC_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_WR_TOTAL 0x47FD1C

#define mmPSOC_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_PCI 0x47FD20

#define mmPSOC_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_EXTMEM 0x47FD24

#define mmPSOC_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_SRAM 0x47FD28

#define mmPSOC_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_REST 0x47FD2C

#define mmPSOC_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_RD_TOTAL 0x47FD30

#define mmPSOC_MSTR_IF_CORE_HBW_MAX_OUTSTANDING_EN 0x47FD34

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_EXTMEM_EN 0x47FD38

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_PERM_SEL 0x47FD3C

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_0 0x47FD40

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_1 0x47FD44

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_2 0x47FD48

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_3 0x47FD4C

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_4 0x47FD50

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_5 0x47FD54

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_6 0x47FD58

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_7 0x47FD5C

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_8 0x47FD60

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_9 0x47FD64

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_10 0x47FD68

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_11 0x47FD6C

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_12 0x47FD70

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_13 0x47FD74

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_14 0x47FD78

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_15 0x47FD7C

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_16 0x47FD80

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_17 0x47FD84

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_18 0x47FD88

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_19 0x47FD8C

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_20 0x47FD90

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_21 0x47FD94

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_22 0x47FD98

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_23 0x47FD9C

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_24 0x47FDA0

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_25 0x47FDA4

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_26 0x47FDA8

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_27 0x47FDAC

#define mmPSOC_MSTR_IF_CORE_HBW_SCRAM_POLY_H3_28 0x47FDB0

#define mmPSOC_MSTR_IF_CORE_HBW_CORE_MODE 0x47FDB4

#define mmPSOC_MSTR_IF_CORE_HBW_EXTMEM_ID_LOC 0x47FDB8

#define mmPSOC_MSTR_IF_CORE_HBW_CRDT_ARB_DBG 0x47FDBC

#endif /* ASIC_REG_PSOC_MSTR_IF_CORE_HBW_REGS_H_ */
