/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2019 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_VENC_VL2C_CTRL_MASKS_H_
#define ASIC_REG_VENC_VL2C_CTRL_MASKS_H_

/*
 *****************************************
 *   VENC_VL2C_CTRL
 *   (Prototype: VL2C_CTRL)
 *****************************************
 */

/* VENC_VL2C_CTRL_CGM_DISABLE */
#define VENC_VL2C_CTRL_CGM_DISABLE_VAL_SHIFT 0
#define VENC_VL2C_CTRL_CGM_DISABLE_VAL_MASK 0x1

/* VENC_VL2C_CTRL_SWREG1_ADDR */
#define VENC_VL2C_CTRL_SWREG1_ADDR_VAL_SHIFT 0
#define VENC_VL2C_CTRL_SWREG1_ADDR_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_CPLQ_HBW_AWPROT */
#define VENC_VL2C_CTRL_CPLQ_HBW_AWPROT_VAL_SHIFT 0
#define VENC_VL2C_CTRL_CPLQ_HBW_AWPROT_VAL_MASK 0x7

/* VENC_VL2C_CTRL_CPLQ_HBW_AWUSER_L */
#define VENC_VL2C_CTRL_CPLQ_HBW_AWUSER_L_VAL_SHIFT 0
#define VENC_VL2C_CTRL_CPLQ_HBW_AWUSER_L_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_CPLQ_HBW_AWUSER_H */
#define VENC_VL2C_CTRL_CPLQ_HBW_AWUSER_H_VAL_SHIFT 0
#define VENC_VL2C_CTRL_CPLQ_HBW_AWUSER_H_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_CPLQ_HBW_AWADDR_L */
#define VENC_VL2C_CTRL_CPLQ_HBW_AWADDR_L_VAL_SHIFT 0
#define VENC_VL2C_CTRL_CPLQ_HBW_AWADDR_L_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_CPLQ_HBW_AWADDR_H */
#define VENC_VL2C_CTRL_CPLQ_HBW_AWADDR_H_VAL_SHIFT 0
#define VENC_VL2C_CTRL_CPLQ_HBW_AWADDR_H_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_MSIX_LBW_AWPROT */
#define VENC_VL2C_CTRL_MSIX_LBW_AWPROT_VAL_SHIFT 0
#define VENC_VL2C_CTRL_MSIX_LBW_AWPROT_VAL_MASK 0x7

/* VENC_VL2C_CTRL_MSIX_LBW_AWUSER */
#define VENC_VL2C_CTRL_MSIX_LBW_AWUSER_VAL_SHIFT 0
#define VENC_VL2C_CTRL_MSIX_LBW_AWUSER_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_MSIX_LBW_AWADDR */
#define VENC_VL2C_CTRL_MSIX_LBW_AWADDR_VAL_SHIFT 0
#define VENC_VL2C_CTRL_MSIX_LBW_AWADDR_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_MSIX_LBW_WDATA */
#define VENC_VL2C_CTRL_MSIX_LBW_WDATA_VAL_SHIFT 0
#define VENC_VL2C_CTRL_MSIX_LBW_WDATA_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_ARC_START_LBW_AWPROT */
#define VENC_VL2C_CTRL_ARC_START_LBW_AWPROT_VAL_SHIFT 0
#define VENC_VL2C_CTRL_ARC_START_LBW_AWPROT_VAL_MASK 0x7

/* VENC_VL2C_CTRL_ARC_START_LBW_AWUSER */
#define VENC_VL2C_CTRL_ARC_START_LBW_AWUSER_VAL_SHIFT 0
#define VENC_VL2C_CTRL_ARC_START_LBW_AWUSER_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_ARC_START_LBW_AWADDR */
#define VENC_VL2C_CTRL_ARC_START_LBW_AWADDR_VAL_SHIFT 0
#define VENC_VL2C_CTRL_ARC_START_LBW_AWADDR_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_ARC_START_LBW_WDATA */
#define VENC_VL2C_CTRL_ARC_START_LBW_WDATA_VAL_SHIFT 0
#define VENC_VL2C_CTRL_ARC_START_LBW_WDATA_VAL_MASK 0xFF

/* VENC_VL2C_CTRL_ARC_FINISH_LBW_AWPROT */
#define VENC_VL2C_CTRL_ARC_FINISH_LBW_AWPROT_VAL_SHIFT 0
#define VENC_VL2C_CTRL_ARC_FINISH_LBW_AWPROT_VAL_MASK 0x7

/* VENC_VL2C_CTRL_ARC_FINISH_LBW_AWUSER */
#define VENC_VL2C_CTRL_ARC_FINISH_LBW_AWUSER_VAL_SHIFT 0
#define VENC_VL2C_CTRL_ARC_FINISH_LBW_AWUSER_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_ARC_FINISH_LBW_AWADDR */
#define VENC_VL2C_CTRL_ARC_FINISH_LBW_AWADDR_VAL_SHIFT 0
#define VENC_VL2C_CTRL_ARC_FINISH_LBW_AWADDR_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_ARC_FINISH_LBW_WDATA */
#define VENC_VL2C_CTRL_ARC_FINISH_LBW_WDATA_VAL_SHIFT 0
#define VENC_VL2C_CTRL_ARC_FINISH_LBW_WDATA_VAL_MASK 0xFF

/* VENC_VL2C_CTRL_MSIX_INTR_MASK */
#define VENC_VL2C_CTRL_MSIX_INTR_MASK_VAL_SHIFT 0
#define VENC_VL2C_CTRL_MSIX_INTR_MASK_VAL_MASK 0x1

/* VENC_VL2C_CTRL_DEC_GIC_INTR_MASK */
#define VENC_VL2C_CTRL_DEC_GIC_INTR_MASK_VAL_SHIFT 0
#define VENC_VL2C_CTRL_DEC_GIC_INTR_MASK_VAL_MASK 0x1

/* VENC_VL2C_CTRL_L2C_GIC_INTR_MASK */
#define VENC_VL2C_CTRL_L2C_GIC_INTR_MASK_VAL_SHIFT 0
#define VENC_VL2C_CTRL_L2C_GIC_INTR_MASK_VAL_MASK 0x1

/* VENC_VL2C_CTRL_ARC_MSG_MASK */
#define VENC_VL2C_CTRL_ARC_MSG_MASK_VAL_SHIFT 0
#define VENC_VL2C_CTRL_ARC_MSG_MASK_VAL_MASK 0x1

/* VENC_VL2C_CTRL_GRACEFUL */
#define VENC_VL2C_CTRL_GRACEFUL_STOP_SHIFT 0
#define VENC_VL2C_CTRL_GRACEFUL_STOP_MASK 0x1
#define VENC_VL2C_CTRL_GRACEFUL_PEND_SHIFT 4
#define VENC_VL2C_CTRL_GRACEFUL_PEND_MASK 0x10

/* VENC_VL2C_CTRL_CAUSE_SEI_INTR */
#define VENC_VL2C_CTRL_CAUSE_SEI_INTR_HBW_ERR_RSP_SHIFT 0
#define VENC_VL2C_CTRL_CAUSE_SEI_INTR_HBW_ERR_RSP_MASK 0x1
#define VENC_VL2C_CTRL_CAUSE_SEI_INTR_MSIX_LBW_ERR_RSP_SHIFT 1
#define VENC_VL2C_CTRL_CAUSE_SEI_INTR_MSIX_LBW_ERR_RSP_MASK 0x2

/* VENC_VL2C_CTRL_CAUSE_SPI_INTR */
#define VENC_VL2C_CTRL_CAUSE_SPI_INTR_DEC_INTR_SHIFT 0
#define VENC_VL2C_CTRL_CAUSE_SPI_INTR_DEC_INTR_MASK 0x1
#define VENC_VL2C_CTRL_CAUSE_SPI_INTR_L2C_INTR_SHIFT 1
#define VENC_VL2C_CTRL_CAUSE_SPI_INTR_L2C_INTR_MASK 0x2

/* VENC_VL2C_CTRL_CAUSE_RES_SERR_INTR */
#define VENC_VL2C_CTRL_CAUSE_RES_SERR_INTR_PART0_SHIFT 0
#define VENC_VL2C_CTRL_CAUSE_RES_SERR_INTR_PART0_MASK 0x1
#define VENC_VL2C_CTRL_CAUSE_RES_SERR_INTR_PART1_SHIFT 1
#define VENC_VL2C_CTRL_CAUSE_RES_SERR_INTR_PART1_MASK 0x2
#define VENC_VL2C_CTRL_CAUSE_RES_SERR_INTR_PART2_SHIFT 2
#define VENC_VL2C_CTRL_CAUSE_RES_SERR_INTR_PART2_MASK 0x4

/* VENC_VL2C_CTRL_CAUSE_RES_DERR_INTR */
#define VENC_VL2C_CTRL_CAUSE_RES_DERR_INTR_PART0_SHIFT 0
#define VENC_VL2C_CTRL_CAUSE_RES_DERR_INTR_PART0_MASK 0x1
#define VENC_VL2C_CTRL_CAUSE_RES_DERR_INTR_PART1_SHIFT 1
#define VENC_VL2C_CTRL_CAUSE_RES_DERR_INTR_PART1_MASK 0x2
#define VENC_VL2C_CTRL_CAUSE_RES_DERR_INTR_PART2_SHIFT 21
#define VENC_VL2C_CTRL_CAUSE_RES_DERR_INTR_PART2_MASK 0x200000

/* VENC_VL2C_CTRL_DEC_HBW_AWUSER_L */
#define VENC_VL2C_CTRL_DEC_HBW_AWUSER_L_VAL_SHIFT 0
#define VENC_VL2C_CTRL_DEC_HBW_AWUSER_L_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_DEC_HBW_AWUSER_H */
#define VENC_VL2C_CTRL_DEC_HBW_AWUSER_H_VAL_SHIFT 0
#define VENC_VL2C_CTRL_DEC_HBW_AWUSER_H_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_DEC_HBW_ARUSER_L */
#define VENC_VL2C_CTRL_DEC_HBW_ARUSER_L_VAL_SHIFT 0
#define VENC_VL2C_CTRL_DEC_HBW_ARUSER_L_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_DEC_HBW_ARUSER_H */
#define VENC_VL2C_CTRL_DEC_HBW_ARUSER_H_VAL_SHIFT 0
#define VENC_VL2C_CTRL_DEC_HBW_ARUSER_H_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_DEC_HBW_AWPROT */
#define VENC_VL2C_CTRL_DEC_HBW_AWPROT_VAL_SHIFT 0
#define VENC_VL2C_CTRL_DEC_HBW_AWPROT_VAL_MASK 0x7

/* VENC_VL2C_CTRL_DEC_HBW_ARPROT */
#define VENC_VL2C_CTRL_DEC_HBW_ARPROT_VAL_SHIFT 0
#define VENC_VL2C_CTRL_DEC_HBW_ARPROT_VAL_MASK 0x7

/* VENC_VL2C_CTRL_FT_CH1_SEL */
#define VENC_VL2C_CTRL_FT_CH1_SEL_VAL_SHIFT 0
#define VENC_VL2C_CTRL_FT_CH1_SEL_VAL_MASK 0x3

/* VENC_VL2C_CTRL_DEC_FREE_RUN_CNT_L */
#define VENC_VL2C_CTRL_DEC_FREE_RUN_CNT_L_VAL_SHIFT 0
#define VENC_VL2C_CTRL_DEC_FREE_RUN_CNT_L_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_DEC_FREE_RUN_CNT_H */
#define VENC_VL2C_CTRL_DEC_FREE_RUN_CNT_H_VAL_SHIFT 0
#define VENC_VL2C_CTRL_DEC_FREE_RUN_CNT_H_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_DEC_FREE_RUN_SET_VALUE_L */
#define VENC_VL2C_CTRL_DEC_FREE_RUN_SET_VALUE_L_IND_SHIFT 0
#define VENC_VL2C_CTRL_DEC_FREE_RUN_SET_VALUE_L_IND_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_DEC_FREE_RUN_SET_VALUE_H */
#define VENC_VL2C_CTRL_DEC_FREE_RUN_SET_VALUE_H_IND_SHIFT 0
#define VENC_VL2C_CTRL_DEC_FREE_RUN_SET_VALUE_H_IND_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_DEC_BUSY_CNT_L */
#define VENC_VL2C_CTRL_DEC_BUSY_CNT_L_VAL_SHIFT 0
#define VENC_VL2C_CTRL_DEC_BUSY_CNT_L_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_DEC_BUSY_CNT_H */
#define VENC_VL2C_CTRL_DEC_BUSY_CNT_H_VAL_SHIFT 0
#define VENC_VL2C_CTRL_DEC_BUSY_CNT_H_VAL_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_DEC_BUSY_SET_VALUE_L */
#define VENC_VL2C_CTRL_DEC_BUSY_SET_VALUE_L_IND_SHIFT 0
#define VENC_VL2C_CTRL_DEC_BUSY_SET_VALUE_L_IND_MASK 0xFFFFFFFF

/* VENC_VL2C_CTRL_DEC_BUSY_SET_VALUE_H */
#define VENC_VL2C_CTRL_DEC_BUSY_SET_VALUE_H_IND_SHIFT 0
#define VENC_VL2C_CTRL_DEC_BUSY_SET_VALUE_H_IND_MASK 0xFFFFFFFF

#endif /* ASIC_REG_VENC_VL2C_CTRL_MASKS_H_ */
